base_model: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
# optionally might have model_type or tokenizer_type
# model_type: AutoModelForCausalLM
# tokenizer_type: AutoTokenizer
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

deepspeed: deepspeed_configs/zero3_bf16_cpuoffload_params.json

datasets:
  - path: /home/riyaza/eval_improver/improver/train/data/train/informal_small_training.jsonl
    type: alpaca
dataset_prepared_path:
val_set_size: 0.05
output_dir: /data/user_data/riyaza/saved_models/Q14_conjecturer_inf

sequence_len: 8192
sample_packing: false
pad_to_sequence_len:

wandb_project: "Q14_conjecturer_inf"
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00005

train_on_inputs: false
group_by_length: true
bf16: auto
fp16: 
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint: 
local_rank:
logging_steps: 2
xformers_attention:
flash_attention:

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
eval_max_new_tokens: 512
saves_per_epoch: 1
debug:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens: