metric: length
dataset_path: "/home/riyaza/eval_improver/improver/train/data/train/final_dataset.json"
prompt_id: final_final_train
model: Qwen/Qwen2.5-Math-7B
split: train
cpus: 12
gpus: 8
n: 16
annotation: false
context: 0
rag: 0
examples: 0
runID: ablation_model_base_Q7
training_data: true