metric: length
dataset_path: "/home/riyaza/eval_improver/improver/train/data/train/final_dataset.json"
prompt_id: final_final_test
model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
split: test
cpus: 12
gpus: 8
n: 16
annotation: false
context: 0
rag: 0
examples: 0
run_id: ablation_model_base_Q7R1
training_data: true