dataset_path: /home/riyaza/eval_improver/improver/train/data/train/final_dataset.json
prompts_id: final_final_train
kg_id: final_final_knowledge_graph
split: train
embedding_model: Qwen/Qwen3-Embedding-0.6B
k: 40
threshold: 0.35
heuristic_model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
cpus: 25
gpus: 1
n: 3
run_inference: true
augment_DB: true
training_data: true
neo4j_uri: bolt://localhost:7687
neo4j_user: neo4j
neo4j_pass: 12345678