dataset_path: /home/riyaza/eval_improver/improver/train/data/train/final_dataset.json
prompts_id: final_final_train
split: train
cpus: 25
model: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
gpus: 6
informalize: true