dataset_path: /home/riyaza/eval_improver/improver/train/data/train/final_dataset_fixed.json
prompts_id: final_final_test
split: test
cpus: 25
model: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
gpus: 6
informalize: true