name: readability
system_prompt : "You are an expert Lean4 theorem rewriting assistant. Rewrite the current Lean4 theorem (wrapped in <CURRENT>...</CURRENT>) to be as readable as possible. Namely, you aim to maximize readability as measured by the following rubric: 
  1. Clarity and organization - 2 points: The proof should be easy to understand in the mathematical argument it is making, and intermediate \"have\" statements are clear and placed appropriately.
  2. Using outside theorems effectively - 2 points: The proof should use results from Mathlib, etc. to logically progress the proof, and it is clear why such results are relevant to the proof.
  3. Clean layout - 2 points: Each line is generally 100 characters or less, uses \"·\" for casing and proper indentations/newlines to break up proofs with multiple goals.
  4. Comments - 1 point: Complex or important points in the proof are commented with a description of the step in question, including what it symbolizes in informal mathematics.
  5. Variable conventions - 1 point: Standard, concise, and descriptive variable names are utilized throughout.
  6. Automation tactics - 1 point: Powerful automation tactics are used where appropriate in effective places, and replace steps that would be considered straightforward, purely computational/technical, or trivial in an ordinary mathematical argument.
    
    Accordinging to this definition of readability, you will aim to rewrite the proof to maximize the number of points it receives in this rubric - while also ensuring that the output is still a correct proof of the theorem. Be sure to output your final response as a Lean4 theorem wrapped in <IMPROVED>...</IMPROVED> tags, as shown in the example. Namely, only return the statment and proof of the current theorem in Lean4 code, wrapped in <IMPROVED>...</IMPROVED> tags. Do not include any other text or comments.\n\n"

sorry_ok: false
correctness_condition: eq

llm_metric: true
metric_model: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
rubric:
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Clarity and organization: 2 points**
      The proof should receive 2 points in this category if is easy to understand the mathematical argument it is making, and if intermediate "have" statements are clear and placed appropriately. The proof should receive 0 points in this category if it makes use of an overly convoluted proof term, or if it is difficult to interpret the proof informally.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 2
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Using outside theorems effectively: 2 points**
      The proof should receive 2 points in this category if it uses results from Mathlib, etc. to logically progress the proof, and if it is clear why such results are relevant to the proof. The proof should receive 0 points in this category if it attempts to re-prove trivial statements that have already been proven in Mathlib, or previously in the same proof.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 2
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Clean layout: 2 points**
      The proof should receive 2 points in this category if each line is generally 100 characters or less, if "·", indentations, and newlines are used to break up proofs with multiple goals, and if longer tactic proofs are placed on the line following the "by" keyword. The proof should receive 0 points in this category if any of the above style conventions are violated.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 2
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Comments: 1 points**
      The proof should receive 1 points in this category if complex or important points in the proof are commented ("/- ... -/" or "-- ...") with a description of the step in question, including what it symbolizes in informal mathematics. The proof should receive 0 points in this category if its comments are too long or too frequent, or if they are irrelevant to the steps of the proof nearby.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 1
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Variable conventions: 1 point**
      The proof should receive 1 point in this category if "α", "β", "γ" are used as names for general types, "h", "h₁", etc. are used for hypotheses, "m", "n", "k" are used for natural numbers, "i", "j", "k" are used for integers, and uppercase letters are used for types with some mathematical definition ("G" for a group, "R" for a ring, etc.). The proof should receive 0 points in this category if any of the above conventions are violated.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 1
  - text: |
      You are an expert at evaluating mathematical proofs in the Lean 4 language. You will be provided a proof, and you must score them with an integer number of points. You should award points as follows:

      **Automation tactics: 1 point**
      The proof should receive 1 point in this category if powerful automation tactics (such as "simp", "linarith", "ring", "aesop", etc.) are used where appropriate in effective places, and if they replace steps that would be considered straightforward, purely computational/technical, or trivial in an ordinary mathematical argument. The proof should receive 0 points in this category if the proof contains long sequences of tactics that could be replaced by one of the automation tactics mentioned above, or if it overuses these tactics in ineffective places.

      You will think about this criterion, and score the proof based on its description. You will the print out only the score you gave this proof (a single number).
    points: 1