metric: length
dataset_path: "/home/riyaza/eval_improver/improver/train/data/train/final_dataset_fixed.json"
prompt_id: really_final_rag_test2
model: o4-mini
split: test
cpus: 64
gpus: 1
n: 16
annotation: false
context: 5
rag: 5
examples: 4
run_id: o4_mini_baseline_all
training_data: true

azure: true
server_concurrency: 512
server_rate_limit: 1000

nccl_p2p: false
num_blocks: 512

engine_cpu_resources: 1
engine_gpu_resources: 1
concurrency: 8
tensor_parallel_size: 1

enable_chunked_prefill: true

max_model_len: 32768
# max_num_batched_tokens: 24576
max_num_batched_tokens: 32768
max_concurrent_batches: 72
batch_size: 10
truncate_prompt_tokens: 31744
max_tokens: 10000
