metric: length
dataset_path: "/home/riyaza/eval_improver/improver/train/data/train/final_dataset_fixed.json"
prompt_id: final_final_test
model: deepseek-ai/DeepSeek-Prover-V2-7B
split: test
cpus: 64
gpus: 7
n: 32
annotation: false
context: 0
rag: -1
examples: 0
run_id: rag_len
training_data: true