metric: readability2
dataset_path: "/home/riyaza/eval_improver/improver/train/data/train/final_dataset_fixed.json"
prompt_id: final_final_test
model: deepseek-ai/DeepSeek-Prover-V2-7B
split: test
cpus: 64
gpus: 7
n: 3
annotation: false
context: 0
rag: 0
examples: 0
run_id: read_model_base_DS2_new
training_data: true