/-- Given a ring `A`, this structure involves a family of elements (indexed by a type `R`)
in a free module `G →₀ A`. This allows to define an `A`-module by generators and relations,
see `Relations.Quotient`. -/
@[nolint checkUnivs]
structure Relations where
  /-- the index type for generators -/
  G : Type w₀
  /-- the index type for relations -/
  R : Type w₁
  /-- the coefficients of the linear relations that are expected between the generators -/
  relation (r : R) : G →₀ A


/-- The module that is presented by generators and relations given by `relations : Relations A`.
This is the quotient of the free `A`-module on `relations.G` by the submodule generated by
the given relations. -/
def Quotient := (relations.G →₀ A) ⧸ Submodule.span A (Set.range relations.relation)


noncomputable instance : AddCommGroup relations.Quotient := by
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    ⊢ AddCommGroup relations.Quotient
  -/
  dsimp only [Quotient]; infer_instance
                         /-
                           🎉 no goals
                         -/


noncomputable instance : Module A relations.Quotient := by
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    ⊢ Module A relations.Quotient
  -/
  dsimp only [Quotient]; infer_instance
                         /-
                           🎉 no goals
                         -/


/-- The canonical (surjective) linear map `(relations.G →₀ A) →ₗ[A] relations.Quotient`. -/
def toQuotient : (relations.G →₀ A) →ₗ[A] relations.Quotient := Submodule.mkQ _


variable {relations} in
@[ext]
lemma Quotient.linearMap_ext {M : Type v} [AddCommGroup M] [Module A M]
    {f f' : relations.Quotient →ₗ[A] M}
    (h : ∀ (g : relations.G), f (relations.toQuotient (Finsupp.single g 1)) =
      f' (relations.toQuotient (Finsupp.single g 1))) :
    f = f' :=
  Submodule.linearMap_qext _ (Finsupp.lhom_ext' (fun g ↦ LinearMap.ext_ring (h g)))


lemma surjective_toQuotient : Function.Surjective relations.toQuotient :=
  Submodule.mkQ_surjective _


lemma ker_toQuotient :
    LinearMap.ker relations.toQuotient = Submodule.span A (Set.range relations.relation) :=
  Submodule.ker_mkQ _


@[simp]
lemma toQuotient_relation (r : relations.R) :
    relations.toQuotient (relations.relation r) = 0 := by
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    r : relations.R
    ⊢ Eq (relations.toQuotient (relations.relation r)) 0
  -/
  dsimp only [toQuotient, Quotient]
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    r : relations.R
    ⊢ Eq ((Submodule.span A (Set.range relations.relation)).mkQ (relations.relatio …
  -/
  rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    r : relations.R
    ⊢ Membership.mem (Submodule.span A (Set.range relations.relation)) (relations. …
  -/
  exact Submodule.subset_span (by simp)
  /-
    🎉 no goals
  -/


/-- The linear map `(relations.R →₀ A) →ₗ[A] (relations.G →₀ A)` corresponding to the relations
given by `relations : Relations A`. -/
noncomputable def map : (relations.R →₀ A) →ₗ[A] (relations.G →₀ A) :=
  Finsupp.linearCombination _ relations.relation


@[simp]
lemma map_single (r : relations.R) :
    relations.map (Finsupp.single r 1) = relations.relation r := by
  /-
    A : Type u
    inst✝ : Ring A
    relations : Module.Relations A
    r : relations.R
    ⊢ Eq (relations.map (Finsupp.single r 1)) (relations.relation r)
  -/
  simp [map]
  /-
    🎉 no goals
  -/


@[simp]
lemma range_map :
    LinearMap.range relations.map = Submodule.span A (Set.range relations.relation) :=
  Finsupp.range_linearCombination _


@[simp]
                                                                         /-
                                                                           A : Type u
                                                                           inst✝ : Ring A
                                                                           relations : Module.Relations A
                                                                           ⊢ Eq (relations.toQuotient.comp relations.map) 0
                                                                         -/
lemma toQuotient_map : relations.toQuotient.comp relations.map = 0 := by aesop
                                                                         /-
                                                                           🎉 no goals
                                                                         -/


@[simp]
lemma toQuotient_map_apply (x : relations.R →₀ A) :
    relations.toQuotient (relations.map x) = 0 :=
  DFunLike.congr_fun relations.toQuotient_map x


/-- The type of solutions in a module `M` of the equations given by `relations : Relations A`. -/
@[ext]
structure Solution where
  /-- the image in `M` of each variable -/
  var (g : relations.G) : M
  linearCombination_var_relation (r : relations.R) :
    Finsupp.linearCombination _ var (relations.relation r) = 0


/-- Given `relations : Relations A` and a solution in `relations.Solution M`, this is
the linear map `(relations.G →₀ A) →ₗ[A] M` canonically associated to the solution. -/
noncomputable def π : (relations.G →₀ A) →ₗ[A] M := Finsupp.linearCombination _ solution.var


@[simp]
lemma π_single (g : relations.G) :
                                                           /-
                                                             A : Type u
                                                             inst✝² : Ring A
                                                             relations : Module.Relations A
                                                             M : Type v
                                                             inst✝¹ : AddCommGroup M
                                                             inst✝ : Module A M
                                                             solution : relations.Solution M
                                                             g : relations.G
                                                             ⊢ Eq (solution.π (Finsupp.single g 1)) (solution.var g)
                                                           -/
    solution.π (Finsupp.single g 1) = solution.var g := by simp [π]
                                                           /-
                                                             🎉 no goals
                                                           -/


@[simp]
lemma π_relation (r : relations.R) : solution.π (relations.relation r) = 0 :=
  solution.linearCombination_var_relation r


@[simp]
                                                           /-
                                                             A : Type u
                                                             inst✝² : Ring A
                                                             relations : Module.Relations A
                                                             M : Type v
                                                             inst✝¹ : AddCommGroup M
                                                             inst✝ : Module A M
                                                             solution : relations.Solution M
                                                             ⊢ Eq (solution.π.comp relations.map) 0
                                                           -/
lemma π_comp_map : solution.π.comp relations.map = 0 := by aesop
                                                           /-
                                                             🎉 no goals
                                                           -/


@[simp]
lemma π_comp_map_apply (x : relations.R →₀ A) : solution.π (relations.map x) = 0 := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    x : Finsupp relations.R A
    ⊢ Eq (solution.π (relations.map x)) 0
  -/
  change solution.π.comp relations.map x = 0
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    x : Finsupp relations.R A
    ⊢ Eq ((solution.π.comp relations.map) x) 0
  -/
  rw [π_comp_map, LinearMap.zero_apply]
  /-
    🎉 no goals
  -/


lemma range_π : LinearMap.range solution.π = Submodule.span A (Set.range solution.var) :=
  Finsupp.range_linearCombination _


lemma span_relation_le_ker_π :
    Submodule.span A (Set.range relations.relation) ≤ LinearMap.ker solution.π := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    ⊢ LE.le (Submodule.span A (Set.range relations.relation)) (LinearMap.ker solut …
  -/
  rw [Submodule.span_le]
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    ⊢ HasSubset.Subset (Set.range relations.relation) ↑(LinearMap.ker solution.π)
  -/
  rintro _ ⟨r, rfl⟩
  /-
    case intro
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    r : relations.R
    ⊢ Membership.mem (↑(LinearMap.ker solution.π)) (relations.relation r)
  -/
  simp only [SetLike.mem_coe, LinearMap.mem_ker, π_relation]
  /-
    🎉 no goals
  -/


/-- Given `relations : Relations A` and `solution : relations.Solution M`, this is
the canonical linear map `relations.Quotient →ₗ[A] M` from the module. -/
noncomputable def fromQuotient : relations.Quotient →ₗ[A] M :=
  Submodule.liftQ _ solution.π solution.span_relation_le_ker_π


@[simp]
lemma fromQuotient_comp_toQuotient :
    solution.fromQuotient.comp relations.toQuotient = solution.π := rfl


@[simp]
lemma fromQuotient_toQuotient (x : relations.G →₀ A) :
    solution.fromQuotient (relations.toQuotient x) = solution.π x := rfl


/-- The image of a solution to `relations : Relation A` by a linear map `M →ₗ[A] N`. -/
@[simps]
def postcomp : relations.Solution N where
  var g := f (solution.var g)
  linearCombination_var_relation r := by
    /-
      A : Type u
      inst✝⁴ : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝³ : AddCommGroup M
      inst✝² : Module A M
      solution : relations.Solution M
      N : Type v'
      inst✝¹ : AddCommGroup N
      inst✝ : Module A N
      f : LinearMap (RingHom.id A) M N
      r : relations.R
      ⊢ Eq ((Finsupp.linearCombination A fun g => f (solution.var g)) (relations.rel …
    -/
    have : Finsupp.linearCombination _ (fun g ↦ f (solution.var g)) = f.comp solution.π := by aesop
    /-
      A : Type u
      inst✝⁴ : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝³ : AddCommGroup M
      inst✝² : Module A M
      solution : relations.Solution M
      N : Type v'
      inst✝¹ : AddCommGroup N
      inst✝ : Module A N
      f : LinearMap (RingHom.id A) M N
      r : relations.R
      this : Eq (Finsupp.linearCombination A fun g => f (solution.var g)) (f.comp so …
      ⊢ Eq ((Finsupp.linearCombination A fun g => f (solution.var g)) (relations.rel …
    -/
    simp [this]
    /-
      🎉 no goals
    -/


@[simp]
lemma postcomp_comp {N' : Type v''} [AddCommGroup N'] [Module A N'] (g : N →ₗ[A] N') :
    solution.postcomp (g.comp f) = (solution.postcomp f).postcomp g := rfl


@[simp]
lemma postcomp_id : solution.postcomp LinearMap.id = solution := rfl


lemma congr_var {solution' : relations.Solution M} (h : solution = solution') (g : relations.G) :
                                           /-
                                             A : Type u
                                             inst✝² : Ring A
                                             relations : Module.Relations A
                                             M : Type v
                                             inst✝¹ : AddCommGroup M
                                             inst✝ : Module A M
                                             solution solution' : relations.Solution M
                                             h : Eq solution solution'
                                             g : relations.G
                                             ⊢ Eq (solution.var g) (solution'.var g)
                                           -/
    solution.var g = solution'.var g := by rw [h]
                                           /-
                                             🎉 no goals
                                           -/


lemma congr_postcomp {solution' : relations.Solution M} (h : solution = solution')
                                                                       /-
                                                                         A : Type u
                                                                         inst✝⁴ : Ring A
                                                                         relations : Module.Relations A
                                                                         M : Type v
                                                                         inst✝³ : AddCommGroup M
                                                                         inst✝² : Module A M
                                                                         solution : relations.Solution M
                                                                         N : Type v'
                                                                         inst✝¹ : AddCommGroup N
                                                                         inst✝ : Module A N
                                                                         solution' : relations.Solution M
                                                                         h : Eq solution solution'
                                                                         f : LinearMap (RingHom.id A) M N
                                                                         ⊢ Eq (solution.postcomp f) (solution'.postcomp f)
                                                                       -/
    (f : M →ₗ[A] N) : solution.postcomp f = solution'.postcomp f := by rw [h]
                                                                       /-
                                                                         🎉 no goals
                                                                       -/


/-- Given `relations : Relations A` and an `A`-module `M`, this is a constructor
for `relations.Solution M` for which the data is given as
a linear map `π : (relations.G →₀ A) →ₗ[A] M`. (See also `ofπ'` for an alternate
vanishing criterion.) -/
@[simps (config := .lemmasOnly)]
noncomputable def ofπ : relations.Solution M where
  var g := π (Finsupp.single g 1)
  linearCombination_var_relation r := by
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
      hπ : ∀ (r : relations.R), Eq (π (relations.relation r)) 0
      r : relations.R
      ⊢ Eq ((Finsupp.linearCombination A fun g => π (Finsupp.single g 1)) (relations …
    -/
    have : π = Finsupp.linearCombination _ (fun g ↦ π (Finsupp.single g 1)) := by ext; simp
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
      hπ : ∀ (r : relations.R), Eq (π (relations.relation r)) 0
      r : relations.R
      this : Eq π (Finsupp.linearCombination A fun g => π (Finsupp.single g 1))
      ⊢ Eq ((Finsupp.linearCombination A fun g => π (Finsupp.single g 1)) (relations …
    -/
    rw [← this]
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
      hπ : ∀ (r : relations.R), Eq (π (relations.relation r)) 0
      r : relations.R
      this : Eq π (Finsupp.linearCombination A fun g => π (Finsupp.single g 1))
      ⊢ Eq (π (relations.relation r)) 0
    -/
    exact hπ r
    /-
      🎉 no goals
    -/


@[simp]
                                     /-
                                       A : Type u
                                       inst✝² : Ring A
                                       relations : Module.Relations A
                                       M : Type v
                                       inst✝¹ : AddCommGroup M
                                       inst✝ : Module A M
                                       π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
                                       hπ : ∀ (r : relations.R), Eq (π (relations.relation r)) 0
                                       ⊢ Eq (Module.Relations.Solution.ofπ π hπ).π π
                                     -/
lemma ofπ_π : (ofπ π hπ).π = π := by ext; simp [ofπ]
                                          /-
                                            🎉 no goals
                                          -/


/-- Variant of `ofπ` where the vanishing condition is expressed in terms
of a composition of linear maps. -/
@[simps! (config := .lemmasOnly)]
noncomputable def ofπ' : relations.Solution M :=
  ofπ π (fun r ↦ by
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
      hπ : Eq (π.comp relations.map) 0
      r : relations.R
      ⊢ Eq (π (relations.relation r)) 0
    -/
    simpa using DFunLike.congr_fun hπ (Finsupp.single r 1))
    /-
      🎉 no goals
    -/


@[simp]
                                       /-
                                         A : Type u
                                         inst✝² : Ring A
                                         relations : Module.Relations A
                                         M : Type v
                                         inst✝¹ : AddCommGroup M
                                         inst✝ : Module A M
                                         π : LinearMap (RingHom.id A) (Finsupp relations.G A) M
                                         hπ : Eq (π.comp relations.map) 0
                                         ⊢ Eq (Module.Relations.Solution.ofπ' π hπ).π π
                                       -/
lemma ofπ'_π : (ofπ' π hπ).π = π := by simp [ofπ']
                                       /-
                                         🎉 no goals
                                       -/


lemma injective_fromQuotient_iff_ker_π_eq_span :
    Function.Injective solution.fromQuotient ↔
      LinearMap.ker solution.π = Submodule.span A (Set.range relations.relation) := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    ⊢ Iff (Function.Injective ⇑solution.fromQuotient) (Eq (LinearMap.ker solution. …
  -/
  constructor
    /-
      case mp
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      ⊢ Function.Injective ⇑solution.fromQuotient → Eq (LinearMap.ker solution.π) (S …
    -/
  · intro h
    rw [← ker_toQuotient, ← fromQuotient_comp_toQuotient, LinearMap.ker_comp,
      LinearMap.ker_eq_bot.2 h, Submodule.comap_bot]
    /-
      case mpr
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      ⊢ Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relatio …
    -/
  · intro h
    /-
      case mpr
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      ⊢ Function.Injective ⇑solution.fromQuotient
    -/
    rw [← LinearMap.ker_eq_bot, eq_bot_iff]
    /-
      case mpr
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      ⊢ LE.le (LinearMap.ker solution.fromQuotient) Bot.bot
    -/
    intro x hx
    /-
      case mpr
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      x : relations.Quotient
      hx : Membership.mem (LinearMap.ker solution.fromQuotient) x
      ⊢ Membership.mem Bot.bot x
    -/
    obtain ⟨x, rfl⟩ := relations.surjective_toQuotient x
    replace hx : x ∈ LinearMap.ker solution.π := by
      simpa only [LinearMap.mem_ker, fromQuotient_toQuotient] using hx
    /-
      case mpr.intro
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      x : Finsupp relations.G A
      hx : Membership.mem (LinearMap.ker solution.π) x
      ⊢ Membership.mem Bot.bot (relations.toQuotient x)
    -/
    rw [h, ← range_map] at hx
    /-
      case mpr.intro
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      x : Finsupp relations.G A
      hx : Membership.mem (LinearMap.range relations.map) x
      ⊢ Membership.mem Bot.bot (relations.toQuotient x)
    -/
    obtain ⟨x, rfl⟩ := hx
    /-
      case mpr.intro.intro
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relat …
      x : Finsupp relations.R A
      ⊢ Membership.mem Bot.bot (relations.toQuotient (relations.map x))
    -/
    simp only [toQuotient_map_apply, Submodule.zero_mem]
    /-
      🎉 no goals
    -/


lemma surjective_fromQuotient_iff_surjective_π :
    Function.Surjective solution.fromQuotient ↔ Function.Surjective solution.π := by
  simpa only [← fromQuotient_comp_toQuotient] using
    (Function.Surjective.of_comp_iff (f := solution.fromQuotient)
      relations.surjective_toQuotient).symm


lemma surjective_π_iff_span_eq_top :
    Function.Surjective solution.π ↔
      Submodule.span A (Set.range solution.var) = ⊤ := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    ⊢ Iff (Function.Surjective ⇑solution.π) (Eq (Submodule.span A (Set.range solut …
  -/
  rw [← LinearMap.range_eq_top, range_π]
  /-
    🎉 no goals
  -/


/-- Given `relations : Relations A`, an `A`-module `M` and `solution : relations.Solution M`,
this property asserts that `solution` gives a presentation of `M` by generators and relations. -/
structure IsPresentation (solution : relations.Solution M) : Prop where
  bijective : Function.Bijective solution.fromQuotient


/-- When `M` admits a presentation by generators and relations given
by `solution : relations.Solutions M`, this is the associated linear equivalence
`relations.Quotient ≃ₗ[A] M`. -/
noncomputable def linearEquiv : relations.Quotient ≃ₗ[A] M := LinearEquiv.ofBijective _ h.bijective


@[simp]
lemma linearEquiv_apply (x : relations.Quotient) :
    h.linearEquiv x = solution.fromQuotient x := rfl


@[simp]
lemma linearEquiv_symm_var (g : relations.G) :
    h.linearEquiv.symm (solution.var g) = relations.toQuotient (Finsupp.single g 1) :=
                              /-
                                A : Type u
                                inst✝² : Ring A
                                relations : Module.Relations A
                                M : Type v
                                inst✝¹ : AddCommGroup M
                                inst✝ : Module A M
                                solution : relations.Solution M
                                h : solution.IsPresentation
                                g : relations.G
                                ⊢ Eq (h.linearEquiv (h.linearEquiv.symm (solution.var g))) (h.linearEquiv (rel …
                              -/
  h.linearEquiv.injective (by simp)
                              /-
                                🎉 no goals
                              -/


lemma surjective_π : Function.Surjective solution.π := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    ⊢ Function.Surjective ⇑solution.π
  -/
  simpa only [← surjective_fromQuotient_iff_surjective_π] using h.bijective.2
  /-
    🎉 no goals
  -/


lemma ker_π : LinearMap.ker solution.π = Submodule.span A (Set.range relations.relation) := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    ⊢ Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.relatio …
  -/
  simpa only [← injective_fromQuotient_iff_ker_π_eq_span] using h.bijective.1
  /-
    🎉 no goals
  -/


/-- The sequence `(relations.R →₀ A) → (relations.G →₀ A) → M → 0` is exact. -/
lemma exact : Function.Exact relations.map solution.π := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    ⊢ Function.Exact ⇑relations.map ⇑solution.π
  -/
  rw [LinearMap.exact_iff, range_map, ← solution.injective_fromQuotient_iff_ker_π_eq_span]
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    ⊢ Function.Injective ⇑solution.fromQuotient
  -/
  exact h.bijective.1
  /-
    🎉 no goals
  -/


/-- If `M` admits a presentation by generators and relations, and we have a solution of the
same equations in a module `N`, then this is the canonical induced linear map `M →ₗ[A] N`. -/
noncomputable def desc (s : relations.Solution N) : M →ₗ[A] N :=
  s.fromQuotient.comp h.linearEquiv.symm.toLinearMap


@[simp]
lemma desc_var (s : relations.Solution N) (g : relations.G) :
    h.desc s (solution.var g) = s.var g := by
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    s : relations.Solution N
    g : relations.G
    ⊢ Eq ((h.desc s) (solution.var g)) (s.var g)
  -/
  dsimp [desc]
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    s : relations.Solution N
    g : relations.G
    ⊢ Eq (s.fromQuotient (h.linearEquiv.symm (solution.var g))) (s.var g)
  -/
  simp only [linearEquiv_symm_var, fromQuotient_toQuotient, π_single]
  /-
    🎉 no goals
  -/


@[simp]
                                                                                      /-
                                                                                        A : Type u
                                                                                        inst✝⁴ : Ring A
                                                                                        relations : Module.Relations A
                                                                                        M : Type v
                                                                                        inst✝³ : AddCommGroup M
                                                                                        inst✝² : Module A M
                                                                                        solution : relations.Solution M
                                                                                        h : solution.IsPresentation
                                                                                        N : Type v'
                                                                                        inst✝¹ : AddCommGroup N
                                                                                        inst✝ : Module A N
                                                                                        s : relations.Solution N
                                                                                        ⊢ Eq ((h.desc s).comp solution.π) s.π
                                                                                      -/
lemma desc_comp_π (s : relations.Solution N) : (h.desc s).comp solution.π = s.π := by aesop
                                                                                      /-
                                                                                        🎉 no goals
                                                                                      -/


@[simp]
lemma π_desc_apply (s : relations.Solution N) (x : relations.G →₀ A) :
    h.desc s (solution.π x) = s.π x :=
  DFunLike.congr_fun (h.desc_comp_π s) x


@[simp]
lemma postcomp_desc (s : relations.Solution N) :
                                           /-
                                             A : Type u
                                             inst✝⁴ : Ring A
                                             relations : Module.Relations A
                                             M : Type v
                                             inst✝³ : AddCommGroup M
                                             inst✝² : Module A M
                                             solution : relations.Solution M
                                             h : solution.IsPresentation
                                             N : Type v'
                                             inst✝¹ : AddCommGroup N
                                             inst✝ : Module A N
                                             s : relations.Solution N
                                             ⊢ Eq (solution.postcomp (h.desc s)) s
                                           -/
    solution.postcomp (h.desc s) = s := by aesop
                                           /-
                                             🎉 no goals
                                           -/


lemma postcomp_injective {f f' : M →ₗ[A] N}
    (h' : solution.postcomp f = solution.postcomp f') : f = f' := by
  suffices f.comp solution.fromQuotient = f'.comp solution.fromQuotient by
    ext x
    obtain ⟨y, rfl⟩ := h.bijective.2 x
    exact DFunLike.congr_fun this y
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    f f' : LinearMap (RingHom.id A) M N
    h' : Eq (solution.postcomp f) (solution.postcomp f')
    ⊢ Eq (f.comp solution.fromQuotient) (f'.comp solution.fromQuotient)
  -/
  ext g
  /-
    case h
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    f f' : LinearMap (RingHom.id A) M N
    h' : Eq (solution.postcomp f) (solution.postcomp f')
    g : relations.G
    ⊢ Eq ((f.comp solution.fromQuotient) (relations.toQuotient (Finsupp.single g 1 …
  -/
  simpa using congr_var h' g
  /-
    🎉 no goals
  -/


/-- If `M` admits a presentation by generators and relations, then
linear maps from `M` can be (naturally) identified to the solutions of
certain linear equations. -/
@[simps]
noncomputable def linearMapEquiv : (M →ₗ[A] N) ≃ relations.Solution N where
  toFun f := solution.postcomp f
  invFun s := h.desc s
                                         /-
                                           A : Type u
                                           inst✝⁴ : Ring A
                                           relations : Module.Relations A
                                           M : Type v
                                           inst✝³ : AddCommGroup M
                                           inst✝² : Module A M
                                           solution : relations.Solution M
                                           h : solution.IsPresentation
                                           N : Type v'
                                           inst✝¹ : AddCommGroup N
                                           inst✝ : Module A N
                                           f : LinearMap (RingHom.id A) M N
                                           ⊢ Eq (solution.postcomp ((fun s => h.desc s) ((fun f => solution.postcomp f) f …
                                         -/
  left_inv f := h.postcomp_injective (by aesop)
                                         /-
                                           🎉 no goals
                                         -/
                    /-
                      A : Type u
                      inst✝⁴ : Ring A
                      relations : Module.Relations A
                      M : Type v
                      inst✝³ : AddCommGroup M
                      inst✝² : Module A M
                      solution : relations.Solution M
                      h : solution.IsPresentation
                      N : Type v'
                      inst✝¹ : AddCommGroup N
                      inst✝ : Module A N
                      s : relations.Solution N
                      ⊢ Eq ((fun f => solution.postcomp f) ((fun s => h.desc s) s)) s
                    -/
  right_inv s := by aesop
                    /-
                      🎉 no goals
                    -/


/-- Uniqueness (up to a unique linear equivalence) of the module defined
by generators and relations. -/
noncomputable def uniq : M ≃ₗ[A] N := LinearEquiv.ofLinear
  (h.desc solution') (h'.desc solution)
                               /-
                                 A : Type u
                                 inst✝⁴ : Ring A
                                 relations : Module.Relations A
                                 M : Type v
                                 inst✝³ : AddCommGroup M
                                 inst✝² : Module A M
                                 solution : relations.Solution M
                                 h : solution.IsPresentation
                                 N : Type v'
                                 inst✝¹ : AddCommGroup N
                                 inst✝ : Module A N
                                 solution' : relations.Solution N
                                 h' : solution'.IsPresentation
                                 ⊢ Eq (solution'.postcomp ((h.desc solution').comp (h'.desc solution))) (soluti …
                               -/
    (h'.postcomp_injective (by simp))
                               /-
                                 🎉 no goals
                               -/
                              /-
                                A : Type u
                                inst✝⁴ : Ring A
                                relations : Module.Relations A
                                M : Type v
                                inst✝³ : AddCommGroup M
                                inst✝² : Module A M
                                solution : relations.Solution M
                                h : solution.IsPresentation
                                N : Type v'
                                inst✝¹ : AddCommGroup N
                                inst✝ : Module A N
                                solution' : relations.Solution N
                                h' : solution'.IsPresentation
                                ⊢ Eq (solution.postcomp ((h'.desc solution).comp (h.desc solution'))) (solutio …
                              -/
    (h.postcomp_injective (by simp))
                              /-
                                🎉 no goals
                              -/


@[simp]
lemma postcomp_uniq : solution.postcomp (uniq h h').toLinearMap = solution' := by
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    solution' : relations.Solution N
    h' : solution'.IsPresentation
    ⊢ Eq (solution.postcomp ↑(h.uniq h')) solution'
  -/
  simp [uniq]
  /-
    🎉 no goals
  -/


@[simp]
lemma postcomp_uniq_symm : solution'.postcomp (uniq h h').symm.toLinearMap = solution := by
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    solution' : relations.Solution N
    h' : solution'.IsPresentation
    ⊢ Eq (solution'.postcomp ↑(h.uniq h').symm) solution
  -/
  simp [uniq]
  /-
    🎉 no goals
  -/


@[simp]
lemma uniq_var (g : relations.G) : uniq h h' (solution.var g) = solution'.var g := by
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    solution' : relations.Solution N
    h' : solution'.IsPresentation
    g : relations.G
    ⊢ Eq ((h.uniq h') (solution.var g)) (solution'.var g)
  -/
  simp [uniq]
  /-
    🎉 no goals
  -/


@[simp]
lemma uniq_symm_var (g : relations.G) : (uniq h h').symm (solution'.var g) = solution.var g := by
  /-
    A : Type u
    inst✝⁴ : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝³ : AddCommGroup M
    inst✝² : Module A M
    solution : relations.Solution M
    h : solution.IsPresentation
    N : Type v'
    inst✝¹ : AddCommGroup N
    inst✝ : Module A N
    solution' : relations.Solution N
    h' : solution'.IsPresentation
    g : relations.G
    ⊢ Eq ((h.uniq h').symm (solution'.var g)) (solution.var g)
  -/
  simp [uniq]
  /-
    🎉 no goals
  -/


lemma of_linearEquiv (e : M ≃ₗ[A] N) : (solution.postcomp e.toLinearMap).IsPresentation where
  bijective := by
    have : (solution.postcomp e.toLinearMap).fromQuotient =
      e.toLinearMap.comp (solution.fromQuotient) := by aesop
    /-
      A : Type u
      inst✝⁴ : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝³ : AddCommGroup M
      inst✝² : Module A M
      solution : relations.Solution M
      h : solution.IsPresentation
      N : Type v'
      inst✝¹ : AddCommGroup N
      inst✝ : Module A N
      e : LinearEquiv (RingHom.id A) M N
      this : Eq (solution.postcomp ↑e).fromQuotient ((↑e).comp solution.fromQuotient)
      ⊢ Function.Bijective ⇑(solution.postcomp ↑e).fromQuotient
    -/
    rw [this, LinearMap.coe_comp, LinearEquiv.coe_coe]
    /-
      A : Type u
      inst✝⁴ : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝³ : AddCommGroup M
      inst✝² : Module A M
      solution : relations.Solution M
      h : solution.IsPresentation
      N : Type v'
      inst✝¹ : AddCommGroup N
      inst✝ : Module A N
      e : LinearEquiv (RingHom.id A) M N
      this : Eq (solution.postcomp ↑e).fromQuotient ((↑e).comp solution.fromQuotient)
      ⊢ Function.Bijective (Function.comp ⇑e ⇑solution.fromQuotient)
    -/
    exact Function.Bijective.comp e.bijective h.bijective
    /-
      🎉 no goals
    -/


/-- Given `relations : Relations A`, this is the obvious solution to `relations`
in the quotient `relations.Quotient`. -/
@[simps!]
noncomputable def ofQuotient : relations.Solution relations.Quotient :=
                               /-
                                 A : Type u
                                 inst✝² : Ring A
                                 relations : Module.Relations A
                                 M : Type v
                                 inst✝¹ : AddCommGroup M
                                 inst✝ : Module A M
                                 ⊢ ∀ (r : relations.R), Eq (relations.toQuotient (relations.relation r)) 0
                               -/
  ofπ relations.toQuotient (by simp)
                               /-
                                 🎉 no goals
                               -/


@[simp]
lemma ofQuotient_π : (ofQuotient relations).π = Submodule.mkQ _ := ofπ_π _ _


@[simp]
                                                                                /-
                                                                                  A : Type u
                                                                                  inst✝ : Ring A
                                                                                  relations : Module.Relations A
                                                                                  ⊢ Eq (Module.Relations.Solution.ofQuotient relations).fromQuotient LinearMap.id
                                                                                -/
lemma ofQuotient_fromQuotient : (ofQuotient relations).fromQuotient = .id := by aesop
                                                                                /-
                                                                                  🎉 no goals
                                                                                -/


lemma ofQuotient_isPresentation : (ofQuotient relations).IsPresentation where
  bijective := by
    /-
      A : Type u
      inst✝ : Ring A
      relations : Module.Relations A
      ⊢ Function.Bijective ⇑(Module.Relations.Solution.ofQuotient relations).fromQuo …
    -/
    simpa only [ofQuotient_fromQuotient, LinearMap.id_coe] using Function.bijective_id
    /-
      🎉 no goals
    -/


/-- Helper structure in order to prove `Module.Relations.Solutions.IsPresentation`
by showing the universal property of the module defined by generators and relations.
The universal property is restricted to modules that are in `Type w'` for
an auxiliary universe `w'`. See `IsPresentationCore.isPresentation`. -/
structure IsPresentationCore (solution : relations.Solution M) where
  /-- any solution in a module `N : Type w'` is obtained in a unique way
  by postcomposing `solution : relations.Solution M` by a linear map `M →ₗ[A] N`. -/
  desc {N : Type w'} [AddCommGroup N] [Module A N] (s : relations.Solution N) : M →ₗ[A] N
  postcomp_desc {N : Type w'} [AddCommGroup N] [Module A N] (s : relations.Solution N) :
    solution.postcomp (desc s) = s
  postcomp_injective {N : Type w'} [AddCommGroup N] [Module A N] {f f' : M →ₗ[A] N}
      (h : solution.postcomp f = solution.postcomp f') : f = f'


@[simp]
lemma desc_var (h : IsPresentationCore.{w'} solution)
    {N : Type w'} [AddCommGroup N] [Module A N] (s : relations.Solution N) (g : relations.G) :
    h.desc s (solution.var g) = s.var g :=
  congr_var (h.postcomp_desc s) g


/-- The structure `IsPresentationCore` can be shrunk to a lower universe. -/
def down (h : IsPresentationCore.{max w' w''} solution) :
    IsPresentationCore.{w''} solution where
  desc s := ULift.moduleEquiv.toLinearMap.comp
    (h.desc (s.postcomp ULift.moduleEquiv.symm.toLinearMap))
  postcomp_desc s:= by
    simpa using congr_postcomp
      (h.postcomp_desc (s.postcomp ULift.moduleEquiv.symm.toLinearMap))
        ULift.moduleEquiv.toLinearMap
  postcomp_injective {N _ _ f f'} h' := by
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : solution.IsPresentationCore
      N : Type w''
      x✝¹ : AddCommGroup N
      x✝ : Module A N
      f f' : LinearMap (RingHom.id A) M N
      h' : Eq (solution.postcomp f) (solution.postcomp f')
      ⊢ Eq f f'
    -/
    ext x
    /-
      case h
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : solution.IsPresentationCore
      N : Type w''
      x✝¹ : AddCommGroup N
      x✝ : Module A N
      f f' : LinearMap (RingHom.id A) M N
      h' : Eq (solution.postcomp f) (solution.postcomp f')
      x : M
      ⊢ Eq (f x) (f' x)
    -/
    have := congr_postcomp h' ULift.moduleEquiv.{_, _, w'}.symm.toLinearMap
    /-
      case h
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : solution.IsPresentationCore
      N : Type w''
      x✝¹ : AddCommGroup N
      x✝ : Module A N
      f f' : LinearMap (RingHom.id A) M N
      h' : Eq (solution.postcomp f) (solution.postcomp f')
      x : M
      this : Eq ((solution.postcomp f).postcomp ↑ULift.moduleEquiv.symm) ((solution. …
      ⊢ Eq (f x) (f' x)
    -/
    simp only [← postcomp_comp] at this
    /-
      case h
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : solution.IsPresentationCore
      N : Type w''
      x✝¹ : AddCommGroup N
      x✝ : Module A N
      f f' : LinearMap (RingHom.id A) M N
      h' : Eq (solution.postcomp f) (solution.postcomp f')
      x : M
      this : Eq (solution.postcomp ((↑ULift.moduleEquiv.symm).comp f)) (solution.pos …
      ⊢ Eq (f x) (f' x)
    -/
    simpa using DFunLike.congr_fun (h.postcomp_injective this) x
    /-
      🎉 no goals
    -/


lemma isPresentation {solution : relations.Solution M}
    (h : IsPresentationCore.{max u v w₀} solution) :
    solution.IsPresentation where
  bijective := by
    let e : relations.Quotient ≃ₗ[A] M :=
      LinearEquiv.ofLinear solution.fromQuotient
      ((down.{v} h).desc (ofQuotient relations))
      ((down.{max u w₀} h).postcomp_injective (by aesop)) (by aesop)
    /-
      A : Type u
      inst✝² : Ring A
      relations : Module.Relations A
      M : Type v
      inst✝¹ : AddCommGroup M
      inst✝ : Module A M
      solution : relations.Solution M
      h : solution.IsPresentationCore
      e : LinearEquiv (RingHom.id A) relations.Quotient M := LinearEquiv.ofLinear so …
      ⊢ Function.Bijective ⇑solution.fromQuotient
    -/
    exact e.bijective
    /-
      🎉 no goals
    -/


lemma isPresentation_iff :
    solution.IsPresentation ↔
      Submodule.span A (Set.range solution.var) = ⊤ ∧
      LinearMap.ker solution.π = Submodule.span A (Set.range relations.relation) := by
  rw [← injective_fromQuotient_iff_ker_π_eq_span,
    ← surjective_π_iff_span_eq_top, ← surjective_fromQuotient_iff_surjective_π, ]
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    ⊢ Iff solution.IsPresentation (And (Function.Surjective ⇑solution.fromQuotient …
  -/
  exact ⟨fun h ↦ ⟨h.bijective.2, h.bijective.1⟩, fun h ↦ ⟨⟨h.2, h.1⟩⟩⟩
  /-
    🎉 no goals
  -/


lemma isPresentation_mk
    (h₁ : Submodule.span A (Set.range solution.var) = ⊤)
    (h₂ : LinearMap.ker solution.π = Submodule.span A (Set.range relations.relation)) :
    solution.IsPresentation := by
  /-
    A : Type u
    inst✝² : Ring A
    relations : Module.Relations A
    M : Type v
    inst✝¹ : AddCommGroup M
    inst✝ : Module A M
    solution : relations.Solution M
    h₁ : Eq (Submodule.span A (Set.range solution.var)) Top.top
    h₂ : Eq (LinearMap.ker solution.π) (Submodule.span A (Set.range relations.rela …
    ⊢ solution.IsPresentation
  -/
                                           /-
                                             🎉 no goals
                                           -/
  rw [isPresentation_iff]; constructor <;> assumption
                                           /-
                                             🎉 no goals
                                           -/


/-- Given an `A`-module `M`, a term in this type is a presentation by `M` by
generators and relations. -/
@[nolint checkUnivs]
structure Presentation extends Relations.{w₀, w₁} A,
  toRelations.Solution M, toSolution.IsPresentation where


/-- Constructor for `Module.Presentation`. -/
@[simps toRelations toSolution]
def Presentation.ofIsPresentation {relations : Relations.{w₀, w₁} A}
    {solution : relations.Solution M} (h : solution.IsPresentation) :
    Presentation.{w₀, w₁} A M where
  toSolution := solution
  toIsPresentation := h


/-- The presentation of an `A`-module `N` that is deduced from a presentation of
a module `M` and a linear equivalence `e : M ≃ₗ[A] N`. -/
@[simps! toRelations toSolution]
def Presentation.ofLinearEquiv (pres : Presentation.{w₀, w₁} A M)
    {N : Type v'} [AddCommGroup N] [Module A N] (e : M ≃ₗ[A] N) :
    Presentation A N :=
  ofIsPresentation (pres.toIsPresentation.of_linearEquiv e)


