/-- The subtype of `G.subgraph` comprising those subgraphs with finite vertex sets. -/
abbrev Finsubgraph (G : SimpleGraph V) :=
  { G' : G.Subgraph // G'.verts.Finite }


/-- A graph homomorphism from a finite subgraph of G to F. -/
abbrev FinsubgraphHom (G' : G.Finsubgraph) (F : SimpleGraph W) :=
  G'.val.coe →g F


local infixl:50 " →fg " => FinsubgraphHom


instance : OrderBot G.Finsubgraph where
  bot := ⟨⊥, finite_empty⟩
  bot_le _ := bot_le (α := G.Subgraph)


instance : Max G.Finsubgraph :=
  ⟨fun G₁ G₂ => ⟨G₁ ⊔ G₂, G₁.2.union G₂.2⟩⟩


instance : Min G.Finsubgraph :=
  ⟨fun G₁ G₂ => ⟨G₁ ⊓ G₂, G₁.2.subset inter_subset_left⟩⟩


instance instSDiff : SDiff G.Finsubgraph where
  sdiff G₁ G₂ := ⟨G₁ \ G₂, G₁.2.subset (Subgraph.verts_mono sdiff_le)⟩


@[simp, norm_cast] lemma coe_bot : (⊥ : G.Finsubgraph) = (⊥ : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_sup (G₁ G₂ : G.Finsubgraph) : ↑(G₁ ⊔ G₂) = (G₁ ⊔ G₂ : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_inf (G₁ G₂ : G.Finsubgraph) : ↑(G₁ ⊓ G₂) = (G₁ ⊓ G₂ : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_sdiff (G₁ G₂ : G.Finsubgraph) : ↑(G₁ \ G₂) = (G₁ \ G₂ : G.Subgraph) := rfl


instance instGeneralizedCoheytingAlgebra : GeneralizedCoheytingAlgebra G.Finsubgraph :=
  Subtype.coe_injective.generalizedCoheytingAlgebra _ coe_sup coe_inf coe_bot coe_sdiff


instance instTop : Top G.Finsubgraph where top := ⟨⊤, finite_univ⟩

instance instHasCompl : HasCompl G.Finsubgraph where compl G' := ⟨G'ᶜ, Set.toFinite _⟩

instance instHNot : HNot G.Finsubgraph where hnot G' := ⟨￢G', Set.toFinite _⟩

instance instHImp : HImp G.Finsubgraph where himp G₁ G₂ := ⟨G₁ ⇨ G₂, Set.toFinite _⟩

instance instSupSet : SupSet G.Finsubgraph where sSup s := ⟨⨆ G ∈ s, ↑G, Set.toFinite _⟩

instance instInfSet : InfSet G.Finsubgraph where sInf s := ⟨⨅ G ∈ s, ↑G, Set.toFinite _⟩


@[simp, norm_cast] lemma coe_top : (⊤ : G.Finsubgraph) = (⊤ : G.Subgraph) := rfl

@[simp, norm_cast] lemma coe_compl (G' : G.Finsubgraph) : ↑(G'ᶜ) = (G'ᶜ : G.Subgraph) := rfl

@[simp, norm_cast] lemma coe_hnot (G' : G.Finsubgraph) : ↑(￢G') = (￢G' : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_himp (G₁ G₂ : G.Finsubgraph) : ↑(G₁ ⇨ G₂) = (G₁ ⇨ G₂ : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_sSup (s : Set G.Finsubgraph) : sSup s = (⨆ G ∈ s, G : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_sInf (s : Set G.Finsubgraph) : sInf s = (⨅ G ∈ s, G : G.Subgraph) := rfl


@[simp, norm_cast]
lemma coe_iSup {ι : Sort*} (f : ι → G.Finsubgraph) : ⨆ i, f i = (⨆ i, f i : G.Subgraph) := by
  /-
    V : Type u
    G : SimpleGraph V
    inst✝ : Finite V
    ι : Sort u_1
    f : ι → G.Finsubgraph
    ⊢ Eq (↑(iSup fun i => f i)) (iSup fun i => ↑(f i))
  -/
  rw [iSup, coe_sSup, iSup_range]
  /-
    🎉 no goals
  -/


@[simp, norm_cast]
lemma coe_iInf {ι : Sort*} (f : ι → G.Finsubgraph) : ⨅ i, f i = (⨅ i, f i : G.Subgraph) := by
  /-
    V : Type u
    G : SimpleGraph V
    inst✝ : Finite V
    ι : Sort u_1
    f : ι → G.Finsubgraph
    ⊢ Eq (↑(iInf fun i => f i)) (iInf fun i => ↑(f i))
  -/
  rw [iInf, coe_sInf, iInf_range]
  /-
    🎉 no goals
  -/


instance instCompletelyDistribLattice : CompletelyDistribLattice G.Finsubgraph :=
  Subtype.coe_injective.completelyDistribLattice _ coe_sup coe_inf coe_sSup coe_sInf coe_top coe_bot
    coe_compl coe_himp coe_hnot coe_sdiff


/-- The finite subgraph of G generated by a single vertex. -/
def singletonFinsubgraph (v : V) : G.Finsubgraph :=
                                         /-
                                           V : Type u
                                           W : Type v
                                           G : SimpleGraph V
                                           F : SimpleGraph W
                                           v : V
                                           ⊢ (G.singletonSubgraph v).verts.Finite
                                         -/
  ⟨SimpleGraph.singletonSubgraph _ v, by simp⟩
                                         /-
                                           🎉 no goals
                                         -/


/-- The finite subgraph of G generated by a single edge. -/
def finsubgraphOfAdj {u v : V} (e : G.Adj u v) : G.Finsubgraph :=
                                     /-
                                       V : Type u
                                       W : Type v
                                       G : SimpleGraph V
                                       F : SimpleGraph W
                                       u v : V
                                       e : G.Adj u v
                                       ⊢ (G.subgraphOfAdj e).verts.Finite
                                     -/
  ⟨SimpleGraph.subgraphOfAdj _ e, by simp⟩
                                     /-
                                       🎉 no goals
                                     -/

-- Lemmas establishing the ordering between edge- and vertex-generated subgraphs.

theorem singletonFinsubgraph_le_adj_left {u v : V} {e : G.Adj u v} :
    singletonFinsubgraph u ≤ finsubgraphOfAdj e := by
  /-
    V : Type u
    G : SimpleGraph V
    u v : V
    e : G.Adj u v
    ⊢ LE.le (SimpleGraph.singletonFinsubgraph u) (SimpleGraph.finsubgraphOfAdj e)
  -/
  simp [singletonFinsubgraph, finsubgraphOfAdj]
  /-
    🎉 no goals
  -/


theorem singletonFinsubgraph_le_adj_right {u v : V} {e : G.Adj u v} :
    singletonFinsubgraph v ≤ finsubgraphOfAdj e := by
  /-
    V : Type u
    G : SimpleGraph V
    u v : V
    e : G.Adj u v
    ⊢ LE.le (SimpleGraph.singletonFinsubgraph v) (SimpleGraph.finsubgraphOfAdj e)
  -/
  simp [singletonFinsubgraph, finsubgraphOfAdj]
  /-
    🎉 no goals
  -/


/-- Given a homomorphism from a subgraph to `F`, construct its restriction to a sub-subgraph. -/
def FinsubgraphHom.restrict {G' G'' : G.Finsubgraph} (h : G'' ≤ G') (f : G' →fg F) : G'' →fg F := by
  /-
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    G' G'' : G.Finsubgraph
    h : LE.le G'' G'
    f : SimpleGraph.FinsubgraphHom G' F
    ⊢ SimpleGraph.FinsubgraphHom G'' F
  -/
  refine ⟨fun ⟨v, hv⟩ => f.toFun ⟨v, h.1 hv⟩, ?_⟩
  /-
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    G' G'' : G.Finsubgraph
    h : LE.le G'' G'
    f : SimpleGraph.FinsubgraphHom G' F
    ⊢ ∀ {a b : ↑(↑G'').verts}, (↑G'').coe.Adj a b → F.Adj ((fun x => SimpleGraph.F …
  -/
  rintro ⟨u, hu⟩ ⟨v, hv⟩ huv
  /-
    case mk.mk
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    G' G'' : G.Finsubgraph
    h : LE.le G'' G'
    f : SimpleGraph.FinsubgraphHom G' F
    u : V
    hu : Membership.mem (↑G'').verts u
    v : V
    hv : Membership.mem (↑G'').verts v
    huv : (↑G'').coe.Adj ⟨u, hu⟩ ⟨v, hv⟩
    ⊢ F.Adj ((fun x => SimpleGraph.FinsubgraphHom.restrict.match_1 (fun x => W) x  …
  -/
  exact f.map_rel' (h.2 huv)
  /-
    🎉 no goals
  -/


/-- The inverse system of finite homomorphisms. -/
def finsubgraphHomFunctor (G : SimpleGraph V) (F : SimpleGraph W) :
    G.Finsubgraphᵒᵖ ⥤ Type max u v where
  obj G' := G'.unop →fg F
  map g f := f.restrict (CategoryTheory.leOfHom g.unop)


/-- If every finite subgraph of a graph `G` has a homomorphism to a finite graph `F`, then there is
a homomorphism from the whole of `G` to `F`. -/
theorem nonempty_hom_of_forall_finite_subgraph_hom [Finite W]
    (h : ∀ G' : G.Subgraph, G'.verts.Finite → G'.coe →g F) : Nonempty (G →g F) := by
  -- Obtain a `Fintype` instance for `W`.
  /-
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    inst✝ : Finite W
    h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
    ⊢ Nonempty (G.Hom F)
  -/
  cases nonempty_fintype W
  -- Establish the required interface instances.
  haveI : ∀ G' : G.Finsubgraphᵒᵖ, Nonempty ((finsubgraphHomFunctor G F).obj G') := fun G' =>
    ⟨h G'.unop G'.unop.property⟩
  haveI : ∀ G' : G.Finsubgraphᵒᵖ, Fintype ((finsubgraphHomFunctor G F).obj G') := by
    intro G'
    haveI : Fintype (G'.unop.val.verts : Type u) := G'.unop.property.fintype
    haveI : Fintype (↥G'.unop.val.verts → W) := by classical exact Pi.instFintype
    exact Fintype.ofInjective (fun f => f.toFun) RelHom.coe_fn_injective
  -- Use compactness to obtain a section.
  /-
    case intro
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    inst✝ : Finite W
    h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
    val✝ : Fintype W
    this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
    this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
    ⊢ Nonempty (G.Hom F)
  -/
  obtain ⟨u, hu⟩ := nonempty_sections_of_finite_inverse_system (finsubgraphHomFunctor G F)
  /-
    case intro.intro
    V : Type u
    W : Type v
    G : SimpleGraph V
    F : SimpleGraph W
    inst✝ : Finite W
    h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
    val✝ : Fintype W
    this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
    this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
    u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
    hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
    ⊢ Nonempty (G.Hom F)
  -/
  refine ⟨⟨fun v => ?_, ?_⟩⟩
  · -- Map each vertex using the homomorphism provided for its singleton subgraph.
    exact
      (u (Opposite.op (singletonFinsubgraph v))).toFun
        ⟨v, by
          unfold singletonFinsubgraph
          simp⟩
  · -- Prove that the above mapping preserves adjacency.
    /-
      case intro.intro.refine_2
      V : Type u
      W : Type v
      G : SimpleGraph V
      F : SimpleGraph W
      inst✝ : Finite W
      h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
      val✝ : Fintype W
      this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
      this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
      u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
      hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
      ⊢ ∀ {a b : V}, G.Adj a b → F.Adj ((fun v => (u { unop := SimpleGraph.singleton …
    -/
    intro v v' e
    /-
      case intro.intro.refine_2
      V : Type u
      W : Type v
      G : SimpleGraph V
      F : SimpleGraph W
      inst✝ : Finite W
      h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
      val✝ : Fintype W
      this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
      this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
      u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
      hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
      v v' : V
      e : G.Adj v v'
      ⊢ F.Adj ((fun v => (u { unop := SimpleGraph.singletonFinsubgraph v }).toFun ⟨v …
    -/
    simp only
    /- The homomorphism for each edge's singleton subgraph agrees with those for its source and
        target vertices. -/
    have hv : Opposite.op (finsubgraphOfAdj e) ⟶ Opposite.op (singletonFinsubgraph v) :=
      Quiver.Hom.op (CategoryTheory.homOfLE singletonFinsubgraph_le_adj_left)
    have hv' : Opposite.op (finsubgraphOfAdj e) ⟶ Opposite.op (singletonFinsubgraph v') :=
      Quiver.Hom.op (CategoryTheory.homOfLE singletonFinsubgraph_le_adj_right)
    /-
      case intro.intro.refine_2
      V : Type u
      W : Type v
      G : SimpleGraph V
      F : SimpleGraph W
      inst✝ : Finite W
      h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
      val✝ : Fintype W
      this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
      this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
      u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
      hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
      v v' : V
      e : G.Adj v v'
      hv : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGra …
      hv' : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGr …
      ⊢ F.Adj ((u { unop := SimpleGraph.singletonFinsubgraph v }).toFun ⟨v, ⋯⟩) ((u  …
    -/
    rw [← hu hv, ← hu hv']
    -- Porting note: was `apply Hom.map_adj`
    /-
      case intro.intro.refine_2
      V : Type u
      W : Type v
      G : SimpleGraph V
      F : SimpleGraph W
      inst✝ : Finite W
      h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
      val✝ : Fintype W
      this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
      this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
      u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
      hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
      v v' : V
      e : G.Adj v v'
      hv : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGra …
      hv' : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGr …
      ⊢ F.Adj (((G.finsubgraphHomFunctor F).map hv (u { unop := SimpleGraph.finsubgr …
    -/
    refine Hom.map_adj (u (Opposite.op (finsubgraphOfAdj e))) ?_
    -- `v` and `v'` are definitionally adjacent in `finsubgraphOfAdj e`
    /-
      case intro.intro.refine_2
      V : Type u
      W : Type v
      G : SimpleGraph V
      F : SimpleGraph W
      inst✝ : Finite W
      h : (G' : G.Subgraph) → G'.verts.Finite → G'.coe.Hom F
      val✝ : Fintype W
      this✝ : ∀ (G' : Opposite G.Finsubgraph), Nonempty ((G.finsubgraphHomFunctor F) …
      this : (G' : Opposite G.Finsubgraph) → Fintype ((G.finsubgraphHomFunctor F).ob …
      u : (j : Opposite G.Finsubgraph) → (G.finsubgraphHomFunctor F).obj j
      hu : Membership.mem (G.finsubgraphHomFunctor F).sections u
      v v' : V
      e : G.Adj v v'
      hv : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGra …
      hv' : Quiver.Hom { unop := SimpleGraph.finsubgraphOfAdj e } { unop := SimpleGr …
      ⊢ (↑(Opposite.unop { unop := SimpleGraph.finsubgraphOfAdj e })).coe.Adj ⟨v, ⋯⟩ …
    -/
    simp [finsubgraphOfAdj]
    /-
      🎉 no goals
    -/


