/-- The semidirect product of groups `N` and `G`, given a map `φ` from `G` to the automorphism
  group of `N`. It the product of sets with the group operation
  `⟨n₁, g₁⟩ * ⟨n₂, g₂⟩ = ⟨n₁ * φ g₁ n₂, g₁ * g₂⟩` -/
@[ext]
structure SemidirectProduct (φ : G →* MulAut N) where
  /-- The element of N -/
  left : N
  /-- The element of G -/
  right : G
  deriving DecidableEq

-- Porting note: these lemmas are autogenerated by the inductive definition and are not
-- in simple form due to the existence of mk_eq_inl_mul_inr

@[inherit_doc]
notation:35 N " ⋊[" φ:35 "] " G:35 => SemidirectProduct N G φ


instance : Mul (SemidirectProduct N G φ) where
  mul a b := ⟨a.1 * φ a.2 b.1, a.2 * b.2⟩


lemma mul_def (a b : SemidirectProduct N G φ) : a * b = ⟨a.1 * φ a.2 b.1, a.2 * b.2⟩ := rfl


@[simp]
theorem mul_left (a b : N ⋊[φ] G) : (a * b).left = a.left * φ a.right b.left := rfl


@[simp]
theorem mul_right (a b : N ⋊[φ] G) : (a * b).right = a.right * b.right := rfl


instance : One (SemidirectProduct N G φ) where one := ⟨1, 1⟩


@[simp]
theorem one_left : (1 : N ⋊[φ] G).left = 1 := rfl


@[simp]
theorem one_right : (1 : N ⋊[φ] G).right = 1 := rfl


instance : Inv (SemidirectProduct N G φ) where
  inv x := ⟨φ x.2⁻¹ x.1⁻¹, x.2⁻¹⟩


@[simp]
theorem inv_left (a : N ⋊[φ] G) : a⁻¹.left = φ a.right⁻¹ a.left⁻¹ := rfl


@[simp]
theorem inv_right (a : N ⋊[φ] G) : a⁻¹.right = a.right⁻¹ := rfl


instance : Group (N ⋊[φ] G) where
                                               /-
                                                 N : Type u_1
                                                 G : Type u_2
                                                 H : Type u_3
                                                 inst✝² : Group N
                                                 inst✝¹ : Group G
                                                 inst✝ : Group H
                                                 φ : MonoidHom G (MulAut N)
                                                 a b c : SemidirectProduct N G φ
                                                 ⊢ Eq (HMul.hMul (HMul.hMul a b) c).left (HMul.hMul a (HMul.hMul b c)).left
                                               -/
                                               /-
                                                 🎉 no goals
                                               -/
  mul_assoc a b c := SemidirectProduct.ext (by simp [mul_assoc]) (by simp [mul_assoc])
                                                                     /-
                                                                       🎉 no goals
                                                                     -/
                                         /-
                                           N : Type u_1
                                           G : Type u_2
                                           H : Type u_3
                                           inst✝² : Group N
                                           inst✝¹ : Group G
                                           inst✝ : Group H
                                           φ : MonoidHom G (MulAut N)
                                           a : SemidirectProduct N G φ
                                           ⊢ Eq (HMul.hMul 1 a).left a.left
                                         -/
  one_mul a := SemidirectProduct.ext (by simp) (one_mul a.2)
                                         /-
                                           🎉 no goals
                                         -/
                                         /-
                                           N : Type u_1
                                           G : Type u_2
                                           H : Type u_3
                                           inst✝² : Group N
                                           inst✝¹ : Group G
                                           inst✝ : Group H
                                           φ : MonoidHom G (MulAut N)
                                           a : SemidirectProduct N G φ
                                           ⊢ Eq (HMul.hMul a 1).left a.left
                                         -/
  mul_one a := SemidirectProduct.ext (by simp) (mul_one _)
                                         /-
                                           🎉 no goals
                                         -/
                                                /-
                                                  N : Type u_1
                                                  G : Type u_2
                                                  H : Type u_3
                                                  inst✝² : Group N
                                                  inst✝¹ : Group G
                                                  inst✝ : Group H
                                                  φ : MonoidHom G (MulAut N)
                                                  a : SemidirectProduct N G φ
                                                  ⊢ Eq (HMul.hMul (Inv.inv a) a).left (SemidirectProduct.left 1)
                                                -/
                                                /-
                                                  🎉 no goals
                                                -/
  inv_mul_cancel a := SemidirectProduct.ext (by simp) (by simp)
                                                          /-
                                                            🎉 no goals
                                                          -/


instance : Inhabited (N ⋊[φ] G) := ⟨1⟩


/-- The canonical map `N →* N ⋊[φ] G` sending `n` to `⟨n, 1⟩` -/
def inl : N →* N ⋊[φ] G where
  toFun n := ⟨n, 1⟩
  map_one' := rfl
                 /-
                   N : Type u_1
                   G : Type u_2
                   H : Type u_3
                   inst✝² : Group N
                   inst✝¹ : Group G
                   inst✝ : Group H
                   φ : MonoidHom G (MulAut N)
                   ⊢ ∀ (x y : N), Eq ({ toFun := fun n => { left := n, right := 1 }, map_one' :=  …
                 -/
  map_mul' := by intros; ext <;>
    /-
      case left
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝² : Group N
      inst✝¹ : Group G
      inst✝ : Group H
      φ : MonoidHom G (MulAut N)
      x✝ y✝ : N
      ⊢ Eq ({ toFun := fun n => { left := n, right := 1 }, map_one' := ⋯ }.toFun (HM …
    -/
    /-
      🎉 no goals
    -/
    simp only [mul_left, map_one, MulAut.one_apply, mul_right, mul_one]
    /-
      🎉 no goals
    -/


@[simp]
theorem left_inl (n : N) : (inl n : N ⋊[φ] G).left = n := rfl


@[simp]
theorem right_inl (n : N) : (inl n : N ⋊[φ] G).right = 1 := rfl


theorem inl_injective : Function.Injective (inl : N → N ⋊[φ] G) :=
  Function.injective_iff_hasLeftInverse.2 ⟨left, left_inl⟩


@[simp]
theorem inl_inj {n₁ n₂ : N} : (inl n₁ : N ⋊[φ] G) = inl n₂ ↔ n₁ = n₂ :=
  inl_injective.eq_iff


/-- The canonical map `G →* N ⋊[φ] G` sending `g` to `⟨1, g⟩` -/
def inr : G →* N ⋊[φ] G where
  toFun g := ⟨1, g⟩
  map_one' := rfl
                 /-
                   N : Type u_1
                   G : Type u_2
                   H : Type u_3
                   inst✝² : Group N
                   inst✝¹ : Group G
                   inst✝ : Group H
                   φ : MonoidHom G (MulAut N)
                   ⊢ ∀ (x y : G), Eq ({ toFun := fun g => { left := 1, right := g }, map_one' :=  …
                 -/
                                 /-
                                   🎉 no goals
                                 -/
  map_mul' := by intros; ext <;> simp
                                 /-
                                   🎉 no goals
                                 -/


@[simp]
theorem left_inr (g : G) : (inr g : N ⋊[φ] G).left = 1 := rfl


@[simp]
theorem right_inr (g : G) : (inr g : N ⋊[φ] G).right = g := rfl


theorem inr_injective : Function.Injective (inr : G → N ⋊[φ] G) :=
  Function.injective_iff_hasLeftInverse.2 ⟨right, right_inr⟩


@[simp]
theorem inr_inj {g₁ g₂ : G} : (inr g₁ : N ⋊[φ] G) = inr g₂ ↔ g₁ = g₂ :=
  inr_injective.eq_iff


theorem inl_aut (g : G) (n : N) : (inl (φ g n) : N ⋊[φ] G) = inr g * inl n * inr g⁻¹ := by
  /-
    N : Type u_1
    G : Type u_2
    inst✝¹ : Group N
    inst✝ : Group G
    φ : MonoidHom G (MulAut N)
    g : G
    n : N
    ⊢ Eq (SemidirectProduct.inl ((φ g) n)) (HMul.hMul (HMul.hMul (SemidirectProduc …
  -/
          /-
            🎉 no goals
          -/
  ext <;> simp
          /-
            🎉 no goals
          -/


theorem inl_aut_inv (g : G) (n : N) : (inl ((φ g)⁻¹ n) : N ⋊[φ] G) = inr g⁻¹ * inl n * inr g := by
  /-
    N : Type u_1
    G : Type u_2
    inst✝¹ : Group N
    inst✝ : Group G
    φ : MonoidHom G (MulAut N)
    g : G
    n : N
    ⊢ Eq (SemidirectProduct.inl ((Inv.inv (φ g)) n)) (HMul.hMul (HMul.hMul (Semidi …
  -/
  rw [← MonoidHom.map_inv, inl_aut, inv_inv]
  /-
    🎉 no goals
  -/


@[simp]
                                                                                      /-
                                                                                        N : Type u_1
                                                                                        G : Type u_2
                                                                                        inst✝¹ : Group N
                                                                                        inst✝ : Group G
                                                                                        φ : MonoidHom G (MulAut N)
                                                                                        g : G
                                                                                        n : N
                                                                                        ⊢ Eq { left := n, right := g } (HMul.hMul (SemidirectProduct.inl n) (Semidirec …
                                                                                      -/
                                                                                              /-
                                                                                                🎉 no goals
                                                                                              -/
theorem mk_eq_inl_mul_inr (g : G) (n : N) : (⟨n, g⟩ : N ⋊[φ] G) = inl n * inr g := by ext <;> simp
                                                                                              /-
                                                                                                🎉 no goals
                                                                                              -/


@[simp]
                                                                                   /-
                                                                                     N : Type u_1
                                                                                     G : Type u_2
                                                                                     inst✝¹ : Group N
                                                                                     inst✝ : Group G
                                                                                     φ : MonoidHom G (MulAut N)
                                                                                     x : SemidirectProduct N G φ
                                                                                     ⊢ Eq (HMul.hMul (SemidirectProduct.inl x.left) (SemidirectProduct.inr x.right) …
                                                                                   -/
                                                                                           /-
                                                                                             🎉 no goals
                                                                                           -/
theorem inl_left_mul_inr_right (x : N ⋊[φ] G) : inl x.left * inr x.right = x := by ext <;> simp
                                                                                           /-
                                                                                             🎉 no goals
                                                                                           -/


/-- The canonical projection map `N ⋊[φ] G →* G`, as a group hom. -/
def rightHom : N ⋊[φ] G →* G where
  toFun := SemidirectProduct.right
  map_one' := rfl
  map_mul' _ _ := rfl


@[simp]
theorem rightHom_eq_right : (rightHom : N ⋊[φ] G → G) = right := rfl


@[simp]
                                                                          /-
                                                                            N : Type u_1
                                                                            G : Type u_2
                                                                            inst✝¹ : Group N
                                                                            inst✝ : Group G
                                                                            φ : MonoidHom G (MulAut N)
                                                                            ⊢ Eq (SemidirectProduct.rightHom.comp SemidirectProduct.inl) 1
                                                                          -/
theorem rightHom_comp_inl : (rightHom : N ⋊[φ] G →* G).comp inl = 1 := by ext; simp [rightHom]
                                                                               /-
                                                                                 🎉 no goals
                                                                               -/


@[simp]
theorem rightHom_comp_inr : (rightHom : N ⋊[φ] G →* G).comp inr = MonoidHom.id _ := by
  /-
    N : Type u_1
    G : Type u_2
    inst✝¹ : Group N
    inst✝ : Group G
    φ : MonoidHom G (MulAut N)
    ⊢ Eq (SemidirectProduct.rightHom.comp SemidirectProduct.inr) (MonoidHom.id G)
  -/
  ext; simp [rightHom]
       /-
         🎉 no goals
       -/


@[simp]
                                                                     /-
                                                                       N : Type u_1
                                                                       G : Type u_2
                                                                       inst✝¹ : Group N
                                                                       inst✝ : Group G
                                                                       φ : MonoidHom G (MulAut N)
                                                                       n : N
                                                                       ⊢ Eq (SemidirectProduct.rightHom (SemidirectProduct.inl n)) 1
                                                                     -/
theorem rightHom_inl (n : N) : rightHom (inl n : N ⋊[φ] G) = 1 := by simp [rightHom]
                                                                     /-
                                                                       🎉 no goals
                                                                     -/


@[simp]
                                                                     /-
                                                                       N : Type u_1
                                                                       G : Type u_2
                                                                       inst✝¹ : Group N
                                                                       inst✝ : Group G
                                                                       φ : MonoidHom G (MulAut N)
                                                                       g : G
                                                                       ⊢ Eq (SemidirectProduct.rightHom (SemidirectProduct.inr g)) g
                                                                     -/
theorem rightHom_inr (g : G) : rightHom (inr g : N ⋊[φ] G) = g := by simp [rightHom]
                                                                     /-
                                                                       🎉 no goals
                                                                     -/


theorem rightHom_surjective : Function.Surjective (rightHom : N ⋊[φ] G → G) :=
  Function.surjective_iff_hasRightInverse.2 ⟨inr, rightHom_inr⟩


theorem range_inl_eq_ker_rightHom : (inl : N →* N ⋊[φ] G).range = rightHom.ker :=
                          /-
                            N : Type u_1
                            G : Type u_2
                            inst✝¹ : Group N
                            inst✝ : Group G
                            φ : MonoidHom G (MulAut N)
                            x✝ : SemidirectProduct N G φ
                            ⊢ Membership.mem SemidirectProduct.inl.range x✝ → Membership.mem SemidirectPro …
                          -/
  le_antisymm (fun _ ↦ by simp +contextual [MonoidHom.mem_ker, eq_comm])
                          /-
                            🎉 no goals
                          -/
                           /-
                             N : Type u_1
                             G : Type u_2
                             inst✝¹ : Group N
                             inst✝ : Group G
                             φ : MonoidHom G (MulAut N)
                             x : SemidirectProduct N G φ
                             hx : Membership.mem SemidirectProduct.rightHom.ker x
                             ⊢ Eq (SemidirectProduct.inl x.left) x
                           -/
                                   /-
                                     🎉 no goals
                                   -/
    fun x hx ↦ ⟨x.left, by ext <;> simp_all [MonoidHom.mem_ker]⟩
                                   /-
                                     🎉 no goals
                                   -/


/-- The bijection between the semidirect product and the product. -/
@[simps!]
def equivProd : N ⋊[φ] G ≃ N × G :=
  { toFun := fun ⟨n, g⟩ ↦ ⟨n, g⟩
    invFun := fun ⟨n, g⟩ ↦ ⟨n, g⟩
    left_inv := fun _ ↦ rfl
    right_inv := fun _ ↦ rfl }


/-- Define a group hom `N ⋊[φ] G →* H`, by defining maps `N →* H` and `G →* H`  -/
def lift : N ⋊[φ] G →* H where
  toFun a := fn a.1 * fg a.2
                 /-
                   N : Type u_1
                   G : Type u_2
                   H : Type u_3
                   inst✝² : Group N
                   inst✝¹ : Group G
                   inst✝ : Group H
                   φ : MonoidHom G (MulAut N)
                   fn : MonoidHom N H
                   fg : MonoidHom G H
                   h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                   ⊢ Eq ((fun a => HMul.hMul (fn a.left) (fg a.right)) 1) 1
                 -/
  map_one' := by simp
                 /-
                   🎉 no goals
                 -/
  map_mul' a b := by
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝² : Group N
      inst✝¹ : Group G
      inst✝ : Group H
      φ : MonoidHom G (MulAut N)
      fn : MonoidHom N H
      fg : MonoidHom G H
      h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
      a b : SemidirectProduct N G φ
      ⊢ Eq ({ toFun := fun a => HMul.hMul (fn a.left) (fg a.right), map_one' := ⋯ }. …
    -/
    have := fun n g ↦ DFunLike.ext_iff.1 (h n) g
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝² : Group N
      inst✝¹ : Group G
      inst✝ : Group H
      φ : MonoidHom G (MulAut N)
      fn : MonoidHom N H
      fg : MonoidHom G H
      h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
      a b : SemidirectProduct N G φ
      this : ∀ (n : G) (g : N), Eq ((fn.comp (MulEquiv.toMonoidHom (φ n))) g) (((Mul …
      ⊢ Eq ({ toFun := fun a => HMul.hMul (fn a.left) (fg a.right), map_one' := ⋯ }. …
    -/
    simp only [MulAut.conj_apply, MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom] at this
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝² : Group N
      inst✝¹ : Group G
      inst✝ : Group H
      φ : MonoidHom G (MulAut N)
      fn : MonoidHom N H
      fg : MonoidHom G H
      h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
      a b : SemidirectProduct N G φ
      this : ∀ (n : G) (g : N), Eq (fn ((φ n) g)) (HMul.hMul (HMul.hMul (fg n) (fn g …
      ⊢ Eq ({ toFun := fun a => HMul.hMul (fn a.left) (fg a.right), map_one' := ⋯ }. …
    -/
    simp only [mul_left, mul_right, map_mul, this, mul_assoc, inv_mul_cancel_left]
    /-
      🎉 no goals
    -/


@[simp]
                                                             /-
                                                               N : Type u_1
                                                               G : Type u_2
                                                               H : Type u_3
                                                               inst✝² : Group N
                                                               inst✝¹ : Group G
                                                               inst✝ : Group H
                                                               φ : MonoidHom G (MulAut N)
                                                               fn : MonoidHom N H
                                                               fg : MonoidHom G H
                                                               h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                                                               n : N
                                                               ⊢ Eq ((SemidirectProduct.lift fn fg h) (SemidirectProduct.inl n)) (fn n)
                                                             -/
theorem lift_inl (n : N) : lift fn fg h (inl n) = fn n := by simp [lift]
                                                             /-
                                                               🎉 no goals
                                                             -/


@[simp]
                                                           /-
                                                             N : Type u_1
                                                             G : Type u_2
                                                             H : Type u_3
                                                             inst✝² : Group N
                                                             inst✝¹ : Group G
                                                             inst✝ : Group H
                                                             φ : MonoidHom G (MulAut N)
                                                             fn : MonoidHom N H
                                                             fg : MonoidHom G H
                                                             h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                                                             ⊢ Eq ((SemidirectProduct.lift fn fg h).comp SemidirectProduct.inl) fn
                                                           -/
theorem lift_comp_inl : (lift fn fg h).comp inl = fn := by ext; simp
                                                                /-
                                                                  🎉 no goals
                                                                -/


@[simp]
                                                             /-
                                                               N : Type u_1
                                                               G : Type u_2
                                                               H : Type u_3
                                                               inst✝² : Group N
                                                               inst✝¹ : Group G
                                                               inst✝ : Group H
                                                               φ : MonoidHom G (MulAut N)
                                                               fn : MonoidHom N H
                                                               fg : MonoidHom G H
                                                               h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                                                               g : G
                                                               ⊢ Eq ((SemidirectProduct.lift fn fg h) (SemidirectProduct.inr g)) (fg g)
                                                             -/
theorem lift_inr (g : G) : lift fn fg h (inr g) = fg g := by simp [lift]
                                                             /-
                                                               🎉 no goals
                                                             -/


@[simp]
                                                           /-
                                                             N : Type u_1
                                                             G : Type u_2
                                                             H : Type u_3
                                                             inst✝² : Group N
                                                             inst✝¹ : Group G
                                                             inst✝ : Group H
                                                             φ : MonoidHom G (MulAut N)
                                                             fn : MonoidHom N H
                                                             fg : MonoidHom G H
                                                             h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                                                             ⊢ Eq ((SemidirectProduct.lift fn fg h).comp SemidirectProduct.inr) fg
                                                           -/
theorem lift_comp_inr : (lift fn fg h).comp inr = fg := by ext; simp
                                                                /-
                                                                  🎉 no goals
                                                                -/


theorem lift_unique (F : N ⋊[φ] G →* H) :
                                                  /-
                                                    N : Type u_1
                                                    G : Type u_2
                                                    H : Type u_3
                                                    inst✝² : Group N
                                                    inst✝¹ : Group G
                                                    inst✝ : Group H
                                                    φ : MonoidHom G (MulAut N)
                                                    fn : MonoidHom N H
                                                    fg : MonoidHom G H
                                                    h : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidHo …
                                                    F : MonoidHom (SemidirectProduct N G φ) H
                                                    x✝ : G
                                                    ⊢ Eq ((F.comp SemidirectProduct.inl).comp (MulEquiv.toMonoidHom (φ x✝))) ((Mul …
                                                  -/
    F = lift (F.comp inl) (F.comp inr) fun _ ↦ by ext; simp [inl_aut] := by
                                                       /-
                                                         🎉 no goals
                                                       -/
  /-
    N : Type u_1
    G : Type u_2
    H : Type u_3
    inst✝² : Group N
    inst✝¹ : Group G
    inst✝ : Group H
    φ : MonoidHom G (MulAut N)
    F : MonoidHom (SemidirectProduct N G φ) H
    ⊢ Eq F (SemidirectProduct.lift (F.comp SemidirectProduct.inl) (F.comp Semidire …
  -/
  rw [DFunLike.ext_iff]
  simp only [lift, MonoidHom.comp_apply, MonoidHom.coe_mk, OneHom.coe_mk, ← map_mul,
    inl_left_mul_inr_right, forall_const]


/-- Two maps out of the semidirect product are equal if they're equal after composition
  with both `inl` and `inr` -/
theorem hom_ext {f g : N ⋊[φ] G →* H} (hl : f.comp inl = g.comp inl)
    (hr : f.comp inr = g.comp inr) : f = g := by
  /-
    N : Type u_1
    G : Type u_2
    H : Type u_3
    inst✝² : Group N
    inst✝¹ : Group G
    inst✝ : Group H
    φ : MonoidHom G (MulAut N)
    f g : MonoidHom (SemidirectProduct N G φ) H
    hl : Eq (f.comp SemidirectProduct.inl) (g.comp SemidirectProduct.inl)
    hr : Eq (f.comp SemidirectProduct.inr) (g.comp SemidirectProduct.inr)
    ⊢ Eq f g
  -/
  rw [lift_unique f, lift_unique g]
  /-
    N : Type u_1
    G : Type u_2
    H : Type u_3
    inst✝² : Group N
    inst✝¹ : Group G
    inst✝ : Group H
    φ : MonoidHom G (MulAut N)
    f g : MonoidHom (SemidirectProduct N G φ) H
    hl : Eq (f.comp SemidirectProduct.inl) (g.comp SemidirectProduct.inl)
    hr : Eq (f.comp SemidirectProduct.inr) (g.comp SemidirectProduct.inr)
    ⊢ Eq (SemidirectProduct.lift (f.comp SemidirectProduct.inl) (f.comp Semidirect …
  -/
  simp only [*]
  /-
    🎉 no goals
  -/


/-- The homomorphism from a semidirect product of subgroups to the ambient group. -/
@[simps!]
def monoidHomSubgroup {H K : Subgroup G} (h : K ≤ H.normalizer) :
    H ⋊[(H.normalizerMonoidHom).comp (inclusion h)] K →* G :=
                               /-
                                 N : Type u_1
                                 G : Type u_2
                                 H✝ : Type u_3
                                 inst✝² : Group N
                                 inst✝¹ : Group G
                                 inst✝ : Group H✝
                                 φ : MonoidHom G (MulAut N)
                                 fn : MonoidHom N H✝
                                 fg : MonoidHom G H✝
                                 h✝ : ∀ (g : G), Eq (fn.comp (MulEquiv.toMonoidHom (φ g))) ((MulEquiv.toMonoidH …
                                 H K : Subgroup G
                                 h : LE.le K H.normalizer
                                 ⊢ ∀ (g : Subtype fun x => Membership.mem K x), Eq (H.subtype.comp (MulEquiv.to …
                               -/
  lift H.subtype K.subtype (by simp [DFunLike.ext_iff])
                               /-
                                 🎉 no goals
                               -/


/-- The isomorphism from a semidirect product of complementary subgroups to the ambient group. -/
@[simps!]
noncomputable def mulEquivSubgroup {H K : Subgroup G} [H.Normal] (h : H.IsComplement' K) :
    H ⋊[(H.normalizerMonoidHom).comp (inclusion (H.normalizer_eq_top ▸ le_top))] K ≃* G :=
  MulEquiv.ofBijective (monoidHomSubgroup _) ((equivProd.bijective_comp _).mpr h)


/-- Define a map from `N₁ ⋊[φ₁] G₁` to `N₂ ⋊[φ₂] G₂` given maps `N₁ →* N₂` and `G₁ →* G₂` that
  satisfy a commutativity condition `∀ n g, fn (φ₁ g n) = φ₂ (fg g) (fn n)`. -/
def map : N₁ ⋊[φ₁] G₁ →* N₂ ⋊[φ₂] G₂ where
  toFun x := ⟨fn x.1, fg x.2⟩
                 /-
                   N : Type u_1
                   G : Type u_2
                   H : Type u_3
                   inst✝⁶ : Group N
                   inst✝⁵ : Group G
                   inst✝⁴ : Group H
                   φ : MonoidHom G (MulAut N)
                   N₁ : Type u_4
                   G₁ : Type u_5
                   N₂ : Type u_6
                   G₂ : Type u_7
                   inst✝³ : Group N₁
                   inst✝² : Group G₁
                   inst✝¹ : Group N₂
                   inst✝ : Group G₂
                   φ₁ : MonoidHom G₁ (MulAut N₁)
                   φ₂ : MonoidHom G₂ (MulAut N₂)
                   fn : MonoidHom N₁ N₂
                   fg : MonoidHom G₁ G₂
                   h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
                   ⊢ Eq ((fun x => { left := fn x.left, right := fg x.right }) 1) 1
                 -/
  map_one' := by simp
                 /-
                   🎉 no goals
                 -/
  map_mul' x y := by
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝⁶ : Group N
      inst✝⁵ : Group G
      inst✝⁴ : Group H
      φ : MonoidHom G (MulAut N)
      N₁ : Type u_4
      G₁ : Type u_5
      N₂ : Type u_6
      G₂ : Type u_7
      inst✝³ : Group N₁
      inst✝² : Group G₁
      inst✝¹ : Group N₂
      inst✝ : Group G₂
      φ₁ : MonoidHom G₁ (MulAut N₁)
      φ₂ : MonoidHom G₂ (MulAut N₂)
      fn : MonoidHom N₁ N₂
      fg : MonoidHom G₁ G₂
      h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
      x y : SemidirectProduct N₁ G₁ φ₁
      ⊢ Eq ({ toFun := fun x => { left := fn x.left, right := fg x.right }, map_one' …
    -/
    replace h := DFunLike.ext_iff.1 (h x.right) y.left
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝⁶ : Group N
      inst✝⁵ : Group G
      inst✝⁴ : Group H
      φ : MonoidHom G (MulAut N)
      N₁ : Type u_4
      G₁ : Type u_5
      N₂ : Type u_6
      G₂ : Type u_7
      inst✝³ : Group N₁
      inst✝² : Group G₁
      inst✝¹ : Group N₂
      inst✝ : Group G₂
      φ₁ : MonoidHom G₁ (MulAut N₁)
      φ₂ : MonoidHom G₂ (MulAut N₂)
      fn : MonoidHom N₁ N₂
      fg : MonoidHom G₁ G₂
      x y : SemidirectProduct N₁ G₁ φ₁
      h : Eq ((fn.comp (MulEquiv.toMonoidHom (φ₁ x.right))) y.left) (((MulEquiv.toMo …
      ⊢ Eq ({ toFun := fun x => { left := fn x.left, right := fg x.right }, map_one' …
    -/
            /-
              🎉 no goals
            -/
    ext <;> simp_all
            /-
              🎉 no goals
            -/


@[simp]
theorem map_left (g : N₁ ⋊[φ₁] G₁) : (map fn fg h g).left = fn g.left := rfl


@[simp]
theorem map_right (g : N₁ ⋊[φ₁] G₁) : (map fn fg h g).right = fg g.right := rfl


@[simp]
theorem rightHom_comp_map : rightHom.comp (map fn fg h) = fg.comp rightHom := rfl


@[simp]
                                                                  /-
                                                                    N₁ : Type u_4
                                                                    G₁ : Type u_5
                                                                    N₂ : Type u_6
                                                                    G₂ : Type u_7
                                                                    inst✝³ : Group N₁
                                                                    inst✝² : Group G₁
                                                                    inst✝¹ : Group N₂
                                                                    inst✝ : Group G₂
                                                                    φ₁ : MonoidHom G₁ (MulAut N₁)
                                                                    φ₂ : MonoidHom G₂ (MulAut N₂)
                                                                    fn : MonoidHom N₁ N₂
                                                                    fg : MonoidHom G₁ G₂
                                                                    h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
                                                                    n : N₁
                                                                    ⊢ Eq ((SemidirectProduct.map fn fg h) (SemidirectProduct.inl n)) (SemidirectPr …
                                                                  -/
theorem map_inl (n : N₁) : map fn fg h (inl n) = inl (fn n) := by simp [map]
                                                                  /-
                                                                    🎉 no goals
                                                                  -/


@[simp]
                                                                  /-
                                                                    N₁ : Type u_4
                                                                    G₁ : Type u_5
                                                                    N₂ : Type u_6
                                                                    G₂ : Type u_7
                                                                    inst✝³ : Group N₁
                                                                    inst✝² : Group G₁
                                                                    inst✝¹ : Group N₂
                                                                    inst✝ : Group G₂
                                                                    φ₁ : MonoidHom G₁ (MulAut N₁)
                                                                    φ₂ : MonoidHom G₂ (MulAut N₂)
                                                                    fn : MonoidHom N₁ N₂
                                                                    fg : MonoidHom G₁ G₂
                                                                    h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
                                                                    ⊢ Eq ((SemidirectProduct.map fn fg h).comp SemidirectProduct.inl) (SemidirectP …
                                                                  -/
                                                                          /-
                                                                            🎉 no goals
                                                                          -/
theorem map_comp_inl : (map fn fg h).comp inl = inl.comp fn := by ext <;> simp
                                                                          /-
                                                                            🎉 no goals
                                                                          -/


@[simp]
                                                                  /-
                                                                    N₁ : Type u_4
                                                                    G₁ : Type u_5
                                                                    N₂ : Type u_6
                                                                    G₂ : Type u_7
                                                                    inst✝³ : Group N₁
                                                                    inst✝² : Group G₁
                                                                    inst✝¹ : Group N₂
                                                                    inst✝ : Group G₂
                                                                    φ₁ : MonoidHom G₁ (MulAut N₁)
                                                                    φ₂ : MonoidHom G₂ (MulAut N₂)
                                                                    fn : MonoidHom N₁ N₂
                                                                    fg : MonoidHom G₁ G₂
                                                                    h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
                                                                    g : G₁
                                                                    ⊢ Eq ((SemidirectProduct.map fn fg h) (SemidirectProduct.inr g)) (SemidirectPr …
                                                                  -/
theorem map_inr (g : G₁) : map fn fg h (inr g) = inr (fg g) := by simp [map]
                                                                  /-
                                                                    🎉 no goals
                                                                  -/


@[simp]
                                                                  /-
                                                                    N₁ : Type u_4
                                                                    G₁ : Type u_5
                                                                    N₂ : Type u_6
                                                                    G₂ : Type u_7
                                                                    inst✝³ : Group N₁
                                                                    inst✝² : Group G₁
                                                                    inst✝¹ : Group N₂
                                                                    inst✝ : Group G₂
                                                                    φ₁ : MonoidHom G₁ (MulAut N₁)
                                                                    φ₂ : MonoidHom G₂ (MulAut N₂)
                                                                    fn : MonoidHom N₁ N₂
                                                                    fg : MonoidHom G₁ G₂
                                                                    h : ∀ (g : G₁), Eq (fn.comp (MulEquiv.toMonoidHom (φ₁ g))) ((MulEquiv.toMonoid …
                                                                    ⊢ Eq ((SemidirectProduct.map fn fg h).comp SemidirectProduct.inr) (SemidirectP …
                                                                  -/
                                                                          /-
                                                                            🎉 no goals
                                                                          -/
theorem map_comp_inr : (map fn fg h).comp inr = inr.comp fg := by ext <;> simp [map]
                                                                          /-
                                                                            🎉 no goals
                                                                          -/


/-- Define an isomorphism from `N₁ ⋊[φ₁] G₁` to `N₂ ⋊[φ₂] G₂` given isomorphisms `N₁ ≃* N₂` and
  `G₁ ≃* G₂` that satisfy a commutativity condition `∀ n g, fn (φ₁ g n) = φ₂ (fg g) (fn n)`. -/
@[simps]
def congr : N₁ ⋊[φ₁] G₁ ≃* N₂ ⋊[φ₂] G₂ where
  toFun x := ⟨fn x.1, fg x.2⟩
  invFun x := ⟨fn.symm x.1, fg.symm x.2⟩
                   /-
                     N : Type u_1
                     G : Type u_2
                     H : Type u_3
                     inst✝⁶ : Group N
                     inst✝⁵ : Group G
                     inst✝⁴ : Group H
                     φ : MonoidHom G (MulAut N)
                     N₁ : Type u_4
                     G₁ : Type u_5
                     N₂ : Type u_6
                     G₂ : Type u_7
                     inst✝³ : Group N₁
                     inst✝² : Group G₁
                     inst✝¹ : Group N₂
                     inst✝ : Group G₂
                     φ₁ : MonoidHom G₁ (MulAut N₁)
                     φ₂ : MonoidHom G₂ (MulAut N₂)
                     fn : MulEquiv N₁ N₂
                     fg : MulEquiv G₁ G₂
                     h : ∀ (g : G₁), Eq (MulEquiv.trans (φ₁ g) fn) (fn.trans (φ₂ (fg g)))
                     x✝ : SemidirectProduct N₁ G₁ φ₁
                     ⊢ Eq ((fun x => { left := fn.symm x.left, right := fg.symm x.right }) ((fun x  …
                   -/
  left_inv _ := by simp
                   /-
                     🎉 no goals
                   -/
                    /-
                      N : Type u_1
                      G : Type u_2
                      H : Type u_3
                      inst✝⁶ : Group N
                      inst✝⁵ : Group G
                      inst✝⁴ : Group H
                      φ : MonoidHom G (MulAut N)
                      N₁ : Type u_4
                      G₁ : Type u_5
                      N₂ : Type u_6
                      G₂ : Type u_7
                      inst✝³ : Group N₁
                      inst✝² : Group G₁
                      inst✝¹ : Group N₂
                      inst✝ : Group G₂
                      φ₁ : MonoidHom G₁ (MulAut N₁)
                      φ₂ : MonoidHom G₂ (MulAut N₂)
                      fn : MulEquiv N₁ N₂
                      fg : MulEquiv G₁ G₂
                      h : ∀ (g : G₁), Eq (MulEquiv.trans (φ₁ g) fn) (fn.trans (φ₂ (fg g)))
                      x✝ : SemidirectProduct N₂ G₂ φ₂
                      ⊢ Eq ((fun x => { left := fn x.left, right := fg x.right }) ((fun x => { left  …
                    -/
  right_inv _ := by simp
                    /-
                      🎉 no goals
                    -/
  map_mul' x y := by
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝⁶ : Group N
      inst✝⁵ : Group G
      inst✝⁴ : Group H
      φ : MonoidHom G (MulAut N)
      N₁ : Type u_4
      G₁ : Type u_5
      N₂ : Type u_6
      G₂ : Type u_7
      inst✝³ : Group N₁
      inst✝² : Group G₁
      inst✝¹ : Group N₂
      inst✝ : Group G₂
      φ₁ : MonoidHom G₁ (MulAut N₁)
      φ₂ : MonoidHom G₂ (MulAut N₂)
      fn : MulEquiv N₁ N₂
      fg : MulEquiv G₁ G₂
      h : ∀ (g : G₁), Eq (MulEquiv.trans (φ₁ g) fn) (fn.trans (φ₂ (fg g)))
      x y : SemidirectProduct N₁ G₁ φ₁
      ⊢ Eq ({ toFun := fun x => { left := fn x.left, right := fg x.right }, invFun : …
    -/
    replace h := DFunLike.ext_iff.1 (h x.right) y.left
    /-
      N : Type u_1
      G : Type u_2
      H : Type u_3
      inst✝⁶ : Group N
      inst✝⁵ : Group G
      inst✝⁴ : Group H
      φ : MonoidHom G (MulAut N)
      N₁ : Type u_4
      G₁ : Type u_5
      N₂ : Type u_6
      G₂ : Type u_7
      inst✝³ : Group N₁
      inst✝² : Group G₁
      inst✝¹ : Group N₂
      inst✝ : Group G₂
      φ₁ : MonoidHom G₁ (MulAut N₁)
      φ₂ : MonoidHom G₂ (MulAut N₂)
      fn : MulEquiv N₁ N₂
      fg : MulEquiv G₁ G₂
      x y : SemidirectProduct N₁ G₁ φ₁
      h : Eq ((MulEquiv.trans (φ₁ x.right) fn) y.left) ((fn.trans (φ₂ (fg x.right))) …
      ⊢ Eq ({ toFun := fun x => { left := fn x.left, right := fg x.right }, invFun : …
    -/
            /-
              🎉 no goals
            -/
    ext <;> simp_all
            /-
              🎉 no goals
            -/


/-- Define a isomorphism from `N₁ ⋊[φ₁] G₁` to `N₂ ⋊[φ₂] G₂` without specifying `φ₂`. -/
@[simps!]
def congr' :
    N₁ ⋊[φ₁] G₁ ≃* N₂ ⋊[MonoidHom.comp (MulAut.congr fn) (φ₁.comp fg.symm)] G₂ :=
                          /-
                            N : Type u_1
                            G : Type u_2
                            H : Type u_3
                            inst✝⁶ : Group N
                            inst✝⁵ : Group G
                            inst✝⁴ : Group H
                            φ : MonoidHom G (MulAut N)
                            N₁ : Type u_4
                            G₁ : Type u_5
                            N₂ : Type u_6
                            G₂ : Type u_7
                            inst✝³ : Group N₁
                            inst✝² : Group G₁
                            inst✝¹ : Group N₂
                            inst✝ : Group G₂
                            φ₁ : MonoidHom G₁ (MulAut N₁)
                            φ₂ : MonoidHom G₂ (MulAut N₂)
                            fn : MulEquiv N₁ N₂
                            fg : MulEquiv G₁ G₂
                            h : ∀ (g : G₁), Eq (MulEquiv.trans (φ₁ g) fn) (fn.trans (φ₂ (fg g)))
                            x✝ : G₁
                            ⊢ Eq (MulEquiv.trans (φ₁ x✝) fn) (fn.trans (((↑(MulAut.congr fn)).comp (φ₁.com …
                          -/
  congr fn fg (fun _ ↦ by ext; simp)
                               /-
                                 🎉 no goals
                               -/


