/-- The order topology on an ordered type is the topology generated by open intervals. We register
it on a preorder, but it is mostly interesting in linear orders, where it is also order-closed.
We define it as a mixin. If you want to introduce the order topology on a preorder, use
`Preorder.topology`. -/
class OrderTopology (α : Type*) [t : TopologicalSpace α] [Preorder α] : Prop where
  /-- The topology is generated by open intervals `Set.Ioi _` and `Set.Iio _`. -/
  topology_eq_generate_intervals : t = generateFrom { s | ∃ a, s = Ioi a ∨ s = Iio a }


/-- (Order) topology on a partial order `α` generated by the subbase of open intervals
`(a, ∞) = { x ∣ a < x }, (-∞ , b) = {x ∣ x < b}` for all `a, b` in `α`. We do not register it as an
instance as many ordered sets are already endowed with the same topology, most often in a non-defeq
way though. Register as a local instance when necessary. -/
def Preorder.topology (α : Type*) [Preorder α] : TopologicalSpace α :=
  generateFrom { s : Set α | ∃ a : α, s = { b : α | a < b } ∨ s = { b : α | b < a } }


instance [t : OrderTopology α] : OrderTopology αᵒᵈ :=
  ⟨by
    /-
      α : Type u
      β : Type v
      γ : Type w
      inst✝¹ : TopologicalSpace α
      inst✝ : Preorder α
      t : OrderTopology α
      ⊢ Eq OrderDual.instTopologicalSpace (TopologicalSpace.generateFrom (setOf fun  …
    -/
    convert OrderTopology.topology_eq_generate_intervals (α := α) using 6
    /-
      case h.e'_3.h.h.e'_2.h.h.e'_2.h.h.h.e'_2.h.h.a
      α : Type u
      β : Type v
      γ : Type w
      inst✝¹ : TopologicalSpace α
      inst✝ : Preorder α
      t : OrderTopology α
      e_1✝² : Eq (TopologicalSpace (OrderDual α)) (TopologicalSpace α)
      e_1✝¹ : Eq (OrderDual α) α
      e_1✝ : Eq (Set (OrderDual α)) (Set α)
      x✝¹ : Set (OrderDual α)
      x✝ : OrderDual α
      ⊢ Iff (Or (Eq x✝¹ (Set.Ioi x✝)) (Eq x✝¹ (Set.Iio x✝))) (Or (Eq x✝¹ (Set.Ioi x✝ …
    -/
    apply or_comm⟩
    /-
      🎉 no goals
    -/


theorem isOpen_iff_generate_intervals [t : OrderTopology α] {s : Set α} :
    IsOpen s ↔ GenerateOpen { s | ∃ a, s = Ioi a ∨ s = Iio a } s := by
  /-
    α : Type u
    inst✝¹ : TopologicalSpace α
    inst✝ : Preorder α
    t : OrderTopology α
    s : Set α
    ⊢ Iff (IsOpen s) (TopologicalSpace.GenerateOpen (setOf fun s => Exists fun a = …
  -/
  rw [t.topology_eq_generate_intervals]; rfl
                                         /-
                                           🎉 no goals
                                         -/


theorem isOpen_lt' [OrderTopology α] (a : α) : IsOpen { b : α | a < b } :=
  isOpen_iff_generate_intervals.2 <| .basic _ ⟨a, .inl rfl⟩


theorem isOpen_gt' [OrderTopology α] (a : α) : IsOpen { b : α | b < a } :=
  isOpen_iff_generate_intervals.2 <| .basic _ ⟨a, .inr rfl⟩


theorem lt_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : ∀ᶠ x in 𝓝 b, a < x :=
  (isOpen_lt' _).mem_nhds h


theorem le_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : ∀ᶠ x in 𝓝 b, a ≤ x :=
  (lt_mem_nhds h).mono fun _ => le_of_lt


theorem gt_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : ∀ᶠ x in 𝓝 a, x < b :=
  (isOpen_gt' _).mem_nhds h


theorem ge_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : ∀ᶠ x in 𝓝 a, x ≤ b :=
  (gt_mem_nhds h).mono fun _ => le_of_lt


theorem nhds_eq_order [OrderTopology α] (a : α) :
    𝓝 a = (⨅ b ∈ Iio a, 𝓟 (Ioi b)) ⊓ ⨅ b ∈ Ioi a, 𝓟 (Iio b) := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ⊢ Eq (nhds a) (Min.min (iInf fun b => iInf fun h => Filter.principal (Set.Ioi  …
  -/
  rw [OrderTopology.topology_eq_generate_intervals (α := α), nhds_generateFrom]
  simp_rw [mem_setOf_eq, @and_comm (a ∈ _), exists_or, or_and_right, iInf_or, iInf_and,
    iInf_exists, iInf_inf_eq, iInf_comm (ι := Set α), iInf_iInf_eq_left, mem_Ioi, mem_Iio]


theorem tendsto_order [OrderTopology α] {f : β → α} {a : α} {x : Filter β} :
    Tendsto f x (𝓝 a) ↔ (∀ a' < a, ∀ᶠ b in x, a' < f b) ∧ ∀ a' > a, ∀ᶠ b in x, f b < a' := by
  /-
    α : Type u
    β : Type v
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    f : β → α
    a : α
    x : Filter β
    ⊢ Iff (Filter.Tendsto f x (nhds a)) (And (∀ (a' : α), LT.lt a' a → Filter.Even …
  -/
  simp only [nhds_eq_order a, tendsto_inf, tendsto_iInf, tendsto_principal]; rfl
                                                                             /-
                                                                               🎉 no goals
                                                                             -/

instance tendstoIccClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Icc (𝓝 a) (𝓝 a) := by
  /-
    α : Type u
    β : Type v
    γ : Type w
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ⊢ Filter.TendstoIxxClass Set.Icc (nhds a) (nhds a)
  -/
  simp only [nhds_eq_order, iInf_subtype']
  refine
    ((hasBasis_iInf_principal_finite _).inf (hasBasis_iInf_principal_finite _)).tendstoIxxClass
      fun s _ => ?_
  /-
    α : Type u
    β : Type v
    γ : Type w
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    s : Prod (Set (Subtype (Membership.mem (Set.Iio a)))) (Set (Subtype (Membershi …
    x✝ : And s.1.Finite s.2.Finite
    ⊢ ∀ (x : α), Membership.mem (Inter.inter (Set.iInter fun i => Set.iInter fun h …
  -/
  refine ((ordConnected_biInter ?_).inter (ordConnected_biInter ?_)).out <;> intro _ _
  /-
    case refine_1
    α : Type u
    β : Type v
    γ : Type w
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    s : Prod (Set (Subtype (Membership.mem (Set.Iio a)))) (Set (Subtype (Membershi …
    x✝ : And s.1.Finite s.2.Finite
    i✝ : Subtype (Membership.mem (Set.Iio a))
    hi✝ : Membership.mem s.1 i✝
    ⊢ (Set.Ioi ↑i✝).OrdConnected
  -/
  exacts [ordConnected_Ioi, ordConnected_Iio]
  /-
    🎉 no goals
  -/


instance tendstoIcoClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ico (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ico_subset_Icc_self


instance tendstoIocClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ioc (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ioc_subset_Icc_self


instance tendstoIooClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ioo (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ioo_subset_Icc_self


/-- **Squeeze theorem** (also known as **sandwich theorem**). This version assumes that inequalities
hold eventually for the filter. -/
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le' [OrderTopology α] {f g h : β → α} {b : Filter β}
    {a : α} (hg : Tendsto g b (𝓝 a)) (hh : Tendsto h b (𝓝 a)) (hgf : ∀ᶠ b in b, g b ≤ f b)
    (hfh : ∀ᶠ b in b, f b ≤ h b) : Tendsto f b (𝓝 a) :=
  (hg.Icc hh).of_smallSets <| hgf.and hfh


/-- **Squeeze theorem** (also known as **sandwich theorem**). This version assumes that inequalities
hold everywhere. -/
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le [OrderTopology α] {f g h : β → α} {b : Filter β}
    {a : α} (hg : Tendsto g b (𝓝 a)) (hh : Tendsto h b (𝓝 a)) (hgf : g ≤ f) (hfh : f ≤ h) :
    Tendsto f b (𝓝 a) :=
  tendsto_of_tendsto_of_tendsto_of_le_of_le' hg hh (Eventually.of_forall hgf)
    (Eventually.of_forall hfh)


theorem nhds_order_unbounded [OrderTopology α] {a : α} (hu : ∃ u, a < u) (hl : ∃ l, l < a) :
    𝓝 a = ⨅ (l) (_ : l < a) (u) (_ : a < u), 𝓟 (Ioo l u) := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    hu : Exists fun u => LT.lt a u
    hl : Exists fun l => LT.lt l a
    ⊢ Eq (nhds a) (iInf fun l => iInf fun x => iInf fun u => iInf fun x => Filter. …
  -/
  simp only [nhds_eq_order, ← inf_biInf, ← biInf_inf, *, ← inf_principal, ← Ioi_inter_Iio]; rfl
                                                                                            /-
                                                                                              🎉 no goals
                                                                                            -/


theorem tendsto_order_unbounded [OrderTopology α] {f : β → α} {a : α} {x : Filter β}
    (hu : ∃ u, a < u) (hl : ∃ l, l < a) (h : ∀ l u, l < a → a < u → ∀ᶠ b in x, l < f b ∧ f b < u) :
    Tendsto f x (𝓝 a) := by
  /-
    α : Type u
    β : Type v
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    f : β → α
    a : α
    x : Filter β
    hu : Exists fun u => LT.lt a u
    hl : Exists fun l => LT.lt l a
    h : ∀ (l u : α), LT.lt l a → LT.lt a u → Filter.Eventually (fun b => And (LT.l …
    ⊢ Filter.Tendsto f x (nhds a)
  -/
  simp only [nhds_order_unbounded hu hl, tendsto_iInf, tendsto_principal]
  /-
    α : Type u
    β : Type v
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    f : β → α
    a : α
    x : Filter β
    hu : Exists fun u => LT.lt a u
    hl : Exists fun l => LT.lt l a
    h : ∀ (l u : α), LT.lt l a → LT.lt a u → Filter.Eventually (fun b => And (LT.l …
    ⊢ ∀ (i : α), LT.lt i a → ∀ (i_2 : α), LT.lt a i_2 → Filter.Eventually (fun a = …
  -/
  exact fun l hl u => h l u hl
  /-
    🎉 no goals
  -/


instance tendstoIxxNhdsWithin {α : Type*} [TopologicalSpace α] (a : α) {s t : Set α}
    {Ixx} [TendstoIxxClass Ixx (𝓝 a) (𝓝 a)] [TendstoIxxClass Ixx (𝓟 s) (𝓟 t)] :
    TendstoIxxClass Ixx (𝓝[s] a) (𝓝[t] a) :=
  Filter.tendstoIxxClass_inf


instance tendstoIccClassNhdsPi {ι : Type*} {α : ι → Type*} [∀ i, Preorder (α i)]
    [∀ i, TopologicalSpace (α i)] [∀ i, OrderTopology (α i)] (f : ∀ i, α i) :
    TendstoIxxClass Icc (𝓝 f) (𝓝 f) := by
  /-
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    ⊢ Filter.TendstoIxxClass Set.Icc (nhds f) (nhds f)
  -/
  constructor
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    ⊢ Filter.Tendsto (fun p => Set.Icc p.1 p.2) (SProd.sprod (nhds f) (nhds f)) (n …
  -/
  conv in (𝓝 f).smallSets => rw [nhds_pi, Filter.pi]
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    ⊢ Filter.Tendsto (fun p => Set.Icc p.1 p.2) (SProd.sprod (nhds f) (nhds f)) (i …
  -/
  simp only [smallSets_iInf, smallSets_comap_eq_comap_image, tendsto_iInf, tendsto_comap_iff]
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    ⊢ ∀ (i : ι), Filter.Tendsto (Function.comp (Set.image (Function.eval i)) fun p …
  -/
  intro i
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    i : ι
    ⊢ Filter.Tendsto (Function.comp (Set.image (Function.eval i)) fun p => Set.Icc …
  -/
  have : Tendsto (fun g : ∀ i, α i => g i) (𝓝 f) (𝓝 (f i)) := (continuous_apply i).tendsto f
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    i : ι
    this : Filter.Tendsto (fun g => g i) (nhds f) (nhds (f i))
    ⊢ Filter.Tendsto (Function.comp (Set.image (Function.eval i)) fun p => Set.Icc …
  -/
  refine (this.comp tendsto_fst).Icc (this.comp tendsto_snd) |>.smallSets_mono ?_
  /-
    case tendsto_Ixx
    α✝ : Type u
    β : Type v
    γ : Type w
    ι : Type u_1
    α : ι → Type u_2
    inst✝² : (i : ι) → Preorder (α i)
    inst✝¹ : (i : ι) → TopologicalSpace (α i)
    inst✝ : ∀ (i : ι), OrderTopology (α i)
    f : (i : ι) → α i
    i : ι
    this : Filter.Tendsto (fun g => g i) (nhds f) (nhds (f i))
    ⊢ Filter.Eventually (fun x => HasSubset.Subset (Function.comp (Set.image (Func …
  -/
  filter_upwards [] using fun ⟨f, g⟩ ↦ image_subset_iff.mpr fun p hp ↦ ⟨hp.1 i, hp.2 i⟩
  /-
    🎉 no goals
  -/


theorem induced_topology_le_preorder [Preorder α] [Preorder β] [TopologicalSpace β]
    [OrderTopology β] {f : α → β} (hf : ∀ {x y}, f x < f y ↔ x < y) :
    induced f ‹TopologicalSpace β› ≤ Preorder.topology α := by
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    ⊢ LE.le (TopologicalSpace.induced f inst✝¹) (Preorder.topology α)
  -/
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    ⊢ LE.le (TopologicalSpace.induced f inst✝¹) (Preorder.topology α)
  -/
  refine le_of_nhds_le_nhds fun x => ?_
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    x : α
    ⊢ LE.le (nhds x) (nhds x)
  -/
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal, Ioi, Iio, ← hf]
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    x : α
    ⊢ LE.le (Min.min (iInf fun i => iInf fun x => Filter.principal (Set.preimage f …
  -/
  refine inf_le_inf (le_iInf₂ fun a ha => ?_) (le_iInf₂ fun a ha => ?_)
  /-
    case refine_1
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    x a : α
    ha : Membership.mem (setOf fun x_1 => LT.lt (f x_1) (f x)) a
    ⊢ LE.le (iInf fun i => iInf fun x => Filter.principal (Set.preimage f (setOf f …
  -/
  exacts [iInf₂_le (f a) ha, iInf₂_le (f a) ha]
  /-
    🎉 no goals
  -/


theorem induced_topology_eq_preorder [Preorder α] [Preorder β] [TopologicalSpace β]
    [OrderTopology β] {f : α → β} (hf : ∀ {x y}, f x < f y ↔ x < y)
    (H₁ : ∀ {a b x}, b < f a → ¬(b < f x) → ∃ y, y < a ∧ b ≤ f y)
    (H₂ : ∀ {a b x}, f a < b → ¬(f x < b) → ∃ y, a < y ∧ f y ≤ b) :
    induced f ‹TopologicalSpace β› = Preorder.topology α := by
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
    H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
    ⊢ Eq (TopologicalSpace.induced f inst✝¹) (Preorder.topology α)
  -/
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
    H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    ⊢ Eq (TopologicalSpace.induced f inst✝¹) (Preorder.topology α)
  -/
  refine le_antisymm (induced_topology_le_preorder hf) ?_
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
    H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    ⊢ LE.le (Preorder.topology α) (TopologicalSpace.induced f inst✝¹)
  -/
  refine le_of_nhds_le_nhds fun a => ?_
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
    H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    a : α
    ⊢ LE.le (nhds a) (nhds a)
  -/
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal]
  /-
    α : Type u
    β : Type v
    inst✝³ : Preorder α
    inst✝² : Preorder β
    inst✝¹ : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
    H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
    H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
    x✝ : TopologicalSpace α := Preorder.topology α
    this : OrderTopology α
    a : α
    ⊢ LE.le (Min.min (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (i …
  -/
  refine inf_le_inf (le_iInf₂ fun b hb => ?_) (le_iInf₂ fun b hb => ?_)
    /-
      case refine_1
      α : Type u
      β : Type v
      inst✝³ : Preorder α
      inst✝² : Preorder β
      inst✝¹ : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
      H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
      H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
      x✝ : TopologicalSpace α := Preorder.topology α
      this : OrderTopology α
      a : α
      b : β
      hb : Membership.mem (Set.Iio (f a)) b
      ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (Filter.pri …
    -/
  · rcases em (∃ x, ¬(b < f x)) with (⟨x, hx⟩ | hb)
      /-
        case refine_1.inl.intro
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb : Membership.mem (Set.Iio (f a)) b
        x : α
        hx : Not (LT.lt b (f x))
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (Filter.pri …
      -/
    · rcases H₁ hb hx with ⟨y, hya, hyb⟩
      /-
        case refine_1.inl.intro.intro.intro
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb : Membership.mem (Set.Iio (f a)) b
        x : α
        hx : Not (LT.lt b (f x))
        y : α
        hya : LT.lt y a
        hyb : LE.le b (f y)
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (Filter.pri …
      -/
      exact iInf₂_le_of_le y hya (principal_mono.2 fun z hz => hyb.trans_lt (hf.2 hz))
      /-
        🎉 no goals
      -/
      /-
        case refine_1.inr
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb✝ : Membership.mem (Set.Iio (f a)) b
        hb : Not (Exists fun x => Not (LT.lt b (f x)))
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (Filter.pri …
      -/
    · push_neg at hb
      /-
        case refine_1.inr
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb✝ : Membership.mem (Set.Iio (f a)) b
        hb : ∀ (x : α), LT.lt b (f x)
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Ioi b)) (Filter.pri …
      -/
      exact le_principal_iff.2 (univ_mem' hb)
      /-
        🎉 no goals
      -/
    /-
      case refine_2
      α : Type u
      β : Type v
      inst✝³ : Preorder α
      inst✝² : Preorder β
      inst✝¹ : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
      H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
      H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
      x✝ : TopologicalSpace α := Preorder.topology α
      this : OrderTopology α
      a : α
      b : β
      hb : Membership.mem (Set.Ioi (f a)) b
      ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Iio b)) (Filter.pri …
    -/
  · rcases em (∃ x, ¬(f x < b)) with (⟨x, hx⟩ | hb)
      /-
        case refine_2.inl.intro
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb : Membership.mem (Set.Ioi (f a)) b
        x : α
        hx : Not (LT.lt (f x) b)
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Iio b)) (Filter.pri …
      -/
    · rcases H₂ hb hx with ⟨y, hya, hyb⟩
      /-
        case refine_2.inl.intro.intro.intro
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb : Membership.mem (Set.Ioi (f a)) b
        x : α
        hx : Not (LT.lt (f x) b)
        y : α
        hya : LT.lt a y
        hyb : LE.le (f y) b
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Iio b)) (Filter.pri …
      -/
      exact iInf₂_le_of_le y hya (principal_mono.2 fun z hz => (hf.2 hz).trans_le hyb)
      /-
        🎉 no goals
      -/
      /-
        case refine_2.inr
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb✝ : Membership.mem (Set.Ioi (f a)) b
        hb : Not (Exists fun x => Not (LT.lt (f x) b))
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Iio b)) (Filter.pri …
      -/
    · push_neg at hb
      /-
        case refine_2.inr
        α : Type u
        β : Type v
        inst✝³ : Preorder α
        inst✝² : Preorder β
        inst✝¹ : TopologicalSpace β
        inst✝ : OrderTopology β
        f : α → β
        hf : ∀ {x y : α}, Iff (LT.lt (f x) (f y)) (LT.lt x y)
        H₁ : ∀ {a : α} {b : β} {x : α}, LT.lt b (f a) → Not (LT.lt b (f x)) → Exists f …
        H₂ : ∀ {a : α} {b : β} {x : α}, LT.lt (f a) b → Not (LT.lt (f x) b) → Exists f …
        x✝ : TopologicalSpace α := Preorder.topology α
        this : OrderTopology α
        a : α
        b : β
        hb✝ : Membership.mem (Set.Ioi (f a)) b
        hb : ∀ (x : α), LT.lt (f x) b
        ⊢ LE.le (iInf fun b => iInf fun h => Filter.principal (Set.Iio b)) (Filter.pri …
      -/
      exact le_principal_iff.2 (univ_mem' hb)
      /-
        🎉 no goals
      -/


theorem induced_orderTopology' {α : Type u} {β : Type v} [Preorder α] [ta : TopologicalSpace β]
    [Preorder β] [OrderTopology β] (f : α → β) (hf : ∀ {x y}, f x < f y ↔ x < y)
    (H₁ : ∀ {a x}, x < f a → ∃ b < a, x ≤ f b) (H₂ : ∀ {a x}, f a < x → ∃ b > a, f b ≤ x) :
    @OrderTopology _ (induced f ta) _ :=
  let _ := induced f ta
  ⟨induced_topology_eq_preorder hf (fun h _ => H₁ h) (fun h _ => H₂ h)⟩


theorem induced_orderTopology {α : Type u} {β : Type v} [Preorder α] [ta : TopologicalSpace β]
    [Preorder β] [OrderTopology β] (f : α → β) (hf : ∀ {x y}, f x < f y ↔ x < y)
    (H : ∀ {x y}, x < y → ∃ a, x < f a ∧ f a < y) : @OrderTopology _ (induced f ta) _ :=
  induced_orderTopology' f (hf)
    (fun xa => let ⟨b, xb, ba⟩ := H xa; ⟨b, hf.1 ba, le_of_lt xb⟩)
    fun ax => let ⟨b, ab, bx⟩ := H ax; ⟨b, hf.1 ab, le_of_lt bx⟩


/-- The topology induced by a strictly monotone function with order-connected range is the preorder
topology. -/
nonrec theorem StrictMono.induced_topology_eq_preorder {α β : Type*} [LinearOrder α]
    [LinearOrder β] [t : TopologicalSpace β] [OrderTopology β] {f : α → β}
    (hf : StrictMono f) (hc : OrdConnected (range f)) : t.induced f = Preorder.topology α := by
  /-
    α : Type u_1
    β : Type u_2
    inst✝² : LinearOrder α
    inst✝¹ : LinearOrder β
    t : TopologicalSpace β
    inst✝ : OrderTopology β
    f : α → β
    hf : StrictMono f
    hc : (Set.range f).OrdConnected
    ⊢ Eq (TopologicalSpace.induced f t) (Preorder.topology α)
  -/
  refine induced_topology_eq_preorder hf.lt_iff_lt (fun h₁ h₂ => ?_) fun h₁ h₂ => ?_
    /-
      case refine_1
      α : Type u_1
      β : Type u_2
      inst✝² : LinearOrder α
      inst✝¹ : LinearOrder β
      t : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : StrictMono f
      hc : (Set.range f).OrdConnected
      a✝ : α
      b✝ : β
      x✝ : α
      h₁ : LT.lt b✝ (f a✝)
      h₂ : Not (LT.lt b✝ (f x✝))
      ⊢ Exists fun y => And (LT.lt y a✝) (LE.le b✝ (f y))
    -/
  · rcases hc.out (mem_range_self _) (mem_range_self _) ⟨not_lt.1 h₂, h₁.le⟩ with ⟨y, rfl⟩
    /-
      case refine_1.intro
      α : Type u_1
      β : Type u_2
      inst✝² : LinearOrder α
      inst✝¹ : LinearOrder β
      t : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : StrictMono f
      hc : (Set.range f).OrdConnected
      a✝ x✝ y : α
      h₁ : LT.lt (f y) (f a✝)
      h₂ : Not (LT.lt (f y) (f x✝))
      ⊢ Exists fun y_1 => And (LT.lt y_1 a✝) (LE.le (f y) (f y_1))
    -/
    exact ⟨y, hf.lt_iff_lt.1 h₁, le_rfl⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_2
      α : Type u_1
      β : Type u_2
      inst✝² : LinearOrder α
      inst✝¹ : LinearOrder β
      t : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : StrictMono f
      hc : (Set.range f).OrdConnected
      a✝ : α
      b✝ : β
      x✝ : α
      h₁ : LT.lt (f a✝) b✝
      h₂ : Not (LT.lt (f x✝) b✝)
      ⊢ Exists fun y => And (LT.lt a✝ y) (LE.le (f y) b✝)
    -/
  · rcases hc.out (mem_range_self _) (mem_range_self _) ⟨h₁.le, not_lt.1 h₂⟩ with ⟨y, rfl⟩
    /-
      case refine_2.intro
      α : Type u_1
      β : Type u_2
      inst✝² : LinearOrder α
      inst✝¹ : LinearOrder β
      t : TopologicalSpace β
      inst✝ : OrderTopology β
      f : α → β
      hf : StrictMono f
      hc : (Set.range f).OrdConnected
      a✝ x✝ y : α
      h₁ : LT.lt (f a✝) (f y)
      h₂ : Not (LT.lt (f x✝) (f y))
      ⊢ Exists fun y_1 => And (LT.lt a✝ y_1) (LE.le (f y_1) (f y))
    -/
    exact ⟨y, hf.lt_iff_lt.1 h₁, le_rfl⟩
    /-
      🎉 no goals
    -/


/-- A strictly monotone function between linear orders with order topology is a topological
embedding provided that the range of `f` is order-connected. -/
theorem StrictMono.isEmbedding_of_ordConnected {α β : Type*} [LinearOrder α] [LinearOrder β]
    [TopologicalSpace α] [h : OrderTopology α] [TopologicalSpace β] [OrderTopology β] {f : α → β}
    (hf : StrictMono f) (hc : OrdConnected (range f)) : IsEmbedding f :=
  ⟨⟨h.1.trans <| Eq.symm <| hf.induced_topology_eq_preorder hc⟩, hf.injective⟩


@[deprecated (since := "2024-10-26")]
alias StrictMono.embedding_of_ordConnected := StrictMono.isEmbedding_of_ordConnected


/-- On a `Set.OrdConnected` subset of a linear order, the order topology for the restriction of the
order is the same as the restriction to the subset of the order topology. -/
instance orderTopology_of_ordConnected {α : Type u} [TopologicalSpace α] [LinearOrder α]
    [OrderTopology α] {t : Set α} [ht : OrdConnected t] : OrderTopology t :=
  ⟨(Subtype.strictMono_coe t).induced_topology_eq_preorder <| by
    /-
      α✝ : Type u
      β : Type v
      γ : Type w
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      t : Set α
      ht : t.OrdConnected
      ⊢ (Set.range Subtype.val).OrdConnected
    -/
    rwa [← @Subtype.range_val _ t] at ht⟩
    /-
      🎉 no goals
    -/


theorem nhdsGE_eq_iInf_inf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] (a : α) :
    𝓝[≥] a = (⨅ (u) (_ : a < u), 𝓟 (Iio u)) ⊓ 𝓟 (Ici a) := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ⊢ Eq (nhdsWithin a (Set.Ici a)) (Min.min (iInf fun u => iInf fun x => Filter.p …
  -/
  rw [nhdsWithin, nhds_eq_order]
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ⊢ Eq (Min.min (Min.min (iInf fun b => iInf fun h => Filter.principal (Set.Ioi  …
  -/
  refine le_antisymm (inf_le_inf_right _ inf_le_right) (le_inf (le_inf ?_ inf_le_left) inf_le_right)
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ⊢ LE.le (Min.min (iInf fun u => iInf fun x => Filter.principal (Set.Iio u)) (F …
  -/
  exact inf_le_right.trans (le_iInf₂ fun l hl => principal_mono.2 <| Ici_subset_Ioi.2 hl)
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Ici_eq'' := nhdsGE_eq_iInf_inf_principal


theorem nhdsLE_eq_iInf_inf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] (a : α) :
    𝓝[≤] a = (⨅ l < a, 𝓟 (Ioi l)) ⊓ 𝓟 (Iic a) :=
  nhdsGE_eq_iInf_inf_principal (toDual a)


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Iic_eq'' := nhdsLE_eq_iInf_inf_principal


theorem nhdsGE_eq_iInf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] {a : α}
    (ha : ∃ u, a < u) : 𝓝[≥] a = ⨅ (u) (_ : a < u), 𝓟 (Ico a u) := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ha : Exists fun u => LT.lt a u
    ⊢ Eq (nhdsWithin a (Set.Ici a)) (iInf fun u => iInf fun x => Filter.principal  …
  -/
  simp only [nhdsGE_eq_iInf_inf_principal, biInf_inf ha, inf_principal, Iio_inter_Ici]
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Ici_eq' := nhdsGE_eq_iInf_principal


theorem nhdsLE_eq_iInf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] {a : α}
    (ha : ∃ l, l < a) : 𝓝[≤] a = ⨅ l < a, 𝓟 (Ioc l a) := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : Preorder α
    inst✝ : OrderTopology α
    a : α
    ha : Exists fun l => LT.lt l a
    ⊢ Eq (nhdsWithin a (Set.Iic a)) (iInf fun l => iInf fun h => Filter.principal  …
  -/
  simp only [nhdsLE_eq_iInf_inf_principal, biInf_inf ha, inf_principal, Ioi_inter_Iic]
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Iic_eq' := nhdsLE_eq_iInf_principal


theorem nhdsGE_basis_of_exists_gt [TopologicalSpace α] [LinearOrder α] [OrderTopology α] {a : α}
    (ha : ∃ u, a < u) : (𝓝[≥] a).HasBasis (fun u => a < u) fun u => Ico a u :=
  (nhdsGE_eq_iInf_principal ha).symm ▸
    hasBasis_biInf_principal
      (fun b hb c hc => ⟨min b c, lt_min hb hc, Ico_subset_Ico_right (min_le_left _ _),
        Ico_subset_Ico_right (min_le_right _ _)⟩)
      ha


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Ici_basis' := nhdsGE_basis_of_exists_gt


theorem nhdsLE_basis_of_exists_lt [TopologicalSpace α] [LinearOrder α] [OrderTopology α] {a : α}
    (ha : ∃ l, l < a) : (𝓝[≤] a).HasBasis (fun l => l < a) fun l => Ioc l a := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    ha : Exists fun l => LT.lt l a
    ⊢ (nhdsWithin a (Set.Iic a)).HasBasis (fun l => LT.lt l a) fun l => Set.Ioc l a
  -/
  convert nhdsGE_basis_of_exists_gt (α := αᵒᵈ) ha using 2
  /-
    case h.e'_5.h.h
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    ha : Exists fun l => LT.lt l a
    e_1✝ : Eq α (OrderDual α)
    x✝ : α
    ⊢ Eq (Set.Ioc x✝ a) (Set.Ico a x✝)
  -/
  exact dual_Ico.symm
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Iic_basis' := nhdsLE_basis_of_exists_lt


theorem nhdsGE_basis [TopologicalSpace α] [LinearOrder α] [OrderTopology α] [NoMaxOrder α] (a : α) :
    (𝓝[≥] a).HasBasis (fun u => a < u) fun u => Ico a u :=
  nhdsGE_basis_of_exists_gt (exists_gt a)


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Ici_basis := nhdsGE_basis


theorem nhdsLE_basis [TopologicalSpace α] [LinearOrder α] [OrderTopology α] [NoMinOrder α] (a : α) :
    (𝓝[≤] a).HasBasis (fun l => l < a) fun l => Ioc l a :=
  nhdsLE_basis_of_exists_lt (exists_lt a)


@[deprecated (since := "2024-12-22")] alias nhdsWithin_Iic_basis := nhdsLE_basis


theorem nhds_top_order [TopologicalSpace α] [Preorder α] [OrderTop α] [OrderTopology α] :
                                                   /-
                                                     α : Type u
                                                     inst✝³ : TopologicalSpace α
                                                     inst✝² : Preorder α
                                                     inst✝¹ : OrderTop α
                                                     inst✝ : OrderTopology α
                                                     ⊢ Eq (nhds Top.top) (iInf fun l => iInf fun x => Filter.principal (Set.Ioi l))
                                                   -/
    𝓝 (⊤ : α) = ⨅ (l) (_ : l < ⊤), 𝓟 (Ioi l) := by simp [nhds_eq_order (⊤ : α)]
                                                   /-
                                                     🎉 no goals
                                                   -/


theorem nhds_bot_order [TopologicalSpace α] [Preorder α] [OrderBot α] [OrderTopology α] :
                                                   /-
                                                     α : Type u
                                                     inst✝³ : TopologicalSpace α
                                                     inst✝² : Preorder α
                                                     inst✝¹ : OrderBot α
                                                     inst✝ : OrderTopology α
                                                     ⊢ Eq (nhds Bot.bot) (iInf fun l => iInf fun x => Filter.principal (Set.Iio l))
                                                   -/
    𝓝 (⊥ : α) = ⨅ (l) (_ : ⊥ < l), 𝓟 (Iio l) := by simp [nhds_eq_order (⊥ : α)]
                                                   /-
                                                     🎉 no goals
                                                   -/


theorem nhds_top_basis [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
    [Nontrivial α] : (𝓝 ⊤).HasBasis (fun a : α => a < ⊤) fun a : α => Ioi a := by
  /-
    α : Type u
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTop α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    ⊢ (nhds Top.top).HasBasis (fun a => LT.lt a Top.top) fun a => Set.Ioi a
  -/
  have : ∃ x : α, x < ⊤ := (exists_ne ⊤).imp fun x hx => hx.lt_top
  /-
    α : Type u
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTop α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    this : Exists fun x => LT.lt x Top.top
    ⊢ (nhds Top.top).HasBasis (fun a => LT.lt a Top.top) fun a => Set.Ioi a
  -/
  simpa only [Iic_top, nhdsWithin_univ, Ioc_top] using nhdsLE_basis_of_exists_lt this
  /-
    🎉 no goals
  -/


theorem nhds_bot_basis [TopologicalSpace α] [LinearOrder α] [OrderBot α] [OrderTopology α]
    [Nontrivial α] : (𝓝 ⊥).HasBasis (fun a : α => ⊥ < a) fun a : α => Iio a :=
  nhds_top_basis (α := αᵒᵈ)


theorem nhds_top_basis_Ici [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
    [Nontrivial α] [DenselyOrdered α] : (𝓝 ⊤).HasBasis (fun a : α => a < ⊤) Ici :=
  nhds_top_basis.to_hasBasis
    (fun _a ha => let ⟨b, hab, hb⟩ := exists_between ha; ⟨b, hb, Ici_subset_Ioi.mpr hab⟩)
    fun a ha => ⟨a, ha, Ioi_subset_Ici_self⟩


theorem nhds_bot_basis_Iic [TopologicalSpace α] [LinearOrder α] [OrderBot α] [OrderTopology α]
    [Nontrivial α] [DenselyOrdered α] : (𝓝 ⊥).HasBasis (fun a : α => ⊥ < a) Iic :=
  nhds_top_basis_Ici (α := αᵒᵈ)


theorem tendsto_nhds_top_mono [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
    {l : Filter α} {f g : α → β} (hf : Tendsto f l (𝓝 ⊤)) (hg : f ≤ᶠ[l] g) : Tendsto g l (𝓝 ⊤) := by
  /-
    α : Type u
    β : Type v
    inst✝³ : TopologicalSpace β
    inst✝² : Preorder β
    inst✝¹ : OrderTop β
    inst✝ : OrderTopology β
    l : Filter α
    f g : α → β
    hf : Filter.Tendsto f l (nhds Top.top)
    hg : l.EventuallyLE f g
    ⊢ Filter.Tendsto g l (nhds Top.top)
  -/
  simp only [nhds_top_order, tendsto_iInf, tendsto_principal] at hf ⊢
  /-
    α : Type u
    β : Type v
    inst✝³ : TopologicalSpace β
    inst✝² : Preorder β
    inst✝¹ : OrderTop β
    inst✝ : OrderTopology β
    l : Filter α
    f g : α → β
    hg : l.EventuallyLE f g
    hf : ∀ (i : β), LT.lt i Top.top → Filter.Eventually (fun a => Membership.mem ( …
    ⊢ ∀ (i : β), LT.lt i Top.top → Filter.Eventually (fun a => Membership.mem (Set …
  -/
  intro x hx
  /-
    α : Type u
    β : Type v
    inst✝³ : TopologicalSpace β
    inst✝² : Preorder β
    inst✝¹ : OrderTop β
    inst✝ : OrderTopology β
    l : Filter α
    f g : α → β
    hg : l.EventuallyLE f g
    hf : ∀ (i : β), LT.lt i Top.top → Filter.Eventually (fun a => Membership.mem ( …
    x : β
    hx : LT.lt x Top.top
    ⊢ Filter.Eventually (fun a => Membership.mem (Set.Ioi x) (g a)) l
  -/
  filter_upwards [hf x hx, hg] with _ using lt_of_lt_of_le
  /-
    🎉 no goals
  -/


theorem tendsto_nhds_bot_mono [TopologicalSpace β] [Preorder β] [OrderBot β] [OrderTopology β]
    {l : Filter α} {f g : α → β} (hf : Tendsto f l (𝓝 ⊥)) (hg : g ≤ᶠ[l] f) : Tendsto g l (𝓝 ⊥) :=
  tendsto_nhds_top_mono (β := βᵒᵈ) hf hg


theorem tendsto_nhds_top_mono' [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
    {l : Filter α} {f g : α → β} (hf : Tendsto f l (𝓝 ⊤)) (hg : f ≤ g) : Tendsto g l (𝓝 ⊤) :=
  tendsto_nhds_top_mono hf (Eventually.of_forall hg)


theorem tendsto_nhds_bot_mono' [TopologicalSpace β] [Preorder β] [OrderBot β] [OrderTopology β]
    {l : Filter α} {f g : α → β} (hf : Tendsto f l (𝓝 ⊥)) (hg : g ≤ f) : Tendsto g l (𝓝 ⊥) :=
  tendsto_nhds_bot_mono hf (Eventually.of_forall hg)


theorem order_separated [OrderTopology α] {a₁ a₂ : α} (h : a₁ < a₂) :
    ∃ u v : Set α, IsOpen u ∧ IsOpen v ∧ a₁ ∈ u ∧ a₂ ∈ v ∧ ∀ b₁ ∈ u, ∀ b₂ ∈ v, b₁ < b₂ :=
  let ⟨x, hx, y, hy, h⟩ := h.exists_disjoint_Iio_Ioi
  ⟨Iio x, Ioi y, isOpen_gt' _, isOpen_lt' _, hx, hy, h⟩

-- see Note [lower instance priority]

instance (priority := 100) OrderTopology.to_orderClosedTopology [OrderTopology α] :
    OrderClosedTopology α where
  isClosed_le' := isOpen_compl_iff.1 <| isOpen_prod_iff.mpr fun a₁ a₂ (h : ¬a₁ ≤ a₂) =>
    have h : a₂ < a₁ := lt_of_not_ge h
    let ⟨u, v, hu, hv, ha₁, ha₂, h⟩ := order_separated h
    ⟨v, u, hv, hu, ha₂, ha₁, fun ⟨b₁, b₂⟩ ⟨h₁, h₂⟩ => not_le_of_gt <| h b₂ h₂ b₁ h₁⟩


theorem exists_Ioc_subset_of_mem_nhds [OrderTopology α] {a : α} {s : Set α} (hs : s ∈ 𝓝 a)
    (h : ∃ l, l < a) : ∃ l < a, Ioc l a ⊆ s :=
  (nhdsLE_basis_of_exists_lt h).mem_iff.mp (nhdsWithin_le_nhds hs)


theorem exists_Ioc_subset_of_mem_nhds' [OrderTopology α] {a : α} {s : Set α} (hs : s ∈ 𝓝 a) {l : α}
    (hl : l < a) : ∃ l' ∈ Ico l a, Ioc l' a ⊆ s :=
  let ⟨l', hl'a, hl's⟩ := exists_Ioc_subset_of_mem_nhds hs ⟨l, hl⟩
  ⟨max l l', ⟨le_max_left _ _, max_lt hl hl'a⟩,
    (Ioc_subset_Ioc_left <| le_max_right _ _).trans hl's⟩


theorem exists_Ico_subset_of_mem_nhds' [OrderTopology α] {a : α} {s : Set α} (hs : s ∈ 𝓝 a) {u : α}
    (hu : a < u) : ∃ u' ∈ Ioc a u, Ico a u' ⊆ s := by
  simpa only [OrderDual.exists, exists_prop, dual_Ico, dual_Ioc] using
    exists_Ioc_subset_of_mem_nhds' (show ofDual ⁻¹' s ∈ 𝓝 (toDual a) from hs) hu.dual


theorem exists_Ico_subset_of_mem_nhds [OrderTopology α] {a : α} {s : Set α} (hs : s ∈ 𝓝 a)
    (h : ∃ u, a < u) : ∃ u, a < u ∧ Ico a u ⊆ s :=
  let ⟨_l', hl'⟩ := h
  let ⟨l, hl⟩ := exists_Ico_subset_of_mem_nhds' hs hl'
  ⟨l, hl.1.1, hl.2⟩


theorem exists_Icc_mem_subset_of_mem_nhdsGE [OrderTopology α] {a : α} {s : Set α}
    (hs : s ∈ 𝓝[≥] a) : ∃ b, a ≤ b ∧ Icc a b ∈ 𝓝[≥] a ∧ Icc a b ⊆ s := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    s : Set α
    hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
    ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
  -/
  rcases (em (IsMax a)).imp_right not_isMax_iff.mp with (ha | ha)
    /-
      case inl
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
      ha : IsMax a
      ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
    -/
  · use a
    /-
      case h
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
      ha : IsMax a
      ⊢ And (LE.le a a) (And (Membership.mem (nhdsWithin a (Set.Ici a)) (Set.Icc a a …
    -/
    simpa [ha.Ici_eq] using hs
    /-
      🎉 no goals
    -/
    /-
      case inr
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
      ha : Exists fun b => LT.lt a b
      ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
    -/
  · rcases(nhdsGE_basis_of_exists_gt ha).mem_iff.mp hs with ⟨b, hab, hbs⟩
    /-
      case inr.intro.intro
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
      ha : Exists fun b => LT.lt a b
      b : α
      hab : LT.lt a b
      hbs : HasSubset.Subset (Set.Ico a b) s
      ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
    -/
    rcases eq_empty_or_nonempty (Ioo a b) with (H | ⟨c, hac, hcb⟩)
      /-
        case inr.intro.intro.inl
        α : Type u
        inst✝² : TopologicalSpace α
        inst✝¹ : LinearOrder α
        inst✝ : OrderTopology α
        a : α
        s : Set α
        hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
        ha : Exists fun b => LT.lt a b
        b : α
        hab : LT.lt a b
        hbs : HasSubset.Subset (Set.Ico a b) s
        H : Eq (Set.Ioo a b) EmptyCollection.emptyCollection
        ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
      -/
    · have : Ico a b = Icc a a := by rw [← Icc_union_Ioo_eq_Ico le_rfl hab, H, union_empty]
      /-
        case inr.intro.intro.inl
        α : Type u
        inst✝² : TopologicalSpace α
        inst✝¹ : LinearOrder α
        inst✝ : OrderTopology α
        a : α
        s : Set α
        hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
        ha : Exists fun b => LT.lt a b
        b : α
        hab : LT.lt a b
        hbs : HasSubset.Subset (Set.Ico a b) s
        H : Eq (Set.Ioo a b) EmptyCollection.emptyCollection
        this : Eq (Set.Ico a b) (Set.Icc a a)
        ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
      -/
      exact ⟨a, le_rfl, this ▸ ⟨Ico_mem_nhdsGE hab, hbs⟩⟩
      /-
        🎉 no goals
      -/
      /-
        case inr.intro.intro.inr.intro.intro
        α : Type u
        inst✝² : TopologicalSpace α
        inst✝¹ : LinearOrder α
        inst✝ : OrderTopology α
        a : α
        s : Set α
        hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
        ha : Exists fun b => LT.lt a b
        b : α
        hab : LT.lt a b
        hbs : HasSubset.Subset (Set.Ico a b) s
        c : α
        hac : LT.lt a c
        hcb : LT.lt c b
        ⊢ Exists fun b => And (LE.le a b) (And (Membership.mem (nhdsWithin a (Set.Ici  …
      -/
    · refine ⟨c, hac.le, Icc_mem_nhdsGE hac, ?_⟩
      /-
        case inr.intro.intro.inr.intro.intro
        α : Type u
        inst✝² : TopologicalSpace α
        inst✝¹ : LinearOrder α
        inst✝ : OrderTopology α
        a : α
        s : Set α
        hs : Membership.mem (nhdsWithin a (Set.Ici a)) s
        ha : Exists fun b => LT.lt a b
        b : α
        hab : LT.lt a b
        hbs : HasSubset.Subset (Set.Ico a b) s
        c : α
        hac : LT.lt a c
        hcb : LT.lt c b
        ⊢ HasSubset.Subset (Set.Icc a c) s
      -/
      exact (Icc_subset_Ico_right hcb).trans hbs
      /-
        🎉 no goals
      -/


@[deprecated (since := "2024-12-22")]
alias exists_Icc_mem_subset_of_mem_nhdsWithin_Ici := exists_Icc_mem_subset_of_mem_nhdsGE


theorem exists_Icc_mem_subset_of_mem_nhdsLE [OrderTopology α] {a : α} {s : Set α}
    (hs : s ∈ 𝓝[≤] a) : ∃ b ≤ a, Icc b a ∈ 𝓝[≤] a ∧ Icc b a ⊆ s := by
  simpa only [dual_Icc, toDual.surjective.exists] using
    exists_Icc_mem_subset_of_mem_nhdsGE (α := αᵒᵈ) (a := toDual a) hs


@[deprecated (since := "2024-12-22")]
alias exists_Icc_mem_subset_of_mem_nhdsWithin_Iic := exists_Icc_mem_subset_of_mem_nhdsLE


theorem exists_Icc_mem_subset_of_mem_nhds [OrderTopology α] {a : α} {s : Set α} (hs : s ∈ 𝓝 a) :
    ∃ b c, a ∈ Icc b c ∧ Icc b c ∈ 𝓝 a ∧ Icc b c ⊆ s := by
  rcases exists_Icc_mem_subset_of_mem_nhdsLE (nhdsWithin_le_nhds hs) with
    ⟨b, hba, hb_nhds, hbs⟩
  rcases exists_Icc_mem_subset_of_mem_nhdsGE (nhdsWithin_le_nhds hs) with
    ⟨c, hac, hc_nhds, hcs⟩
  /-
    case intro.intro.intro.intro.intro.intro
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    s : Set α
    hs : Membership.mem (nhds a) s
    b : α
    hba : LE.le b a
    hb_nhds : Membership.mem (nhdsWithin a (Set.Iic a)) (Set.Icc b a)
    hbs : HasSubset.Subset (Set.Icc b a) s
    c : α
    hac : LE.le a c
    hc_nhds : Membership.mem (nhdsWithin a (Set.Ici a)) (Set.Icc a c)
    hcs : HasSubset.Subset (Set.Icc a c) s
    ⊢ Exists fun b => Exists fun c => And (Membership.mem (Set.Icc b c) a) (And (M …
  -/
  refine ⟨b, c, ⟨hba, hac⟩, ?_⟩
  /-
    case intro.intro.intro.intro.intro.intro
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    s : Set α
    hs : Membership.mem (nhds a) s
    b : α
    hba : LE.le b a
    hb_nhds : Membership.mem (nhdsWithin a (Set.Iic a)) (Set.Icc b a)
    hbs : HasSubset.Subset (Set.Icc b a) s
    c : α
    hac : LE.le a c
    hc_nhds : Membership.mem (nhdsWithin a (Set.Ici a)) (Set.Icc a c)
    hcs : HasSubset.Subset (Set.Icc a c) s
    ⊢ And (Membership.mem (nhds a) (Set.Icc b c)) (HasSubset.Subset (Set.Icc b c) s)
  -/
  rw [← Icc_union_Icc_eq_Icc hba hac, ← nhdsLE_sup_nhdsGE]
  /-
    case intro.intro.intro.intro.intro.intro
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    s : Set α
    hs : Membership.mem (nhds a) s
    b : α
    hba : LE.le b a
    hb_nhds : Membership.mem (nhdsWithin a (Set.Iic a)) (Set.Icc b a)
    hbs : HasSubset.Subset (Set.Icc b a) s
    c : α
    hac : LE.le a c
    hc_nhds : Membership.mem (nhdsWithin a (Set.Ici a)) (Set.Icc a c)
    hcs : HasSubset.Subset (Set.Icc a c) s
    ⊢ And (Membership.mem (Max.max (nhdsWithin a (Set.Iic a)) (nhdsWithin a (Set.I …
  -/
  exact ⟨union_mem_sup hb_nhds hc_nhds, union_subset hbs hcs⟩
  /-
    🎉 no goals
  -/


theorem IsOpen.exists_Ioo_subset [OrderTopology α] [Nontrivial α] {s : Set α} (hs : IsOpen s)
    (h : s.Nonempty) : ∃ a b, a < b ∧ Ioo a b ⊆ s := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    hs : IsOpen s
    h : s.Nonempty
    ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
  -/
  obtain ⟨x, hx⟩ : ∃ x, x ∈ s := h
  /-
    case intro
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    hs : IsOpen s
    x : α
    hx : Membership.mem s x
    ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
  -/
  obtain ⟨y, hy⟩ : ∃ y, y ≠ x := exists_ne x
  /-
    case intro.intro
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    hs : IsOpen s
    x : α
    hx : Membership.mem s x
    y : α
    hy : Ne y x
    ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
  -/
  rcases lt_trichotomy x y with (H | rfl | H)
  · obtain ⟨u, xu, hu⟩ : ∃ u, x < u ∧ Ico x u ⊆ s :=
      exists_Ico_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    /-
      case intro.intro.inl.intro.intro
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : Nontrivial α
      s : Set α
      hs : IsOpen s
      x : α
      hx : Membership.mem s x
      y : α
      hy : Ne y x
      H : LT.lt x y
      u : α
      xu : LT.lt x u
      hu : HasSubset.Subset (Set.Ico x u) s
      ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
    -/
    exact ⟨x, u, xu, Ioo_subset_Ico_self.trans hu⟩
    /-
      🎉 no goals
    -/
    /-
      case intro.intro.inr.inl
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : Nontrivial α
      s : Set α
      hs : IsOpen s
      x : α
      hx : Membership.mem s x
      hy : Ne x x
      ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
    -/
  · exact (hy rfl).elim
    /-
      🎉 no goals
    -/
  · obtain ⟨l, lx, hl⟩ : ∃ l, l < x ∧ Ioc l x ⊆ s :=
      exists_Ioc_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    /-
      case intro.intro.inr.inr.intro.intro
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : Nontrivial α
      s : Set α
      hs : IsOpen s
      x : α
      hx : Membership.mem s x
      y : α
      hy : Ne y x
      H : LT.lt y x
      l : α
      lx : LT.lt l x
      hl : HasSubset.Subset (Set.Ioc l x) s
      ⊢ Exists fun a => Exists fun b => And (LT.lt a b) (HasSubset.Subset (Set.Ioo a …
    -/
    exact ⟨l, x, lx, Ioo_subset_Ioc_self.trans hl⟩
    /-
      🎉 no goals
    -/


theorem dense_of_exists_between [OrderTopology α] [Nontrivial α] {s : Set α}
    (h : ∀ ⦃a b⦄, a < b → ∃ c ∈ s, a < c ∧ c < b) : Dense s := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    h : ∀ ⦃a b : α⦄, LT.lt a b → Exists fun c => And (Membership.mem s c) (And (LT …
    ⊢ Dense s
  -/
  refine dense_iff_inter_open.2 fun U U_open U_nonempty => ?_
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    h : ∀ ⦃a b : α⦄, LT.lt a b → Exists fun c => And (Membership.mem s c) (And (LT …
    U : Set α
    U_open : IsOpen U
    U_nonempty : U.Nonempty
    ⊢ (Inter.inter U s).Nonempty
  -/
  obtain ⟨a, b, hab, H⟩ : ∃ a b : α, a < b ∧ Ioo a b ⊆ U := U_open.exists_Ioo_subset U_nonempty
  /-
    case intro.intro.intro
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    h : ∀ ⦃a b : α⦄, LT.lt a b → Exists fun c => And (Membership.mem s c) (And (LT …
    U : Set α
    U_open : IsOpen U
    U_nonempty : U.Nonempty
    a b : α
    hab : LT.lt a b
    H : HasSubset.Subset (Set.Ioo a b) U
    ⊢ (Inter.inter U s).Nonempty
  -/
  obtain ⟨x, xs, hx⟩ : ∃ x ∈ s, a < x ∧ x < b := h hab
  /-
    case intro.intro.intro.intro.intro
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : Nontrivial α
    s : Set α
    h : ∀ ⦃a b : α⦄, LT.lt a b → Exists fun c => And (Membership.mem s c) (And (LT …
    U : Set α
    U_open : IsOpen U
    U_nonempty : U.Nonempty
    a b : α
    hab : LT.lt a b
    H : HasSubset.Subset (Set.Ioo a b) U
    x : α
    xs : Membership.mem s x
    hx : And (LT.lt a x) (LT.lt x b)
    ⊢ (Inter.inter U s).Nonempty
  -/
  exact ⟨x, ⟨H hx, xs⟩⟩
  /-
    🎉 no goals
  -/


/-- A set in a nontrivial densely linear ordered type is dense in the sense of topology if and only
if for any `a < b` there exists `c ∈ s`, `a < c < b`. Each implication requires less typeclass
assumptions. -/
theorem dense_iff_exists_between [OrderTopology α] [DenselyOrdered α] [Nontrivial α] {s : Set α} :
    Dense s ↔ ∀ a b, a < b → ∃ c ∈ s, a < c ∧ c < b :=
  ⟨fun h _ _ hab => h.exists_between hab, dense_of_exists_between⟩


/-- A set is a neighborhood of `a` if and only if it contains an interval `(l, u)` containing `a`,
provided `a` is neither a bottom element nor a top element. -/
theorem mem_nhds_iff_exists_Ioo_subset' [OrderTopology α] {a : α} {s : Set α} (hl : ∃ l, l < a)
    (hu : ∃ u, a < u) : s ∈ 𝓝 a ↔ ∃ l u, a ∈ Ioo l u ∧ Ioo l u ⊆ s := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderTopology α
    a : α
    s : Set α
    hl : Exists fun l => LT.lt l a
    hu : Exists fun u => LT.lt a u
    ⊢ Iff (Membership.mem (nhds a) s) (Exists fun l => Exists fun u => And (Member …
  -/
  constructor
    /-
      case mp
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl : Exists fun l => LT.lt l a
      hu : Exists fun u => LT.lt a u
      ⊢ Membership.mem (nhds a) s → Exists fun l => Exists fun u => And (Membership. …
    -/
  · intro h
    /-
      case mp
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl : Exists fun l => LT.lt l a
      hu : Exists fun u => LT.lt a u
      h : Membership.mem (nhds a) s
      ⊢ Exists fun l => Exists fun u => And (Membership.mem (Set.Ioo l u) a) (HasSub …
    -/
    rcases exists_Ico_subset_of_mem_nhds h hu with ⟨u, au, hu⟩
    /-
      case mp.intro.intro
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl : Exists fun l => LT.lt l a
      hu✝ : Exists fun u => LT.lt a u
      h : Membership.mem (nhds a) s
      u : α
      au : LT.lt a u
      hu : HasSubset.Subset (Set.Ico a u) s
      ⊢ Exists fun l => Exists fun u => And (Membership.mem (Set.Ioo l u) a) (HasSub …
    -/
    rcases exists_Ioc_subset_of_mem_nhds h hl with ⟨l, la, hl⟩
    /-
      case mp.intro.intro.intro.intro
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl✝ : Exists fun l => LT.lt l a
      hu✝ : Exists fun u => LT.lt a u
      h : Membership.mem (nhds a) s
      u : α
      au : LT.lt a u
      hu : HasSubset.Subset (Set.Ico a u) s
      l : α
      la : LT.lt l a
      hl : HasSubset.Subset (Set.Ioc l a) s
      ⊢ Exists fun l => Exists fun u => And (Membership.mem (Set.Ioo l u) a) (HasSub …
    -/
    exact ⟨l, u, ⟨la, au⟩, Ioc_union_Ico_eq_Ioo la au ▸ union_subset hl hu⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl : Exists fun l => LT.lt l a
      hu : Exists fun u => LT.lt a u
      ⊢ (Exists fun l => Exists fun u => And (Membership.mem (Set.Ioo l u) a) (HasSu …
    -/
  · rintro ⟨l, u, ha, h⟩
    /-
      case mpr.intro.intro.intro
      α : Type u
      inst✝² : TopologicalSpace α
      inst✝¹ : LinearOrder α
      inst✝ : OrderTopology α
      a : α
      s : Set α
      hl : Exists fun l => LT.lt l a
      hu : Exists fun u => LT.lt a u
      l u : α
      ha : Membership.mem (Set.Ioo l u) a
      h : HasSubset.Subset (Set.Ioo l u) s
      ⊢ Membership.mem (nhds a) s
    -/
    apply mem_of_superset (Ioo_mem_nhds ha.1 ha.2) h
    /-
      🎉 no goals
    -/


/-- A set is a neighborhood of `a` if and only if it contains an interval `(l, u)` containing `a`.
-/
theorem mem_nhds_iff_exists_Ioo_subset [OrderTopology α] [NoMaxOrder α] [NoMinOrder α] {a : α}
    {s : Set α} : s ∈ 𝓝 a ↔ ∃ l u, a ∈ Ioo l u ∧ Ioo l u ⊆ s :=
  mem_nhds_iff_exists_Ioo_subset' (exists_lt a) (exists_gt a)


theorem nhds_basis_Ioo' [OrderTopology α] {a : α} (hl : ∃ l, l < a) (hu : ∃ u, a < u) :
    (𝓝 a).HasBasis (fun b : α × α => b.1 < a ∧ a < b.2) fun b => Ioo b.1 b.2 :=
                                                                /-
                                                                  α : Type u
                                                                  inst✝² : TopologicalSpace α
                                                                  inst✝¹ : LinearOrder α
                                                                  inst✝ : OrderTopology α
                                                                  a : α
                                                                  hl : Exists fun l => LT.lt l a
                                                                  hu : Exists fun u => LT.lt a u
                                                                  s : Set α
                                                                  ⊢ Iff (Exists fun l => Exists fun u => And (Membership.mem (Set.Ioo l u) a) (H …
                                                                -/
  ⟨fun s => (mem_nhds_iff_exists_Ioo_subset' hl hu).trans <| by simp⟩
                                                                /-
                                                                  🎉 no goals
                                                                -/


theorem nhds_basis_Ioo [OrderTopology α] [NoMaxOrder α] [NoMinOrder α] (a : α) :
    (𝓝 a).HasBasis (fun b : α × α => b.1 < a ∧ a < b.2) fun b => Ioo b.1 b.2 :=
  nhds_basis_Ioo' (exists_lt a) (exists_gt a)


theorem Filter.Eventually.exists_Ioo_subset [OrderTopology α] [NoMaxOrder α] [NoMinOrder α] {a : α}
    {p : α → Prop} (hp : ∀ᶠ x in 𝓝 a, p x) : ∃ l u, a ∈ Ioo l u ∧ Ioo l u ⊆ { x | p x } :=
  mem_nhds_iff_exists_Ioo_subset.1 hp


theorem Dense.topology_eq_generateFrom [OrderTopology α] [DenselyOrdered α] {s : Set α}
    (hs : Dense s) : ‹TopologicalSpace α› = .generateFrom (Ioi '' s ∪ Iio '' s) := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : DenselyOrdered α
    s : Set α
    hs : Dense s
    ⊢ Eq inst✝³ (TopologicalSpace.generateFrom (Union.union (Set.image Set.Ioi s)  …
  -/
  refine (OrderTopology.topology_eq_generate_intervals (α := α)).trans ?_
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : DenselyOrdered α
    s : Set α
    hs : Dense s
    ⊢ Eq (TopologicalSpace.generateFrom (setOf fun s => Exists fun a => Or (Eq s ( …
  -/
  refine le_antisymm (generateFrom_anti ?_) (le_generateFrom ?_)
    /-
      case refine_1
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : DenselyOrdered α
      s : Set α
      hs : Dense s
      ⊢ HasSubset.Subset (Union.union (Set.image Set.Ioi s) (Set.image Set.Iio s)) ( …
    -/
  · simp only [union_subset_iff, image_subset_iff]
    /-
      case refine_1
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : DenselyOrdered α
      s : Set α
      hs : Dense s
      ⊢ And (HasSubset.Subset s (Set.preimage Set.Ioi (setOf fun s => Exists fun a = …
    -/
    exact ⟨fun a _ ↦ ⟨a, .inl rfl⟩, fun a _ ↦ ⟨a, .inr rfl⟩⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_2
      α : Type u
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : DenselyOrdered α
      s : Set α
      hs : Dense s
      ⊢ ∀ (s_1 : Set α), Membership.mem (setOf fun s => Exists fun a => Or (Eq s (Se …
    -/
  · rintro _ ⟨a, rfl | rfl⟩
      /-
        case refine_2.intro.inl
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        ⊢ IsOpen (Set.Ioi a)
      -/
    · rw [hs.Ioi_eq_biUnion]
      /-
        case refine_2.intro.inl
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        ⊢ IsOpen (Set.iUnion fun y => Set.iUnion fun h => Set.Ioi y)
      -/
      let _ := generateFrom (Ioi '' s ∪ Iio '' s)
      /-
        case refine_2.intro.inl
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        x✝ : TopologicalSpace α := TopologicalSpace.generateFrom (Union.union (Set.ima …
        ⊢ IsOpen (Set.iUnion fun y => Set.iUnion fun h => Set.Ioi y)
      -/
      exact isOpen_iUnion fun x ↦ isOpen_iUnion fun h ↦ .basic _ <| .inl <| mem_image_of_mem _ h.1
      /-
        🎉 no goals
      -/
      /-
        case refine_2.intro.inr
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        ⊢ IsOpen (Set.Iio a)
      -/
    · rw [hs.Iio_eq_biUnion]
      /-
        case refine_2.intro.inr
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        ⊢ IsOpen (Set.iUnion fun y => Set.iUnion fun h => Set.Iio y)
      -/
      let _ := generateFrom (Ioi '' s ∪ Iio '' s)
      /-
        case refine_2.intro.inr
        α : Type u
        inst✝³ : TopologicalSpace α
        inst✝² : LinearOrder α
        inst✝¹ : OrderTopology α
        inst✝ : DenselyOrdered α
        s : Set α
        hs : Dense s
        a : α
        x✝ : TopologicalSpace α := TopologicalSpace.generateFrom (Union.union (Set.ima …
        ⊢ IsOpen (Set.iUnion fun y => Set.iUnion fun h => Set.Iio y)
      -/
      exact isOpen_iUnion fun x ↦ isOpen_iUnion fun h ↦ .basic _ <| .inr <| mem_image_of_mem _ h.1
      /-
        🎉 no goals
      -/


@[deprecated OrderBot.atBot_eq (since := "2024-02-14")]
theorem atBot_le_nhds_bot [OrderBot α] : (atBot : Filter α) ≤ 𝓝 ⊥ := by
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderBot α
    ⊢ LE.le Filter.atBot (nhds Bot.bot)
  -/
  rw [OrderBot.atBot_eq]
  /-
    α : Type u
    inst✝² : TopologicalSpace α
    inst✝¹ : LinearOrder α
    inst✝ : OrderBot α
    ⊢ LE.le (Pure.pure Bot.bot) (nhds Bot.bot)
  -/
  apply pure_le_nhds
  /-
    🎉 no goals
  -/


set_option linter.deprecated false in
@[deprecated OrderTop.atTop_eq (since := "2024-02-14")]
theorem atTop_le_nhds_top [OrderTop α] : (atTop : Filter α) ≤ 𝓝 ⊤ :=
  @atBot_le_nhds_bot αᵒᵈ _ _ _


/-- Let `α` be a densely ordered linear order with order topology. If `α` is a separable space, then
it has second countable topology. Note that the "densely ordered" assumption cannot be dropped, see
[double arrow space](https://topology.pi-base.org/spaces/S000093) for a counterexample. -/
theorem SecondCountableTopology.of_separableSpace_orderTopology [OrderTopology α] [DenselyOrdered α]
    [SeparableSpace α] : SecondCountableTopology α := by
  /-
    α : Type u
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : DenselyOrdered α
    inst✝ : TopologicalSpace.SeparableSpace α
    ⊢ SecondCountableTopology α
  -/
  rcases exists_countable_dense α with ⟨s, hc, hd⟩
  /-
    case intro.intro
    α : Type u
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : DenselyOrdered α
    inst✝ : TopologicalSpace.SeparableSpace α
    s : Set α
    hc : s.Countable
    hd : Dense s
    ⊢ SecondCountableTopology α
  -/
  refine ⟨⟨_, ?_, hd.topology_eq_generateFrom⟩⟩
  /-
    case intro.intro
    α : Type u
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : DenselyOrdered α
    inst✝ : TopologicalSpace.SeparableSpace α
    s : Set α
    hc : s.Countable
    hd : Dense s
    ⊢ (Union.union (Set.image Set.Ioi s) (Set.image Set.Iio s)).Countable
  -/
  exact (hc.image _).union (hc.image _)
  /-
    🎉 no goals
  -/


/-- The set of points which are isolated on the right is countable when the space is
second-countable. -/
theorem countable_setOf_covBy_right [OrderTopology α] [SecondCountableTopology α] :
    Set.Countable { x : α | ∃ y, x ⋖ y } := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    ⊢ (setOf fun x => Exists fun y => CovBy x y).Countable
  -/
  nontriviality α
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    ⊢ (setOf fun x => Exists fun y => CovBy x y).Countable
  -/
  let s := { x : α | ∃ y, x ⋖ y }
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    ⊢ (setOf fun x => Exists fun y => CovBy x y).Countable
  -/
  have : ∀ x ∈ s, ∃ y, x ⋖ y := fun x => id
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    this : ∀ (x : α), Membership.mem s x → Exists fun y => CovBy x y
    ⊢ (setOf fun x => Exists fun y => CovBy x y).Countable
  -/
  choose! y hy using this
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    ⊢ (setOf fun x => Exists fun y => CovBy x y).Countable
  -/
  have Hy : ∀ x z, x ∈ s → z < y x → z ≤ x := fun x z hx => (hy x hx).le_of_lt
  suffices H : ∀ a : Set α, IsOpen a → Set.Countable { x | x ∈ s ∧ x ∈ a ∧ y x ∉ a } by
    have : s ⊆ ⋃ a ∈ countableBasis α, { x | x ∈ s ∧ x ∈ a ∧ y x ∉ a } := fun x hx => by
      rcases (isBasis_countableBasis α).exists_mem_of_ne (hy x hx).ne with ⟨a, ab, xa, ya⟩
      exact mem_iUnion₂.2 ⟨a, ab, hx, xa, ya⟩
    refine Set.Countable.mono this ?_
    refine Countable.biUnion (countable_countableBasis α) fun a ha => H _ ?_
    exact isOpen_of_mem_countableBasis ha
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    ⊢ ∀ (a : Set α), IsOpen a → (setOf fun x => And (Membership.mem s x) (And (Mem …
  -/
  intro a ha
  suffices H : Set.Countable { x | (x ∈ s ∧ x ∈ a ∧ y x ∉ a) ∧ ¬IsBot x } from
    H.of_diff (subsingleton_isBot α).countable
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    a : Set α
    ha : IsOpen a
    ⊢ (setOf fun x => And (And (Membership.mem s x) (And (Membership.mem a x) (Not …
  -/
  simp only [and_assoc]
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    a : Set α
    ha : IsOpen a
    ⊢ (setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) (And (Not …
  -/
  let t := { x | x ∈ s ∧ x ∈ a ∧ y x ∉ a ∧ ¬IsBot x }
  have : ∀ x ∈ t, ∃ z < x, Ioc z x ⊆ a := by
    intro x hx
    apply exists_Ioc_subset_of_mem_nhds (ha.mem_nhds hx.2.1)
    simpa only [IsBot, not_forall, not_le] using hx.right.right.right
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    a : Set α
    ha : IsOpen a
    t : Set α := setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) …
    this : ∀ (x : α), Membership.mem t x → Exists fun z => And (LT.lt z x) (HasSub …
    ⊢ (setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) (And (Not …
  -/
  choose! z hz h'z using this
  have : PairwiseDisjoint t fun x => Ioc (z x) x := fun x xt x' x't hxx' => by
    rcases hxx'.lt_or_lt with (h' | h')
    · refine disjoint_left.2 fun u ux ux' => xt.2.2.1 ?_
      refine h'z x' x't ⟨ux'.1.trans_le (ux.2.trans (hy x xt.1).le), ?_⟩
      by_contra! H
      exact lt_irrefl _ ((Hy _ _ xt.1 H).trans_lt h')
    · refine disjoint_left.2 fun u ux ux' => x't.2.2.1 ?_
      refine h'z x xt ⟨ux.1.trans_le (ux'.2.trans (hy x' x't.1).le), ?_⟩
      by_contra! H
      exact lt_irrefl _ ((Hy _ _ x't.1 H).trans_lt h')
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    a : Set α
    ha : IsOpen a
    t : Set α := setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) …
    z : α → α
    hz : ∀ (x : α), Membership.mem t x → LT.lt (z x) x
    h'z : ∀ (x : α), Membership.mem t x → HasSubset.Subset (Set.Ioc (z x) x) a
    this : t.PairwiseDisjoint fun x => Set.Ioc (z x) x
    ⊢ (setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) (And (Not …
  -/
  refine this.countable_of_isOpen (fun x hx => ?_) fun x hx => ⟨x, hz x hx, le_rfl⟩
  suffices H : Ioc (z x) x = Ioo (z x) (y x) by
    rw [H]
    exact isOpen_Ioo
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial α
    s : Set α := setOf fun x => Exists fun y => CovBy x y
    y : α → α
    hy : ∀ (x : α), Membership.mem s x → CovBy x (y x)
    Hy : ∀ (x z : α), Membership.mem s x → LT.lt z (y x) → LE.le z x
    a : Set α
    ha : IsOpen a
    t : Set α := setOf fun x => And (Membership.mem s x) (And (Membership.mem a x) …
    z : α → α
    hz : ∀ (x : α), Membership.mem t x → LT.lt (z x) x
    h'z : ∀ (x : α), Membership.mem t x → HasSubset.Subset (Set.Ioc (z x) x) a
    this : t.PairwiseDisjoint fun x => Set.Ioc (z x) x
    x : α
    hx : Membership.mem t x
    ⊢ Eq (Set.Ioc (z x) x) (Set.Ioo (z x) (y x))
  -/
  exact Subset.antisymm (Ioc_subset_Ioo_right (hy x hx.1).lt) fun u hu => ⟨hu.1, Hy _ _ hx.1 hu.2⟩
  /-
    🎉 no goals
  -/


/-- The set of points which are isolated on the left is countable when the space is
second-countable. -/
theorem countable_setOf_covBy_left [OrderTopology α] [SecondCountableTopology α] :
    Set.Countable { x : α | ∃ y, y ⋖ x } := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    ⊢ (setOf fun x => Exists fun y => CovBy y x).Countable
  -/
  convert countable_setOf_covBy_right (α := αᵒᵈ) using 5
  /-
    case h.e'_2.h.h.e'_2.h.h.h.e'_2.h.h.a
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    e_1✝ : Eq α (OrderDual α)
    x✝¹ x✝ : α
    ⊢ Iff (CovBy x✝ x✝¹) (CovBy x✝¹ x✝)
  -/
  exact toDual_covBy_toDual_iff.symm
  /-
    🎉 no goals
  -/


/-- The set of points which are isolated on the left is countable when the space is
second-countable. -/
theorem countable_of_isolated_left' [OrderTopology α] [SecondCountableTopology α] :
    Set.Countable { x : α | ∃ y, y < x ∧ Ioo y x = ∅ } := by
  /-
    α : Type u
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    ⊢ (setOf fun x => Exists fun y => And (LT.lt y x) (Eq (Set.Ioo y x) EmptyColle …
  -/
  simpa only [← covBy_iff_Ioo_eq] using countable_setOf_covBy_left
  /-
    🎉 no goals
  -/


/-- Consider a disjoint family of intervals `(x, y)` with `x < y` in a second-countable space.
Then the family is countable.
This is not a straightforward consequence of second-countability as some of these intervals might be
empty (but in fact this can happen only for countably many of them). -/
theorem Set.PairwiseDisjoint.countable_of_Ioo [OrderTopology α] [SecondCountableTopology α]
    {y : α → α} {s : Set α} (h : PairwiseDisjoint s fun x => Ioo x (y x))
    (h' : ∀ x ∈ s, x < y x) : s.Countable :=
  have : (s \ { x | ∃ y, x ⋖ y }).Countable :=
    (h.subset diff_subset).countable_of_isOpen (fun _ _ => isOpen_Ioo)
      fun x hx => (h' _ hx.1).exists_lt_lt (mt (Exists.intro (y x)) hx.2)
  this.of_diff countable_setOf_covBy_right


/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated above from `f x` is countable. -/
theorem countable_image_lt_image_Ioi [OrderTopology α] [LinearOrder β] (f : β → α)
    [SecondCountableTopology α] : Set.Countable {x | ∃ z, f x < z ∧ ∀ y, x < y → z ≤ f y} := by
  /- If the values of `f` are separated above on the right of `x`, there is an interval `(f x, z x)`
    which is not reached by `f`. This gives a family of disjoint open intervals in `α`. Such a
    family can only be countable as `α` is second-countable. -/
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  nontriviality β
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial β
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  have : Nonempty α := Nonempty.map f (by infer_instance)
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial β
    this : Nonempty α
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  let s := {x | ∃ z, f x < z ∧ ∀ y, x < y → z ≤ f y}
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial β
    this : Nonempty α
    s : Set β := setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT …
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  have : ∀ x, x ∈ s → ∃ z, f x < z ∧ ∀ y, x < y → z ≤ f y := fun x hx ↦ hx
  -- choose `z x` such that `f` does not take the values in `(f x, z x)`.
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial β
    this✝ : Nonempty α
    s : Set β := setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT …
    this : ∀ (x : β), Membership.mem s x → Exists fun z => And (LT.lt (f x) z) (∀  …
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  choose! z hz using this
  have I : InjOn f s := by
    apply StrictMonoOn.injOn
    intro x hx y _ hxy
    calc
      f x < z x := (hz x hx).1
      _ ≤ f y := (hz x hx).2 y hxy
  -- show that `f s` is countable by arguing that a disjoint family of disjoint open intervals
  -- (the intervals `(f x, z x)`) is at most countable.
  have fs_count : (f '' s).Countable := by
    have A : (f '' s).PairwiseDisjoint fun x => Ioo x (z (invFunOn f s x)) := by
      rintro _ ⟨u, us, rfl⟩ _ ⟨v, vs, rfl⟩ huv
      wlog hle : u ≤ v generalizing u v
      · exact (this v vs u us huv.symm (le_of_not_le hle)).symm
      have hlt : u < v := hle.lt_of_ne (ne_of_apply_ne _ huv)
      apply disjoint_iff_forall_ne.2
      rintro a ha b hb rfl
      simp only [I.leftInvOn_invFunOn us, I.leftInvOn_invFunOn vs] at ha hb
      exact lt_irrefl _ ((ha.2.trans_le ((hz u us).2 v hlt)).trans hb.1)
    apply Set.PairwiseDisjoint.countable_of_Ioo A
    rintro _ ⟨y, ys, rfl⟩
    simpa only [I.leftInvOn_invFunOn ys] using (hz y ys).1
  /-
    α : Type u
    β : Type v
    inst✝⁴ : TopologicalSpace α
    inst✝³ : LinearOrder α
    inst✝² : OrderTopology α
    inst✝¹ : LinearOrder β
    f : β → α
    inst✝ : SecondCountableTopology α
    a✝ : Nontrivial β
    this : Nonempty α
    s : Set β := setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT …
    z : β → α
    hz : ∀ (x : β), Membership.mem s x → And (LT.lt (f x) (z x)) (∀ (y : β), LT.lt …
    I : Set.InjOn f s
    fs_count : (Set.image f s).Countable
    ⊢ (setOf fun x => Exists fun z => And (LT.lt (f x) z) (∀ (y : β), LT.lt x y →  …
  -/
  exact MapsTo.countable_of_injOn (mapsTo_image f s) I fs_count
  /-
    🎉 no goals
  -/


/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated below from `f x` is countable. -/
theorem countable_image_gt_image_Ioi [OrderTopology α] [LinearOrder β] (f : β → α)
    [SecondCountableTopology α] : Set.Countable {x | ∃ z, z < f x ∧ ∀ y, x < y → f y ≤ z} :=
  countable_image_lt_image_Ioi (α := αᵒᵈ) f


/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated above from `f x` is countable. -/
theorem countable_image_lt_image_Iio [OrderTopology α] [LinearOrder β] (f : β → α)
    [SecondCountableTopology α] : Set.Countable {x | ∃ z, f x < z ∧ ∀ y, y < x → z ≤ f y} :=
  countable_image_lt_image_Ioi (β := βᵒᵈ) f


/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated below from `f x` is countable. -/
theorem countable_image_gt_image_Iio [OrderTopology α] [LinearOrder β] (f : β → α)
    [SecondCountableTopology α] : Set.Countable {x | ∃ z, z < f x ∧ ∀ y, y < x → f y ≤ z} :=
  countable_image_lt_image_Ioi (α := αᵒᵈ) (β := βᵒᵈ) f


instance instIsCountablyGenerated_atTop [OrderTopology α] [SecondCountableTopology α] :
    IsCountablyGenerated (atTop : Filter α) := by
  /-
    α : Type u
    β : Type v
    γ : Type w
    inst✝³ : TopologicalSpace α
    inst✝² : LinearOrder α
    inst✝¹ : OrderTopology α
    inst✝ : SecondCountableTopology α
    ⊢ Filter.atTop.IsCountablyGenerated
  -/
  by_cases h : ∃ (x : α), IsTop x
    /-
      case pos
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Exists fun x => IsTop x
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
  · rcases h with ⟨x, hx⟩
    /-
      case pos.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      x : α
      hx : IsTop x
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
    rw [atTop_eq_pure_of_isTop hx]
    /-
      case pos.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      x : α
      hx : IsTop x
      ⊢ (Pure.pure x).IsCountablyGenerated
    -/
    exact isCountablyGenerated_pure x
    /-
      🎉 no goals
    -/
    /-
      case neg
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Not (Exists fun x => IsTop x)
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
  · rcases exists_countable_basis α with ⟨b, b_count, b_ne, hb⟩
    /-
      case neg.intro.intro.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Not (Exists fun x => IsTop x)
      b : Set (Set α)
      b_count : b.Countable
      b_ne : Not (Membership.mem b EmptyCollection.emptyCollection)
      hb : TopologicalSpace.IsTopologicalBasis b
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
    have : Countable b := by exact Iff.mpr countable_coe_iff b_count
    have A : ∀ (s : b), ∃ (x : α), x ∈ (s : Set α) := by
      intro s
      have : (s : Set α) ≠ ∅ := by
        intro H
        apply b_ne
        convert s.2
        exact H.symm
      exact Iff.mp nmem_singleton_empty this
    /-
      case neg.intro.intro.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Not (Exists fun x => IsTop x)
      b : Set (Set α)
      b_count : b.Countable
      b_ne : Not (Membership.mem b EmptyCollection.emptyCollection)
      hb : TopologicalSpace.IsTopologicalBasis b
      this : Countable ↑b
      A : ∀ (s : ↑b), Exists fun x => Membership.mem (↑s) x
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
    choose a ha using A
    have : (atTop : Filter α) = (generate (Ici '' (range a))) := by
      apply atTop_eq_generate_of_not_bddAbove
      intro ⟨x, hx⟩
      simp only [IsTop, not_exists, not_forall, not_le] at h
      rcases h x with ⟨y, hy⟩
      obtain ⟨s, sb, -, hs⟩ : ∃ s, s ∈ b ∧ y ∈ s ∧ s ⊆ Ioi x :=
        hb.exists_subset_of_mem_open hy isOpen_Ioi
      have I : a ⟨s, sb⟩ ≤ x := hx (mem_range_self _)
      have J : x < a ⟨s, sb⟩ := hs (ha ⟨s, sb⟩)
      exact lt_irrefl _ (I.trans_lt J)
    /-
      case neg.intro.intro.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Not (Exists fun x => IsTop x)
      b : Set (Set α)
      b_count : b.Countable
      b_ne : Not (Membership.mem b EmptyCollection.emptyCollection)
      hb : TopologicalSpace.IsTopologicalBasis b
      this✝ : Countable ↑b
      a : ↑b → α
      ha : ∀ (s : ↑b), Membership.mem (↑s) (a s)
      this : Eq Filter.atTop (Filter.generate (Set.image Set.Ici (Set.range a)))
      ⊢ Filter.atTop.IsCountablyGenerated
    -/
    rw [this]
    /-
      case neg.intro.intro.intro
      α : Type u
      β : Type v
      γ : Type w
      inst✝³ : TopologicalSpace α
      inst✝² : LinearOrder α
      inst✝¹ : OrderTopology α
      inst✝ : SecondCountableTopology α
      h : Not (Exists fun x => IsTop x)
      b : Set (Set α)
      b_count : b.Countable
      b_ne : Not (Membership.mem b EmptyCollection.emptyCollection)
      hb : TopologicalSpace.IsTopologicalBasis b
      this✝ : Countable ↑b
      a : ↑b → α
      ha : ∀ (s : ↑b), Membership.mem (↑s) (a s)
      this : Eq Filter.atTop (Filter.generate (Set.image Set.Ici (Set.range a)))
      ⊢ (Filter.generate (Set.image Set.Ici (Set.range a))).IsCountablyGenerated
    -/
    exact ⟨_, (countable_range _).image _, rfl⟩
    /-
      🎉 no goals
    -/


instance instIsCountablyGenerated_atBot [OrderTopology α] [SecondCountableTopology α] :
    IsCountablyGenerated (atBot : Filter α) :=
  @instIsCountablyGenerated_atTop αᵒᵈ _ _ _ _


theorem pi_Iic_mem_nhds (ha : ∀ i, x i < a i) : Iic a ∈ 𝓝 x :=
  pi_univ_Iic a ▸ set_pi_mem_nhds (Set.toFinite _) fun _ _ => Iic_mem_nhds (ha _)


theorem pi_Iic_mem_nhds' (ha : ∀ i, x' i < a' i) : Iic a' ∈ 𝓝 x' :=
  pi_Iic_mem_nhds ha


theorem pi_Ici_mem_nhds (ha : ∀ i, a i < x i) : Ici a ∈ 𝓝 x :=
  pi_univ_Ici a ▸ set_pi_mem_nhds (Set.toFinite _) fun _ _ => Ici_mem_nhds (ha _)


theorem pi_Ici_mem_nhds' (ha : ∀ i, a' i < x' i) : Ici a' ∈ 𝓝 x' :=
  pi_Ici_mem_nhds ha


theorem pi_Icc_mem_nhds (ha : ∀ i, a i < x i) (hb : ∀ i, x i < b i) : Icc a b ∈ 𝓝 x :=
  pi_univ_Icc a b ▸ set_pi_mem_nhds finite_univ fun _ _ => Icc_mem_nhds (ha _) (hb _)


theorem pi_Icc_mem_nhds' (ha : ∀ i, a' i < x' i) (hb : ∀ i, x' i < b' i) : Icc a' b' ∈ 𝓝 x' :=
  pi_Icc_mem_nhds ha hb


theorem pi_Iio_mem_nhds (ha : ∀ i, x i < a i) : Iio a ∈ 𝓝 x := mem_of_superset
  (set_pi_mem_nhds finite_univ fun i _ ↦ Iio_mem_nhds (ha i)) (pi_univ_Iio_subset a)


theorem pi_Iio_mem_nhds' (ha : ∀ i, x' i < a' i) : Iio a' ∈ 𝓝 x' :=
  pi_Iio_mem_nhds ha


theorem pi_Ioi_mem_nhds (ha : ∀ i, a i < x i) : Ioi a ∈ 𝓝 x :=
  pi_Iio_mem_nhds (π := fun i => (π i)ᵒᵈ) ha


theorem pi_Ioi_mem_nhds' (ha : ∀ i, a' i < x' i) : Ioi a' ∈ 𝓝 x' :=
  pi_Ioi_mem_nhds ha


theorem pi_Ioc_mem_nhds (ha : ∀ i, a i < x i) (hb : ∀ i, x i < b i) : Ioc a b ∈ 𝓝 x := by
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    ⊢ Membership.mem (nhds x) (Set.Ioc a b)
  -/
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioc_subset a b)
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    i : ι
    x✝ : Membership.mem Set.univ i
    ⊢ Membership.mem (nhds (x i)) (Set.Ioc (a i) (b i))
  -/
  exact Ioc_mem_nhds (ha i) (hb i)
  /-
    🎉 no goals
  -/


theorem pi_Ioc_mem_nhds' (ha : ∀ i, a' i < x' i) (hb : ∀ i, x' i < b' i) : Ioc a' b' ∈ 𝓝 x' :=
  pi_Ioc_mem_nhds ha hb


theorem pi_Ico_mem_nhds (ha : ∀ i, a i < x i) (hb : ∀ i, x i < b i) : Ico a b ∈ 𝓝 x := by
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    ⊢ Membership.mem (nhds x) (Set.Ico a b)
  -/
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ico_subset a b)
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    i : ι
    x✝ : Membership.mem Set.univ i
    ⊢ Membership.mem (nhds (x i)) (Set.Ico (a i) (b i))
  -/
  exact Ico_mem_nhds (ha i) (hb i)
  /-
    🎉 no goals
  -/


theorem pi_Ico_mem_nhds' (ha : ∀ i, a' i < x' i) (hb : ∀ i, x' i < b' i) : Ico a' b' ∈ 𝓝 x' :=
  pi_Ico_mem_nhds ha hb


theorem pi_Ioo_mem_nhds (ha : ∀ i, a i < x i) (hb : ∀ i, x i < b i) : Ioo a b ∈ 𝓝 x := by
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    ⊢ Membership.mem (nhds x) (Set.Ioo a b)
  -/
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioo_subset a b)
  /-
    ι : Type u_1
    π : ι → Type u_2
    inst✝⁴ : Finite ι
    inst✝³ : (i : ι) → LinearOrder (π i)
    inst✝² : (i : ι) → TopologicalSpace (π i)
    inst✝¹ : ∀ (i : ι), OrderTopology (π i)
    a b x : (i : ι) → π i
    inst✝ : Nonempty ι
    ha : ∀ (i : ι), LT.lt (a i) (x i)
    hb : ∀ (i : ι), LT.lt (x i) (b i)
    i : ι
    x✝ : Membership.mem Set.univ i
    ⊢ Membership.mem (nhds (x i)) (Set.Ioo (a i) (b i))
  -/
  exact Ioo_mem_nhds (ha i) (hb i)
  /-
    🎉 no goals
  -/


theorem pi_Ioo_mem_nhds' (ha : ∀ i, a' i < x' i) (hb : ∀ i, x' i < b' i) : Ioo a' b' ∈ 𝓝 x' :=
  pi_Ioo_mem_nhds ha hb


