instance {R A : Type*} [CommRing R] [StarRing R] [NormedRing A] [Algebra R A] [StarRing A]
    [ContinuousStar A] [StarModule R A] (a : A) [IsStarNormal a] :
    NormedCommRing (elemental R a) :=
  { SubringClass.toNormedRing (elemental R a) with
    mul_comm := mul_comm }


noncomputable instance (a : A) [IsStarNormal a] : CommCStarAlgebra (elemental ℂ a) where
  mul_comm := mul_comm


/-- The natural map from `characterSpace ℂ (elemental ℂ x)` to `spectrum ℂ x` given
by evaluating `φ` at `x`. This is essentially just evaluation of the `gelfandTransform` of `x`,
but because we want something in `spectrum ℂ x`, as opposed to
`spectrum ℂ ⟨x, elemental.self_mem ℂ x⟩` there is slightly more work to do. -/
@[simps]
noncomputable def characterSpaceToSpectrum (x : A)
    (φ : characterSpace ℂ (elemental ℂ x)) : spectrum ℂ x where
  val := φ ⟨x, self_mem ℂ x⟩
  property := by
    simpa only [StarSubalgebra.spectrum_eq (hS := isClosed ℂ x)
      (a := ⟨x, self_mem ℂ x⟩)] using AlgHom.apply_mem_spectrum φ ⟨x, self_mem ℂ x⟩


@[deprecated (since := "2024-11-05")]
alias _root_.elementalStarAlgebra.characterSpaceToSpectrum := characterSpaceToSpectrum


theorem continuous_characterSpaceToSpectrum (x : A) :
    Continuous (characterSpaceToSpectrum x) :=
  continuous_induced_rng.2
    (map_continuous <| gelfandTransform ℂ (elemental ℂ x) ⟨x, self_mem ℂ x⟩)


@[deprecated (since := "2024-11-05")]
alias _root_.elementalStarAlgebra.continuous_characterSpaceToSpectrum :=
  continuous_characterSpaceToSpectrum


theorem bijective_characterSpaceToSpectrum :
    Function.Bijective (characterSpaceToSpectrum a) := by
  /-
    A : Type u_1
    inst✝¹ : CStarAlgebra A
    a : A
    inst✝ : IsStarNormal a
    ⊢ Function.Bijective (StarAlgebra.elemental.characterSpaceToSpectrum a)
  -/
  refine ⟨fun φ ψ h => starAlgHomClass_ext ℂ ?_ ?_ ?_, ?_⟩
    /-
      case refine_1
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      φ ψ : ↑(WeakDual.characterSpace Complex (Subtype fun x => Membership.mem (Star …
      h : Eq (StarAlgebra.elemental.characterSpaceToSpectrum a φ) (StarAlgebra.eleme …
      ⊢ Continuous ⇑φ
    -/
  · exact (map_continuous φ)
    /-
      🎉 no goals
    -/
    /-
      case refine_2
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      φ ψ : ↑(WeakDual.characterSpace Complex (Subtype fun x => Membership.mem (Star …
      h : Eq (StarAlgebra.elemental.characterSpaceToSpectrum a φ) (StarAlgebra.eleme …
      ⊢ Continuous ⇑ψ
    -/
  · exact (map_continuous ψ)
    /-
      🎉 no goals
    -/
  · simpa only [characterSpaceToSpectrum, Subtype.mk_eq_mk,
      ContinuousMap.coe_mk] using h
    /-
      case refine_4
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      ⊢ Function.Surjective (StarAlgebra.elemental.characterSpaceToSpectrum a)
    -/
  · rintro ⟨z, hz⟩
    have hz' := (StarSubalgebra.spectrum_eq (hS := isClosed ℂ a)
      (a := ⟨a, self_mem ℂ a⟩) ▸ hz)
    /-
      case refine_4.mk
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      z : Complex
      hz : Membership.mem (spectrum Complex a) z
      hz' : Membership.mem (spectrum Complex ⟨a, ⋯⟩) z
      ⊢ Exists fun a_1 => Eq (StarAlgebra.elemental.characterSpaceToSpectrum a a_1)  …
    -/
    rw [CharacterSpace.mem_spectrum_iff_exists] at hz'
    /-
      case refine_4.mk
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      z : Complex
      hz : Membership.mem (spectrum Complex a) z
      hz' : Exists fun f => Eq (f ⟨a, ⋯⟩) z
      ⊢ Exists fun a_1 => Eq (StarAlgebra.elemental.characterSpaceToSpectrum a a_1)  …
    -/
    obtain ⟨φ, rfl⟩ := hz'
    /-
      case refine_4.mk.intro
      A : Type u_1
      inst✝¹ : CStarAlgebra A
      a : A
      inst✝ : IsStarNormal a
      φ : ↑(WeakDual.characterSpace Complex (Subtype fun x => Membership.mem (StarAl …
      hz : Membership.mem (spectrum Complex a) (φ ⟨a, ⋯⟩)
      ⊢ Exists fun a_1 => Eq (StarAlgebra.elemental.characterSpaceToSpectrum a a_1)  …
    -/
    exact ⟨φ, rfl⟩
    /-
      🎉 no goals
    -/


@[deprecated (since := "2024-11-05")]
alias _root_.elementalStarAlgebra.bijective_characterSpaceToSpectrum :=
  bijective_characterSpaceToSpectrum


/-- The homeomorphism between the character space of the unital C⋆-subalgebra generated by a
single normal element `a : A` and `spectrum ℂ a`. -/
noncomputable def characterSpaceHomeo :
    characterSpace ℂ (elemental ℂ a) ≃ₜ spectrum ℂ a :=
  @Continuous.homeoOfEquivCompactToT2 _ _ _ _ _ _
    (Equiv.ofBijective (characterSpaceToSpectrum a)
      (bijective_characterSpaceToSpectrum a))
    (continuous_characterSpaceToSpectrum a)


@[deprecated (since := "2024-11-05")]
alias _root_.elementalStarAlgebra.characterSpaceHomeo := characterSpaceHomeo


/-- **Continuous functional calculus.** Given a normal element `a : A` of a unital C⋆-algebra,
the continuous functional calculus is a `StarAlgEquiv` from the complex-valued continuous
functions on the spectrum of `a` to the unital C⋆-subalgebra generated by `a`. Moreover, this
equivalence identifies `(ContinuousMap.id ℂ).restrict (spectrum ℂ a))` with `a`; see
`continuousFunctionalCalculus_map_id`. As such it extends the polynomial functional calculus. -/
noncomputable def continuousFunctionalCalculus :
    C(spectrum ℂ a, ℂ) ≃⋆ₐ[ℂ] elemental ℂ a :=
  ((characterSpaceHomeo a).compStarAlgEquiv' ℂ ℂ).trans
    (gelfandStarTransform (elemental ℂ a)).symm


theorem continuousFunctionalCalculus_map_id :
    continuousFunctionalCalculus a ((ContinuousMap.id ℂ).restrict (spectrum ℂ a)) =
      ⟨a, self_mem ℂ a⟩ :=
  (gelfandStarTransform (elemental ℂ a)).symm_apply_apply _

