/-- A topological vector space `E` is said to be **barrelled** if all lower semicontinuous
seminorms on `E` are actually continuous. This is not the usual definition for TVS over `ℝ` or `ℂ`,
but this has the big advantage of working and giving sensible results over *any*
`NontriviallyNormedField`. In particular, the Banach-Steinhaus theorem holds for maps between such
a space and any space whose topology is generated by a family of seminorms. -/
class BarrelledSpace (𝕜 E : Type*) [SeminormedRing 𝕜] [AddGroup E] [SMul 𝕜 E]
    [TopologicalSpace E] : Prop where
  /-- In a barrelled space, all lower semicontinuous seminorms on `E` are actually continuous. -/
  continuous_of_lowerSemicontinuous : ∀ p : Seminorm 𝕜 E, LowerSemicontinuous p → Continuous p


theorem Seminorm.continuous_of_lowerSemicontinuous {𝕜 E : Type*} [AddGroup E] [SMul 𝕜 E]
    [SeminormedRing 𝕜] [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : Seminorm 𝕜 E)
    (hp : LowerSemicontinuous p) : Continuous p :=
  BarrelledSpace.continuous_of_lowerSemicontinuous p hp


theorem Seminorm.continuous_iSup
    {ι : Sort*} {𝕜 E : Type*} [NormedField 𝕜]  [AddCommGroup E] [Module 𝕜 E]
    [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : ι → Seminorm 𝕜 E)
    (hp : ∀ i, Continuous (p i)) (bdd : BddAbove (range p)) :
    Continuous (⨆ i, p i) := by
  /-
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : BddAbove (Set.range p)
    ⊢ Continuous (iSup fun i => ⇑(p i))
  -/
  rw [← Seminorm.coe_iSup_eq bdd]
  /-
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : BddAbove (Set.range p)
    ⊢ Continuous ⇑(iSup fun i => p i)
  -/
  refine Seminorm.continuous_of_lowerSemicontinuous _ ?_
  /-
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : BddAbove (Set.range p)
    ⊢ LowerSemicontinuous ⇑(iSup fun i => p i)
  -/
  rw [Seminorm.coe_iSup_eq bdd]
  /-
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : BddAbove (Set.range p)
    ⊢ LowerSemicontinuous (iSup fun i => ⇑(p i))
  -/
  rw [Seminorm.bddAbove_range_iff] at bdd
  /-
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : ∀ (x : E), BddAbove (Set.range fun i => (p i) x)
    ⊢ LowerSemicontinuous (iSup fun i => ⇑(p i))
  -/
  convert lowerSemicontinuous_ciSup (f := fun i x ↦ p i x) bdd (fun i ↦ (hp i).lowerSemicontinuous)
  /-
    case h.e'_5.h
    ι : Sort u_1
    𝕜 : Type u_2
    E : Type u_3
    inst✝⁴ : NormedField 𝕜
    inst✝³ : AddCommGroup E
    inst✝² : Module 𝕜 E
    inst✝¹ : TopologicalSpace E
    inst✝ : BarrelledSpace 𝕜 E
    p : ι → Seminorm 𝕜 E
    hp : ∀ (i : ι), Continuous ⇑(p i)
    bdd : ∀ (x : E), BddAbove (Set.range fun i => (p i) x)
    x✝ : E
    ⊢ Eq (iSup (fun i => ⇑(p i)) x✝) (iSup fun i => (p i) x✝)
  -/
  exact iSup_apply
  /-
    🎉 no goals
  -/


/-- Any TVS over a `NontriviallyNormedField` that is also a Baire space is barrelled. In
particular, this applies to Banach spaces and Fréchet spaces. -/
instance BaireSpace.instBarrelledSpace [TopologicalSpace E] [TopologicalAddGroup E]
    [ContinuousConstSMul 𝕜₁ E] [BaireSpace E] :
    BarrelledSpace 𝕜₁ E where
  continuous_of_lowerSemicontinuous := by
    -- Let `p` be a lower-semicontinuous seminorm on `E`.
    /-
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      ⊢ ∀ (p : Seminorm 𝕜₁ E), LowerSemicontinuous ⇑p → Continuous ⇑p
    -/
    intro p hp
    -- Consider the family of all `p`-closed-balls with integer radius.
    -- By lower semicontinuity, each of these closed balls is indeed closed...
    have h₁ : ∀ n : ℕ, IsClosed (p.closedBall (0 : E) n) := fun n ↦ by
      simpa [p.closedBall_zero_eq] using hp.isClosed_preimage n
    -- ... and clearly they cover the whole space.
    have h₂ : (⋃ n : ℕ, p.closedBall (0 : E) n) = univ :=
      eq_univ_of_forall fun x ↦ mem_iUnion.mpr (exists_nat_ge <| p (x - 0))
    -- Hence, one of them has nonempty interior. Let `n : ℕ` be its radius, and fix `x` an
    -- interior point.
    /-
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      ⊢ Continuous ⇑p
    -/
    rcases nonempty_interior_of_iUnion_of_closed h₁ h₂ with ⟨n, ⟨x, hxn⟩⟩
    -- To show that `p` is continuous, we will show that the `p`-closed-ball of
    -- radius `2*n` is a neighborhood of zero.
    /-
      case intro.intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      n : Nat
      x : E
      hxn : Membership.mem (interior (p.closedBall 0 ↑n)) x
      ⊢ Continuous ⇑p
    -/
    refine Seminorm.continuous' (r := n + n) ?_
    /-
      case intro.intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      n : Nat
      x : E
      hxn : Membership.mem (interior (p.closedBall 0 ↑n)) x
      ⊢ Membership.mem (nhds 0) (p.closedBall 0 (HAdd.hAdd ↑n ↑n))
    -/
    rw [p.closedBall_zero_eq] at hxn ⊢
    /-
      case intro.intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      n : Nat
      x : E
      hxn : Membership.mem (interior (setOf fun y => LE.le (p y) ↑n)) x
      ⊢ Membership.mem (nhds 0) (setOf fun y => LE.le (p y) (HAdd.hAdd ↑n ↑n))
    -/
    have hxn' : p x ≤ n := by convert interior_subset hxn
    -- By definition, we have `p x' ≤ n` for `x'` sufficiently close to `x`.
    -- In other words, `p (x + y) ≤ n` for `y` sufficiently close to `0`.
    /-
      case intro.intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      n : Nat
      x : E
      hxn : Membership.mem (interior (setOf fun y => LE.le (p y) ↑n)) x
      hxn' : LE.le (p x) ↑n
      ⊢ Membership.mem (nhds 0) (setOf fun y => LE.le (p y) (HAdd.hAdd ↑n ↑n))
    -/
    rw [mem_interior_iff_mem_nhds, ← map_add_left_nhds_zero] at hxn
    -- Hence, for `y` sufficiently close to `0`, we have
    -- `p y = p (x + y - x) ≤ p (x + y) + p x ≤ 2*n`
    /-
      case intro.intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹¹ : Nonempty κ
      inst✝¹⁰ : NontriviallyNormedField 𝕜₁
      inst✝⁹ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝⁸ : RingHomIsometric σ₁₂
      inst✝⁷ : AddCommGroup E
      inst✝⁶ : AddCommGroup F
      inst✝⁵ : Module 𝕜₁ E
      inst✝⁴ : Module 𝕜₂ F
      inst✝³ : TopologicalSpace E
      inst✝² : TopologicalAddGroup E
      inst✝¹ : ContinuousConstSMul 𝕜₁ E
      inst✝ : BaireSpace E
      p : Seminorm 𝕜₁ E
      hp : LowerSemicontinuous ⇑p
      h₁ : ∀ (n : Nat), IsClosed (p.closedBall 0 ↑n)
      h₂ : Eq (Set.iUnion fun n => p.closedBall 0 ↑n) Set.univ
      n : Nat
      x : E
      hxn : Membership.mem (Filter.map (fun x_1 => HAdd.hAdd x x_1) (nhds 0)) (setOf …
      hxn' : LE.le (p x) ↑n
      ⊢ Membership.mem (nhds 0) (setOf fun y => LE.le (p y) (HAdd.hAdd ↑n ↑n))
    -/
    filter_upwards [hxn] with y hy
    calc p y = p (x + y - x) := by rw [add_sub_cancel_left]
      _ ≤ p (x + y) + p x := map_sub_le_add _ _ _
      _ ≤ n + n := add_le_add hy hxn'


/-- The **Banach-Steinhaus** theorem, or **Uniform Boundedness Principle**, for maps from a
barrelled space to any space whose topology is generated by a family of seminorms. Use
`WithSeminorms.equicontinuous_TFAE` and `Seminorm.bound_of_continuous` to get explicit bounds on
the seminorms from equicontinuity. -/
protected theorem banach_steinhaus (H : ∀ k x, BddAbove (range fun i ↦ q k (𝓕 i x))) :
    UniformEquicontinuous ((↑) ∘ 𝓕) := by
  -- We just have to prove that `⊔ i, (q k) ∘ (𝓕 i)` is a (well-defined) continuous seminorm
  -- for all `k`.
  /-
    ι : Type u_2
    κ : Type u_3
    𝕜₁ : Type u_4
    𝕜₂ : Type u_5
    E : Type u_6
    F : Type u_7
    inst✝¹³ : Nonempty κ
    inst✝¹² : NontriviallyNormedField 𝕜₁
    inst✝¹¹ : NontriviallyNormedField 𝕜₂
    σ₁₂ : RingHom 𝕜₁ 𝕜₂
    inst✝¹⁰ : RingHomIsometric σ₁₂
    inst✝⁹ : AddCommGroup E
    inst✝⁸ : AddCommGroup F
    inst✝⁷ : Module 𝕜₁ E
    inst✝⁶ : Module 𝕜₂ F
    inst✝⁵ : UniformSpace E
    inst✝⁴ : UniformSpace F
    inst✝³ : UniformAddGroup E
    inst✝² : UniformAddGroup F
    inst✝¹ : ContinuousSMul 𝕜₁ E
    inst✝ : BarrelledSpace 𝕜₁ E
    𝓕 : ι → ContinuousLinearMap σ₁₂ E F
    q : SeminormFamily 𝕜₂ F κ
    hq : WithSeminorms q
    H : ∀ (k : κ) (x : E), BddAbove (Set.range fun i => (q k) ((𝓕 i) x))
    ⊢ UniformEquicontinuous (Function.comp DFunLike.coe 𝓕)
  -/
  refine (hq.uniformEquicontinuous_iff_bddAbove_and_continuous_iSup (toLinearMap ∘ 𝓕)).mpr ?_
  /-
    ι : Type u_2
    κ : Type u_3
    𝕜₁ : Type u_4
    𝕜₂ : Type u_5
    E : Type u_6
    F : Type u_7
    inst✝¹³ : Nonempty κ
    inst✝¹² : NontriviallyNormedField 𝕜₁
    inst✝¹¹ : NontriviallyNormedField 𝕜₂
    σ₁₂ : RingHom 𝕜₁ 𝕜₂
    inst✝¹⁰ : RingHomIsometric σ₁₂
    inst✝⁹ : AddCommGroup E
    inst✝⁸ : AddCommGroup F
    inst✝⁷ : Module 𝕜₁ E
    inst✝⁶ : Module 𝕜₂ F
    inst✝⁵ : UniformSpace E
    inst✝⁴ : UniformSpace F
    inst✝³ : UniformAddGroup E
    inst✝² : UniformAddGroup F
    inst✝¹ : ContinuousSMul 𝕜₁ E
    inst✝ : BarrelledSpace 𝕜₁ E
    𝓕 : ι → ContinuousLinearMap σ₁₂ E F
    q : SeminormFamily 𝕜₂ F κ
    hq : WithSeminorms q
    H : ∀ (k : κ) (x : E), BddAbove (Set.range fun i => (q k) ((𝓕 i) x))
    ⊢ ∀ (i : κ), And (BddAbove (Set.range fun k => (q i).comp (Function.comp Conti …
  -/
  intro k
  -- By assumption the supremum `⊔ i, q k (𝓕 i x)` is well-defined for all `x`, hence the
  -- supremum `⊔ i, (q k) ∘ (𝓕 i)` is well defined in the lattice of seminorms.
  have : BddAbove (range fun i ↦ (q k).comp (𝓕 i).toLinearMap) := by
    rw [Seminorm.bddAbove_range_iff]
    exact H k
  -- By definition of the lattice structure on seminorms, `⊔ i, (q k) ∘ (𝓕 i)` is the *pointwise*
  -- supremum of the continuous seminorms `(q k) ∘ (𝓕 i)`. Since `E` is barrelled, this supremum
  -- is continuous.
  exact ⟨this, Seminorm.continuous_iSup _
    (fun i ↦ (hq.continuous_seminorm k).comp (𝓕 i).continuous) this⟩


/-- Given a sequence of continuous linear maps which converges pointwise and for which the
domain is barrelled, the Banach-Steinhaus theorem is used to guarantee that the limit map
is a *continuous* linear map as well.

This actually works for any *countably generated* filter instead of `atTop : Filter ℕ`,
but the proof ultimately goes back to sequences. -/
protected def continuousLinearMapOfTendsto (hq : WithSeminorms q)
    [T2Space F] {l : Filter α} [l.IsCountablyGenerated]
    [l.NeBot] (g : α → E →SL[σ₁₂] F) {f : E → F} (h : Tendsto (fun n x ↦ g n x) l (𝓝 f)) :
    E →SL[σ₁₂] F where
  toLinearMap := linearMapOfTendsto _ _ h
  cont := by
    -- Since the filter `l` is countably generated and nontrivial, we can find a sequence
    -- `u : ℕ → α` that tends to `l`. By considering `g ∘ u` instead of `g`, we can thus assume
    -- that `α = ℕ` and `l = atTop`
    /-
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹⁷ : Nonempty κ
      inst✝¹⁶ : NontriviallyNormedField 𝕜₁
      inst✝¹⁵ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝¹⁴ : RingHomIsometric σ₁₂
      inst✝¹³ : AddCommGroup E
      inst✝¹² : AddCommGroup F
      inst✝¹¹ : Module 𝕜₁ E
      inst✝¹⁰ : Module 𝕜₂ F
      inst✝⁹ : UniformSpace E
      inst✝⁸ : UniformSpace F
      inst✝⁷ : UniformAddGroup E
      inst✝⁶ : UniformAddGroup F
      inst✝⁵ : ContinuousSMul 𝕜₁ E
      inst✝⁴ : BarrelledSpace 𝕜₁ E
      𝓕 : ι → ContinuousLinearMap σ₁₂ E F
      q : SeminormFamily 𝕜₂ F κ
      hq✝ : WithSeminorms q
      inst✝³ : ContinuousSMul 𝕜₂ F
      hq : WithSeminorms q
      inst✝² : T2Space F
      l : Filter α
      inst✝¹ : l.IsCountablyGenerated
      inst✝ : l.NeBot
      g : α → ContinuousLinearMap σ₁₂ E F
      f : E → F
      h : Filter.Tendsto (fun n x => (g n) x) l (nhds f)
      ⊢ Continuous (linearMapOfTendsto f (fun a => ↑(g a)) h).toFun
    -/
    rcases l.exists_seq_tendsto with ⟨u, hu⟩
    -- We claim that the limit is continuous because it's a limit of an equicontinuous family.
    -- By the Banach-Steinhaus theorem, this equicontinuity will follow from pointwise boundedness.
    /-
      case intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹⁷ : Nonempty κ
      inst✝¹⁶ : NontriviallyNormedField 𝕜₁
      inst✝¹⁵ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝¹⁴ : RingHomIsometric σ₁₂
      inst✝¹³ : AddCommGroup E
      inst✝¹² : AddCommGroup F
      inst✝¹¹ : Module 𝕜₁ E
      inst✝¹⁰ : Module 𝕜₂ F
      inst✝⁹ : UniformSpace E
      inst✝⁸ : UniformSpace F
      inst✝⁷ : UniformAddGroup E
      inst✝⁶ : UniformAddGroup F
      inst✝⁵ : ContinuousSMul 𝕜₁ E
      inst✝⁴ : BarrelledSpace 𝕜₁ E
      𝓕 : ι → ContinuousLinearMap σ₁₂ E F
      q : SeminormFamily 𝕜₂ F κ
      hq✝ : WithSeminorms q
      inst✝³ : ContinuousSMul 𝕜₂ F
      hq : WithSeminorms q
      inst✝² : T2Space F
      l : Filter α
      inst✝¹ : l.IsCountablyGenerated
      inst✝ : l.NeBot
      g : α → ContinuousLinearMap σ₁₂ E F
      f : E → F
      h : Filter.Tendsto (fun n x => (g n) x) l (nhds f)
      u : Nat → α
      hu : Filter.Tendsto u Filter.atTop l
      ⊢ Continuous (linearMapOfTendsto f (fun a => ↑(g a)) h).toFun
    -/
    refine (h.comp hu).continuous_of_equicontinuous (hq.banach_steinhaus ?_).equicontinuous
    -- For `k` and `x` fixed, we need to show that `(i : ℕ) ↦ q k (g i x)` is bounded.
    /-
      case intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹⁷ : Nonempty κ
      inst✝¹⁶ : NontriviallyNormedField 𝕜₁
      inst✝¹⁵ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝¹⁴ : RingHomIsometric σ₁₂
      inst✝¹³ : AddCommGroup E
      inst✝¹² : AddCommGroup F
      inst✝¹¹ : Module 𝕜₁ E
      inst✝¹⁰ : Module 𝕜₂ F
      inst✝⁹ : UniformSpace E
      inst✝⁸ : UniformSpace F
      inst✝⁷ : UniformAddGroup E
      inst✝⁶ : UniformAddGroup F
      inst✝⁵ : ContinuousSMul 𝕜₁ E
      inst✝⁴ : BarrelledSpace 𝕜₁ E
      𝓕 : ι → ContinuousLinearMap σ₁₂ E F
      q : SeminormFamily 𝕜₂ F κ
      hq✝ : WithSeminorms q
      inst✝³ : ContinuousSMul 𝕜₂ F
      hq : WithSeminorms q
      inst✝² : T2Space F
      l : Filter α
      inst✝¹ : l.IsCountablyGenerated
      inst✝ : l.NeBot
      g : α → ContinuousLinearMap σ₁₂ E F
      f : E → F
      h : Filter.Tendsto (fun n x => (g n) x) l (nhds f)
      u : Nat → α
      hu : Filter.Tendsto u Filter.atTop l
      ⊢ ∀ (k : κ) (x : E), BddAbove (Set.range fun i => (q k) ((g (u i)) x))
    -/
    intro k x
    -- This follows from the fact that this sequences converges (to `q k (f x)`) by hypothesis and
    -- continuity of `q k`.
    /-
      case intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹⁷ : Nonempty κ
      inst✝¹⁶ : NontriviallyNormedField 𝕜₁
      inst✝¹⁵ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝¹⁴ : RingHomIsometric σ₁₂
      inst✝¹³ : AddCommGroup E
      inst✝¹² : AddCommGroup F
      inst✝¹¹ : Module 𝕜₁ E
      inst✝¹⁰ : Module 𝕜₂ F
      inst✝⁹ : UniformSpace E
      inst✝⁸ : UniformSpace F
      inst✝⁷ : UniformAddGroup E
      inst✝⁶ : UniformAddGroup F
      inst✝⁵ : ContinuousSMul 𝕜₁ E
      inst✝⁴ : BarrelledSpace 𝕜₁ E
      𝓕 : ι → ContinuousLinearMap σ₁₂ E F
      q : SeminormFamily 𝕜₂ F κ
      hq✝ : WithSeminorms q
      inst✝³ : ContinuousSMul 𝕜₂ F
      hq : WithSeminorms q
      inst✝² : T2Space F
      l : Filter α
      inst✝¹ : l.IsCountablyGenerated
      inst✝ : l.NeBot
      g : α → ContinuousLinearMap σ₁₂ E F
      f : E → F
      h : Filter.Tendsto (fun n x => (g n) x) l (nhds f)
      u : Nat → α
      hu : Filter.Tendsto u Filter.atTop l
      k : κ
      x : E
      ⊢ BddAbove (Set.range fun i => (q k) ((g (u i)) x))
    -/
    rw [tendsto_pi_nhds] at h
    /-
      case intro
      α : Type u_1
      ι : Type u_2
      κ : Type u_3
      𝕜₁ : Type u_4
      𝕜₂ : Type u_5
      E : Type u_6
      F : Type u_7
      inst✝¹⁷ : Nonempty κ
      inst✝¹⁶ : NontriviallyNormedField 𝕜₁
      inst✝¹⁵ : NontriviallyNormedField 𝕜₂
      σ₁₂ : RingHom 𝕜₁ 𝕜₂
      inst✝¹⁴ : RingHomIsometric σ₁₂
      inst✝¹³ : AddCommGroup E
      inst✝¹² : AddCommGroup F
      inst✝¹¹ : Module 𝕜₁ E
      inst✝¹⁰ : Module 𝕜₂ F
      inst✝⁹ : UniformSpace E
      inst✝⁸ : UniformSpace F
      inst✝⁷ : UniformAddGroup E
      inst✝⁶ : UniformAddGroup F
      inst✝⁵ : ContinuousSMul 𝕜₁ E
      inst✝⁴ : BarrelledSpace 𝕜₁ E
      𝓕 : ι → ContinuousLinearMap σ₁₂ E F
      q : SeminormFamily 𝕜₂ F κ
      hq✝ : WithSeminorms q
      inst✝³ : ContinuousSMul 𝕜₂ F
      hq : WithSeminorms q
      inst✝² : T2Space F
      l : Filter α
      inst✝¹ : l.IsCountablyGenerated
      inst✝ : l.NeBot
      g : α → ContinuousLinearMap σ₁₂ E F
      f : E → F
      h : ∀ (x : E), Filter.Tendsto (fun i => (g i) x) l (nhds (f x))
      u : Nat → α
      hu : Filter.Tendsto u Filter.atTop l
      k : κ
      x : E
      ⊢ BddAbove (Set.range fun i => (q k) ((g (u i)) x))
    -/
    exact (((hq.continuous_seminorm k).tendsto _).comp <| (h x).comp hu).bddAbove_range
    /-
      🎉 no goals
    -/

