local notation "ιₜ" => TensorAlgebra.ι R


/-- The quotient by the ideal generated by this relation is the universal enveloping algebra.

Note that we have avoided using the more natural expression:
| lie_compat (x y : L) : rel (ιₜ ⁅x, y⁆) ⁅ιₜ x, ιₜ y⁆
so that our construction needs only the semiring structure of the tensor algebra. -/
inductive Rel : TensorAlgebra R L → TensorAlgebra R L → Prop
  | lie_compat (x y : L) : Rel (ιₜ ⁅x, y⁆ + ιₜ y * ιₜ x) (ιₜ x * ιₜ y)


/-- The universal enveloping algebra of a Lie algebra. -/
def UniversalEnvelopingAlgebra :=
  RingQuot (UniversalEnvelopingAlgebra.Rel R L)


instance instInhabited : Inhabited (UniversalEnvelopingAlgebra R L) :=
  inferInstanceAs (Inhabited (RingQuot (UniversalEnvelopingAlgebra.Rel R L)))


instance instRing : Ring (UniversalEnvelopingAlgebra R L) :=
  inferInstanceAs (Ring (RingQuot (UniversalEnvelopingAlgebra.Rel R L)))


instance instAlgebra : Algebra R (UniversalEnvelopingAlgebra R L) :=
  inferInstanceAs (Algebra R (RingQuot (UniversalEnvelopingAlgebra.Rel R L)))



/-- The quotient map from the tensor algebra to the universal enveloping algebra as a morphism of
associative algebras. -/
def mkAlgHom : TensorAlgebra R L →ₐ[R] UniversalEnvelopingAlgebra R L :=
  RingQuot.mkAlgHom R (Rel R L)


/-- The natural Lie algebra morphism from a Lie algebra to its universal enveloping algebra. -/
@[simps!] -- Porting note (https://github.com/leanprover-community/mathlib4/issues/11445): added
def ι : L →ₗ⁅R⁆ UniversalEnvelopingAlgebra R L :=
  { (mkAlgHom R L).toLinearMap.comp ιₜ with
    map_lie' := fun {x y} => by
      suffices mkAlgHom R L (ιₜ ⁅x, y⁆ + ιₜ y * ιₜ x) = mkAlgHom R L (ιₜ x * ιₜ y) by
        rw [map_mul] at this; simp [LieRing.of_associative_ring_bracket, ← this]
      /-
        R : Type u₁
        L : Type u₂
        inst✝² : CommRing R
        inst✝¹ : LieRing L
        inst✝ : LieAlgebra R L
        x y : L
        ⊢ Eq ((UniversalEnvelopingAlgebra.mkAlgHom R L) (HAdd.hAdd ((TensorAlgebra.ι R …
      -/
      exact RingQuot.mkAlgHom_rel _ (Rel.lie_compat x y) }
      /-
        🎉 no goals
      -/


/-- The universal property of the universal enveloping algebra: Lie algebra morphisms into
associative algebras lift to associative algebra morphisms from the universal enveloping algebra. -/
def lift : (L →ₗ⁅R⁆ A) ≃ (UniversalEnvelopingAlgebra R L →ₐ[R] A) where
  toFun f :=
    RingQuot.liftAlgHom R
      ⟨TensorAlgebra.lift R (f : L →ₗ[R] A), by
        /-
          R : Type u₁
          L : Type u₂
          inst✝⁴ : CommRing R
          inst✝³ : LieRing L
          inst✝² : LieAlgebra R L
          A : Type u₃
          inst✝¹ : Ring A
          inst✝ : Algebra R A
          f✝ f : LieHom R L A
          ⊢ ∀ ⦃x y : TensorAlgebra R L⦄, UniversalEnvelopingAlgebra.Rel R L x y → Eq ((( …
        -/
        intro a b h; induction h
        simp only [LieRing.of_associative_ring_bracket, map_add, TensorAlgebra.lift_ι_apply,
          LieHom.coe_toLinearMap, LieHom.map_lie, map_mul, sub_add_cancel]⟩
  invFun F := (F : UniversalEnvelopingAlgebra R L →ₗ⁅R⁆ A).comp (ι R)
  left_inv f := by
    /-
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f✝ f : LieHom R L A
      ⊢ Eq ((fun F => F.toLieHom.comp (UniversalEnvelopingAlgebra.ι R)) ((fun f => ( …
    -/
    ext
    -- Porting note: was
    -- simp only [ι, mkAlgHom, TensorAlgebra.lift_ι_apply, LieHom.coe_toLinearMap,
    --   LinearMap.toFun_eq_coe, LinearMap.coe_comp, LieHom.coe_comp, AlgHom.coe_toLieHom,
    --   LieHom.coe_mk, Function.comp_apply, AlgHom.toLinearMap_apply,
    --   RingQuot.liftAlgHom_mkAlgHom_apply]
    simp only [LieHom.coe_comp, Function.comp_apply, AlgHom.coe_toLieHom,
      UniversalEnvelopingAlgebra.ι_apply, mkAlgHom]
    -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
    /-
      case h
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f✝ f : LieHom R L A
      x✝ : L
      ⊢ Eq (((RingQuot.liftAlgHom R) ⟨(TensorAlgebra.lift R) ↑f, ⋯⟩) ((RingQuot.mkAl …
    -/
    erw [RingQuot.liftAlgHom_mkAlgHom_apply]
    /-
      case h
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f✝ f : LieHom R L A
      x✝ : L
      ⊢ Eq (((TensorAlgebra.lift R) ↑f) ((TensorAlgebra.ι R) x✝)) (f x✝)
    -/
    simp only [TensorAlgebra.lift_ι_apply, LieHom.coe_toLinearMap]
    /-
      🎉 no goals
    -/
  right_inv F := by
    /-
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f : LieHom R L A
      F : AlgHom R (UniversalEnvelopingAlgebra R L) A
      ⊢ Eq ((fun f => (RingQuot.liftAlgHom R) ⟨(TensorAlgebra.lift R) ↑f, ⋯⟩) ((fun  …
    -/
    apply RingQuot.ringQuot_ext'
    /-
      case w
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f : LieHom R L A
      F : AlgHom R (UniversalEnvelopingAlgebra R L) A
      ⊢ Eq (((fun f => (RingQuot.liftAlgHom R) ⟨(TensorAlgebra.lift R) ↑f, ⋯⟩) ((fun …
    -/
    ext
    -- Porting note: was
    -- simp only [ι, mkAlgHom, TensorAlgebra.lift_ι_apply, LieHom.coe_toLinearMap,
    --   LinearMap.toFun_eq_coe, LinearMap.coe_comp, LieHom.toLinearMap_comp,
    --   AlgHom.comp_toLinearMap, Function.comp_apply, AlgHom.toLinearMap_apply,
    --   RingQuot.liftAlgHom_mkAlgHom_apply, AlgHom.coe_toLieHom, LieHom.coe_mk]
    -- extra `rfl` after https://github.com/leanprover/lean4/pull/2644
    /-
      case w.w.h
      R : Type u₁
      L : Type u₂
      inst✝⁴ : CommRing R
      inst✝³ : LieRing L
      inst✝² : LieAlgebra R L
      A : Type u₃
      inst✝¹ : Ring A
      inst✝ : Algebra R A
      f : LieHom R L A
      F : AlgHom R (UniversalEnvelopingAlgebra R L) A
      x✝ : L
      ⊢ Eq (((((fun f => (RingQuot.liftAlgHom R) ⟨(TensorAlgebra.lift R) ↑f, ⋯⟩) ((f …
    -/
    simp [mkAlgHom]; rfl
                     /-
                       🎉 no goals
                     -/


@[simp]
theorem lift_symm_apply (F : UniversalEnvelopingAlgebra R L →ₐ[R] A) :
    (lift R).symm F = (F : UniversalEnvelopingAlgebra R L →ₗ⁅R⁆ A).comp (ι R) :=
  rfl


@[simp]
theorem ι_comp_lift : lift R f ∘ ι R = f :=
  funext <| LieHom.ext_iff.mp <| (lift R).symm_apply_apply f

-- Porting note: moved `@[simp]` to the next theorem (LHS simplifies)

theorem lift_ι_apply (x : L) : lift R f (ι R x) = f x := by
  /-
    R : Type u₁
    L : Type u₂
    inst✝⁴ : CommRing R
    inst✝³ : LieRing L
    inst✝² : LieAlgebra R L
    A : Type u₃
    inst✝¹ : Ring A
    inst✝ : Algebra R A
    f : LieHom R L A
    x : L
    ⊢ Eq (((UniversalEnvelopingAlgebra.lift R) f) ((UniversalEnvelopingAlgebra.ι R …
  -/
  rw [← Function.comp_apply (f := lift R f) (g := ι R) (x := x), ι_comp_lift]
  /-
    🎉 no goals
  -/


@[simp]
theorem lift_ι_apply' (x : L) :
    lift R f ((UniversalEnvelopingAlgebra.mkAlgHom R L) (ιₜ x)) = f x := by
  /-
    R : Type u₁
    L : Type u₂
    inst✝⁴ : CommRing R
    inst✝³ : LieRing L
    inst✝² : LieAlgebra R L
    A : Type u₃
    inst✝¹ : Ring A
    inst✝ : Algebra R A
    f : LieHom R L A
    x : L
    ⊢ Eq (((UniversalEnvelopingAlgebra.lift R) f) ((UniversalEnvelopingAlgebra.mkA …
  -/
  simpa using lift_ι_apply R f x
  /-
    🎉 no goals
  -/


theorem lift_unique (g : UniversalEnvelopingAlgebra R L →ₐ[R] A) : g ∘ ι R = f ↔ g = lift R f := by
  /-
    R : Type u₁
    L : Type u₂
    inst✝⁴ : CommRing R
    inst✝³ : LieRing L
    inst✝² : LieAlgebra R L
    A : Type u₃
    inst✝¹ : Ring A
    inst✝ : Algebra R A
    f : LieHom R L A
    g : AlgHom R (UniversalEnvelopingAlgebra R L) A
    ⊢ Iff (Eq (Function.comp ⇑g ⇑(UniversalEnvelopingAlgebra.ι R)) ⇑f) (Eq g ((Uni …
  -/
  refine Iff.trans ?_ (lift R).symm_apply_eq
  /-
    R : Type u₁
    L : Type u₂
    inst✝⁴ : CommRing R
    inst✝³ : LieRing L
    inst✝² : LieAlgebra R L
    A : Type u₃
    inst✝¹ : Ring A
    inst✝ : Algebra R A
    f : LieHom R L A
    g : AlgHom R (UniversalEnvelopingAlgebra R L) A
    ⊢ Iff (Eq (Function.comp ⇑g ⇑(UniversalEnvelopingAlgebra.ι R)) ⇑f) (Eq ((Unive …
  -/
                                  /-
                                    🎉 no goals
                                  -/
  constructor <;> · intro h; ext; simp [← h]
                                  /-
                                    🎉 no goals
                                  -/


/-- See note [partially-applied ext lemmas]. -/
@[ext]
theorem hom_ext {g₁ g₂ : UniversalEnvelopingAlgebra R L →ₐ[R] A}
    (h :
      (g₁ : UniversalEnvelopingAlgebra R L →ₗ⁅R⁆ A).comp (ι R) =
        (g₂ : UniversalEnvelopingAlgebra R L →ₗ⁅R⁆ A).comp (ι R)) :
    g₁ = g₂ :=
                                                      /-
                                                        R : Type u₁
                                                        L : Type u₂
                                                        inst✝⁴ : CommRing R
                                                        inst✝³ : LieRing L
                                                        inst✝² : LieAlgebra R L
                                                        A : Type u₃
                                                        inst✝¹ : Ring A
                                                        inst✝ : Algebra R A
                                                        g₁ g₂ : AlgHom R (UniversalEnvelopingAlgebra R L) A
                                                        h : Eq (g₁.toLieHom.comp (UniversalEnvelopingAlgebra.ι R)) (g₂.toLieHom.comp ( …
                                                        ⊢ Eq ((UniversalEnvelopingAlgebra.lift R).symm g₁) ((UniversalEnvelopingAlgebr …
                                                      -/
  have h' : (lift R).symm g₁ = (lift R).symm g₂ := by ext; simp [h]
                                                           /-
                                                             🎉 no goals
                                                           -/
  (lift R).symm.injective h'


