/-- If `P` is a multiplicative morphism property which is stable under base change on a category
`C` with pullbacks, then `P` induces a pretopology, where coverings are given by presieves whose
elements satisfy `P`. -/
def pretopology (P : MorphismProperty C) [P.IsMultiplicative] [P.IsStableUnderBaseChange] :
    Pretopology C where
  coverings X S := ∀ {Y : C} {f : Y ⟶ X}, S f → P f
  has_isos X Y f h Z g hg := by
    /-
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X Y : C
      f : Quiver.Hom Y X
      h : CategoryTheory.IsIso f
      Z : C
      g : Quiver.Hom Z X
      hg : CategoryTheory.Presieve.singleton f g
      ⊢ P g
    -/
    cases hg
    /-
      case mk
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X Y : C
      f : Quiver.Hom Y X
      h : CategoryTheory.IsIso f
      ⊢ P f
    -/
    exact P.of_isIso f
    /-
      🎉 no goals
    -/
  pullbacks X Y f S hS Z g hg := by
    /-
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X Y : C
      f : Quiver.Hom Y X
      S : CategoryTheory.Presieve X
      hS : Membership.mem ((fun X S => ∀ {Y : C} {f : Quiver.Hom Y X}, S f → P f) X) S
      Z : C
      g : Quiver.Hom Z Y
      hg : CategoryTheory.Presieve.pullbackArrows f S g
      ⊢ P g
    -/
    obtain ⟨Z, g, hg⟩ := hg
    /-
      case mk
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X Y✝ : C
      f : Quiver.Hom Y✝ X
      S : CategoryTheory.Presieve X
      hS : Membership.mem ((fun X S => ∀ {Y : C} {f : Quiver.Hom Y X}, S f → P f) X) S
      Y Z : C
      g : Quiver.Hom Z X
      hg : S g
      ⊢ P (CategoryTheory.Limits.pullback.snd g f)
    -/
    apply P.pullback_snd g f (hS hg)
    /-
      🎉 no goals
    -/
  transitive X S Ti hS hTi Y f hf := by
    /-
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X : C
      S : CategoryTheory.Presieve X
      Ti : ⦃Y : C⦄ → (f : Quiver.Hom Y X) → S f → CategoryTheory.Presieve Y
      hS : Membership.mem ((fun X S => ∀ {Y : C} {f : Quiver.Hom Y X}, S f → P f) X) S
      hTi : ∀ ⦃Y : C⦄ (f : Quiver.Hom Y X) (H : S f), Membership.mem ((fun X S => ∀  …
      Y : C
      f : Quiver.Hom Y X
      hf : S.bind Ti f
      ⊢ P f
    -/
    obtain ⟨Z, g, h, H, H', rfl⟩ := hf
    /-
      case intro.intro.intro.intro.intro
      C : Type u_1
      inst✝³ : CategoryTheory.Category.{?u.29, u_1} C
      inst✝² : CategoryTheory.Limits.HasPullbacks C
      P : CategoryTheory.MorphismProperty C
      inst✝¹ : P.IsMultiplicative
      inst✝ : P.IsStableUnderBaseChange
      X : C
      S : CategoryTheory.Presieve X
      Ti : ⦃Y : C⦄ → (f : Quiver.Hom Y X) → S f → CategoryTheory.Presieve Y
      hS : Membership.mem ((fun X S => ∀ {Y : C} {f : Quiver.Hom Y X}, S f → P f) X) S
      hTi : ∀ ⦃Y : C⦄ (f : Quiver.Hom Y X) (H : S f), Membership.mem ((fun X S => ∀  …
      Y Z : C
      g : Quiver.Hom Y Z
      h : Quiver.Hom Z X
      H : S h
      H' : Ti h H g
      ⊢ P (CategoryTheory.CategoryStruct.comp g h)
    -/
    exact comp_mem _ _ _ (hTi h H H') (hS H)
    /-
      🎉 no goals
    -/


/-- To a morphism property `P` satisfying the conditions of `MorphismProperty.pretopology`, we
associate the Grothendieck topology generated by `P.pretopology`. -/
abbrev grothendieckTopology (P : MorphismProperty C) [P.IsMultiplicative]
    [P.IsStableUnderBaseChange] : GrothendieckTopology C :=
  P.pretopology.toGrothendieck


lemma pretopology_le (hPQ : P ≤ Q) : P.pretopology ≤ Q.pretopology :=
  fun _ _ hS _ f hf ↦ hPQ f (hS hf)


variable (P Q) in
lemma pretopology_inf :
    (P ⊓ Q).pretopology = P.pretopology ⊓ Q.pretopology := by
  /-
    C : Type u_1
    inst✝⁵ : CategoryTheory.Category.{u_2, u_1} C
    inst✝⁴ : CategoryTheory.Limits.HasPullbacks C
    P Q : CategoryTheory.MorphismProperty C
    inst✝³ : P.IsMultiplicative
    inst✝² : P.IsStableUnderBaseChange
    inst✝¹ : Q.IsMultiplicative
    inst✝ : Q.IsStableUnderBaseChange
    ⊢ Eq (Min.min P Q).pretopology (Min.min P.pretopology Q.pretopology)
  -/
  ext X S
  exact ⟨fun hS ↦ ⟨fun hf ↦ (hS hf).left, fun hf ↦ (hS hf).right⟩,
    fun h ↦ fun hf ↦ ⟨h.left hf, h.right hf⟩⟩


