local notation "lib" => FreeNonUnitalNonAssocAlgebra


local notation "lib.lift" => FreeNonUnitalNonAssocAlgebra.lift


local notation "lib.of" => FreeNonUnitalNonAssocAlgebra.of


local notation "lib.lift_of_apply" => FreeNonUnitalNonAssocAlgebra.lift_of_apply


local notation "lib.lift_comp_of" => FreeNonUnitalNonAssocAlgebra.lift_comp_of


/-- The quotient of `lib R X` by the equivalence relation generated by this relation will give us
the free Lie algebra. -/
inductive Rel : lib R X → lib R X → Prop
  | lie_self (a : lib R X) : Rel (a * a) 0
  | leibniz_lie (a b c : lib R X) : Rel (a * (b * c)) (a * b * c + b * (a * c))
  | smul (t : R) {a b : lib R X} : Rel a b → Rel (t • a) (t • b)
  | add_right {a b : lib R X} (c : lib R X) : Rel a b → Rel (a + c) (b + c)
  | mul_left (a : lib R X) {b c : lib R X} : Rel b c → Rel (a * b) (a * c)
  | mul_right {a b : lib R X} (c : lib R X) : Rel a b → Rel (a * c) (b * c)


theorem Rel.addLeft (a : lib R X) {b c : lib R X} (h : Rel R X b c) : Rel R X (a + b) (a + c) := by
  /-
    R : Type u
    X : Type v
    inst✝ : CommRing R
    a b c : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X b c
    ⊢ FreeLieAlgebra.Rel R X (HAdd.hAdd a b) (HAdd.hAdd a c)
  -/
  rw [add_comm _ b, add_comm _ c]; exact h.add_right _
                                   /-
                                     🎉 no goals
                                   -/


theorem Rel.neg {a b : lib R X} (h : Rel R X a b) : Rel R X (-a) (-b) := by
  /-
    R : Type u
    X : Type v
    inst✝ : CommRing R
    a b : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X a b
    ⊢ FreeLieAlgebra.Rel R X (Neg.neg a) (Neg.neg b)
  -/
  simpa only [neg_one_smul] using h.smul (-1)
  /-
    🎉 no goals
  -/


theorem Rel.subLeft (a : lib R X) {b c : lib R X} (h : Rel R X b c) : Rel R X (a - b) (a - c) := by
  /-
    R : Type u
    X : Type v
    inst✝ : CommRing R
    a b c : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X b c
    ⊢ FreeLieAlgebra.Rel R X (HSub.hSub a b) (HSub.hSub a c)
  -/
  simpa only [sub_eq_add_neg] using h.neg.addLeft a
  /-
    🎉 no goals
  -/


theorem Rel.subRight {a b : lib R X} (c : lib R X) (h : Rel R X a b) : Rel R X (a - c) (b - c) := by
  /-
    R : Type u
    X : Type v
    inst✝ : CommRing R
    a b c : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X a b
    ⊢ FreeLieAlgebra.Rel R X (HSub.hSub a c) (HSub.hSub b c)
  -/
  simpa only [sub_eq_add_neg] using h.add_right (-c)
  /-
    🎉 no goals
  -/


theorem Rel.smulOfTower {S : Type*} [Monoid S] [DistribMulAction S R] [IsScalarTower S R R] (t : S)
    (a b : lib R X) (h : Rel R X a b) : Rel R X (t • a) (t • b) := by
  /-
    R : Type u
    X : Type v
    inst✝³ : CommRing R
    S : Type u_1
    inst✝² : Monoid S
    inst✝¹ : DistribMulAction S R
    inst✝ : IsScalarTower S R R
    t : S
    a b : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X a b
    ⊢ FreeLieAlgebra.Rel R X (HSMul.hSMul t a) (HSMul.hSMul t b)
  -/
  rw [← smul_one_smul R t a, ← smul_one_smul R t b]
  /-
    R : Type u
    X : Type v
    inst✝³ : CommRing R
    S : Type u_1
    inst✝² : Monoid S
    inst✝¹ : DistribMulAction S R
    inst✝ : IsScalarTower S R R
    t : S
    a b : FreeNonUnitalNonAssocAlgebra R X
    h : FreeLieAlgebra.Rel R X a b
    ⊢ FreeLieAlgebra.Rel R X (HSMul.hSMul (HSMul.hSMul t 1) a) (HSMul.hSMul (HSMul …
  -/
  exact h.smul _
  /-
    🎉 no goals
  -/


/-- The free Lie algebra on the type `X` with coefficients in the commutative ring `R`. -/
def FreeLieAlgebra :=
  Quot (FreeLieAlgebra.Rel R X)


                                                /-
                                                  R : Type u
                                                  X : Type v
                                                  inst✝ : CommRing R
                                                  ⊢ Inhabited (FreeLieAlgebra R X)
                                                -/
instance : Inhabited (FreeLieAlgebra R X) := by rw [FreeLieAlgebra]; infer_instance
                                                                     /-
                                                                       🎉 no goals
                                                                     -/


instance {S : Type*} [Monoid S] [DistribMulAction S R] [IsScalarTower S R R] :
    SMul S (FreeLieAlgebra R X) where smul t := Quot.map (t • ·) (Rel.smulOfTower t)


instance {S : Type*} [Monoid S] [DistribMulAction S R] [DistribMulAction Sᵐᵒᵖ R]
    [IsScalarTower S R R] [IsCentralScalar S R] : IsCentralScalar S (FreeLieAlgebra R X) where
  op_smul_eq_smul t := Quot.ind fun a => congr_arg (Quot.mk _) (op_smul_eq_smul t a)


instance : Zero (FreeLieAlgebra R X) where zero := Quot.mk _ 0


instance : Add (FreeLieAlgebra R X) where
  add := Quot.map₂ (· + ·) (fun _ _ _ => Rel.addLeft _) fun _ _ _ => Rel.add_right _


instance : Neg (FreeLieAlgebra R X) where neg := Quot.map Neg.neg fun _ _ => Rel.neg


instance : Sub (FreeLieAlgebra R X) where
  sub := Quot.map₂ Sub.sub (fun _ _ _ => Rel.subLeft _) fun _ _ _ => Rel.subRight _


instance : AddGroup (FreeLieAlgebra R X) :=
  Function.Surjective.addGroup (Quot.mk _) Quot.mk_surjective rfl (fun _ _ => rfl)
    (fun _ => rfl) (fun _ _ => rfl) (fun _ _ => rfl) fun _ _ => rfl


instance : AddCommSemigroup (FreeLieAlgebra R X) :=
  Function.Surjective.addCommSemigroup (Quot.mk _) Quot.mk_surjective fun _ _ => rfl


instance : AddCommGroup (FreeLieAlgebra R X) :=
  { (inferInstance : AddGroup (FreeLieAlgebra R X)),
    (inferInstance :  AddCommSemigroup (FreeLieAlgebra R X)) with }


instance {S : Type*} [Semiring S] [Module S R] [IsScalarTower S R R] :
    Module S (FreeLieAlgebra R X) :=
  Function.Surjective.module S ⟨⟨Quot.mk (Rel R X), rfl⟩, fun _ _ => rfl⟩
    Quot.mk_surjective (fun _ _ => rfl)


/-- Note that here we turn the `Mul` coming from the `NonUnitalNonAssocSemiring` structure
on `lib R X` into a `Bracket` on `FreeLieAlgebra`. -/
instance : LieRing (FreeLieAlgebra R X) where
  bracket := Quot.map₂ (· * ·) (fun _ _ _ => Rel.mul_left _) fun _ _ _ => Rel.mul_right _
                /-
                  R : Type u
                  X : Type v
                  inst✝ : CommRing R
                  ⊢ ∀ (x y z : FreeLieAlgebra R X), Eq (Bracket.bracket (HAdd.hAdd x y) z) (HAdd …
                -/
  add_lie := by rintro ⟨a⟩ ⟨b⟩ ⟨c⟩; change Quot.mk _ _ = Quot.mk _ _; simp_rw [add_mul]
                                                                      /-
                                                                        🎉 no goals
                                                                      -/
                /-
                  R : Type u
                  X : Type v
                  inst✝ : CommRing R
                  ⊢ ∀ (x y z : FreeLieAlgebra R X), Eq (Bracket.bracket x (HAdd.hAdd y z)) (HAdd …
                -/
  lie_add := by rintro ⟨a⟩ ⟨b⟩ ⟨c⟩; change Quot.mk _ _ = Quot.mk _ _; simp_rw [mul_add]
                                                                      /-
                                                                        🎉 no goals
                                                                      -/
                 /-
                   R : Type u
                   X : Type v
                   inst✝ : CommRing R
                   ⊢ ∀ (x : FreeLieAlgebra R X), Eq (Bracket.bracket x x) 0
                 -/
  lie_self := by rintro ⟨a⟩; exact Quot.sound (Rel.lie_self a)
                             /-
                               🎉 no goals
                             -/
                    /-
                      R : Type u
                      X : Type v
                      inst✝ : CommRing R
                      ⊢ ∀ (x y z : FreeLieAlgebra R X), Eq (Bracket.bracket x (Bracket.bracket y z)) …
                    -/
  leibniz_lie := by rintro ⟨a⟩ ⟨b⟩ ⟨c⟩; exact Quot.sound (Rel.leibniz_lie a b c)
                                        /-
                                          🎉 no goals
                                        -/


instance : LieAlgebra R (FreeLieAlgebra R X) where
  lie_smul := by
    /-
      R : Type u
      X : Type v
      inst✝ : CommRing R
      ⊢ ∀ (t : R) (x y : FreeLieAlgebra R X), Eq (Bracket.bracket x (HSMul.hSMul t y …
    -/
    rintro t ⟨a⟩ ⟨c⟩
    /-
      case mk.mk
      R : Type u
      X : Type v
      inst✝ : CommRing R
      t : R
      x✝ : FreeLieAlgebra R X
      a : FreeNonUnitalNonAssocAlgebra R X
      y✝ : FreeLieAlgebra R X
      c : FreeNonUnitalNonAssocAlgebra R X
      ⊢ Eq (Bracket.bracket (Quot.mk (FreeLieAlgebra.Rel R X) a) (HSMul.hSMul t (Quo …
    -/
    change Quot.mk _ (a • t • c) = Quot.mk _ (t • a • c)
    /-
      case mk.mk
      R : Type u
      X : Type v
      inst✝ : CommRing R
      t : R
      x✝ : FreeLieAlgebra R X
      a : FreeNonUnitalNonAssocAlgebra R X
      y✝ : FreeLieAlgebra R X
      c : FreeNonUnitalNonAssocAlgebra R X
      ⊢ Eq (Quot.mk (FreeLieAlgebra.Rel R X) (HSMul.hSMul a (HSMul.hSMul t c))) (Quo …
    -/
    rw [← smul_comm]
    /-
      🎉 no goals
    -/


/-- The embedding of `X` into the free Lie algebra of `X` with coefficients in the commutative ring
`R`. -/
def of : X → FreeLieAlgebra R X := fun x => Quot.mk _ (lib.of R x)


/-- An auxiliary definition used to construct the equivalence `lift` below. -/
def liftAux (f : X → CommutatorRing L) :=
  lib.lift R f


theorem liftAux_map_smul (f : X → L) (t : R) (a : lib R X) :
    liftAux R f (t • a) = t • liftAux R f a :=
  NonUnitalAlgHom.map_smul _ t a


theorem liftAux_map_add (f : X → L) (a b : lib R X) :
    liftAux R f (a + b) = liftAux R f a + liftAux R f b :=
  NonUnitalAlgHom.map_add _ a b


theorem liftAux_map_mul (f : X → L) (a b : lib R X) :
    liftAux R f (a * b) = ⁅liftAux R f a, liftAux R f b⁆ :=
  NonUnitalAlgHom.map_mul _ a b


theorem liftAux_spec (f : X → L) (a b : lib R X) (h : FreeLieAlgebra.Rel R X a b) :
    liftAux R f a = liftAux R f b := by
  induction h with
  | lie_self a' => simp only [liftAux_map_mul, NonUnitalAlgHom.map_zero, lie_self]
  | leibniz_lie a' b' c' =>
    simp only [liftAux_map_mul, liftAux_map_add, sub_add_cancel, lie_lie]
  | smul b' _ h₂ => simp only [liftAux_map_smul, h₂]
  | add_right c' _ h₂ => simp only [liftAux_map_add, h₂]
  | mul_left c' _ h₂ => simp only [liftAux_map_mul, h₂]
  | mul_right c' _ h₂ => simp only [liftAux_map_mul, h₂]


/-- The quotient map as a `NonUnitalAlgHom`. -/
def mk : lib R X →ₙₐ[R] CommutatorRing (FreeLieAlgebra R X) where
  toFun := Quot.mk (Rel R X)
  map_smul' _ _ := rfl
  map_zero' := rfl
  map_add' _ _ := rfl
  map_mul' _ _ := rfl


/-- The functor `X ↦ FreeLieAlgebra R X` from the category of types to the category of Lie
algebras over `R` is adjoint to the forgetful functor in the other direction. -/
def lift : (X → L) ≃ (FreeLieAlgebra R X →ₗ⁅R⁆ L) where
  toFun f :=
    { toFun := fun c => Quot.liftOn c (liftAux R f) (liftAux_spec R f)
                     /-
                       R : Type u
                       X : Type v
                       inst✝² : CommRing R
                       L : Type w
                       inst✝¹ : LieRing L
                       inst✝ : LieAlgebra R L
                       f : X → L
                       ⊢ ∀ (x y : FreeLieAlgebra R X), Eq ((fun c => Quot.liftOn c ⇑(FreeLieAlgebra.l …
                     -/
      map_add' := by rintro ⟨a⟩ ⟨b⟩; rw [← liftAux_map_add]; rfl
                                                             /-
                                                               🎉 no goals
                                                             -/
                      /-
                        R : Type u
                        X : Type v
                        inst✝² : CommRing R
                        L : Type w
                        inst✝¹ : LieRing L
                        inst✝ : LieAlgebra R L
                        f : X → L
                        ⊢ ∀ (m : R) (x : FreeLieAlgebra R X), Eq ({ toFun := fun c => Quot.liftOn c ⇑( …
                      -/
      map_smul' := by rintro t ⟨a⟩; rw [← liftAux_map_smul]; rfl
                                                             /-
                                                               🎉 no goals
                                                             -/
                     /-
                       R : Type u
                       X : Type v
                       inst✝² : CommRing R
                       L : Type w
                       inst✝¹ : LieRing L
                       inst✝ : LieAlgebra R L
                       f : X → L
                       ⊢ ∀ {x y : FreeLieAlgebra R X}, Eq ({ toFun := fun c => Quot.liftOn c ⇑(FreeLi …
                     -/
      map_lie' := by rintro ⟨a⟩ ⟨b⟩; rw [← liftAux_map_mul]; rfl }
                                                             /-
                                                               🎉 no goals
                                                             -/
  invFun F := F ∘ of R
  left_inv f := by
    /-
      R : Type u
      X : Type v
      inst✝² : CommRing R
      L : Type w
      inst✝¹ : LieRing L
      inst✝ : LieAlgebra R L
      f : X → L
      ⊢ Eq ((fun F => Function.comp (⇑F) (FreeLieAlgebra.of R)) ((fun f => { toFun : …
    -/
    ext x
    /-
      case h
      R : Type u
      X : Type v
      inst✝² : CommRing R
      L : Type w
      inst✝¹ : LieRing L
      inst✝ : LieAlgebra R L
      f : X → L
      x : X
      ⊢ Eq ((fun F => Function.comp (⇑F) (FreeLieAlgebra.of R)) ((fun f => { toFun : …
    -/
    simp only [liftAux, of, Quot.liftOn_mk, LieHom.coe_mk, Function.comp_apply, lib.lift_of_apply]
    /-
      🎉 no goals
    -/
  right_inv F := by
    /-
      R : Type u
      X : Type v
      inst✝² : CommRing R
      L : Type w
      inst✝¹ : LieRing L
      inst✝ : LieAlgebra R L
      F : LieHom R (FreeLieAlgebra R X) L
      ⊢ Eq ((fun f => { toFun := fun c => Quot.liftOn c ⇑(FreeLieAlgebra.liftAux R f …
    -/
    ext ⟨a⟩
    /-
      case h.mk
      R : Type u
      X : Type v
      inst✝² : CommRing R
      L : Type w
      inst✝¹ : LieRing L
      inst✝ : LieAlgebra R L
      F : LieHom R (FreeLieAlgebra R X) L
      x✝ : FreeLieAlgebra R X
      a : FreeNonUnitalNonAssocAlgebra R X
      ⊢ Eq (((fun f => { toFun := fun c => Quot.liftOn c ⇑(FreeLieAlgebra.liftAux R  …
    -/
    let F' := F.toNonUnitalAlgHom.comp (mk R)
    /-
      case h.mk
      R : Type u
      X : Type v
      inst✝² : CommRing R
      L : Type w
      inst✝¹ : LieRing L
      inst✝ : LieAlgebra R L
      F : LieHom R (FreeLieAlgebra R X) L
      x✝ : FreeLieAlgebra R X
      a : FreeNonUnitalNonAssocAlgebra R X
      F' : NonUnitalAlgHom (MonoidHom.id R) (FreeNonUnitalNonAssocAlgebra R X) (Comm …
      ⊢ Eq (((fun f => { toFun := fun c => Quot.liftOn c ⇑(FreeLieAlgebra.liftAux R  …
    -/
    exact NonUnitalAlgHom.congr_fun (lib.lift_comp_of R F') a
    /-
      🎉 no goals
    -/


@[simp]
theorem lift_symm_apply (F : FreeLieAlgebra R X →ₗ⁅R⁆ L) : (lift R).symm F = F ∘ of R := rfl


@[simp]
theorem of_comp_lift (f : X → L) : lift R f ∘ of R = f := (lift R).left_inv f


@[simp]
theorem lift_unique (f : X → L) (g : FreeLieAlgebra R X →ₗ⁅R⁆ L) : g ∘ of R = f ↔ g = lift R f :=
  (lift R).symm_apply_eq


@[simp]
theorem lift_of_apply (f : X → L) (x) : lift R f (of R x) = f x := by
  /-
    R : Type u
    X : Type v
    inst✝² : CommRing R
    L : Type w
    inst✝¹ : LieRing L
    inst✝ : LieAlgebra R L
    f : X → L
    x : X
    ⊢ Eq (((FreeLieAlgebra.lift R) f) (FreeLieAlgebra.of R x)) (f x)
  -/
  rw [← @Function.comp_apply _ _ _ (lift R f) (of R) x, of_comp_lift]
  /-
    🎉 no goals
  -/


@[simp]
theorem lift_comp_of (F : FreeLieAlgebra R X →ₗ⁅R⁆ L) : lift R (F ∘ of R) = F := by
  /-
    R : Type u
    X : Type v
    inst✝² : CommRing R
    L : Type w
    inst✝¹ : LieRing L
    inst✝ : LieAlgebra R L
    F : LieHom R (FreeLieAlgebra R X) L
    ⊢ Eq ((FreeLieAlgebra.lift R) (Function.comp (⇑F) (FreeLieAlgebra.of R))) F
  -/
  rw [← lift_symm_apply]; exact (lift R).apply_symm_apply F
                          /-
                            🎉 no goals
                          -/


@[ext]
theorem hom_ext {F₁ F₂ : FreeLieAlgebra R X →ₗ⁅R⁆ L} (h : ∀ x, F₁ (of R x) = F₂ (of R x)) :
    F₁ = F₂ :=
                                                      /-
                                                        R : Type u
                                                        X : Type v
                                                        inst✝² : CommRing R
                                                        L : Type w
                                                        inst✝¹ : LieRing L
                                                        inst✝ : LieAlgebra R L
                                                        F₁ F₂ : LieHom R (FreeLieAlgebra R X) L
                                                        h : ∀ (x : X), Eq (F₁ (FreeLieAlgebra.of R x)) (F₂ (FreeLieAlgebra.of R x))
                                                        ⊢ Eq ((FreeLieAlgebra.lift R).symm F₁) ((FreeLieAlgebra.lift R).symm F₂)
                                                      -/
  have h' : (lift R).symm F₁ = (lift R).symm F₂ := by ext; simp [h]
                                                           /-
                                                             🎉 no goals
                                                           -/
  (lift R).symm.injective h'


/-- The universal enveloping algebra of the free Lie algebra is just the free unital associative
algebra. -/
@[simps!]
def universalEnvelopingEquivFreeAlgebra :
    UniversalEnvelopingAlgebra R (FreeLieAlgebra R X) ≃ₐ[R] FreeAlgebra R X :=
  AlgEquiv.ofAlgHom (UniversalEnvelopingAlgebra.lift R <| FreeLieAlgebra.lift R <| FreeAlgebra.ι R)
                                                                                     /-
                                                                                       R : Type u
                                                                                       X : Type v
                                                                                       inst✝² : CommRing R
                                                                                       L : Type w
                                                                                       inst✝¹ : LieRing L
                                                                                       inst✝ : LieAlgebra R L
                                                                                       ⊢ Eq (((UniversalEnvelopingAlgebra.lift R) ((FreeLieAlgebra.lift R) (FreeAlgeb …
                                                                                     -/
    (FreeAlgebra.lift R <| UniversalEnvelopingAlgebra.ι R ∘ FreeLieAlgebra.of R) (by ext; simp)
                                                                                          /-
                                                                                            🎉 no goals
                                                                                          -/
        /-
          R : Type u
          X : Type v
          inst✝² : CommRing R
          L : Type w
          inst✝¹ : LieRing L
          inst✝ : LieAlgebra R L
          ⊢ Eq (((FreeAlgebra.lift R) (Function.comp (⇑(UniversalEnvelopingAlgebra.ι R)) …
        -/
    (by ext; simp)
             /-
               🎉 no goals
             -/


