/-- If all prime ideals in a commutative ring are principal, so are all other ideals. -/
theorem IsPrincipalIdealRing.of_prime (H : ∀ P : Ideal R, P.IsPrime → P.IsPrincipal) :
    IsPrincipalIdealRing R := by
  -- Suppose the set of `nonPrincipals` is not empty.
  /-
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    ⊢ IsPrincipalIdealRing R
  -/
  rw [← nonPrincipals_eq_empty_iff, Set.eq_empty_iff_forall_not_mem]
  /-
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    ⊢ ∀ (x : Ideal R), Not (Membership.mem (nonPrincipals R) x)
  -/
  intro J hJ
  -- We will show a maximal element `I ∈ nonPrincipals R` (which exists by Zorn) is prime.
  /-
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    J : Ideal R
    hJ : Membership.mem (nonPrincipals R) J
    ⊢ False
  -/
  obtain ⟨I, hJI, hI⟩ := zorn_le_nonempty₀ (nonPrincipals R) nonPrincipals_zorn _ hJ

  have Imax' : ∀ {J}, I < J → J.IsPrincipal := by
    intro K hK
    simpa [nonPrincipals] using hI.not_prop_of_gt hK

  /-
    case intro.intro
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    J : Ideal R
    hJ : Membership.mem (nonPrincipals R) J
    I : Ideal R
    hJI : LE.le J I
    hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
    Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
    ⊢ False
  -/
  by_cases hI1 : I = ⊤
    /-
      case pos
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Eq I Top.top
      ⊢ False
    -/
  · subst hI1
    /-
      case pos
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      hJI : LE.le J Top.top
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) Top.top
      Imax' : ∀ {J : Ideal R}, LT.lt Top.top J → Submodule.IsPrincipal J
      ⊢ False
    -/
    exact hI.prop top_isPrincipal
    /-
      🎉 no goals
    -/
  -- Let `x y : R` with `x * y ∈ I` and suppose WLOG `y ∉ I`.
  /-
    case neg
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    J : Ideal R
    hJ : Membership.mem (nonPrincipals R) J
    I : Ideal R
    hJI : LE.le J I
    hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
    Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
    hI1 : Not (Eq I Top.top)
    ⊢ False
  -/
  refine hI.prop (H I ⟨hI1, fun {x y} hxy => or_iff_not_imp_right.mpr fun hy => ?_⟩)
  obtain ⟨a, ha⟩ : (I ⊔ span {y}).IsPrincipal :=
    Imax' (left_lt_sup.mpr (mt I.span_singleton_le_iff_mem.mp hy))
  -- Then `x ∈ I.colon (span {y})`, which is equal to `I` if it's not principal.
  suffices He : ¬(I.colon (span {y})).IsPrincipal by
    rw [hI.eq_of_le ((nonPrincipals_def R).2 He) fun a ha ↦
      Ideal.mem_colon_singleton.2 (mul_mem_right _ _ ha)]
    exact Ideal.mem_colon_singleton.2 hxy
  -- So suppose for the sake of contradiction that both `I ⊔ span {y}` and `I.colon (span {y})`
  -- are principal.
  /-
    case neg.mk.intro
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    J : Ideal R
    hJ : Membership.mem (nonPrincipals R) J
    I : Ideal R
    hJI : LE.le J I
    hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
    Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
    hI1 : Not (Eq I Top.top)
    x y : R
    hxy : Membership.mem I (HMul.hMul x y)
    hy : Not (Membership.mem I y)
    a : R
    ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
    ⊢ Not (Submodule.IsPrincipal (Submodule.colon I (Ideal.span (Singleton.singlet …
  -/
  rintro ⟨b, hb⟩
  -- We will show `I` is generated by `a * b`.
  /-
    case neg.mk.intro.mk.intro
    R : Type u_1
    inst✝ : CommRing R
    H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
    J : Ideal R
    hJ : Membership.mem (nonPrincipals R) J
    I : Ideal R
    hJI : LE.le J I
    hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
    Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
    hI1 : Not (Eq I Top.top)
    x y : R
    hxy : Membership.mem I (HMul.hMul x y)
    hy : Not (Membership.mem I y)
    a : R
    ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
    b : R
    hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
    ⊢ False
  -/
  refine (nonPrincipals_def _).1 hI.prop ⟨a * b, ?_⟩
  refine
    le_antisymm (α := Ideal R) (fun i hi => ?_) <|
      (span_singleton_mul_span_singleton a b).ge.trans ?_
    /-
      case neg.mk.intro.mk.intro.refine_1
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x y : R
      hxy : Membership.mem I (HMul.hMul x y)
      hy : Not (Membership.mem I y)
      a : R
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
      b : R
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
      i : R
      hi : Membership.mem I i
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) i
    -/
  · have hisup : i ∈ I ⊔ span {y} := Ideal.mem_sup_left hi
    /-
      case neg.mk.intro.mk.intro.refine_1
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x y : R
      hxy : Membership.mem I (HMul.hMul x y)
      hy : Not (Membership.mem I y)
      a : R
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
      b : R
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
      i : R
      hi : Membership.mem I i
      hisup : Membership.mem (Max.max I (Ideal.span (Singleton.singleton y))) i
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) i
    -/
    have : y ∈ I ⊔ span {y} := Ideal.mem_sup_right (Ideal.mem_span_singleton_self y)
    /-
      case neg.mk.intro.mk.intro.refine_1
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x y : R
      hxy : Membership.mem I (HMul.hMul x y)
      hy : Not (Membership.mem I y)
      a : R
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
      b : R
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
      i : R
      hi : Membership.mem I i
      hisup : Membership.mem (Max.max I (Ideal.span (Singleton.singleton y))) i
      this : Membership.mem (Max.max I (Ideal.span (Singleton.singleton y))) y
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) i
    -/
    erw [ha, mem_span_singleton'] at hisup this
    /-
      case neg.mk.intro.mk.intro.refine_1
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x y : R
      hxy : Membership.mem I (HMul.hMul x y)
      hy : Not (Membership.mem I y)
      a : R
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
      b : R
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
      i : R
      hi : Membership.mem I i
      hisup : Exists fun a_1 => Eq (HMul.hMul a_1 a) i
      this : Exists fun a_1 => Eq (HMul.hMul a_1 a) y
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) i
    -/
    obtain ⟨v, rfl⟩ := this
    /-
      case neg.mk.intro.mk.intro.refine_1.intro
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x a b i : R
      hi : Membership.mem I i
      hisup : Exists fun a_1 => Eq (HMul.hMul a_1 a) i
      v : R
      hxy : Membership.mem I (HMul.hMul x (HMul.hMul v a))
      hy : Not (Membership.mem I (HMul.hMul v a))
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) (Submod …
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) …
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) i
    -/
    obtain ⟨u, rfl⟩ := hisup
    have hucolon : u ∈ I.colon (span {v * a}) := by
      rw [Ideal.mem_colon_singleton, mul_comm v, ← mul_assoc]
      exact mul_mem_right _ _ hi
    /-
      case neg.mk.intro.mk.intro.refine_1.intro.intro
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x a b v : R
      hxy : Membership.mem I (HMul.hMul x (HMul.hMul v a))
      hy : Not (Membership.mem I (HMul.hMul v a))
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) (Submod …
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) …
      u : R
      hi : Membership.mem I (HMul.hMul u a)
      hucolon : Membership.mem (Submodule.colon I (Ideal.span (Singleton.singleton ( …
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) (HMu …
    -/
    erw [hb, mem_span_singleton'] at hucolon
    /-
      case neg.mk.intro.mk.intro.refine_1.intro.intro
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x a b v : R
      hxy : Membership.mem I (HMul.hMul x (HMul.hMul v a))
      hy : Not (Membership.mem I (HMul.hMul v a))
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) (Submod …
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) …
      u : R
      hi : Membership.mem I (HMul.hMul u a)
      hucolon : Exists fun a => Eq (HMul.hMul a b) u
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) (HMu …
    -/
    obtain ⟨z, rfl⟩ := hucolon
    /-
      case neg.mk.intro.mk.intro.refine_1.intro.intro.intro
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x a b v : R
      hxy : Membership.mem I (HMul.hMul x (HMul.hMul v a))
      hy : Not (Membership.mem I (HMul.hMul v a))
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) (Submod …
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton (HMul.hMul v a)))) …
      z : R
      hi : Membership.mem I (HMul.hMul (HMul.hMul z b) a)
      ⊢ Membership.mem (Submodule.span R (Singleton.singleton (HMul.hMul a b))) (HMu …
    -/
    exact mem_span_singleton'.2 ⟨z, by ring⟩
    /-
      🎉 no goals
    -/
  · rw [← Ideal.submodule_span_eq, ← ha, Ideal.sup_mul, sup_le_iff,
      span_singleton_mul_span_singleton, mul_comm y, Ideal.span_singleton_le_iff_mem]
    /-
      case neg.mk.intro.mk.intro.refine_2
      R : Type u_1
      inst✝ : CommRing R
      H : ∀ (P : Ideal R), P.IsPrime → Submodule.IsPrincipal P
      J : Ideal R
      hJ : Membership.mem (nonPrincipals R) J
      I : Ideal R
      hJI : LE.le J I
      hI : Maximal (fun x => Membership.mem (nonPrincipals R) x) I
      Imax' : ∀ {J : Ideal R}, LT.lt I J → Submodule.IsPrincipal J
      hI1 : Not (Eq I Top.top)
      x y : R
      hxy : Membership.mem I (HMul.hMul x y)
      hy : Not (Membership.mem I y)
      a : R
      ha : Eq (Max.max I (Ideal.span (Singleton.singleton y))) (Submodule.span R (Si …
      b : R
      hb : Eq (Submodule.colon I (Ideal.span (Singleton.singleton y))) (Submodule.sp …
      ⊢ And (LE.le (HMul.hMul I (Ideal.span (Singleton.singleton b))) I) (Membership …
    -/
    exact ⟨mul_le_right, Ideal.mem_colon_singleton.1 <| hb.symm ▸ Ideal.mem_span_singleton_self b⟩
    /-
      🎉 no goals
    -/

