/-- A sieve is effective epimorphic if the associated cocone is a colimit cocone. -/
def Sieve.EffectiveEpimorphic {X : C} (S : Sieve X) : Prop :=
  Nonempty (IsColimit (S : Presieve X).cocone)


/-- A presieve is effective epimorphic if the cocone associated to the sieve it generates
is a colimit cocone. -/
abbrev Presieve.EffectiveEpimorphic {X : C} (S : Presieve X) : Prop :=
  (Sieve.generate S).EffectiveEpimorphic


/--
The sieve of morphisms which factor through a given morphism `f`.
This is equal to `Sieve.generate (Presieve.singleton f)`, but has
more convenient definitional properties.
-/
def Sieve.generateSingleton {X Y : C} (f : Y ⟶ X) : Sieve X where
  arrows Z := { g | ∃ (e : Z ⟶ Y), e ≫ f = g }
  downward_closed := by
    /-
      C : Type u_1
      inst✝ : CategoryTheory.Category.{?u.888, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      ⊢ ∀ {Y_1 Z : C} {f_1 : Quiver.Hom Y_1 X}, (fun Z => setOf fun g => Exists fun  …
    -/
    rintro W Z g ⟨e,rfl⟩ q
    /-
      case intro
      C : Type u_1
      inst✝ : CategoryTheory.Category.{?u.888, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      W Z : C
      e : Quiver.Hom W Y
      q : Quiver.Hom Z W
      ⊢ setOf (fun g => Exists fun e => Eq (CategoryTheory.CategoryStruct.comp e f)  …
    -/
    exact ⟨q ≫ e, by simp⟩
    /-
      🎉 no goals
    -/


lemma Sieve.generateSingleton_eq {X Y : C} (f : Y ⟶ X) :
    Sieve.generate (Presieve.singleton f) = Sieve.generateSingleton f := by
  /-
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_2, u_1} C
    X Y : C
    f : Quiver.Hom Y X
    ⊢ Eq (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.singleton f)) (Ca …
  -/
  ext Z g
  /-
    case h
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_2, u_1} C
    X Y : C
    f : Quiver.Hom Y X
    Z : C
    g : Quiver.Hom Z X
    ⊢ Iff ((CategoryTheory.Sieve.generate (CategoryTheory.Presieve.singleton f)).a …
  -/
  constructor
    /-
      case h.mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      Z : C
      g : Quiver.Hom Z X
      ⊢ (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.singleton f)).arrows …
    -/
  · rintro ⟨W,i,p,⟨⟩,rfl⟩
    /-
      case h.mp.intro.intro.intro.intro.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y✝ : C
      f : Quiver.Hom Y✝ X
      Z Y : C
      i : Quiver.Hom Z Y✝
      ⊢ (CategoryTheory.Sieve.generateSingleton f).arrows (CategoryTheory.CategorySt …
    -/
    exact ⟨i,rfl⟩
    /-
      🎉 no goals
    -/
    /-
      case h.mpr
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      Z : C
      g : Quiver.Hom Z X
      ⊢ (CategoryTheory.Sieve.generateSingleton f).arrows g → (CategoryTheory.Sieve. …
    -/
  · rintro ⟨g,h⟩
    /-
      case h.mpr.intro
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      Z : C
      g✝ : Quiver.Hom Z X
      g : Quiver.Hom Z Y
      h : Eq (CategoryTheory.CategoryStruct.comp g f) g✝
      ⊢ (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.singleton f)).arrows …
    -/
    exact ⟨Y,g,f,⟨⟩,h⟩
    /-
      🎉 no goals
    -/


/--
Implementation: This is a construction which will be used in the proof that
the sieve generated by a single arrow is effective epimorphic if and only if
the arrow is an effective epi.
-/
def isColimitOfEffectiveEpiStruct {X Y : C} (f : Y ⟶ X) (Hf : EffectiveEpiStruct f) :
    IsColimit (Sieve.generateSingleton f : Presieve X).cocone :=
  letI D := FullSubcategory fun T : Over X => Sieve.generateSingleton f T.hom
  letI F : D ⥤ _ := (Sieve.generateSingleton f).arrows.diagram
                                                           /-
                                                             C : Type u_1
                                                             inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
                                                             X Y : C
                                                             f : Quiver.Hom Y X
                                                             Hf : CategoryTheory.EffectiveEpiStruct f
                                                             D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
                                                             F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
                                                             S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
                                                             ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.id ((C …
                                                           -/
  { desc := fun S => Hf.desc (S.ι.app ⟨Over.mk f, ⟨𝟙 _, by simp⟩⟩) <| by
                                                           /-
                                                             🎉 no goals
                                                           -/
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        ⊢ ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp g …
      -/
      intro Z g₁ g₂ h
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let Y' : D := ⟨Over.mk f, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        Y' : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let Z' : D := ⟨Over.mk (g₁ ≫ f), g₁, rfl⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        Y' : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let g₁' : Z' ⟶ Y' := Over.homMk g₁
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        Y' : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        g₁' : Quiver.Hom Z' Y' := CategoryTheory.Over.homMk g₁ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let g₂' : Z' ⟶ Y' := Over.homMk g₂ (by simp [Y', Z', h])
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        Y' : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        g₁' : Quiver.Hom Z' Y' := CategoryTheory.Over.homMk g₁ ⋯
        g₂' : Quiver.Hom Z' Y' := CategoryTheory.Over.homMk g₂ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      change F.map g₁' ≫ _ = F.map g₂' ≫ _
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        Z : C
        g₁ g₂ : Quiver.Hom Z Y
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ f) (CategoryTheory.CategoryStruc …
        Y' : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        g₁' : Quiver.Hom Z' Y' := CategoryTheory.Over.homMk g₁ ⋯
        g₂' : Quiver.Hom Z' Y' := CategoryTheory.Over.homMk g₂ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map g₁') (S.ι.app { obj := Categor …
      -/
      simp only [Y', F, S.w]
      /-
        🎉 no goals
      -/
    fac := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        ⊢ ∀ (s : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton  …
      -/
      rintro S ⟨T,g,hT⟩
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateSingle …
      -/
      dsimp
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp T.hom (Hf.desc (S.ι.app { obj := Cate …
      -/
      nth_rewrite 1 [← hT, Category.assoc, Hf.fac]
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let y : D := ⟨Over.mk f, 𝟙 _, by simp⟩
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        y : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let x : D := ⟨Over.mk T.hom, g, hT⟩
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        y : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        x : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let g' : x ⟶ y := Over.homMk g
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        y : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        x : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        g' : Quiver.Hom x y := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      change F.map g' ≫ _ = _
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        y : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        x : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        g' : Quiver.Hom x y := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map g') (S.ι.app { obj := Category …
      -/
      rw [S.w]
      /-
        case mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        T : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj T.left) Y
        hT : Eq (CategoryTheory.CategoryStruct.comp g f) T.hom
        y : D := { obj := CategoryTheory.Over.mk f, property := ⋯ }
        x : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        g' : Quiver.Hom x y := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (S.ι.app x) (S.ι.app { obj := T, property := ⋯ })
      -/
      rfl
      /-
        🎉 no goals
      -/
    uniq := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        ⊢ ∀ (s : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton  …
      -/
      intro S m hm
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        m : Quiver.Hom (CategoryTheory.Sieve.generateSingleton f).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateSingleton f).arrows.category), Eq (C …
        ⊢ Eq m ((fun S => Hf.desc (S.ι.app { obj := CategoryTheory.Over.mk f, property …
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        m : Quiver.Hom (CategoryTheory.Sieve.generateSingleton f).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateSingleton f).arrows.category), Eq (C …
        ⊢ Eq m (Hf.desc (S.ι.app { obj := CategoryTheory.Over.mk f, property := ⋯ }) ⋯)
      -/
      generalize_proofs h1 h2
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        m : Quiver.Hom (CategoryTheory.Sieve.generateSingleton f).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateSingleton f).arrows.category), Eq (C …
        h1 : (CategoryTheory.Sieve.generateSingleton f).arrows (CategoryTheory.Over.mk …
        h2 : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.com …
        ⊢ Eq m (Hf.desc (S.ι.app { obj := CategoryTheory.Over.mk f, property := h1 })  …
      -/
      apply Hf.uniq _ h2
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.2134, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.EffectiveEpiStruct f
        D : Type (max u_1 ?u.2134) := CategoryTheory.FullSubcategory fun T => (Categor …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateSingleton f).a …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateSingleton f).ar …
        m : Quiver.Hom (CategoryTheory.Sieve.generateSingleton f).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateSingleton f).arrows.category), Eq (C …
        h1 : (CategoryTheory.Sieve.generateSingleton f).arrows (CategoryTheory.Over.mk …
        h2 : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.com …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp f m) (S.ι.app { obj := CategoryTheory …
      -/
      exact hm ⟨Over.mk f, 𝟙 _, by simp⟩ }
      /-
        🎉 no goals
      -/


/--
Implementation: This is a construction which will be used in the proof that
the sieve generated by a single arrow is effective epimorphic if and only if
the arrow is an effective epi.
-/
noncomputable
def effectiveEpiStructOfIsColimit {X Y : C} (f : Y ⟶ X)
    (Hf : IsColimit (Sieve.generateSingleton f : Presieve X).cocone) :
    EffectiveEpiStruct f :=
  let aux {W : C} (e : Y ⟶ W)
    (h : ∀ {Z : C} (g₁ g₂ : Z ⟶ Y), g₁ ≫ f = g₂ ≫ f → g₁ ≫ e = g₂ ≫ e) :
    Cocone (Sieve.generateSingleton f).arrows.diagram :=
    { pt := W
      ι := {
        app := fun ⟨_,hT⟩ => hT.choose ≫ e
        naturality := by
          /-
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
            X Y : C
            f : Quiver.Hom Y X
            Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
            W : C
            e : Quiver.Hom Y W
            h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
            ⊢ ∀ ⦃X_1 Y_1 : (CategoryTheory.Sieve.generateSingleton f).arrows.category⦄ (f_ …
          -/
          rintro ⟨A,hA⟩ ⟨B,hB⟩ (q : A ⟶ B)
          /-
            case mk.mk
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
            X Y : C
            f : Quiver.Hom Y X
            Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
            W : C
            e : Quiver.Hom Y W
            h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
            A : CategoryTheory.Over X
            hA : (CategoryTheory.Sieve.generateSingleton f).arrows A.hom
            B : CategoryTheory.Over X
            hB : (CategoryTheory.Sieve.generateSingleton f).arrows B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateSingle …
          -/
          dsimp; simp only [← Category.assoc, Category.comp_id]
          /-
            case mk.mk
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
            X Y : C
            f : Quiver.Hom Y X
            Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
            W : C
            e : Quiver.Hom Y W
            h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
            A : CategoryTheory.Over X
            hA : (CategoryTheory.Sieve.generateSingleton f).arrows A.hom
            B : CategoryTheory.Over X
            hB : (CategoryTheory.Sieve.generateSingleton f).arrows B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp q …
          -/
          apply h
          /-
            case mk.mk.a
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
            X Y : C
            f : Quiver.Hom Y X
            Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
            W : C
            e : Quiver.Hom Y W
            h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
            A : CategoryTheory.Over X
            hA : (CategoryTheory.Sieve.generateSingleton f).arrows A.hom
            B : CategoryTheory.Over X
            hB : (CategoryTheory.Sieve.generateSingleton f).arrows B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp q …
          -/
          rw [Category.assoc, hB.choose_spec, hA.choose_spec, Over.w] } }
          /-
            🎉 no goals
          -/
  { desc := fun {_} e h => Hf.desc (aux e h)
    fac := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        ⊢ ∀ {W : C} (e : Quiver.Hom Y W) (h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq ( …
      -/
      intro W e h
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp f ((fun {x} e h => Hf.desc (aux e ⋯)) …
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp f (Hf.desc (aux e ⋯))) e
      -/
      have := Hf.fac (aux e h) ⟨Over.mk f, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        this : Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateS …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp f (Hf.desc (aux e ⋯))) e
      -/
      dsimp [aux] at this; rw [this]; clear this
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (Exists.choose ⋯) e) e
      -/
      nth_rewrite 2 [← Category.id_comp e]
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (Exists.choose ⋯) e) (CategoryTheory. …
      -/
      apply h
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (Exists.choose ⋯) f) (CategoryTheory. …
      -/
      generalize_proofs hh
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        hh : Exists fun e => Eq (CategoryTheory.CategoryStruct.comp e f) f
        ⊢ Eq (CategoryTheory.CategoryStruct.comp hh.choose f) (CategoryTheory.Category …
      -/
      rw [hh.choose_spec, Category.id_comp]
      /-
        🎉 no goals
      -/
    uniq := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        ⊢ ∀ {W : C} (e : Quiver.Hom Y W) (h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq ( …
      -/
      intro W e h m hm
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        ⊢ Eq m ((fun {x} e h => Hf.desc (aux e ⋯)) e ⋯)
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        ⊢ Eq m (Hf.desc (aux e ⋯))
      -/
      apply Hf.uniq (aux e h)
      /-
        case x
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        ⊢ ∀ (j : (CategoryTheory.Sieve.generateSingleton f).arrows.category), Eq (Cate …
      -/
      rintro ⟨A,g,hA⟩
      /-
        case x.mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        A : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj A.left) Y
        hA : Eq (CategoryTheory.CategoryStruct.comp g f) A.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateSingle …
      -/
      dsimp
      /-
        case x.mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        A : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj A.left) Y
        hA : Eq (CategoryTheory.CategoryStruct.comp g f) A.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp A.hom m) (CategoryTheory.CategoryStru …
      -/
      nth_rewrite 1 [← hA, Category.assoc, hm]
      /-
        case x.mk.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        A : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj A.left) Y
        hA : Eq (CategoryTheory.CategoryStruct.comp g f) A.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g e) (CategoryTheory.CategoryStruct.c …
      -/
      apply h
      /-
        case x.mk.intro.a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        A : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj A.left) Y
        hA : Eq (CategoryTheory.CategoryStruct.comp g f) A.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g f) (CategoryTheory.CategoryStruct.c …
      -/
      generalize_proofs hh
      /-
        case x.mk.intro.a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.15305, u_1} C
        X Y : C
        f : Quiver.Hom Y X
        Hf : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSingleton f …
        aux : {W : C} → (e : Quiver.Hom Y W) → (∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq …
        W : C
        e : Quiver.Hom Y W
        h : ∀ {Z : C} (g₁ g₂ : Quiver.Hom Z Y), Eq (CategoryTheory.CategoryStruct.comp …
        m : Quiver.Hom X W
        hm : Eq (CategoryTheory.CategoryStruct.comp f m) e
        A : CategoryTheory.Over X
        g : Quiver.Hom ((CategoryTheory.Functor.id C).obj A.left) Y
        hA : Eq (CategoryTheory.CategoryStruct.comp g f) A.hom
        hh : Exists fun e => Eq (CategoryTheory.CategoryStruct.comp e f) A.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g f) (CategoryTheory.CategoryStruct.c …
      -/
      rwa [hh.choose_spec] }
      /-
        🎉 no goals
      -/


theorem Sieve.effectiveEpimorphic_singleton {X Y : C} (f : Y ⟶ X) :
    (Presieve.singleton f).EffectiveEpimorphic ↔ (EffectiveEpi f) := by
  /-
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_2, u_1} C
    X Y : C
    f : Quiver.Hom Y X
    ⊢ Iff (CategoryTheory.Presieve.singleton f).EffectiveEpimorphic (CategoryTheor …
  -/
  constructor
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      ⊢ (CategoryTheory.Presieve.singleton f).EffectiveEpimorphic → CategoryTheory.E …
    -/
  · intro (h : Nonempty _)
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generate ( …
      ⊢ CategoryTheory.EffectiveEpi f
    -/
    rw [Sieve.generateSingleton_eq] at h
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSi …
      ⊢ CategoryTheory.EffectiveEpi f
    -/
    constructor
    /-
      case mp.effectiveEpi
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSi …
      ⊢ Nonempty (CategoryTheory.EffectiveEpiStruct f)
    -/
    apply Nonempty.map (effectiveEpiStructOfIsColimit _) h
    /-
      🎉 no goals
    -/
    /-
      case mpr
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      ⊢ CategoryTheory.EffectiveEpi f → (CategoryTheory.Presieve.singleton f).Effect …
    -/
  · rintro ⟨h⟩
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.EffectiveEpiStruct f)
      ⊢ (CategoryTheory.Presieve.singleton f).EffectiveEpimorphic
    -/
    show Nonempty _
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.EffectiveEpiStruct f)
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generate (Ca …
    -/
    rw [Sieve.generateSingleton_eq]
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_2, u_1} C
      X Y : C
      f : Quiver.Hom Y X
      h : Nonempty (CategoryTheory.EffectiveEpiStruct f)
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateSing …
    -/
    apply Nonempty.map (isColimitOfEffectiveEpiStruct _) h
    /-
      🎉 no goals
    -/


/--
The sieve of morphisms which factor through a morphism in a given family.
This is equal to `Sieve.generate (Presieve.ofArrows X π)`, but has
more convenient definitional properties.
-/
def Sieve.generateFamily {B : C} {α : Type*} (X : α → C) (π : (a : α) → (X a ⟶ B)) :
    Sieve B where
  arrows Y := { f | ∃ (a : α) (g : Y ⟶ X a), g ≫ π a = f }
  downward_closed := by
    /-
      C : Type u_1
      inst✝ : CategoryTheory.Category.{?u.28387, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      ⊢ ∀ {Y Z : C} {f : Quiver.Hom Y B}, (fun Y => setOf fun f => Exists fun a => E …
    -/
    rintro Y₁ Y₂ g₁ ⟨a,q,rfl⟩ e
    /-
      case intro.intro
      C : Type u_1
      inst✝ : CategoryTheory.Category.{?u.28387, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      Y₁ Y₂ : C
      a : α
      q : Quiver.Hom Y₁ (X a)
      e : Quiver.Hom Y₂ Y₁
      ⊢ setOf (fun f => Exists fun a => Exists fun g => Eq (CategoryTheory.CategoryS …
    -/
    exact ⟨a, e ≫ q, by simp⟩
    /-
      🎉 no goals
    -/


lemma Sieve.generateFamily_eq {B : C} {α : Type*} (X : α → C) (π : (a : α) → (X a ⟶ B)) :
    Sieve.generate (Presieve.ofArrows X π) = Sieve.generateFamily X π := by
  /-
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_3, u_1} C
    B : C
    α : Type u_2
    X : α → C
    π : (a : α) → Quiver.Hom (X a) B
    ⊢ Eq (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.ofArrows X π)) (C …
  -/
  ext Y g
  /-
    case h
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_3, u_1} C
    B : C
    α : Type u_2
    X : α → C
    π : (a : α) → Quiver.Hom (X a) B
    Y : C
    g : Quiver.Hom Y B
    ⊢ Iff ((CategoryTheory.Sieve.generate (CategoryTheory.Presieve.ofArrows X π)). …
  -/
  constructor
    /-
      case h.mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      Y : C
      g : Quiver.Hom Y B
      ⊢ (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.ofArrows X π)).arrow …
    -/
  · rintro ⟨W, g, f, ⟨a⟩, rfl⟩
    /-
      case h.mp.intro.intro.intro.intro.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      Y✝ Y : C
      a : α
      g : Quiver.Hom Y✝ (X a)
      ⊢ (CategoryTheory.Sieve.generateFamily X π).arrows (CategoryTheory.CategoryStr …
    -/
    exact ⟨a, g, rfl⟩
    /-
      🎉 no goals
    -/
    /-
      case h.mpr
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      Y : C
      g : Quiver.Hom Y B
      ⊢ (CategoryTheory.Sieve.generateFamily X π).arrows g → (CategoryTheory.Sieve.g …
    -/
  · rintro ⟨a, g, rfl⟩
    /-
      case h.mpr.intro.intro
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      Y : C
      a : α
      g : Quiver.Hom Y (X a)
      ⊢ (CategoryTheory.Sieve.generate (CategoryTheory.Presieve.ofArrows X π)).arrow …
    -/
    exact ⟨_, g, π a, ⟨a⟩, rfl⟩
    /-
      🎉 no goals
    -/


/--
Implementation: This is a construction which will be used in the proof that
the sieve generated by a family of arrows is effective epimorphic if and only if
the family is an effective epi.
-/
def isColimitOfEffectiveEpiFamilyStruct {B : C} {α : Type*}
    (X : α → C) (π : (a : α) → (X a ⟶ B)) (H : EffectiveEpiFamilyStruct X π) :
    IsColimit (Sieve.generateFamily X π : Presieve B).cocone :=
  letI D := FullSubcategory fun T : Over B => Sieve.generateFamily X π T.hom
  letI F : D ⥤ _ := (Sieve.generateFamily X π).arrows.diagram
                                                                         /-
                                                                           C : Type u_1
                                                                           inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
                                                                           B : C
                                                                           α : Type u_2
                                                                           X : α → C
                                                                           π : (a : α) → Quiver.Hom (X a) B
                                                                           H : CategoryTheory.EffectiveEpiFamilyStruct X π
                                                                           D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
                                                                           F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
                                                                           S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
                                                                           a : α
                                                                           ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.id ((C …
                                                                         -/
  { desc := fun S => H.desc (fun a => S.ι.app ⟨Over.mk (π a), ⟨a,𝟙 _, by simp⟩⟩) <| by
                                                                         /-
                                                                           🎉 no goals
                                                                         -/
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        ⊢ ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂)), …
      -/
      intro Z a₁ a₂ g₁ g₂ h
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ ((fun a => S.ι.app { obj := Catego …
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let A₁ : D := ⟨Over.mk (π a₁), a₁, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let A₂ : D := ⟨Over.mk (π a₂), a₂, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        A₂ : D := { obj := CategoryTheory.Over.mk (π a₂), property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let Z' : D := ⟨Over.mk (g₁ ≫ π a₁), a₁, g₁, rfl⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        A₂ : D := { obj := CategoryTheory.Over.mk (π a₂), property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let i₁ : Z' ⟶ A₁ := Over.homMk g₁
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        A₂ : D := { obj := CategoryTheory.Over.mk (π a₂), property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        i₁ : Quiver.Hom Z' A₁ := CategoryTheory.Over.homMk g₁ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      let i₂ : Z' ⟶ A₂ := Over.homMk g₂
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        A₂ : D := { obj := CategoryTheory.Over.mk (π a₂), property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        i₁ : Quiver.Hom Z' A₁ := CategoryTheory.Over.homMk g₁ ⋯
        i₂ : Quiver.Hom Z' A₂ := CategoryTheory.Over.homMk g₂ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.ι.app { obj := CategoryTheory.O …
      -/
      change F.map i₁ ≫ _ = F.map i₂ ≫ _
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        Z : C
        a₁ a₂ : α
        g₁ : Quiver.Hom Z (X a₁)
        g₂ : Quiver.Hom Z (X a₂)
        h : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a₁)) (CategoryTheory.Category …
        A₁ : D := { obj := CategoryTheory.Over.mk (π a₁), property := ⋯ }
        A₂ : D := { obj := CategoryTheory.Over.mk (π a₂), property := ⋯ }
        Z' : D := { obj := CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp  …
        i₁ : Quiver.Hom Z' A₁ := CategoryTheory.Over.homMk g₁ ⋯
        i₂ : Quiver.Hom Z' A₂ := CategoryTheory.Over.homMk g₂ ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map i₁) (S.ι.app { obj := Category …
      -/
      simp only [F, A₁, A₂, S.w]
      /-
        🎉 no goals
      -/
    fac := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        ⊢ ∀ (s : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π …
      -/
      intro S ⟨T, a, (g : T.left ⟶ X a), hT⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateFamily …
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp T.hom (H.desc (fun a => S.ι.app { obj …
      -/
      nth_rewrite 1 [← hT, Category.assoc, H.fac]
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let A : D := ⟨Over.mk (π a), a, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        A : D := { obj := CategoryTheory.Over.mk (π a), property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let B : D := ⟨Over.mk T.hom, a, g, hT⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B✝ : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B✝
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B✝
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        A : D := { obj := CategoryTheory.Over.mk (π a), property := ⋯ }
        B : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      let i : B ⟶ A := Over.homMk g
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B✝ : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B✝
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B✝
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        A : D := { obj := CategoryTheory.Over.mk (π a), property := ⋯ }
        B : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        i : Quiver.Hom B A := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (S.ι.app { obj := CategoryTheory.Ov …
      -/
      change F.map i ≫ _ = _
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B✝ : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B✝
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B✝
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        A : D := { obj := CategoryTheory.Over.mk (π a), property := ⋯ }
        B : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        i : Quiver.Hom B A := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map i) (S.ι.app { obj := CategoryT …
      -/
      rw [S.w]
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B✝ : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B✝
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        T : CategoryTheory.Over B✝
        a : α
        g : Quiver.Hom T.left (X a)
        hT : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        A : D := { obj := CategoryTheory.Over.mk (π a), property := ⋯ }
        B : D := { obj := CategoryTheory.Over.mk T.hom, property := ⋯ }
        i : Quiver.Hom B A := CategoryTheory.Over.homMk g ⋯
        ⊢ Eq (S.ι.app B) (S.ι.app { obj := T, property := ⋯ })
      -/
      rfl
      /-
        🎉 no goals
      -/
    uniq := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        ⊢ ∀ (s : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π …
      -/
      intro S m hm; dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        m : Quiver.Hom (CategoryTheory.Sieve.generateFamily X π).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateFamily X π).arrows.category), Eq (Ca …
        ⊢ Eq m (H.desc (fun a => S.ι.app { obj := CategoryTheory.Over.mk (π a), proper …
      -/
      apply H.uniq
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        m : Quiver.Hom (CategoryTheory.Sieve.generateFamily X π).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateFamily X π).arrows.category), Eq (Ca …
        ⊢ ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (S.ι.app { obj := …
      -/
      intro a
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.29784, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.EffectiveEpiFamilyStruct X π
        D : Type (max u_1 ?u.29784) := CategoryTheory.FullSubcategory fun T => (Catego …
        F : CategoryTheory.Functor D C := (CategoryTheory.Sieve.generateFamily X π).ar …
        S : CategoryTheory.Limits.Cocone (CategoryTheory.Sieve.generateFamily X π).arr …
        m : Quiver.Hom (CategoryTheory.Sieve.generateFamily X π).arrows.cocone.pt S.pt
        hm : ∀ (j : (CategoryTheory.Sieve.generateFamily X π).arrows.category), Eq (Ca …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (π a) m) (S.ι.app { obj := CategoryTh …
      -/
      exact hm ⟨Over.mk (π a), a, 𝟙 _, by simp⟩ }
      /-
        🎉 no goals
      -/


/--
Implementation: This is a construction which will be used in the proof that
the sieve generated by a family of arrows is effective epimorphic if and only if
the family is an effective epi.
-/
noncomputable
def effectiveEpiFamilyStructOfIsColimit {B : C} {α : Type*}
    (X : α → C) (π : (a : α) → (X a ⟶ B))
    (H : IsColimit (Sieve.generateFamily X π : Presieve B).cocone) :
    EffectiveEpiFamilyStruct X π :=
  let aux {W : C} (e : (a : α) → (X a ⟶ W))
    (h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Z ⟶ X a₁) (g₂ : Z ⟶ X a₂),
      g₁ ≫ π _ = g₂ ≫ π _ → g₁ ≫ e _ = g₂ ≫ e _) :
    Cocone (Sieve.generateFamily X π).arrows.diagram := {
      pt := W
      ι := {
        app := fun ⟨_,hT⟩ => hT.choose_spec.choose ≫ e hT.choose
        naturality := by
          /-
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
            B : C
            α : Type u_2
            X : α → C
            π : (a : α) → Quiver.Hom (X a) B
            H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
            W : C
            e : (a : α) → Quiver.Hom (X a) W
            h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
            ⊢ ∀ ⦃X_1 Y : (CategoryTheory.Sieve.generateFamily X π).arrows.category⦄ (f : Q …
          -/
          intro ⟨A,a,(g₁ : A.left ⟶ _),ha⟩ ⟨B,b,(g₂ : B.left ⟶ _),hb⟩ (q : A ⟶ B)
          /-
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
            B✝ : C
            α : Type u_2
            X : α → C
            π : (a : α) → Quiver.Hom (X a) B✝
            H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
            W : C
            e : (a : α) → Quiver.Hom (X a) W
            h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
            A : CategoryTheory.Over B✝
            a : α
            g₁ : Quiver.Hom A.left (X a)
            ha : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a)) A.hom
            B : CategoryTheory.Over B✝
            b : α
            g₂ : Quiver.Hom B.left (X b)
            hb : Eq (CategoryTheory.CategoryStruct.comp g₂ (π b)) B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateFamily …
          -/
          dsimp; rw [Category.comp_id, ← Category.assoc]
          /-
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
            B✝ : C
            α : Type u_2
            X : α → C
            π : (a : α) → Quiver.Hom (X a) B✝
            H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
            W : C
            e : (a : α) → Quiver.Hom (X a) W
            h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
            A : CategoryTheory.Over B✝
            a : α
            g₁ : Quiver.Hom A.left (X a)
            ha : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a)) A.hom
            B : CategoryTheory.Over B✝
            b : α
            g₂ : Quiver.Hom B.left (X b)
            hb : Eq (CategoryTheory.CategoryStruct.comp g₂ (π b)) B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp q …
          -/
          apply h; rw [Category.assoc]
          /-
            case a
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
            B✝ : C
            α : Type u_2
            X : α → C
            π : (a : α) → Quiver.Hom (X a) B✝
            H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
            W : C
            e : (a : α) → Quiver.Hom (X a) W
            h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
            A : CategoryTheory.Over B✝
            a : α
            g₁ : Quiver.Hom A.left (X a)
            ha : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a)) A.hom
            B : CategoryTheory.Over B✝
            b : α
            g₂ : Quiver.Hom B.left (X b)
            hb : Eq (CategoryTheory.CategoryStruct.comp g₂ (π b)) B.hom
            q : Quiver.Hom A B
            ⊢ Eq (CategoryTheory.CategoryStruct.comp q.left (CategoryTheory.CategoryStruct …
          -/
          generalize_proofs h1 h2 h3 h4
          /-
            case a
            C : Type u_1
            inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
            B✝ : C
            α : Type u_2
            X : α → C
            π : (a : α) → Quiver.Hom (X a) B✝
            H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
            W : C
            e : (a : α) → Quiver.Hom (X a) W
            h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
            A : CategoryTheory.Over B✝
            a : α
            g₁ : Quiver.Hom A.left (X a)
            ha : Eq (CategoryTheory.CategoryStruct.comp g₁ (π a)) A.hom
            B : CategoryTheory.Over B✝
            b : α
            g₂ : Quiver.Hom B.left (X b)
            hb : Eq (CategoryTheory.CategoryStruct.comp g₂ (π b)) B.hom
            q : Quiver.Hom A B
            h1 : Exists fun a => Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g  …
            h2 : Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g (π h1.choose)) B …
            h3 : Exists fun a => Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g  …
            h4 : Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g (π h3.choose)) A …
            ⊢ Eq (CategoryTheory.CategoryStruct.comp q.left (CategoryTheory.CategoryStruct …
          -/
          rw [h2.choose_spec, h4.choose_spec, Over.w] } }
          /-
            🎉 no goals
          -/
  { desc := fun {_} e h => H.desc (aux e h)
    fac := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        ⊢ ∀ {W : C} (e : (a : α) → Quiver.Hom (X a) W) (h : ∀ {Z : C} (a₁ a₂ : α) (g₁  …
      -/
      intro W e h a
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (π a) ((fun {x} e h => H.desc (aux e  …
      -/
      dsimp
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (π a) (H.desc (aux e ⋯))) (e a)
      -/
      have := H.fac (aux e h) ⟨Over.mk (π a), a, 𝟙 _, by simp⟩
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        this : Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateF …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (π a) (H.desc (aux e ⋯))) (e a)
      -/
      dsimp [aux] at this; rw [this]; clear this
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ⋯.choose (e (Exists.choose ⋯))) (e a)
      -/
      conv_rhs => rw [← Category.id_comp (e a)]
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ⋯.choose (e (Exists.choose ⋯))) (Cate …
      -/
      apply h
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ⋯.choose (π (Exists.choose ⋯))) (Cate …
      -/
      generalize_proofs h1 h2
      /-
        case a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        a : α
        h1 : Exists fun a_1 => Exists fun g => Eq (CategoryTheory.CategoryStruct.comp  …
        h2 : Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g (π h1.choose)) ( …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp h2.choose (π h1.choose)) (CategoryThe …
      -/
      rw [h2.choose_spec, Category.id_comp]
      /-
        🎉 no goals
      -/
    uniq := by
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        ⊢ ∀ {W : C} (e : (a : α) → Quiver.Hom (X a) W) (h : ∀ {Z : C} (a₁ a₂ : α) (g₁  …
      -/
      intro W e h m hm
      /-
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        ⊢ Eq m ((fun {x} e h => H.desc (aux e ⋯)) e ⋯)
      -/
      apply H.uniq (aux e h)
      /-
        case x
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        ⊢ ∀ (j : (CategoryTheory.Sieve.generateFamily X π).arrows.category), Eq (Categ …
      -/
      rintro ⟨T, a, (g : T.left ⟶ _), ha⟩
      /-
        case x.mk.intro.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        ha : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp ((CategoryTheory.Sieve.generateFamily …
      -/
      dsimp
      /-
        case x.mk.intro.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        ha : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp T.hom m) (CategoryTheory.CategoryStru …
      -/
      nth_rewrite 1 [← ha, Category.assoc, hm]
      /-
        case x.mk.intro.intro
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        ha : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (e a)) (CategoryTheory.CategoryStru …
      -/
      apply h
      /-
        case x.mk.intro.intro.a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        ha : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (π a)) (CategoryTheory.CategoryStru …
      -/
      generalize_proofs h1 h2
      /-
        case x.mk.intro.intro.a
        C : Type u_1
        inst✝ : CategoryTheory.Category.{?u.43166, u_1} C
        B : C
        α : Type u_2
        X : α → C
        π : (a : α) → Quiver.Hom (X a) B
        H : CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFamily X π). …
        aux : {W : C} → (e : (a : α) → Quiver.Hom (X a) W) → (∀ {Z : C} (a₁ a₂ : α) (g …
        W : C
        e : (a : α) → Quiver.Hom (X a) W
        h : ∀ {Z : C} (a₁ a₂ : α) (g₁ : Quiver.Hom Z (X a₁)) (g₂ : Quiver.Hom Z (X a₂) …
        m : Quiver.Hom B W
        hm : ∀ (a : α), Eq (CategoryTheory.CategoryStruct.comp (π a) m) (e a)
        T : CategoryTheory.Over B
        a : α
        g : Quiver.Hom T.left (X a)
        ha : Eq (CategoryTheory.CategoryStruct.comp g (π a)) T.hom
        h1 : Exists fun a => Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g  …
        h2 : Exists fun g => Eq (CategoryTheory.CategoryStruct.comp g (π h1.choose)) T …
        ⊢ Eq (CategoryTheory.CategoryStruct.comp g (π a)) (CategoryTheory.CategoryStru …
      -/
      rwa [h2.choose_spec] }
      /-
        🎉 no goals
      -/


theorem Sieve.effectiveEpimorphic_family {B : C} {α : Type*}
    (X : α → C) (π : (a : α) → (X a ⟶ B)) :
    (Presieve.ofArrows X π).EffectiveEpimorphic ↔ EffectiveEpiFamily X π := by
  /-
    C : Type u_1
    inst✝ : CategoryTheory.Category.{u_3, u_1} C
    B : C
    α : Type u_2
    X : α → C
    π : (a : α) → Quiver.Hom (X a) B
    ⊢ Iff (CategoryTheory.Presieve.ofArrows X π).EffectiveEpimorphic (CategoryTheo …
  -/
  constructor
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      ⊢ (CategoryTheory.Presieve.ofArrows X π).EffectiveEpimorphic → CategoryTheory. …
    -/
  · intro (h : Nonempty _)
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generate ( …
      ⊢ CategoryTheory.EffectiveEpiFamily X π
    -/
    rw [Sieve.generateFamily_eq] at h
    /-
      case mp
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFa …
      ⊢ CategoryTheory.EffectiveEpiFamily X π
    -/
    constructor
    /-
      case mp.effectiveEpiFamily
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFa …
      ⊢ Nonempty (CategoryTheory.EffectiveEpiFamilyStruct X π)
    -/
    apply Nonempty.map (effectiveEpiFamilyStructOfIsColimit _ _) h
    /-
      🎉 no goals
    -/
    /-
      case mpr
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      ⊢ CategoryTheory.EffectiveEpiFamily X π → (CategoryTheory.Presieve.ofArrows X  …
    -/
  · rintro ⟨h⟩
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.EffectiveEpiFamilyStruct X π)
      ⊢ (CategoryTheory.Presieve.ofArrows X π).EffectiveEpimorphic
    -/
    show Nonempty _
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.EffectiveEpiFamilyStruct X π)
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generate (Ca …
    -/
    rw [Sieve.generateFamily_eq]
    /-
      case mpr.mk
      C : Type u_1
      inst✝ : CategoryTheory.Category.{u_3, u_1} C
      B : C
      α : Type u_2
      X : α → C
      π : (a : α) → Quiver.Hom (X a) B
      h : Nonempty (CategoryTheory.EffectiveEpiFamilyStruct X π)
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit (CategoryTheory.Sieve.generateFami …
    -/
    apply Nonempty.map (isColimitOfEffectiveEpiFamilyStruct _ _) h
    /-
      🎉 no goals
    -/


