/-- Index a basis of E/F using the initial ordinal of the cardinal `Module.rank F E`. -/
local notation "ι" => (Module.rank F E).ord.toType


private local instance : SuccOrder ι := SuccOrder.ofLinearWellFoundedLT ι

local notation i"⁺" => succ i -- Note: conflicts with `PosPart` notation


/-- A basis of E/F indexed by the initial ordinal. -/
def wellOrderedBasis : Basis ι F E :=
  (chooseBasis F E).reindex
    (Cardinal.eq.mp <| (mk_ord_toType _).trans <| rank_eq_card_chooseBasisIndex F E).some.symm


local notation "b" => wellOrderedBasis F E

local notation "Ē" => AlgebraicClosure E


theorem adjoin_basis_eq_top : adjoin F (range b) = ⊤ :=
  toSubalgebra_injective <| Subalgebra.toSubmodule_injective <| top_unique <|
    (Basis.span_eq b).ge.trans <| (Algebra.span_le_adjoin F _).trans <| algebra_adjoin_le_adjoin _ _


lemma noMaxOrder_rank_toType : NoMaxOrder ι := Cardinal.noMaxOrder Fact.out

variable (F E) in
/-- `leastExt i` is defined to be the smallest `k : ι` that generates a nontrival extension over
(i.e. does not lie in) the subalgebra (= intermediate field) generated by all previous
`leastExt j`, `j < i`. For cardinality reasons, such `k` always exist if `ι` is infinite. -/
def leastExt : ι → ι :=
  wellFounded_lt.fix fun i ih ↦
    let s := range fun j : Iio i ↦ b (ih j j.2)
    wellFounded_lt.min {k | b k ∉ adjoin F s} <| by
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        ⊢ (setOf fun k => Not (Membership.mem (IntermediateField.adjoin F s) ((Field.E …
      -/
      rw [← compl_setOf, nonempty_compl]; by_contra!
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this : Eq (setOf fun a => Membership.mem (IntermediateField.adjoin F s) ((Fiel …
        ⊢ False
      -/
      simp_rw [eq_univ_iff_forall, mem_setOf] at this
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateField …
        ⊢ False
      -/
      have := adjoin_le_iff.mpr (range_subset_iff.mpr this)
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFiel …
        this : LE.le (IntermediateField.adjoin F (Set.range ⇑(Field.Emb.Cardinal.wellO …
        ⊢ False
      -/
      rw [adjoin_basis_eq_top, ← eq_top_iff] at this
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFiel …
        this : Eq (IntermediateField.adjoin F s) Top.top
        ⊢ False
      -/
      apply_fun Module.rank F at this
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFiel …
        this : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.a …
        ⊢ False
      -/
      refine ne_of_lt ?_ this
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFiel …
        this : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.a …
        ⊢ LT.lt (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.adj …
      -/
      conv_rhs => rw [topEquiv.toLinearEquiv.rank_eq]
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFiel …
        this : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.a …
        ⊢ LT.lt (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.adj …
      -/
      have := mk_Iio_ord_toType i
      /-
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
        s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
        this✝¹ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFie …
        this✝ : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField. …
        this : LT.lt (Cardinal.mk ↑(Set.Iio i)) (Module.rank F E)
        ⊢ LT.lt (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.adj …
      -/
      obtain eq | lt := rank_inf.out.eq_or_lt
        /-
          case inl
          F : Type u
          E : Type v
          inst✝³ : Field F
          inst✝² : Field E
          inst✝¹ : Algebra F E
          rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
          inst✝ : Algebra.IsAlgebraic F E
          i : (Module.rank F E).ord.toType
          ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
          s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
          this✝¹ : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFie …
          this✝ : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField. …
          this : LT.lt (Cardinal.mk ↑(Set.Iio i)) (Module.rank F E)
          eq : Eq Cardinal.aleph0 (Module.rank F E)
          ⊢ LT.lt (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.adj …
        -/
      · replace this := mk_lt_aleph0_iff.mp (this.trans_eq eq.symm)
        have : FiniteDimensional F (adjoin F s) :=
          finiteDimensional_adjoin fun x _ ↦ (IsAlgebraic.isAlgebraic x).isIntegral
        /-
          case inl
          F : Type u
          E : Type v
          inst✝³ : Field F
          inst✝² : Field E
          inst✝¹ : Algebra F E
          rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
          inst✝ : Algebra.IsAlgebraic F E
          i : (Module.rank F E).ord.toType
          ih : (y : (Module.rank F E).ord.toType) → LT.lt y i → (Module.rank F E).ord.to …
          s : Set E := Set.range fun j => (Field.Emb.Cardinal.wellOrderedBasis F E) (ih  …
          this✝² : ∀ (x : (Module.rank F E).ord.toType), Membership.mem (IntermediateFie …
          this✝¹ : Eq (Module.rank F (Subtype fun x => Membership.mem (IntermediateField …
          eq : Eq Cardinal.aleph0 (Module.rank F E)
          this✝ : Finite ↑(Set.Iio i)
          this : FiniteDimensional F (Subtype fun x => Membership.mem (IntermediateField …
          ⊢ LT.lt (Module.rank F (Subtype fun x => Membership.mem (IntermediateField.adj …
        -/
        exact (Module.rank_lt_aleph0 _ _).trans_eq eq
        /-
          🎉 no goals
        -/
      · exact (Subalgebra.equivOfEq _ _ <| adjoin_algebraic_toSubalgebra
          fun x _ ↦ IsAlgebraic.isAlgebraic x)|>.toLinearEquiv.rank_eq.trans_lt <|
          (Algebra.rank_adjoin_le _).trans_lt (max_lt (mk_range_le.trans_lt this) lt)


local notation "φ" => leastExt F E


local notation "E⟮<"i"⟯" => adjoin F (b ∘ φ '' Iio i)


theorem isLeast_leastExt (i : ι) : IsLeast {k | b k ∉ E⟮<i⟯} (φ i) := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ IsLeast (setOf fun k => Not (Membership.mem (IntermediateField.adjoin F (Set …
  -/
  rw [image_eq_range, leastExt, wellFounded_lt.fix_eq]
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ IsLeast
        (setOf fun k =>
          Not
            (Membership.mem
              (IntermediateField.adjoin F
                (Set.range fun x =>
                  Function.comp (⇑(Field.Emb.Cardinal.wellOrderedBasis F E))
                    (⋯.fix fun i ih =>
                      let s := Set.range fun j => (Field.Emb.Cardinal.wellOrderedB …
                      ⋯.min (setOf fun k => Not (Membership.mem (IntermediateField …
                    ↑x))
              ((Field.Emb.Cardinal.wellOrderedBasis F E) k)))
        (let s :=
          Set.range fun j =>
            (Field.Emb.Cardinal.wellOrderedBasis F E)
              ((fun y x =>
                  ⋯.fix
                    (fun i ih =>
                      let s := Set.range fun j => (Field.Emb.Cardinal.wellOrderedB …
                      ⋯.min (setOf fun k => Not (Membership.mem (IntermediateField …
                    y)
                ↑j ⋯);
        ⋯.min (setOf fun k => Not (Membership.mem (IntermediateField.adjoin F s) ( …
  -/
  exact ⟨wellFounded_lt.min_mem _ _, fun _ ↦ (wellFounded_lt.min_le ·)⟩
  /-
    🎉 no goals
  -/


theorem strictMono_leastExt : StrictMono φ := fun i j h ↦ by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i j : (Module.rank F E).ord.toType
    h : LT.lt i j
    ⊢ LT.lt (Field.Emb.Cardinal.leastExt F E i) (Field.Emb.Cardinal.leastExt F E j)
  -/
  have least := isLeast_leastExt (F := F) (E := E)
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i j : (Module.rank F E).ord.toType
    h : LT.lt i j
    least : ∀ (i : (Module.rank F E).ord.toType), IsLeast (setOf fun k => Not (Mem …
    ⊢ LT.lt (Field.Emb.Cardinal.leastExt F E i) (Field.Emb.Cardinal.leastExt F E j)
  -/
  by_contra!
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i j : (Module.rank F E).ord.toType
    h : LT.lt i j
    least : ∀ (i : (Module.rank F E).ord.toType), IsLeast (setOf fun k => Not (Mem …
    this : LE.le (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt  …
    ⊢ False
  -/
  obtain eq | lt := this.eq_or_lt
    /-
      case inl
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i j : (Module.rank F E).ord.toType
      h : LT.lt i j
      least : ∀ (i : (Module.rank F E).ord.toType), IsLeast (setOf fun k => Not (Mem …
      this : LE.le (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt  …
      eq : Eq (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt F E i)
      ⊢ False
    -/
  · exact (least j).1 (subset_adjoin _ _ ⟨i, h, congr_arg b eq.symm⟩)
    /-
      🎉 no goals
    -/
    /-
      case inr
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i j : (Module.rank F E).ord.toType
      h : LT.lt i j
      least : ∀ (i : (Module.rank F E).ord.toType), IsLeast (setOf fun k => Not (Mem …
      this : LE.le (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt  …
      lt : LT.lt (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt F  …
      ⊢ False
    -/
  · refine ((least i).2 <| mt (adjoin.mono _ _ _ (image_mono ?_) ·) (least j).1).not_lt lt
    /-
      case inr
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i j : (Module.rank F E).ord.toType
      h : LT.lt i j
      least : ∀ (i : (Module.rank F E).ord.toType), IsLeast (setOf fun k => Not (Mem …
      this : LE.le (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt  …
      lt : LT.lt (Field.Emb.Cardinal.leastExt F E j) (Field.Emb.Cardinal.leastExt F  …
      x✝ : Membership.mem (IntermediateField.adjoin F (Set.image (Function.comp (⇑(F …
      ⊢ HasSubset.Subset (Set.Iio i) (Set.Iio j)
    -/
    exact fun k (hk : k < i) ↦ hk.trans h
    /-
      🎉 no goals
    -/


theorem adjoin_image_leastExt (i : ι) : E⟮<i⟯ = adjoin F (b '' Iio (φ i)) := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ Eq (IntermediateField.adjoin F (Set.image (Function.comp (⇑(Field.Emb.Cardin …
  -/
  refine le_antisymm (adjoin.mono _ _ _ ?_) (adjoin_le_iff.mpr ?_)
    /-
      case refine_1
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : (Module.rank F E).ord.toType
      ⊢ HasSubset.Subset (Set.image (Function.comp (⇑(Field.Emb.Cardinal.wellOrdered …
    -/
  · rw [image_comp]; apply image_mono; rintro _ ⟨j, hj, rfl⟩; exact strictMono_leastExt hj
                                                              /-
                                                                🎉 no goals
                                                              -/
    /-
      case refine_2
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : (Module.rank F E).ord.toType
      ⊢ HasSubset.Subset (Set.image (⇑(Field.Emb.Cardinal.wellOrderedBasis F E)) (Se …
    -/
  · rintro _ ⟨j, hj, rfl⟩; contrapose! hj; exact ((isLeast_leastExt i).2 hj).not_lt
                                           /-
                                             🎉 no goals
                                           -/


theorem iSup_adjoin_eq_top : ⨆ i : ι, E⟮<i⟯ = ⊤ := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    ⊢ Eq (iSup fun i => IntermediateField.adjoin F (Set.image (Function.comp (⇑(Fi …
  -/
  simp_rw [adjoin_image_leastExt, eq_top_iff, ← adjoin_basis_eq_top, adjoin_le_iff]
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    ⊢ HasSubset.Subset (Set.range ⇑(Field.Emb.Cardinal.wellOrderedBasis F E)) ↑(iS …
  -/
  rintro _ ⟨i, rfl⟩
  /-
    case intro
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ Membership.mem (↑(iSup fun i => IntermediateField.adjoin F (Set.image (⇑(Fie …
  -/
  refine le_iSup (α := IntermediateField F E) _ (i⁺) (subset_adjoin _ _ ⟨i, ?_, rfl⟩)
  /-
    case intro
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ Membership.mem (Set.Iio (Field.Emb.Cardinal.leastExt F E (Order.succ i))) i
  -/
  exact (lt_succ i).trans_le strictMono_leastExt.le_apply
  /-
    🎉 no goals
  -/


theorem strictMono_filtration : StrictMono (E⟮<·⟯) :=
  fun i _ h ↦ ⟨adjoin.mono _ _ _ (image_mono <| Iio_subset_Iio h.le),
    fun incl ↦ (isLeast_leastExt i).1 (incl <| subset_adjoin _ _ ⟨i, h, rfl⟩)⟩


theorem filtration_succ (i : ι) : E⟮<i⁺⟯ = E⟮<i⟯⟮b (φ i)⟯.restrictScalars F := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    ⊢ Eq (IntermediateField.adjoin F (Set.image (Function.comp (⇑(Field.Emb.Cardin …
  -/
  rw [Iio_succ, ← Iio_insert, image_insert_eq, ← union_singleton, adjoin_adjoin_left]; rfl
                                                                                       /-
                                                                                         🎉 no goals
                                                                                       -/


local notation "X" i => Field.Emb (E⟮<i⟯) <| E⟮<i⟯⟮b (φ i)⟯


/-- Each embedding of `E⟮<i⟯` into `Ē` extend to `#(X i)` embeddings of `E⟮<i⁺⟯`. -/
def succEquiv (i : ι) : (E⟮<i⁺⟯ →ₐ[F] Ē) ≃ (E⟮<i⟯ →ₐ[F] Ē) × X i :=
  (((show _ ≃ₐ[F] E⟮<i⟯⟮b (φ i)⟯ from equivOfEq (filtration_succ i))).arrowCongr .refl).trans <|
    algHomEquivSigma (B := E⟮<i⟯).trans <| .sigmaEquivProdOfEquiv fun _ ↦
      (@Field.embEquivOfIsAlgClosed _ _ _ _ _ _ _ (_) <|
        (Algebra.IsAlgebraic.tower_top (K := F) _).of_injective (val _) Subtype.val_injective).symm


theorem succEquiv_coherence (i : ι) (f) : (succEquiv i f).1 =
    f.comp (Subalgebra.inclusion <| strictMono_filtration.monotone <| le_succ i) := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : (Module.rank F E).ord.toType
    f : AlgHom F (Subtype fun x => Membership.mem (IntermediateField.adjoin F (Set …
    ⊢ Eq ((Field.Emb.Cardinal.succEquiv i) f).1 (f.comp (Subalgebra.inclusion ⋯))
  -/
  ext; simp [succEquiv]; rfl -- slow rfl (type checking took 11.9s)
                         /-
                           🎉 no goals
                         -/


instance (i : ι) : FiniteDimensional (E⟮<i⟯) (E⟮<i⟯⟮b (φ i)⟯) :=
  adjoin.finiteDimensional ((Algebra.IsAlgebraic.tower_top (K := F) _).isAlgebraic _).isIntegral


theorem deg_lt_aleph0 (i : ι) : #(X i) < ℵ₀ :=
  (toNat_ne_zero.mp (Field.instNeZeroFinSepDegree (E⟮<i⟯) <| E⟮<i⟯⟮b (φ i)⟯).out).2


open WithTop in
/-- Extend the family `E⟮<i⟯, i : ι` by adjoining a top element. -/
@[simps!] def filtration : WithTop ι ↪o IntermediateField F E :=
  .ofStrictMono (fun i ↦ i.recTopCoe ⊤ (E⟮<·⟯)) fun i j h ↦ by
    /-
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i j : WithTop (Module.rank F E).ord.toType
      h : LT.lt i j
      ⊢ LT.lt ((fun i => WithTop.recTopCoe Top.top (fun x => IntermediateField.adjoi …
    -/
    cases j
      /-
        case top
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        h : LT.lt i Top.top
        ⊢ LT.lt ((fun i => WithTop.recTopCoe Top.top (fun x => IntermediateField.adjoi …
      -/
    · obtain ⟨i, rfl⟩ := ne_top_iff_exists.mp h.ne
      /-
        case top.intro
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : (Module.rank F E).ord.toType
        h : LT.lt (↑i) Top.top
        ⊢ LT.lt ((fun i => WithTop.recTopCoe Top.top (fun x => IntermediateField.adjoi …
      -/
      exact ⟨le_top, fun incl ↦ (isLeast_leastExt i).1 (incl trivial)⟩
      /-
        🎉 no goals
      -/
      /-
        case coe
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        a✝ : (Module.rank F E).ord.toType
        h : LT.lt i ↑a✝
        ⊢ LT.lt ((fun i => WithTop.recTopCoe Top.top (fun x => IntermediateField.adjoi …
      -/
    · obtain ⟨i, rfl⟩ := ne_top_iff_exists.mp (h.trans <| coe_lt_top _).ne
      /-
        case coe.intro
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        a✝ i : (Module.rank F E).ord.toType
        h : LT.lt ↑i ↑a✝
        ⊢ LT.lt ((fun i => WithTop.recTopCoe Top.top (fun x => IntermediateField.adjoi …
      -/
      exact strictMono_filtration (coe_lt_coe.mp h)
      /-
        🎉 no goals
      -/


/-- Extend the family `X i := E⟮<i⟯ →ₐ[F] Ē` from `ι` to `WithTop ι`. -/
def factor (i : WithTop ι) : Type _ := i.recTopCoe PUnit (X ·)


instance (i : ι) : Algebra.IsSeparable (E⟮<i⟯) (E⟮<i⟯⟮b (φ i)⟯) :=
  have := Algebra.isSeparable_tower_top_of_isSeparable F (E⟮<i⟯) E
  have : IsScalarTower (E⟮<i⟯) (E⟮<i⟯⟮b (φ i)⟯) E := .of_algebraMap_eq' rfl
  Algebra.isSeparable_tower_bot_of_isSeparable _ _ E


open Field in
theorem two_le_deg (i : ι) : 2 ≤ #(X i) := by
  rw [← Nat.cast_ofNat, ← toNat_le_iff_le_of_lt_aleph0 (nat_lt_aleph0 _) (deg_lt_aleph0 i),
    toNat_natCast, ← Nat.card, ← finSepDegree, finSepDegree_eq_finrank_of_isSeparable, Nat.succ_le]
  /-
    F : Type u
    E : Type v
    inst✝⁴ : Field F
    inst✝³ : Field E
    inst✝² : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝¹ : Algebra.IsAlgebraic F E
    inst✝ : Algebra.IsSeparable F E
    i : (Module.rank F E).ord.toType
    ⊢ LT.lt 1 (Module.finrank (Subtype fun x => Membership.mem (IntermediateField. …
  -/
  by_contra!
  /-
    F : Type u
    E : Type v
    inst✝⁴ : Field F
    inst✝³ : Field E
    inst✝² : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝¹ : Algebra.IsAlgebraic F E
    inst✝ : Algebra.IsSeparable F E
    i : (Module.rank F E).ord.toType
    this : LE.le (Module.finrank (Subtype fun x => Membership.mem (IntermediateFie …
    ⊢ False
  -/
  obtain ⟨x, hx⟩ := finrank_adjoin_simple_eq_one_iff.mp (this.antisymm Module.finrank_pos)
  /-
    case intro
    F : Type u
    E : Type v
    inst✝⁴ : Field F
    inst✝³ : Field E
    inst✝² : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝¹ : Algebra.IsAlgebraic F E
    inst✝ : Algebra.IsSeparable F E
    i : (Module.rank F E).ord.toType
    this : LE.le (Module.finrank (Subtype fun x => Membership.mem (IntermediateFie …
    x : Subtype fun x => Membership.mem (IntermediateField.adjoin F (Set.image (Fu …
    hx : Eq ((Algebra.ofId (Subtype fun x => Membership.mem (IntermediateField.adj …
    ⊢ False
  -/
  refine (isLeast_leastExt i).1 (hx ▸ ?_)
  /-
    case intro
    F : Type u
    E : Type v
    inst✝⁴ : Field F
    inst✝³ : Field E
    inst✝² : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝¹ : Algebra.IsAlgebraic F E
    inst✝ : Algebra.IsSeparable F E
    i : (Module.rank F E).ord.toType
    this : LE.le (Module.finrank (Subtype fun x => Membership.mem (IntermediateFie …
    x : Subtype fun x => Membership.mem (IntermediateField.adjoin F (Set.image (Fu …
    hx : Eq ((Algebra.ofId (Subtype fun x => Membership.mem (IntermediateField.adj …
    ⊢ Membership.mem (IntermediateField.adjoin F (Set.image (Function.comp (⇑(Fiel …
  -/
  exact x.2
  /-
    🎉 no goals
  -/


local notation "E⟮<"i"⟯" => filtration i


variable (F E) in
/-- The functor on `WithTop ι` given by embeddings of `E⟮<i⟯` into `Ē` -/
def embFunctor ⦃i j : WithTop ι⦄ (h : i ≤ j) (f : E⟮<j⟯ →ₐ[F] Ē) : E⟮<i⟯ →ₐ[F] Ē :=
  f.comp (Subalgebra.inclusion <| filtration.monotone h)


instance : InverseSystem (embFunctor F E) where
  map_self _ _ := rfl
  map_map _ _ _ _ _ _ := rfl


private local instance (i : ι) : Decidable (succ i = i) := .isFalse (lt_succ i).ne'


/-- Extend `succEquiv` from `ι` to `WithTop ι`. -/
def equivSucc (i : WithTop ι) : (E⟮<i⁺⟯ →ₐ[F] Ē) ≃ (E⟮<i⟯ →ₐ[F] Ē) × factor i :=
                                 /-
                                   F : Type u
                                   E : Type v
                                   inst✝³ : Field F
                                   inst✝² : Field E
                                   inst✝¹ : Algebra F E
                                   rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
                                   inst✝ : Algebra.IsAlgebraic F E
                                   i : WithTop (Module.rank F E).ord.toType
                                   ⊢ Eq (Field.Emb.Cardinal.filtration (Order.succ Top.top)) (Field.Emb.Cardinal. …
                                 -/
  i.recTopCoe (((equivOfEq <| by rw [succ_top]).arrowCongr .refl).trans <| .symm <| .prodPUnit _)
                                 /-
                                   🎉 no goals
                                 -/
    (succEquiv ·)


theorem equivSucc_coherence (i f) : (equivSucc i f).1 = embFunctor F E (le_succ i) f := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : WithTop (Module.rank F E).ord.toType
    f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration ( …
    ⊢ Eq ((Field.Emb.Cardinal.equivSucc i) f).1 (Field.Emb.Cardinal.embFunctor F E …
  -/
  cases i; exacts [rfl, succEquiv_coherence _ f]
           /-
             🎉 no goals
           -/


theorem directed_filtration : Directed (· ≤ ·) fun j : Iio i ↦ filtration j.1 :=
  (filtration.monotone.comp <| Subtype.mono_coe _).directed_le


open WithTop in
theorem iSup_filtration : ⨆ j : Iio i, filtration j = filtration i := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : WithTop (Module.rank F E).ord.toType
    hi : Order.IsSuccPrelimit i
    ⊢ Eq (iSup fun j => Field.Emb.Cardinal.filtration ↑j) (Field.Emb.Cardinal.filt …
  -/
  cases i
    /-
      case top
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      hi : Order.IsSuccPrelimit Top.top
      ⊢ Eq (iSup fun j => Field.Emb.Cardinal.filtration ↑j) (Field.Emb.Cardinal.filt …
    -/
  · rw [← range_coe, iSup_range']; exact iSup_adjoin_eq_top
                                   /-
                                     🎉 no goals
                                   -/
  /-
    case coe
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    a✝ : (Module.rank F E).ord.toType
    hi : Order.IsSuccPrelimit ↑a✝
    ⊢ Eq (iSup fun j => Field.Emb.Cardinal.filtration ↑j) (Field.Emb.Cardinal.filt …
  -/
  refine (iSup_le fun j ↦ filtration.monotone (mem_Iio.1 j.2).le).antisymm (adjoin_le_iff.2 ?_)
  /-
    case coe
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    a✝ : (Module.rank F E).ord.toType
    hi : Order.IsSuccPrelimit ↑a✝
    ⊢ HasSubset.Subset (Set.image (Function.comp (⇑(Field.Emb.Cardinal.wellOrdered …
  -/
  rintro _ ⟨j, hj, rfl⟩
  /-
    case coe.intro.intro
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    a✝ : (Module.rank F E).ord.toType
    hi : Order.IsSuccPrelimit ↑a✝
    j : (Module.rank F E).ord.toType
    hj : Membership.mem (Set.Iio a✝) j
    ⊢ Membership.mem (↑(iSup fun j => Field.Emb.Cardinal.filtration ↑j)) (Function …
  -/
  refine le_iSup (α := IntermediateField F E) _ ⟨j⁺, ?_⟩ (subset_adjoin F _ ?_)
  /-
    case coe.intro.intro.refine_1
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    a✝ : (Module.rank F E).ord.toType
    hi : Order.IsSuccPrelimit ↑a✝
    j : (Module.rank F E).ord.toType
    hj : Membership.mem (Set.Iio a✝) j
    ⊢ Membership.mem (Set.image (Function.comp (⇑(Field.Emb.Cardinal.wellOrderedBa …
  -/
  exacts [⟨j, lt_succ j, rfl⟩, hi.succ_lt (coe_lt_coe.mpr hj)]
  /-
    🎉 no goals
  -/


lemma eq_bot_of_not_nonempty (hi : ¬ Nonempty (Iio i)) : filtration i = ⊥ := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    inst✝ : Algebra.IsAlgebraic F E
    i : WithTop (Module.rank F E).ord.toType
    hi✝ : Order.IsSuccPrelimit i
    hi : Not (Nonempty ↑(Set.Iio i))
    ⊢ Eq (Field.Emb.Cardinal.filtration i) Bot.bot
  -/
  cases i
    /-
      case top
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      hi✝ : Order.IsSuccPrelimit Top.top
      hi : Not (Nonempty ↑(Set.Iio Top.top))
      ⊢ Eq (Field.Emb.Cardinal.filtration Top.top) Bot.bot
    -/
  · have := mk_ne_zero_iff.mp (rank_pos.trans_eq (mk_ord_toType <| Module.rank F E).symm).ne'
    /-
      case top
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      hi✝ : Order.IsSuccPrelimit Top.top
      hi : Not (Nonempty ↑(Set.Iio Top.top))
      this : Nonempty (Module.rank F E).ord.toType
      ⊢ Eq (Field.Emb.Cardinal.filtration Top.top) Bot.bot
    -/
    rw [← range_coe] at hi; exact (hi inferInstance).elim
                            /-
                              🎉 no goals
                            -/
    /-
      case coe
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      a✝ : (Module.rank F E).ord.toType
      hi✝ : Order.IsSuccPrelimit ↑a✝
      hi : Not (Nonempty ↑(Set.Iio ↑a✝))
      ⊢ Eq (Field.Emb.Cardinal.filtration ↑a✝) Bot.bot
    -/
  · exact bot_unique <| adjoin_le_iff.mpr fun _ ⟨j, hj, _⟩ ↦ (hi ⟨j, coe_lt_coe.mpr hj⟩).elim
    /-
      🎉 no goals
    -/


open Classical in
/-- If `i` is a limit, the type of embeddings of `E⟮<i⟯` into `Ē` is
the limit of the types of embeddings of `E⟮<j⟯` for `j < i`. -/
def equivLim : (E⟮<i⟯ →ₐ[F] Ē) ≃ limit (embFunctor F E) i where
  toFun f := ⟨fun j ↦ embFunctor _ _ (id j.2 : j < i).le f, fun _ _ _ ↦ rfl⟩
  invFun f := if h : Nonempty (Iio i) then
    Subalgebra.iSupLift _ directed_filtration f.1
      (fun _ _ h ↦ (f.2 <| filtration.map_rel_iff.mp h).symm) _ <| by
        /-
          F : Type u
          E : Type v
          inst✝³ : Field F
          inst✝² : Field E
          inst✝¹ : Algebra F E
          rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
          inst✝ : Algebra.IsAlgebraic F E
          i : WithTop (Module.rank F E).ord.toType
          hi : Order.IsSuccPrelimit i
          f : ↑(InverseSystem.limit (Field.Emb.Cardinal.embFunctor F E) i)
          h : Nonempty ↑(Set.Iio i)
          ⊢ Eq (Field.Emb.Cardinal.filtration i).toSubalgebra (iSup fun x => ((fun j =>  …
        -/
        rw [← iSup_filtration hi, toSubalgebra_iSup_of_directed directed_filtration]
        /-
          🎉 no goals
        -/
    else (Algebra.ofId F Ē).comp ((equivOfEq (eq_bot_of_not_nonempty hi h)).trans <| botEquiv F E)
  left_inv f := by
    /-
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : WithTop (Module.rank F E).ord.toType
      hi : Order.IsSuccPrelimit i
      f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
      ⊢ Eq ((fun f => dite (Nonempty ↑(Set.Iio i)) (fun h => Subalgebra.iSupLift (fu …
    -/
    split_ifs with h
      /-
        case pos
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        hi : Order.IsSuccPrelimit i
        f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
        h : Nonempty ↑(Set.Iio i)
        ⊢ Eq ((fun f => Subalgebra.iSupLift (fun x => ((fun j => Field.Emb.Cardinal.fi …
      -/
    · ext ⟨x, hx⟩
      rw [← iSup_filtration hi, mem_toSubalgebra, ← SetLike.mem_coe,
          coe_iSup_of_directed directed_filtration, mem_iUnion] at hx
      /-
        case pos.H.mk
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        hi : Order.IsSuccPrelimit i
        f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
        h : Nonempty ↑(Set.Iio i)
        x : E
        hx✝ : Membership.mem (Field.Emb.Cardinal.filtration i).toSubalgebra x
        hx : Exists fun i_1 => Membership.mem (↑(Field.Emb.Cardinal.filtration ↑i_1)) x
        ⊢ Eq (((fun f => Subalgebra.iSupLift (fun x => ((fun j => Field.Emb.Cardinal.f …
      -/
      rw [Subalgebra.iSupLift_of_mem _ _ (by exact hx.choose_spec)]; rfl
                                                                     /-
                                                                       🎉 no goals
                                                                     -/
      /-
        case neg
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        hi : Order.IsSuccPrelimit i
        f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
        h : Not (Nonempty ↑(Set.Iio i))
        ⊢ Eq ((fun f => (Algebra.ofId F (AlgebraicClosure E)).comp ↑((IntermediateFiel …
      -/
    · apply AlgHom.ext
      /-
        case neg.H
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        hi : Order.IsSuccPrelimit i
        f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
        h : Not (Nonempty ↑(Set.Iio i))
        ⊢ ∀ (x : Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i) x), …
      -/
      rw [((equivOfEq (eq_bot_of_not_nonempty hi h)).trans <| botEquiv F E).forall_congr_left]
      /-
        case neg.H
        F : Type u
        E : Type v
        inst✝³ : Field F
        inst✝² : Field E
        inst✝¹ : Algebra F E
        rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
        inst✝ : Algebra.IsAlgebraic F E
        i : WithTop (Module.rank F E).ord.toType
        hi : Order.IsSuccPrelimit i
        f : AlgHom F (Subtype fun x => Membership.mem (Field.Emb.Cardinal.filtration i …
        h : Not (Nonempty ↑(Set.Iio i))
        ⊢ ∀ («b» : F), Eq (((fun f => (Algebra.ofId F (AlgebraicClosure E)).comp ↑((In …
      -/
      simp
      /-
        🎉 no goals
      -/
  right_inv f := Subtype.ext <| funext fun j ↦ by
    /-
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : WithTop (Module.rank F E).ord.toType
      hi : Order.IsSuccPrelimit i
      f : ↑(InverseSystem.limit (Field.Emb.Cardinal.embFunctor F E) i)
      j : ↑(Set.Iio i)
      ⊢ Eq (↑((fun f => ⟨fun j => Field.Emb.Cardinal.embFunctor F E ⋯ f, ⋯⟩) ((fun f …
    -/
    have := Nonempty.intro j
    /-
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : WithTop (Module.rank F E).ord.toType
      hi : Order.IsSuccPrelimit i
      f : ↑(InverseSystem.limit (Field.Emb.Cardinal.embFunctor F E) i)
      j : ↑(Set.Iio i)
      this : Nonempty ↑(Set.Iio i)
      ⊢ Eq (↑((fun f => ⟨fun j => Field.Emb.Cardinal.embFunctor F E ⋯ f, ⋯⟩) ((fun f …
    -/
    simp_rw [dif_pos this]
    /-
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      rank_inf : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      inst✝ : Algebra.IsAlgebraic F E
      i : WithTop (Module.rank F E).ord.toType
      hi : Order.IsSuccPrelimit i
      f : ↑(InverseSystem.limit (Field.Emb.Cardinal.embFunctor F E) i)
      j : ↑(Set.Iio i)
      this : Nonempty ↑(Set.Iio i)
      ⊢ Eq (Field.Emb.Cardinal.embFunctor F E ⋯ (Subalgebra.iSupLift (fun x => (Fiel …
    -/
    apply Subalgebra.iSupLift_comp_inclusion
    /-
      🎉 no goals
    -/


theorem equivLim_coherence (x l) : (equivLim hi x).1 l = embFunctor F E (mem_Iio.mp l.2).le x :=
  rfl


/-- A bijection between `E →ₐ[F] Ē` and the product of `E⟮<i⁺⟯ →ₐ[E⟮<i⟯] Ē` over all `i : ι`. -/
def embEquivPi : Field.Emb F E ≃ ∀ i : ι, factor (F := F) (E := E) i :=
  let e := globalEquiv
    (fun i _ ↦ ⟨_, equivSucc_coherence i⟩) (fun _ hi ↦ ⟨equivLim hi, fun _ _ ↦ rfl⟩) ⊤
  (topEquiv.arrowCongr .refl).symm.trans <| e.trans <| .trans (.piCongrSet WithTop.range_coe.symm)
    <| .symm <| .piCongr (.ofInjective _ WithTop.coe_injective) fun _ ↦ .refl _


theorem cardinal_eq_two_pow_rank [Algebra.IsSeparable F E]
    (rank_inf : ℵ₀ ≤ Module.rank F E) : #(Field.Emb F E) = 2 ^ Module.rank F E := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsSeparable F E
    rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) (HPow.hPow 2 (Module.rank F E))
  -/
  haveI := Fact.mk rank_inf
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsSeparable F E
    rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
    this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) (HPow.hPow 2 (Module.rank F E))
  -/
  rw [Emb.Cardinal.embEquivPi.cardinal_eq, mk_pi]
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsSeparable F E
    rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
    this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
    ⊢ Eq (Cardinal.prod fun i => Cardinal.mk (Field.Emb.Cardinal.factor ↑i)) (HPow …
  -/
  apply le_antisymm
    /-
      case a
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
      this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      ⊢ LE.le (Cardinal.prod fun i => Cardinal.mk (Field.Emb.Cardinal.factor ↑i)) (H …
    -/
  · rw [← power_eq_two_power rank_inf (nat_lt_aleph0 2).le rank_inf]
    /-
      case a
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
      this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      ⊢ LE.le (Cardinal.prod fun i => Cardinal.mk (Field.Emb.Cardinal.factor ↑i)) (H …
    -/
    conv_rhs => rw [← mk_ord_toType (Module.rank F E), ← prod_const']
    /-
      case a
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
      this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      ⊢ LE.le (Cardinal.prod fun i => Cardinal.mk (Field.Emb.Cardinal.factor ↑i)) (C …
    -/
    exact prod_le_prod _ _ fun i ↦ (Emb.Cardinal.deg_lt_aleph0 _).le
    /-
      🎉 no goals
    -/
    /-
      case a
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
      this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      ⊢ LE.le (HPow.hPow 2 (Module.rank F E)) (Cardinal.prod fun i => Cardinal.mk (F …
    -/
  · conv_lhs => rw [← mk_ord_toType (Module.rank F E), ← prod_const']
    /-
      case a
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      rank_inf : LE.le Cardinal.aleph0 (Module.rank F E)
      this : Fact (LE.le Cardinal.aleph0 (Module.rank F E))
      ⊢ LE.le (Cardinal.prod fun x => 2) (Cardinal.prod fun i => Cardinal.mk (Field. …
    -/
    exact prod_le_prod _ _ Emb.Cardinal.two_le_deg
    /-
      🎉 no goals
    -/


theorem cardinal_eq_of_isSeparable [Algebra.IsSeparable F E] :
    #(Field.Emb F E) = (fun c ↦ if ℵ₀ ≤ c then 2 ^ c else c) (Module.rank F E) := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsSeparable F E
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) ((fun c => ite (LE.le Cardinal.aleph0 c) (H …
  -/
  dsimp only; split_ifs with h
    /-
      case pos
      F : Type u
      E : Type v
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Algebra.IsSeparable F E
      h : LE.le Cardinal.aleph0 (Module.rank F E)
      ⊢ Eq (Cardinal.mk (Field.Emb F E)) (HPow.hPow 2 (Module.rank F E))
    -/
  · exact cardinal_eq_two_pow_rank h
    /-
      🎉 no goals
    -/
  /-
    case neg
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsSeparable F E
    h : Not (LE.le Cardinal.aleph0 (Module.rank F E))
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) (Module.rank F E)
  -/
  rw [not_le, ← IsNoetherian.iff_rank_lt_aleph0] at h
  rw [← Module.finrank_eq_rank, ← toNat_eq_iff Module.finrank_pos.ne',
    ← Nat.card, ← finSepDegree, finSepDegree_eq_finrank_of_isSeparable]


theorem cardinal_eq_two_pow_sepDegree [Algebra.IsAlgebraic F E]
    (rank_inf : ℵ₀ ≤ sepDegree F E) : #(Field.Emb F E) = 2 ^ sepDegree F E := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    rank_inf : LE.le Cardinal.aleph0 (Field.sepDegree F E)
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) (HPow.hPow 2 (Field.sepDegree F E))
  -/
  rw [← cardinal_separableClosure, cardinal_eq_two_pow_rank rank_inf]
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    rank_inf : LE.le Cardinal.aleph0 (Field.sepDegree F E)
    ⊢ Eq (HPow.hPow 2 (Module.rank F (Subtype fun x => Membership.mem (separableCl …
  -/
  rfl
  /-
    🎉 no goals
  -/


theorem cardinal_eq [Algebra.IsAlgebraic F E] :
    #(Field.Emb F E) = (fun c ↦ if ℵ₀ ≤ c then 2 ^ c else c) (sepDegree F E) := by
  /-
    F : Type u
    E : Type v
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    ⊢ Eq (Cardinal.mk (Field.Emb F E)) ((fun c => ite (LE.le Cardinal.aleph0 c) (H …
  -/
  rw [← cardinal_separableClosure, cardinal_eq_of_isSeparable]; rfl
                                                                /-
                                                                  🎉 no goals
                                                                -/


