/-- **Primitive element theorem** assuming E is finite. -/
@[stacks 09HY "second part"]
theorem exists_primitive_element_of_finite_top [Finite E] : ∃ α : E, F⟮α⟯ = ⊤ := by
  /-
    F : Type u_1
    inst✝³ : Field F
    E : Type u_2
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite E
    ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
  -/
  obtain ⟨α, hα⟩ := @IsCyclic.exists_generator Eˣ _ _
  /-
    case intro
    F : Type u_1
    inst✝³ : Field F
    E : Type u_2
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite E
    α : Units E
    hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
    ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
  -/
  use α
  /-
    case h
    F : Type u_1
    inst✝³ : Field F
    E : Type u_2
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite E
    α : Units E
    hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
    ⊢ Eq (IntermediateField.adjoin F (Singleton.singleton ↑α)) Top.top
  -/
  rw [eq_top_iff]
  /-
    case h
    F : Type u_1
    inst✝³ : Field F
    E : Type u_2
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite E
    α : Units E
    hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
    ⊢ LE.le Top.top (IntermediateField.adjoin F (Singleton.singleton ↑α))
  -/
  rintro x -
  /-
    case h
    F : Type u_1
    inst✝³ : Field F
    E : Type u_2
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite E
    α : Units E
    hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
    x : E
    ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) x
  -/
  by_cases hx : x = 0
    /-
      case pos
      F : Type u_1
      inst✝³ : Field F
      E : Type u_2
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite E
      α : Units E
      hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
      x : E
      hx : Eq x 0
      ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) x
    -/
  · rw [hx]
    /-
      case pos
      F : Type u_1
      inst✝³ : Field F
      E : Type u_2
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite E
      α : Units E
      hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
      x : E
      hx : Eq x 0
      ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) 0
    -/
    exact F⟮α.val⟯.zero_mem
    /-
      🎉 no goals
    -/
    /-
      case neg
      F : Type u_1
      inst✝³ : Field F
      E : Type u_2
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite E
      α : Units E
      hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
      x : E
      hx : Not (Eq x 0)
      ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) x
    -/
  · obtain ⟨n, hn⟩ := Set.mem_range.mp (hα (Units.mk0 x hx))
    /-
      case neg.intro
      F : Type u_1
      inst✝³ : Field F
      E : Type u_2
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite E
      α : Units E
      hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
      x : E
      hx : Not (Eq x 0)
      n : Int
      hn : Eq (HPow.hPow α n) (Units.mk0 x hx)
      ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) x
    -/
    rw [show x = α ^ n by norm_cast; rw [hn, Units.val_mk0]]
    /-
      case neg.intro
      F : Type u_1
      inst✝³ : Field F
      E : Type u_2
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite E
      α : Units E
      hα : ∀ (x : Units E), Membership.mem (Subgroup.zpowers α) x
      x : E
      hx : Not (Eq x 0)
      n : Int
      hn : Eq (HPow.hPow α n) (Units.mk0 x hx)
      ⊢ Membership.mem (IntermediateField.adjoin F (Singleton.singleton ↑α)) (HPow.h …
    -/
    exact zpow_mem (mem_adjoin_simple_self F (E := E) ↑α) n
    /-
      🎉 no goals
    -/


/-- Primitive element theorem for finite dimensional extension of a finite field. -/
theorem exists_primitive_element_of_finite_bot [Finite F] [FiniteDimensional F E] :
    ∃ α : E, F⟮α⟯ = ⊤ :=
  haveI : Finite E := Module.finite_of_finite F
  exists_primitive_element_of_finite_top F E


theorem primitive_element_inf_aux_exists_c (f g : F[X]) :
    ∃ c : F, ∀ α' ∈ (f.map ϕ).roots, ∀ β' ∈ (g.map ϕ).roots, -(α' - α) / (β' - β) ≠ ϕ c := by
  classical
  let sf := (f.map ϕ).roots
  let sg := (g.map ϕ).roots
  classical
  let s := (sf.bind fun α' => sg.map fun β' => -(α' - α) / (β' - β)).toFinset
  let s' := s.preimage ϕ fun x _ y _ h => ϕ.injective h
  obtain ⟨c, hc⟩ := Infinite.exists_not_mem_finset s'
  simp_rw [s', s, Finset.mem_preimage, Multiset.mem_toFinset, Multiset.mem_bind, Multiset.mem_map]
    at hc
  push_neg at hc
  exact ⟨c, hc⟩


/-- This is the heart of the proof of the primitive element theorem. It shows that if `F` is
infinite and `α` and `β` are separable over `F` then `F⟮α, β⟯` is generated by a single element. -/
theorem primitive_element_inf_aux [Algebra.IsSeparable F E] : ∃ γ : E, F⟮α, β⟯ = F⟮γ⟯ := by
  classical
  have hα := Algebra.IsSeparable.isIntegral F α
  have hβ := Algebra.IsSeparable.isIntegral F β
  let f := minpoly F α
  let g := minpoly F β
  let ιFE := algebraMap F E
  let ιEE' := algebraMap E (SplittingField (g.map ιFE))
  obtain ⟨c, hc⟩ := primitive_element_inf_aux_exists_c (ιEE'.comp ιFE) (ιEE' α) (ιEE' β) f g
  let γ := α + c • β
  suffices β_in_Fγ : β ∈ F⟮γ⟯ by
    use γ
    apply le_antisymm
    · rw [adjoin_le_iff]
      have α_in_Fγ : α ∈ F⟮γ⟯ := by
        rw [← add_sub_cancel_right α (c • β)]
        exact F⟮γ⟯.sub_mem (mem_adjoin_simple_self F γ) (F⟮γ⟯.toSubalgebra.smul_mem β_in_Fγ c)
      rintro x (rfl | rfl) <;> assumption
    · rw [adjoin_simple_le_iff]
      have α_in_Fαβ : α ∈ F⟮α, β⟯ := subset_adjoin F {α, β} (Set.mem_insert α {β})
      have β_in_Fαβ : β ∈ F⟮α, β⟯ := subset_adjoin F {α, β} (Set.mem_insert_of_mem α rfl)
      exact F⟮α, β⟯.add_mem α_in_Fαβ (F⟮α, β⟯.smul_mem β_in_Fαβ)
  classical
  let p := EuclideanDomain.gcd ((f.map (algebraMap F F⟮γ⟯)).comp
    (C (AdjoinSimple.gen F γ) - (C ↑c : F⟮γ⟯[X]) * X)) (g.map (algebraMap F F⟮γ⟯))
  let h := EuclideanDomain.gcd ((f.map ιFE).comp (C γ - C (ιFE c) * X)) (g.map ιFE)
  have map_g_ne_zero : g.map ιFE ≠ 0 := map_ne_zero (minpoly.ne_zero hβ)
  have h_ne_zero : h ≠ 0 :=
    mt EuclideanDomain.gcd_eq_zero_iff.mp (not_and.mpr fun _ => map_g_ne_zero)
  suffices p_linear : p.map (algebraMap F⟮γ⟯ E) = C h.leadingCoeff * (X - C β) by
    have finale : β = algebraMap F⟮γ⟯ E (-p.coeff 0 / p.coeff 1) := by
      rw [map_div₀, RingHom.map_neg, ← coeff_map, ← coeff_map, p_linear]
      -- Porting note: had to add `-map_add` to avoid going in the wrong direction.
      simp [mul_sub, coeff_C, mul_div_cancel_left₀ β (mt leadingCoeff_eq_zero.mp h_ne_zero),
        -map_add]
      -- Porting note: an alternative solution is:
      -- simp_rw [Polynomial.coeff_C_mul, Polynomial.coeff_sub, mul_sub,
      --   Polynomial.coeff_X_zero, Polynomial.coeff_X_one, mul_zero, mul_one, zero_sub, neg_neg,
      --   Polynomial.coeff_C, eq_self_iff_true, Nat.one_ne_zero, if_true, if_false, mul_zero,
      --   sub_zero, mul_div_cancel_left β (mt leadingCoeff_eq_zero.mp h_ne_zero)]
    rw [finale]
    exact Subtype.mem (-p.coeff 0 / p.coeff 1)
  have h_sep : h.Separable := separable_gcd_right _ (Algebra.IsSeparable.isSeparable F β).map
  have h_root : h.eval β = 0 := by
    apply eval_gcd_eq_zero
    · rw [eval_comp, eval_sub, eval_mul, eval_C, eval_C, eval_X, eval_map, ← aeval_def, ←
        Algebra.smul_def, add_sub_cancel_right, minpoly.aeval]
    · rw [eval_map, ← aeval_def, minpoly.aeval]
  have h_splits : Splits ιEE' h :=
    splits_of_splits_gcd_right ιEE' map_g_ne_zero (SplittingField.splits _)
  have h_roots : ∀ x ∈ (h.map ιEE').roots, x = ιEE' β := by
    intro x hx
    rw [mem_roots_map h_ne_zero] at hx
    specialize hc (ιEE' γ - ιEE' (ιFE c) * x) (by
      have f_root := root_left_of_root_gcd hx
      rw [eval₂_comp, eval₂_sub, eval₂_mul, eval₂_C, eval₂_C, eval₂_X, eval₂_map] at f_root
      exact (mem_roots_map (minpoly.ne_zero hα)).mpr f_root)
    specialize hc x (by
      rw [mem_roots_map (minpoly.ne_zero hβ), ← eval₂_map]
      exact root_right_of_root_gcd hx)
    by_contra a
    apply hc
    apply (div_eq_iff (sub_ne_zero.mpr a)).mpr
    simp only [γ, Algebra.smul_def, RingHom.map_add, RingHom.map_mul, RingHom.comp_apply]
    ring
  rw [← eq_X_sub_C_of_separable_of_root_eq h_sep h_root h_splits h_roots]
  trans EuclideanDomain.gcd (?_ : E[X]) (?_ : E[X])
  · dsimp only [γ]
    convert (gcd_map (algebraMap F⟮γ⟯ E)).symm
  · simp only [map_comp, Polynomial.map_map, ← IsScalarTower.algebraMap_eq, Polynomial.map_sub,
      map_C, AdjoinSimple.algebraMap_gen, map_add, Polynomial.map_mul, map_X]
    congr

-- If `F` is infinite and `E/F` has only finitely many intermediate fields, then for any
-- `α` and `β` in `E`, `F⟮α, β⟯` is generated by a single element.
-- Marked as private since it's a special case of
-- `exists_primitive_element_of_finite_intermediateField`.

private theorem primitive_element_inf_aux_of_finite_intermediateField
    [Finite (IntermediateField F E)] : ∃ γ : E, F⟮α, β⟯ = F⟮γ⟯ := by
  /-
    F : Type u_1
    inst✝⁴ : Field F
    inst✝³ : Infinite F
    E : Type u_2
    inst✝² : Field E
    α β : E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    ⊢ Exists fun γ => Eq (IntermediateField.adjoin F (Insert.insert α (Singleton.s …
  -/
  let f : F → IntermediateField F E := fun x ↦ F⟮α + x • β⟯
  /-
    F : Type u_1
    inst✝⁴ : Field F
    inst✝³ : Infinite F
    E : Type u_2
    inst✝² : Field E
    α β : E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
    ⊢ Exists fun γ => Eq (IntermediateField.adjoin F (Insert.insert α (Singleton.s …
  -/
  obtain ⟨x, y, hneq, heq⟩ := Finite.exists_ne_map_eq_of_infinite f
  /-
    case intro.intro.intro
    F : Type u_1
    inst✝⁴ : Field F
    inst✝³ : Infinite F
    E : Type u_2
    inst✝² : Field E
    α β : E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
    x y : F
    hneq : Ne x y
    heq : Eq (f x) (f y)
    ⊢ Exists fun γ => Eq (IntermediateField.adjoin F (Insert.insert α (Singleton.s …
  -/
  use α + x • β
  /-
    case h
    F : Type u_1
    inst✝⁴ : Field F
    inst✝³ : Infinite F
    E : Type u_2
    inst✝² : Field E
    α β : E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
    x y : F
    hneq : Ne x y
    heq : Eq (f x) (f y)
    ⊢ Eq (IntermediateField.adjoin F (Insert.insert α (Singleton.singleton β))) (I …
  -/
  apply le_antisymm
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      ⊢ LE.le (IntermediateField.adjoin F (Insert.insert α (Singleton.singleton β))) …
    -/
  · rw [adjoin_le_iff]
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    have αxβ_in_K : α + x • β ∈ F⟮α + x • β⟯ := mem_adjoin_simple_self F _
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    have αyβ_in_K : α + y • β ∈ F⟮α + y • β⟯ := mem_adjoin_simple_self F _
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    dsimp [f] at *
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    simp only [← heq] at αyβ_in_K
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    have β_in_K := sub_mem αxβ_in_K αyβ_in_K
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      β_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HAdd …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    rw [show (α + x • β) - (α + y • β) = (x - y) • β by rw [sub_smul]; abel1] at β_in_K
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      β_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HAdd …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    replace β_in_K := smul_mem _ β_in_K (x := (x - y)⁻¹)
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      β_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HAdd …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
    rw [smul_smul, inv_mul_eq_div, div_self (sub_ne_zero.2 hneq), one_smul] at β_in_K
    have α_in_K : α ∈ F⟮α + x • β⟯ := by
      convert ← sub_mem αxβ_in_K (smul_mem _ β_in_K)
      apply add_sub_cancel_right
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Not (Eq x y)
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul. …
      αxβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      αyβ_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HA …
      β_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HAdd …
      α_in_K : Membership.mem (IntermediateField.adjoin F (Singleton.singleton (HAdd …
      ⊢ HasSubset.Subset (Insert.insert α (Singleton.singleton β)) ↑(IntermediateFie …
    -/
                             /-
                               🎉 no goals
                             -/
    rintro x (rfl | rfl) <;> assumption
                             /-
                               🎉 no goals
                             -/
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      ⊢ LE.le (IntermediateField.adjoin F (Singleton.singleton (HAdd.hAdd α (HSMul.h …
    -/
  · rw [adjoin_simple_le_iff]
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      ⊢ Membership.mem (IntermediateField.adjoin F (Insert.insert α (Singleton.singl …
    -/
    have α_in_Fαβ : α ∈ F⟮α, β⟯ := subset_adjoin F {α, β} (Set.mem_insert α {β})
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      α_in_Fαβ : Membership.mem (IntermediateField.adjoin F (Insert.insert α (Single …
      ⊢ Membership.mem (IntermediateField.adjoin F (Insert.insert α (Singleton.singl …
    -/
    have β_in_Fαβ : β ∈ F⟮α, β⟯ := subset_adjoin F {α, β} (Set.mem_insert_of_mem α rfl)
    /-
      case h.a
      F : Type u_1
      inst✝⁴ : Field F
      inst✝³ : Infinite F
      E : Type u_2
      inst✝² : Field E
      α β : E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      f : F → IntermediateField F E := fun x => IntermediateField.adjoin F (Singleto …
      x y : F
      hneq : Ne x y
      heq : Eq (f x) (f y)
      α_in_Fαβ : Membership.mem (IntermediateField.adjoin F (Insert.insert α (Single …
      β_in_Fαβ : Membership.mem (IntermediateField.adjoin F (Insert.insert α (Single …
      ⊢ Membership.mem (IntermediateField.adjoin F (Insert.insert α (Singleton.singl …
    -/
    exact F⟮α, β⟯.add_mem α_in_Fαβ (F⟮α, β⟯.smul_mem β_in_Fαβ)
    /-
      🎉 no goals
    -/


/-- **Primitive element theorem**: a finite separable field extension `E` of `F` has a
  primitive element, i.e. there is an `α ∈ E` such that `F⟮α⟯ = (⊤ : Subalgebra F E)`. -/
@[stacks 030N "The moreover part"]
theorem exists_primitive_element : ∃ α : E, F⟮α⟯ = ⊤ := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝⁴ : Field F
    inst✝³ : Field E
    inst✝² : Algebra F E
    inst✝¹ : FiniteDimensional F E
    inst✝ : Algebra.IsSeparable F E
    ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
  -/
  rcases isEmpty_or_nonempty (Fintype F) with (F_inf | ⟨⟨F_finite⟩⟩)
    /-
      case inl
      F : Type u_1
      E : Type u_2
      inst✝⁴ : Field F
      inst✝³ : Field E
      inst✝² : Algebra F E
      inst✝¹ : FiniteDimensional F E
      inst✝ : Algebra.IsSeparable F E
      F_inf : IsEmpty (Fintype F)
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
    -/
  · let P : IntermediateField F E → Prop := fun K => ∃ α : E, F⟮α⟯ = K
    /-
      case inl
      F : Type u_1
      E : Type u_2
      inst✝⁴ : Field F
      inst✝³ : Field E
      inst✝² : Algebra F E
      inst✝¹ : FiniteDimensional F E
      inst✝ : Algebra.IsSeparable F E
      F_inf : IsEmpty (Fintype F)
      P : IntermediateField F E → Prop := fun K => Exists fun α => Eq (IntermediateF …
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
    -/
    have base : P ⊥ := ⟨0, adjoin_zero⟩
    have ih : ∀ (K : IntermediateField F E) (x : E), P K → P (K⟮x⟯.restrictScalars F) := by
      intro K β hK
      cases' hK with α hK
      rw [← hK, adjoin_simple_adjoin_simple]
      haveI : Infinite F := isEmpty_fintype.mp F_inf
      cases' primitive_element_inf_aux F α β with γ hγ
      exact ⟨γ, hγ.symm⟩
    /-
      case inl
      F : Type u_1
      E : Type u_2
      inst✝⁴ : Field F
      inst✝³ : Field E
      inst✝² : Algebra F E
      inst✝¹ : FiniteDimensional F E
      inst✝ : Algebra.IsSeparable F E
      F_inf : IsEmpty (Fintype F)
      P : IntermediateField F E → Prop := fun K => Exists fun α => Eq (IntermediateF …
      base : P Bot.bot
      ih : ∀ (K : IntermediateField F E) (x : E), P K → P (IntermediateField.restric …
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
    -/
    exact induction_on_adjoin P base ih ⊤
    /-
      🎉 no goals
    -/
    /-
      case inr.intro
      F : Type u_1
      E : Type u_2
      inst✝⁴ : Field F
      inst✝³ : Field E
      inst✝² : Algebra F E
      inst✝¹ : FiniteDimensional F E
      inst✝ : Algebra.IsSeparable F E
      F_finite : Fintype F
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top. …
    -/
  · exact exists_primitive_element_of_finite_bot F E
    /-
      🎉 no goals
    -/


/-- Alternative phrasing of primitive element theorem:
a finite separable field extension has a basis `1, α, α^2, ..., α^n`.

See also `exists_primitive_element`. -/
noncomputable def powerBasisOfFiniteOfSeparable : PowerBasis F E :=
  let α := (exists_primitive_element F E).choose
  let pb := adjoin.powerBasis (Algebra.IsSeparable.isIntegral F α)
  have e : F⟮α⟯ = ⊤ := (exists_primitive_element F E).choose_spec
  pb.map ((IntermediateField.equivOfEq e).trans IntermediateField.topEquiv)


theorem isAlgebraic_of_adjoin_eq_adjoin {α : E} {m n : ℕ} (hneq : m ≠ n)
    (heq : F⟮α ^ m⟯ = F⟮α ^ n⟯) : IsAlgebraic F α := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    ⊢ IsAlgebraic F α
  -/
  wlog hmn : m < n
    /-
      case inr
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      this : ∀ (F : Type u_1) (E : Type u_2) [inst : Field F] [inst_1 : Field E] [in …
      hmn : Not (LT.lt m n)
      ⊢ IsAlgebraic F α
    -/
  · exact this F E hneq.symm heq.symm (hneq.lt_or_lt.resolve_left hmn)
    /-
      🎉 no goals
    -/
  /-
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    ⊢ IsAlgebraic F α
  -/
  by_cases hm : m = 0
    /-
      case pos
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      hm : Eq m 0
      ⊢ IsAlgebraic F α
    -/
  · rw [hm] at heq hmn
    /-
      case pos
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α 0))) (I …
      hmn : LT.lt 0 n
      hm : Eq m 0
      ⊢ IsAlgebraic F α
    -/
    simp only [pow_zero, adjoin_one] at heq
    /-
      case pos
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      hmn : LT.lt 0 n
      hm : Eq m 0
      heq : Eq Bot.bot (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α …
      ⊢ IsAlgebraic F α
    -/
    obtain ⟨y, h⟩ := mem_bot.1 (heq.symm ▸ mem_adjoin_simple_self F (α ^ n))
    /-
      case pos.intro
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      hmn : LT.lt 0 n
      hm : Eq m 0
      heq : Eq Bot.bot (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α …
      y : F
      h : Eq ((algebraMap F E) y) (HPow.hPow α n)
      ⊢ IsAlgebraic F α
    -/
    refine ⟨X ^ n - C y, X_pow_sub_C_ne_zero hmn y, ?_⟩
    /-
      case pos.intro
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      hmn : LT.lt 0 n
      hm : Eq m 0
      heq : Eq Bot.bot (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α …
      y : F
      h : Eq ((algebraMap F E) y) (HPow.hPow α n)
      ⊢ Eq ((Polynomial.aeval α) (HSub.hSub (HPow.hPow Polynomial.X n) (Polynomial.C …
    -/
    simp only [map_sub, map_pow, aeval_X, aeval_C, h, sub_self]
    /-
      🎉 no goals
    -/
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    hm : Not (Eq m 0)
    ⊢ IsAlgebraic F α
  -/
  obtain ⟨r, s, h⟩ := (mem_adjoin_simple_iff F _).1 (heq ▸ mem_adjoin_simple_self F (α ^ m))
  /-
    case neg.intro.intro
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    hm : Not (Eq m 0)
    r s : Polynomial F
    h : Eq (HPow.hPow α m) (HDiv.hDiv ((Polynomial.aeval (HPow.hPow α n)) r) ((Pol …
    ⊢ IsAlgebraic F α
  -/
  by_cases hzero : aeval (α ^ n) s = 0
    /-
      case pos
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      hm : Not (Eq m 0)
      r s : Polynomial F
      h : Eq (HPow.hPow α m) (HDiv.hDiv ((Polynomial.aeval (HPow.hPow α n)) r) ((Pol …
      hzero : Eq ((Polynomial.aeval (HPow.hPow α n)) s) 0
      ⊢ IsAlgebraic F α
    -/
  · simp only [hzero, div_zero, pow_eq_zero_iff hm] at h
    /-
      case pos
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      hm : Not (Eq m 0)
      r s : Polynomial F
      hzero : Eq ((Polynomial.aeval (HPow.hPow α n)) s) 0
      h : Eq α 0
      ⊢ IsAlgebraic F α
    -/
    exact h.symm ▸ isAlgebraic_zero
    /-
      🎉 no goals
    -/
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    hm : Not (Eq m 0)
    r s : Polynomial F
    h : Eq (HPow.hPow α m) (HDiv.hDiv ((Polynomial.aeval (HPow.hPow α n)) r) ((Pol …
    hzero : Not (Eq ((Polynomial.aeval (HPow.hPow α n)) s) 0)
    ⊢ IsAlgebraic F α
  -/
  replace hm : 0 < m := Nat.pos_of_ne_zero hm
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    r s : Polynomial F
    h : Eq (HPow.hPow α m) (HDiv.hDiv ((Polynomial.aeval (HPow.hPow α n)) r) ((Pol …
    hzero : Not (Eq ((Polynomial.aeval (HPow.hPow α n)) s) 0)
    hm : LT.lt 0 m
    ⊢ IsAlgebraic F α
  -/
  rw [eq_div_iff hzero, ← sub_eq_zero] at h
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    r s : Polynomial F
    h : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α n …
    hzero : Not (Eq ((Polynomial.aeval (HPow.hPow α n)) s) 0)
    hm : LT.lt 0 m
    ⊢ IsAlgebraic F α
  -/
  replace hzero : s ≠ 0 := by rintro rfl; simp only [map_zero, not_true_eq_false] at hzero
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    r s : Polynomial F
    h : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α n …
    hm : LT.lt 0 m
    hzero : Ne s 0
    ⊢ IsAlgebraic F α
  -/
  let f : F[X] := X ^ m * expand F n s - expand F n r
  /-
    case neg
    F✝ : Type u_1
    E✝ : Type u_2
    inst✝⁵ : Field F✝
    inst✝⁴ : Field E✝
    inst✝³ : Algebra F✝ E✝
    F : Type u_1
    E : Type u_2
    inst✝² : Field F
    inst✝¹ : Field E
    inst✝ : Algebra F E
    α : E
    m n : Nat
    hneq : Ne m n
    heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
    hmn : LT.lt m n
    r s : Polynomial F
    h : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α n …
    hm : LT.lt 0 m
    hzero : Ne s 0
    f : Polynomial F := HSub.hSub (HMul.hMul (HPow.hPow Polynomial.X m) ((Polynomi …
    ⊢ IsAlgebraic F α
  -/
  refine ⟨f, ?_, ?_⟩
  · have : f.coeff (n * s.natDegree + m) ≠ 0 := by
      have hn : 0 < n := by linarith only [hm, hmn]
      have hndvd : ¬ n ∣ n * s.natDegree + m := by
        rw [← Nat.dvd_add_iff_right (n.dvd_mul_right s.natDegree)]
        exact Nat.not_dvd_of_pos_of_lt hm hmn
      simp only [f, coeff_sub, coeff_X_pow_mul, s.coeff_expand_mul' hn, coeff_natDegree,
        coeff_expand hn r, hndvd, ite_false, sub_zero]
      exact leadingCoeff_ne_zero.2 hzero
    /-
      case neg.refine_1
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      r s : Polynomial F
      h : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α n …
      hm : LT.lt 0 m
      hzero : Ne s 0
      f : Polynomial F := HSub.hSub (HMul.hMul (HPow.hPow Polynomial.X m) ((Polynomi …
      this : Ne (f.coeff (HAdd.hAdd (HMul.hMul n s.natDegree) m)) 0
      ⊢ Ne f 0
    -/
    intro h
    /-
      case neg.refine_1
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      r s : Polynomial F
      h✝ : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α  …
      hm : LT.lt 0 m
      hzero : Ne s 0
      f : Polynomial F := HSub.hSub (HMul.hMul (HPow.hPow Polynomial.X m) ((Polynomi …
      this : Ne (f.coeff (HAdd.hAdd (HMul.hMul n s.natDegree) m)) 0
      h : Eq f 0
      ⊢ False
    -/
    simp only [h, coeff_zero, ne_eq, not_true_eq_false] at this
    /-
      🎉 no goals
    -/
    /-
      case neg.refine_2
      F✝ : Type u_1
      E✝ : Type u_2
      inst✝⁵ : Field F✝
      inst✝⁴ : Field E✝
      inst✝³ : Algebra F✝ E✝
      F : Type u_1
      E : Type u_2
      inst✝² : Field F
      inst✝¹ : Field E
      inst✝ : Algebra F E
      α : E
      m n : Nat
      hneq : Ne m n
      heq : Eq (IntermediateField.adjoin F (Singleton.singleton (HPow.hPow α m))) (I …
      hmn : LT.lt m n
      r s : Polynomial F
      h : Eq (HSub.hSub (HMul.hMul (HPow.hPow α m) ((Polynomial.aeval (HPow.hPow α n …
      hm : LT.lt 0 m
      hzero : Ne s 0
      f : Polynomial F := HSub.hSub (HMul.hMul (HPow.hPow Polynomial.X m) ((Polynomi …
      ⊢ Eq ((Polynomial.aeval α) f) 0
    -/
  · simp only [f, map_sub, map_mul, map_pow, aeval_X, expand_aeval, h]
    /-
      🎉 no goals
    -/


theorem isAlgebraic_of_finite_intermediateField
    [Finite (IntermediateField F E)] : Algebra.IsAlgebraic F E := ⟨fun α ↦
  have ⟨_m, _n, hneq, heq⟩ := Finite.exists_ne_map_eq_of_infinite fun n ↦ F⟮α ^ n⟯
  isAlgebraic_of_adjoin_eq_adjoin F E hneq heq⟩


theorem FiniteDimensional.of_finite_intermediateField
    [Finite (IntermediateField F E)] : FiniteDimensional F E := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    ⊢ FiniteDimensional F E
  -/
  let IF := { K : IntermediateField F E // ∃ x, K = F⟮x⟯ }
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    IF : Type (max 0 u_2) := Subtype fun K => Exists fun x => Eq K (IntermediateFi …
    ⊢ FiniteDimensional F E
  -/
  have := isAlgebraic_of_finite_intermediateField F E
  haveI : ∀ K : IF, FiniteDimensional F K.1 := fun ⟨_, x, rfl⟩ ↦ adjoin.finiteDimensional
    (Algebra.IsIntegral.isIntegral _)
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    IF : Type (max 0 u_2) := Subtype fun K => Exists fun x => Eq K (IntermediateFi …
    this✝ : Algebra.IsAlgebraic F E
    this : ∀ (K : IF), FiniteDimensional F (Subtype fun x => Membership.mem (↑K) x)
    ⊢ FiniteDimensional F E
  -/
  have hfin := finiteDimensional_iSup_of_finite (t := fun K : IF ↦ K.1)
  have htop : ⨆ K : IF, K.1 = ⊤ := le_top.antisymm fun x _ ↦
    le_iSup (fun K : IF ↦ K.1) ⟨F⟮x⟯, x, rfl⟩ <| mem_adjoin_simple_self F x
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    IF : Type (max 0 u_2) := Subtype fun K => Exists fun x => Eq K (IntermediateFi …
    this✝ : Algebra.IsAlgebraic F E
    this : ∀ (K : IF), FiniteDimensional F (Subtype fun x => Membership.mem (↑K) x)
    hfin : FiniteDimensional F (Subtype fun x => Membership.mem (iSup fun i => ↑i) …
    htop : Eq (iSup fun K => ↑K) Top.top
    ⊢ FiniteDimensional F E
  -/
  rw [htop] at hfin
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    IF : Type (max 0 u_2) := Subtype fun K => Exists fun x => Eq K (IntermediateFi …
    this✝ : Algebra.IsAlgebraic F E
    this : ∀ (K : IF), FiniteDimensional F (Subtype fun x => Membership.mem (↑K) x)
    hfin : FiniteDimensional F (Subtype fun x => Membership.mem Top.top x)
    htop : Eq (iSup fun K => ↑K) Top.top
    ⊢ FiniteDimensional F E
  -/
  exact topEquiv.toLinearEquiv.finiteDimensional
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-02-02")]
alias finiteDimensional_of_finite_intermediateField := FiniteDimensional.of_finite_intermediateField


theorem exists_primitive_element_of_finite_intermediateField
    [Finite (IntermediateField F E)] (K : IntermediateField F E) : ∃ α : E, F⟮α⟯ = K := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    K : IntermediateField F E
    ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) K
  -/
  haveI := FiniteDimensional.of_finite_intermediateField F E
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Finite (IntermediateField F E)
    K : IntermediateField F E
    this : FiniteDimensional F E
    ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) K
  -/
  rcases finite_or_infinite F with (_ | _)
    /-
      case inl
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Finite F
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) K
    -/
  · obtain ⟨α, h⟩ := exists_primitive_element_of_finite_bot F K
    /-
      case inl.intro
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Finite F
      α : Subtype fun x => Membership.mem K x
      h : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) K
    -/
    exact ⟨α, by simpa only [lift_adjoin_simple, lift_top] using congr_arg lift h⟩
    /-
      🎉 no goals
    -/
    /-
      case inr
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Infinite F
      ⊢ Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) K
    -/
  · apply induction_on_adjoin (fun K ↦ ∃ α : E, F⟮α⟯ = K) ⟨0, adjoin_zero⟩
    /-
      case inr.ih
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Infinite F
      ⊢ ∀ (K : IntermediateField F E) (x : E), (Exists fun α => Eq (IntermediateFiel …
    -/
    rintro K β ⟨α, rfl⟩
    /-
      case inr.ih.intro
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Infinite F
      β α : E
      ⊢ Exists fun α_1 => Eq (IntermediateField.adjoin F (Singleton.singleton α_1))  …
    -/
    simp_rw [adjoin_simple_adjoin_simple, eq_comm]
    /-
      case inr.ih.intro
      F : Type u_1
      E : Type u_2
      inst✝³ : Field F
      inst✝² : Field E
      inst✝¹ : Algebra F E
      inst✝ : Finite (IntermediateField F E)
      K : IntermediateField F E
      this : FiniteDimensional F E
      h✝ : Infinite F
      β α : E
      ⊢ Exists fun α_1 => Eq (IntermediateField.adjoin F (Insert.insert α (Singleton …
    -/
    exact primitive_element_inf_aux_of_finite_intermediateField F α β
    /-
      🎉 no goals
    -/


theorem FiniteDimensional.of_exists_primitive_element [Algebra.IsAlgebraic F E]
    (h : ∃ α : E, F⟮α⟯ = ⊤) : FiniteDimensional F E := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    h : Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) To …
    ⊢ FiniteDimensional F E
  -/
  obtain ⟨α, hprim⟩ := h
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    ⊢ FiniteDimensional F E
  -/
  have hfin := adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral (R := F) α)
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    hfin : FiniteDimensional F (Subtype fun x => Membership.mem (IntermediateField …
    ⊢ FiniteDimensional F E
  -/
  rw [hprim] at hfin
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    hfin : FiniteDimensional F (Subtype fun x => Membership.mem Top.top x)
    ⊢ FiniteDimensional F E
  -/
  exact topEquiv.toLinearEquiv.finiteDimensional
  /-
    🎉 no goals
  -/


@[deprecated (since := "2024-02-02")]
alias finiteDimensional_of_exists_primitive_element := FiniteDimensional.of_exists_primitive_element

-- A finite simple extension has only finitely many intermediate fields

theorem finite_intermediateField_of_exists_primitive_element [Algebra.IsAlgebraic F E]
    (h : ∃ α : E, F⟮α⟯ = ⊤) : Finite (IntermediateField F E) := by
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    h : Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) To …
    ⊢ Finite (IntermediateField F E)
  -/
  haveI := FiniteDimensional.of_exists_primitive_element F E h
  /-
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    h : Exists fun α => Eq (IntermediateField.adjoin F (Singleton.singleton α)) To …
    this : FiniteDimensional F E
    ⊢ Finite (IntermediateField F E)
  -/
  obtain ⟨α, hprim⟩ := h
  -- Let `f` be the minimal polynomial of `α ∈ E` over `F`
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    this : FiniteDimensional F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    ⊢ Finite (IntermediateField F E)
  -/
  let f : F[X] := minpoly F α
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    this : FiniteDimensional F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    f : Polynomial F := minpoly F α
    ⊢ Finite (IntermediateField F E)
  -/
  let G := { g : E[X] // g.Monic ∧ g ∣ f.map (algebraMap F E) }
  -- Then `f` has only finitely many monic factors
  have hfin : Finite G := @Finite.of_fintype _ <| fintypeSubtypeMonicDvd
    (f.map (algebraMap F E)) <| map_ne_zero (minpoly.ne_zero_of_finite F α)
  -- If `K` is an intermediate field of `E/F`, let `g` be the minimal polynomial of `α` over `K`
  -- which is a monic factor of `f`
  let g : IntermediateField F E → G := fun K ↦
    ⟨(minpoly K α).map (algebraMap K E), (minpoly.monic <| .of_finite K α).map _, by
      convert Polynomial.map_dvd (algebraMap K E) (minpoly.dvd_map_of_isScalarTower F K α)
      rw [Polynomial.map_map]; rfl⟩
  -- The map `K ↦ g` is injective
  have hinj : Function.Injective g := fun K K' heq ↦ by
    rw [Subtype.mk.injEq] at heq
    apply_fun fun f : E[X] ↦ adjoin F (f.coeffs : Set E) at heq
    simpa only [adjoin_minpoly_coeff_of_exists_primitive_element F hprim] using heq
  -- Therefore there are only finitely many intermediate fields
  /-
    case intro
    F : Type u_1
    E : Type u_2
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : Algebra.IsAlgebraic F E
    this : FiniteDimensional F E
    α : E
    hprim : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    f : Polynomial F := minpoly F α
    G : Type (max 0 u_2) := Subtype fun g => And g.Monic (Dvd.dvd g (Polynomial.ma …
    hfin : Finite G
    g : IntermediateField F E → G := fun K => ⟨Polynomial.map (algebraMap (Subtype …
    hinj : Function.Injective g
    ⊢ Finite (IntermediateField F E)
  -/
  exact Finite.of_injective g hinj
  /-
    🎉 no goals
  -/


/-- **Steinitz theorem**: an algebraic extension `E` of `F` has a
  primitive element (i.e. there is an `α ∈ E` such that `F⟮α⟯ = (⊤ : Subalgebra F E)`)
  if and only if there exist only finitely many intermediate fields between `E` and `F`. -/
@[stacks 030N "Equivalence of (1) & (2)"]
theorem exists_primitive_element_iff_finite_intermediateField :
    (Algebra.IsAlgebraic F E ∧ ∃ α : E, F⟮α⟯ = ⊤) ↔ Finite (IntermediateField F E) :=
  ⟨fun ⟨_, h⟩ ↦ finite_intermediateField_of_exists_primitive_element F E h,
    fun _ ↦ ⟨isAlgebraic_of_finite_intermediateField F E,
      exists_primitive_element_of_finite_intermediateField F E _⟩⟩


@[simp]
theorem AlgHom.card_of_splits (L : Type*) [Field L] [Algebra F L]
    (hL : ∀ x : E, (minpoly F x).Splits (algebraMap F L)) :
    Fintype.card (E →ₐ[F] L) = finrank F E := by
  convert (AlgHom.card_of_powerBasis (L := L) (Field.powerBasisOfFiniteOfSeparable F E)
    (Algebra.IsSeparable.isSeparable _ _) <| hL _).trans
      (PowerBasis.finrank _).symm


@[simp]
theorem AlgHom.card (K : Type*) [Field K] [IsAlgClosed K] [Algebra F K] :
    Fintype.card (E →ₐ[F] K) = finrank F E :=
  AlgHom.card_of_splits _ _ _ (fun _ ↦ IsAlgClosed.splits_codomain _)


theorem primitive_element_iff_minpoly_natDegree_eq (α : E) :
    F⟮α⟯ = ⊤ ↔ (minpoly F α).natDegree = finrank F E := by
  /-
    F : Type u_3
    E : Type u_4
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : FiniteDimensional F E
    α : E
    ⊢ Iff (Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top) (Eq (m …
  -/
  rw [← adjoin.finrank (IsIntegral.of_finite F α), ← finrank_top F E]
  /-
    F : Type u_3
    E : Type u_4
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : FiniteDimensional F E
    α : E
    ⊢ Iff (Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top) (Eq (M …
  -/
  refine ⟨fun h => ?_, fun h => eq_of_le_of_finrank_eq le_top h⟩
  /-
    F : Type u_3
    E : Type u_4
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : FiniteDimensional F E
    α : E
    h : Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top
    ⊢ Eq (Module.finrank F (Subtype fun x => Membership.mem (IntermediateField.adj …
  -/
  exact congr_arg (fun K : IntermediateField F E => finrank F K) h
  /-
    🎉 no goals
  -/


theorem primitive_element_iff_minpoly_degree_eq (α : E) :
    F⟮α⟯ = ⊤ ↔ (minpoly F α).degree = finrank F E := by
  /-
    F : Type u_3
    E : Type u_4
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : FiniteDimensional F E
    α : E
    ⊢ Iff (Eq (IntermediateField.adjoin F (Singleton.singleton α)) Top.top) (Eq (m …
  -/
  rw [degree_eq_iff_natDegree_eq, primitive_element_iff_minpoly_natDegree_eq]
  /-
    F : Type u_3
    E : Type u_4
    inst✝³ : Field F
    inst✝² : Field E
    inst✝¹ : Algebra F E
    inst✝ : FiniteDimensional F E
    α : E
    ⊢ Ne (minpoly F α) 0
  -/
  exact minpoly.ne_zero_of_finite F α
  /-
    🎉 no goals
  -/


theorem primitive_element_iff_algHom_eq_of_eval' (α : E) :
    F⟮α⟯ = ⊤ ↔ Function.Injective fun φ : E →ₐ[F] A ↦ φ α := by
  classical
  simp_rw [primitive_element_iff_minpoly_natDegree_eq, ← card_rootSet_eq_natDegree (K := A)
    (Algebra.IsSeparable.isSeparable F α) (hA _), ← toFinset_card,
    ← (Algebra.IsAlgebraic.of_finite F E).range_eval_eq_rootSet_minpoly_of_splits _ hA α,
    ← AlgHom.card_of_splits F E A hA, Fintype.card, toFinset_range, Finset.card_image_iff,
    Finset.coe_univ, ← injective_iff_injOn_univ]


theorem primitive_element_iff_algHom_eq_of_eval (α : E)
    (φ : E →ₐ[F] A) : F⟮α⟯ = ⊤ ↔ ∀ ψ : E →ₐ[F] A, φ α = ψ α → φ = ψ := by
  refine ⟨fun h ψ hψ ↦ (Field.primitive_element_iff_algHom_eq_of_eval' F A hA α).mp h hψ,
    fun h ↦ eq_of_le_of_finrank_eq' le_top ?_⟩
  /-
    F : Type u_3
    E : Type u_4
    inst✝⁶ : Field F
    inst✝⁵ : Field E
    inst✝⁴ : Algebra F E
    inst✝³ : FiniteDimensional F E
    inst✝² : Algebra.IsSeparable F E
    A : Type u_5
    inst✝¹ : Field A
    inst✝ : Algebra F A
    hA : ∀ (x : E), Polynomial.Splits (algebraMap F A) (minpoly F x)
    α : E
    φ : AlgHom F E A
    h : ∀ (ψ : AlgHom F E A), Eq (φ α) (ψ α) → Eq φ ψ
    ⊢ Eq (Module.finrank (Subtype fun x => Membership.mem (IntermediateField.adjoi …
  -/
  letI : Algebra F⟮α⟯ A := (φ.comp F⟮α⟯.val).toAlgebra
  /-
    F : Type u_3
    E : Type u_4
    inst✝⁶ : Field F
    inst✝⁵ : Field E
    inst✝⁴ : Algebra F E
    inst✝³ : FiniteDimensional F E
    inst✝² : Algebra.IsSeparable F E
    A : Type u_5
    inst✝¹ : Field A
    inst✝ : Algebra F A
    hA : ∀ (x : E), Polynomial.Splits (algebraMap F A) (minpoly F x)
    α : E
    φ : AlgHom F E A
    h : ∀ (ψ : AlgHom F E A), Eq (φ α) (ψ α) → Eq φ ψ
    this : Algebra (Subtype fun x => Membership.mem (IntermediateField.adjoin F (S …
    ⊢ Eq (Module.finrank (Subtype fun x => Membership.mem (IntermediateField.adjoi …
  -/
  haveI := Algebra.isSeparable_tower_top_of_isSeparable F F⟮α⟯ E
  /-
    F : Type u_3
    E : Type u_4
    inst✝⁶ : Field F
    inst✝⁵ : Field E
    inst✝⁴ : Algebra F E
    inst✝³ : FiniteDimensional F E
    inst✝² : Algebra.IsSeparable F E
    A : Type u_5
    inst✝¹ : Field A
    inst✝ : Algebra F A
    hA : ∀ (x : E), Polynomial.Splits (algebraMap F A) (minpoly F x)
    α : E
    φ : AlgHom F E A
    h : ∀ (ψ : AlgHom F E A), Eq (φ α) (ψ α) → Eq φ ψ
    this✝ : Algebra (Subtype fun x => Membership.mem (IntermediateField.adjoin F ( …
    this : Algebra.IsSeparable (Subtype fun x => Membership.mem (IntermediateField …
    ⊢ Eq (Module.finrank (Subtype fun x => Membership.mem (IntermediateField.adjoi …
  -/
  rw [IntermediateField.finrank_top, ← AlgHom.card_of_splits _ _ A, Fintype.card_eq_one_iff]
  · exact ⟨{ __ := φ, commutes' := fun _ ↦ rfl }, fun ψ ↦ AlgHom.restrictScalars_injective F <|
      Eq.symm <| h _ (ψ.commutes <| AdjoinSimple.gen F α).symm⟩
    /-
      F : Type u_3
      E : Type u_4
      inst✝⁶ : Field F
      inst✝⁵ : Field E
      inst✝⁴ : Algebra F E
      inst✝³ : FiniteDimensional F E
      inst✝² : Algebra.IsSeparable F E
      A : Type u_5
      inst✝¹ : Field A
      inst✝ : Algebra F A
      hA : ∀ (x : E), Polynomial.Splits (algebraMap F A) (minpoly F x)
      α : E
      φ : AlgHom F E A
      h : ∀ (ψ : AlgHom F E A), Eq (φ α) (ψ α) → Eq φ ψ
      this✝ : Algebra (Subtype fun x => Membership.mem (IntermediateField.adjoin F ( …
      this : Algebra.IsSeparable (Subtype fun x => Membership.mem (IntermediateField …
      ⊢ ∀ (x : E), Polynomial.Splits (algebraMap (Subtype fun x => Membership.mem (I …
    -/
  · exact fun x ↦ (IsIntegral.of_finite F x).minpoly_splits_tower_top (hA x)
    /-
      🎉 no goals
    -/


