/-- `prod C D` gives the cartesian product of two categories.

See <https://stacks.math.columbia.edu/tag/001K>.
-/
@[simps (config := { notRecursive := [] }) Hom id_fst id_snd comp_fst comp_snd]
instance prod : Category.{max v₁ v₂} (C × D) where
  Hom X Y := (X.1 ⟶ Y.1) × (X.2 ⟶ Y.2)
  id X := ⟨𝟙 X.1, 𝟙 X.2⟩
  comp f g := (f.1 ≫ g.1, f.2 ≫ g.2)


@[ext]
lemma prod.hom_ext {X Y : C × D} {f g : X ⟶ Y} (h₁ : f.1 = g.1) (h₂ : f.2 = g.2) : f = g := by
  /-
    C : Type u₁
    inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
    D : Type u₂
    inst✝ : CategoryTheory.Category.{v₂, u₂} D
    X Y : Prod C D
    f g : Quiver.Hom X Y
    h₁ : Eq f.1 g.1
    h₂ : Eq f.2 g.2
    ⊢ Eq f g
  -/
  dsimp
  /-
    C : Type u₁
    inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
    D : Type u₂
    inst✝ : CategoryTheory.Category.{v₂, u₂} D
    X Y : Prod C D
    f g : Quiver.Hom X Y
    h₁ : Eq f.1 g.1
    h₂ : Eq f.2 g.2
    ⊢ Eq f g
  -/
          /-
            🎉 no goals
          -/
  ext <;> assumption
          /-
            🎉 no goals
          -/


/-- Two rfl lemmas that cannot be generated by `@[simps]`. -/
@[simp]
theorem prod_id (X : C) (Y : D) : 𝟙 (X, Y) = (𝟙 X, 𝟙 Y) :=
  rfl


@[simp]
theorem prod_comp {P Q R : C} {S T U : D} (f : (P, S) ⟶ (Q, T)) (g : (Q, T) ⟶ (R, U)) :
    f ≫ g = (f.1 ≫ g.1, f.2 ≫ g.2) :=
  rfl


theorem isIso_prod_iff {P Q : C} {S T : D} {f : (P, S) ⟶ (Q, T)} :
    IsIso f ↔ IsIso f.1 ∧ IsIso f.2 := by
  /-
    C : Type u₁
    inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
    D : Type u₂
    inst✝ : CategoryTheory.Category.{v₂, u₂} D
    P Q : C
    S T : D
    f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
    ⊢ Iff (CategoryTheory.IsIso f) (And (CategoryTheory.IsIso f.1) (CategoryTheory …
  -/
  constructor
    /-
      case mp
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      ⊢ CategoryTheory.IsIso f → And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIs …
    -/
  · rintro ⟨g, hfg, hgf⟩
    /-
      case mp.mk.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g : Quiver.Hom { fst := Q, snd := T } { fst := P, snd := S }
      hfg : Eq (CategoryTheory.CategoryStruct.comp f g) (CategoryTheory.CategoryStru …
      hgf : Eq (CategoryTheory.CategoryStruct.comp g f) (CategoryTheory.CategoryStru …
      ⊢ And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIso f.2)
    -/
    simp? at hfg hgf says simp only [prod_Hom, prod_comp, prod_id, Prod.mk.injEq] at hfg hgf
    /-
      case mp.mk.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g : Quiver.Hom { fst := Q, snd := T } { fst := P, snd := S }
      hfg : And (Eq (CategoryTheory.CategoryStruct.comp f.1 g.1) (CategoryTheory.Cat …
      hgf : And (Eq (CategoryTheory.CategoryStruct.comp g.1 f.1) (CategoryTheory.Cat …
      ⊢ And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIso f.2)
    -/
    rcases hfg with ⟨hfg₁, hfg₂⟩
    /-
      case mp.mk.intro.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g : Quiver.Hom { fst := Q, snd := T } { fst := P, snd := S }
      hgf : And (Eq (CategoryTheory.CategoryStruct.comp g.1 f.1) (CategoryTheory.Cat …
      hfg₁ : Eq (CategoryTheory.CategoryStruct.comp f.1 g.1) (CategoryTheory.Categor …
      hfg₂ : Eq (CategoryTheory.CategoryStruct.comp f.2 g.2) (CategoryTheory.Categor …
      ⊢ And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIso f.2)
    -/
    rcases hgf with ⟨hgf₁, hgf₂⟩
    /-
      case mp.mk.intro.intro.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g : Quiver.Hom { fst := Q, snd := T } { fst := P, snd := S }
      hfg₁ : Eq (CategoryTheory.CategoryStruct.comp f.1 g.1) (CategoryTheory.Categor …
      hfg₂ : Eq (CategoryTheory.CategoryStruct.comp f.2 g.2) (CategoryTheory.Categor …
      hgf₁ : Eq (CategoryTheory.CategoryStruct.comp g.1 f.1) (CategoryTheory.Categor …
      hgf₂ : Eq (CategoryTheory.CategoryStruct.comp g.2 f.2) (CategoryTheory.Categor …
      ⊢ And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIso f.2)
    -/
    exact ⟨⟨⟨g.1, hfg₁, hgf₁⟩⟩, ⟨⟨g.2, hfg₂, hgf₂⟩⟩⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      ⊢ And (CategoryTheory.IsIso f.1) (CategoryTheory.IsIso f.2) → CategoryTheory.I …
    -/
  · rintro ⟨⟨g₁, hfg₁, hgf₁⟩, ⟨g₂, hfg₂, hgf₂⟩⟩
    /-
      case mpr.intro.mk.intro.intro.mk.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g₁ : Quiver.Hom { fst := Q, snd := T }.1 { fst := P, snd := S }.1
      hfg₁ : Eq (CategoryTheory.CategoryStruct.comp f.1 g₁) (CategoryTheory.Category …
      hgf₁ : Eq (CategoryTheory.CategoryStruct.comp g₁ f.1) (CategoryTheory.Category …
      g₂ : Quiver.Hom { fst := Q, snd := T }.2 { fst := P, snd := S }.2
      hfg₂ : Eq (CategoryTheory.CategoryStruct.comp f.2 g₂) (CategoryTheory.Category …
      hgf₂ : Eq (CategoryTheory.CategoryStruct.comp g₂ f.2) (CategoryTheory.Category …
      ⊢ CategoryTheory.IsIso f
    -/
    dsimp at hfg₁ hgf₁ hfg₂ hgf₂
    /-
      case mpr.intro.mk.intro.intro.mk.intro.intro
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g₁ : Quiver.Hom { fst := Q, snd := T }.1 { fst := P, snd := S }.1
      hfg₁ : Eq (CategoryTheory.CategoryStruct.comp f.1 g₁) (CategoryTheory.Category …
      hgf₁ : Eq (CategoryTheory.CategoryStruct.comp g₁ f.1) (CategoryTheory.Category …
      g₂ : Quiver.Hom { fst := Q, snd := T }.2 { fst := P, snd := S }.2
      hfg₂ : Eq (CategoryTheory.CategoryStruct.comp f.2 g₂) (CategoryTheory.Category …
      hgf₂ : Eq (CategoryTheory.CategoryStruct.comp g₂ f.2) (CategoryTheory.Category …
      ⊢ CategoryTheory.IsIso f
    -/
    refine ⟨⟨(g₁, g₂), ?_, ?_⟩⟩
    /-
      case mpr.intro.mk.intro.intro.mk.intro.intro.refine_1
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      P Q : C
      S T : D
      f : Quiver.Hom { fst := P, snd := S } { fst := Q, snd := T }
      g₁ : Quiver.Hom { fst := Q, snd := T }.1 { fst := P, snd := S }.1
      hfg₁ : Eq (CategoryTheory.CategoryStruct.comp f.1 g₁) (CategoryTheory.Category …
      hgf₁ : Eq (CategoryTheory.CategoryStruct.comp g₁ f.1) (CategoryTheory.Category …
      g₂ : Quiver.Hom { fst := Q, snd := T }.2 { fst := P, snd := S }.2
      hfg₂ : Eq (CategoryTheory.CategoryStruct.comp f.2 g₂) (CategoryTheory.Category …
      hgf₂ : Eq (CategoryTheory.CategoryStruct.comp g₂ f.2) (CategoryTheory.Category …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp f { fst := g₁, snd := g₂ }) (Category …
    -/
    repeat { simp; constructor; assumption; assumption }
    /-
      🎉 no goals
    -/


/-- The isomorphism between `(X.1, X.2)` and `X`. -/
@[simps]
def prod.etaIso (X : C × D) : (X.1, X.2) ≅ X where
  hom := (𝟙 _, 𝟙 _)
  inv := (𝟙 _, 𝟙 _)


/-- Construct an isomorphism in `C × D` out of two isomorphisms in `C` and `D`. -/
@[simps]
def Iso.prod {P Q : C} {S T : D} (f : P ≅ Q) (g : S ≅ T) : (P, S) ≅ (Q, T) where
  hom := (f.hom, g.hom)
  inv := (f.inv, g.inv)


/-- `Category.uniformProd C D` is an additional instance specialised so both factors have the same
universe levels. This helps typeclass resolution.
-/
instance uniformProd : Category (C × D) :=
  CategoryTheory.prod C D


/-- `sectL C Z` is the functor `C ⥤ C × D` given by `X ↦ (X, Z)`. -/
@[simps]
def sectL (C : Type u₁) [Category.{v₁} C] {D : Type u₂} [Category.{v₂} D] (Z : D) : C ⥤ C × D where
  obj X := (X, Z)
  map f := (f, 𝟙 Z)


/-- `sectR Z D` is the functor `D ⥤ C × D` given by `Y ↦ (Z, Y)` . -/
@[simps]
def sectR {C : Type u₁} [Category.{v₁} C] (Z : C) (D : Type u₂) [Category.{v₂} D] : D ⥤ C × D where
  obj X := (Z, X)
  map f := (𝟙 Z, f)


@[deprecated (since := "2024-11-12")] alias sectl := sectL

@[deprecated (since := "2024-11-12")] alias sectr := sectR

@[deprecated (since := "2024-11-12")] alias sectl_obj := sectL_obj

@[deprecated (since := "2024-11-12")] alias sectr_obj := sectR_obj

@[deprecated (since := "2024-11-12")] alias sectl_map := sectL_map

@[deprecated (since := "2024-11-12")] alias sectr_map := sectR_map


/-- `fst` is the functor `(X, Y) ↦ X`. -/
@[simps]
def fst : C × D ⥤ C where
  obj X := X.1
  map f := f.1


/-- `snd` is the functor `(X, Y) ↦ Y`. -/
@[simps]
def snd : C × D ⥤ D where
  obj X := X.2
  map f := f.2


/-- The functor swapping the factors of a cartesian product of categories, `C × D ⥤ D × C`. -/
@[simps]
def swap : C × D ⥤ D × C where
  obj X := (X.2, X.1)
  map f := (f.2, f.1)


/-- Swapping the factors of a cartesian product of categories twice is naturally isomorphic
to the identity functor.
-/
@[simps]
def symmetry : swap C D ⋙ swap D C ≅ 𝟭 (C × D) where
  hom := { app := fun X => 𝟙 X }
  inv := { app := fun X => 𝟙 X }


/-- The equivalence, given by swapping factors, between `C × D` and `D × C`.
-/
@[simps]
def braiding : C × D ≌ D × C where
  functor := swap C D
  inverse := swap D C
  unitIso := Iso.refl _
  counitIso := Iso.refl _


instance swapIsEquivalence : (swap C D).IsEquivalence :=
      /-
        C : Type u₁
        inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
        D : Type u₂
        inst✝ : CategoryTheory.Category.{v₂, u₂} D
        ⊢ (CategoryTheory.Prod.braiding C D).functor.IsEquivalence
      -/
  (by infer_instance : (braiding C D).functor.IsEquivalence)
      /-
        🎉 no goals
      -/


/-- The "evaluation at `X`" functor, such that
`(evaluation.obj X).obj F = F.obj X`,
which is functorial in both `X` and `F`.
-/
@[simps]
def evaluation : C ⥤ (C ⥤ D) ⥤ D where
  obj X :=
    { obj := fun F => F.obj X
      map := fun α => α.app X }
  map {_} {_} f :=
    { app := fun F => F.map f
      naturality := fun {_} {_} α => Eq.symm (α.naturality f) }


/-- The "evaluation of `F` at `X`" functor,
as a functor `C × (C ⥤ D) ⥤ D`.
-/
@[simps]
def evaluationUncurried : C × (C ⥤ D) ⥤ D where
  obj p := p.2.obj p.1
  map := fun {x} {y} f => x.2.map f.1 ≫ f.2.app y.1
  map_comp := fun {X} {Y} {Z} f g => by
    /-
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      X Y Z : Prod C (CategoryTheory.Functor C D)
      f : Quiver.Hom X Y
      g : Quiver.Hom Y Z
      ⊢ Eq ({ obj := fun p => p.2.obj p.1, map := fun {x y} f => CategoryTheory.Cate …
    -/
    cases g; cases f; cases Z; cases Y; cases X
    /-
      case mk.mk.mk.mk.mk
      C : Type u₁
      inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
      D : Type u₂
      inst✝ : CategoryTheory.Category.{v₂, u₂} D
      fst✝⁴ : C
      snd✝⁴ : CategoryTheory.Functor C D
      fst✝³ : C
      snd✝³ : CategoryTheory.Functor C D
      fst✝² : Quiver.Hom { fst := fst✝³, snd := snd✝³ }.1 { fst := fst✝⁴, snd := snd …
      snd✝² : Quiver.Hom { fst := fst✝³, snd := snd✝³ }.2 { fst := fst✝⁴, snd := snd …
      fst✝¹ : C
      snd✝¹ : CategoryTheory.Functor C D
      fst✝ : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ }.1 { fst := fst✝³, snd := snd✝ …
      snd✝ : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ }.2 { fst := fst✝³, snd := snd✝ …
      ⊢ Eq ({ obj := fun p => p.2.obj p.1, map := fun {x y} f => CategoryTheory.Cate …
    -/
    simp only [prod_comp, NatTrans.comp_app, Functor.map_comp, Category.assoc]
    rw [← NatTrans.comp_app, NatTrans.naturality, NatTrans.comp_app, Category.assoc,
      NatTrans.naturality]


/-- The constant functor followed by the evaluation functor is just the identity. -/
@[simps!]
def Functor.constCompEvaluationObj (X : C) : Functor.const C ⋙ (evaluation C D).obj X ≅ 𝟭 D :=
  /-
    C : Type u₁
    inst✝¹ : CategoryTheory.Category.{v₁, u₁} C
    D : Type u₂
    inst✝ : CategoryTheory.Category.{v₂, u₂} D
    X : C
    ⊢ ∀ {X_1 Y : D} (f : Quiver.Hom X_1 Y), Eq (CategoryTheory.CategoryStruct.comp …
  -/
  NatIso.ofComponents fun _ => Iso.refl _
  /-
    🎉 no goals
  -/


/-- The cartesian product of two functors. -/
@[simps]
def prod (F : A ⥤ B) (G : C ⥤ D) : A × C ⥤ B × D where
  obj X := (F.obj X.1, G.obj X.2)
  map f := (F.map f.1, G.map f.2)

/- Because of limitations in Lean 3's handling of notations, we do not setup a notation `F × G`.
   You can use `F.prod G` as a "poor man's infix", or just write `functor.prod F G`. -/

/-- Similar to `prod`, but both functors start from the same category `A` -/
@[simps]
def prod' (F : A ⥤ B) (G : A ⥤ C) : A ⥤ B × C where
  obj a := (F.obj a, G.obj a)
  map f := (F.map f, G.map f)


/-- The product `F.prod' G` followed by projection on the first component is isomorphic to `F` -/
@[simps!]
def prod'CompFst (F : A ⥤ B) (G : A ⥤ C) : F.prod' G ⋙ CategoryTheory.Prod.fst B C ≅ F :=
  /-
    A : Type u₁
    inst✝³ : CategoryTheory.Category.{v₁, u₁} A
    B : Type u₂
    inst✝² : CategoryTheory.Category.{v₂, u₂} B
    C : Type u₃
    inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
    D : Type u₄
    inst✝ : CategoryTheory.Category.{v₄, u₄} D
    F : CategoryTheory.Functor A B
    G : CategoryTheory.Functor A C
    ⊢ ∀ {X Y : A} (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((( …
  -/
  NatIso.ofComponents fun _ => Iso.refl _
  /-
    🎉 no goals
  -/


/-- The product `F.prod' G` followed by projection on the second component is isomorphic to `G` -/
@[simps!]
def prod'CompSnd (F : A ⥤ B) (G : A ⥤ C) : F.prod' G ⋙ CategoryTheory.Prod.snd B C ≅ G :=
  /-
    A : Type u₁
    inst✝³ : CategoryTheory.Category.{v₁, u₁} A
    B : Type u₂
    inst✝² : CategoryTheory.Category.{v₂, u₂} B
    C : Type u₃
    inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
    D : Type u₄
    inst✝ : CategoryTheory.Category.{v₄, u₄} D
    F : CategoryTheory.Functor A B
    G : CategoryTheory.Functor A C
    ⊢ ∀ {X Y : A} (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((( …
  -/
  NatIso.ofComponents fun _ => Iso.refl _
  /-
    🎉 no goals
  -/


/-- The diagonal functor. -/
def diag : C ⥤ C × C :=
  (𝟭 C).prod' (𝟭 C)


@[simp]
theorem diag_obj (X : C) : (diag C).obj X = (X, X) :=
  rfl


@[simp]
theorem diag_map {X Y : C} (f : X ⟶ Y) : (diag C).map f = (f, f) :=
  rfl


/-- The cartesian product of two natural transformations. -/
@[simps]
def prod {F G : A ⥤ B} {H I : C ⥤ D} (α : F ⟶ G) (β : H ⟶ I) : F.prod H ⟶ G.prod I where
  app X := (α.app X.1, β.app X.2)
  naturality {X} {Y} f := by
    /-
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      F G : CategoryTheory.Functor A B
      H I : CategoryTheory.Functor C D
      α : Quiver.Hom F G
      β : Quiver.Hom H I
      X Y : Prod A C
      f : Quiver.Hom X Y
      ⊢ Eq (CategoryTheory.CategoryStruct.comp ((F.prod H).map f) ((fun X => { fst : …
    -/
    cases X; cases Y
    /-
      case mk.mk
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      F G : CategoryTheory.Functor A B
      H I : CategoryTheory.Functor C D
      α : Quiver.Hom F G
      β : Quiver.Hom H I
      fst✝¹ : A
      snd✝¹ : C
      fst✝ : A
      snd✝ : C
      f : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ } { fst := fst✝, snd := snd✝ }
      ⊢ Eq (CategoryTheory.CategoryStruct.comp ((F.prod H).map f) ((fun X => { fst : …
    -/
    simp only [Functor.prod_map, prod_comp]
    /-
      case mk.mk
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      F G : CategoryTheory.Functor A B
      H I : CategoryTheory.Functor C D
      α : Quiver.Hom F G
      β : Quiver.Hom H I
      fst✝¹ : A
      snd✝¹ : C
      fst✝ : A
      snd✝ : C
      f : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ } { fst := fst✝, snd := snd✝ }
      ⊢ Eq { fst := CategoryTheory.CategoryStruct.comp (F.map f.1) (α.app fst✝), snd …
    -/
    rw [Prod.mk.inj_iff]
    /-
      case mk.mk
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      F G : CategoryTheory.Functor A B
      H I : CategoryTheory.Functor C D
      α : Quiver.Hom F G
      β : Quiver.Hom H I
      fst✝¹ : A
      snd✝¹ : C
      fst✝ : A
      snd✝ : C
      f : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ } { fst := fst✝, snd := snd✝ }
      ⊢ And (Eq (CategoryTheory.CategoryStruct.comp (F.map f.1) (α.app fst✝)) (Categ …
    -/
    constructor
    /-
      case mk.mk.left
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      F G : CategoryTheory.Functor A B
      H I : CategoryTheory.Functor C D
      α : Quiver.Hom F G
      β : Quiver.Hom H I
      fst✝¹ : A
      snd✝¹ : C
      fst✝ : A
      snd✝ : C
      f : Quiver.Hom { fst := fst✝¹, snd := snd✝¹ } { fst := fst✝, snd := snd✝ }
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map f.1) (α.app fst✝)) (CategoryTh …
    -/
    repeat {rw [naturality]}
    /-
      🎉 no goals
    -/

/- Again, it is inadvisable in Lean 3 to setup a notation `α × β`;
   use instead `α.prod β` or `NatTrans.prod α β`. -/


/-- The cartesian product of two natural transformations. -/
def prod' : F.prod' H ⟶ G.prod' K where
  app X := (α.app X, β.app X)


@[simp] lemma prod'_app_fst (X : A) : ((prod' α β).app X).1 = α.app X := rfl

@[simp] lemma prod'_app_snd (X : A) : ((prod' α β).app X).2 = β.app X := rfl


/-- The cartesian product functor between functor categories -/
@[simps]
def prodFunctor : (A ⥤ B) × (C ⥤ D) ⥤ A × C ⥤ B × D where
  obj FG := FG.1.prod FG.2
  map nm := NatTrans.prod nm.1 nm.2


/-- The cartesian product of two natural isomorphisms. -/
@[simps]
def prod {F F' : A ⥤ B} {G G' : C ⥤ D} (e₁ : F ≅ F') (e₂ : G ≅ G') :
    F.prod G ≅ F'.prod G' where
  hom := NatTrans.prod e₁.hom e₂.hom
  inv := NatTrans.prod e₁.inv e₂.inv


/-- The cartesian product of two equivalences of categories. -/
@[simps]
def prod (E₁ : A ≌ B) (E₂ : C ≌ D) : A × C ≌ B × D where
  functor := E₁.functor.prod E₂.functor
  inverse := E₁.inverse.prod E₂.inverse
  unitIso := NatIso.prod E₁.unitIso E₂.unitIso
  counitIso := NatIso.prod E₁.counitIso E₂.counitIso


/-- `F.flip` composed with evaluation is the same as evaluating `F`. -/
@[simps!]
def flipCompEvaluation (F : A ⥤ B ⥤ C) (a) : F.flip ⋙ (evaluation _ _).obj a ≅ F.obj a :=
  /-
    A : Type u₁
    inst✝³ : CategoryTheory.Category.{v₁, u₁} A
    B : Type u₂
    inst✝² : CategoryTheory.Category.{v₂, u₂} B
    C : Type u₃
    inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
    D : Type u₄
    inst✝ : CategoryTheory.Category.{v₄, u₄} D
    F : CategoryTheory.Functor A (CategoryTheory.Functor B C)
    a : A
    ⊢ ∀ {X Y : B} (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((F …
  -/
  NatIso.ofComponents fun b => Iso.refl _
  /-
    🎉 no goals
  -/


theorem flip_comp_evaluation (F : A ⥤ B ⥤ C) (a) : F.flip ⋙ (evaluation _ _).obj a = F.obj a :=
  rfl


/-- `F` composed with evaluation is the same as evaluating `F.flip`. -/
@[simps!]
def compEvaluation (F : A ⥤ B ⥤ C) (b) : F ⋙ (evaluation _ _).obj b ≅ F.flip.obj b :=
  /-
    A : Type u₁
    inst✝³ : CategoryTheory.Category.{v₁, u₁} A
    B : Type u₂
    inst✝² : CategoryTheory.Category.{v₂, u₂} B
    C : Type u₃
    inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
    D : Type u₄
    inst✝ : CategoryTheory.Category.{v₄, u₄} D
    F : CategoryTheory.Functor A (CategoryTheory.Functor B C)
    b : B
    ⊢ ∀ {X Y : A} (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((F …
  -/
  NatIso.ofComponents fun a => Iso.refl _
  /-
    🎉 no goals
  -/


theorem comp_evaluation (F : A ⥤ B ⥤ C) (b) : F ⋙ (evaluation _ _).obj b = F.flip.obj b :=
  rfl


/-- Whiskering by `F` and then evaluating at `a` is the same as evaluating at `F.obj a`. -/
@[simps!]
def whiskeringLeftCompEvaluation (F : A ⥤ B) (a : A) :
    (whiskeringLeft A B C).obj F ⋙ (evaluation A C).obj a ≅ (evaluation B C).obj (F.obj a) :=
  Iso.refl _


/-- Whiskering by `F` and then evaluating at `a` is the same as evaluating at `F.obj a`. -/
@[simp]
theorem whiskeringLeft_comp_evaluation (F : A ⥤ B) (a : A) :
    (whiskeringLeft A B C).obj F ⋙ (evaluation A C).obj a = (evaluation B C).obj (F.obj a) :=
  rfl


/-- Whiskering by `F` and then evaluating at `a` is the same as evaluating at `F` and then
applying `F`. -/
@[simps!]
def whiskeringRightCompEvaluation (F : B ⥤ C) (a : A) :
    (whiskeringRight A B C).obj F ⋙ (evaluation _ _).obj a ≅ (evaluation _ _).obj a ⋙ F :=
  Iso.refl _


/-- Whiskering by `F` and then evaluating at `a` is the same as evaluating at `F` and then
applying `F`. -/
@[simp]
theorem whiskeringRight_comp_evaluation (F : B ⥤ C) (a : A) :
    (whiskeringRight A B C).obj F ⋙ (evaluation _ _).obj a = (evaluation _ _).obj a ⋙ F :=
  rfl


/-- The forward direction for `functorProdFunctorEquiv` -/
@[simps]
def prodFunctorToFunctorProd : (A ⥤ B) × (A ⥤ C) ⥤ A ⥤ B × C where
  obj F := F.1.prod' F.2
  map f := { app := fun X => (f.1.app X, f.2.app X) }


/-- The backward direction for `functorProdFunctorEquiv` -/
@[simps]
def functorProdToProdFunctor : (A ⥤ B × C) ⥤ (A ⥤ B) × (A ⥤ C) where
  obj F := ⟨F ⋙ CategoryTheory.Prod.fst B C, F ⋙ CategoryTheory.Prod.snd B C⟩
  map α :=
    ⟨{  app := fun X => (α.app X).1
        naturality := fun X Y f => by
          /-
            A : Type u₁
            inst✝³ : CategoryTheory.Category.{v₁, u₁} A
            B : Type u₂
            inst✝² : CategoryTheory.Category.{v₂, u₂} B
            C : Type u₃
            inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
            D : Type u₄
            inst✝ : CategoryTheory.Category.{v₄, u₄} D
            X✝ Y✝ : CategoryTheory.Functor A (Prod B C)
            α : Quiver.Hom X✝ Y✝
            X Y : A
            f : Quiver.Hom X Y
            ⊢ Eq (CategoryTheory.CategoryStruct.comp (((fun F => { fst := F.comp (Category …
          -/
          simp only [Functor.comp_map, Prod.fst_map, ← prod_comp_fst, α.naturality] },
          /-
            🎉 no goals
          -/
      { app := fun X => (α.app X).2
        naturality := fun X Y f => by
          /-
            A : Type u₁
            inst✝³ : CategoryTheory.Category.{v₁, u₁} A
            B : Type u₂
            inst✝² : CategoryTheory.Category.{v₂, u₂} B
            C : Type u₃
            inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
            D : Type u₄
            inst✝ : CategoryTheory.Category.{v₄, u₄} D
            X✝ Y✝ : CategoryTheory.Functor A (Prod B C)
            α : Quiver.Hom X✝ Y✝
            X Y : A
            f : Quiver.Hom X Y
            ⊢ Eq (CategoryTheory.CategoryStruct.comp (((fun F => { fst := F.comp (Category …
          -/
          simp only [Functor.comp_map, Prod.snd_map, ← prod_comp_snd, α.naturality] }⟩
          /-
            🎉 no goals
          -/


/-- The unit isomorphism for `functorProdFunctorEquiv` -/
@[simps!]
def functorProdFunctorEquivUnitIso :
    𝟭 _ ≅ prodFunctorToFunctorProd A B C ⋙ functorProdToProdFunctor A B C :=
  /-
    A : Type u₁
    inst✝³ : CategoryTheory.Category.{v₁, u₁} A
    B : Type u₂
    inst✝² : CategoryTheory.Category.{v₂, u₂} B
    C : Type u₃
    inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
    D : Type u₄
    inst✝ : CategoryTheory.Category.{v₄, u₄} D
    ⊢ ∀ {X Y : Prod (CategoryTheory.Functor A B) (CategoryTheory.Functor A C)} (f  …
  -/
  NatIso.ofComponents fun F =>
  /-
    🎉 no goals
  -/
    (((Functor.prod'CompFst F.fst F.snd).prod (Functor.prod'CompSnd F.fst F.snd)).trans
      (prod.etaIso F)).symm


/-- The counit isomorphism for `functorProdFunctorEquiv` -/
@[simps!]
def functorProdFunctorEquivCounitIso :
    functorProdToProdFunctor A B C ⋙ prodFunctorToFunctorProd A B C ≅ 𝟭 _ :=
                               /-
                                 A : Type u₁
                                 inst✝³ : CategoryTheory.Category.{v₁, u₁} A
                                 B : Type u₂
                                 inst✝² : CategoryTheory.Category.{v₂, u₂} B
                                 C : Type u₃
                                 inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
                                 D : Type u₄
                                 inst✝ : CategoryTheory.Category.{v₄, u₄} D
                                 F : CategoryTheory.Functor A (Prod B C)
                                 ⊢ ∀ {X Y : A} (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((( …
                               -/
                               /-
                                 🎉 no goals
                               -/
  NatIso.ofComponents fun F => NatIso.ofComponents fun X => prod.etaIso (F.obj X)
  /-
    🎉 no goals
  -/


/-- The equivalence of categories between `(A ⥤ B) × (A ⥤ C)` and `A ⥤ (B × C)` -/
@[simps]
def functorProdFunctorEquiv : (A ⥤ B) × (A ⥤ C) ≌ A ⥤ B × C :=
  { functor := prodFunctorToFunctorProd A B C,
    inverse := functorProdToProdFunctor A B C,
    unitIso := functorProdFunctorEquivUnitIso A B C,
    counitIso := functorProdFunctorEquivCounitIso A B C, }


/-- The equivalence between the opposite of a product and the product of the opposites. -/
@[simps]
def prodOpEquiv : (C × D)ᵒᵖ ≌ Cᵒᵖ × Dᵒᵖ where
  functor :=
    { obj := fun X ↦ ⟨op X.unop.1, op X.unop.2⟩,
      map := fun f ↦ ⟨f.unop.1.op, f.unop.2.op⟩ }
  inverse :=
    { obj := fun ⟨X,Y⟩ ↦ op ⟨X.unop, Y.unop⟩,
      map := fun ⟨f,g⟩ ↦ op ⟨f.unop, g.unop⟩ }
  unitIso := Iso.refl _
  counitIso := Iso.refl _
  functor_unitIso_comp := fun ⟨X, Y⟩ => by
    /-
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      x✝ : Opposite (Prod C D)
      X : C
      Y : D
      ⊢ Eq (CategoryTheory.CategoryStruct.comp ({ obj := fun X => { fst := { unop := …
    -/
    dsimp
    /-
      A : Type u₁
      inst✝³ : CategoryTheory.Category.{v₁, u₁} A
      B : Type u₂
      inst✝² : CategoryTheory.Category.{v₂, u₂} B
      C : Type u₃
      inst✝¹ : CategoryTheory.Category.{v₃, u₃} C
      D : Type u₄
      inst✝ : CategoryTheory.Category.{v₄, u₄} D
      x✝ : Opposite (Prod C D)
      X : C
      Y : D
      ⊢ Eq { fst := CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruc …
    -/
            /-
              🎉 no goals
            -/
    ext <;> apply Category.id_comp
            /-
              🎉 no goals
            -/


