protected theorem isOpen_iff (hS : RestrictGenTopology S) :
    IsOpen t ↔ ∀ s ∈ S, IsOpen ((↑) ⁻¹' t : Set s) :=
  ⟨fun ht _ _ ↦ ht.preimage continuous_subtype_val, hS.1 t⟩


protected theorem isClosed_iff (hS : RestrictGenTopology S) :
    IsClosed t ↔ ∀ s ∈ S, IsClosed ((↑) ⁻¹' t : Set s) := by
  /-
    X : Type u_1
    inst✝ : TopologicalSpace X
    S : Set (Set X)
    t : Set X
    hS : Topology.RestrictGenTopology S
    ⊢ Iff (IsClosed t) (∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage …
  -/
  simp only [← isOpen_compl_iff, hS.isOpen_iff, preimage_compl]
  /-
    🎉 no goals
  -/


protected theorem continuous_iff {Y : Type*} [TopologicalSpace Y] {f : X → Y}
    (hS : RestrictGenTopology S) :
    Continuous f ↔ ∀ s ∈ S, ContinuousOn f s :=
  ⟨fun h _ _ ↦ h.continuousOn, fun h ↦ continuous_def.2 fun _u hu ↦ hS.isOpen_iff.2 fun s hs ↦
    hu.preimage <| (h s hs).restrict⟩


theorem of_continuous_prop (h : ∀ f : X → Prop, (∀ s ∈ S, ContinuousOn f s) → Continuous f) :
    RestrictGenTopology S where
  isOpen_of_forall_induced u hu := by
    /-
      X : Type u_1
      inst✝ : TopologicalSpace X
      S : Set (Set X)
      h : ∀ (f : X → Prop), (∀ (s : Set X), Membership.mem S s → ContinuousOn f s) → …
      u : Set X
      hu : ∀ (s : Set X), Membership.mem S s → IsOpen (Set.preimage Subtype.val u)
      ⊢ IsOpen u
    -/
    simp only [continuousOn_iff_continuous_restrict, continuous_Prop] at *
    /-
      X : Type u_1
      inst✝ : TopologicalSpace X
      S : Set (Set X)
      u : Set X
      hu : ∀ (s : Set X), Membership.mem S s → IsOpen (Set.preimage Subtype.val u)
      h : ∀ (f : X → Prop), (∀ (s : Set X), Membership.mem S s → IsOpen (setOf fun x …
      ⊢ IsOpen u
    -/
    exact h _ hu
    /-
      🎉 no goals
    -/


theorem of_isClosed (h : ∀ t : Set X, (∀ s ∈ S, IsClosed ((↑) ⁻¹' t : Set s)) → IsClosed t) :
    RestrictGenTopology S :=
  ⟨fun _t ht ↦ isClosed_compl_iff.1 <| h _ fun s hs ↦ (ht s hs).isClosed_compl⟩


protected theorem enlarge {T} (hS : RestrictGenTopology S) (hT : ∀ s ∈ S, ∃ t ∈ T, s ⊆ t) :
    RestrictGenTopology T :=
  of_continuous_prop fun _f hf ↦ hS.continuous_iff.2 fun s hs ↦
    let ⟨t, htT, hst⟩ := hT s hs; (hf t htT).mono hst


protected theorem mono {T} (hS : RestrictGenTopology S) (hT : S ⊆ T) : RestrictGenTopology T :=
  hS.enlarge fun s hs ↦ ⟨s, hT hs, Subset.rfl⟩


/-- If `X` is a sequential space
and `S` contains each set of the form `insert x (Set.range u)`
where `u : ℕ → X` is a sequence and `x` is its limit,
then topology on `X` is generated by its restrictions to the sets of `S`. -/
lemma of_seq [SequentialSpace X]
    (h : ∀ ⦃u : ℕ → X⦄ ⦃x : X⦄, Tendsto u atTop (𝓝 x) → insert x (range u) ∈ S) :
    RestrictGenTopology S := by
  /-
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    ⊢ Topology.RestrictGenTopology S
  -/
  refine of_isClosed fun t ht ↦ IsSeqClosed.isClosed fun u x hut hux ↦ ?_
  /-
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    ⊢ Membership.mem t x
  -/
  rcases isClosed_induced_iff.1 (ht _ (h hux)) with ⟨s, hsc, hst⟩
  /-
    case intro.intro
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    s : Set X
    hsc : IsClosed s
    hst : Eq (Set.preimage Subtype.val s) (Set.preimage Subtype.val t)
    ⊢ Membership.mem t x
  -/
  rw [Subtype.preimage_val_eq_preimage_val_iff, Set.ext_iff] at hst
  /-
    case intro.intro
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    s : Set X
    hsc : IsClosed s
    hst : ∀ (x_1 : X), Iff (Membership.mem (Inter.inter (Insert.insert x (Set.rang …
    ⊢ Membership.mem t x
  -/
  suffices x ∈ s by specialize hst x; simp_all
  /-
    case intro.intro
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    s : Set X
    hsc : IsClosed s
    hst : ∀ (x_1 : X), Iff (Membership.mem (Inter.inter (Insert.insert x (Set.rang …
    ⊢ Membership.mem s x
  -/
  refine hsc.mem_of_tendsto hux <| Eventually.of_forall fun k ↦ ?_
  /-
    case intro.intro
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    s : Set X
    hsc : IsClosed s
    hst : ∀ (x_1 : X), Iff (Membership.mem (Inter.inter (Insert.insert x (Set.rang …
    k : Nat
    ⊢ Membership.mem s (u k)
  -/
  specialize hst (u k)
  /-
    case intro.intro
    X : Type u_1
    inst✝¹ : TopologicalSpace X
    S : Set (Set X)
    inst✝ : SequentialSpace X
    h : ∀ ⦃u : Nat → X⦄ ⦃x : X⦄, Filter.Tendsto u Filter.atTop (nhds x) → Membersh …
    t : Set X
    ht : ∀ (s : Set X), Membership.mem S s → IsClosed (Set.preimage Subtype.val t)
    u : Nat → X
    x : X
    hut : ∀ (n : Nat), Membership.mem t (u n)
    hux : Filter.Tendsto u Filter.atTop (nhds x)
    s : Set X
    hsc : IsClosed s
    k : Nat
    hst : Iff (Membership.mem (Inter.inter (Insert.insert x (Set.range u)) s) (u k …
    ⊢ Membership.mem s (u k)
  -/
  simp_all
  /-
    🎉 no goals
  -/


/-- A sequential space is compactly generated. -/
lemma isCompact_of_seq [SequentialSpace X] : RestrictGenTopology {K : Set X | IsCompact K} :=
  of_seq fun _u _x hux ↦ hux.isCompact_insert_range


/-- If each point of the space has a neighborhood from the family `S`,
then the topology is generated by its restrictions to the sets of `S`. -/
lemma of_nhds (h : ∀ x, ∃ s ∈ S, s ∈ 𝓝 x) : RestrictGenTopology S :=
  of_continuous_prop fun _f hf ↦ continuous_iff_continuousAt.2 fun x ↦
    let ⟨s, hsS, hsx⟩ := h x
    (hf s hsS).continuousAt hsx


/-- A weakly locally compact space is compactly generated. -/
lemma isCompact_of_weaklyLocallyCompact [WeaklyLocallyCompactSpace X] :
    RestrictGenTopology {K : Set X | IsCompact K} :=
  of_nhds exists_compact_mem_nhds


