/-- Construct a quadratic form on a product of two modules from the quadratic form on each module.
-/
@[simps!]
def prod (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) : QuadraticMap R (M₁ × M₂) P :=
  Q₁.comp (LinearMap.fst _ _ _) + Q₂.comp (LinearMap.snd _ _ _)


/-- An isometry between quadratic forms generated by `QuadraticForm.prod` can be constructed
from a pair of isometries between the left and right parts. -/
@[simps toLinearEquiv]
def IsometryEquiv.prod
    {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    {Q₁' : QuadraticMap R N₁ P} {Q₂' : QuadraticMap R N₂ P}
    (e₁ : Q₁.IsometryEquiv Q₁') (e₂ : Q₂.IsometryEquiv Q₂') :
    (Q₁.prod Q₂).IsometryEquiv (Q₁'.prod Q₂') where
  map_app' x := congr_arg₂ (· + ·) (e₁.map_app x.1) (e₂.map_app x.2)
  toLinearEquiv := LinearEquiv.prod e₁.toLinearEquiv e₂.toLinearEquiv


/-- `LinearMap.inl` as an isometry. -/
@[simps!]
def Isometry.inl (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) : Q₁ →qᵢ (Q₁.prod Q₂) where
  toLinearMap := LinearMap.inl R _ _
                    /-
                      ι : Type u_1
                      R : Type u_2
                      M₁ : Type u_3
                      M₂ : Type u_4
                      N₁ : Type u_5
                      N₂ : Type u_6
                      P : Type u_7
                      Mᵢ : ι → Type u_8
                      Nᵢ : ι → Type u_9
                      inst✝¹⁰ : CommSemiring R
                      inst✝⁹ : AddCommMonoid M₁
                      inst✝⁸ : AddCommMonoid M₂
                      inst✝⁷ : AddCommMonoid N₁
                      inst✝⁶ : AddCommMonoid N₂
                      inst✝⁵ : AddCommMonoid P
                      inst✝⁴ : Module R M₁
                      inst✝³ : Module R M₂
                      inst✝² : Module R N₁
                      inst✝¹ : Module R N₂
                      inst✝ : Module R P
                      Q₁ : QuadraticMap R M₁ P
                      Q₂ : QuadraticMap R M₂ P
                      m₁ : M₁
                      ⊢ Eq ((Q₁.prod Q₂) ((LinearMap.inl R M₁ M₂).toFun m₁)) (Q₁ m₁)
                    -/
  map_app' m₁ := by simp
                    /-
                      🎉 no goals
                    -/


/-- `LinearMap.inr` as an isometry. -/
@[simps!]
def Isometry.inr (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) : Q₂ →qᵢ (Q₁.prod Q₂) where
  toLinearMap := LinearMap.inr R _ _
                    /-
                      ι : Type u_1
                      R : Type u_2
                      M₁ : Type u_3
                      M₂ : Type u_4
                      N₁ : Type u_5
                      N₂ : Type u_6
                      P : Type u_7
                      Mᵢ : ι → Type u_8
                      Nᵢ : ι → Type u_9
                      inst✝¹⁰ : CommSemiring R
                      inst✝⁹ : AddCommMonoid M₁
                      inst✝⁸ : AddCommMonoid M₂
                      inst✝⁷ : AddCommMonoid N₁
                      inst✝⁶ : AddCommMonoid N₂
                      inst✝⁵ : AddCommMonoid P
                      inst✝⁴ : Module R M₁
                      inst✝³ : Module R M₂
                      inst✝² : Module R N₁
                      inst✝¹ : Module R N₂
                      inst✝ : Module R P
                      Q₁ : QuadraticMap R M₁ P
                      Q₂ : QuadraticMap R M₂ P
                      m₁ : M₂
                      ⊢ Eq ((Q₁.prod Q₂) ((LinearMap.inr R M₁ M₂).toFun m₁)) (Q₂ m₁)
                    -/
  map_app' m₁ := by simp
                    /-
                      🎉 no goals
                    -/


variable (M₂) in
/-- `LinearMap.fst` as an isometry, when the second space has the zero quadratic form. -/
@[simps!]
def Isometry.fst (Q₁ : QuadraticMap R M₁ P) : (Q₁.prod (0 : QuadraticMap R M₂ P)) →qᵢ Q₁ where
  toLinearMap := LinearMap.fst R _ _
                    /-
                      ι : Type u_1
                      R : Type u_2
                      M₁ : Type u_3
                      M₂ : Type u_4
                      N₁ : Type u_5
                      N₂ : Type u_6
                      P : Type u_7
                      Mᵢ : ι → Type u_8
                      Nᵢ : ι → Type u_9
                      inst✝¹⁰ : CommSemiring R
                      inst✝⁹ : AddCommMonoid M₁
                      inst✝⁸ : AddCommMonoid M₂
                      inst✝⁷ : AddCommMonoid N₁
                      inst✝⁶ : AddCommMonoid N₂
                      inst✝⁵ : AddCommMonoid P
                      inst✝⁴ : Module R M₁
                      inst✝³ : Module R M₂
                      inst✝² : Module R N₁
                      inst✝¹ : Module R N₂
                      inst✝ : Module R P
                      Q₁ : QuadraticMap R M₁ P
                      m₁ : Prod M₁ M₂
                      ⊢ Eq (Q₁ ((LinearMap.fst R M₁ M₂).toFun m₁)) ((Q₁.prod 0) m₁)
                    -/
  map_app' m₁ := by simp
                    /-
                      🎉 no goals
                    -/


variable (M₁) in
/-- `LinearMap.snd` as an isometry, when the first space has the zero quadratic form. -/
@[simps!]
def Isometry.snd (Q₂ : QuadraticMap R M₂ P) : ((0 : QuadraticMap R M₁ P).prod Q₂) →qᵢ Q₂ where
  toLinearMap := LinearMap.snd R _ _
                    /-
                      ι : Type u_1
                      R : Type u_2
                      M₁ : Type u_3
                      M₂ : Type u_4
                      N₁ : Type u_5
                      N₂ : Type u_6
                      P : Type u_7
                      Mᵢ : ι → Type u_8
                      Nᵢ : ι → Type u_9
                      inst✝¹⁰ : CommSemiring R
                      inst✝⁹ : AddCommMonoid M₁
                      inst✝⁸ : AddCommMonoid M₂
                      inst✝⁷ : AddCommMonoid N₁
                      inst✝⁶ : AddCommMonoid N₂
                      inst✝⁵ : AddCommMonoid P
                      inst✝⁴ : Module R M₁
                      inst✝³ : Module R M₂
                      inst✝² : Module R N₁
                      inst✝¹ : Module R N₂
                      inst✝ : Module R P
                      Q₂ : QuadraticMap R M₂ P
                      m₁ : Prod M₁ M₂
                      ⊢ Eq (Q₂ ((LinearMap.snd R M₁ M₂).toFun m₁)) ((QuadraticMap.prod 0 Q₂) m₁)
                    -/
  map_app' m₁ := by simp
                    /-
                      🎉 no goals
                    -/


@[simp]
lemma Isometry.fst_comp_inl (Q₁ : QuadraticMap R M₁ P) :
    (fst M₂ Q₁).comp (inl Q₁ (0 : QuadraticMap R M₂ P)) = .id _ :=
  ext fun _ => rfl


@[simp]
lemma Isometry.snd_comp_inr (Q₂ : QuadraticMap R M₂ P) :
    (snd M₁ Q₂).comp (inr (0 : QuadraticMap R M₁ P) Q₂) = .id _ :=
  ext fun _ => rfl


@[simp]
lemma Isometry.snd_comp_inl (Q₂ : QuadraticMap R M₂ P) :
    (snd M₁ Q₂).comp (inl (0 : QuadraticMap R M₁ P) Q₂) = 0 :=
  ext fun _ => rfl


@[simp]
lemma Isometry.fst_comp_inr (Q₁ : QuadraticMap R M₁ P) :
    (fst M₂ Q₁).comp (inr Q₁ (0 : QuadraticMap R M₂ P)) = 0 :=
  ext fun _ => rfl


theorem Equivalent.prod {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    {Q₁' : QuadraticMap R N₁ P} {Q₂' : QuadraticMap R N₂ P} (e₁ : Q₁.Equivalent Q₁')
    (e₂ : Q₂.Equivalent Q₂') : (Q₁.prod Q₂).Equivalent (Q₁'.prod Q₂') :=
  Nonempty.map2 IsometryEquiv.prod e₁ e₂


/-- `LinearEquiv.prodComm` is isometric. -/
@[simps!]
def IsometryEquiv.prodComm (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) :
    (Q₁.prod Q₂).IsometryEquiv (Q₂.prod Q₁) where
  toLinearEquiv := LinearEquiv.prodComm _ _ _
  map_app' _ := add_comm _ _


/-- `LinearEquiv.prodProdProdComm` is isometric. -/
@[simps!]
def IsometryEquiv.prodProdProdComm
    (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P)
    (Q₃ : QuadraticMap R N₁ P) (Q₄ : QuadraticMap R N₂ P) :
    ((Q₁.prod Q₂).prod (Q₃.prod Q₄)).IsometryEquiv ((Q₁.prod Q₃).prod (Q₂.prod Q₄)) where
  toLinearEquiv := LinearEquiv.prodProdProdComm _ _ _ _ _
  map_app' _ := add_add_add_comm _ _ _ _


/-- If a product is anisotropic then its components must be. The converse is not true. -/
theorem anisotropic_of_prod
    {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P} (h : (Q₁.prod Q₂).Anisotropic) :
    Q₁.Anisotropic ∧ Q₂.Anisotropic := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommSemiring R
    inst✝⁵ : AddCommMonoid M₁
    inst✝⁴ : AddCommMonoid M₂
    inst✝³ : AddCommMonoid P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    h : (Q₁.prod Q₂).Anisotropic
    ⊢ And Q₁.Anisotropic Q₂.Anisotropic
  -/
  simp_rw [Anisotropic, prod_apply, Prod.forall, Prod.mk_eq_zero] at h
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommSemiring R
    inst✝⁵ : AddCommMonoid M₁
    inst✝⁴ : AddCommMonoid M₂
    inst✝³ : AddCommMonoid P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
    ⊢ And Q₁.Anisotropic Q₂.Anisotropic
  -/
  constructor
    /-
      case left
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      ⊢ Q₁.Anisotropic
    -/
  · intro x hx
    /-
      case left
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      x : M₁
      hx : Eq (Q₁ x) 0
      ⊢ Eq x 0
    -/
    refine (h x 0 ?_).1
    /-
      case left
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      x : M₁
      hx : Eq (Q₁ x) 0
      ⊢ Eq (HAdd.hAdd (Q₁ x) (Q₂ 0)) 0
    -/
    rw [hx, zero_add, map_zero]
    /-
      🎉 no goals
    -/
    /-
      case right
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      ⊢ Q₂.Anisotropic
    -/
  · intro x hx
    /-
      case right
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      x : M₂
      hx : Eq (Q₂ x) 0
      ⊢ Eq x 0
    -/
    refine (h 0 x ?_).2
    /-
      case right
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁶ : CommSemiring R
      inst✝⁵ : AddCommMonoid M₁
      inst✝⁴ : AddCommMonoid M₂
      inst✝³ : AddCommMonoid P
      inst✝² : Module R M₁
      inst✝¹ : Module R M₂
      inst✝ : Module R P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), Eq (HAdd.hAdd (Q₁ a) (Q₂ b)) 0 → And (Eq a 0) (Eq b 0)
      x : M₂
      hx : Eq (Q₂ x) 0
      ⊢ Eq (HAdd.hAdd (Q₁ 0) (Q₂ x)) 0
    -/
    rw [hx, add_zero, map_zero]
    /-
      🎉 no goals
    -/


theorem nonneg_prod_iff [Preorder P] [AddLeftMono P]
    {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P} :
    (∀ x, 0 ≤ (Q₁.prod Q₂) x) ↔ (∀ x, 0 ≤ Q₁ x) ∧ ∀ x, 0 ≤ Q₂ x := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁸ : CommSemiring R
    inst✝⁷ : AddCommMonoid M₁
    inst✝⁶ : AddCommMonoid M₂
    inst✝⁵ : AddCommMonoid P
    inst✝⁴ : Module R M₁
    inst✝³ : Module R M₂
    inst✝² : Module R P
    inst✝¹ : Preorder P
    inst✝ : AddLeftMono P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Iff (∀ (x : Prod M₁ M₂), LE.le 0 ((Q₁.prod Q₂) x)) (And (∀ (x : M₁), LE.le 0 …
  -/
  simp_rw [Prod.forall, prod_apply]
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁸ : CommSemiring R
    inst✝⁷ : AddCommMonoid M₁
    inst✝⁶ : AddCommMonoid M₂
    inst✝⁵ : AddCommMonoid P
    inst✝⁴ : Module R M₁
    inst✝³ : Module R M₂
    inst✝² : Module R P
    inst✝¹ : Preorder P
    inst✝ : AddLeftMono P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Iff (∀ (a : M₁) (b : M₂), LE.le 0 (HAdd.hAdd (Q₁ a) (Q₂ b))) (And (∀ (x : M₁ …
  -/
  constructor
    /-
      case mp
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : Preorder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ⊢ (∀ (a : M₁) (b : M₂), LE.le 0 (HAdd.hAdd (Q₁ a) (Q₂ b))) → And (∀ (x : M₁),  …
    -/
  · intro h
    /-
      case mp
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : Preorder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h : ∀ (a : M₁) (b : M₂), LE.le 0 (HAdd.hAdd (Q₁ a) (Q₂ b))
      ⊢ And (∀ (x : M₁), LE.le 0 (Q₁ x)) (∀ (x : M₂), LE.le 0 (Q₂ x))
    -/
    constructor
      /-
        case mp.left
        R : Type u_2
        M₁ : Type u_3
        M₂ : Type u_4
        P : Type u_7
        inst✝⁸ : CommSemiring R
        inst✝⁷ : AddCommMonoid M₁
        inst✝⁶ : AddCommMonoid M₂
        inst✝⁵ : AddCommMonoid P
        inst✝⁴ : Module R M₁
        inst✝³ : Module R M₂
        inst✝² : Module R P
        inst✝¹ : Preorder P
        inst✝ : AddLeftMono P
        Q₁ : QuadraticMap R M₁ P
        Q₂ : QuadraticMap R M₂ P
        h : ∀ (a : M₁) (b : M₂), LE.le 0 (HAdd.hAdd (Q₁ a) (Q₂ b))
        ⊢ ∀ (x : M₁), LE.le 0 (Q₁ x)
      -/
    · intro x; simpa only [add_zero, map_zero] using h x 0
               /-
                 🎉 no goals
               -/
      /-
        case mp.right
        R : Type u_2
        M₁ : Type u_3
        M₂ : Type u_4
        P : Type u_7
        inst✝⁸ : CommSemiring R
        inst✝⁷ : AddCommMonoid M₁
        inst✝⁶ : AddCommMonoid M₂
        inst✝⁵ : AddCommMonoid P
        inst✝⁴ : Module R M₁
        inst✝³ : Module R M₂
        inst✝² : Module R P
        inst✝¹ : Preorder P
        inst✝ : AddLeftMono P
        Q₁ : QuadraticMap R M₁ P
        Q₂ : QuadraticMap R M₂ P
        h : ∀ (a : M₁) (b : M₂), LE.le 0 (HAdd.hAdd (Q₁ a) (Q₂ b))
        ⊢ ∀ (x : M₂), LE.le 0 (Q₂ x)
      -/
    · intro x; simpa only [zero_add, map_zero] using h 0 x
               /-
                 🎉 no goals
               -/
    /-
      case mpr
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : Preorder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ⊢ And (∀ (x : M₁), LE.le 0 (Q₁ x)) (∀ (x : M₂), LE.le 0 (Q₂ x)) → ∀ (a : M₁) ( …
    -/
  · rintro ⟨h₁, h₂⟩ x₁ x₂
    /-
      case mpr.intro
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : Preorder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      h₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      h₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      x₁ : M₁
      x₂ : M₂
      ⊢ LE.le 0 (HAdd.hAdd (Q₁ x₁) (Q₂ x₂))
    -/
    exact add_nonneg (h₁ x₁) (h₂ x₂)
    /-
      🎉 no goals
    -/


theorem posDef_prod_iff [PartialOrder P] [AddLeftMono P]
    {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P} :
    (Q₁.prod Q₂).PosDef ↔ Q₁.PosDef ∧ Q₂.PosDef := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁸ : CommSemiring R
    inst✝⁷ : AddCommMonoid M₁
    inst✝⁶ : AddCommMonoid M₂
    inst✝⁵ : AddCommMonoid P
    inst✝⁴ : Module R M₁
    inst✝³ : Module R M₂
    inst✝² : Module R P
    inst✝¹ : PartialOrder P
    inst✝ : AddLeftMono P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Iff (Q₁.prod Q₂).PosDef (And Q₁.PosDef Q₂.PosDef)
  -/
  simp_rw [posDef_iff_nonneg, nonneg_prod_iff]
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁸ : CommSemiring R
    inst✝⁷ : AddCommMonoid M₁
    inst✝⁶ : AddCommMonoid M₂
    inst✝⁵ : AddCommMonoid P
    inst✝⁴ : Module R M₁
    inst✝³ : Module R M₂
    inst✝² : Module R P
    inst✝¹ : PartialOrder P
    inst✝ : AddLeftMono P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Iff (And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) (∀ (x : M₂), LE.le 0 (Q₂ x))) (Q₁ …
  -/
  constructor
    /-
      case mp
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ⊢ And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) (∀ (x : M₂), LE.le 0 (Q₂ x))) (Q₁.prod …
    -/
  · rintro ⟨⟨hle₁, hle₂⟩, ha⟩
    /-
      case mp.intro.intro
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ha : (Q₁.prod Q₂).Anisotropic
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ⊢ And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) Q₁.Anisotropic) (And (∀ (x : M₂), LE.l …
    -/
    obtain ⟨ha₁, ha₂⟩ := anisotropic_of_prod ha
    /-
      case mp.intro.intro.intro
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ha : (Q₁.prod Q₂).Anisotropic
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ha₁ : Q₁.Anisotropic
      ha₂ : Q₂.Anisotropic
      ⊢ And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) Q₁.Anisotropic) (And (∀ (x : M₂), LE.l …
    -/
    exact ⟨⟨hle₁, ha₁⟩, ⟨hle₂, ha₂⟩⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      ⊢ And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) Q₁.Anisotropic) (And (∀ (x : M₂), LE.l …
    -/
  · rintro ⟨⟨hle₁, ha₁⟩, ⟨hle₂, ha₂⟩⟩
    /-
      case mpr.intro.intro.intro
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      ha₁ : Q₁.Anisotropic
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ha₂ : Q₂.Anisotropic
      ⊢ And (And (∀ (x : M₁), LE.le 0 (Q₁ x)) (∀ (x : M₂), LE.le 0 (Q₂ x))) (Q₁.prod …
    -/
    refine ⟨⟨hle₁, hle₂⟩, ?_⟩
    /-
      case mpr.intro.intro.intro
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      ha₁ : Q₁.Anisotropic
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ha₂ : Q₂.Anisotropic
      ⊢ (Q₁.prod Q₂).Anisotropic
    -/
    rintro ⟨x₁, x₂⟩ (hx : Q₁ x₁ + Q₂ x₂ = 0)
    /-
      case mpr.intro.intro.intro.mk
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      ha₁ : Q₁.Anisotropic
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ha₂ : Q₂.Anisotropic
      x₁ : M₁
      x₂ : M₂
      hx : Eq (HAdd.hAdd (Q₁ x₁) (Q₂ x₂)) 0
      ⊢ Eq { fst := x₁, snd := x₂ } 0
    -/
    rw [add_eq_zero_iff_of_nonneg (hle₁ x₁) (hle₂ x₂), ha₁.eq_zero_iff, ha₂.eq_zero_iff] at hx
    /-
      case mpr.intro.intro.intro.mk
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      P : Type u_7
      inst✝⁸ : CommSemiring R
      inst✝⁷ : AddCommMonoid M₁
      inst✝⁶ : AddCommMonoid M₂
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : Module R M₁
      inst✝³ : Module R M₂
      inst✝² : Module R P
      inst✝¹ : PartialOrder P
      inst✝ : AddLeftMono P
      Q₁ : QuadraticMap R M₁ P
      Q₂ : QuadraticMap R M₂ P
      hle₁ : ∀ (x : M₁), LE.le 0 (Q₁ x)
      ha₁ : Q₁.Anisotropic
      hle₂ : ∀ (x : M₂), LE.le 0 (Q₂ x)
      ha₂ : Q₂.Anisotropic
      x₁ : M₁
      x₂ : M₂
      hx : And (Eq x₁ 0) (Eq x₂ 0)
      ⊢ Eq { fst := x₁, snd := x₂ } 0
    -/
    rwa [Prod.mk_eq_zero]
    /-
      🎉 no goals
    -/


theorem PosDef.prod [PartialOrder P] [AddLeftMono P]
    {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P} (h₁ : Q₁.PosDef) (h₂ : Q₂.PosDef) :
    (Q₁.prod Q₂).PosDef :=
  posDef_prod_iff.mpr ⟨h₁, h₂⟩


theorem IsOrtho.prod {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    {v w : M₁ × M₂} (h₁ : Q₁.IsOrtho v.1 w.1) (h₂ : Q₂.IsOrtho v.2 w.2) :
    (Q₁.prod Q₂).IsOrtho v w :=
  (congr_arg₂ HAdd.hAdd h₁ h₂).trans <| add_add_add_comm _ _ _ _


@[simp] theorem IsOrtho.inl_inr {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    (m₁ : M₁) (m₂ : M₂) :
    (Q₁.prod Q₂).IsOrtho (m₁, 0) (0, m₂) :=
      QuadraticMap.IsOrtho.prod (.zero_right _) (.zero_left _)


@[simp] theorem IsOrtho.inr_inl {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    (m₁ : M₁) (m₂ : M₂) :
    (Q₁.prod Q₂).IsOrtho (0, m₂) (m₁, 0) := (IsOrtho.inl_inr _ _).symm


@[simp] theorem isOrtho_inl_inl_iff {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    (m₁ m₁' : M₁) :
    (Q₁.prod Q₂).IsOrtho (m₁, 0) (m₁', 0) ↔ Q₁.IsOrtho m₁ m₁' := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommSemiring R
    inst✝⁵ : AddCommMonoid M₁
    inst✝⁴ : AddCommMonoid M₂
    inst✝³ : AddCommMonoid P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    m₁ m₁' : M₁
    ⊢ Iff ((Q₁.prod Q₂).IsOrtho { fst := m₁, snd := 0 } { fst := m₁', snd := 0 })  …
  -/
  simp [isOrtho_def]
  /-
    🎉 no goals
  -/


@[simp] theorem isOrtho_inr_inr_iff {Q₁ : QuadraticMap R M₁ P} {Q₂ : QuadraticMap R M₂ P}
    (m₂ m₂' : M₂) :
    (Q₁.prod Q₂).IsOrtho (0, m₂) (0, m₂') ↔ Q₂.IsOrtho m₂ m₂' := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommSemiring R
    inst✝⁵ : AddCommMonoid M₁
    inst✝⁴ : AddCommMonoid M₂
    inst✝³ : AddCommMonoid P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    m₂ m₂' : M₂
    ⊢ Iff ((Q₁.prod Q₂).IsOrtho { fst := 0, snd := m₂ } { fst := 0, snd := m₂' })  …
  -/
  simp [isOrtho_def]
  /-
    🎉 no goals
  -/


@[simp] theorem polar_prod (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) (x y : M₁ × M₂) :
    polar (Q₁.prod Q₂) x y = polar Q₁ x.1 y.1 + polar Q₂ x.2 y.2 := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommRing R
    inst✝⁵ : AddCommGroup M₁
    inst✝⁴ : AddCommGroup M₂
    inst✝³ : AddCommGroup P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    x y : Prod M₁ M₂
    ⊢ Eq (QuadraticMap.polar (⇑(Q₁.prod Q₂)) x y) (HAdd.hAdd (QuadraticMap.polar ( …
  -/
  dsimp [polar]
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁶ : CommRing R
    inst✝⁵ : AddCommGroup M₁
    inst✝⁴ : AddCommGroup M₂
    inst✝³ : AddCommGroup P
    inst✝² : Module R M₁
    inst✝¹ : Module R M₂
    inst✝ : Module R P
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    x y : Prod M₁ M₂
    ⊢ Eq (HSub.hSub (HSub.hSub (HAdd.hAdd (Q₁ (HAdd.hAdd x.1 y.1)) (Q₂ (HAdd.hAdd  …
  -/
  /-
    🎉 no goals
  -/
  abel
  /-
    🎉 no goals
  -/


@[simp] theorem polarBilin_prod (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) :
    (Q₁.prod Q₂).polarBilin =
      Q₁.polarBilin.compl₁₂ (.fst R M₁ M₂) (.fst R M₁ M₂) +
      Q₂.polarBilin.compl₁₂ (.snd R M₁ M₂) (.snd R M₁ M₂) :=
  LinearMap.ext₂ <| polar_prod _ _


@[simp] theorem associated_prod [Invertible (2 : R)]
    (Q₁ : QuadraticMap R M₁ P) (Q₂ : QuadraticMap R M₂ P) :
    associated (Q₁.prod Q₂) =
      (associated Q₁).compl₁₂ (.fst R M₁ M₂) (.fst R M₁ M₂) +
      (associated Q₂).compl₁₂ (.snd R M₁ M₂) (.snd R M₁ M₂) := by
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁷ : CommRing R
    inst✝⁶ : AddCommGroup M₁
    inst✝⁵ : AddCommGroup M₂
    inst✝⁴ : AddCommGroup P
    inst✝³ : Module R M₁
    inst✝² : Module R M₂
    inst✝¹ : Module R P
    inst✝ : Invertible 2
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Eq (QuadraticMap.associated (Q₁.prod Q₂)) (HAdd.hAdd (LinearMap.compl₁₂ (Qua …
  -/
  dsimp [associated, associatedHom]
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁷ : CommRing R
    inst✝⁶ : AddCommGroup M₁
    inst✝⁵ : AddCommGroup M₂
    inst✝⁴ : AddCommGroup P
    inst✝³ : Module R M₁
    inst✝² : Module R M₂
    inst✝¹ : Module R P
    inst✝ : Invertible 2
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Eq (HSMul.hSMul (Invertible.invOf 2) (Q₁.prod Q₂).polarBilin) (HAdd.hAdd (Li …
  -/
  rw [polarBilin_prod, smul_add]
  /-
    R : Type u_2
    M₁ : Type u_3
    M₂ : Type u_4
    P : Type u_7
    inst✝⁷ : CommRing R
    inst✝⁶ : AddCommGroup M₁
    inst✝⁵ : AddCommGroup M₂
    inst✝⁴ : AddCommGroup P
    inst✝³ : Module R M₁
    inst✝² : Module R M₂
    inst✝¹ : Module R P
    inst✝ : Invertible 2
    Q₁ : QuadraticMap R M₁ P
    Q₂ : QuadraticMap R M₂ P
    ⊢ Eq (HAdd.hAdd (HSMul.hSMul (Invertible.invOf 2) (LinearMap.compl₁₂ Q₁.polarB …
  -/
  rfl
  /-
    🎉 no goals
  -/


/-- Construct a quadratic form on a family of modules from the quadratic form on each module. -/
def pi [Fintype ι] (Q : ∀ i, QuadraticMap R (Mᵢ i) P) : QuadraticMap R (∀ i, Mᵢ i) P :=
  ∑ i, (Q i).comp (LinearMap.proj i : _ →ₗ[R] Mᵢ i)


@[simp]
theorem pi_apply [Fintype ι] (Q : ∀ i, QuadraticMap R (Mᵢ i) P) (x : ∀ i, Mᵢ i) :
    pi Q x = ∑ i, Q i (x i) :=
  sum_apply _ _ _


theorem pi_apply_single [Fintype ι] [DecidableEq ι]
    (Q : ∀ i, QuadraticMap R (Mᵢ i) P) (i : ι) (m : Mᵢ i) :
    pi Q (Pi.single i m) = Q i m := by
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁶ : CommSemiring R
    inst✝⁵ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝⁴ : AddCommMonoid P
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    inst✝² : Module R P
    inst✝¹ : Fintype ι
    inst✝ : DecidableEq ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    i : ι
    m : Mᵢ i
    ⊢ Eq ((QuadraticMap.pi Q) (Pi.single i m)) ((Q i) m)
  -/
  rw [pi_apply, Fintype.sum_eq_single i fun j hj => ?_, Pi.single_eq_same]
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁶ : CommSemiring R
    inst✝⁵ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝⁴ : AddCommMonoid P
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    inst✝² : Module R P
    inst✝¹ : Fintype ι
    inst✝ : DecidableEq ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    i : ι
    m : Mᵢ i
    j : ι
    hj : Ne j i
    ⊢ Eq ((Q j) (Pi.single i m j)) 0
  -/
  rw [Pi.single_eq_of_ne hj, map_zero]
  /-
    🎉 no goals
  -/


/-- An isometry between quadratic forms generated by `QuadraticMap.pi` can be constructed
from a pair of isometries between the left and right parts. -/
@[simps toLinearEquiv]
def IsometryEquiv.pi [Fintype ι]
    {Q : ∀ i, QuadraticMap R (Mᵢ i) P} {Q' : ∀ i, QuadraticMap R (Nᵢ i) P}
    (e : ∀ i, (Q i).IsometryEquiv (Q' i)) : (pi Q).IsometryEquiv (pi Q') where
  map_app' x := by
    simp only [pi_apply, LinearEquiv.piCongrRight, LinearEquiv.toFun_eq_coe,
      IsometryEquiv.coe_toLinearEquiv, IsometryEquiv.map_app]
  toLinearEquiv := LinearEquiv.piCongrRight fun i => (e i : Mᵢ i ≃ₗ[R] Nᵢ i)


/-- `LinearMap.single` as an isometry. -/
@[simps!]
def Isometry.single [Fintype ι] [DecidableEq ι] (Q : ∀ i, QuadraticMap R (Mᵢ i) P) (i : ι) :
    Q i →qᵢ pi Q where
  toLinearMap := LinearMap.single _ _ i
  map_app' := pi_apply_single _ _


/-- `LinearMap.proj` as an isometry, when all but one quadratic form is zero. -/
@[simps!]
def Isometry.proj [Fintype ι] [DecidableEq ι] (i : ι) (Q : QuadraticMap R (Mᵢ i) P) :
    pi (Pi.single i Q) →qᵢ Q where
  toLinearMap := LinearMap.proj i
  map_app' m := by
    /-
      ι : Type u_1
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      N₁ : Type u_5
      N₂ : Type u_6
      P : Type u_7
      Mᵢ : ι → Type u_8
      Nᵢ : ι → Type u_9
      inst✝⁸ : CommSemiring R
      inst✝⁷ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝⁶ : (i : ι) → AddCommMonoid (Nᵢ i)
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : (i : ι) → Module R (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Nᵢ i)
      inst✝² : Module R P
      inst✝¹ : Fintype ι
      inst✝ : DecidableEq ι
      i : ι
      Q : QuadraticMap R (Mᵢ i) P
      m : (i : ι) → Mᵢ i
      ⊢ Eq (Q ((LinearMap.proj i).toFun m)) ((QuadraticMap.pi (Pi.single i Q)) m)
    -/
    dsimp
    /-
      ι : Type u_1
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      N₁ : Type u_5
      N₂ : Type u_6
      P : Type u_7
      Mᵢ : ι → Type u_8
      Nᵢ : ι → Type u_9
      inst✝⁸ : CommSemiring R
      inst✝⁷ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝⁶ : (i : ι) → AddCommMonoid (Nᵢ i)
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : (i : ι) → Module R (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Nᵢ i)
      inst✝² : Module R P
      inst✝¹ : Fintype ι
      inst✝ : DecidableEq ι
      i : ι
      Q : QuadraticMap R (Mᵢ i) P
      m : (i : ι) → Mᵢ i
      ⊢ Eq (Q (m i)) ((QuadraticMap.pi (Pi.single i Q)) m)
    -/
    rw [pi_apply, Fintype.sum_eq_single i (fun j hij => ?_), Pi.single_eq_same]
    /-
      ι : Type u_1
      R : Type u_2
      M₁ : Type u_3
      M₂ : Type u_4
      N₁ : Type u_5
      N₂ : Type u_6
      P : Type u_7
      Mᵢ : ι → Type u_8
      Nᵢ : ι → Type u_9
      inst✝⁸ : CommSemiring R
      inst✝⁷ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝⁶ : (i : ι) → AddCommMonoid (Nᵢ i)
      inst✝⁵ : AddCommMonoid P
      inst✝⁴ : (i : ι) → Module R (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Nᵢ i)
      inst✝² : Module R P
      inst✝¹ : Fintype ι
      inst✝ : DecidableEq ι
      i : ι
      Q : QuadraticMap R (Mᵢ i) P
      m : (i : ι) → Mᵢ i
      j : ι
      hij : Ne j i
      ⊢ Eq ((Pi.single i Q j) (m j)) 0
    -/
    rw [Pi.single_eq_of_ne hij, zero_apply]
    /-
      🎉 no goals
    -/


/-- Note that `QuadraticMap.Isometry.id` would not be well-typed as the RHS. -/
@[simp, nolint simpNF]  -- ignore the bogus "Left-hand side does not simplify" lint error
theorem Isometry.proj_comp_single_of_same [Fintype ι] [DecidableEq ι]
    (i : ι) (Q : QuadraticMap R (Mᵢ i) P) :
    (proj i Q).comp (single _ i) = .ofEq (Pi.single_eq_same _ _) :=
  ext fun _ => Pi.single_eq_same _ _


/-- Note that `0 : 0 →qᵢ Q` alone would not be well-typed as the RHS. -/
@[simp]
theorem Isometry.proj_comp_single_of_ne [Fintype ι] [DecidableEq ι]
    {i j : ι} (h : i ≠ j) (Q : QuadraticMap R (Mᵢ i) P) :
    (proj i Q).comp (single _ j) = (0 : 0 →qᵢ Q).comp (ofEq (Pi.single_eq_of_ne h.symm _)) :=
  ext fun _ => Pi.single_eq_of_ne h _


theorem Equivalent.pi [Fintype ι] {Q : ∀ i, QuadraticMap R (Mᵢ i) P}
    {Q' : ∀ i, QuadraticMap R (Nᵢ i) P} (e : ∀ i, (Q i).Equivalent (Q' i)) :
    (pi Q).Equivalent (pi Q') :=
  ⟨IsometryEquiv.pi fun i => Classical.choice (e i)⟩


/-- If a family is anisotropic then its components must be. The converse is not true. -/
theorem anisotropic_of_pi [Fintype ι]
    {Q : ∀ i, QuadraticMap R (Mᵢ i) P} (h : (pi Q).Anisotropic) : ∀ i, (Q i).Anisotropic := by
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : AddCommMonoid P
    inst✝² : (i : ι) → Module R (Mᵢ i)
    inst✝¹ : Module R P
    inst✝ : Fintype ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    h : (QuadraticMap.pi Q).Anisotropic
    ⊢ ∀ (i : ι), (Q i).Anisotropic
  -/
  simp_rw [Anisotropic, pi_apply, funext_iff, Pi.zero_apply] at h
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : AddCommMonoid P
    inst✝² : (i : ι) → Module R (Mᵢ i)
    inst✝¹ : Module R P
    inst✝ : Fintype ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    h : ∀ (x : (i : ι) → Mᵢ i), Eq (Finset.univ.sum fun i => (Q i) (x i)) 0 → ∀ (x …
    ⊢ ∀ (i : ι), (Q i).Anisotropic
  -/
  intro i x hx
  classical
  have := h (Pi.single i x) ?_ i
  · rw [Pi.single_eq_same] at this
    exact this
  apply Finset.sum_eq_zero
  intro j _
  by_cases hji : j = i
  · subst hji; rw [Pi.single_eq_same, hx]
  · rw [Pi.single_eq_of_ne hji, map_zero]


theorem nonneg_pi_iff {P} [Fintype ι] [OrderedAddCommMonoid P] [Module R P]
    {Q : ∀ i, QuadraticMap R (Mᵢ i) P} : (∀ x, 0 ≤ pi Q x) ↔ ∀ i x, 0 ≤ Q i x := by
  /-
    ι : Type u_1
    R : Type u_2
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    P : Type u_10
    inst✝² : Fintype ι
    inst✝¹ : OrderedAddCommMonoid P
    inst✝ : Module R P
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Iff (∀ (x : (i : ι) → Mᵢ i), LE.le 0 ((QuadraticMap.pi Q) x)) (∀ (i : ι) (x  …
  -/
  simp_rw [pi, sum_apply, comp_apply, LinearMap.proj_apply]
  /-
    ι : Type u_1
    R : Type u_2
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    P : Type u_10
    inst✝² : Fintype ι
    inst✝¹ : OrderedAddCommMonoid P
    inst✝ : Module R P
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Iff (∀ (x : (i : ι) → Mᵢ i), LE.le 0 (Finset.univ.sum fun x_1 => (Q x_1) (x  …
  -/
  constructor
  -- TODO: does this generalize to a useful lemma independent of `QuadraticMap`?
    /-
      case mp
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      ⊢ (∀ (x : (i : ι) → Mᵢ i), LE.le 0 (Finset.univ.sum fun x_1 => (Q x_1) (x x_1) …
    -/
  · intro h i x
    classical
    convert h (Pi.single i x) using 1
    rw [Finset.sum_eq_single_of_mem i (Finset.mem_univ _) fun j _ hji => ?_, Pi.single_eq_same]
    rw [Pi.single_eq_of_ne hji, map_zero]
    /-
      case mpr
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      ⊢ (∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)) → ∀ (x : (i : ι) → Mᵢ i), LE.le 0  …
    -/
  · rintro h x
    /-
      case mpr
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      h : ∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)
      x : (i : ι) → Mᵢ i
      ⊢ LE.le 0 (Finset.univ.sum fun x_1 => (Q x_1) (x x_1))
    -/
    exact Finset.sum_nonneg fun i _ => h i (x i)
    /-
      🎉 no goals
    -/


theorem posDef_pi_iff {P} [Fintype ι] [OrderedAddCommMonoid P] [Module R P]
    {Q : ∀ i, QuadraticMap R (Mᵢ i) P} : (pi Q).PosDef ↔ ∀ i, (Q i).PosDef := by
  /-
    ι : Type u_1
    R : Type u_2
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    P : Type u_10
    inst✝² : Fintype ι
    inst✝¹ : OrderedAddCommMonoid P
    inst✝ : Module R P
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Iff (QuadraticMap.pi Q).PosDef (∀ (i : ι), (Q i).PosDef)
  -/
  simp_rw [posDef_iff_nonneg, nonneg_pi_iff]
  /-
    ι : Type u_1
    R : Type u_2
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommSemiring R
    inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    P : Type u_10
    inst✝² : Fintype ι
    inst✝¹ : OrderedAddCommMonoid P
    inst✝ : Module R P
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Iff (And (∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)) (QuadraticMap.pi Q).Aniso …
  -/
  constructor
    /-
      case mp
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      ⊢ And (∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)) (QuadraticMap.pi Q).Anisotropi …
    -/
  · rintro ⟨hle, ha⟩
    /-
      case mp.intro
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      hle : ∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)
      ha : (QuadraticMap.pi Q).Anisotropic
      ⊢ ∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
    -/
    intro i
    /-
      case mp.intro
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      hle : ∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)
      ha : (QuadraticMap.pi Q).Anisotropic
      i : ι
      ⊢ And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
    -/
    exact ⟨hle i, anisotropic_of_pi ha i⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      ⊢ (∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic) → And ( …
    -/
  · intro h
    /-
      case mpr
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      h : ∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
      ⊢ And (∀ (i : ι) (x : Mᵢ i), LE.le 0 ((Q i) x)) (QuadraticMap.pi Q).Anisotropic
    -/
    refine ⟨fun i => (h i).1, fun x hx => funext fun i => (h i).2 _ ?_⟩
    /-
      case mpr
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      h : ∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
      x : (i : ι) → Mᵢ i
      hx : Eq ((QuadraticMap.pi Q) x) 0
      i : ι
      ⊢ Eq ((Q i) (x i)) 0
    -/
    rw [pi_apply, Finset.sum_eq_zero_iff_of_nonneg fun j _ => ?_] at hx
      /-
        case mpr
        ι : Type u_1
        R : Type u_2
        Mᵢ : ι → Type u_8
        inst✝⁵ : CommSemiring R
        inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
        inst✝³ : (i : ι) → Module R (Mᵢ i)
        P : Type u_10
        inst✝² : Fintype ι
        inst✝¹ : OrderedAddCommMonoid P
        inst✝ : Module R P
        Q : (i : ι) → QuadraticMap R (Mᵢ i) P
        h : ∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
        x : (i : ι) → Mᵢ i
        hx : ∀ (i : ι), Membership.mem Finset.univ i → Eq ((Q i) (x i)) 0
        i : ι
        ⊢ Eq ((Q i) (x i)) 0
      -/
    · exact hx _ (Finset.mem_univ _)
      /-
        🎉 no goals
      -/
    /-
      ι : Type u_1
      R : Type u_2
      Mᵢ : ι → Type u_8
      inst✝⁵ : CommSemiring R
      inst✝⁴ : (i : ι) → AddCommMonoid (Mᵢ i)
      inst✝³ : (i : ι) → Module R (Mᵢ i)
      P : Type u_10
      inst✝² : Fintype ι
      inst✝¹ : OrderedAddCommMonoid P
      inst✝ : Module R P
      Q : (i : ι) → QuadraticMap R (Mᵢ i) P
      h : ∀ (i : ι), And (∀ (x : Mᵢ i), LE.le 0 ((Q i) x)) (Q i).Anisotropic
      x : (i : ι) → Mᵢ i
      hx : Eq (Finset.univ.sum fun i => (Q i) (x i)) 0
      i j : ι
      x✝ : Membership.mem Finset.univ j
      ⊢ LE.le 0 ((Q j) (x j))
    -/
    exact (h j).1 _
    /-
      🎉 no goals
    -/


@[simp] theorem polar_pi (Q : ∀ i, QuadraticMap R (Mᵢ i) P) (x y : ∀ i, Mᵢ i) :
    polar (pi Q) x y = ∑ i, polar (Q i) (x i) (y i) := by
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommRing R
    inst✝⁴ : (i : ι) → AddCommGroup (Mᵢ i)
    inst✝³ : AddCommGroup P
    inst✝² : (i : ι) → Module R (Mᵢ i)
    inst✝¹ : Module R P
    inst✝ : Fintype ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    x y : (i : ι) → Mᵢ i
    ⊢ Eq (QuadraticMap.polar (⇑(QuadraticMap.pi Q)) x y) (Finset.univ.sum fun i => …
  -/
  dsimp [polar]
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁵ : CommRing R
    inst✝⁴ : (i : ι) → AddCommGroup (Mᵢ i)
    inst✝³ : AddCommGroup P
    inst✝² : (i : ι) → Module R (Mᵢ i)
    inst✝¹ : Module R P
    inst✝ : Fintype ι
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    x y : (i : ι) → Mᵢ i
    ⊢ Eq (HSub.hSub (HSub.hSub ((QuadraticMap.pi Q) (HAdd.hAdd x y)) ((QuadraticMa …
  -/
  simp_rw [Finset.sum_sub_distrib, pi_apply, Pi.add_apply]
  /-
    🎉 no goals
  -/


@[simp] theorem polarBilin_pi (Q : ∀ i, QuadraticMap R (Mᵢ i) P) :
    (pi Q).polarBilin = ∑ i, (Q i).polarBilin.compl₁₂ (.proj i) (.proj i) :=
                                                         /-
                                                           ι : Type u_1
                                                           R : Type u_2
                                                           P : Type u_7
                                                           Mᵢ : ι → Type u_8
                                                           inst✝⁵ : CommRing R
                                                           inst✝⁴ : (i : ι) → AddCommGroup (Mᵢ i)
                                                           inst✝³ : AddCommGroup P
                                                           inst✝² : (i : ι) → Module R (Mᵢ i)
                                                           inst✝¹ : Module R P
                                                           inst✝ : Fintype ι
                                                           Q : (i : ι) → QuadraticMap R (Mᵢ i) P
                                                           x y : (i : ι) → Mᵢ i
                                                           ⊢ Eq (Finset.univ.sum fun i => QuadraticMap.polar (⇑(Q i)) (x i) (y i)) (((Fin …
                                                         -/
  LinearMap.ext₂ fun x y => (polar_pi _ _ _).trans <| by simp
                                                         /-
                                                           🎉 no goals
                                                         -/


@[simp] theorem associated_pi [Invertible (2 : R)] (Q : ∀ i, QuadraticMap R (Mᵢ i) P) :
    associated (pi Q) = ∑ i, (Q i).associated.compl₁₂ (.proj i) (.proj i) := by
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁶ : CommRing R
    inst✝⁵ : (i : ι) → AddCommGroup (Mᵢ i)
    inst✝⁴ : AddCommGroup P
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    inst✝² : Module R P
    inst✝¹ : Fintype ι
    inst✝ : Invertible 2
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Eq (QuadraticMap.associated (QuadraticMap.pi Q)) (Finset.univ.sum fun i => L …
  -/
  dsimp [associated, associatedHom]
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁶ : CommRing R
    inst✝⁵ : (i : ι) → AddCommGroup (Mᵢ i)
    inst✝⁴ : AddCommGroup P
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    inst✝² : Module R P
    inst✝¹ : Fintype ι
    inst✝ : Invertible 2
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Eq (HSMul.hSMul (Invertible.invOf 2) (QuadraticMap.pi Q).polarBilin) (Finset …
  -/
  rw [polarBilin_pi, Finset.smul_sum]
  /-
    ι : Type u_1
    R : Type u_2
    P : Type u_7
    Mᵢ : ι → Type u_8
    inst✝⁶ : CommRing R
    inst✝⁵ : (i : ι) → AddCommGroup (Mᵢ i)
    inst✝⁴ : AddCommGroup P
    inst✝³ : (i : ι) → Module R (Mᵢ i)
    inst✝² : Module R P
    inst✝¹ : Fintype ι
    inst✝ : Invertible 2
    Q : (i : ι) → QuadraticMap R (Mᵢ i) P
    ⊢ Eq (Finset.univ.sum fun x => HSMul.hSMul (Invertible.invOf 2) (LinearMap.com …
  -/
  rfl
  /-
    🎉 no goals
  -/


