/-- Given the condition `[Sub n]` and a vector `v : n → α`,
    we define `circulant v` to be the circulant matrix generated by `v` of type `Matrix n n α`.
    The `(i,j)`th entry is defined to be `v (i - j)`. -/
def circulant [Sub n] (v : n → α) : Matrix n n α :=
  of fun i j => v (i - j)

-- TODO: set as an equation lemma for `circulant`, see https://github.com/leanprover-community/mathlib4/pull/3024

@[simp]
theorem circulant_apply [Sub n] (v : n → α) (i j) : circulant v i j = v (i - j) := rfl


theorem circulant_col_zero_eq [AddGroup n] (v : n → α) (i : n) : circulant v i 0 = v i :=
  congr_arg v (sub_zero _)


theorem circulant_injective [AddGroup n] : Injective (circulant : (n → α) → Matrix n n α) := by
  /-
    α : Type u_1
    n : Type u_3
    inst✝ : AddGroup n
    ⊢ Function.Injective Matrix.circulant
  -/
  intro v w h
  /-
    α : Type u_1
    n : Type u_3
    inst✝ : AddGroup n
    v w : n → α
    h : Eq (Matrix.circulant v) (Matrix.circulant w)
    ⊢ Eq v w
  -/
  ext k
  /-
    case h
    α : Type u_1
    n : Type u_3
    inst✝ : AddGroup n
    v w : n → α
    h : Eq (Matrix.circulant v) (Matrix.circulant w)
    k : n
    ⊢ Eq (v k) (w k)
  -/
  rw [← circulant_col_zero_eq v, ← circulant_col_zero_eq w, h]
  /-
    🎉 no goals
  -/


theorem Fin.circulant_injective : ∀ n, Injective fun v : Fin n → α => circulant v
            /-
              α : Type u_1
              ⊢ Function.Injective fun v => Matrix.circulant v
            -/
  | 0 => by simp [Injective]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.circulant_injective


@[simp]
theorem circulant_inj [AddGroup n] {v w : n → α} : circulant v = circulant w ↔ v = w :=
  circulant_injective.eq_iff


@[simp]
theorem Fin.circulant_inj {n} {v w : Fin n → α} : circulant v = circulant w ↔ v = w :=
  (Fin.circulant_injective n).eq_iff


theorem transpose_circulant [AddGroup n] (v : n → α) :
                                                     /-
                                                       α : Type u_1
                                                       n : Type u_3
                                                       inst✝ : AddGroup n
                                                       v : n → α
                                                       ⊢ Eq (Matrix.circulant v).transpose (Matrix.circulant fun i => v (Neg.neg i))
                                                     -/
    (circulant v)ᵀ = circulant fun i => v (-i) := by ext; simp
                                                          /-
                                                            🎉 no goals
                                                          -/


theorem conjTranspose_circulant [Star α] [AddGroup n] (v : n → α) :
                                                            /-
                                                              α : Type u_1
                                                              n : Type u_3
                                                              inst✝¹ : Star α
                                                              inst✝ : AddGroup n
                                                              v : n → α
                                                              ⊢ Eq (Matrix.circulant v).conjTranspose (Matrix.circulant (Star.star fun i =>  …
                                                            -/
    (circulant v)ᴴ = circulant (star fun i => v (-i)) := by ext; simp
                                                                 /-
                                                                   🎉 no goals
                                                                 -/


theorem Fin.transpose_circulant : ∀ {n} (v : Fin n → α), (circulant v)ᵀ = circulant fun i => v (-i)
            /-
              α : Type u_1
              ⊢ ∀ (v : Fin 0 → α), Eq (Matrix.circulant v).transpose (Matrix.circulant fun i …
            -/
  | 0 => by simp [Injective, eq_iff_true_of_subsingleton]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.transpose_circulant


theorem Fin.conjTranspose_circulant [Star α] :
    ∀ {n} (v : Fin n → α), (circulant v)ᴴ = circulant (star fun i => v (-i))
            /-
              α : Type u_1
              inst✝ : Star α
              ⊢ ∀ (v : Fin 0 → α), Eq (Matrix.circulant v).conjTranspose (Matrix.circulant ( …
            -/
  | 0 => by simp [Injective, eq_iff_true_of_subsingleton]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.conjTranspose_circulant


theorem map_circulant [Sub n] (v : n → α) (f : α → β) :
    (circulant v).map f = circulant fun i => f (v i) :=
  ext fun _ _ => rfl


theorem circulant_neg [Neg α] [Sub n] (v : n → α) : circulant (-v) = -circulant v :=
  ext fun _ _ => rfl


@[simp]
theorem circulant_zero (α n) [Zero α] [Sub n] : circulant 0 = (0 : Matrix n n α) :=
  ext fun _ _ => rfl


theorem circulant_add [Add α] [Sub n] (v w : n → α) :
    circulant (v + w) = circulant v + circulant w :=
  ext fun _ _ => rfl


theorem circulant_sub [Sub α] [Sub n] (v w : n → α) :
    circulant (v - w) = circulant v - circulant w :=
  ext fun _ _ => rfl


/-- The product of two circulant matrices `circulant v` and `circulant w` is
    the circulant matrix generated by `circulant v *ᵥ w`. -/
theorem circulant_mul [Semiring α] [Fintype n] [AddGroup n] (v w : n → α) :
    circulant v * circulant w = circulant (circulant v *ᵥ w) := by
  /-
    α : Type u_1
    n : Type u_3
    inst✝² : Semiring α
    inst✝¹ : Fintype n
    inst✝ : AddGroup n
    v w : n → α
    ⊢ Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w)) (Matrix.circulant ( …
  -/
  ext i j
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝² : Semiring α
    inst✝¹ : Fintype n
    inst✝ : AddGroup n
    v w : n → α
    i j : n
    ⊢ Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w) i j) (Matrix.circula …
  -/
  simp only [mul_apply, mulVec, circulant_apply, dotProduct]
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝² : Semiring α
    inst✝¹ : Fintype n
    inst✝ : AddGroup n
    v w : n → α
    i j : n
    ⊢ Eq (Finset.univ.sum fun x => HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j …
  -/
  refine Fintype.sum_equiv (Equiv.subRight j) _ _ ?_
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝² : Semiring α
    inst✝¹ : Fintype n
    inst✝ : AddGroup n
    v w : n → α
    i j : n
    ⊢ ∀ (x : n), Eq (HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j))) (HMul.hMul …
  -/
  intro x
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝² : Semiring α
    inst✝¹ : Fintype n
    inst✝ : AddGroup n
    v w : n → α
    i j x : n
    ⊢ Eq (HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j))) (HMul.hMul (v (HSub.h …
  -/
  simp only [Equiv.subRight_apply, sub_sub_sub_cancel_right]
  /-
    🎉 no goals
  -/


theorem Fin.circulant_mul [Semiring α] :
    ∀ {n} (v w : Fin n → α), circulant v * circulant w = circulant (circulant v *ᵥ w)
            /-
              α : Type u_1
              inst✝ : Semiring α
              ⊢ ∀ (v w : Fin 0 → α), Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w) …
            -/
  | 0 => by simp [Injective, eq_iff_true_of_subsingleton]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.circulant_mul


/-- Multiplication of circulant matrices commutes when the elements do. -/
theorem circulant_mul_comm [CommSemigroup α] [AddCommMonoid α] [Fintype n] [AddCommGroup n]
    (v w : n → α) : circulant v * circulant w = circulant w * circulant v := by
  /-
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    ⊢ Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w)) (HMul.hMul (Matrix. …
  -/
  ext i j
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    i j : n
    ⊢ Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w) i j) (HMul.hMul (Mat …
  -/
  simp only [mul_apply, circulant_apply, mul_comm]
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    i j : n
    ⊢ Eq (Finset.univ.sum fun x => HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j …
  -/
  refine Fintype.sum_equiv ((Equiv.subLeft i).trans (Equiv.addRight j)) _ _ ?_
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    i j : n
    ⊢ ∀ (x : n), Eq (HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j))) (HMul.hMul …
  -/
  intro x
  simp only [Equiv.trans_apply, Equiv.subLeft_apply, Equiv.coe_addRight, add_sub_cancel_right,
    mul_comm]
  /-
    case a
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    i j x : n
    ⊢ Eq (HMul.hMul (v (HSub.hSub i x)) (w (HSub.hSub x j))) (HMul.hMul (v (HSub.h …
  -/
  congr 2
  /-
    case a.e_a.e_a
    α : Type u_1
    n : Type u_3
    inst✝³ : CommSemigroup α
    inst✝² : AddCommMonoid α
    inst✝¹ : Fintype n
    inst✝ : AddCommGroup n
    v w : n → α
    i j x : n
    ⊢ Eq (HSub.hSub x j) (HSub.hSub i (HAdd.hAdd (HSub.hSub i x) j))
  -/
  /-
    🎉 no goals
  -/
  abel
  /-
    🎉 no goals
  -/


theorem Fin.circulant_mul_comm [CommSemigroup α] [AddCommMonoid α] :
    ∀ {n} (v w : Fin n → α), circulant v * circulant w = circulant w * circulant v
            /-
              α : Type u_1
              inst✝¹ : CommSemigroup α
              inst✝ : AddCommMonoid α
              ⊢ ∀ (v w : Fin 0 → α), Eq (HMul.hMul (Matrix.circulant v) (Matrix.circulant w) …
            -/
  | 0 => by simp [Injective]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.circulant_mul_comm


/-- `k • circulant v` is another circulant matrix `circulant (k • v)`. -/
theorem circulant_smul [Sub n] [SMul R α] (k : R) (v : n → α) :
    circulant (k • v) = k • circulant v := rfl


@[simp]
theorem circulant_single_one (α n) [Zero α] [One α] [DecidableEq n] [AddGroup n] :
    circulant (Pi.single 0 1 : n → α) = (1 : Matrix n n α) := by
  /-
    α : Type u_5
    n : Type u_6
    inst✝³ : Zero α
    inst✝² : One α
    inst✝¹ : DecidableEq n
    inst✝ : AddGroup n
    ⊢ Eq (Matrix.circulant (Pi.single 0 1)) 1
  -/
  ext i j
  /-
    case a
    α : Type u_5
    n : Type u_6
    inst✝³ : Zero α
    inst✝² : One α
    inst✝¹ : DecidableEq n
    inst✝ : AddGroup n
    i j : n
    ⊢ Eq (Matrix.circulant (Pi.single 0 1) i j) (1 i j)
  -/
  simp [one_apply, Pi.single_apply, sub_eq_zero]
  /-
    🎉 no goals
  -/


@[simp]
theorem circulant_single (n) [Semiring α] [DecidableEq n] [AddGroup n] [Fintype n] (a : α) :
    circulant (Pi.single 0 a : n → α) = scalar n a := by
  /-
    α : Type u_1
    n : Type u_5
    inst✝³ : Semiring α
    inst✝² : DecidableEq n
    inst✝¹ : AddGroup n
    inst✝ : Fintype n
    a : α
    ⊢ Eq (Matrix.circulant (Pi.single 0 a)) ((Matrix.scalar n) a)
  -/
  ext i j
  /-
    case a
    α : Type u_1
    n : Type u_5
    inst✝³ : Semiring α
    inst✝² : DecidableEq n
    inst✝¹ : AddGroup n
    inst✝ : Fintype n
    a : α
    i j : n
    ⊢ Eq (Matrix.circulant (Pi.single 0 a) i j) ((Matrix.scalar n) a i j)
  -/
  simp [Pi.single_apply, diagonal_apply, sub_eq_zero]
  /-
    🎉 no goals
  -/


/-- Note we use `↑i = 0` instead of `i = 0` as `Fin 0` has no `0`.
This means that we cannot state this with `Pi.single` as we did with `Matrix.circulant_single`. -/
theorem Fin.circulant_ite (α) [Zero α] [One α] :
    ∀ n, circulant (fun i => ite (i.1 = 0) 1 0 : Fin n → α) = 1
            /-
              α : Type u_5
              inst✝¹ : Zero α
              inst✝ : One α
              ⊢ Eq (Matrix.circulant fun i => ite (Eq (↑i) 0) 1 0) 1
            -/
  | 0 => by simp [Injective, eq_iff_true_of_subsingleton]
            /-
              🎉 no goals
            -/
  | n + 1 => by
    /-
      α : Type u_5
      inst✝¹ : Zero α
      inst✝ : One α
      n : Nat
      ⊢ Eq (Matrix.circulant fun i => ite (Eq (↑i) 0) 1 0) 1
    -/
    rw [← circulant_single_one]
    /-
      α : Type u_5
      inst✝¹ : Zero α
      inst✝ : One α
      n : Nat
      ⊢ Eq (Matrix.circulant fun i => ite (Eq (↑i) 0) 1 0) (Matrix.circulant (Pi.sin …
    -/
    congr with j
    /-
      case a
      α : Type u_5
      inst✝¹ : Zero α
      inst✝ : One α
      n : Nat
      j j✝ : Fin (HAdd.hAdd n 1)
      ⊢ Eq (Matrix.circulant (fun i => ite (Eq (↑i) 0) 1 0) j j✝) (Matrix.circulant  …
    -/
    simp [Pi.single_apply, Fin.ext_iff]
    /-
      🎉 no goals
    -/


/-- A circulant of `v` is symmetric iff `v` equals its reverse. -/
theorem circulant_isSymm_iff [AddGroup n] {v : n → α} :
    (circulant v).IsSymm ↔ ∀ i, v (-i) = v i := by
  /-
    α : Type u_1
    n : Type u_3
    inst✝ : AddGroup n
    v : n → α
    ⊢ Iff (Matrix.circulant v).IsSymm (∀ (i : n), Eq (v (Neg.neg i)) (v i))
  -/
  rw [IsSymm, transpose_circulant, circulant_inj, funext_iff]
  /-
    🎉 no goals
  -/


theorem Fin.circulant_isSymm_iff : ∀ {n} {v : Fin n → α}, (circulant v).IsSymm ↔ ∀ i, v (-i) = v i
            /-
              α : Type u_1
              v✝ : Fin 0 → α
              ⊢ Iff (Matrix.circulant v✝).IsSymm (∀ (i : Fin 0), Eq (v✝ (Neg.neg i)) (v✝ i))
            -/
  | 0 => by simp [IsSymm.ext_iff, IsEmpty.forall_iff]
            /-
              🎉 no goals
            -/
  | _ + 1 => Matrix.circulant_isSymm_iff


/-- If `circulant v` is symmetric, `∀ i j : I, v (- i) = v i`. -/
theorem circulant_isSymm_apply [AddGroup n] {v : n → α} (h : (circulant v).IsSymm) (i : n) :
    v (-i) = v i :=
  circulant_isSymm_iff.1 h i


theorem Fin.circulant_isSymm_apply {n} {v : Fin n → α} (h : (circulant v).IsSymm) (i : Fin n) :
    v (-i) = v i :=
  Fin.circulant_isSymm_iff.1 h i


