/-- `ℤ` modulo multiples of `n : ℕ` is `ZMod n`. -/
def quotientZMultiplesNatEquivZMod : ℤ ⧸ AddSubgroup.zmultiples (n : ℤ) ≃+ ZMod n :=
  (quotientAddEquivOfEq (ZMod.ker_intCastAddHom _)).symm.trans <|
    quotientKerEquivOfRightInverse (Int.castAddHom (ZMod n)) cast intCast_zmod_cast


/-- `ℤ` modulo multiples of `a : ℤ` is `ZMod a.natAbs`. -/
def quotientZMultiplesEquivZMod (a : ℤ) : ℤ ⧸ AddSubgroup.zmultiples a ≃+ ZMod a.natAbs :=
  (quotientAddEquivOfEq (zmultiples_natAbs a)).symm.trans (quotientZMultiplesNatEquivZMod a.natAbs)


/-- `ℤ` modulo the ideal generated by `n : ℕ` is `ZMod n`. -/
def quotientSpanNatEquivZMod : ℤ ⧸ Ideal.span {(n : ℤ)} ≃+* ZMod n :=
  (Ideal.quotEquivOfEq (ZMod.ker_intCastRingHom _)).symm.trans <|
    RingHom.quotientKerEquivOfRightInverse <|
      show Function.RightInverse ZMod.cast (Int.castRingHom (ZMod n)) from intCast_zmod_cast


/-- `ℤ` modulo the ideal generated by `a : ℤ` is `ZMod a.natAbs`. -/
def quotientSpanEquivZMod (a : ℤ) : ℤ ⧸ Ideal.span ({a} : Set ℤ) ≃+* ZMod a.natAbs :=
  (Ideal.quotEquivOfEq (span_natAbs a)).symm.trans (quotientSpanNatEquivZMod a.natAbs)


@[simp]
lemma index_zmultiples (a : ℤ) : (AddSubgroup.zmultiples a).index = a.natAbs := by
  /-
    a : Int
    ⊢ Eq (AddSubgroup.zmultiples a).index a.natAbs
  -/
  rw [AddSubgroup.index, Nat.card_congr (quotientZMultiplesEquivZMod a).toEquiv, Nat.card_zmod]
  /-
    🎉 no goals
  -/


/-- The **Chinese remainder theorem**, elementary version for `ZMod`. See also
`Mathlib.Data.ZMod.Basic` for versions involving only two numbers. -/
def ZMod.prodEquivPi {ι : Type*} [Fintype ι] (a : ι → ℕ)
    (coprime : Pairwise (Nat.Coprime on a)) : ZMod (∏ i, a i) ≃+* Π i, ZMod (a i) :=
  have : Pairwise fun i j => IsCoprime (span {(a i : ℤ)}) (span {(a j : ℤ)}) :=
    fun _i _j h ↦ (isCoprime_span_singleton_iff _ _).mpr ((coprime h).cast (R := ℤ))
  Int.quotientSpanNatEquivZMod _ |>.symm.trans <|
  quotEquivOfEq (iInf_span_singleton_natCast (R := ℤ) coprime) |>.symm.trans <|
  quotientInfRingEquivPiQuotient _ this |>.trans <|
  RingEquiv.piCongrRight fun i ↦ Int.quotientSpanNatEquivZMod (a i)


/-- The quotient `(ℤ ∙ a) ⧸ (stabilizer b)` is cyclic of order `minimalPeriod (a +ᵥ ·) b`. -/
noncomputable def zmultiplesQuotientStabilizerEquiv :
    zmultiples a ⧸ stabilizer (zmultiples a) b ≃+ ZMod (minimalPeriod (a +ᵥ ·) b) :=
  (ofBijective
          (map _ (stabilizer (zmultiples a) b) (zmultiplesHom (zmultiples a) ⟨a, mem_zmultiples a⟩)
            (by
              /-
                n : Nat
                A : Type u_1
                R : Type u_2
                inst✝³ : AddGroup A
                inst✝² : Ring R
                α : Type u_3
                β : Type u_4
                inst✝¹ : AddGroup α
                a : α
                inst✝ : AddAction α β
                b : β
                ⊢ LE.le (AddSubgroup.zmultiples ↑(Function.minimalPeriod (fun x => HVAdd.hVAdd …
              -/
              rw [zmultiples_le, mem_comap, mem_stabilizer_iff, zmultiplesHom_apply, natCast_zsmul]
              /-
                n : Nat
                A : Type u_1
                R : Type u_2
                inst✝³ : AddGroup A
                inst✝² : Ring R
                α : Type u_3
                β : Type u_4
                inst✝¹ : AddGroup α
                a : α
                inst✝ : AddAction α β
                b : β
                ⊢ Eq (HVAdd.hVAdd (HSMul.hSMul (Function.minimalPeriod (fun x => HVAdd.hVAdd a …
              -/
              simp_rw [← vadd_iterate]
              /-
                n : Nat
                A : Type u_1
                R : Type u_2
                inst✝³ : AddGroup A
                inst✝² : Ring R
                α : Type u_3
                β : Type u_4
                inst✝¹ : AddGroup α
                a : α
                inst✝ : AddAction α β
                b : β
                ⊢ Eq (Nat.iterate (fun x => HVAdd.hVAdd ⟨a, ⋯⟩ x) (Function.minimalPeriod (fun …
              -/
              exact isPeriodicPt_minimalPeriod (a +ᵥ ·) b))
              /-
                🎉 no goals
              -/
          ⟨by
            /-
              n : Nat
              A : Type u_1
              R : Type u_2
              inst✝³ : AddGroup A
              inst✝² : Ring R
              α : Type u_3
              β : Type u_4
              inst✝¹ : AddGroup α
              a : α
              inst✝ : AddAction α β
              b : β
              ⊢ Function.Injective ⇑(QuotientAddGroup.map (AddSubgroup.zmultiples ↑(Function …
            -/
            rw [← ker_eq_bot_iff, eq_bot_iff]
            /-
              n : Nat
              A : Type u_1
              R : Type u_2
              inst✝³ : AddGroup A
              inst✝² : Ring R
              α : Type u_3
              β : Type u_4
              inst✝¹ : AddGroup α
              a : α
              inst✝ : AddAction α β
              b : β
              ⊢ LE.le (QuotientAddGroup.map (AddSubgroup.zmultiples ↑(Function.minimalPeriod …
            -/
            refine fun q => induction_on q fun n hn => ?_
            rw [mem_bot, eq_zero_iff, Int.mem_zmultiples_iff, ←
              zsmul_vadd_eq_iff_minimalPeriod_dvd]
            /-
              n✝ : Nat
              A : Type u_1
              R : Type u_2
              inst✝³ : AddGroup A
              inst✝² : Ring R
              α : Type u_3
              β : Type u_4
              inst✝¹ : AddGroup α
              a : α
              inst✝ : AddAction α β
              b : β
              q : HasQuotient.Quotient Int (AddSubgroup.zmultiples ↑(Function.minimalPeriod  …
              n : Int
              hn : Membership.mem (QuotientAddGroup.map (AddSubgroup.zmultiples ↑(Function.m …
              ⊢ Eq (HVAdd.hVAdd (HSMul.hSMul n a) b) b
            -/
            exact (eq_zero_iff _).mp hn, fun q =>
            /-
              🎉 no goals
            -/
            induction_on q fun ⟨_, n, rfl⟩ => ⟨n, rfl⟩⟩).symm.trans
    (Int.quotientZMultiplesNatEquivZMod (minimalPeriod (a +ᵥ ·) b))


theorem zmultiplesQuotientStabilizerEquiv_symm_apply (n : ZMod (minimalPeriod (a +ᵥ ·) b)) :
    (zmultiplesQuotientStabilizerEquiv a b).symm n =
      (cast n : ℤ) • (⟨a, mem_zmultiples a⟩ : zmultiples a) :=
  rfl


/-- The quotient `(a ^ ℤ) ⧸ (stabilizer b)` is cyclic of order `minimalPeriod ((•) a) b`. -/
noncomputable def zpowersQuotientStabilizerEquiv :
    zpowers a ⧸ stabilizer (zpowers a) b ≃* Multiplicative (ZMod (minimalPeriod (a • ·) b)) :=
  letI f := zmultiplesQuotientStabilizerEquiv (Additive.ofMul a) b
  AddEquiv.toMultiplicative f


theorem zpowersQuotientStabilizerEquiv_symm_apply (n : ZMod (minimalPeriod (a • ·) b)) :
    (zpowersQuotientStabilizerEquiv a b).symm n = (⟨a, mem_zpowers a⟩ : zpowers a) ^ (cast n : ℤ) :=
  rfl


/-- The orbit `(a ^ ℤ) • b` is a cycle of order `minimalPeriod ((•) a) b`. -/
noncomputable def orbitZPowersEquiv : orbit (zpowers a) b ≃ ZMod (minimalPeriod (a • ·) b) :=
  (orbitEquivQuotientStabilizer _ b).trans (zpowersQuotientStabilizerEquiv a b).toEquiv


/-- The orbit `(ℤ • a) +ᵥ b` is a cycle of order `minimalPeriod (a +ᵥ ·) b`. -/
noncomputable def _root_.AddAction.orbitZMultiplesEquiv {α β : Type*} [AddGroup α] (a : α)
    [AddAction α β] (b : β) :
    AddAction.orbit (zmultiples a) b ≃ ZMod (minimalPeriod (a +ᵥ ·) b) :=
  (AddAction.orbitEquivQuotientStabilizer (zmultiples a) b).trans
    (zmultiplesQuotientStabilizerEquiv a b).toEquiv


attribute [to_additive existing] orbitZPowersEquiv


@[to_additive]
theorem orbitZPowersEquiv_symm_apply (k : ZMod (minimalPeriod (a • ·) b)) :
    (orbitZPowersEquiv a b).symm k =
      (⟨a, mem_zpowers a⟩ : zpowers a) ^ (cast k : ℤ) • ⟨b, mem_orbit_self b⟩ :=
  rfl


@[deprecated (since := "2024-02-21")]
alias _root_.AddAction.orbit_zmultiples_equiv_symm_apply := orbitZMultiplesEquiv_symm_apply


theorem orbitZPowersEquiv_symm_apply' (k : ℤ) :
    (orbitZPowersEquiv a b).symm k =
      (⟨a, mem_zpowers a⟩ : zpowers a) ^ k • ⟨b, mem_orbit_self b⟩ := by
  /-
    α : Type u_3
    β : Type u_4
    inst✝¹ : Group α
    a : α
    inst✝ : MulAction α β
    b : β
    k : Int
    ⊢ Eq ((MulAction.orbitZPowersEquiv a b).symm ↑k) (HSMul.hSMul (HPow.hPow ⟨a, ⋯ …
  -/
  rw [orbitZPowersEquiv_symm_apply, ZMod.coe_intCast]
  /-
    α : Type u_3
    β : Type u_4
    inst✝¹ : Group α
    a : α
    inst✝ : MulAction α β
    b : β
    k : Int
    ⊢ Eq (HSMul.hSMul (HPow.hPow ⟨a, ⋯⟩ (HMod.hMod k ↑(Function.minimalPeriod (fun …
  -/
  exact Subtype.ext (zpow_smul_mod_minimalPeriod _ _ k)
  /-
    🎉 no goals
  -/


theorem _root_.AddAction.orbitZMultiplesEquiv_symm_apply' {α β : Type*} [AddGroup α] (a : α)
    [AddAction α β] (b : β) (k : ℤ) :
    (AddAction.orbitZMultiplesEquiv a b).symm k =
      k • (⟨a, mem_zmultiples a⟩ : zmultiples a) +ᵥ ⟨b, AddAction.mem_orbit_self b⟩ := by
  /-
    α : Type u_5
    β : Type u_6
    inst✝¹ : AddGroup α
    a : α
    inst✝ : AddAction α β
    b : β
    k : Int
    ⊢ Eq ((AddAction.orbitZMultiplesEquiv a b).symm ↑k) (HVAdd.hVAdd (HSMul.hSMul  …
  -/
  rw [AddAction.orbitZMultiplesEquiv_symm_apply, ZMod.coe_intCast]
  -- Porting note: times out without `a b` explicit
  /-
    α : Type u_5
    β : Type u_6
    inst✝¹ : AddGroup α
    a : α
    inst✝ : AddAction α β
    b : β
    k : Int
    ⊢ Eq (HVAdd.hVAdd (HSMul.hSMul (HMod.hMod k ↑(Function.minimalPeriod (fun x => …
  -/
  exact Subtype.ext (zsmul_vadd_mod_minimalPeriod a b k)
  /-
    🎉 no goals
  -/


@[to_additive]
theorem minimalPeriod_eq_card [Fintype (orbit (zpowers a) b)] :
    minimalPeriod (a • ·) b = Fintype.card (orbit (zpowers a) b) := by
  -- Porting note: added `(_)` to find `Fintype` by unification
  /-
    α : Type u_3
    β : Type u_4
    inst✝² : Group α
    a : α
    inst✝¹ : MulAction α β
    b : β
    inst✝ : Fintype ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.z …
    ⊢ Eq (Function.minimalPeriod (fun x => HSMul.hSMul a x) b) (Fintype.card ↑(Mul …
  -/
  rw [← Fintype.ofEquiv_card (orbitZPowersEquiv a b), @ZMod.card _ (_)]
  /-
    🎉 no goals
  -/


@[to_additive]
instance minimalPeriod_pos [Finite <| orbit (zpowers a) b] :
    NeZero <| minimalPeriod (a • ·) b :=
  ⟨by
    /-
      n : Nat
      A : Type u_1
      R : Type u_2
      inst✝⁴ : AddGroup A
      inst✝³ : Ring R
      α : Type u_3
      β : Type u_4
      inst✝² : Group α
      a : α
      inst✝¹ : MulAction α β
      b : β
      inst✝ : Finite ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      ⊢ Ne (Function.minimalPeriod (fun x => HSMul.hSMul a x) b) 0
    -/
    cases nonempty_fintype (orbit (zpowers a) b)
    /-
      case intro
      n : Nat
      A : Type u_1
      R : Type u_2
      inst✝⁴ : AddGroup A
      inst✝³ : Ring R
      α : Type u_3
      β : Type u_4
      inst✝² : Group α
      a : α
      inst✝¹ : MulAction α β
      b : β
      inst✝ : Finite ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      val✝ : Fintype ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      ⊢ Ne (Function.minimalPeriod (fun x => HSMul.hSMul a x) b) 0
    -/
    haveI : Nonempty (orbit (zpowers a) b) := (orbit_nonempty b).to_subtype
    /-
      case intro
      n : Nat
      A : Type u_1
      R : Type u_2
      inst✝⁴ : AddGroup A
      inst✝³ : Ring R
      α : Type u_3
      β : Type u_4
      inst✝² : Group α
      a : α
      inst✝¹ : MulAction α β
      b : β
      inst✝ : Finite ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      val✝ : Fintype ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      this : Nonempty ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.z …
      ⊢ Ne (Function.minimalPeriod (fun x => HSMul.hSMul a x) b) 0
    -/
    rw [minimalPeriod_eq_card]
    /-
      case intro
      n : Nat
      A : Type u_1
      R : Type u_2
      inst✝⁴ : AddGroup A
      inst✝³ : Ring R
      α : Type u_3
      β : Type u_4
      inst✝² : Group α
      a : α
      inst✝¹ : MulAction α β
      b : β
      inst✝ : Finite ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      val✝ : Fintype ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.zp …
      this : Nonempty ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgroup.z …
      ⊢ Ne (Fintype.card ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgrou …
    -/
    exact Fintype.card_ne_zero⟩
    /-
      🎉 no goals
    -/


/-- See also `Fintype.card_zpowers`. -/
@[to_additive (attr := simp) "See also `Fintype.card_zmultiples`."]
theorem Nat.card_zpowers : Nat.card (zpowers a) = orderOf a := by
  /-
    α : Type u_3
    inst✝ : Group α
    a : α
    ⊢ Eq (Nat.card (Subtype fun x => Membership.mem (Subgroup.zpowers a) x)) (orde …
  -/
  have := Nat.card_congr (MulAction.orbitZPowersEquiv a (1 : α))
  /-
    α : Type u_3
    inst✝ : Group α
    a : α
    this : Eq (Nat.card ↑(MulAction.orbit (Subtype fun x => Membership.mem (Subgro …
    ⊢ Eq (Nat.card (Subtype fun x => Membership.mem (Subgroup.zpowers a) x)) (orde …
  -/
  rwa [Nat.card_zmod, orbit_subgroup_one_eq_self] at this
  /-
    🎉 no goals
  -/


@[to_additive (attr := simp)]
lemma finite_zpowers : (zpowers a : Set α).Finite ↔ IsOfFinOrder a := by
  simp only [← orderOf_pos_iff, ← Nat.card_zpowers, Nat.card_pos_iff, ← SetLike.coe_sort_coe,
    nonempty_coe_sort, Nat.card_pos_iff, Set.finite_coe_iff, Subgroup.coe_nonempty, true_and]


@[to_additive (attr := simp)]
lemma infinite_zpowers : (zpowers a : Set α).Infinite ↔ ¬IsOfFinOrder a := finite_zpowers.not


@[to_additive]
protected alias ⟨_, IsOfFinOrder.finite_zpowers⟩ := finite_zpowers


/-- Partition `G ⧸ H` into orbits of the action of `g : G`. -/
noncomputable def quotientEquivSigmaZMod :
    G ⧸ H ≃ Σq : orbitRel.Quotient (zpowers g) (G ⧸ H), ZMod (minimalPeriod (g • ·) q.out) :=
  (selfEquivSigmaOrbits (zpowers g) (G ⧸ H)).trans
    (sigmaCongrRight fun q => orbitZPowersEquiv g q.out)


lemma quotientEquivSigmaZMod_symm_apply (q : orbitRel.Quotient (zpowers g) (G ⧸ H))
    (k : ZMod (minimalPeriod (g • ·) q.out)) :
    (quotientEquivSigmaZMod H g).symm ⟨q, k⟩ = g ^ (cast k : ℤ) • q.out := rfl


lemma quotientEquivSigmaZMod_apply (q : orbitRel.Quotient (zpowers g) (G ⧸ H)) (k : ℤ) :
    quotientEquivSigmaZMod H g (g ^ k • q.out) = ⟨q, k⟩ := by
  rw [apply_eq_iff_eq_symm_apply, quotientEquivSigmaZMod_symm_apply, ZMod.coe_intCast,
    zpow_smul_mod_minimalPeriod]


