/-- The congruence relation generated by a normal subgroup. -/
@[to_additive "The additive congruence relation generated by a normal additive subgroup."]
protected def con : Con G where
  toSetoid := leftRel N
  mul' := fun {a b c d} hab hcd => by
    /-
      G : Type u
      inst✝² : Group G
      N : Subgroup G
      nN : N.Normal
      H : Type v
      inst✝¹ : Group H
      M : Type x
      inst✝ : Monoid M
      a b c d : G
      hab : (QuotientGroup.leftRel N) a b
      hcd : (QuotientGroup.leftRel N) c d
      ⊢ (QuotientGroup.leftRel N) (HMul.hMul a c) (HMul.hMul b d)
    -/
    rw [leftRel_eq] at hab hcd ⊢
    /-
      G : Type u
      inst✝² : Group G
      N : Subgroup G
      nN : N.Normal
      H : Type v
      inst✝¹ : Group H
      M : Type x
      inst✝ : Monoid M
      a b c d : G
      hab : Membership.mem N (HMul.hMul (Inv.inv a) b)
      hcd : Membership.mem N (HMul.hMul (Inv.inv c) d)
      ⊢ (fun x y => Membership.mem N (HMul.hMul (Inv.inv x) y)) (HMul.hMul a c) (HMu …
    -/
    dsimp only
    calc
      c⁻¹ * (a⁻¹ * b) * c⁻¹⁻¹ * (c⁻¹ * d) ∈ N := N.mul_mem (nN.conj_mem _ hab _) hcd
      _ = (a * c)⁻¹ * (b * d) := by
        simp only [mul_inv_rev, mul_assoc, inv_mul_cancel_left]


@[to_additive]
instance Quotient.group : Group (G ⧸ N) :=
  (QuotientGroup.con N).group


/-- The group homomorphism from `G` to `G/N`. -/
@[to_additive "The additive group homomorphism from `G` to `G/N`."]
def mk' : G →* G ⧸ N :=
  MonoidHom.mk' QuotientGroup.mk fun _ _ => rfl


@[to_additive (attr := simp)]
theorem coe_mk' : (mk' N : G → G ⧸ N) = mk :=
  rfl


@[to_additive (attr := simp)]
theorem mk'_apply (x : G) : mk' N x = x :=
  rfl


@[to_additive]
theorem mk'_surjective : Surjective <| mk' N :=
  @mk_surjective _ _ N


@[to_additive]
theorem mk'_eq_mk' {x y : G} : mk' N x = mk' N y ↔ ∃ z ∈ N, x * z = y :=
  QuotientGroup.eq.trans <| by
    /-
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      x y : G
      ⊢ Iff (Membership.mem N (HMul.hMul (Inv.inv x) y)) (Exists fun z => And (Membe …
    -/
    simp only [← _root_.eq_inv_mul_iff_mul_eq, exists_prop, exists_eq_right]
    /-
      🎉 no goals
    -/


/-- Two `MonoidHom`s from a quotient group are equal if their compositions with
`QuotientGroup.mk'` are equal.

See note [partially-applied ext lemmas]. -/
@[to_additive (attr := ext 1100) "Two `AddMonoidHom`s from an additive quotient group are equal if
 their compositions with `AddQuotientGroup.mk'` are equal.

 See note [partially-applied ext lemmas]. "]
theorem monoidHom_ext ⦃f g : G ⧸ N →* M⦄ (h : f.comp (mk' N) = g.comp (mk' N)) : f = g :=
  MonoidHom.ext fun x => QuotientGroup.induction_on x <| (DFunLike.congr_fun h : _)


@[to_additive (attr := simp)]
theorem eq_one_iff {N : Subgroup G} [N.Normal] (x : G) : (x : G ⧸ N) = 1 ↔ x ∈ N := by
  /-
    G : Type u
    inst✝¹ : Group G
    N : Subgroup G
    inst✝ : N.Normal
    x : G
    ⊢ Iff (Eq (↑x) 1) (Membership.mem N x)
  -/
  refine QuotientGroup.eq.trans ?_
  /-
    G : Type u
    inst✝¹ : Group G
    N : Subgroup G
    inst✝ : N.Normal
    x : G
    ⊢ Iff (Membership.mem N (HMul.hMul (Inv.inv x) 1)) (Membership.mem N x)
  -/
  rw [mul_one, Subgroup.inv_mem_iff]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem ker_le_range_iff {I : Type w} [Group I] (f : G →* H) [f.range.Normal] (g : H →* I) :
    g.ker ≤ f.range ↔ (mk' f.range).comp g.ker.subtype = 1 :=
  ⟨fun h => MonoidHom.ext fun ⟨_, hx⟩ => (eq_one_iff _).mpr <| h hx,
                                          /-
                                            G : Type u
                                            inst✝³ : Group G
                                            H : Type v
                                            inst✝² : Group H
                                            I : Type w
                                            inst✝¹ : Group I
                                            f : MonoidHom G H
                                            inst✝ : f.range.Normal
                                            g : MonoidHom H I
                                            h : Eq ((QuotientGroup.mk' f.range).comp g.ker.subtype) 1
                                            x : H
                                            hx : Membership.mem g.ker x
                                            ⊢ Eq (↑x) 1
                                          -/
    fun h x hx => (eq_one_iff _).mp <| by exact DFunLike.congr_fun h ⟨x, hx⟩⟩
                                          /-
                                            🎉 no goals
                                          -/


@[to_additive (attr := simp)]
theorem ker_mk' : MonoidHom.ker (QuotientGroup.mk' N : G →* G ⧸ N) = N :=
  Subgroup.ext eq_one_iff
-- Porting note: I think this is misnamed without the prime


@[to_additive]
theorem eq_iff_div_mem {N : Subgroup G} [nN : N.Normal] {x y : G} :
    (x : G ⧸ N) = y ↔ x / y ∈ N := by
  /-
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    x y : G
    ⊢ Iff (Eq ↑x ↑y) (Membership.mem N (HDiv.hDiv x y))
  -/
  refine eq_comm.trans (QuotientGroup.eq.trans ?_)
  /-
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    x y : G
    ⊢ Iff (Membership.mem N (HMul.hMul (Inv.inv y) x)) (Membership.mem N (HDiv.hDi …
  -/
  rw [nN.mem_comm_iff, div_eq_mul_inv]
  /-
    🎉 no goals
  -/

-- for commutative groups we don't need normality assumption


@[to_additive]
instance Quotient.commGroup {G : Type*} [CommGroup G] (N : Subgroup G) : CommGroup (G ⧸ N) :=
  { toGroup := have := N.normal_of_comm; QuotientGroup.Quotient.group N
    mul_comm := fun a b => Quotient.inductionOn₂' a b fun a b => congr_arg mk (mul_comm a b) }


local notation " Q " => G ⧸ N


@[to_additive (attr := simp)]
theorem mk_one : ((1 : G) : Q) = 1 :=
  rfl


@[to_additive (attr := simp)]
theorem mk_mul (a b : G) : ((a * b : G) : Q) = a * b :=
  rfl


@[to_additive (attr := simp)]
theorem mk_inv (a : G) : ((a⁻¹ : G) : Q) = (a : Q)⁻¹ :=
  rfl


@[to_additive (attr := simp)]
theorem mk_div (a b : G) : ((a / b : G) : Q) = a / b :=
  rfl


@[to_additive (attr := simp)]
theorem mk_pow (a : G) (n : ℕ) : ((a ^ n : G) : Q) = (a : Q) ^ n :=
  rfl


@[to_additive (attr := simp)]
theorem mk_zpow (a : G) (n : ℤ) : ((a ^ n : G) : Q) = (a : Q) ^ n :=
  rfl


                                                                           /-
                                                                             G : Type u
                                                                             inst✝ : Group G
                                                                             N : Subgroup G
                                                                             nN : N.Normal
                                                                             ⊢ Eq (Subgroup.map (QuotientGroup.mk' N) N) Bot.bot
                                                                           -/
@[to_additive (attr := simp)] lemma map_mk'_self : N.map (mk' N) = ⊥ := by aesop
                                                                           /-
                                                                             🎉 no goals
                                                                           -/


/-- A group homomorphism `φ : G →* M` with `N ⊆ ker(φ)` descends (i.e. `lift`s) to a
group homomorphism `G/N →* M`. -/
@[to_additive "An `AddGroup` homomorphism `φ : G →+ M` with `N ⊆ ker(φ)` descends (i.e. `lift`s)
 to a group homomorphism `G/N →* M`."]
def lift (φ : G →* M) (HN : N ≤ φ.ker) : Q →* M :=
  (QuotientGroup.con N).lift φ fun x y h => by
    /-
      G : Type u
      inst✝² : Group G
      N : Subgroup G
      nN : N.Normal
      H : Type v
      inst✝¹ : Group H
      M : Type x
      inst✝ : Monoid M
      φ : MonoidHom G M
      HN : LE.le N φ.ker
      x y : G
      h : (QuotientGroup.con N) x y
      ⊢ (Con.ker φ) x y
    -/
    simp only [QuotientGroup.con, leftRel_apply, Con.rel_mk] at h
    /-
      G : Type u
      inst✝² : Group G
      N : Subgroup G
      nN : N.Normal
      H : Type v
      inst✝¹ : Group H
      M : Type x
      inst✝ : Monoid M
      φ : MonoidHom G M
      HN : LE.le N φ.ker
      x y : G
      h : Membership.mem N (HMul.hMul (Inv.inv x) y)
      ⊢ (Con.ker φ) x y
    -/
    rw [Con.ker_rel]
    calc
      φ x = φ (y * (x⁻¹ * y)⁻¹) := by rw [mul_inv_rev, inv_inv, mul_inv_cancel_left]
      _ = φ y := by rw [φ.map_mul, HN (N.inv_mem h), mul_one]


@[to_additive (attr := simp)]
theorem lift_mk {φ : G →* M} (HN : N ≤ φ.ker) (g : G) : lift N φ HN (g : Q) = φ g :=
  rfl


@[to_additive (attr := simp)]
theorem lift_mk' {φ : G →* M} (HN : N ≤ φ.ker) (g : G) : lift N φ HN (mk g : Q) = φ g :=
  rfl
-- TODO: replace `mk` with `mk'`)


@[to_additive (attr := simp)]
theorem lift_quot_mk {φ : G →* M} (HN : N ≤ φ.ker) (g : G) :
    lift N φ HN (Quot.mk _ g : Q) = φ g :=
  rfl


/-- A group homomorphism `f : G →* H` induces a map `G/N →* H/M` if `N ⊆ f⁻¹(M)`. -/
@[to_additive
      "An `AddGroup` homomorphism `f : G →+ H` induces a map `G/N →+ H/M` if `N ⊆ f⁻¹(M)`."]
def map (M : Subgroup H) [M.Normal] (f : G →* H) (h : N ≤ M.comap f) : G ⧸ N →* H ⧸ M := by
  /-
    G : Type u
    inst✝³ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝² : Group H
    M✝ : Type x
    inst✝¹ : Monoid M✝
    M : Subgroup H
    inst✝ : M.Normal
    f : MonoidHom G H
    h : LE.le N (Subgroup.comap f M)
    ⊢ MonoidHom (HasQuotient.Quotient G N) (HasQuotient.Quotient H M)
  -/
  refine QuotientGroup.lift N ((mk' M).comp f) ?_
  /-
    G : Type u
    inst✝³ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝² : Group H
    M✝ : Type x
    inst✝¹ : Monoid M✝
    M : Subgroup H
    inst✝ : M.Normal
    f : MonoidHom G H
    h : LE.le N (Subgroup.comap f M)
    ⊢ LE.le N ((QuotientGroup.mk' M).comp f).ker
  -/
  intro x hx
  /-
    G : Type u
    inst✝³ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝² : Group H
    M✝ : Type x
    inst✝¹ : Monoid M✝
    M : Subgroup H
    inst✝ : M.Normal
    f : MonoidHom G H
    h : LE.le N (Subgroup.comap f M)
    x : G
    hx : Membership.mem N x
    ⊢ Membership.mem ((QuotientGroup.mk' M).comp f).ker x
  -/
  refine QuotientGroup.eq.2 ?_
  /-
    G : Type u
    inst✝³ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝² : Group H
    M✝ : Type x
    inst✝¹ : Monoid M✝
    M : Subgroup H
    inst✝ : M.Normal
    f : MonoidHom G H
    h : LE.le N (Subgroup.comap f M)
    x : G
    hx : Membership.mem N x
    ⊢ Membership.mem M (HMul.hMul (Inv.inv (f x)) 1)
  -/
  rw [mul_one, Subgroup.inv_mem_iff]
  /-
    G : Type u
    inst✝³ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝² : Group H
    M✝ : Type x
    inst✝¹ : Monoid M✝
    M : Subgroup H
    inst✝ : M.Normal
    f : MonoidHom G H
    h : LE.le N (Subgroup.comap f M)
    x : G
    hx : Membership.mem N x
    ⊢ Membership.mem M (f x)
  -/
  exact h hx
  /-
    🎉 no goals
  -/


@[to_additive (attr := simp)]
theorem map_mk (M : Subgroup H) [M.Normal] (f : G →* H) (h : N ≤ M.comap f) (x : G) :
    map N M f h ↑x = ↑(f x) :=
  rfl


@[to_additive]
theorem map_mk' (M : Subgroup H) [M.Normal] (f : G →* H) (h : N ≤ M.comap f) (x : G) :
    map N M f h (mk' _ x) = ↑(f x) :=
  rfl


@[to_additive]
theorem map_id_apply (h : N ≤ Subgroup.comap (MonoidHom.id _) N := (Subgroup.comap_id N).le) (x) :
    map N N (MonoidHom.id _) h x = x :=
  induction_on x fun _x => rfl


@[to_additive (attr := simp)]
theorem map_id (h : N ≤ Subgroup.comap (MonoidHom.id _) N := (Subgroup.comap_id N).le) :
    map N N (MonoidHom.id _) h = MonoidHom.id _ :=
  MonoidHom.ext (map_id_apply N h)


@[to_additive (attr := simp)]
theorem map_map {I : Type*} [Group I] (M : Subgroup H) (O : Subgroup I) [M.Normal] [O.Normal]
    (f : G →* H) (g : H →* I) (hf : N ≤ Subgroup.comap f M) (hg : M ≤ Subgroup.comap g O)
    (hgf : N ≤ Subgroup.comap (g.comp f) O :=
      hf.trans ((Subgroup.comap_mono hg).trans_eq (Subgroup.comap_comap _ _ _)))
    (x : G ⧸ N) : map M O g hg (map N M f hf x) = map N O (g.comp f) hgf x := by
  /-
    G : Type u
    inst✝⁴ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝³ : Group H
    I : Type u_1
    inst✝² : Group I
    M : Subgroup H
    O : Subgroup I
    inst✝¹ : M.Normal
    inst✝ : O.Normal
    f : MonoidHom G H
    g : MonoidHom H I
    hf : LE.le N (Subgroup.comap f M)
    hg : LE.le M (Subgroup.comap g O)
    hgf : optParam (LE.le N (Subgroup.comap (g.comp f) O)) ⋯
    x : HasQuotient.Quotient G N
    ⊢ Eq ((QuotientGroup.map M O g hg) ((QuotientGroup.map N M f hf) x)) ((Quotien …
  -/
  refine induction_on x fun x => ?_
  /-
    G : Type u
    inst✝⁴ : Group G
    N : Subgroup G
    nN : N.Normal
    H : Type v
    inst✝³ : Group H
    I : Type u_1
    inst✝² : Group I
    M : Subgroup H
    O : Subgroup I
    inst✝¹ : M.Normal
    inst✝ : O.Normal
    f : MonoidHom G H
    g : MonoidHom H I
    hf : LE.le N (Subgroup.comap f M)
    hg : LE.le M (Subgroup.comap g O)
    hgf : optParam (LE.le N (Subgroup.comap (g.comp f) O)) ⋯
    x✝ : HasQuotient.Quotient G N
    x : G
    ⊢ Eq ((QuotientGroup.map M O g hg) ((QuotientGroup.map N M f hf) ↑x)) ((Quotie …
  -/
  simp only [map_mk, MonoidHom.comp_apply]
  /-
    🎉 no goals
  -/


@[to_additive (attr := simp)]
theorem map_comp_map {I : Type*} [Group I] (M : Subgroup H) (O : Subgroup I) [M.Normal] [O.Normal]
    (f : G →* H) (g : H →* I) (hf : N ≤ Subgroup.comap f M) (hg : M ≤ Subgroup.comap g O)
    (hgf : N ≤ Subgroup.comap (g.comp f) O :=
      hf.trans ((Subgroup.comap_mono hg).trans_eq (Subgroup.comap_comap _ _ _))) :
    (map M O g hg).comp (map N M f hf) = map N O (g.comp f) hgf :=
  MonoidHom.ext (map_map N M O f g hf hg hgf)


@[to_additive (attr := simp)] lemma image_coe : ((↑) : G → Q) '' N = 1 :=
  congr_arg ((↑) : Subgroup Q → Set Q) <| map_mk'_self N


@[to_additive]
lemma preimage_image_coe (s : Set G) : ((↑) : G → Q) ⁻¹' ((↑) '' s) = N * s := by
  /-
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    s : Set G
    ⊢ Eq (Set.preimage QuotientGroup.mk (Set.image QuotientGroup.mk s)) (HMul.hMul …
  -/
  ext a
  /-
    case h
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    s : Set G
    a : G
    ⊢ Iff (Membership.mem (Set.preimage QuotientGroup.mk (Set.image QuotientGroup. …
  -/
  constructor
    /-
      case h.mp
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a : G
      ⊢ Membership.mem (Set.preimage QuotientGroup.mk (Set.image QuotientGroup.mk s) …
    -/
  · rintro ⟨b, hb, h⟩
    /-
      case h.mp.intro.intro
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a b : G
      hb : Membership.mem s b
      h : Eq ↑b ↑a
      ⊢ Membership.mem (HMul.hMul (↑N) s) a
    -/
    refine ⟨a / b, (QuotientGroup.eq_one_iff _).1 ?_, b, hb, div_mul_cancel _ _⟩
    /-
      case h.mp.intro.intro
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a b : G
      hb : Membership.mem s b
      h : Eq ↑b ↑a
      ⊢ Eq (↑(HDiv.hDiv a b)) 1
    -/
    simp only [h, QuotientGroup.mk_div, div_self']
    /-
      🎉 no goals
    -/
    /-
      case h.mpr
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a : G
      ⊢ Membership.mem (HMul.hMul (↑N) s) a → Membership.mem (Set.preimage QuotientG …
    -/
  · rintro ⟨a, ha, b, hb, rfl⟩
    /-
      case h.mpr.intro.intro.intro.intro
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a : G
      ha : Membership.mem (↑N) a
      b : G
      hb : Membership.mem s b
      ⊢ Membership.mem (Set.preimage QuotientGroup.mk (Set.image QuotientGroup.mk s) …
    -/
    refine ⟨b, hb, ?_⟩
    /-
      case h.mpr.intro.intro.intro.intro
      G : Type u
      inst✝ : Group G
      N : Subgroup G
      nN : N.Normal
      s : Set G
      a : G
      ha : Membership.mem (↑N) a
      b : G
      hb : Membership.mem s b
      ⊢ Eq ↑b ↑((fun x1 x2 => HMul.hMul x1 x2) a b)
    -/
    simpa only [QuotientGroup.mk_mul, self_eq_mul_left, QuotientGroup.eq_one_iff]
    /-
      🎉 no goals
    -/


@[to_additive]
lemma image_coe_inj {s t : Set G} : ((↑) : G → Q) '' s = ((↑) : G → Q) '' t ↔ ↑N * s = N * t := by
  /-
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    s t : Set G
    ⊢ Iff (Eq (Set.image QuotientGroup.mk s) (Set.image QuotientGroup.mk t)) (Eq ( …
  -/
  simp_rw [← preimage_image_coe]
  /-
    G : Type u
    inst✝ : Group G
    N : Subgroup G
    nN : N.Normal
    s t : Set G
    ⊢ Iff (Eq (Set.image QuotientGroup.mk s) (Set.image QuotientGroup.mk t)) (Eq ( …
  -/
  exact QuotientGroup.mk_surjective.preimage_injective.eq_iff.symm
  /-
    🎉 no goals
  -/


/-- `QuotientGroup.congr` lifts the isomorphism `e : G ≃ H` to `G ⧸ G' ≃ H ⧸ H'`,
given that `e` maps `G` to `H`. -/
@[to_additive "`QuotientAddGroup.congr` lifts the isomorphism `e : G ≃ H` to `G ⧸ G' ≃ H ⧸ H'`,
 given that `e` maps `G` to `H`."]
def congr (e : G ≃* H) (he : G'.map e = H') : G ⧸ G' ≃* H ⧸ H' :=
  { map G' H' e (he ▸ G'.le_comap_map (e : G →* H)) with
    toFun := map G' H' e (he ▸ G'.le_comap_map (e : G →* H))
    invFun := map H' G' e.symm (he ▸ (G'.map_equiv_eq_comap_symm e).le)
    left_inv := fun x => by
      rw [map_map G' H' G' e e.symm (he ▸ G'.le_comap_map (e : G →* H))
        (he ▸ (G'.map_equiv_eq_comap_symm e).le)]
      simp only [map_map, ← MulEquiv.coe_monoidHom_trans, MulEquiv.self_trans_symm,
        MulEquiv.coe_monoidHom_refl, map_id_apply]
    right_inv := fun x => by
      rw [map_map H' G' H' e.symm e (he ▸ (G'.map_equiv_eq_comap_symm e).le)
        (he ▸ G'.le_comap_map (e : G →* H)) ]
      simp only [← MulEquiv.coe_monoidHom_trans, MulEquiv.symm_trans_self,
        MulEquiv.coe_monoidHom_refl, map_id_apply] }


@[simp]
theorem congr_mk (e : G ≃* H) (he : G'.map ↑e = H') (x) : congr G' H' e he (mk x) = e x :=
  rfl


theorem congr_mk' (e : G ≃* H) (he : G'.map ↑e = H') (x) :
    congr G' H' e he (mk' G' x) = mk' H' (e x) :=
  rfl


@[simp]
theorem congr_apply (e : G ≃* H) (he : G'.map ↑e = H') (x : G) :
    congr G' H' e he x = mk' H' (e x) :=
  rfl


@[simp]
theorem congr_refl (he : G'.map (MulEquiv.refl G : G →* G) = G' := Subgroup.map_id G') :
    congr G' G' (MulEquiv.refl G) he = MulEquiv.refl (G ⧸ G') := by
  /-
    G : Type u
    inst✝¹ : Group G
    G' : Subgroup G
    inst✝ : G'.Normal
    he : optParam (Eq (Subgroup.map (↑(MulEquiv.refl G)) G') G') ⋯
    ⊢ Eq (QuotientGroup.congr G' G' (MulEquiv.refl G) he) (MulEquiv.refl (HasQuoti …
  -/
  ext ⟨x⟩
  /-
    case h.mk
    G : Type u
    inst✝¹ : Group G
    G' : Subgroup G
    inst✝ : G'.Normal
    he : optParam (Eq (Subgroup.map (↑(MulEquiv.refl G)) G') G') ⋯
    x✝ : HasQuotient.Quotient G G'
    x : G
    ⊢ Eq ((QuotientGroup.congr G' G' (MulEquiv.refl G) he) (Quot.mk (⇑(QuotientGro …
  -/
  rfl
  /-
    🎉 no goals
  -/


@[simp]
theorem congr_symm (e : G ≃* H) (he : G'.map ↑e = H') :
    (congr G' H' e he).symm = congr H' G' e.symm ((Subgroup.map_symm_eq_iff_map_eq _).mpr he) :=
  rfl


