/-- The isomorphism between the sheafification of `P` composed with `F` and
the sheafification of `P ⋙ F`.

Use the lemmas `whisker_right_to_sheafify_sheafify_comp_iso_hom`,
`to_sheafify_comp_sheafify_comp_iso_inv` and `sheafify_comp_iso_inv_eq_sheafify_lift` to reduce
the components of this isomorphisms to a state that can be handled using the universal property
of sheafification. -/
noncomputable def sheafifyCompIso : J.sheafify P ⋙ F ≅ J.sheafify (P ⋙ F) :=
  J.plusCompIso _ _ ≪≫ (J.plusFunctor _).mapIso (J.plusCompIso _ _)


/-- The isomorphism between the sheafification of `P` composed with `F` and
the sheafification of `P ⋙ F`, functorially in `F`. -/
noncomputable def sheafificationWhiskerLeftIso (P : Cᵒᵖ ⥤ D)
    [∀ (F : D ⥤ E) (X : C), PreservesColimitsOfShape (J.Cover X)ᵒᵖ F]
    [∀ (F : D ⥤ E) (X : C) (W : J.Cover X) (P : Cᵒᵖ ⥤ D),
        PreservesLimit (W.index P).multicospan F] :
    (whiskeringLeft _ _ E).obj (J.sheafify P) ≅
    (whiskeringLeft _ _ _).obj P ⋙ J.sheafification E := by
  /-
    C : Type u
    inst✝¹⁰ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁸ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁷ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁶ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁴ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝² : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P✝ P : CategoryTheory.Functor (Opposite C) D
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ CategoryTheory.Iso ((CategoryTheory.whiskeringLeft (Opposite C) D E).obj (J. …
  -/
  refine J.plusFunctorWhiskerLeftIso _ ≪≫ ?_ ≪≫ Functor.associator _ _ _
  /-
    C : Type u
    inst✝¹⁰ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁸ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁷ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁶ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁴ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝² : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P✝ P : CategoryTheory.Functor (Opposite C) D
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ CategoryTheory.Iso (((CategoryTheory.whiskeringLeft (Opposite C) D E).obj (J …
  -/
  refine isoWhiskerRight ?_ _
  /-
    C : Type u
    inst✝¹⁰ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁸ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁷ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁶ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁴ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝² : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P✝ P : CategoryTheory.Functor (Opposite C) D
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ CategoryTheory.Iso ((CategoryTheory.whiskeringLeft (Opposite C) D E).obj (J. …
  -/
  exact J.plusFunctorWhiskerLeftIso _
  /-
    🎉 no goals
  -/


@[simp]
theorem sheafificationWhiskerLeftIso_hom_app (P : Cᵒᵖ ⥤ D) (F : D ⥤ E)
    [∀ (F : D ⥤ E) (X : C), PreservesColimitsOfShape (J.Cover X)ᵒᵖ F]
    [∀ (F : D ⥤ E) (X : C) (W : J.Cover X) (P : Cᵒᵖ ⥤ D),
        PreservesLimit (W.index P).multicospan F] :
    (sheafificationWhiskerLeftIso J P).hom.app F = (J.sheafifyCompIso F P).hom := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    P : CategoryTheory.Functor (Opposite C) D
    F : CategoryTheory.Functor D E
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ Eq ((J.sheafificationWhiskerLeftIso P).hom.app F) (J.sheafifyCompIso F P).hom
  -/
  dsimp [sheafificationWhiskerLeftIso, sheafifyCompIso]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    P : CategoryTheory.Functor (Opposite C) D
    F : CategoryTheory.Functor D E
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (J.plusCompIso F (J.plusObj P)).hom ( …
  -/
  rw [Category.comp_id]
  /-
    🎉 no goals
  -/


@[simp]
theorem sheafificationWhiskerLeftIso_inv_app (P : Cᵒᵖ ⥤ D) (F : D ⥤ E)
    [∀ (F : D ⥤ E) (X : C), PreservesColimitsOfShape (J.Cover X)ᵒᵖ F]
    [∀ (F : D ⥤ E) (X : C) (W : J.Cover X) (P : Cᵒᵖ ⥤ D),
        PreservesLimit (W.index P).multicospan F] :
    (sheafificationWhiskerLeftIso J P).inv.app F = (J.sheafifyCompIso F P).inv := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    P : CategoryTheory.Functor (Opposite C) D
    F : CategoryTheory.Functor D E
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ Eq ((J.sheafificationWhiskerLeftIso P).inv.app F) (J.sheafifyCompIso F P).inv
  -/
  dsimp [sheafificationWhiskerLeftIso, sheafifyCompIso]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    P : CategoryTheory.Functor (Opposite C) D
    F : CategoryTheory.Functor D E
    inst✝¹ : ∀ (F : CategoryTheory.Functor D E) (X : C), CategoryTheory.Limits.Pre …
    inst✝ : ∀ (F : CategoryTheory.Functor D E) (X : C) (W : J.Cover X) (P : Catego …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp ( …
  -/
  erw [Category.id_comp]
  /-
    🎉 no goals
  -/


/-- The isomorphism between the sheafification of `P` composed with `F` and
the sheafification of `P ⋙ F`, functorially in `P`. -/
noncomputable def sheafificationWhiskerRightIso :
    J.sheafification D ⋙ (whiskeringRight _ _ _).obj F ≅
      (whiskeringRight _ _ _).obj F ⋙ J.sheafification E := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ CategoryTheory.Iso ((J.sheafification D).comp ((CategoryTheory.whiskeringRig …
  -/
  refine Functor.associator _ _ _ ≪≫ ?_
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ CategoryTheory.Iso ((J.plusFunctor D).comp ((J.plusFunctor D).comp ((Categor …
  -/
  refine isoWhiskerLeft (J.plusFunctor D) (J.plusFunctorWhiskerRightIso _) ≪≫ ?_
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ CategoryTheory.Iso ((J.plusFunctor D).comp (((CategoryTheory.whiskeringRight …
  -/
  refine ?_ ≪≫ Functor.associator _ _ _
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ CategoryTheory.Iso ((J.plusFunctor D).comp (((CategoryTheory.whiskeringRight …
  -/
  refine (Functor.associator _ _ _).symm ≪≫ ?_
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ CategoryTheory.Iso (((J.plusFunctor D).comp ((CategoryTheory.whiskeringRight …
  -/
  exact isoWhiskerRight (J.plusFunctorWhiskerRightIso _) (J.plusFunctor E)
  /-
    🎉 no goals
  -/


@[simp]
theorem sheafificationWhiskerRightIso_hom_app :
    (J.sheafificationWhiskerRightIso F).hom.app P = (J.sheafifyCompIso F P).hom := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq ((J.sheafificationWhiskerRightIso F).hom.app P) (J.sheafifyCompIso F P).hom
  -/
  dsimp [sheafificationWhiskerRightIso, sheafifyCompIso]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.id ((J …
  -/
  simp only [Category.id_comp, Category.comp_id]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.id ((J …
  -/
  erw [Category.id_comp]
  /-
    🎉 no goals
  -/


@[simp]
theorem sheafificationWhiskerRightIso_inv_app :
    (J.sheafificationWhiskerRightIso F).inv.app P = (J.sheafifyCompIso F P).inv := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq ((J.sheafificationWhiskerRightIso F).inv.app P) (J.sheafifyCompIso F P).inv
  -/
  dsimp [sheafificationWhiskerRightIso, sheafifyCompIso]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp ( …
  -/
  simp only [Category.id_comp, Category.comp_id]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp ( …
  -/
  erw [Category.id_comp]
  /-
    🎉 no goals
  -/


@[simp, reassoc]
theorem whiskerRight_toSheafify_sheafifyCompIso_hom :
    whiskerRight (J.toSheafify _) _ ≫ (J.sheafifyCompIso F P).hom = J.toSheafify _ := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.whiskerRight (J.toShe …
  -/
  dsimp [sheafifyCompIso]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.whiskerRight (J.toShe …
  -/
  erw [whiskerRight_comp, Category.assoc]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.whiskerRight (J.toPlu …
  -/
  slice_lhs 2 3 => rw [plusCompIso_whiskerRight]
  rw [Category.assoc, ← J.plusMap_comp, whiskerRight_toPlus_comp_plusCompIso_hom, ←
    Category.assoc, whiskerRight_toPlus_comp_plusCompIso_hom]
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (J.toPlus (P.comp F)) (J.plusMap (J.t …
  -/
  rfl
  /-
    🎉 no goals
  -/


@[simp, reassoc]
theorem toSheafify_comp_sheafifyCompIso_inv :
    J.toSheafify _ ≫ (J.sheafifyCompIso F P).inv = whiskerRight (J.toSheafify _) _ := by
  /-
    C : Type u
    inst✝⁸ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝⁷ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝⁶ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁵ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁴ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝³ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝² : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D), …
    P : CategoryTheory.Functor (Opposite C) D
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (J.toSheafify (P.comp F)) (J.sheafify …
  -/
  rw [Iso.comp_inv_eq]; simp
                        /-
                          🎉 no goals
                        -/


@[simp]
theorem sheafifyCompIso_inv_eq_sheafifyLift :
    (J.sheafifyCompIso F P).inv =
      J.sheafifyLift (whiskerRight (J.toSheafify P) F)
        (HasSheafCompose.isSheaf _ ((J.sheafify_isSheaf _))) := by
  /-
    C : Type u
    inst✝¹² : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝¹¹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝¹⁰ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁹ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁸ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁷ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁶ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝⁴ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P : CategoryTheory.Functor (Opposite C) D
    inst✝³ : CategoryTheory.ConcreteCategory D
    inst✝² : CategoryTheory.Limits.PreservesLimits (CategoryTheory.forget D)
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : (CategoryTheory.forget D).ReflectsIsomorphisms
    ⊢ Eq (J.sheafifyCompIso F P).inv (J.sheafifyLift (CategoryTheory.whiskerRight  …
  -/
  apply J.sheafifyLift_unique
  /-
    case a
    C : Type u
    inst✝¹² : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝¹¹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝¹⁰ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁹ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁸ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁷ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁶ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝⁴ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P : CategoryTheory.Functor (Opposite C) D
    inst✝³ : CategoryTheory.ConcreteCategory D
    inst✝² : CategoryTheory.Limits.PreservesLimits (CategoryTheory.forget D)
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : (CategoryTheory.forget D).ReflectsIsomorphisms
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (J.toSheafify (P.comp F)) (J.sheafify …
  -/
  rw [Iso.comp_inv_eq]
  /-
    case a
    C : Type u
    inst✝¹² : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    D : Type w₁
    inst✝¹¹ : CategoryTheory.Category.{max v u, w₁} D
    E : Type w₂
    inst✝¹⁰ : CategoryTheory.Category.{max v u, w₂} E
    F : CategoryTheory.Functor D E
    inst✝⁹ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁸ : ∀ (α β : Type (max v u)) (fst snd : β → α), CategoryTheory.Limits.Has …
    inst✝⁷ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁶ : ∀ (X : C), CategoryTheory.Limits.HasColimitsOfShape (Opposite (J.Cove …
    inst✝⁵ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝⁴ : ∀ (X : C) (W : J.Cover X) (P : CategoryTheory.Functor (Opposite C) D) …
    P : CategoryTheory.Functor (Opposite C) D
    inst✝³ : CategoryTheory.ConcreteCategory D
    inst✝² : CategoryTheory.Limits.PreservesLimits (CategoryTheory.forget D)
    inst✝¹ : ∀ (X : C), CategoryTheory.Limits.PreservesColimitsOfShape (Opposite ( …
    inst✝ : (CategoryTheory.forget D).ReflectsIsomorphisms
    ⊢ Eq (J.toSheafify (P.comp F)) (CategoryTheory.CategoryStruct.comp (CategoryTh …
  -/
  simp
  /-
    🎉 no goals
  -/


