@[to_additive]
instance : InfSet (Submonoid M) :=
  ⟨fun s =>
    { carrier := ⋂ t ∈ s, ↑t
      one_mem' := Set.mem_biInter fun i _ => i.one_mem
      mul_mem' := fun hx hy =>
        Set.mem_biInter fun i h =>
                        /-
                          M : Type u_1
                          N : Type u_2
                          A : Type u_3
                          inst✝¹ : MulOneClass M
                          s✝ : Set M
                          inst✝ : AddZeroClass A
                          t : Set A
                          S : Submonoid M
                          s : Set (Submonoid M)
                          a✝ b✝ : M
                          hx : Membership.mem (Set.iInter fun t => Set.iInter fun h => ↑t) a✝
                          hy : Membership.mem (Set.iInter fun t => Set.iInter fun h => ↑t) b✝
                          i : Submonoid M
                          h : Membership.mem s i
                          ⊢ Membership.mem i a✝
                        -/
                        /-
                          🎉 no goals
                        -/
          i.mul_mem (by apply Set.mem_iInter₂.1 hx i h) (by apply Set.mem_iInter₂.1 hy i h) }⟩
                                                            /-
                                                              🎉 no goals
                                                            -/


@[to_additive (attr := simp, norm_cast)]
theorem coe_sInf (S : Set (Submonoid M)) : ((sInf S : Submonoid M) : Set M) = ⋂ s ∈ S, ↑s :=
  rfl


@[to_additive]
theorem mem_sInf {S : Set (Submonoid M)} {x : M} : x ∈ sInf S ↔ ∀ p ∈ S, x ∈ p :=
  Set.mem_iInter₂


@[to_additive]
theorem mem_iInf {ι : Sort*} {S : ι → Submonoid M} {x : M} : (x ∈ ⨅ i, S i) ↔ ∀ i, x ∈ S i := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    ι : Sort u_4
    S : ι → Submonoid M
    x : M
    ⊢ Iff (Membership.mem (iInf fun i => S i) x) (∀ (i : ι), Membership.mem (S i) x)
  -/
  simp only [iInf, mem_sInf, Set.forall_mem_range]
  /-
    🎉 no goals
  -/


@[to_additive (attr := simp, norm_cast)]
theorem coe_iInf {ι : Sort*} {S : ι → Submonoid M} : (↑(⨅ i, S i) : Set M) = ⋂ i, S i := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    ι : Sort u_4
    S : ι → Submonoid M
    ⊢ Eq (↑(iInf fun i => S i)) (Set.iInter fun i => ↑(S i))
  -/
  simp only [iInf, coe_sInf, Set.biInter_range]
  /-
    🎉 no goals
  -/


/-- Submonoids of a monoid form a complete lattice. -/
@[to_additive "The `AddSubmonoid`s of an `AddMonoid` form a complete lattice."]
instance : CompleteLattice (Submonoid M) :=
  { (completeLatticeOfInf (Submonoid M)) fun _ =>
      IsGLB.of_image (f := (SetLike.coe : Submonoid M → Set M))
        (@fun S T => show (S : Set M) ≤ T ↔ S ≤ T from SetLike.coe_subset_coe)
        isGLB_biInf with
    le := (· ≤ ·)
    lt := (· < ·)
    bot := ⊥
    bot_le := fun S _ hx => (mem_bot.1 hx).symm ▸ S.one_mem
    top := ⊤
    le_top := fun _ x _ => mem_top x
    inf := (· ⊓ ·)
    sInf := InfSet.sInf
    le_inf := fun _ _ _ ha hb _ hx => ⟨ha hx, hb hx⟩
    inf_le_left := fun _ _ _ => And.left
    inf_le_right := fun _ _ _ => And.right }


/-- The `Submonoid` generated by a set. -/
@[to_additive "The `AddSubmonoid` generated by a set"]
def closure (s : Set M) : Submonoid M :=
  sInf { S | s ⊆ S }


@[to_additive]
theorem mem_closure {x : M} : x ∈ closure s ↔ ∀ S : Submonoid M, s ⊆ S → x ∈ S :=
  mem_sInf


/-- The submonoid generated by a set includes the set. -/
@[to_additive (attr := simp, aesop safe 20 apply (rule_sets := [SetLike]))
  "The `AddSubmonoid` generated by a set includes the set."]
theorem subset_closure : s ⊆ closure s := fun _ hx => mem_closure.2 fun _ hS => hS hx


@[to_additive]
theorem not_mem_of_not_mem_closure {P : M} (hP : P ∉ closure s) : P ∉ s := fun h =>
  hP (subset_closure h)


/-- A submonoid `S` includes `closure s` if and only if it includes `s`. -/
@[to_additive (attr := simp)
"An additive submonoid `S` includes `closure s` if and only if it includes `s`"]
theorem closure_le : closure s ≤ S ↔ s ⊆ S :=
  ⟨Subset.trans subset_closure, fun h => sInf_le h⟩


/-- Submonoid closure of a set is monotone in its argument: if `s ⊆ t`,
then `closure s ≤ closure t`. -/
@[to_additive (attr := gcongr)
      "Additive submonoid closure of a set is monotone in its argument: if `s ⊆ t`,
      then `closure s ≤ closure t`"]
theorem closure_mono ⦃s t : Set M⦄ (h : s ⊆ t) : closure s ≤ closure t :=
  closure_le.2 <| Subset.trans h subset_closure


@[to_additive]
theorem closure_eq_of_le (h₁ : s ⊆ S) (h₂ : S ≤ closure s) : closure s = S :=
  le_antisymm (closure_le.2 h₁) h₂


/-- An induction principle for closure membership. If `p` holds for `1` and all elements of `s`, and
is preserved under multiplication, then `p` holds for all elements of the closure of `s`. -/
@[to_additive (attr := elab_as_elim)
      "An induction principle for additive closure membership. If `p` holds for `0` and all
      elements of `s`, and is preserved under addition, then `p` holds for all elements of the
      additive closure of `s`."]
theorem closure_induction {s : Set M} {p : (x : M) → x ∈ closure s → Prop}
    (mem : ∀ (x) (h : x ∈ s), p x (subset_closure h)) (one : p 1 (one_mem _))
    (mul : ∀ x y hx hy, p x hx → p y hy → p (x * y) (mul_mem hx hy)) {x} (hx : x ∈ closure s) :
    p x hx :=
  let S : Submonoid M :=
    { carrier := { x | ∃ hx, p x hx }
      one_mem' := ⟨_, one⟩
      mul_mem' := fun ⟨_, hpx⟩ ⟨_, hpy⟩ ↦ ⟨_, mul _ _ _ _ hpx hpy⟩ }
  closure_le (S := S) |>.mpr (fun y hy ↦ ⟨subset_closure hy, mem y hy⟩) hx |>.elim fun _ ↦ id


@[deprecated closure_induction (since := "2024-10-10")]
alias closure_induction' := closure_induction


/-- An induction principle for closure membership for predicates with two arguments. -/
@[to_additive (attr := elab_as_elim)
      "An induction principle for additive closure membership for predicates with two arguments."]
theorem closure_induction₂ {p : (x y : M) → x ∈ closure s → y ∈ closure s → Prop}
    (mem : ∀ (x) (y) (hx : x ∈ s) (hy : y ∈ s), p x y (subset_closure hx) (subset_closure hy))
    (one_left : ∀ x hx, p 1 x (one_mem _) hx) (one_right : ∀ x hx, p x 1 hx (one_mem _))
    (mul_left : ∀ x y z hx hy hz, p x z hx hz → p y z hy hz → p (x * y) z (mul_mem hx hy) hz)
    (mul_right : ∀ x y z hx hy hz, p z x hz hx → p z y hz hy → p z (x * y) hz (mul_mem hx hy))
    {x y : M} (hx : x ∈ closure s) (hy : y ∈ closure s) : p x y hx hy := by
  induction hy using closure_induction with
  | mem z hz => induction hx using closure_induction with
    | mem _ h => exact mem _ _ h hz
    | one => exact one_left _ (subset_closure hz)
    | mul _ _ _ _ h₁ h₂ => exact mul_left _ _ _ _ _ _ h₁ h₂
  | one => exact one_right x hx
  | mul _ _ _ _ h₁ h₂ => exact mul_right _ _ _ _ _ hx h₁ h₂


/-- If `s` is a dense set in a monoid `M`, `Submonoid.closure s = ⊤`, then in order to prove that
some predicate `p` holds for all `x : M` it suffices to verify `p x` for `x ∈ s`, verify `p 1`,
and verify that `p x` and `p y` imply `p (x * y)`. -/
@[to_additive (attr := elab_as_elim)
      "If `s` is a dense set in an additive monoid `M`, `AddSubmonoid.closure s = ⊤`, then in
      order to prove that some predicate `p` holds for all `x : M` it suffices to verify `p x` for
      `x ∈ s`, verify `p 0`, and verify that `p x` and `p y` imply `p (x + y)`."]
theorem dense_induction {p : M → Prop} (s : Set M) (closure : closure s = ⊤) (mem : ∀ x ∈ s, p x)
    (one : p 1) (mul : ∀ x y, p x → p y → p (x * y)) (x : M) : p x := by
  induction closure.symm ▸ mem_top x using closure_induction with
  | mem _ h => exact mem _ h
  | one => exact one
  | mul _ _ _ _ h₁ h₂ => exact mul _ _ h₁ h₂

/- The argument `s : Set M` is explicit in `Submonoid.dense_induction` because the type of the
induction variable, namely `x : M`, does not reference `x`. Making `s` explicit allows the user
to apply the induction principle while deferring the proof of `closure s = ⊤` without creating
metavariables, as in the following example. -/

/-- The `Submonoid.closure` of a set is the union of `{1}` and its `Subsemigroup.closure`. -/
lemma closure_eq_one_union (s : Set M) :
    closure s = {(1 : M)} ∪ (Subsemigroup.closure s : Set M) := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    s : Set M
    ⊢ Eq (↑(Submonoid.closure s)) (Union.union (Singleton.singleton 1) ↑(Subsemigr …
  -/
  apply le_antisymm
    /-
      case a
      M : Type u_1
      inst✝ : MulOneClass M
      s : Set M
      ⊢ LE.le (↑(Submonoid.closure s)) (Union.union (Singleton.singleton 1) ↑(Subsem …
    -/
  · intro x hx
    induction hx using closure_induction with
    | mem x hx => exact Or.inr <| Subsemigroup.subset_closure hx
    | one => exact Or.inl <| by simp
    | mul x hx y hy hx hy =>
      simp only [singleton_union, mem_insert_iff, SetLike.mem_coe] at hx hy
      obtain ⟨(rfl | hx), (rfl | hy)⟩ := And.intro hx hy
      all_goals simp_all
      exact Or.inr <| mul_mem hx hy
    /-
      case a
      M : Type u_1
      inst✝ : MulOneClass M
      s : Set M
      ⊢ LE.le (Union.union (Singleton.singleton 1) ↑(Subsemigroup.closure s)) ↑(Subm …
    -/
  · rintro x (hx | hx)
      /-
        case a.inl
        M : Type u_1
        inst✝ : MulOneClass M
        s : Set M
        x : M
        hx : Membership.mem (Singleton.singleton 1) x
        ⊢ Membership.mem (↑(Submonoid.closure s)) x
      -/
    · exact (show x = 1 by simpa using hx) ▸ one_mem (closure s)
      /-
        🎉 no goals
      -/
      /-
        case a.inr
        M : Type u_1
        inst✝ : MulOneClass M
        s : Set M
        x : M
        hx : Membership.mem (↑(Subsemigroup.closure s)) x
        ⊢ Membership.mem (↑(Submonoid.closure s)) x
      -/
    · exact Subsemigroup.closure_le.mpr subset_closure hx
      /-
        🎉 no goals
      -/


/-- `closure` forms a Galois insertion with the coercion to set. -/
@[to_additive "`closure` forms a Galois insertion with the coercion to set."]
protected def gi : GaloisInsertion (@closure M _) SetLike.coe where
  choice s _ := closure s
  gc _ _ := closure_le
  le_l_u _ := subset_closure
  choice_eq _ _ := rfl


/-- Closure of a submonoid `S` equals `S`. -/
@[to_additive (attr := simp) "Additive closure of an additive submonoid `S` equals `S`"]
theorem closure_eq : closure (S : Set M) = S :=
  (Submonoid.gi M).l_u_eq S


@[to_additive (attr := simp)]
theorem closure_empty : closure (∅ : Set M) = ⊥ :=
  (Submonoid.gi M).gc.l_bot


@[to_additive (attr := simp)]
theorem closure_univ : closure (univ : Set M) = ⊤ :=
  @coe_top M _ ▸ closure_eq ⊤


@[to_additive]
theorem closure_union (s t : Set M) : closure (s ∪ t) = closure s ⊔ closure t :=
  (Submonoid.gi M).gc.l_sup


@[to_additive]
theorem sup_eq_closure (N N' : Submonoid M) : N ⊔ N' = closure ((N : Set M) ∪ (N' : Set M)) := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    N N' : Submonoid M
    ⊢ Eq (Max.max N N') (Submonoid.closure (Union.union ↑N ↑N'))
  -/
  simp_rw [closure_union, closure_eq]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem closure_iUnion {ι} (s : ι → Set M) : closure (⋃ i, s i) = ⨆ i, closure (s i) :=
  (Submonoid.gi M).gc.l_iSup


@[to_additive]
theorem closure_singleton_le_iff_mem (m : M) (p : Submonoid M) : closure {m} ≤ p ↔ m ∈ p := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    m : M
    p : Submonoid M
    ⊢ Iff (LE.le (Submonoid.closure (Singleton.singleton m)) p) (Membership.mem p m)
  -/
  rw [closure_le, singleton_subset_iff, SetLike.mem_coe]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem mem_iSup {ι : Sort*} (p : ι → Submonoid M) {m : M} :
    (m ∈ ⨆ i, p i) ↔ ∀ N, (∀ i, p i ≤ N) → m ∈ N := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    ι : Sort u_4
    p : ι → Submonoid M
    m : M
    ⊢ Iff (Membership.mem (iSup fun i => p i) m) (∀ (N : Submonoid M), (∀ (i : ι), …
  -/
  rw [← closure_singleton_le_iff_mem, le_iSup_iff]
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    ι : Sort u_4
    p : ι → Submonoid M
    m : M
    ⊢ Iff (∀ (b : Submonoid M), (∀ (i : ι), LE.le (p i) b) → LE.le (Submonoid.clos …
  -/
  simp only [closure_singleton_le_iff_mem]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem iSup_eq_closure {ι : Sort*} (p : ι → Submonoid M) :
    ⨆ i, p i = Submonoid.closure (⋃ i, (p i : Set M)) := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    ι : Sort u_4
    p : ι → Submonoid M
    ⊢ Eq (iSup fun i => p i) (Submonoid.closure (Set.iUnion fun i => ↑(p i)))
  -/
  simp_rw [Submonoid.closure_iUnion, Submonoid.closure_eq]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem disjoint_def {p₁ p₂ : Submonoid M} :
    Disjoint p₁ p₂ ↔ ∀ {x : M}, x ∈ p₁ → x ∈ p₂ → x = 1 := by
  /-
    M : Type u_1
    inst✝ : MulOneClass M
    p₁ p₂ : Submonoid M
    ⊢ Iff (Disjoint p₁ p₂) (∀ {x : M}, Membership.mem p₁ x → Membership.mem p₂ x → …
  -/
  simp_rw [disjoint_iff_inf_le, SetLike.le_def, mem_inf, and_imp, mem_bot]
  /-
    🎉 no goals
  -/


@[to_additive]
theorem disjoint_def' {p₁ p₂ : Submonoid M} :
    Disjoint p₁ p₂ ↔ ∀ {x y : M}, x ∈ p₁ → y ∈ p₂ → x = y → x = 1 :=
  disjoint_def.trans ⟨fun h _ _ hx hy hxy => h hx <| hxy.symm ▸ hy, fun h _ hx hx' => h hx hx' rfl⟩


/-- If two monoid homomorphisms are equal on a set, then they are equal on its submonoid closure. -/
@[to_additive
      "If two monoid homomorphisms are equal on a set, then they are equal on its submonoid
      closure."]
theorem eqOn_closureM {f g : M →* N} {s : Set M} (h : Set.EqOn f g s) : Set.EqOn f g (closure s) :=
  show closure s ≤ f.eqLocusM g from closure_le.2 h


@[to_additive]
theorem eq_of_eqOn_denseM {s : Set M} (hs : closure s = ⊤) {f g : M →* N} (h : s.EqOn f g) :
    f = g :=
  eq_of_eqOn_topM <| hs ▸ eqOn_closureM h


/-- The submonoid consisting of the units of a monoid -/
@[to_additive "The additive submonoid consisting of the additive units of an additive monoid"]
def IsUnit.submonoid (M : Type*) [Monoid M] : Submonoid M where
  carrier := setOf IsUnit
                 /-
                   M✝ : Type u_1
                   N : Type u_2
                   A : Type u_3
                   inst✝² : Monoid M✝
                   inst✝¹ : Monoid N
                   s : Set M✝
                   M : Type u_4
                   inst✝ : Monoid M
                   ⊢ Membership.mem { carrier := setOf IsUnit, mul_mem' := ⋯ }.carrier 1
                 -/
  one_mem' := by simp only [isUnit_one, Set.mem_setOf_eq]
    /-
      M✝ : Type u_1
      N : Type u_2
      A : Type u_3
      inst✝² : Monoid M✝
      inst✝¹ : Monoid N
      s : Set M✝
      M : Type u_4
      inst✝ : Monoid M
      ⊢ ∀ {a b : M}, Membership.mem (setOf IsUnit) a → Membership.mem (setOf IsUnit) …
    -/
                 /-
                   🎉 no goals
                 -/
    /-
      M✝ : Type u_1
      N : Type u_2
      A : Type u_3
      inst✝² : Monoid M✝
      inst✝¹ : Monoid N
      s : Set M✝
      M : Type u_4
      inst✝ : Monoid M
      a b : M
      ha : Membership.mem (setOf IsUnit) a
      hb : Membership.mem (setOf IsUnit) b
      ⊢ Membership.mem (setOf IsUnit) (HMul.hMul a b)
    -/
  mul_mem' := by
    /-
      M✝ : Type u_1
      N : Type u_2
      A : Type u_3
      inst✝² : Monoid M✝
      inst✝¹ : Monoid N
      s : Set M✝
      M : Type u_4
      inst✝ : Monoid M
      a b : M
      ha : IsUnit a
      hb : IsUnit b
      ⊢ IsUnit (HMul.hMul a b)
    -/
    intro a b ha hb
    /-
      🎉 no goals
    -/
    rw [Set.mem_setOf_eq] at *
    exact IsUnit.mul ha hb


@[to_additive]
theorem IsUnit.mem_submonoid_iff {M : Type*} [Monoid M] (a : M) :
    a ∈ IsUnit.submonoid M ↔ IsUnit a := by
  /-
    M : Type u_4
    inst✝ : Monoid M
    a : M
    ⊢ Iff (Membership.mem (IsUnit.submonoid M) a) (IsUnit a)
  -/
  change a ∈ setOf IsUnit ↔ IsUnit a
  /-
    M : Type u_4
    inst✝ : Monoid M
    a : M
    ⊢ Iff (Membership.mem (setOf IsUnit) a) (IsUnit a)
  -/
  rw [Set.mem_setOf_eq]
  /-
    🎉 no goals
  -/


/-- Let `s` be a subset of a monoid `M` such that the closure of `s` is the whole monoid.
Then `MonoidHom.ofClosureEqTopLeft` defines a monoid homomorphism from `M` asking for
a proof of `f (x * y) = f x * f y` only for `x ∈ s`. -/
@[to_additive
      "Let `s` be a subset of an additive monoid `M` such that the closure of `s` is
      the whole monoid. Then `AddMonoidHom.ofClosureEqTopLeft` defines an additive monoid
      homomorphism from `M` asking for a proof of `f (x + y) = f x + f y` only for `x ∈ s`. "]
def ofClosureMEqTopLeft {M N} [Monoid M] [Monoid N] {s : Set M} (f : M → N) (hs : closure s = ⊤)
    (h1 : f 1 = 1) (hmul : ∀ x ∈ s, ∀ (y), f (x * y) = f x * f y) :
    M →* N where
  toFun := f
  map_one' := h1
  map_mul' x :=
                                                   /-
                                                     M✝ : Type u_1
                                                     N✝ : Type u_2
                                                     A : Type u_3
                                                     inst✝³ : Monoid M✝
                                                     inst✝² : Monoid N✝
                                                     s✝ : Set M✝
                                                     M : Type ?u.21564
                                                     N : Type ?u.21567
                                                     inst✝¹ : Monoid M
                                                     inst✝ : Monoid N
                                                     s : Set M
                                                     f : M → N
                                                     hs : Eq (Submonoid.closure s) Top.top
                                                     h1 : Eq (f 1) 1
                                                     hmul : ∀ (x : M), Membership.mem s x → ∀ (y : M), Eq (f (HMul.hMul x y)) (HMul …
                                                     x y : M
                                                     ⊢ Eq (f (HMul.hMul 1 y)) (HMul.hMul (f 1) (f y))
                                                   -/
    dense_induction (p := _) _ hs hmul fun y => by rw [one_mul, h1, one_mul]
                                                   /-
                                                     🎉 no goals
                                                   -/
                             /-
                               M✝ : Type u_1
                               N✝ : Type u_2
                               A : Type u_3
                               inst✝³ : Monoid M✝
                               inst✝² : Monoid N✝
                               s✝ : Set M✝
                               M : Type ?u.21564
                               N : Type ?u.21567
                               inst✝¹ : Monoid M
                               inst✝ : Monoid N
                               s : Set M
                               f : M → N
                               hs : Eq (Submonoid.closure s) Top.top
                               h1 : Eq (f 1) 1
                               hmul : ∀ (x : M), Membership.mem s x → ∀ (y : M), Eq (f (HMul.hMul x y)) (HMul …
                               x a b : M
                               ha : ∀ (y : M), Eq (f (HMul.hMul a y)) (HMul.hMul (f a) (f y))
                               hb : ∀ (y : M), Eq (f (HMul.hMul b y)) (HMul.hMul (f b) (f y))
                               y : M
                               ⊢ Eq (f (HMul.hMul (HMul.hMul a b) y)) (HMul.hMul (f (HMul.hMul a b)) (f y))
                             -/
      (fun a b ha hb y => by rw [mul_assoc, ha, ha, hb, mul_assoc]) x
                             /-
                               🎉 no goals
                             -/


@[to_additive (attr := simp, norm_cast)]
theorem coe_ofClosureMEqTopLeft (f : M → N) (hs : closure s = ⊤) (h1 hmul) :
    ⇑(ofClosureMEqTopLeft f hs h1 hmul) = f :=
  rfl


/-- Let `s` be a subset of a monoid `M` such that the closure of `s` is the whole monoid.
Then `MonoidHom.ofClosureEqTopRight` defines a monoid homomorphism from `M` asking for
a proof of `f (x * y) = f x * f y` only for `y ∈ s`. -/
@[to_additive
      "Let `s` be a subset of an additive monoid `M` such that the closure of `s` is
      the whole monoid. Then `AddMonoidHom.ofClosureEqTopRight` defines an additive monoid
      homomorphism from `M` asking for a proof of `f (x + y) = f x + f y` only for `y ∈ s`. "]
def ofClosureMEqTopRight {M N} [Monoid M] [Monoid N] {s : Set M} (f : M → N) (hs : closure s = ⊤)
    (h1 : f 1 = 1) (hmul : ∀ (x), ∀ y ∈ s, f (x * y) = f x * f y) :
    M →* N where
  toFun := f
  map_one' := h1
  map_mul' x y :=
                                                         /-
                                                           M✝ : Type u_1
                                                           N✝ : Type u_2
                                                           A : Type u_3
                                                           inst✝³ : Monoid M✝
                                                           inst✝² : Monoid N✝
                                                           s✝ : Set M✝
                                                           M : Type ?u.23451
                                                           N : Type ?u.23454
                                                           inst✝¹ : Monoid M
                                                           inst✝ : Monoid N
                                                           s : Set M
                                                           f : M → N
                                                           hs : Eq (Submonoid.closure s) Top.top
                                                           h1 : Eq (f 1) 1
                                                           hmul : ∀ (x y : M), Membership.mem s y → Eq (f (HMul.hMul x y)) (HMul.hMul (f  …
                                                           x y : M
                                                           ⊢ ∀ (x : M), Eq ({ toFun := f, map_one' := h1 }.toFun (HMul.hMul x 1)) (HMul.h …
                                                         -/
    dense_induction _ hs (fun y hy x => hmul x y hy) (by simp [h1])
                                                         /-
                                                           🎉 no goals
                                                         -/
      (fun y₁ y₂ (h₁ : ∀ _, f _ = f _ * f _) (h₂ : ∀ _, f _ = f _ * f _) x => by
        /-
          M✝ : Type u_1
          N✝ : Type u_2
          A : Type u_3
          inst✝³ : Monoid M✝
          inst✝² : Monoid N✝
          s✝ : Set M✝
          M : Type ?u.23451
          N : Type ?u.23454
          inst✝¹ : Monoid M
          inst✝ : Monoid N
          s : Set M
          f : M → N
          hs : Eq (Submonoid.closure s) Top.top
          h1 : Eq (f 1) 1
          hmul : ∀ (x y : M), Membership.mem s y → Eq (f (HMul.hMul x y)) (HMul.hMul (f  …
          x✝ y y₁ y₂ : M
          h₁ : ∀ (x : M), Eq (f (HMul.hMul x y₁)) (HMul.hMul (f x) (f y₁))
          h₂ : ∀ (x : M), Eq (f (HMul.hMul x y₂)) (HMul.hMul (f x) (f y₂))
          x : M
          ⊢ Eq ({ toFun := f, map_one' := h1 }.toFun (HMul.hMul x (HMul.hMul y₁ y₂))) (H …
        -/
        simp [← mul_assoc, h₁, h₂]) y x
        /-
          🎉 no goals
        -/


@[to_additive (attr := simp, norm_cast)]
theorem coe_ofClosureMEqTopRight (f : M → N) (hs : closure s = ⊤) (h1 hmul) :
    ⇑(ofClosureMEqTopRight f hs h1 hmul) = f :=
  rfl


