theorem finite_stableUnderComposition : StableUnderComposition @Finite := by
  /-
    ⊢ RingHom.StableUnderComposition @RingHom.Finite
  -/
  introv R hf hg
  /-
    R S T : Type u_1
    inst✝² : CommRing R
    inst✝¹ : CommRing S
    inst✝ : CommRing T
    f : RingHom R S
    g : RingHom S T
    hf : f.Finite
    hg : g.Finite
    ⊢ (g.comp f).Finite
  -/
  exact hg.comp hf
  /-
    🎉 no goals
  -/


theorem finite_respectsIso : RespectsIso @Finite := by
  /-
    ⊢ RingHom.RespectsIso @RingHom.Finite
  -/
  apply finite_stableUnderComposition.respectsIso
  /-
    ⊢ ∀ {R S : Type u_1} [inst : CommRing R] [inst_1 : CommRing S] (e : RingEquiv  …
  -/
  intros
  /-
    R✝ S✝ : Type u_1
    inst✝¹ : CommRing R✝
    inst✝ : CommRing S✝
    e✝ : RingEquiv R✝ S✝
    ⊢ e✝.toRingHom.Finite
  -/
  exact Finite.of_surjective _ (RingEquiv.toEquiv _).surjective
  /-
    🎉 no goals
  -/


lemma finite_containsIdentities : ContainsIdentities @Finite := Finite.id


theorem finite_isStableUnderBaseChange : IsStableUnderBaseChange @Finite := by
  /-
    ⊢ RingHom.IsStableUnderBaseChange @RingHom.Finite
  -/
  refine IsStableUnderBaseChange.mk _ finite_respectsIso ?_
  classical
  introv h
  replace h : Module.Finite R T := by
    rw [RingHom.Finite] at h; convert h; ext; simp_rw [Algebra.smul_def]; rfl
  suffices Module.Finite S (S ⊗[R] T) by
    rw [RingHom.Finite]; convert this; congr; ext; simp_rw [Algebra.smul_def]; rfl
  exact inferInstance


lemma Module.Finite_of_isLocalization (R S Rₚ Sₚ) [CommSemiring R] [CommRing S] [CommRing Rₚ]
    [CommRing Sₚ] [Algebra R S] [Algebra R Rₚ] [Algebra R Sₚ] [Algebra S Sₚ] [Algebra Rₚ Sₚ]
    [IsScalarTower R S Sₚ] [IsScalarTower R Rₚ Sₚ] (M : Submonoid R) [IsLocalization M Rₚ]
    [IsLocalization (Algebra.algebraMapSubmonoid S M) Sₚ] [hRS : Module.Finite R S] :
    Module.Finite Rₚ Sₚ := by
  classical
  have : algebraMap Rₚ Sₚ = IsLocalization.map (T := Algebra.algebraMapSubmonoid S M) Sₚ
      (algebraMap R S) (Submonoid.le_comap_map M) := by
    apply IsLocalization.ringHom_ext M
    simp only [IsLocalization.map_comp, ← IsScalarTower.algebraMap_eq]
  -- We claim that if `S` is generated by `T` as an `R`-module,
  -- then `S'` is generated by `T` as an `R'`-module.
  obtain ⟨T, hT⟩ := hRS
  use T.image (algebraMap S Sₚ)
  rw [eq_top_iff]
  rintro x -
  -- By the hypotheses, for each `x : S'`, we have `x = y / (f r)` for some `y : S` and `r : M`.
  -- Since `S` is generated by `T`, the image of `y` should fall in the span of the image of `T`.
  obtain ⟨y, ⟨_, ⟨r, hr, rfl⟩⟩, rfl⟩ :=
    IsLocalization.mk'_surjective (Algebra.algebraMapSubmonoid S M) x
  rw [IsLocalization.mk'_eq_mul_mk'_one, mul_comm, Finset.coe_image]
  have hy : y ∈ Submodule.span R ↑T := by rw [hT]; trivial
  replace hy : algebraMap S Sₚ y ∈ Submodule.map (IsScalarTower.toAlgHom R S Sₚ).toLinearMap
    (Submodule.span R (T : Set S)) := Submodule.mem_map_of_mem
--     -- Note: https://github.com/leanprover-community/mathlib4/pull/8386 had to specify the value of `f` below
      (f := (IsScalarTower.toAlgHom R S Sₚ).toLinearMap) hy
  rw [Submodule.map_span (IsScalarTower.toAlgHom R S Sₚ).toLinearMap T] at hy
  have H : Submodule.span R (algebraMap S Sₚ '' T) ≤
      (Submodule.span Rₚ (algebraMap S Sₚ '' T)).restrictScalars R := by
    rw [Submodule.span_le]; exact Submodule.subset_span
  -- Now, since `y ∈ span T`, and `(f r)⁻¹ ∈ R'`, `x / (f r)` is in `span T` as well.
  convert (Submodule.span Rₚ (algebraMap S Sₚ '' T)).smul_mem
    (IsLocalization.mk' Rₚ (1 : R) ⟨r, hr⟩) (H hy) using 1
  rw [Algebra.smul_def, this, IsLocalization.map_mk', map_one]


/-- If `S` is a finite `R`-algebra, then `S' = M⁻¹S` is a finite `R' = M⁻¹R`-algebra. -/
theorem RingHom.finite_localizationPreserves : RingHom.LocalizationPreserves @RingHom.Finite := by
  /-
    ⊢ RingHom.LocalizationPreserves @RingHom.Finite
  -/
  introv R hf
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  letI := f.toAlgebra
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this : Algebra R S := f.toAlgebra
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  letI := ((algebraMap S S').comp f).toAlgebra
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this✝ : Algebra R S := f.toAlgebra
    this : Algebra R S' := ((algebraMap S S').comp f).toAlgebra
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  let f' : R' →+* S' := IsLocalization.map S' f (Submonoid.le_comap_map M)
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this✝ : Algebra R S := f.toAlgebra
    this : Algebra R S' := ((algebraMap S S').comp f).toAlgebra
    f' : RingHom R' S' := IsLocalization.map S' f ⋯
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  letI := f'.toAlgebra
  have : IsScalarTower R R' S' := IsScalarTower.of_algebraMap_eq'
    (IsLocalization.map_comp M.le_comap_map).symm
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this✝² : Algebra R S := f.toAlgebra
    this✝¹ : Algebra R S' := ((algebraMap S S').comp f).toAlgebra
    f' : RingHom R' S' := IsLocalization.map S' f ⋯
    this✝ : Algebra R' S' := f'.toAlgebra
    this : IsScalarTower R R' S'
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  have : IsScalarTower R S S' := IsScalarTower.of_algebraMap_eq' rfl
  have : IsLocalization (Algebra.algebraMapSubmonoid S M) S' := by
    rwa [Algebra.algebraMapSubmonoid, RingHom.algebraMap_toAlgebra]
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this✝⁴ : Algebra R S := f.toAlgebra
    this✝³ : Algebra R S' := ((algebraMap S S').comp f).toAlgebra
    f' : RingHom R' S' := IsLocalization.map S' f ⋯
    this✝² : Algebra R' S' := f'.toAlgebra
    this✝¹ : IsScalarTower R R' S'
    this✝ : IsScalarTower R S S'
    this : IsLocalization (Algebra.algebraMapSubmonoid S M) S'
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  have : Module.Finite R S := hf
  /-
    R S : Type u_1
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    f : RingHom R S
    M : Submonoid R
    R' S' : Type u_1
    inst✝⁵ : CommRing R'
    inst✝⁴ : CommRing S'
    inst✝³ : Algebra R R'
    inst✝² : Algebra S S'
    inst✝¹ : IsLocalization M R'
    inst✝ : IsLocalization (Submonoid.map f M) S'
    hf : f.Finite
    this✝⁵ : Algebra R S := f.toAlgebra
    this✝⁴ : Algebra R S' := ((algebraMap S S').comp f).toAlgebra
    f' : RingHom R' S' := IsLocalization.map S' f ⋯
    this✝³ : Algebra R' S' := f'.toAlgebra
    this✝² : IsScalarTower R R' S'
    this✝¹ : IsScalarTower R S S'
    this✝ : IsLocalization (Algebra.algebraMapSubmonoid S M) S'
    this : Module.Finite R S
    ⊢ (IsLocalization.map S' f ⋯).Finite
  -/
  apply Module.Finite_of_isLocalization R S R' S' M
  /-
    🎉 no goals
  -/


theorem RingHom.localization_away_map_finite (r : R) [IsLocalization.Away r R']
    [IsLocalization.Away (f r) S'] (hf : f.Finite) : (IsLocalization.Away.map R' S' f r).Finite :=
  finite_localizationPreserves.away f r _ _ hf


open scoped Classical in
/-- Let `S` be an `R`-algebra, `M` a submonoid of `R`, and `S' = M⁻¹S`.
If the image of some `x : S` falls in the span of some finite `s ⊆ S'` over `R`,
then there exists some `m : M` such that `m • x` falls in the
span of `IsLocalization.finsetIntegerMultiple _ s` over `R`.
-/
theorem IsLocalization.smul_mem_finsetIntegerMultiple_span [Algebra R S] [Algebra R S']
    [IsScalarTower R S S'] [IsLocalization (M.map (algebraMap R S)) S'] (x : S) (s : Finset S')
    (hx : algebraMap S S' x ∈ Submodule.span R (s : Set S')) :
    ∃ m : M, m • x ∈
      Submodule.span R
        (IsLocalization.finsetIntegerMultiple (M.map (algebraMap R S)) s : Set S) := by
  let g : S →ₐ[R] S' :=
    AlgHom.mk' (algebraMap S S') fun c x => by simp [Algebra.algebraMap_eq_smul_one]
  -- We first obtain the `y' ∈ M` such that `s' = y' • s` is falls in the image of `S` in `S'`.
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  let y := IsLocalization.commonDenomOfFinset (M.map (algebraMap R S)) s
  have hx₁ : (y : S) • (s : Set S') = g '' _ :=
    (IsLocalization.finsetIntegerMultiple_image _ s).symm
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    hx₁ : Eq (HSMul.hSMul ↑y ↑s) (Set.image ⇑g ↑(IsLocalization.finsetIntegerMulti …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  obtain ⟨y', hy', e : algebraMap R S y' = y⟩ := y.prop
  have : algebraMap R S y' • (s : Set S') = y' • (s : Set S') := by
    simp_rw [Algebra.algebraMap_eq_smul_one, smul_assoc, one_smul]
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    hx₁ : Eq (HSMul.hSMul ↑y ↑s) (Set.image ⇑g ↑(IsLocalization.finsetIntegerMulti …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  rw [← e, this] at hx₁
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hx₁ : Eq (HSMul.hSMul y' ↑s) (Set.image ⇑g ↑(IsLocalization.finsetIntegerMulti …
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  replace hx₁ := congr_arg (Submodule.span R) hx₁
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (Submodule.span R (HSMul.hSMul y' ↑s)) (Submodule.span R (Set.image ⇑ …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  rw [Submodule.span_smul] at hx₁
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    hx : Membership.mem (Submodule.span R ↑s) ((algebraMap S S') x)
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  replace hx : _ ∈ y' • Submodule.span R (s : Set S') := Set.smul_mem_smul_set hx
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    hx : Membership.mem (HSMul.hSMul y' (Submodule.span R ↑s)) (HSMul.hSMul y' ((a …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  rw [hx₁] at hx
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    hx : Membership.mem (Submodule.span R (Set.image ⇑g ↑(IsLocalization.finsetInt …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  erw [← _root_.map_smul g, ← Submodule.map_span (g : S →ₗ[R] S')] at hx
  -- Since `x` falls in the span of `s` in `S'`, `y' • x : S` falls in the span of `s'` in `S'`.
  -- That is, there exists some `x' : S` in the span of `s'` in `S` and `x' = y' • x` in `S'`.
  -- Thus `a • (y' • x) = a • x' ∈ span s'` in `S` for some `a ∈ M`.
  /-
    case intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    hx : Membership.mem (Submodule.map (↑g) (Submodule.span R ↑(IsLocalization.fin …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  obtain ⟨x', hx', hx'' : algebraMap _ _ _ = _⟩ := hx
  obtain ⟨⟨_, a, ha₁, rfl⟩, ha₂⟩ :=
    (IsLocalization.eq_iff_exists (M.map (algebraMap R S)) S').mp hx''
  /-
    case intro.intro.intro.intro.intro.mk.intro.intro
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    x' : S
    hx' : Membership.mem (↑(Submodule.span R ↑(IsLocalization.finsetIntegerMultipl …
    hx'' : Eq ((algebraMap S S') x') (g (HSMul.hSMul y' x))
    a : R
    ha₁ : Membership.mem (↑M) a
    ha₂ : Eq (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x') (HMul.hMul (↑⟨(algebraMap R …
    ⊢ Exists fun m => Membership.mem (Submodule.span R ↑(IsLocalization.finsetInte …
  -/
  use (⟨a, ha₁⟩ : M) * (⟨y', hy'⟩ : M)
  convert (Submodule.span R
    (IsLocalization.finsetIntegerMultiple (Submonoid.map (algebraMap R S) M) s : Set S)).smul_mem
      a hx' using 1
  /-
    case h.e'_5
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    S' : Type u
    inst✝⁵ : CommRing S'
    inst✝⁴ : Algebra S S'
    inst✝³ : Algebra R S
    inst✝² : Algebra R S'
    inst✝¹ : IsScalarTower R S S'
    inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
    x : S
    s : Finset S'
    g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
    y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
    y' : R
    hy' : Membership.mem (↑M) y'
    e : Eq ((algebraMap R S) y') ↑y
    this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
    hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
    x' : S
    hx' : Membership.mem (↑(Submodule.span R ↑(IsLocalization.finsetIntegerMultipl …
    hx'' : Eq ((algebraMap S S') x') (g (HSMul.hSMul y' x))
    a : R
    ha₁ : Membership.mem (↑M) a
    ha₂ : Eq (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x') (HMul.hMul (↑⟨(algebraMap R …
    ⊢ Eq (HSMul.hSMul (HMul.hMul ⟨a, ha₁⟩ ⟨y', hy'⟩) x) (HSMul.hSMul a x')
  -/
  convert ha₂.symm using 1
    /-
      case h.e'_2
      R S : Type u
      inst✝⁷ : CommRing R
      inst✝⁶ : CommRing S
      M : Submonoid R
      S' : Type u
      inst✝⁵ : CommRing S'
      inst✝⁴ : Algebra S S'
      inst✝³ : Algebra R S
      inst✝² : Algebra R S'
      inst✝¹ : IsScalarTower R S S'
      inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
      x : S
      s : Finset S'
      g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
      y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
      y' : R
      hy' : Membership.mem (↑M) y'
      e : Eq ((algebraMap R S) y') ↑y
      this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
      hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
      x' : S
      hx' : Membership.mem (↑(Submodule.span R ↑(IsLocalization.finsetIntegerMultipl …
      hx'' : Eq ((algebraMap S S') x') (g (HSMul.hSMul y' x))
      a : R
      ha₁ : Membership.mem (↑M) a
      ha₂ : Eq (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x') (HMul.hMul (↑⟨(algebraMap R …
      ⊢ Eq (HSMul.hSMul (HMul.hMul ⟨a, ha₁⟩ ⟨y', hy'⟩) x) (HMul.hMul (↑⟨(algebraMap  …
    -/
  · rw [Subtype.coe_mk, Submonoid.smul_def, Submonoid.coe_mul, ← smul_smul]
    /-
      case h.e'_2
      R S : Type u
      inst✝⁷ : CommRing R
      inst✝⁶ : CommRing S
      M : Submonoid R
      S' : Type u
      inst✝⁵ : CommRing S'
      inst✝⁴ : Algebra S S'
      inst✝³ : Algebra R S
      inst✝² : Algebra R S'
      inst✝¹ : IsScalarTower R S S'
      inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
      x : S
      s : Finset S'
      g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
      y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
      y' : R
      hy' : Membership.mem (↑M) y'
      e : Eq ((algebraMap R S) y') ↑y
      this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
      hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
      x' : S
      hx' : Membership.mem (↑(Submodule.span R ↑(IsLocalization.finsetIntegerMultipl …
      hx'' : Eq ((algebraMap S S') x') (g (HSMul.hSMul y' x))
      a : R
      ha₁ : Membership.mem (↑M) a
      ha₂ : Eq (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x') (HMul.hMul (↑⟨(algebraMap R …
      ⊢ Eq (HSMul.hSMul (↑⟨a, ha₁⟩) (HSMul.hSMul (↑⟨y', hy'⟩) x)) (HMul.hMul ((algeb …
    -/
    exact Algebra.smul_def _ _
    /-
      🎉 no goals
    -/
    /-
      case h.e'_3
      R S : Type u
      inst✝⁷ : CommRing R
      inst✝⁶ : CommRing S
      M : Submonoid R
      S' : Type u
      inst✝⁵ : CommRing S'
      inst✝⁴ : Algebra S S'
      inst✝³ : Algebra R S
      inst✝² : Algebra R S'
      inst✝¹ : IsScalarTower R S S'
      inst✝ : IsLocalization (Submonoid.map (algebraMap R S) M) S'
      x : S
      s : Finset S'
      g : AlgHom R S S' := AlgHom.mk' (algebraMap S S') ⋯
      y : Subtype fun x => Membership.mem (Submonoid.map (algebraMap R S) M) x := Is …
      y' : R
      hy' : Membership.mem (↑M) y'
      e : Eq ((algebraMap R S) y') ↑y
      this : Eq (HSMul.hSMul ((algebraMap R S) y') ↑s) (HSMul.hSMul y' ↑s)
      hx₁ : Eq (HSMul.hSMul y' (Submodule.span R ↑s)) (Submodule.span R (Set.image ⇑ …
      x' : S
      hx' : Membership.mem (↑(Submodule.span R ↑(IsLocalization.finsetIntegerMultipl …
      hx'' : Eq ((algebraMap S S') x') (g (HSMul.hSMul y' x))
      a : R
      ha₁ : Membership.mem (↑M) a
      ha₂ : Eq (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x') (HMul.hMul (↑⟨(algebraMap R …
      ⊢ Eq (HSMul.hSMul a x') (HMul.hMul (↑⟨(algebraMap R S) a, ⋯⟩) x')
    -/
  · exact Algebra.smul_def _ _
    /-
      🎉 no goals
    -/


/-- If `M` is an `R' = S⁻¹R` module, and `x ∈ span R' s`,
then `t • x ∈ span R s` for some `t : S`. -/
theorem multiple_mem_span_of_mem_localization_span
    {N : Type*} [AddCommMonoid N] [Module R N] [Module R' N]
    [IsScalarTower R R' N] [IsLocalization M R'] (s : Set N) (x : N)
    (hx : x ∈ Submodule.span R' s) : ∃ (t : M), t • x ∈ Submodule.span R s := by
  classical
  obtain ⟨s', hss', hs'⟩ := Submodule.mem_span_finite_of_mem_span hx
  rsuffices ⟨t, ht⟩ : ∃ t : M, t • x ∈ Submodule.span R (s' : Set N)
  · exact ⟨t, Submodule.span_mono hss' ht⟩
  clear hx hss' s
  induction s' using Finset.induction_on generalizing x
  · use 1; simpa using hs'
  rename_i a s _ hs
  simp only [Finset.coe_insert, Finset.image_insert, Finset.coe_image, Subtype.coe_mk,
    Submodule.mem_span_insert] at hs' ⊢
  rcases hs' with ⟨y, z, hz, rfl⟩
  rcases IsLocalization.surj M y with ⟨⟨y', s'⟩, e⟩
  apply congrArg (fun x ↦ x • a) at e
  simp only [algebraMap_smul] at e
  rcases hs _ hz with ⟨t, ht⟩
  refine ⟨t * s', t * y', _, (Submodule.span R (s : Set N)).smul_mem s' ht, ?_⟩
  rw [smul_add, ← smul_smul, mul_comm, ← smul_smul, ← smul_smul, ← e, mul_comm, ← Algebra.smul_def]
  simp
  rfl


/-- If `S` is an `R' = M⁻¹R` algebra, and `x ∈ adjoin R' s`,
then `t • x ∈ adjoin R s` for some `t : M`. -/
theorem multiple_mem_adjoin_of_mem_localization_adjoin [Algebra R' S] [Algebra R S]
    [IsScalarTower R R' S] [IsLocalization M R'] (s : Set S) (x : S)
    (hx : x ∈ Algebra.adjoin R' s) : ∃ t : M, t • x ∈ Algebra.adjoin R s := by
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    R' : Type u
    inst✝⁵ : CommRing R'
    inst✝⁴ : Algebra R R'
    inst✝³ : Algebra R' S
    inst✝² : Algebra R S
    inst✝¹ : IsScalarTower R R' S
    inst✝ : IsLocalization M R'
    s : Set S
    x : S
    hx : Membership.mem (Algebra.adjoin R' s) x
    ⊢ Exists fun t => Membership.mem (Algebra.adjoin R s) (HSMul.hSMul t x)
  -/
  change ∃ t : M, t • x ∈ Subalgebra.toSubmodule (Algebra.adjoin R s)
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    R' : Type u
    inst✝⁵ : CommRing R'
    inst✝⁴ : Algebra R R'
    inst✝³ : Algebra R' S
    inst✝² : Algebra R S
    inst✝¹ : IsScalarTower R R' S
    inst✝ : IsLocalization M R'
    s : Set S
    x : S
    hx : Membership.mem (Algebra.adjoin R' s) x
    ⊢ Exists fun t => Membership.mem (Subalgebra.toSubmodule (Algebra.adjoin R s)) …
  -/
  change x ∈ Subalgebra.toSubmodule (Algebra.adjoin R' s) at hx
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    R' : Type u
    inst✝⁵ : CommRing R'
    inst✝⁴ : Algebra R R'
    inst✝³ : Algebra R' S
    inst✝² : Algebra R S
    inst✝¹ : IsScalarTower R R' S
    inst✝ : IsLocalization M R'
    s : Set S
    x : S
    hx : Membership.mem (Subalgebra.toSubmodule (Algebra.adjoin R' s)) x
    ⊢ Exists fun t => Membership.mem (Subalgebra.toSubmodule (Algebra.adjoin R s)) …
  -/
  simp_rw [Algebra.adjoin_eq_span] at hx ⊢
  /-
    R S : Type u
    inst✝⁷ : CommRing R
    inst✝⁶ : CommRing S
    M : Submonoid R
    R' : Type u
    inst✝⁵ : CommRing R'
    inst✝⁴ : Algebra R R'
    inst✝³ : Algebra R' S
    inst✝² : Algebra R S
    inst✝¹ : IsScalarTower R R' S
    inst✝ : IsLocalization M R'
    s : Set S
    x : S
    hx : Membership.mem (Submodule.span R' ↑(Submonoid.closure s)) x
    ⊢ Exists fun t => Membership.mem (Submodule.span R ↑(Submonoid.closure s)) (HS …
  -/
  exact multiple_mem_span_of_mem_localization_span M R' _ _ hx
  /-
    🎉 no goals
  -/


/-- `S` is a finite `R`-algebra if there exists a set `{ r }` that
  spans `R` such that `Sᵣ` is a finite `Rᵣ`-algebra. -/
theorem RingHom.finite_ofLocalizationSpan : RingHom.OfLocalizationSpan @RingHom.Finite := by
  classical
  rw [RingHom.ofLocalizationSpan_iff_finite]
  introv R hs H
  -- We first setup the instances
  letI := f.toAlgebra
  letI := fun r : s => (Localization.awayMap f r).toAlgebra
  have : ∀ r : s,
      IsLocalization ((Submonoid.powers (r : R)).map (algebraMap R S)) (Localization.Away (f r)) :=
    by intro r; rw [Submonoid.map_powers]; exact Localization.isLocalization
  haveI : ∀ r : s, IsScalarTower R (Localization.Away (r : R)) (Localization.Away (f r)) :=
    fun r => IsScalarTower.of_algebraMap_eq'
      (IsLocalization.map_comp (Submonoid.powers (r : R)).le_comap_map).symm
  -- By the hypothesis, we may find a finite generating set for each `Sᵣ`. This set can then be
  -- lifted into `R` by multiplying a sufficiently large power of `r`. I claim that the union of
  -- these generates `S`.
  constructor
  replace H := fun r => (H r).1
  choose s₁ s₂ using H
  let sf := fun x : s => IsLocalization.finsetIntegerMultiple (Submonoid.powers (f x)) (s₁ x)
  use s.attach.biUnion sf
  rw [Submodule.span_attach_biUnion, eq_top_iff]
  -- It suffices to show that `r ^ n • x ∈ span T` for each `r : s`, since `{ r ^ n }` spans `R`.
  -- This then follows from the fact that each `x : R` is a linear combination of the generating set
  -- of `Sᵣ`. By multiplying a sufficiently large power of `r`, we can cancel out the `r`s in the
  -- denominators of both the generating set and the coefficients.
  rintro x -
  apply Submodule.mem_of_span_eq_top_of_smul_pow_mem _ (s : Set R) hs _ _
  intro r
  obtain ⟨⟨_, n₁, rfl⟩, hn₁⟩ :=
    multiple_mem_span_of_mem_localization_span (Submonoid.powers (r : R))
      (Localization.Away (r : R)) (s₁ r : Set (Localization.Away (f r))) (algebraMap S _ x)
      (by rw [s₂ r]; trivial)
  dsimp only at hn₁
  rw [Submonoid.smul_def, Algebra.smul_def, IsScalarTower.algebraMap_apply R S, ← map_mul] at hn₁
  obtain ⟨⟨_, n₂, rfl⟩, hn₂⟩ :=
    IsLocalization.smul_mem_finsetIntegerMultiple_span (Submonoid.powers (r : R))
      (Localization.Away (f r)) _ (s₁ r) hn₁
  rw [Submonoid.smul_def, ← Algebra.smul_def, smul_smul, ← pow_add] at hn₂
  simp_rw [Submonoid.map_powers] at hn₂
  use n₂ + n₁
  exact le_iSup (fun x : s => Submodule.span R (sf x : Set S)) r hn₂

