/-- The type of profinite topological spaces. -/
abbrev Profinite := CompHausLike (fun X ↦ TotallyDisconnectedSpace X)


instance (X : Type*) [TopologicalSpace X]
    [TotallyDisconnectedSpace X] :  HasProp (fun Y ↦ TotallyDisconnectedSpace Y) X :=
  ⟨(inferInstance : TotallyDisconnectedSpace X)⟩


/-- Construct a term of `Profinite` from a type endowed with the structure of a
compact, Hausdorff and totally disconnected topological space.
-/
abbrev of (X : Type*) [TopologicalSpace X] [CompactSpace X] [T2Space X]
    [TotallyDisconnectedSpace X] : Profinite :=
  CompHausLike.of _ X


instance : Inhabited Profinite :=
  ⟨Profinite.of PEmpty⟩


instance {X : Profinite} : TotallyDisconnectedSpace X :=
  X.prop


instance {X : Profinite} : TotallyDisconnectedSpace ((forget Profinite).obj X) := by
  /-
    X : Profinite
    ⊢ TotallyDisconnectedSpace ((CategoryTheory.forget Profinite).obj X)
  -/
  change TotallyDisconnectedSpace X
  /-
    X : Profinite
    ⊢ TotallyDisconnectedSpace ↑X.toTop
  -/
  exact inferInstance
  /-
    🎉 no goals
  -/


/-- The fully faithful embedding of `Profinite` in `CompHaus`. -/
abbrev profiniteToCompHaus : Profinite ⥤ CompHaus :=
  compHausLikeToCompHaus _
-- Porting note: deriving fails, adding manually.
-- deriving Full, Faithful

-- Porting note: added, as it is not found otherwise.

instance {X : Profinite} : TotallyDisconnectedSpace (profiniteToCompHaus.obj X) :=
  X.prop


/-- The fully faithful embedding of `Profinite` in `TopCat`.
This is definitionally the same as the obvious composite. -/
abbrev Profinite.toTopCat : Profinite ⥤ TopCat :=
  CompHausLike.compHausLikeToTop _
-- Porting note: deriving fails, adding manually.
-- deriving Full, Faithful


/--
(Implementation) The object part of the connected_components functor from compact Hausdorff spaces
to Profinite spaces, given by quotienting a space by its connected components.
See: https://stacks.math.columbia.edu/tag/0900
-/
def CompHaus.toProfiniteObj (X : CompHaus.{u}) : Profinite.{u} where
  toTop := TopCat.of (ConnectedComponents X)
  is_compact := Quotient.compactSpace
  is_hausdorff := ConnectedComponents.t2
  prop := ConnectedComponents.totallyDisconnectedSpace


/-- (Implementation) The bijection of homsets to establish the reflective adjunction of Profinite
spaces in compact Hausdorff spaces.
-/
def Profinite.toCompHausEquivalence (X : CompHaus.{u}) (Y : Profinite.{u}) :
    (CompHaus.toProfiniteObj X ⟶ Y) ≃ (X ⟶ profiniteToCompHaus.obj Y) where
  toFun f := f.comp ⟨Quotient.mk'', continuous_quotient_mk'⟩
  invFun g :=
    { toFun := Continuous.connectedComponentsLift g.2
      continuous_toFun := Continuous.connectedComponentsLift_continuous g.2 }
  left_inv _ := ContinuousMap.ext <| ConnectedComponents.surjective_coe.forall.2 fun _ => rfl
  right_inv _ := ContinuousMap.ext fun _ => rfl


/-- The connected_components functor from compact Hausdorff spaces to profinite spaces,
left adjoint to the inclusion functor.
-/
def CompHaus.toProfinite : CompHaus ⥤ Profinite :=
  Adjunction.leftAdjointOfEquiv Profinite.toCompHausEquivalence fun _ _ _ _ _ => rfl


theorem CompHaus.toProfinite_obj' (X : CompHaus) :
    ↥(CompHaus.toProfinite.obj X) = ConnectedComponents X :=
  rfl


/-- Finite types are given the discrete topology. -/
def FintypeCat.botTopology (A : FintypeCat) : TopologicalSpace A := ⊥


theorem FintypeCat.discreteTopology (A : FintypeCat) : DiscreteTopology A :=
  ⟨rfl⟩


/-- The natural functor from `Fintype` to `Profinite`, endowing a finite type with the
discrete topology. -/
@[simps map_apply]
def FintypeCat.toProfinite : FintypeCat ⥤ Profinite where
  obj A := Profinite.of A
                  /-
                    X✝ Y✝ : FintypeCat
                    f : Quiver.Hom X✝ Y✝
                    ⊢ Continuous f
                  -/
  map f := ⟨f, by continuity⟩
                  /-
                    🎉 no goals
                  -/

-- This lemma is generated by `simps` but we don't actually want the `@[simp]` attribute.
-- https://github.com/leanprover-community/mathlib4/issues/18942

/-- `FintypeCat.toLightProfinite` is fully faithful. -/
def FintypeCat.toProfiniteFullyFaithful : toProfinite.FullyFaithful where
  preimage f := (f : _ → _)
  map_preimage _ := rfl
  preimage_map _ := rfl


instance : FintypeCat.toProfinite.Faithful := FintypeCat.toProfiniteFullyFaithful.faithful


instance : FintypeCat.toProfinite.Full := FintypeCat.toProfiniteFullyFaithful.full


instance (X : FintypeCat) : Fintype (FintypeCat.toProfinite.obj X) := inferInstanceAs (Fintype X)


instance (X : FintypeCat) : Fintype (Profinite.of X) := inferInstanceAs (Fintype X)


/-- An explicit limit cone for a functor `F : J ⥤ Profinite`, defined in terms of
`CompHaus.limitCone`, which is defined in terms of `TopCat.limitCone`. -/
def limitCone {J : Type v} [SmallCategory J] (F : J ⥤ Profinite.{max u v}) : Limits.Cone F where
  pt :=
    { toTop := (CompHaus.limitCone.{v, u} (F ⋙ profiniteToCompHaus)).pt.toTop
      prop := by
        /-
          J : Type v
          inst✝ : CategoryTheory.SmallCategory J
          F : CategoryTheory.Functor J Profinite
          ⊢ TotallyDisconnectedSpace ↑(CompHaus.limitCone (F.comp profiniteToCompHaus)). …
        -/
        change TotallyDisconnectedSpace ({ u : ∀ j : J, F.obj j | _ } : Type _)
        /-
          J : Type v
          inst✝ : CategoryTheory.SmallCategory J
          F : CategoryTheory.Functor J Profinite
          ⊢ TotallyDisconnectedSpace ↑(setOf fun u => ∀ {i j : J} (f : Quiver.Hom i j),  …
        -/
        exact Subtype.totallyDisconnectedSpace }
        /-
          🎉 no goals
        -/
  π :=
  { app := (CompHaus.limitCone.{v, u} (F ⋙ profiniteToCompHaus)).π.app
    -- Porting note: was `by tidy`:
    naturality := by
      /-
        J : Type v
        inst✝ : CategoryTheory.SmallCategory J
        F : CategoryTheory.Functor J Profinite
        ⊢ ∀ ⦃X Y : J⦄ (f : Quiver.Hom X Y), Eq (CategoryTheory.CategoryStruct.comp ((( …
      -/
      intro j k f
      /-
        J : Type v
        inst✝ : CategoryTheory.SmallCategory J
        F : CategoryTheory.Functor J Profinite
        j k : J
        f : Quiver.Hom j k
        ⊢ Eq (CategoryTheory.CategoryStruct.comp (((CategoryTheory.Functor.const J).ob …
      -/
      ext ⟨g, p⟩
      /-
        case w.mk
        J : Type v
        inst✝ : CategoryTheory.SmallCategory J
        F : CategoryTheory.Functor J Profinite
        j k : J
        f : Quiver.Hom j k
        g : (j : J) → ↑(((F.comp profiniteToCompHaus).comp compHausToTop).obj j)
        p : Membership.mem (setOf fun u => ∀ {i j : J} (f : Quiver.Hom i j), Eq ((((F. …
        ⊢ Eq ((CategoryTheory.CategoryStruct.comp (((CategoryTheory.Functor.const J).o …
      -/
      exact (p f).symm }
      /-
        🎉 no goals
      -/


/-- The limit cone `Profinite.limitCone F` is indeed a limit cone. -/
def limitConeIsLimit {J : Type v} [SmallCategory J] (F : J ⥤ Profinite.{max u v}) :
    Limits.IsLimit (limitCone F) where
  lift S :=
    (CompHaus.limitConeIsLimit.{v, u} (F ⋙ profiniteToCompHaus)).lift
      (profiniteToCompHaus.mapCone S)
  uniq S _ h := (CompHaus.limitConeIsLimit.{v, u} _).uniq (profiniteToCompHaus.mapCone S) _ h


/-- The adjunction between CompHaus.to_Profinite and Profinite.to_CompHaus -/
def toProfiniteAdjToCompHaus : CompHaus.toProfinite ⊣ profiniteToCompHaus :=
  Adjunction.adjunctionOfEquivLeft _ _


/-- The category of profinite sets is reflective in the category of compact Hausdorff spaces -/
instance toCompHaus.reflective : Reflective profiniteToCompHaus where
  adj := Profinite.toProfiniteAdjToCompHaus


noncomputable instance toCompHaus.createsLimits : CreatesLimits profiniteToCompHaus :=
  monadicCreatesLimits _


noncomputable instance toTopCat.reflective : Reflective Profinite.toTopCat :=
  Reflective.comp profiniteToCompHaus compHausToTop


noncomputable instance toTopCat.createsLimits : CreatesLimits Profinite.toTopCat :=
  monadicCreatesLimits _


instance hasLimits : Limits.HasLimits Profinite :=
  hasLimits_of_hasLimits_createsLimits Profinite.toTopCat


instance hasColimits : Limits.HasColimits Profinite :=
  hasColimits_of_reflective profiniteToCompHaus


instance forget_preservesLimits : Limits.PreservesLimits (forget Profinite) := by
  /-
    ⊢ CategoryTheory.Limits.PreservesLimits (CategoryTheory.forget Profinite)
  -/
  apply Limits.comp_preservesLimits Profinite.toTopCat (forget TopCat)
  /-
    🎉 no goals
  -/


theorem epi_iff_surjective {X Y : Profinite.{u}} (f : X ⟶ Y) : Epi f ↔ Function.Surjective f := by
  /-
    X Y : Profinite
    f : Quiver.Hom X Y
    ⊢ Iff (CategoryTheory.Epi f) (Function.Surjective ⇑f)
  -/
  constructor
  · -- Porting note: in mathlib3 `contrapose` saw through `Function.Surjective`.
    /-
      case mp
      X Y : Profinite
      f : Quiver.Hom X Y
      ⊢ CategoryTheory.Epi f → Function.Surjective ⇑f
    -/
    dsimp [Function.Surjective]
    /-
      case mp
      X Y : Profinite
      f : Quiver.Hom X Y
      ⊢ CategoryTheory.Epi f → ∀ (b : (CategoryTheory.forget Profinite).obj Y), Exis …
    -/
    contrapose!
    /-
      case mp
      X Y : Profinite
      f : Quiver.Hom X Y
      ⊢ (Exists fun b => ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) b …
    -/
    rintro ⟨y, hy⟩ hf
    /-
      case mp.intro
      X Y : Profinite
      f : Quiver.Hom X Y
      y : (CategoryTheory.forget Profinite).obj Y
      hy : ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) y
      hf : CategoryTheory.Epi f
      ⊢ False
    -/
    let C := Set.range f
    /-
      case mp.intro
      X Y : Profinite
      f : Quiver.Hom X Y
      y : (CategoryTheory.forget Profinite).obj Y
      hy : ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) y
      hf : CategoryTheory.Epi f
      C : Set ((CategoryTheory.forget Profinite).obj Y) := Set.range ⇑f
      ⊢ False
    -/
    have hC : IsClosed C := (isCompact_range f.continuous).isClosed
    /-
      case mp.intro
      X Y : Profinite
      f : Quiver.Hom X Y
      y : (CategoryTheory.forget Profinite).obj Y
      hy : ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) y
      hf : CategoryTheory.Epi f
      C : Set ((CategoryTheory.forget Profinite).obj Y) := Set.range ⇑f
      hC : IsClosed C
      ⊢ False
    -/
    let U := Cᶜ
    have hyU : y ∈ U := by
      refine Set.mem_compl ?_
      rintro ⟨y', hy'⟩
      exact hy y' hy'
    /-
      case mp.intro
      X Y : Profinite
      f : Quiver.Hom X Y
      y : (CategoryTheory.forget Profinite).obj Y
      hy : ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) y
      hf : CategoryTheory.Epi f
      C : Set ((CategoryTheory.forget Profinite).obj Y) := Set.range ⇑f
      hC : IsClosed C
      U : Set ((CategoryTheory.forget Profinite).obj Y) := HasCompl.compl C
      hyU : Membership.mem U y
      ⊢ False
    -/
    have hUy : U ∈ 𝓝 y := hC.compl_mem_nhds hyU
    /-
      case mp.intro
      X Y : Profinite
      f : Quiver.Hom X Y
      y : (CategoryTheory.forget Profinite).obj Y
      hy : ∀ (a : (CategoryTheory.forget Profinite).obj X), Ne (f a) y
      hf : CategoryTheory.Epi f
      C : Set ((CategoryTheory.forget Profinite).obj Y) := Set.range ⇑f
      hC : IsClosed C
      U : Set ((CategoryTheory.forget Profinite).obj Y) := HasCompl.compl C
      hyU : Membership.mem U y
      hUy : Membership.mem (nhds y) U
      ⊢ False
    -/
    obtain ⟨V, hV, hyV, hVU⟩ := isTopologicalBasis_isClopen.mem_nhds_iff.mp hUy
    classical
      let Z := of (ULift.{u} <| Fin 2)
      let g : Y ⟶ Z := ⟨(LocallyConstant.ofIsClopen hV).map ULift.up, LocallyConstant.continuous _⟩
      let h : Y ⟶ Z := ⟨fun _ => ⟨1⟩, continuous_const⟩
      have H : h = g := by
        rw [← cancel_epi f]
        ext x
        apply ULift.ext
        dsimp [g, LocallyConstant.ofIsClopen]
        -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
        erw [comp_apply, ContinuousMap.coe_mk, comp_apply, ContinuousMap.coe_mk,
          Function.comp_apply, if_neg]
        refine mt (fun α => hVU α) ?_
        simp only [U, C, Set.mem_range_self, not_true, not_false_iff, Set.mem_compl_iff]
      apply_fun fun e => (e y).down at H
      dsimp [g, LocallyConstant.ofIsClopen] at H
      -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
      erw [ContinuousMap.coe_mk, ContinuousMap.coe_mk, Function.comp_apply, if_pos hyV] at H
      exact top_ne_bot H
    /-
      case mpr
      X Y : Profinite
      f : Quiver.Hom X Y
      ⊢ Function.Surjective ⇑f → CategoryTheory.Epi f
    -/
  · rw [← CategoryTheory.epi_iff_surjective]
    /-
      case mpr
      X Y : Profinite
      f : Quiver.Hom X Y
      ⊢ CategoryTheory.Epi ⇑f → CategoryTheory.Epi f
    -/
    apply (forget Profinite).epi_of_epi_map
    /-
      🎉 no goals
    -/


/-- The pi-type of profinite spaces is profinite. -/
def pi {α : Type u} (β : α → Profinite) : Profinite := .of (Π (a : α), β a)


