variable (R) in
/-- The principal ideals of `R` form a submonoid of `Ideal R`. -/
def isPrincipalSubmonoid : Submonoid (Ideal R) where
  carrier := {I | IsPrincipal I}
  mul_mem' := by
    /-
      R : Type u_1
      inst✝ : CommRing R
      ⊢ ∀ {a b : Ideal R}, Membership.mem (setOf fun I => Submodule.IsPrincipal I) a …
    -/
    rintro _ _ ⟨x, rfl⟩ ⟨y, rfl⟩
    /-
      case mk.intro.mk.intro
      R : Type u_1
      inst✝ : CommRing R
      x y : R
      ⊢ Membership.mem (setOf fun I => Submodule.IsPrincipal I) (HMul.hMul (Submodul …
    -/
    exact ⟨x * y, span_singleton_mul_span_singleton x y⟩
    /-
      🎉 no goals
    -/
  one_mem' := ⟨1, one_eq_span⟩


theorem mem_isPrincipalSubmonoid_iff {I : Ideal R} :
    I ∈ isPrincipalSubmonoid R ↔ IsPrincipal I := Iff.rfl


theorem span_singleton_mem_isPrincipalSubmonoid (a : R) :
    span {a} ∈ isPrincipalSubmonoid R := mem_isPrincipalSubmonoid_iff.mpr ⟨a, rfl⟩


variable (R) in
/-- The non-zero-divisors principal ideals of `R` form a submonoid of `(Ideal R)⁰`. -/
def isPrincipalNonZeroDivisorsSubmonoid : Submonoid (Ideal R)⁰ where
  carrier := {I | IsPrincipal I.val}
  mul_mem' := by
    /-
      R : Type u_1
      inst✝ : CommRing R
      ⊢ ∀ {a b : Subtype fun x => Membership.mem (nonZeroDivisors (Ideal R)) x}, Mem …
    -/
    rintro ⟨_, _⟩ ⟨_, _⟩ ⟨x, rfl⟩ ⟨y, rfl⟩
    exact ⟨x * y, by
      simp_rw [Submonoid.mk_mul_mk, submodule_span_eq, span_singleton_mul_span_singleton]⟩
                     /-
                       R : Type u_1
                       inst✝ : CommRing R
                       ⊢ Eq (↑1) (Submodule.span R (Singleton.singleton 1))
                     -/
  one_mem' := ⟨1, by simp⟩
                     /-
                       🎉 no goals
                     -/


variable (R) in
/-- The equivalence between `Associates R` and the principal ideals of `R` defined by sending the
class of `x` to the principal ideal generated by `x`. -/
noncomputable def associatesEquivIsPrincipal :
    Associates R ≃ {I : Ideal R // IsPrincipal I} where
  toFun := _root_.Quotient.lift (fun x ↦ ⟨span {x}, x, rfl⟩)
                    /-
                      R : Type u_1
                      inst✝¹ : CommRing R
                      inst✝ : IsDomain R
                      x✝² x✝¹ : R
                      x✝ : HasEquiv.Equiv x✝² x✝¹
                      ⊢ Eq ((fun x => ⟨Ideal.span (Singleton.singleton x), ⋯⟩) x✝²) ((fun x => ⟨Idea …
                    -/
    (fun _ _ _ ↦ by simpa [span_singleton_eq_span_singleton])
                    /-
                      🎉 no goals
                    -/
  invFun I := .mk I.2.generator
  left_inv := Quotient.ind fun _ ↦ by simpa using
    Ideal.span_singleton_eq_span_singleton.mp (@Ideal.span_singleton_generator _ _ _ ⟨_, rfl⟩)
                    /-
                      R : Type u_1
                      inst✝¹ : CommRing R
                      inst✝ : IsDomain R
                      I : Subtype fun I => Submodule.IsPrincipal I
                      ⊢ Eq (Quotient.lift (fun x => ⟨Ideal.span (Singleton.singleton x), ⋯⟩) ⋯ ((fun …
                    -/
  right_inv I := by simp only [_root_.Quotient.lift_mk, span_singleton_generator, Subtype.coe_eta]
                    /-
                      🎉 no goals
                    -/


@[simp]
theorem associatesEquivIsPrincipal_apply (x : R) :
    associatesEquivIsPrincipal R (.mk x) = span {x} := rfl


@[simp]
theorem associatesEquivIsPrincipal_symm_apply {I : Ideal R} (hI : IsPrincipal I) :
    (associatesEquivIsPrincipal R).symm ⟨I, hI⟩ = .mk hI.generator := rfl


theorem associatesEquivIsPrincipal_mul (x y : Associates R) :
    (associatesEquivIsPrincipal R (x * y) : Ideal R) =
      (associatesEquivIsPrincipal R x) * (associatesEquivIsPrincipal R y) := by
  /-
    R : Type u_1
    inst✝¹ : CommRing R
    inst✝ : IsDomain R
    x y : Associates R
    ⊢ Eq (↑((Ideal.associatesEquivIsPrincipal R) (HMul.hMul x y))) (HMul.hMul ↑((I …
  -/
  rw [← quot_out x, ← quot_out y]
  /-
    R : Type u_1
    inst✝¹ : CommRing R
    inst✝ : IsDomain R
    x y : Associates R
    ⊢ Eq (↑((Ideal.associatesEquivIsPrincipal R) (HMul.hMul (Associates.mk (Quot.o …
  -/
  simp_rw [mk_mul_mk, associatesEquivIsPrincipal_apply, span_singleton_mul_span_singleton]
  /-
    🎉 no goals
  -/


@[simp]
theorem associatesEquivIsPrincipal_map_zero :
    (associatesEquivIsPrincipal R 0 : Ideal R) = 0 := by
  /-
    R : Type u_1
    inst✝¹ : CommRing R
    inst✝ : IsDomain R
    ⊢ Eq (↑((Ideal.associatesEquivIsPrincipal R) 0)) 0
  -/
  rw [← mk_zero, associatesEquivIsPrincipal_apply, Submodule.zero_eq_bot, span_singleton_eq_bot]
  /-
    🎉 no goals
  -/


@[simp]
theorem associatesEquivIsPrincipal_map_one :
    (associatesEquivIsPrincipal R 1 : Ideal R) = 1 := by
  /-
    R : Type u_1
    inst✝¹ : CommRing R
    inst✝ : IsDomain R
    ⊢ Eq (↑((Ideal.associatesEquivIsPrincipal R) 1)) 1
  -/
  rw [one_eq_mk_one, associatesEquivIsPrincipal_apply, span_singleton_one, one_eq_top]
  /-
    🎉 no goals
  -/


variable (R) in
/-- The `MulEquiv` version of `Ideal.associatesEquivIsPrincipal`. -/
noncomputable def associatesMulEquivIsPrincipal :
    Associates R ≃* (isPrincipalSubmonoid R) where
  __ := associatesEquivIsPrincipal R
  map_mul' _ _ := by
    /-
      R : Type u_1
      inst✝¹ : CommRing R
      inst✝ : IsDomain R
      x✝¹ x✝ : Associates R
      ⊢ Eq (__spread✝⁻⁰.toFun (HMul.hMul x✝¹ x✝)) (HMul.hMul (__spread✝⁻⁰.toFun x✝¹) …
    -/
    erw [Subtype.ext_iff, associatesEquivIsPrincipal_mul]
    /-
      R : Type u_1
      inst✝¹ : CommRing R
      inst✝ : IsDomain R
      x✝¹ x✝ : Associates R
      ⊢ Eq (HMul.hMul ↑((Ideal.associatesEquivIsPrincipal R) x✝¹) ↑((Ideal.associate …
    -/
    rfl
    /-
      🎉 no goals
    -/


variable (R) in
/-- A version of `Ideal.associatesEquivIsPrincipal` for non-zero-divisors generators. -/
noncomputable def associatesNonZeroDivisorsEquivIsPrincipal :
    Associates R⁰ ≃ {I : (Ideal R)⁰ // IsPrincipal (I : Ideal R)} :=
  calc Associates R⁰ ≃ (Associates R)⁰ := associatesNonZeroDivisorsEquiv.toEquiv.symm
    _ ≃ {I : {I : Ideal R // IsPrincipal I} // I.1 ∈ (Ideal R)⁰} :=
      Equiv.subtypeEquiv (associatesEquivIsPrincipal R)
        (fun x ↦ by rw [← quot_out x, mk_mem_nonZeroDivisors_associates,
          associatesEquivIsPrincipal_apply, span_singleton_nonZeroDivisors])
    _ ≃ {I : Ideal R // IsPrincipal I ∧ I ∈ (Ideal R)⁰} :=
      Equiv.subtypeSubtypeEquivSubtypeInter (fun I ↦ IsPrincipal I) (fun I ↦ I ∈ (Ideal R)⁰)
                                                                              /-
                                                                                R : Type u_1
                                                                                inst✝¹ : CommRing R
                                                                                inst✝ : IsDomain R
                                                                                ⊢ Eq (fun I => And (Submodule.IsPrincipal I) (Membership.mem (nonZeroDivisors  …
                                                                              -/
    _ ≃ {I : Ideal R // I ∈ (Ideal R)⁰ ∧ IsPrincipal I} := Equiv.setCongr (by simp_rw [and_comm])
                                                                              /-
                                                                                🎉 no goals
                                                                              -/
    _ ≃ {I : (Ideal R)⁰ // IsPrincipal I.1} := (Equiv.subtypeSubtypeEquivSubtypeInter _ _).symm


@[simp]
theorem associatesNonZeroDivisorsEquivIsPrincipal_apply (x : R⁰) :
    associatesNonZeroDivisorsEquivIsPrincipal R (.mk x) = Ideal.span {(x : R)} := rfl


theorem associatesNonZeroDivisorsEquivIsPrincipal_coe (x : Associates R⁰) :
    (associatesNonZeroDivisorsEquivIsPrincipal R x : Ideal R) =
      (associatesEquivIsPrincipal R (associatesNonZeroDivisorsEquiv.symm x)) := rfl


theorem associatesNonZeroDivisorsEquivIsPrincipal_mul (x y : Associates R⁰) :
    (associatesNonZeroDivisorsEquivIsPrincipal R (x * y) : Ideal R) =
      (associatesNonZeroDivisorsEquivIsPrincipal R x) *
        (associatesNonZeroDivisorsEquivIsPrincipal R y) := by
  simp_rw [associatesNonZeroDivisorsEquivIsPrincipal_coe, _root_.map_mul, Submonoid.coe_mul,
    associatesEquivIsPrincipal_mul]


@[simp]
theorem associatesNonZeroDivisorsEquivIsPrincipal_map_one :
    (associatesNonZeroDivisorsEquivIsPrincipal R 1 : Ideal R) = 1 := by
  rw [associatesNonZeroDivisorsEquivIsPrincipal_coe, map_one, OneMemClass.coe_one,
    associatesEquivIsPrincipal_map_one]


variable (R) in
/-- The `MulEquiv` version of `Ideal.associatesNonZeroDivisorsEquivIsPrincipal`. -/
noncomputable def associatesNonZeroDivisorsMulEquivIsPrincipal :
    Associates R⁰ ≃* (isPrincipalNonZeroDivisorsSubmonoid R) where
  __ := associatesNonZeroDivisorsEquivIsPrincipal R
  map_mul' _ _ := by
    /-
      R : Type u_1
      inst✝¹ : CommRing R
      inst✝ : IsDomain R
      x✝¹ x✝ : Associates (Subtype fun x => Membership.mem (nonZeroDivisors R) x)
      ⊢ Eq (__spread✝⁻⁰.toFun (HMul.hMul x✝¹ x✝)) (HMul.hMul (__spread✝⁻⁰.toFun x✝¹) …
    -/
    erw [Subtype.ext_iff, Subtype.ext_iff, associatesNonZeroDivisorsEquivIsPrincipal_mul]
    /-
      R : Type u_1
      inst✝¹ : CommRing R
      inst✝ : IsDomain R
      x✝¹ x✝ : Associates (Subtype fun x => Membership.mem (nonZeroDivisors R) x)
      ⊢ Eq (HMul.hMul ↑↑((Ideal.associatesNonZeroDivisorsEquivIsPrincipal R) x✝¹) ↑↑ …
    -/
    rfl
    /-
      🎉 no goals
    -/


