/-- The category of open sets contained in some element of the cover.
-/
def OpensLeCover : Type w :=
  FullSubcategory fun V : Opens X => ∃ i, V ≤ U i

-- Porting note: failed to derive `category`

instance : Category (OpensLeCover U) := FullSubcategory.category _


instance [h : Nonempty ι] : Inhabited (OpensLeCover U) :=
  ⟨⟨⊥, let ⟨i⟩ := h; ⟨i, bot_le⟩⟩⟩


/-- An arbitrarily chosen index such that `V ≤ U i`.
-/
def index (V : OpensLeCover U) : ι :=
  V.property.choose


/-- The morphism from `V` to `U i` for some `i`.
-/
def homToIndex (V : OpensLeCover U) : V.obj ⟶ U (index V) :=
  V.property.choose_spec.hom


/-- `iSup U` as a cocone over the opens sets contained in some element of the cover.

(In fact this is a colimit cocone.)
-/
def opensLeCoverCocone : Cocone (fullSubcategoryInclusion _ : OpensLeCover U ⥤ Opens X) where
  pt := iSup U
  ι := { app := fun V : OpensLeCover U => V.homToIndex ≫ Opens.leSupr U _ }


/-- An equivalent formulation of the sheaf condition
(which we prove equivalent to the usual one below as
`isSheaf_iff_isSheafOpensLeCover`).

A presheaf is a sheaf if `F` sends the cone `(opensLeCoverCocone U).op` to a limit cone.
(Recall `opensLeCoverCocone U`, has cone point `iSup U`,
mapping down to any `V` which is contained in some `U i`.)
-/
def IsSheafOpensLeCover : Prop :=
  ∀ ⦃ι : Type w⦄ (U : ι → Opens X), Nonempty (IsLimit (F.mapCone (opensLeCoverCocone U).op))


/-- Given a family of opens `U` and an open `Y` equal to the union of opens in `U`, we may
    take the presieve on `Y` associated to `U` and the sieve generated by it, and form the
    full subcategory (subposet) of opens contained in `Y` (`over Y`) consisting of arrows
    in the sieve. This full subcategory is equivalent to `OpensLeCover U`, the (poset)
    category of opens contained in some `U i`. -/
@[simps]
def generateEquivalenceOpensLe_functor' (hY : Y = iSup U) :
    (FullSubcategory fun f : Over Y => (Sieve.generate (presieveOfCoveringAux U Y)).arrows f.hom) ⥤
    OpensLeCover U :=
{ obj := fun f =>
    ⟨f.1.left,
      let ⟨_, h, _, ⟨i, hY⟩, _⟩ := f.2
      ⟨i, hY ▸ h.le⟩⟩
  map := fun {_ _} g => g.left }

-- Porting note: split it out to prevent timeout

/-- Given a family of opens `U` and an open `Y` equal to the union of opens in `U`, we may
    take the presieve on `Y` associated to `U` and the sieve generated by it, and form the
    full subcategory (subposet) of opens contained in `Y` (`over Y`) consisting of arrows
    in the sieve. This full subcategory is equivalent to `OpensLeCover U`, the (poset)
    category of opens contained in some `U i`. -/
@[simps]
def generateEquivalenceOpensLe_inverse' (hY : Y = iSup U) :
    OpensLeCover U ⥤
    (FullSubcategory fun f : Over Y =>
      (Sieve.generate (presieveOfCoveringAux U Y)).arrows f.hom) where
  obj := fun V => ⟨⟨V.obj, ⟨⟨⟩⟩, homOfLE <| hY ▸ (V.2.choose_spec.trans (le_iSup U (V.2.choose)))⟩,
    ⟨U V.2.choose, V.2.choose_spec.hom, homOfLE <| hY ▸ le_iSup U V.2.choose,
      ⟨V.2.choose, rfl⟩, rfl⟩⟩
                 /-
                   C : Type u
                   inst✝ : CategoryTheory.Category.{v, u} C
                   X : TopCat
                   F : TopCat.Presheaf C X
                   ι : Type w
                   U : ι → TopologicalSpace.Opens ↑X
                   Y : TopologicalSpace.Opens ↑X
                   hY : Eq Y (iSup U)
                   x✝¹ x✝ : TopCat.Presheaf.SheafCondition.OpensLeCover U
                   g : Quiver.Hom x✝¹ x✝
                   ⊢ Eq (CategoryTheory.CategoryStruct.comp g ((fun V => { obj := { left := V.obj …
                 -/
  map {_ _} g := Over.homMk g
                 /-
                   🎉 no goals
                 -/
  map_id _ := by
    /-
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      x✝ : TopCat.Presheaf.SheafCondition.OpensLeCover U
      ⊢ Eq ({ obj := fun V => { obj := { left := V.obj, right := { as := PUnit.unit  …
    -/
    refine Over.OverMorphism.ext ?_
    simp only [Functor.id_obj, Sieve.generate_apply, Functor.const_obj_obj, Over.homMk_left,
      eq_iff_true_of_subsingleton]
  map_comp {_ _ _} f g := by
    /-
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      x✝² x✝¹ x✝ : TopCat.Presheaf.SheafCondition.OpensLeCover U
      f : Quiver.Hom x✝² x✝¹
      g : Quiver.Hom x✝¹ x✝
      ⊢ Eq ({ obj := fun V => { obj := { left := V.obj, right := { as := PUnit.unit  …
    -/
    refine Over.OverMorphism.ext ?_
    simp only [Functor.id_obj, Sieve.generate_apply, Functor.const_obj_obj, Over.homMk_left,
      eq_iff_true_of_subsingleton]


/-- Given a family of opens `U` and an open `Y` equal to the union of opens in `U`, we may
    take the presieve on `Y` associated to `U` and the sieve generated by it, and form the
    full subcategory (subposet) of opens contained in `Y` (`over Y`) consisting of arrows
    in the sieve. This full subcategory is equivalent to `OpensLeCover U`, the (poset)
    category of opens contained in some `U i`. -/
@[simps]
def generateEquivalenceOpensLe (hY : Y = iSup U) :
    (FullSubcategory fun f : Over Y => (Sieve.generate (presieveOfCoveringAux U Y)).arrows f.hom) ≌
    OpensLeCover U where
  -- Porting note: split it out to prevent timeout
  functor := generateEquivalenceOpensLe_functor' _ hY
  inverse := generateEquivalenceOpensLe_inverse' _ hY
  unitIso := eqToIso <| CategoryTheory.Functor.ext
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          ⊢ ∀ (X_1 : CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.gener …
        -/
    (by rintro ⟨⟨_, _⟩, _⟩; dsimp; congr)
                                   /-
                                     🎉 no goals
                                   -/
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          ⊢ ∀ (X_1 Y_1 : CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.g …
        -/
    (by intros; refine Over.OverMorphism.ext ?_; aesop_cat)
                                                 /-
                                                   🎉 no goals
                                                 -/
  counitIso := eqToIso <| CategoryTheory.Functor.hext
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          ⊢ ∀ (X_1 : TopCat.Presheaf.SheafCondition.OpensLeCover U), Eq (((TopCat.Preshe …
        -/
                                              /-
                                                🎉 no goals
                                              -/
    (by intro; refine FullSubcategory.ext ?_; rfl) (by intros; rfl)
                                                               /-
                                                                 🎉 no goals
                                                               -/


/-- Given a family of opens `opensLeCoverCocone U` is essentially the natural cocone
    associated to the sieve generated by the presieve associated to `U` with indexing
    category changed using the above equivalence. -/
@[simps]
def whiskerIsoMapGenerateCocone (hY : Y = iSup U) :
    (F.mapCone (opensLeCoverCocone U).op).whisker (generateEquivalenceOpensLe U hY).op.functor ≅
      F.mapCone (Sieve.generate (presieveOfCoveringAux U Y)).arrows.cocone.op where
  hom :=
    { hom := F.map (eqToHom (congr_arg op hY.symm))
      w := fun j => by
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map (CategoryTheory.eqToHom ⋯)) (( …
        -/
        erw [← F.map_comp]
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (F.map (CategoryTheory.CategoryStruct.comp (CategoryTheory.eqToHom ⋯) ((C …
        -/
        dsimp
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (F.map (CategoryTheory.CategoryStruct.comp (CategoryTheory.eqToHom ⋯) (Op …
        -/
        congr 1 }
        /-
          🎉 no goals
        -/
  inv :=
    { hom := F.map (eqToHom (congr_arg op hY))
      w := fun j => by
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map (CategoryTheory.eqToHom ⋯)) (( …
        -/
        erw [← F.map_comp]
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (F.map (CategoryTheory.CategoryStruct.comp (CategoryTheory.eqToHom ⋯) ((T …
        -/
        dsimp
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          X : TopCat
          F : TopCat.Presheaf C X
          ι : Type w
          U : ι → TopologicalSpace.Opens ↑X
          Y : TopologicalSpace.Opens ↑X
          hY : Eq Y (iSup U)
          j : Opposite (CategoryTheory.FullSubcategory fun f => (CategoryTheory.Sieve.ge …
          ⊢ Eq (F.map (CategoryTheory.CategoryStruct.comp (CategoryTheory.eqToHom ⋯) ((T …
        -/
        congr 1 }
        /-
          🎉 no goals
        -/
  hom_inv_id := by
    /-
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      ⊢ Eq (CategoryTheory.CategoryStruct.comp { hom := F.map (CategoryTheory.eqToHo …
    -/
    ext
    /-
      case w
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      ⊢ Eq (CategoryTheory.CategoryStruct.comp { hom := F.map (CategoryTheory.eqToHo …
    -/
    simp [eqToHom_map]
    /-
      🎉 no goals
    -/
  inv_hom_id := by
    /-
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      ⊢ Eq (CategoryTheory.CategoryStruct.comp { hom := F.map (CategoryTheory.eqToHo …
    -/
    ext
    /-
      case w
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      Y : TopologicalSpace.Opens ↑X
      hY : Eq Y (iSup U)
      ⊢ Eq (CategoryTheory.CategoryStruct.comp { hom := F.map (CategoryTheory.eqToHo …
    -/
    simp [eqToHom_map]
    /-
      🎉 no goals
    -/


/-- Given a presheaf `F` on the topological space `X` and a family of opens `U` of `X`,
    the natural cone associated to `F` and `U` used in the definition of
    `F.IsSheafOpensLeCover` is a limit cone iff the natural cone associated to `F`
    and the sieve generated by the presieve associated to `U` is a limit cone. -/
def isLimitOpensLeEquivGenerate₁ (hY : Y = iSup U) :
    IsLimit (F.mapCone (opensLeCoverCocone U).op) ≃
      IsLimit (F.mapCone (Sieve.generate (presieveOfCoveringAux U Y)).arrows.cocone.op) :=
  (IsLimit.whiskerEquivalenceEquiv (generateEquivalenceOpensLe U hY).op).trans
    (IsLimit.equivIsoLimit (whiskerIsoMapGenerateCocone F U hY))


/-- Given a presheaf `F` on the topological space `X` and a presieve `R` whose generated sieve
    is covering for the associated Grothendieck topology (equivalently, the presieve is covering
    for the associated pretopology), the natural cone associated to `F` and the family of opens
    associated to `R` is a limit cone iff the natural cone associated to `F` and the generated
    sieve is a limit cone.
    Since only the existence of a 1-1 correspondence will be used, the exact definition does
    not matter, so tactics are used liberally. -/
def isLimitOpensLeEquivGenerate₂ (R : Presieve Y)
    (hR : Sieve.generate R ∈ Opens.grothendieckTopology X Y) :
    IsLimit (F.mapCone (opensLeCoverCocone (coveringOfPresieve Y R)).op) ≃
      IsLimit (F.mapCone (Sieve.generate R).arrows.cocone.op) := by
  convert isLimitOpensLeEquivGenerate₁ F (coveringOfPresieve Y R)
      (coveringOfPresieve.iSup_eq_of_mem_grothendieck Y R hR).symm using 1
  /-
    case h.e'_2
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : TopCat
    F : TopCat.Presheaf C X
    ι : Type w
    U : ι → TopologicalSpace.Opens ↑X
    Y : TopologicalSpace.Opens ↑X
    R : CategoryTheory.Presieve Y
    hR : Membership.mem ((Opens.grothendieckTopology ↑X) Y) (CategoryTheory.Sieve. …
    ⊢ Eq (CategoryTheory.Limits.IsLimit (CategoryTheory.Functor.mapCone F (Categor …
  -/
  rw [covering_presieve_eq_self R]
  /-
    🎉 no goals
  -/


/-- A presheaf `(opens X)ᵒᵖ ⥤ C` on a topological space `X` is a sheaf on the site `opens X` iff
    it satisfies the `IsSheafOpensLeCover` sheaf condition. The latter is not the
    official definition of sheaves on spaces, but has the advantage that it does not
    require `has_products C`. -/
theorem isSheaf_iff_isSheafOpensLeCover : F.IsSheaf ↔ F.IsSheafOpensLeCover := by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : TopCat
    F : TopCat.Presheaf C X
    ⊢ Iff F.IsSheaf F.IsSheafOpensLeCover
  -/
  refine (Presheaf.isSheaf_iff_isLimit _ _).trans ?_
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : TopCat
    F : TopCat.Presheaf C X
    ⊢ Iff (∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryTheory.Sieve X_1), Mem …
  -/
  constructor
    /-
      case mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ⊢ (∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryTheory.Sieve X_1), Members …
    -/
  · intro h ι U
    /-
      case mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : ∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryTheory.Sieve X_1), Member …
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      ⊢ Nonempty (CategoryTheory.Limits.IsLimit (CategoryTheory.Functor.mapCone F (T …
    -/
    rw [(isLimitOpensLeEquivGenerate₁ F U rfl).nonempty_congr]
    /-
      case mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : ∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryTheory.Sieve X_1), Member …
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      ⊢ Nonempty (CategoryTheory.Limits.IsLimit (CategoryTheory.Functor.mapCone F (C …
    -/
    apply h
    /-
      case mp.a
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : ∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryTheory.Sieve X_1), Member …
      ι : Type w
      U : ι → TopologicalSpace.Opens ↑X
      ⊢ Membership.mem ((Opens.grothendieckTopology ↑X) (iSup U)) (CategoryTheory.Si …
    -/
    apply presieveOfCovering.mem_grothendieckTopology
    /-
      🎉 no goals
    -/
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      ⊢ F.IsSheafOpensLeCover → ∀ ⦃X_1 : TopologicalSpace.Opens ↑X⦄ (S : CategoryThe …
    -/
  · intro h Y S
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : F.IsSheafOpensLeCover
      Y : TopologicalSpace.Opens ↑X
      S : CategoryTheory.Sieve Y
      ⊢ Membership.mem ((Opens.grothendieckTopology ↑X) Y) S → Nonempty (CategoryThe …
    -/
    rw [← Sieve.generate_sieve S]
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : F.IsSheafOpensLeCover
      Y : TopologicalSpace.Opens ↑X
      S : CategoryTheory.Sieve Y
      ⊢ Membership.mem ((Opens.grothendieckTopology ↑X) Y) (CategoryTheory.Sieve.gen …
    -/
    intro hS
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : F.IsSheafOpensLeCover
      Y : TopologicalSpace.Opens ↑X
      S : CategoryTheory.Sieve Y
      hS : Membership.mem ((Opens.grothendieckTopology ↑X) Y) (CategoryTheory.Sieve. …
      ⊢ Nonempty (CategoryTheory.Limits.IsLimit (CategoryTheory.Functor.mapCone F (C …
    -/
    rw [← (isLimitOpensLeEquivGenerate₂ F S.1 hS).nonempty_congr]
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : TopCat
      F : TopCat.Presheaf C X
      h : F.IsSheafOpensLeCover
      Y : TopologicalSpace.Opens ↑X
      S : CategoryTheory.Sieve Y
      hS : Membership.mem ((Opens.grothendieckTopology ↑X) Y) (CategoryTheory.Sieve. …
      ⊢ Nonempty (CategoryTheory.Limits.IsLimit (CategoryTheory.Functor.mapCone F (T …
    -/
    apply h
    /-
      🎉 no goals
    -/


