/-- A presheaf is separated for a topology if it is separated for every sieve in the topology. -/
def IsSeparated (P : Cᵒᵖ ⥤ Type w) : Prop :=
  ∀ {X} (S : Sieve X), S ∈ J X → IsSeparatedFor P (S : Presieve X)


/-- A presheaf is a sheaf for a topology if it is a sheaf for every sieve in the topology.

If the given topology is given by a pretopology, `isSheaf_pretopology` shows it suffices to
check the sheaf condition at presieves in the pretopology.
-/
def IsSheaf (P : Cᵒᵖ ⥤ Type w) : Prop :=
  ∀ ⦃X⦄ (S : Sieve X), S ∈ J X → IsSheafFor P (S : Presieve X)


theorem IsSheaf.isSheafFor {P : Cᵒᵖ ⥤ Type w} (hp : IsSheaf J P) (R : Presieve X)
    (hr : generate R ∈ J X) : IsSheafFor P R :=
  (isSheafFor_iff_generate R).2 <| hp _ hr


theorem isSheaf_of_le (P : Cᵒᵖ ⥤ Type w) {J₁ J₂ : GrothendieckTopology C} :
    J₁ ≤ J₂ → IsSheaf J₂ P → IsSheaf J₁ P := fun h t _ S hS => t S (h _ hS)


theorem isSeparated_of_isSheaf (P : Cᵒᵖ ⥤ Type w) (h : IsSheaf J P) : IsSeparated J P :=
  fun S hS => (h S hS).isSeparatedFor


include he in
lemma isSheaf_of_nat_equiv (hP₁ : Presieve.IsSheaf J P₁) :
    Presieve.IsSheaf J P₂ := fun _ R hR ↦
  isSheafFor_of_nat_equiv e he (hP₁ R hR)


include he in
lemma isSheaf_iff_of_nat_equiv :
    Presieve.IsSheaf J P₁ ↔ Presieve.IsSheaf J P₂ :=
  ⟨fun hP₁ ↦ isSheaf_of_nat_equiv e he hP₁,
    fun hP₂ ↦
      isSheaf_of_nat_equiv (fun _ ↦ (@e _).symm) (fun X Y f x ↦ by
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          J : CategoryTheory.GrothendieckTopology C
          P₁ : CategoryTheory.Functor (Opposite C) (Type w)
          P₂ : CategoryTheory.Functor (Opposite C) (Type w')
          e : ⦃X : C⦄ → Equiv (P₁.obj { unop := X }) (P₂.obj { unop := X })
          he : ∀ ⦃X Y : C⦄ (f : Quiver.Hom X Y) (x : P₁.obj { unop := Y }), Eq (e (P₁.ma …
          hP₂ : CategoryTheory.Presieve.IsSheaf J P₂
          X Y : C
          f : Quiver.Hom X Y
          x : P₂.obj { unop := Y }
          ⊢ Eq (((fun x => e.symm) X) (P₂.map f.op x)) (P₁.map f.op (((fun x => e.symm)  …
        -/
        obtain ⟨y, rfl⟩ := e.surjective x
        /-
          case intro
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          J : CategoryTheory.GrothendieckTopology C
          P₁ : CategoryTheory.Functor (Opposite C) (Type w)
          P₂ : CategoryTheory.Functor (Opposite C) (Type w')
          e : ⦃X : C⦄ → Equiv (P₁.obj { unop := X }) (P₂.obj { unop := X })
          he : ∀ ⦃X Y : C⦄ (f : Quiver.Hom X Y) (x : P₁.obj { unop := Y }), Eq (e (P₁.ma …
          hP₂ : CategoryTheory.Presieve.IsSheaf J P₂
          X Y : C
          f : Quiver.Hom X Y
          y : P₁.obj { unop := Y }
          ⊢ Eq (((fun x => e.symm) X) (P₂.map f.op (e y))) (P₁.map f.op (((fun x => e.sy …
        -/
        refine e.injective ?_
        /-
          case intro
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          J : CategoryTheory.GrothendieckTopology C
          P₁ : CategoryTheory.Functor (Opposite C) (Type w)
          P₂ : CategoryTheory.Functor (Opposite C) (Type w')
          e : ⦃X : C⦄ → Equiv (P₁.obj { unop := X }) (P₂.obj { unop := X })
          he : ∀ ⦃X Y : C⦄ (f : Quiver.Hom X Y) (x : P₁.obj { unop := Y }), Eq (e (P₁.ma …
          hP₂ : CategoryTheory.Presieve.IsSheaf J P₂
          X Y : C
          f : Quiver.Hom X Y
          y : P₁.obj { unop := Y }
          ⊢ Eq (e (((fun x => e.symm) X) (P₂.map f.op (e y)))) (e (P₁.map f.op (((fun x  …
        -/
        simp only [Equiv.apply_symm_apply, Equiv.symm_apply_apply, he]) hP₂⟩
        /-
          🎉 no goals
        -/


/-- The property of being a sheaf is preserved by isomorphism. -/
theorem isSheaf_iso {P' : Cᵒᵖ ⥤ Type w} (i : P ≅ P') (h : IsSheaf J P) : IsSheaf J P' :=
  fun _ S hS => isSheafFor_iso i (h S hS)


theorem isSheaf_of_yoneda {P : Cᵒᵖ ⥤ Type v}
    (h : ∀ {X} (S : Sieve X), S ∈ J X → YonedaSheafCondition P S) : IsSheaf J P := fun _ _ hS =>
  isSheafFor_iff_yonedaSheafCondition.2 (h _ hS)


/-- For a topology generated by a basis, it suffices to check the sheaf condition on the basis
presieves only.
-/
theorem isSheaf_pretopology [HasPullbacks C] (K : Pretopology C) :
    IsSheaf (K.toGrothendieck C) P ↔ ∀ {X : C} (R : Presieve X), R ∈ K X → IsSheafFor P R := by
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    P : CategoryTheory.Functor (Opposite C) (Type w)
    inst✝ : CategoryTheory.Limits.HasPullbacks C
    K : CategoryTheory.Pretopology C
    ⊢ Iff (CategoryTheory.Presieve.IsSheaf (CategoryTheory.Pretopology.toGrothendi …
  -/
  constructor
    /-
      case mp
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      ⊢ CategoryTheory.Presieve.IsSheaf (CategoryTheory.Pretopology.toGrothendieck C …
    -/
  · intro PJ X R hR
    /-
      case mp
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PJ : CategoryTheory.Presieve.IsSheaf (CategoryTheory.Pretopology.toGrothendiec …
      X : C
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      ⊢ CategoryTheory.Presieve.IsSheafFor P R
    -/
    rw [isSheafFor_iff_generate]
    /-
      case mp
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PJ : CategoryTheory.Presieve.IsSheaf (CategoryTheory.Pretopology.toGrothendiec …
      X : C
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      ⊢ CategoryTheory.Presieve.IsSheafFor P (CategoryTheory.Sieve.generate R).arrows
    -/
    apply PJ (Sieve.generate R) ⟨_, hR, le_generate R⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      ⊢ (∀ {X : C} (R : CategoryTheory.Presieve X), Membership.mem (K.coverings X) R …
    -/
  · rintro PK X S ⟨R, hR, RS⟩
    have gRS : ⇑(generate R) ≤ S := by
      apply giGenerate.gc.monotone_u
      rwa [generate_le_iff]
    /-
      case mpr.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PK : ∀ {X : C} (R : CategoryTheory.Presieve X), Membership.mem (K.coverings X) …
      X : C
      S : CategoryTheory.Sieve X
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      RS : LE.le R S.arrows
      gRS : LE.le (CategoryTheory.Sieve.generate R).arrows S.arrows
      ⊢ CategoryTheory.Presieve.IsSheafFor P S.arrows
    -/
    apply isSheafFor_subsieve P gRS _
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PK : ∀ {X : C} (R : CategoryTheory.Presieve X), Membership.mem (K.coverings X) …
      X : C
      S : CategoryTheory.Sieve X
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      RS : LE.le R S.arrows
      gRS : LE.le (CategoryTheory.Sieve.generate R).arrows S.arrows
      ⊢ ∀ ⦃Y : C⦄ (f : Quiver.Hom Y X), CategoryTheory.Presieve.IsSheafFor P (Catego …
    -/
    intro Y f
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PK : ∀ {X : C} (R : CategoryTheory.Presieve X), Membership.mem (K.coverings X) …
      X : C
      S : CategoryTheory.Sieve X
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      RS : LE.le R S.arrows
      gRS : LE.le (CategoryTheory.Sieve.generate R).arrows S.arrows
      Y : C
      f : Quiver.Hom Y X
      ⊢ CategoryTheory.Presieve.IsSheafFor P (CategoryTheory.Sieve.pullback f (Categ …
    -/
    rw [← pullbackArrows_comm, ← isSheafFor_iff_generate]
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      P : CategoryTheory.Functor (Opposite C) (Type w)
      inst✝ : CategoryTheory.Limits.HasPullbacks C
      K : CategoryTheory.Pretopology C
      PK : ∀ {X : C} (R : CategoryTheory.Presieve X), Membership.mem (K.coverings X) …
      X : C
      S : CategoryTheory.Sieve X
      R : CategoryTheory.Presieve X
      hR : Membership.mem (K.coverings X) R
      RS : LE.le R S.arrows
      gRS : LE.le (CategoryTheory.Sieve.generate R).arrows S.arrows
      Y : C
      f : Quiver.Hom Y X
      ⊢ CategoryTheory.Presieve.IsSheafFor P (CategoryTheory.Presieve.pullbackArrows …
    -/
    exact PK (pullbackArrows f R) (K.pullbacks f R hR)
    /-
      🎉 no goals
    -/


/-- Any presheaf is a sheaf for the bottom (trivial) grothendieck topology. -/
theorem isSheaf_bot : IsSheaf (⊥ : GrothendieckTopology C) P := fun X => by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    P : CategoryTheory.Functor (Opposite C) (Type w)
    X : C
    ⊢ ∀ (S : CategoryTheory.Sieve X), Membership.mem (Bot.bot X) S → CategoryTheor …
  -/
  simp [isSheafFor_top_sieve]
  /-
    🎉 no goals
  -/


/--
For a presheaf of the form `yoneda.obj W`, a compatible family of elements on a sieve
is the same as a co-cone over the sieve. Constructing a co-cone from a compatible family works for
any presieve, as does constructing a family of elements from a co-cone. Showing compatibility of the
family needs the sieve condition.
Note: This is related to `CategoryTheory.Presheaf.conesEquivSieveCompatibleFamily`
 -/

def compatibleYonedaFamily_toCocone (R : Presieve X) (W : C) (x : FamilyOfElements (yoneda.obj W) R)
    (hx : FamilyOfElements.Compatible x) :
    Cocone (R.diagram) where
  pt := W
  ι :=
    { app := fun f => x f.obj.hom f.property
      naturality := by
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          P : CategoryTheory.Functor (Opposite C) (Type w)
          X : C
          J J₂ : CategoryTheory.GrothendieckTopology C
          R : CategoryTheory.Presieve X
          W : C
          x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) R
          hx : x.Compatible
          ⊢ ∀ ⦃X_1 Y : R.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory.CategorySt …
        -/
        intro g₁ g₂ F
        simp only [Functor.id_obj, Functor.comp_obj, fullSubcategoryInclusion.obj, Over.forget_obj,
          Functor.const_obj_obj, Functor.comp_map, fullSubcategoryInclusion.map, Over.forget_map,
          Functor.const_obj_map, Category.comp_id]
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          P : CategoryTheory.Functor (Opposite C) (Type w)
          X : C
          J J₂ : CategoryTheory.GrothendieckTopology C
          R : CategoryTheory.Presieve X
          W : C
          x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) R
          hx : x.Compatible
          g₁ g₂ : R.category
          F : Quiver.Hom g₁ g₂
          ⊢ Eq (CategoryTheory.CategoryStruct.comp F.left (x g₂.obj.hom ⋯)) (x g₁.obj.ho …
        -/
        rw [← Category.id_comp (x g₁.obj.hom g₁.property)]
        /-
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          P : CategoryTheory.Functor (Opposite C) (Type w)
          X : C
          J J₂ : CategoryTheory.GrothendieckTopology C
          R : CategoryTheory.Presieve X
          W : C
          x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) R
          hx : x.Compatible
          g₁ g₂ : R.category
          F : Quiver.Hom g₁ g₂
          ⊢ Eq (CategoryTheory.CategoryStruct.comp F.left (x g₂.obj.hom ⋯)) (CategoryThe …
        -/
        apply hx
        /-
          case a
          C : Type u
          inst✝ : CategoryTheory.Category.{v, u} C
          P : CategoryTheory.Functor (Opposite C) (Type w)
          X : C
          J J₂ : CategoryTheory.GrothendieckTopology C
          R : CategoryTheory.Presieve X
          W : C
          x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) R
          hx : x.Compatible
          g₁ g₂ : R.category
          F : Quiver.Hom g₁ g₂
          ⊢ Eq (CategoryTheory.CategoryStruct.comp F.1 g₂.obj.hom) (CategoryTheory.Categ …
        -/
        simp only [Functor.id_obj, Over.w, Opposite.unop_op, Category.id_comp] }
        /-
          🎉 no goals
        -/


def yonedaFamilyOfElements_fromCocone (R : Presieve X) (s : Cocone (diagram R)) :
    FamilyOfElements (yoneda.obj s.pt) R :=
  fun _ f hf => s.ι.app ⟨Over.mk f, hf⟩


theorem yonedaFamily_fromCocone_compatible (S : Sieve X) (s : Cocone (diagram S.arrows)) :
    FamilyOfElements.Compatible <| yonedaFamilyOfElements_fromCocone S.arrows s := by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    ⊢ (S.arrows.yonedaFamilyOfElements_fromCocone s).Compatible
  -/
  intro Y₁ Y₂ Z g₁ g₂ f₁ f₂ hf₁ hf₂ hgf
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    ⊢ Eq ((CategoryTheory.yoneda.obj s.pt).map g₁.op (S.arrows.yonedaFamilyOfEleme …
  -/
  have Hs := s.ι.naturality
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    ⊢ Eq ((CategoryTheory.yoneda.obj s.pt).map g₁.op (S.arrows.yonedaFamilyOfEleme …
  -/
  simp only [Functor.id_obj, yoneda_obj_obj, Opposite.unop_op, yoneda_obj_map, Quiver.Hom.unop_op]
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (S.arrows.yonedaFamilyOfElements_f …
  -/
  dsimp [yonedaFamilyOfElements_fromCocone]
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  have hgf₁ : S.arrows (g₁ ≫ f₁) := by exact Sieve.downward_closed S hf₁ g₁
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  have hgf₂ : S.arrows (g₂ ≫ f₂) := by exact Sieve.downward_closed S hf₂ g₂
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  let F : (Over.mk (g₁ ≫ f₁) : Over X) ⟶ (Over.mk (g₂ ≫ f₂) : Over X) := Over.homMk (𝟙 Z)
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  let F₁ : (Over.mk (g₁ ≫ f₁) : Over X) ⟶ (Over.mk f₁ : Over X) := Over.homMk g₁
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    F₁ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁ …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  let F₂ : (Over.mk (g₂ ≫ f₂) : Over X) ⟶ (Over.mk f₂ : Over X) := Over.homMk g₂
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    F₁ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁ …
    F₂ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₂ …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  have hF := @Hs ⟨Over.mk (g₁ ≫ f₁), hgf₁⟩ ⟨Over.mk (g₂ ≫ f₂), hgf₂⟩ F
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    F₁ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁ …
    F₂ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₂ …
    hF : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F) (s.ι.app  …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  have hF₁ := @Hs ⟨Over.mk (g₁ ≫ f₁), hgf₁⟩ ⟨Over.mk f₁, hf₁⟩ F₁
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    F₁ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁ …
    F₂ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₂ …
    hF : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F) (s.ι.app  …
    hF₁ : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F₁) (s.ι.ap …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  have hF₂ := @Hs ⟨Over.mk (g₂ ≫ f₂), hgf₂⟩ ⟨Over.mk f₂, hf₂⟩ F₂
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    s : CategoryTheory.Limits.Cocone S.arrows.diagram
    Y₁ Y₂ Z : C
    g₁ : Quiver.Hom Z Y₁
    g₂ : Quiver.Hom Z Y₂
    f₁ : Quiver.Hom Y₁ X
    f₂ : Quiver.Hom Y₂ X
    hf₁ : S.arrows f₁
    hf₂ : S.arrows f₂
    hgf : Eq (CategoryTheory.CategoryStruct.comp g₁ f₁) (CategoryTheory.CategorySt …
    Hs : ∀ ⦃X_1 Y : S.arrows.category⦄ (f : Quiver.Hom X_1 Y), Eq (CategoryTheory. …
    hgf₁ : S.arrows (CategoryTheory.CategoryStruct.comp g₁ f₁)
    hgf₂ : S.arrows (CategoryTheory.CategoryStruct.comp g₂ f₂)
    F : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁  …
    F₁ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₁ …
    F₂ : Quiver.Hom (CategoryTheory.Over.mk (CategoryTheory.CategoryStruct.comp g₂ …
    hF : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F) (s.ι.app  …
    hF₁ : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F₁) (s.ι.ap …
    hF₂ : Eq (CategoryTheory.CategoryStruct.comp (S.arrows.diagram.map F₂) (s.ι.ap …
    ⊢ Eq (CategoryTheory.CategoryStruct.comp g₁ (s.ι.app { obj := CategoryTheory.O …
  -/
  aesop_cat
  /-
    🎉 no goals
  -/


/--
The base of a sieve `S` is a colimit of `S` iff all Yoneda-presheaves satisfy
the sheaf condition for `S`.
-/
theorem forallYonedaIsSheaf_iff_colimit (S : Sieve X) :
    (∀ W : C, Presieve.IsSheafFor (yoneda.obj W) (S : Presieve X)) ↔
      Nonempty (IsColimit S.arrows.cocone) := by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    X : C
    S : CategoryTheory.Sieve X
    ⊢ Iff (∀ (W : C), CategoryTheory.Presieve.IsSheafFor (CategoryTheory.yoneda.ob …
  -/
  constructor
    /-
      case mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      ⊢ (∀ (W : C), CategoryTheory.Presieve.IsSheafFor (CategoryTheory.yoneda.obj W) …
    -/
  · intro H
    /-
      case mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      H : ∀ (W : C), CategoryTheory.Presieve.IsSheafFor (CategoryTheory.yoneda.obj W …
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit S.arrows.cocone)
    -/
    refine Nonempty.intro ?_
    exact
    { desc := fun s => H s.pt (yonedaFamilyOfElements_fromCocone S.arrows s)
        (yonedaFamily_fromCocone_compatible S s) |>.choose
      fac := by
        intro s f
        replace H := H s.pt (yonedaFamilyOfElements_fromCocone S.arrows s)
          (yonedaFamily_fromCocone_compatible S s)
        have ht := H.choose_spec.1 f.obj.hom f.property
        aesop_cat
      uniq := by
        intro s Fs HFs
        replace H := H s.pt (yonedaFamilyOfElements_fromCocone S.arrows s)
          (yonedaFamily_fromCocone_compatible S s)
        apply H.choose_spec.2 Fs
        exact fun _ f hf => HFs ⟨Over.mk f, hf⟩ }
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      ⊢ Nonempty (CategoryTheory.Limits.IsColimit S.arrows.cocone) → ∀ (W : C), Cate …
    -/
  · intro H W x hx
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      H : Nonempty (CategoryTheory.Limits.IsColimit S.arrows.cocone)
      W : C
      x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
      hx : x.Compatible
      ⊢ ExistsUnique fun t => x.IsAmalgamation t
    -/
    replace H := Classical.choice H
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      W : C
      x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
      hx : x.Compatible
      H : CategoryTheory.Limits.IsColimit S.arrows.cocone
      ⊢ ExistsUnique fun t => x.IsAmalgamation t
    -/
    let s := compatibleYonedaFamily_toCocone S.arrows W x hx
    /-
      case mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      W : C
      x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
      hx : x.Compatible
      H : CategoryTheory.Limits.IsColimit S.arrows.cocone
      s : CategoryTheory.Limits.Cocone S.arrows.diagram := S.arrows.compatibleYoneda …
      ⊢ ExistsUnique fun t => x.IsAmalgamation t
    -/
    use H.desc s
    /-
      case h
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      X : C
      S : CategoryTheory.Sieve X
      W : C
      x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
      hx : x.Compatible
      H : CategoryTheory.Limits.IsColimit S.arrows.cocone
      s : CategoryTheory.Limits.Cocone S.arrows.diagram := S.arrows.compatibleYoneda …
      ⊢ And ((fun t => x.IsAmalgamation t) (H.desc s)) (∀ (y : (CategoryTheory.yoned …
    -/
    constructor
      /-
        case h.left
        C : Type u
        inst✝ : CategoryTheory.Category.{v, u} C
        X : C
        S : CategoryTheory.Sieve X
        W : C
        x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
        hx : x.Compatible
        H : CategoryTheory.Limits.IsColimit S.arrows.cocone
        s : CategoryTheory.Limits.Cocone S.arrows.diagram := S.arrows.compatibleYoneda …
        ⊢ (fun t => x.IsAmalgamation t) (H.desc s)
      -/
    · exact fun _ f hf => (H.fac s) ⟨Over.mk f, hf⟩
      /-
        🎉 no goals
      -/
      /-
        case h.right
        C : Type u
        inst✝ : CategoryTheory.Category.{v, u} C
        X : C
        S : CategoryTheory.Sieve X
        W : C
        x : CategoryTheory.Presieve.FamilyOfElements (CategoryTheory.yoneda.obj W) S.a …
        hx : x.Compatible
        H : CategoryTheory.Limits.IsColimit S.arrows.cocone
        s : CategoryTheory.Limits.Cocone S.arrows.diagram := S.arrows.compatibleYoneda …
        ⊢ ∀ (y : (CategoryTheory.yoneda.obj W).obj { unop := X }), (fun t => x.IsAmalg …
      -/
    · exact fun g hg => H.uniq s g (fun ⟨⟨f, _, hom⟩, hf⟩ => hg hom hf)
      /-
        🎉 no goals
      -/


