/-- The cohomology of an abelian sheaf in degree `n`. -/
def H (n : ℕ) : Type w' :=
  Ext ((constantSheaf J AddCommGrp.{w}).obj (AddCommGrp.of (ULift ℤ))) F n


noncomputable instance (n : ℕ) : AddCommGroup (F.H n) := by
  /-
    C : Type u
    inst✝² : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    F : CategoryTheory.Sheaf J AddCommGrp
    inst✝¹ : CategoryTheory.HasSheafify J AddCommGrp
    inst✝ : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrp)
    n : Nat
    ⊢ AddCommGroup (F.H n)
  -/
  dsimp only [H]
  /-
    C : Type u
    inst✝² : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    F : CategoryTheory.Sheaf J AddCommGrp
    inst✝¹ : CategoryTheory.HasSheafify J AddCommGrp
    inst✝ : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrp)
    n : Nat
    ⊢ AddCommGroup (CategoryTheory.Abelian.Ext ((CategoryTheory.constantSheaf J Ad …
  -/
  infer_instance
  /-
    🎉 no goals
  -/


variable (J) in
/-- The bifunctor which sends an abelian sheaf `F` and an object `U` to the
`n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`. -/
noncomputable def cohomologyPresheafFunctor (n : ℕ) :
    Sheaf J AddCommGrp.{v} ⥤ Cᵒᵖ ⥤ AddCommGrp.{w'} :=
  Functor.flip
    (Functor.op (yoneda ⋙ (whiskeringRight _ _ _).obj
      AddCommGrp.free ⋙ presheafToSheaf _ _) ⋙ extFunctor n)


/-- Given an abelian sheaf `F`, this is the presheaf which sends `U`
to the `n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`. -/
noncomputable abbrev cohomologyPresheaf (F : Sheaf J AddCommGrp.{v}) (n : ℕ) :
    Cᵒᵖ ⥤ AddCommGrp.{w'} :=
  (cohomologyPresheafFunctor J n).obj F


