/-- `A.IsDiag` means square matrix `A` is a diagonal matrix. -/
def IsDiag [Zero α] (A : Matrix n n α) : Prop :=
  Pairwise fun i j => A i j = 0


@[simp]
theorem isDiag_diagonal [Zero α] [DecidableEq n] (d : n → α) : (diagonal d).IsDiag := fun _ _ =>
  Matrix.diagonal_apply_ne _


/-- Diagonal matrices are generated by the `Matrix.diagonal` of their `Matrix.diag`. -/
theorem IsDiag.diagonal_diag [Zero α] [DecidableEq n] {A : Matrix n n α} (h : A.IsDiag) :
    diagonal (diag A) = A :=
  ext fun i j => by
    /-
      α : Type u_1
      n : Type u_4
      inst✝¹ : Zero α
      inst✝ : DecidableEq n
      A : Matrix n n α
      h : A.IsDiag
      i j : n
      ⊢ Eq (Matrix.diagonal A.diag i j) (A i j)
    -/
    obtain rfl | hij := Decidable.eq_or_ne i j
      /-
        case inl
        α : Type u_1
        n : Type u_4
        inst✝¹ : Zero α
        inst✝ : DecidableEq n
        A : Matrix n n α
        h : A.IsDiag
        i : n
        ⊢ Eq (Matrix.diagonal A.diag i i) (A i i)
      -/
    · rw [diagonal_apply_eq, diag]
      /-
        🎉 no goals
      -/
      /-
        case inr
        α : Type u_1
        n : Type u_4
        inst✝¹ : Zero α
        inst✝ : DecidableEq n
        A : Matrix n n α
        h : A.IsDiag
        i j : n
        hij : Ne i j
        ⊢ Eq (Matrix.diagonal A.diag i j) (A i j)
      -/
    · rw [diagonal_apply_ne _ hij, h hij]
      /-
        🎉 no goals
      -/


/-- `Matrix.IsDiag.diagonal_diag` as an iff. -/
theorem isDiag_iff_diagonal_diag [Zero α] [DecidableEq n] (A : Matrix n n α) :
    A.IsDiag ↔ diagonal (diag A) = A :=
  ⟨IsDiag.diagonal_diag, fun hd => hd ▸ isDiag_diagonal (diag A)⟩


/-- Every matrix indexed by a subsingleton is diagonal. -/
theorem isDiag_of_subsingleton [Zero α] [Subsingleton n] (A : Matrix n n α) : A.IsDiag :=
  fun i j h => (h <| Subsingleton.elim i j).elim


/-- Every zero matrix is diagonal. -/
@[simp]
theorem isDiag_zero [Zero α] : (0 : Matrix n n α).IsDiag := fun _ _ _ => rfl


/-- Every identity matrix is diagonal. -/
@[simp]
theorem isDiag_one [DecidableEq n] [Zero α] [One α] : (1 : Matrix n n α).IsDiag := fun _ _ =>
  one_apply_ne


theorem IsDiag.map [Zero α] [Zero β] {A : Matrix n n α} (ha : A.IsDiag) {f : α → β} (hf : f 0 = 0) :
    (A.map f).IsDiag := by
  /-
    α : Type u_1
    β : Type u_2
    n : Type u_4
    inst✝¹ : Zero α
    inst✝ : Zero β
    A : Matrix n n α
    ha : A.IsDiag
    f : α → β
    hf : Eq (f 0) 0
    ⊢ (A.map f).IsDiag
  -/
  intro i j h
  /-
    α : Type u_1
    β : Type u_2
    n : Type u_4
    inst✝¹ : Zero α
    inst✝ : Zero β
    A : Matrix n n α
    ha : A.IsDiag
    f : α → β
    hf : Eq (f 0) 0
    i j : n
    h : Ne i j
    ⊢ Eq (A.map f i j) 0
  -/
  simp [ha h, hf]
  /-
    🎉 no goals
  -/


theorem IsDiag.neg [AddGroup α] {A : Matrix n n α} (ha : A.IsDiag) : (-A).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddGroup α
    A : Matrix n n α
    ha : A.IsDiag
    ⊢ (Neg.neg A).IsDiag
  -/
  intro i j h
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddGroup α
    A : Matrix n n α
    ha : A.IsDiag
    i j : n
    h : Ne i j
    ⊢ Eq (Neg.neg A i j) 0
  -/
  simp [ha h]
  /-
    🎉 no goals
  -/


@[simp]
theorem isDiag_neg_iff [AddGroup α] {A : Matrix n n α} : (-A).IsDiag ↔ A.IsDiag :=
  ⟨fun ha _ _ h => neg_eq_zero.1 (ha h), IsDiag.neg⟩


theorem IsDiag.add [AddZeroClass α] {A B : Matrix n n α} (ha : A.IsDiag) (hb : B.IsDiag) :
    (A + B).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddZeroClass α
    A B : Matrix n n α
    ha : A.IsDiag
    hb : B.IsDiag
    ⊢ (HAdd.hAdd A B).IsDiag
  -/
  intro i j h
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddZeroClass α
    A B : Matrix n n α
    ha : A.IsDiag
    hb : B.IsDiag
    i j : n
    h : Ne i j
    ⊢ Eq (HAdd.hAdd A B i j) 0
  -/
  simp [ha h, hb h]
  /-
    🎉 no goals
  -/


theorem IsDiag.sub [AddGroup α] {A B : Matrix n n α} (ha : A.IsDiag) (hb : B.IsDiag) :
    (A - B).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddGroup α
    A B : Matrix n n α
    ha : A.IsDiag
    hb : B.IsDiag
    ⊢ (HSub.hSub A B).IsDiag
  -/
  intro i j h
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : AddGroup α
    A B : Matrix n n α
    ha : A.IsDiag
    hb : B.IsDiag
    i j : n
    h : Ne i j
    ⊢ Eq (HSub.hSub A B i j) 0
  -/
  simp [ha h, hb h]
  /-
    🎉 no goals
  -/


theorem IsDiag.smul [Monoid R] [AddMonoid α] [DistribMulAction R α] (k : R) {A : Matrix n n α}
    (ha : A.IsDiag) : (k • A).IsDiag := by
  /-
    α : Type u_1
    R : Type u_3
    n : Type u_4
    inst✝² : Monoid R
    inst✝¹ : AddMonoid α
    inst✝ : DistribMulAction R α
    k : R
    A : Matrix n n α
    ha : A.IsDiag
    ⊢ (HSMul.hSMul k A).IsDiag
  -/
  intro i j h
  /-
    α : Type u_1
    R : Type u_3
    n : Type u_4
    inst✝² : Monoid R
    inst✝¹ : AddMonoid α
    inst✝ : DistribMulAction R α
    k : R
    A : Matrix n n α
    ha : A.IsDiag
    i j : n
    h : Ne i j
    ⊢ Eq (HSMul.hSMul k A i j) 0
  -/
  simp [ha h]
  /-
    🎉 no goals
  -/


@[simp]
theorem isDiag_smul_one (n) [Semiring α] [DecidableEq n] (k : α) :
    (k • (1 : Matrix n n α)).IsDiag :=
  isDiag_one.smul k


theorem IsDiag.transpose [Zero α] {A : Matrix n n α} (ha : A.IsDiag) : Aᵀ.IsDiag := fun _ _ h =>
  ha h.symm


@[simp]
theorem isDiag_transpose_iff [Zero α] {A : Matrix n n α} : Aᵀ.IsDiag ↔ A.IsDiag :=
  ⟨IsDiag.transpose, IsDiag.transpose⟩


theorem IsDiag.conjTranspose [Semiring α] [StarRing α] {A : Matrix n n α} (ha : A.IsDiag) :
    Aᴴ.IsDiag :=
  ha.transpose.map (star_zero _)


@[simp]
theorem isDiag_conjTranspose_iff [Semiring α] [StarRing α] {A : Matrix n n α} :
    Aᴴ.IsDiag ↔ A.IsDiag :=
  ⟨fun ha => by
    /-
      α : Type u_1
      n : Type u_4
      inst✝¹ : Semiring α
      inst✝ : StarRing α
      A : Matrix n n α
      ha : A.conjTranspose.IsDiag
      ⊢ A.IsDiag
    -/
    convert ha.conjTranspose
    /-
      case h.e'_4
      α : Type u_1
      n : Type u_4
      inst✝¹ : Semiring α
      inst✝ : StarRing α
      A : Matrix n n α
      ha : A.conjTranspose.IsDiag
      ⊢ Eq A A.conjTranspose.conjTranspose
    -/
    simp, IsDiag.conjTranspose⟩
    /-
      🎉 no goals
    -/


theorem IsDiag.submatrix [Zero α] {A : Matrix n n α} (ha : A.IsDiag) {f : m → n}
    (hf : Injective f) : (A.submatrix f f).IsDiag := fun _ _ h => ha (hf.ne h)


/-- `(A ⊗ B).IsDiag` if both `A` and `B` are diagonal. -/
theorem IsDiag.kronecker [MulZeroClass α] {A : Matrix m m α} {B : Matrix n n α} (hA : A.IsDiag)
    (hB : B.IsDiag) : (A ⊗ₖ B).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : MulZeroClass α
    A : Matrix m m α
    B : Matrix n n α
    hA : A.IsDiag
    hB : B.IsDiag
    ⊢ (Matrix.kroneckerMap (fun x1 x2 => HMul.hMul x1 x2) A B).IsDiag
  -/
  rintro ⟨a, b⟩ ⟨c, d⟩ h
  /-
    case mk.mk
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : MulZeroClass α
    A : Matrix m m α
    B : Matrix n n α
    hA : A.IsDiag
    hB : B.IsDiag
    a : m
    b : n
    c : m
    d : n
    h : Ne { fst := a, snd := b } { fst := c, snd := d }
    ⊢ Eq (Matrix.kroneckerMap (fun x1 x2 => HMul.hMul x1 x2) A B { fst := a, snd : …
  -/
  simp only [Prod.mk.inj_iff, Ne, not_and_or] at h
  /-
    case mk.mk
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : MulZeroClass α
    A : Matrix m m α
    B : Matrix n n α
    hA : A.IsDiag
    hB : B.IsDiag
    a : m
    b : n
    c : m
    d : n
    h : Or (Not (Eq a c)) (Not (Eq b d))
    ⊢ Eq (Matrix.kroneckerMap (fun x1 x2 => HMul.hMul x1 x2) A B { fst := a, snd : …
  -/
  cases' h with hac hbd
    /-
      case mk.mk.inl
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : MulZeroClass α
      A : Matrix m m α
      B : Matrix n n α
      hA : A.IsDiag
      hB : B.IsDiag
      a : m
      b : n
      c : m
      d : n
      hac : Not (Eq a c)
      ⊢ Eq (Matrix.kroneckerMap (fun x1 x2 => HMul.hMul x1 x2) A B { fst := a, snd : …
    -/
  · simp [hA hac]
    /-
      🎉 no goals
    -/
    /-
      case mk.mk.inr
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : MulZeroClass α
      A : Matrix m m α
      B : Matrix n n α
      hA : A.IsDiag
      hB : B.IsDiag
      a : m
      b : n
      c : m
      d : n
      hbd : Not (Eq b d)
      ⊢ Eq (Matrix.kroneckerMap (fun x1 x2 => HMul.hMul x1 x2) A B { fst := a, snd : …
    -/
  · simp [hB hbd]
    /-
      🎉 no goals
    -/


theorem IsDiag.isSymm [Zero α] {A : Matrix n n α} (h : A.IsDiag) : A.IsSymm := by
  /-
    α : Type u_1
    n : Type u_4
    inst✝ : Zero α
    A : Matrix n n α
    h : A.IsDiag
    ⊢ A.IsSymm
  -/
  ext i j
  /-
    case a
    α : Type u_1
    n : Type u_4
    inst✝ : Zero α
    A : Matrix n n α
    h : A.IsDiag
    i j : n
    ⊢ Eq (A.transpose i j) (A i j)
  -/
  by_cases g : i = j; · rw [g, transpose_apply]
                        /-
                          🎉 no goals
                        -/
  /-
    case neg
    α : Type u_1
    n : Type u_4
    inst✝ : Zero α
    A : Matrix n n α
    h : A.IsDiag
    i j : n
    g : Not (Eq i j)
    ⊢ Eq (A.transpose i j) (A i j)
  -/
  simp [h g, h (Ne.symm g)]
  /-
    🎉 no goals
  -/


/-- The block matrix `A.fromBlocks 0 0 D` is diagonal if `A` and `D` are diagonal. -/
theorem IsDiag.fromBlocks [Zero α] {A : Matrix m m α} {D : Matrix n n α} (ha : A.IsDiag)
    (hd : D.IsDiag) : (A.fromBlocks 0 0 D).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : Zero α
    A : Matrix m m α
    D : Matrix n n α
    ha : A.IsDiag
    hd : D.IsDiag
    ⊢ (Matrix.fromBlocks A 0 0 D).IsDiag
  -/
  rintro (i | i) (j | j) hij
    /-
      case inl.inl
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      D : Matrix n n α
      ha : A.IsDiag
      hd : D.IsDiag
      i j : m
      hij : Ne (Sum.inl i) (Sum.inl j)
      ⊢ Eq (Matrix.fromBlocks A 0 0 D (Sum.inl i) (Sum.inl j)) 0
    -/
  · exact ha (ne_of_apply_ne _ hij)
    /-
      🎉 no goals
    -/
    /-
      case inl.inr
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      D : Matrix n n α
      ha : A.IsDiag
      hd : D.IsDiag
      i : m
      j : n
      hij : Ne (Sum.inl i) (Sum.inr j)
      ⊢ Eq (Matrix.fromBlocks A 0 0 D (Sum.inl i) (Sum.inr j)) 0
    -/
  · rfl
    /-
      🎉 no goals
    -/
    /-
      case inr.inl
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      D : Matrix n n α
      ha : A.IsDiag
      hd : D.IsDiag
      i : n
      j : m
      hij : Ne (Sum.inr i) (Sum.inl j)
      ⊢ Eq (Matrix.fromBlocks A 0 0 D (Sum.inr i) (Sum.inl j)) 0
    -/
  · rfl
    /-
      🎉 no goals
    -/
    /-
      case inr.inr
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      D : Matrix n n α
      ha : A.IsDiag
      hd : D.IsDiag
      i j : n
      hij : Ne (Sum.inr i) (Sum.inr j)
      ⊢ Eq (Matrix.fromBlocks A 0 0 D (Sum.inr i) (Sum.inr j)) 0
    -/
  · exact hd (ne_of_apply_ne _ hij)
    /-
      🎉 no goals
    -/


/-- This is the `iff` version of `Matrix.IsDiag.fromBlocks`. -/
theorem isDiag_fromBlocks_iff [Zero α] {A : Matrix m m α} {B : Matrix m n α} {C : Matrix n m α}
    {D : Matrix n n α} : (A.fromBlocks B C D).IsDiag ↔ A.IsDiag ∧ B = 0 ∧ C = 0 ∧ D.IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : Zero α
    A : Matrix m m α
    B : Matrix m n α
    C : Matrix n m α
    D : Matrix n n α
    ⊢ Iff (Matrix.fromBlocks A B C D).IsDiag (And A.IsDiag (And (Eq B 0) (And (Eq  …
  -/
  constructor
    /-
      case mp
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      B : Matrix m n α
      C : Matrix n m α
      D : Matrix n n α
      ⊢ (Matrix.fromBlocks A B C D).IsDiag → And A.IsDiag (And (Eq B 0) (And (Eq C 0 …
    -/
  · intro h
    /-
      case mp
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      B : Matrix m n α
      C : Matrix n m α
      D : Matrix n n α
      h : (Matrix.fromBlocks A B C D).IsDiag
      ⊢ And A.IsDiag (And (Eq B 0) (And (Eq C 0) D.IsDiag))
    -/
    refine ⟨fun i j hij => ?_, ext fun i j => ?_, ext fun i j => ?_, fun i j hij => ?_⟩
      /-
        case mp.refine_1
        α : Type u_1
        n : Type u_4
        m : Type u_5
        inst✝ : Zero α
        A : Matrix m m α
        B : Matrix m n α
        C : Matrix n m α
        D : Matrix n n α
        h : (Matrix.fromBlocks A B C D).IsDiag
        i j : m
        hij : Ne i j
        ⊢ (fun i j => Eq (A i j) 0) i j
      -/
    · exact h (Sum.inl_injective.ne hij)
      /-
        🎉 no goals
      -/
      /-
        case mp.refine_2
        α : Type u_1
        n : Type u_4
        m : Type u_5
        inst✝ : Zero α
        A : Matrix m m α
        B : Matrix m n α
        C : Matrix n m α
        D : Matrix n n α
        h : (Matrix.fromBlocks A B C D).IsDiag
        i : m
        j : n
        ⊢ Eq (B i j) (0 i j)
      -/
    · exact h Sum.inl_ne_inr
      /-
        🎉 no goals
      -/
      /-
        case mp.refine_3
        α : Type u_1
        n : Type u_4
        m : Type u_5
        inst✝ : Zero α
        A : Matrix m m α
        B : Matrix m n α
        C : Matrix n m α
        D : Matrix n n α
        h : (Matrix.fromBlocks A B C D).IsDiag
        i : n
        j : m
        ⊢ Eq (C i j) (0 i j)
      -/
    · exact h Sum.inr_ne_inl
      /-
        🎉 no goals
      -/
      /-
        case mp.refine_4
        α : Type u_1
        n : Type u_4
        m : Type u_5
        inst✝ : Zero α
        A : Matrix m m α
        B : Matrix m n α
        C : Matrix n m α
        D : Matrix n n α
        h : (Matrix.fromBlocks A B C D).IsDiag
        i j : n
        hij : Ne i j
        ⊢ (fun i j => Eq (D i j) 0) i j
      -/
    · exact h (Sum.inr_injective.ne hij)
      /-
        🎉 no goals
      -/
    /-
      case mpr
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      B : Matrix m n α
      C : Matrix n m α
      D : Matrix n n α
      ⊢ And A.IsDiag (And (Eq B 0) (And (Eq C 0) D.IsDiag)) → (Matrix.fromBlocks A B …
    -/
  · rintro ⟨ha, hb, hc, hd⟩
    /-
      case mpr.intro.intro.intro
      α : Type u_1
      n : Type u_4
      m : Type u_5
      inst✝ : Zero α
      A : Matrix m m α
      B : Matrix m n α
      C : Matrix n m α
      D : Matrix n n α
      ha : A.IsDiag
      hb : Eq B 0
      hc : Eq C 0
      hd : D.IsDiag
      ⊢ (Matrix.fromBlocks A B C D).IsDiag
    -/
    convert IsDiag.fromBlocks ha hd
    /-
      🎉 no goals
    -/


/-- A symmetric block matrix `A.fromBlocks B C D` is diagonal
    if `A` and `D` are diagonal and `B` is `0`. -/
theorem IsDiag.fromBlocks_of_isSymm [Zero α] {A : Matrix m m α} {C : Matrix n m α}
    {D : Matrix n n α} (h : (A.fromBlocks 0 C D).IsSymm) (ha : A.IsDiag) (hd : D.IsDiag) :
    (A.fromBlocks 0 C D).IsDiag := by
  /-
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : Zero α
    A : Matrix m m α
    C : Matrix n m α
    D : Matrix n n α
    h : (Matrix.fromBlocks A 0 C D).IsSymm
    ha : A.IsDiag
    hd : D.IsDiag
    ⊢ (Matrix.fromBlocks A 0 C D).IsDiag
  -/
  rw [← (isSymm_fromBlocks_iff.1 h).2.1]
  /-
    α : Type u_1
    n : Type u_4
    m : Type u_5
    inst✝ : Zero α
    A : Matrix m m α
    C : Matrix n m α
    D : Matrix n n α
    h : (Matrix.fromBlocks A 0 C D).IsSymm
    ha : A.IsDiag
    hd : D.IsDiag
    ⊢ (Matrix.fromBlocks A 0 (Matrix.transpose 0) D).IsDiag
  -/
  exact ha.fromBlocks hd
  /-
    🎉 no goals
  -/


theorem mul_transpose_self_isDiag_iff_hasOrthogonalRows [Fintype n] [Mul α] [AddCommMonoid α]
    {A : Matrix m n α} : (A * Aᵀ).IsDiag ↔ A.HasOrthogonalRows :=
  Iff.rfl


theorem transpose_mul_self_isDiag_iff_hasOrthogonalCols [Fintype m] [Mul α] [AddCommMonoid α]
    {A : Matrix m n α} : (Aᵀ * A).IsDiag ↔ A.HasOrthogonalCols :=
  Iff.rfl


