/-- A free group basis `FreeGroupBasis ι G` is a structure recording the isomorphism between a
group `G` and the free group over `ι`. One may think of such a basis as a function from `ι` to `G`
(which is registered through a `FunLike` instance) together with the fact that the morphism induced
by this function from `FreeGroup ι` to `G` is an isomorphism. -/
structure FreeGroupBasis (ι : Type*) (G : Type*) [Group G] where
  /-- `FreeGroupBasis.ofRepr` constructs a basis given an equivalence with a free group. -/
  ofRepr ::
    /-- `repr` is the isomorphism between the group `G` and the free group generated by `ι`. -/
    repr : G ≃* FreeGroup ι


/-- A group is free if it admits a free group basis. In the definition, we require the basis to
be in the same universe as `G`, although this property follows from the existence of a basis in
any universe, see `FreeGroupBasis.isFreeGroup`. -/
class IsFreeGroup (G : Type u) [Group G] : Prop where
  nonempty_basis : ∃ (ι : Type u), Nonempty (FreeGroupBasis ι G)


/-- A free group basis for `G` over `ι` is associated to a map `ι → G` recording the images of
the generators. -/
instance instFunLike : FunLike (FreeGroupBasis ι G) ι G where
  coe b := fun i ↦ b.repr.symm (FreeGroup.of i)
  coe_injective' := by
    /-
      ι : Type u_1
      ι' : Type u_2
      G : Type u_3
      H : Type u_4
      inst✝¹ : Group G
      inst✝ : Group H
      ⊢ Function.Injective fun b i => b.repr.symm (FreeGroup.of i)
    -/
    rintro ⟨b⟩  ⟨b'⟩ hbb'
    have H : (b.symm : FreeGroup ι →* G) = (b'.symm : FreeGroup ι →* G) := by
      ext i; exact congr_fun hbb' i
    /-
      case ofRepr.ofRepr
      ι : Type u_1
      ι' : Type u_2
      G : Type u_3
      H✝ : Type u_4
      inst✝¹ : Group G
      inst✝ : Group H✝
      b b' : MulEquiv G (FreeGroup ι)
      hbb' : Eq ((fun b i => b.repr.symm (FreeGroup.of i)) { repr := b }) ((fun b i  …
      H : Eq ↑b.symm ↑b'.symm
      ⊢ Eq { repr := b } { repr := b' }
    -/
    have : b.symm = b'.symm := by ext x; exact DFunLike.congr_fun H x
    /-
      case ofRepr.ofRepr
      ι : Type u_1
      ι' : Type u_2
      G : Type u_3
      H✝ : Type u_4
      inst✝¹ : Group G
      inst✝ : Group H✝
      b b' : MulEquiv G (FreeGroup ι)
      hbb' : Eq ((fun b i => b.repr.symm (FreeGroup.of i)) { repr := b }) ((fun b i  …
      H : Eq ↑b.symm ↑b'.symm
      this : Eq b.symm b'.symm
      ⊢ Eq { repr := b } { repr := b' }
    -/
    rw [ofRepr.injEq, ← MulEquiv.symm_symm b, ← MulEquiv.symm_symm b', this]
    /-
      🎉 no goals
    -/


@[simp] lemma repr_apply_coe (b : FreeGroupBasis ι G) (i : ι) : b.repr (b i) = FreeGroup.of i := by
  /-
    ι : Type u_1
    G : Type u_3
    inst✝ : Group G
    b : FreeGroupBasis ι G
    i : ι
    ⊢ Eq (b.repr (b i)) (FreeGroup.of i)
  -/
  change b.repr (b.repr.symm (FreeGroup.of i)) = FreeGroup.of i
  /-
    ι : Type u_1
    G : Type u_3
    inst✝ : Group G
    b : FreeGroupBasis ι G
    i : ι
    ⊢ Eq (b.repr (b.repr.symm (FreeGroup.of i))) (FreeGroup.of i)
  -/
  simp
  /-
    🎉 no goals
  -/


/-- The canonical basis of the free group over `X`. -/
def ofFreeGroup (X : Type*) : FreeGroupBasis X (FreeGroup X) := ofRepr (MulEquiv.refl _)


@[simp] lemma ofFreeGroup_apply {X : Type*} (x : X) :
    FreeGroupBasis.ofFreeGroup X x = FreeGroup.of x :=
  rfl


/-- Reindex a free group basis through a bijection of the indexing sets. -/
protected def reindex (b : FreeGroupBasis ι G) (e : ι ≃ ι') : FreeGroupBasis ι' G :=
  ofRepr (b.repr.trans (FreeGroup.freeGroupCongr e))


@[simp] lemma reindex_apply (b : FreeGroupBasis ι G) (e : ι ≃ ι') (x : ι') :
    b.reindex e x = b (e.symm x) := rfl


/-- Pushing a free group basis through a group isomorphism. -/
protected def map (b : FreeGroupBasis ι G) (e : G ≃* H) : FreeGroupBasis ι H :=
  ofRepr (e.symm.trans b.repr)


@[simp] lemma map_apply (b : FreeGroupBasis ι G) (e : G ≃* H) (x : ι) :
    b.map e x = e (b x) := rfl


protected lemma injective (b : FreeGroupBasis ι G) : Injective b :=
  b.repr.symm.injective.comp FreeGroup.of_injective


/-- A group admitting a free group basis is a free group. -/
lemma isFreeGroup (b : FreeGroupBasis ι G) : IsFreeGroup G :=
  ⟨range b, ⟨b.reindex (Equiv.ofInjective (↑b) b.injective)⟩⟩


instance (X : Type*) : IsFreeGroup (FreeGroup X) :=
  (ofFreeGroup X).isFreeGroup


/-- Given a free group basis of `G` over `ι`, there is a canonical bijection between maps from `ι`
to a group `H` and morphisms from `G` to `H`. -/
@[simps!]
def lift (b : FreeGroupBasis ι G) : (ι → H) ≃ (G →* H) :=
  FreeGroup.lift.trans
    { toFun := fun f => f.comp b.repr.toMonoidHom
      invFun := fun f => f.comp b.repr.symm.toMonoidHom
      left_inv := fun f => by
        /-
          ι : Type u_1
          ι' : Type u_2
          G : Type u_3
          H : Type u_4
          inst✝¹ : Group G
          inst✝ : Group H
          b : FreeGroupBasis ι G
          f : MonoidHom (FreeGroup ι) H
          ⊢ Eq ((fun f => f.comp b.repr.symm.toMonoidHom) ((fun f => f.comp b.repr.toMon …
        -/
        ext
        /-
          case h
          ι : Type u_1
          ι' : Type u_2
          G : Type u_3
          H : Type u_4
          inst✝¹ : Group G
          inst✝ : Group H
          b : FreeGroupBasis ι G
          f : MonoidHom (FreeGroup ι) H
          a✝ : ι
          ⊢ Eq (((fun f => f.comp b.repr.symm.toMonoidHom) ((fun f => f.comp b.repr.toMo …
        -/
        simp
        /-
          🎉 no goals
        -/
      right_inv := fun f => by
        /-
          ι : Type u_1
          ι' : Type u_2
          G : Type u_3
          H : Type u_4
          inst✝¹ : Group G
          inst✝ : Group H
          b : FreeGroupBasis ι G
          f : MonoidHom G H
          ⊢ Eq ((fun f => f.comp b.repr.toMonoidHom) ((fun f => f.comp b.repr.symm.toMon …
        -/
        ext
        /-
          case h
          ι : Type u_1
          ι' : Type u_2
          G : Type u_3
          H : Type u_4
          inst✝¹ : Group G
          inst✝ : Group H
          b : FreeGroupBasis ι G
          f : MonoidHom G H
          x✝ : G
          ⊢ Eq (((fun f => f.comp b.repr.toMonoidHom) ((fun f => f.comp b.repr.symm.toMo …
        -/
        simp }
        /-
          🎉 no goals
        -/


/-- If two morphisms on `G` coincide on the elements of a basis, then they coincide. -/
lemma ext_hom (b : FreeGroupBasis ι G) (f g : G →* H) (h : ∀ i, f (b i) = g (b i)) : f = g :=
  b.lift.symm.injective <| funext h


/-- If a group satisfies the universal property of a free group with respect to a given type, then
it admits a free group basis based on this type. Here, the universal property is expressed as
in `IsFreeGroup.lift` and its properties. -/
def ofLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (lift : ∀ {H : Type u} [Group H], (X → H) ≃ (G →* H))
    (lift_of : ∀ {H : Type u} [Group H], ∀ (f : X → H) (a), lift f (of a) = f a) :
    FreeGroupBasis X G where
  repr := MulEquiv.symm <| MonoidHom.toMulEquiv (FreeGroup.lift of) (lift FreeGroup.of)
      (by
        /-
          ι : Type u_1
          ι' : Type u_2
          G✝ : Type u_3
          H : Type u_4
          inst✝² : Group G✝
          inst✝¹ : Group H
          G : Type u
          inst✝ : Group G
          X : Type u
          of : X → G
          lift : {H : Type u} → [inst : Group H] → Equiv (X → H) (MonoidHom G H)
          lift_of : ∀ {H : Type u} [inst : Group H] (f : X → H) (a : X), Eq ((lift f) (o …
          ⊢ Eq ((lift FreeGroup.of).comp (FreeGroup.lift of)) (MonoidHom.id (FreeGroup X))
        -/
        apply FreeGroup.ext_hom; intro x
        simp only [MonoidHom.coe_comp, Function.comp_apply, MonoidHom.id_apply, FreeGroup.lift.of,
          lift_of])
      (by
        let lift_symm_of : ∀ {H : Type u} [Group H], ∀ (f : G →* H) (a), lift.symm f a = f (of a) :=
          by intro H _ f a; simp [← lift_of (lift.symm f)]
        /-
          ι : Type u_1
          ι' : Type u_2
          G✝ : Type u_3
          H : Type u_4
          inst✝² : Group G✝
          inst✝¹ : Group H
          G : Type u
          inst✝ : Group G
          X : Type u
          of : X → G
          lift : {H : Type u} → [inst : Group H] → Equiv (X → H) (MonoidHom G H)
          lift_of : ∀ {H : Type u} [inst : Group H] (f : X → H) (a : X), Eq ((lift f) (o …
          lift_symm_of : ∀ {H : Type u} [inst : Group H] (f : MonoidHom G H) (a : X), Eq …
          ⊢ Eq ((FreeGroup.lift of).comp (lift FreeGroup.of)) (MonoidHom.id G)
        -/
        apply lift.symm.injective; ext x
        simp only [MonoidHom.coe_comp, Function.comp_apply, MonoidHom.id_apply, FreeGroup.lift.of,
          lift_of, lift_symm_of])


/-- If a group satisfies the universal property of a free group with respect to a given type, then
it admits a free group basis based on this type. Here
the universal property is expressed as in `IsFreeGroup.unique_lift`. -/
def ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (h : ∀ {H : Type u} [Group H] (f : X → H), ∃! F : G →* H, ∀ a, F (of a) = f a) :
    FreeGroupBasis X G :=
  let lift {H : Type u} [Group H] : (X → H) ≃ (G →* H) :=
    { toFun := fun f => Classical.choose (h f)
      invFun := fun F => F ∘ of
      left_inv := fun f => funext (Classical.choose_spec (h f)).left
      right_inv := fun F => ((Classical.choose_spec (h (F ∘ of))).right F fun _ => rfl).symm }
  let lift_of {H : Type u} [Group H] (f : X → H) (a : X) : lift f (of a) = f a :=
    congr_fun (lift.symm_apply_apply f) a
  ofLift X of @lift @lift_of


/-- A set of generators of a free group, chosen arbitrarily -/
def Generators : Type _ := (IsFreeGroup.nonempty_basis (G := G)).choose


/-- Any free group is isomorphic to "the" free group. -/
irreducible_def mulEquiv : FreeGroup (Generators G) ≃* G :=
  (IsFreeGroup.nonempty_basis (G := G)).choose_spec.some.repr.symm


/-- A free group basis of a free group `G`, over the set `Generators G`. -/
def basis : FreeGroupBasis (Generators G) G := FreeGroupBasis.ofRepr (mulEquiv G).symm


/-- Any free group is isomorphic to "the" free group. -/
@[simps!]
def toFreeGroup : G ≃* FreeGroup (Generators G) :=
  (mulEquiv G).symm


/-- The canonical injection of G's generators into G -/
def of : Generators G → G :=
  (mulEquiv G).toFun ∘ FreeGroup.of


/-- The equivalence between functions on the generators and group homomorphisms from a free group
given by those generators. -/
def lift : (Generators G → H) ≃ (G →* H) :=
  (basis G).lift


@[simp]
theorem lift_of (f : Generators G → H) (a : Generators G) : lift f (of a) = f a :=
  congr_fun (lift.symm_apply_apply f) a


@[simp]
theorem lift_symm_apply (f : G →* H) (a : Generators G) : (lift.symm f) a = f (of a) :=
  rfl

/- Do not register this as an ext lemma, as `Generators G` is not canonical. -/

theorem ext_hom ⦃f g : G →* H⦄ (h : ∀ a : Generators G, f (of a) = g (of a)) : f = g :=
  lift.symm.injective (funext h)


/-- The universal property of a free group: A function from the generators of `G` to another
group extends in a unique way to a homomorphism from `G`.

Note that since `IsFreeGroup.lift` is expressed as a bijection, it already
expresses the universal property. -/
theorem unique_lift (f : Generators G → H) : ∃! F : G →* H, ∀ a, F (of a) = f a := by
  /-
    G : Type u_1
    inst✝² : Group G
    inst✝¹ : IsFreeGroup G
    H : Type u_2
    inst✝ : Group H
    f : IsFreeGroup.Generators G → H
    ⊢ ExistsUnique fun F => ∀ (a : IsFreeGroup.Generators G), Eq (F (IsFreeGroup.o …
  -/
  simpa only [funext_iff] using lift.symm.bijective.existsUnique f
  /-
    🎉 no goals
  -/


/-- If a group satisfies the universal property of a free group with respect to a given type, then
it is free. Here, the universal property is expressed as in `IsFreeGroup.lift` and its
properties. -/
lemma ofLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (lift : ∀ {H : Type u} [Group H], (X → H) ≃ (G →* H))
    (lift_of : ∀ {H : Type u} [Group H], ∀ (f : X → H) (a), lift f (of a) = f a) :
    IsFreeGroup G :=
  (FreeGroupBasis.ofLift X of lift lift_of).isFreeGroup


/-- If a group satisfies the universal property of a free group with respect to a given type, then
it is free. Here the universal property is expressed as in `IsFreeGroup.unique_lift`. -/
lemma ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (h : ∀ {H : Type u} [Group H] (f : X → H), ∃! F : G →* H, ∀ a, F (of a) = f a) :
    IsFreeGroup G :=
  (FreeGroupBasis.ofUniqueLift X of h).isFreeGroup


lemma ofMulEquiv (e : G ≃* H) : IsFreeGroup H :=
  ((basis G).map e).isFreeGroup


