/-- The type of sections which generate a sheaf of modules. -/
structure GeneratingSections where
  /-- the index type for the sections -/
  I : Type u
  /-- a family of sections which generate the sheaf of modules -/
  s : I → M.sections
  epi : Epi (M.freeHomEquiv.symm s) := by infer_instance


/-- The epimorphism `free σ.I ⟶ M` given by `σ : M.GeneratingSections`. -/
noncomputable abbrev π (σ : M.GeneratingSections) : free σ.I ⟶ M := M.freeHomEquiv.symm σ.s


/-- If `M ⟶ N` is an epimorphisms and that `M` is generated by some sections,
then `N` is generated by the images of these sections. -/
@[simps]
def ofEpi (σ : M.GeneratingSections) (p : M ⟶ N) [Epi p] :
    N.GeneratingSections where
  I := σ.I
  s i := sectionsMap p (σ.s i)
  epi := by
    /-
      C : Type u'
      inst✝⁴ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝³ : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝² : J.WEqualsLocallyBijective AddCommGrp
      inst✝¹ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      σ : M.GeneratingSections
      p : Quiver.Hom M N
      inst✝ : CategoryTheory.Epi p
      ⊢ CategoryTheory.Epi (N.freeHomEquiv.symm fun i => SheafOfModules.sectionsMap  …
    -/
    rw [← freeHomEquiv_symm_comp]
    /-
      C : Type u'
      inst✝⁴ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝³ : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝² : J.WEqualsLocallyBijective AddCommGrp
      inst✝¹ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      σ : M.GeneratingSections
      p : Quiver.Hom M N
      inst✝ : CategoryTheory.Epi p
      ⊢ CategoryTheory.Epi (CategoryTheory.CategoryStruct.comp (M.freeHomEquiv.symm  …
    -/
    apply epi_comp
    /-
      🎉 no goals
    -/


lemma opEpi_id (σ : M.GeneratingSections) :
    σ.ofEpi (𝟙 M) = σ := rfl


lemma opEpi_comp (σ : M.GeneratingSections) (p : M ⟶ N) (q : N ⟶ P) [Epi p] [Epi q] :
    σ.ofEpi (p ≫ q) = (σ.ofEpi p).ofEpi q := rfl


/-- Two isomorphic sheaves of modules have equivalent families of generating sections. -/
def equivOfIso (e : M ≅ N) :
    M.GeneratingSections ≃ N.GeneratingSections where
  toFun σ := σ.ofEpi e.hom
  invFun σ := σ.ofEpi e.inv
  left_inv σ := by
    /-
      C : Type u'
      inst✝³ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝² : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝¹ : J.WEqualsLocallyBijective AddCommGrp
      inst✝ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      e : CategoryTheory.Iso M N
      σ : M.GeneratingSections
      ⊢ Eq ((fun σ => σ.ofEpi e.inv) ((fun σ => σ.ofEpi e.hom) σ)) σ
    -/
    dsimp
    /-
      C : Type u'
      inst✝³ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝² : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝¹ : J.WEqualsLocallyBijective AddCommGrp
      inst✝ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      e : CategoryTheory.Iso M N
      σ : M.GeneratingSections
      ⊢ Eq ((σ.ofEpi e.hom).ofEpi e.inv) σ
    -/
    simp only [← opEpi_comp, e.hom_inv_id, opEpi_id]
    /-
      🎉 no goals
    -/
  right_inv σ := by
    /-
      C : Type u'
      inst✝³ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝² : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝¹ : J.WEqualsLocallyBijective AddCommGrp
      inst✝ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      e : CategoryTheory.Iso M N
      σ : N.GeneratingSections
      ⊢ Eq ((fun σ => σ.ofEpi e.hom) ((fun σ => σ.ofEpi e.inv) σ)) σ
    -/
    dsimp
    /-
      C : Type u'
      inst✝³ : CategoryTheory.Category.{v', u'} C
      J : CategoryTheory.GrothendieckTopology C
      R : CategoryTheory.Sheaf J RingCat
      inst✝² : CategoryTheory.HasWeakSheafify J AddCommGrp
      inst✝¹ : J.WEqualsLocallyBijective AddCommGrp
      inst✝ : J.HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrp)
      M N P : SheafOfModules R
      e : CategoryTheory.Iso M N
      σ : N.GeneratingSections
      ⊢ Eq ((σ.ofEpi e.inv).ofEpi e.hom) σ
    -/
    simp only [← opEpi_comp, e.inv_hom_id, opEpi_id]
    /-
      🎉 no goals
    -/


/-- The data of generating sections of the restriction of a sheaf of modules
over a covering of the terminal object. -/
structure LocalGeneratorsData where
  /-- the index type of the covering -/
  I : Type u'
  /-- a family of objects which cover the terminal object -/
  X : I → C
  coversTop : J.CoversTop X
  /-- the data of sections of `M` over `X i` which generate `M.over (X i)` -/
  generators (i : I) : (M.over (X i)).GeneratingSections


/-- A sheaf of modules is of finite type if locally, it is generated by finitely
many sections. -/
class IsFiniteType : Prop where
  exists_localGeneratorsData :
    ∃ (σ : M.LocalGeneratorsData), ∀ (i : σ.I), Finite (σ.generators i).I


/-- A choice of local generators when `M` is a sheaf of modules of finite type. -/
noncomputable def localGeneratorsDataOfIsFiniteType : M.LocalGeneratorsData :=
  h.exists_localGeneratorsData.choose


instance (i : M.localGeneratorsDataOfIsFiniteType.I) :
    Finite (M.localGeneratorsDataOfIsFiniteType.generators i).I :=
  h.exists_localGeneratorsData.choose_spec i


