/-- The categorical data that is involved in a `1`-hypercover of an object `S`. This
consists of a family of morphisms `f i : X i ⟶ S` for `i : I₀`, and for each
tuple `(i₁, i₂)` of elements in `I₀`, a family of objects `Y j` indexed by
a type `I₁ i₁ i₂`, which are equipped with a map to the fibre product of `X i₁`
and `X i₂`, which is phrased here as the data of the two projections
`p₁ : Y j ⟶ X i₁`, `p₂ : Y j ⟶ X i₂` and the relation `p₁ j ≫ f i₁ = p₂ j ≫ f i₂`.
(See `GrothendieckTopology.OneHypercover` for the topological conditions.) -/
structure PreOneHypercover (S : C) where
  /-- the index type of the covering of `S` -/
  I₀ : Type w
  /-- the objects in the covering of `S` -/
  X (i : I₀) : C
  /-- the morphisms in the covering of `S` -/
  f (i : I₀) : X i ⟶ S
  /-- the index type of the coverings of the fibre products -/
  I₁ (i₁ i₂ : I₀) : Type w
  /-- the objects in the coverings of the fibre products  -/
  Y ⦃i₁ i₂ : I₀⦄ (j : I₁ i₁ i₂) : C
  /-- the first projection `Y j ⟶ X i₁` -/
  p₁ ⦃i₁ i₂ : I₀⦄ (j : I₁ i₁ i₂) : Y j ⟶ X i₁
  /-- the second projection `Y j ⟶ X i₂` -/
  p₂ ⦃i₁ i₂ : I₀⦄ (j : I₁ i₁ i₂) : Y j ⟶ X i₂
  w ⦃i₁ i₂ : I₀⦄ (j : I₁ i₁ i₂) : p₁ j ≫ f i₁ = p₂ j ≫ f i₂


/-- The assumption that the pullback of `X i₁` and `X i₂` over `S` exists
for any `i₁` and `i₂`. -/
abbrev HasPullbacks := ∀ (i₁ i₂ : E.I₀), HasPullback (E.f i₁) (E.f i₂)


/-- The sieve of `S` that is generated by the morphisms `f i : X i ⟶ S`. -/
abbrev sieve₀ : Sieve S := Sieve.ofArrows _ E.f


/-- Given an object `W` equipped with morphisms `p₁ : W ⟶ E.X i₁`, `p₂ : W ⟶ E.X i₂`,
this is the sieve of `W` which consists of morphisms `g : Z ⟶ W` such that there exists `j`
and `h : Z ⟶ E.Y j` such that `g ≫ p₁ = h ≫ E.p₁ j` and `g ≫ p₂ = h ≫ E.p₂ j`.
See lemmas `sieve₁_eq_pullback_sieve₁'` and `sieve₁'_eq_sieve₁` for equational lemmas
regarding this sieve. -/
@[simps]
def sieve₁ {i₁ i₂ : E.I₀} {W : C} (p₁ : W ⟶ E.X i₁) (p₂ : W ⟶ E.X i₂) : Sieve W where
  arrows Z g := ∃ (j : E.I₁ i₁ i₂) (h : Z ⟶ E.Y j), g ≫ p₁ = h ≫ E.p₁ j ∧ g ≫ p₂ = h ≫ E.p₂ j
  downward_closed := by
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.3024, u_1} A
      S : C
      E : CategoryTheory.PreOneHypercover S
      i₁ i₂ : E.I₀
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      ⊢ ∀ {Y Z : C} {f : Quiver.Hom Y W}, (fun Z g => Exists fun j => Exists fun h = …
    -/
    rintro Z Z' g ⟨j, h, fac₁, fac₂⟩ φ
    /-
      case intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.3024, u_1} A
      S : C
      E : CategoryTheory.PreOneHypercover S
      i₁ i₂ : E.I₀
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      Z Z' : C
      g : Quiver.Hom Z W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom Z (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      φ : Quiver.Hom Z' Z
      ⊢ Exists fun j => Exists fun h => And (Eq (CategoryTheory.CategoryStruct.comp  …
    -/
    exact ⟨j, φ ≫ h, by simpa using φ ≫= fac₁, by simpa using φ ≫= fac₂⟩
    /-
      🎉 no goals
    -/


/-- The obvious morphism `E.Y j ⟶ pullback (E.f i₁) (E.f i₂)` given by `E : PreOneHypercover S`. -/
noncomputable abbrev toPullback (j : E.I₁ i₁ i₂) [HasPullback (E.f i₁) (E.f i₂)] :
    E.Y j ⟶ pullback (E.f i₁) (E.f i₂) :=
  pullback.lift (E.p₁ j) (E.p₂ j) (E.w j)


variable (i₁ i₂) in
/-- The sieve of `pullback (E.f i₁) (E.f i₂)` given by `E : PreOneHypercover S`. -/
def sieve₁' : Sieve (pullback (E.f i₁) (E.f i₂)) :=
  Sieve.ofArrows _ (fun (j : E.I₁ i₁ i₂) => E.toPullback j)


lemma sieve₁_eq_pullback_sieve₁' {W : C} (p₁ : W ⟶ E.X i₁) (p₂ : W ⟶ E.X i₂)
    (w : p₁ ≫ E.f i₁ = p₂ ≫ E.f i₂) :
    E.sieve₁ p₁ p₂ = (E.sieve₁' i₁ i₂).pullback (pullback.lift _ _ w) := by
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    S : C
    E : CategoryTheory.PreOneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    W : C
    p₁ : Quiver.Hom W (E.X i₁)
    p₂ : Quiver.Hom W (E.X i₂)
    w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
    ⊢ Eq (E.sieve₁ p₁ p₂) (CategoryTheory.Sieve.pullback (CategoryTheory.Limits.pu …
  -/
  ext Z g
  /-
    case h
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    S : C
    E : CategoryTheory.PreOneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    W : C
    p₁ : Quiver.Hom W (E.X i₁)
    p₂ : Quiver.Hom W (E.X i₂)
    w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
    Z : C
    g : Quiver.Hom Z W
    ⊢ Iff ((E.sieve₁ p₁ p₂).arrows g) ((CategoryTheory.Sieve.pullback (CategoryThe …
  -/
  constructor
    /-
      case h.mp
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      S : C
      E : CategoryTheory.PreOneHypercover S
      i₁ i₂ : E.I₀
      inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      Z : C
      g : Quiver.Hom Z W
      ⊢ (E.sieve₁ p₁ p₂).arrows g → (CategoryTheory.Sieve.pullback (CategoryTheory.L …
    -/
  · rintro ⟨j, h, fac₁, fac₂⟩
    /-
      case h.mp.intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      S : C
      E : CategoryTheory.PreOneHypercover S
      i₁ i₂ : E.I₀
      inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      Z : C
      g : Quiver.Hom Z W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom Z (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      ⊢ (CategoryTheory.Sieve.pullback (CategoryTheory.Limits.pullback.lift p₁ p₂ w) …
    -/
    exact ⟨_, h, _, ⟨j⟩, by aesop_cat⟩
    /-
      🎉 no goals
    -/
    /-
      case h.mpr
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      S : C
      E : CategoryTheory.PreOneHypercover S
      i₁ i₂ : E.I₀
      inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      Z : C
      g : Quiver.Hom Z W
      ⊢ (CategoryTheory.Sieve.pullback (CategoryTheory.Limits.pullback.lift p₁ p₂ w) …
    -/
  · rintro ⟨_, h, w, ⟨j⟩, fac⟩
    exact ⟨j, h, by simpa using fac.symm =≫ pullback.fst _ _,
      by simpa using fac.symm =≫ pullback.snd _ _⟩


variable (i₁ i₂) in
lemma sieve₁'_eq_sieve₁ : E.sieve₁' i₁ i₂ = E.sieve₁ (pullback.fst _ _) (pullback.snd _ _) := by
  rw [← Sieve.pullback_id (S := E.sieve₁' i₁ i₂),
    sieve₁_eq_pullback_sieve₁' _ _ _ pullback.condition]
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    S : C
    E : CategoryTheory.PreOneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    ⊢ Eq (CategoryTheory.Sieve.pullback (CategoryTheory.CategoryStruct.id (Categor …
  -/
  congr
  /-
    case e_h
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    S : C
    E : CategoryTheory.PreOneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    ⊢ Eq (CategoryTheory.CategoryStruct.id (CategoryTheory.Limits.pullback (E.f i₁ …
  -/
  aesop_cat
  /-
    🎉 no goals
  -/


/-- The sigma type of all `E.I₁ i₁ i₂` for `⟨i₁, i₂⟩ : E.I₀ × E.I₀`. -/
abbrev I₁' : Type w := Sigma (fun (i : E.I₀ × E.I₀) => E.I₁ i.1 i.2)


/-- The diagram of the multifork attached to a presheaf
`F : Cᵒᵖ ⥤ A`, `S : C` and `E : PreOneHypercover S`. -/
@[simps]
def multicospanIndex (F : Cᵒᵖ ⥤ A) : MulticospanIndex A where
  L := E.I₀
  R := E.I₁'
  fstTo j := j.1.1
  sndTo j := j.1.2
  left i := F.obj (Opposite.op (E.X i))
  right j := F.obj (Opposite.op (E.Y j.2))
  fst j := F.map ((E.p₁ j.2).op)
  snd j := F.map ((E.p₂ j.2).op)


/-- The multifork attached to a presheaf `F : Cᵒᵖ ⥤ A`, `S : C` and `E : PreOneHypercover S`. -/
def multifork (F : Cᵒᵖ ⥤ A) :
    Multifork (E.multicospanIndex F) :=
  Multifork.ofι _ (F.obj (Opposite.op S)) (fun i₀ => F.map (E.f i₀).op) (by
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.17845, u_1} A
      S : C
      E : CategoryTheory.PreOneHypercover S
      F : CategoryTheory.Functor (Opposite C) A
      ⊢ ∀ (b : (E.multicospanIndex F).R), Eq (CategoryTheory.CategoryStruct.comp ((f …
    -/
    rintro ⟨⟨i₁, i₂⟩, (j : E.I₁ i₁ i₂)⟩
    /-
      case mk.mk
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.17845, u_1} A
      S : C
      E : CategoryTheory.PreOneHypercover S
      F : CategoryTheory.Functor (Opposite C) A
      i₁ i₂ : E.I₀
      j : E.I₁ i₁ i₂
      ⊢ Eq (CategoryTheory.CategoryStruct.comp ((fun i₀ => F.map (E.f i₀).op) ((E.mu …
    -/
    dsimp
    /-
      case mk.mk
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.17845, u_1} A
      S : C
      E : CategoryTheory.PreOneHypercover S
      F : CategoryTheory.Functor (Opposite C) A
      i₁ i₂ : E.I₀
      j : E.I₁ i₁ i₂
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (F.map (E.f i₁).op) (F.map (E.p₁ j).o …
    -/
    simp only [← F.map_comp, ← op_comp, E.w])
    /-
      🎉 no goals
    -/


/-- The type of `1`-hypercovers of an object `S : C` in a category equipped with a
Grothendieck topology `J`. This can be constructed from a covering of `S` and
a covering of the fibre products of the objects in this covering (see `OneHypercover.mk'`). -/
structure OneHypercover (S : C) extends PreOneHypercover.{w} S where
  mem₀ : toPreOneHypercover.sieve₀ ∈ J S
  mem₁ (i₁ i₂ : I₀) ⦃W : C⦄ (p₁ : W ⟶ X i₁) (p₂ : W ⟶ X i₂) (w : p₁ ≫ f i₁ = p₂ ≫ f i₂) :
    toPreOneHypercover.sieve₁ p₁ p₂ ∈ J W


lemma OneHypercover.mem_sieve₁' {S : C} (E : J.OneHypercover S)
    (i₁ i₂ : E.I₀) [HasPullback (E.f i₁) (E.f i₂)] :
    E.sieve₁' i₁ i₂ ∈ J _ := by
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    S : C
    E : J.OneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    ⊢ Membership.mem (J (CategoryTheory.Limits.pullback (E.f i₁) (E.f i₂))) (E.sie …
  -/
  rw [E.sieve₁'_eq_sieve₁]
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    S : C
    E : J.OneHypercover S
    i₁ i₂ : E.I₀
    inst✝ : CategoryTheory.Limits.HasPullback (E.f i₁) (E.f i₂)
    ⊢ Membership.mem (J (CategoryTheory.Limits.pullback (E.f i₁) (E.f i₂))) (E.sie …
  -/
  exact mem₁ _ _ _ _ _ pullback.condition
  /-
    🎉 no goals
  -/


/-- In order to check that a certain data is a `1`-hypercover of `S`, it suffices to
check that the data provides a covering of `S` and of the fibre products. -/
@[simps toPreOneHypercover]
def mk' {S : C} (E : PreOneHypercover S) [E.HasPullbacks]
    (mem₀ : E.sieve₀ ∈ J S) (mem₁' : ∀ (i₁ i₂ : E.I₀), E.sieve₁' i₁ i₂ ∈ J _) :
    J.OneHypercover S where
  toPreOneHypercover := E
  mem₀ := mem₀
  mem₁ i₁ i₂ W p₁ p₂ w := by
    /-
      C : Type u
      inst✝² : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝¹ : CategoryTheory.Category.{?u.21859, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : CategoryTheory.PreOneHypercover S
      inst✝ : E.HasPullbacks
      mem₀ : Membership.mem (J S) E.sieve₀
      mem₁' : ∀ (i₁ i₂ : E.I₀), Membership.mem (J (CategoryTheory.Limits.pullback (E …
      i₁ i₂ : E.I₀
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      ⊢ Membership.mem (J W) (E.sieve₁ p₁ p₂)
    -/
    rw [E.sieve₁_eq_pullback_sieve₁' _ _ w]
    /-
      C : Type u
      inst✝² : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝¹ : CategoryTheory.Category.{?u.21859, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : CategoryTheory.PreOneHypercover S
      inst✝ : E.HasPullbacks
      mem₀ : Membership.mem (J S) E.sieve₀
      mem₁' : ∀ (i₁ i₂ : E.I₀), Membership.mem (J (CategoryTheory.Limits.pullback (E …
      i₁ i₂ : E.I₀
      W : C
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      ⊢ Membership.mem (J W) (CategoryTheory.Sieve.pullback (CategoryTheory.Limits.p …
    -/
    exact J.pullback_stable' _ (mem₁' i₁ i₂)
    /-
      🎉 no goals
    -/


/-- Auxiliary definition of `isLimitMultifork`. -/
noncomputable def multiforkLift : c.pt ⟶ F.val.obj (Opposite.op S) :=
  F.cond.amalgamateOfArrows _ E.mem₀ c.ι (fun W i₁ i₂ p₁ p₂ w => by
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (c.ι i₁) (F.val.map p₁.op)) (Category …
    -/
    apply F.cond.hom_ext ⟨_, E.mem₁ _ _ _ _ w⟩
    /-
      case h
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      ⊢ ∀ (I : CategoryTheory.GrothendieckTopology.Cover.Arrow ⟨E.sieve₁ p₁ p₂, ⋯⟩), …
    -/
    rintro ⟨T, g, j, h, fac₁, fac₂⟩
    /-
      case h.mk.intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      T : C
      g : Quiver.Hom T W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom T (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp ( …
    -/
    dsimp
    /-
      case h.mk.intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      T : C
      g : Quiver.Hom T W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom T (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.CategoryStruct.comp ( …
    -/
    simp only [assoc, ← Functor.map_comp, ← op_comp, fac₁, fac₂]
    /-
      case h.mk.intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      T : C
      g : Quiver.Hom T W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom T (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (c.ι i₁) (F.val.map (CategoryTheory.C …
    -/
    simp only [op_comp, Functor.map_comp]
    /-
      case h.mk.intro.intro.intro
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.23605, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      W : C
      i₁ i₂ : E.I₀
      p₁ : Quiver.Hom W (E.X i₁)
      p₂ : Quiver.Hom W (E.X i₂)
      w : Eq (CategoryTheory.CategoryStruct.comp p₁ (E.f i₁)) (CategoryTheory.Catego …
      T : C
      g : Quiver.Hom T W
      j : E.I₁ i₁ i₂
      h : Quiver.Hom T (E.Y j)
      fac₁ : Eq (CategoryTheory.CategoryStruct.comp g p₁) (CategoryTheory.CategorySt …
      fac₂ : Eq (CategoryTheory.CategoryStruct.comp g p₂) (CategoryTheory.CategorySt …
      ⊢ Eq (CategoryTheory.CategoryStruct.comp (c.ι i₁) (CategoryTheory.CategoryStru …
    -/
    simpa using c.condition ⟨⟨i₁, i₂⟩, j⟩ =≫ F.val.map h.op)
    /-
      🎉 no goals
    -/


@[reassoc]
lemma multiforkLift_map (i₀ : E.I₀) : multiforkLift c ≫ F.val.map (E.f i₀).op = c.ι i₀ := by
  /-
    C : Type u
    inst✝¹ : CategoryTheory.Category.{v, u} C
    A : Type u_1
    inst✝ : CategoryTheory.Category.{u_3, u_1} A
    J : CategoryTheory.GrothendieckTopology C
    S : C
    E : J.OneHypercover S
    F : CategoryTheory.Sheaf J A
    c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
    i₀ : E.I₀
    ⊢ Eq (CategoryTheory.CategoryStruct.comp (CategoryTheory.GrothendieckTopology. …
  -/
  simp [multiforkLift]
  /-
    🎉 no goals
  -/


/-- If `E : J.OneHypercover S` and `F : Sheaf J A`, then `F.obj (op S)` is
a multiequalizer of suitable maps `F.obj (op (E.X i)) ⟶ F.obj (op (E.Y j))`
induced by `E.p₁ j` and `E.p₂ j`. -/
noncomputable def isLimitMultifork : IsLimit (E.multifork F.1) :=
  Multifork.IsLimit.mk _ (fun c => multiforkLift c) (fun c => multiforkLift_map c) (by
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      ⊢ ∀ (E_1 : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)) (m : Qu …
    -/
    intro c m hm
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      m : Quiver.Hom c.pt (E.multifork F.val).pt
      hm : ∀ (i : (E.multicospanIndex F.val).L), Eq (CategoryTheory.CategoryStruct.c …
      ⊢ Eq m ((fun c => CategoryTheory.GrothendieckTopology.OneHypercover.multiforkL …
    -/
    apply F.cond.hom_ext_ofArrows _ E.mem₀
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      m : Quiver.Hom c.pt (E.multifork F.val).pt
      hm : ∀ (i : (E.multicospanIndex F.val).L), Eq (CategoryTheory.CategoryStruct.c …
      ⊢ ∀ (i : E.I₀), Eq (CategoryTheory.CategoryStruct.comp m (F.val.map (E.f i).op …
    -/
    intro i₀
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      m : Quiver.Hom c.pt (E.multifork F.val).pt
      hm : ∀ (i : (E.multicospanIndex F.val).L), Eq (CategoryTheory.CategoryStruct.c …
      i₀ : E.I₀
      ⊢ Eq (CategoryTheory.CategoryStruct.comp m (F.val.map (E.f i₀).op)) (CategoryT …
    -/
    dsimp only
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      m : Quiver.Hom c.pt (E.multifork F.val).pt
      hm : ∀ (i : (E.multicospanIndex F.val).L), Eq (CategoryTheory.CategoryStruct.c …
      i₀ : E.I₀
      ⊢ Eq (CategoryTheory.CategoryStruct.comp m (F.val.map (E.f i₀).op)) (CategoryT …
    -/
    rw [multiforkLift_map]
    /-
      C : Type u
      inst✝¹ : CategoryTheory.Category.{v, u} C
      A : Type u_1
      inst✝ : CategoryTheory.Category.{?u.29319, u_1} A
      J : CategoryTheory.GrothendieckTopology C
      S : C
      E : J.OneHypercover S
      F : CategoryTheory.Sheaf J A
      c : CategoryTheory.Limits.Multifork (E.multicospanIndex F.val)
      m : Quiver.Hom c.pt (E.multifork F.val).pt
      hm : ∀ (i : (E.multicospanIndex F.val).L), Eq (CategoryTheory.CategoryStruct.c …
      i₀ : E.I₀
      ⊢ Eq (CategoryTheory.CategoryStruct.comp m (F.val.map (E.f i₀).op)) (c.ι i₀)
    -/
    exact hm i₀)
    /-
      🎉 no goals
    -/


/-- The tautological 1-pre-hypercover induced by `S : J.Cover X`. Its index type `I₀`
is given by `S.Arrow` (i.e. all the morphisms in the sieve `S`), while `I₁` is given
by all possible pullback cones. -/
@[simps]
def preOneHypercover : PreOneHypercover.{max u v} X where
  I₀ := S.Arrow
  X f := f.Y
  f f := f.f
  I₁ f₁ f₂ := f₁.Relation f₂
  Y _ _ r := r.Z
  p₁ _ _ r := r.g₁
  p₂ _ _ r := r.g₂
  w _ _ r := r.w


@[simp]
lemma preOneHypercover_sieve₀ : S.preOneHypercover.sieve₀ = S.1 := by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    X : C
    S : J.Cover X
    ⊢ Eq S.preOneHypercover.sieve₀ ↑S
  -/
  ext Y f
  /-
    case h
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    X : C
    S : J.Cover X
    Y : C
    f : Quiver.Hom Y X
    ⊢ Iff (S.preOneHypercover.sieve₀.arrows f) ((↑S).arrows f)
  -/
  constructor
    /-
      case h.mp
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      J : CategoryTheory.GrothendieckTopology C
      X : C
      S : J.Cover X
      Y : C
      f : Quiver.Hom Y X
      ⊢ S.preOneHypercover.sieve₀.arrows f → (↑S).arrows f
    -/
  · rintro ⟨_, _, _, ⟨g⟩, rfl⟩
    /-
      case h.mp.intro.intro.intro.intro.mk
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      J : CategoryTheory.GrothendieckTopology C
      X : C
      S : J.Cover X
      Y✝ Y : C
      g : S.preOneHypercover.I₀
      w✝ : Quiver.Hom Y✝ (S.preOneHypercover.X g)
      ⊢ (↑S).arrows (CategoryTheory.CategoryStruct.comp w✝ (S.preOneHypercover.f g))
    -/
    exact S.1.downward_closed g.hf _
    /-
      🎉 no goals
    -/
    /-
      case h.mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      J : CategoryTheory.GrothendieckTopology C
      X : C
      S : J.Cover X
      Y : C
      f : Quiver.Hom Y X
      ⊢ (↑S).arrows f → S.preOneHypercover.sieve₀.arrows f
    -/
  · intro hf
    /-
      case h.mpr
      C : Type u
      inst✝ : CategoryTheory.Category.{v, u} C
      J : CategoryTheory.GrothendieckTopology C
      X : C
      S : J.Cover X
      Y : C
      f : Quiver.Hom Y X
      hf : (↑S).arrows f
      ⊢ S.preOneHypercover.sieve₀.arrows f
    -/
    exact Sieve.ofArrows_mk _ _ ({ hf := hf } : S.Arrow)
    /-
      🎉 no goals
    -/


lemma preOneHypercover_sieve₁ (f₁ f₂ : S.Arrow) {W : C} (p₁ : W ⟶ f₁.Y) (p₂ : W ⟶ f₂.Y)
    (w : p₁ ≫ f₁.f = p₂ ≫ f₂.f) :
    S.preOneHypercover.sieve₁ p₁ p₂ = ⊤ := by
  /-
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    X : C
    S : J.Cover X
    f₁ f₂ : S.Arrow
    W : C
    p₁ : Quiver.Hom W f₁.Y
    p₂ : Quiver.Hom W f₂.Y
    w : Eq (CategoryTheory.CategoryStruct.comp p₁ f₁.f) (CategoryTheory.CategorySt …
    ⊢ Eq (S.preOneHypercover.sieve₁ p₁ p₂) Top.top
  -/
  ext Y f
  /-
    case h
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    X : C
    S : J.Cover X
    f₁ f₂ : S.Arrow
    W : C
    p₁ : Quiver.Hom W f₁.Y
    p₂ : Quiver.Hom W f₂.Y
    w : Eq (CategoryTheory.CategoryStruct.comp p₁ f₁.f) (CategoryTheory.CategorySt …
    Y : C
    f : Quiver.Hom Y W
    ⊢ Iff ((S.preOneHypercover.sieve₁ p₁ p₂).arrows f) (Top.top.arrows f)
  -/
  simp only [Sieve.top_apply, iff_true]
  /-
    case h
    C : Type u
    inst✝ : CategoryTheory.Category.{v, u} C
    J : CategoryTheory.GrothendieckTopology C
    X : C
    S : J.Cover X
    f₁ f₂ : S.Arrow
    W : C
    p₁ : Quiver.Hom W f₁.Y
    p₂ : Quiver.Hom W f₂.Y
    w : Eq (CategoryTheory.CategoryStruct.comp p₁ f₁.f) (CategoryTheory.CategorySt …
    Y : C
    f : Quiver.Hom Y W
    ⊢ (S.preOneHypercover.sieve₁ p₁ p₂).arrows f
  -/
  exact ⟨{ w := w}, f, rfl, rfl⟩
  /-
    🎉 no goals
  -/


/-- The tautological 1-hypercover induced by `S : J.Cover X`. Its index type `I₀`
is given by `S.Arrow` (i.e. all the morphisms in the sieve `S`), while `I₁` is given
by all possible pullback cones. -/
@[simps toPreOneHypercover]
def oneHypercover : J.OneHypercover X where
  toPreOneHypercover := S.preOneHypercover
             /-
               C : Type u
               inst✝¹ : CategoryTheory.Category.{v, u} C
               A : Type u_1
               inst✝ : CategoryTheory.Category.{?u.33176, u_1} A
               J : CategoryTheory.GrothendieckTopology C
               X : C
               S : J.Cover X
               ⊢ Membership.mem (J X) S.preOneHypercover.sieve₀
             -/
  mem₀ := by simp
             /-
               🎉 no goals
             -/
                             /-
                               C : Type u
                               inst✝¹ : CategoryTheory.Category.{v, u} C
                               A : Type u_1
                               inst✝ : CategoryTheory.Category.{?u.33176, u_1} A
                               J : CategoryTheory.GrothendieckTopology C
                               X : C
                               S : J.Cover X
                               f₁ f₂ : S.preOneHypercover.I₀
                               x✝ : C
                               p₁ : Quiver.Hom x✝ (S.preOneHypercover.X f₁)
                               p₂ : Quiver.Hom x✝ (S.preOneHypercover.X f₂)
                               w : Eq (CategoryTheory.CategoryStruct.comp p₁ (S.preOneHypercover.f f₁)) (Cate …
                               ⊢ Membership.mem (J x✝) (S.preOneHypercover.sieve₁ p₁ p₂)
                             -/
  mem₁ f₁ f₂ _ p₁ p₂ w := by simp [S.preOneHypercover_sieve₁ f₁ f₂ p₁ p₂ w]
                             /-
                               🎉 no goals
                             -/


