/-- Any injective polynomial map over an algebraic extension of a finite field is surjective. -/
theorem ax_grothendieck_of_locally_finite {ι K R : Type*} [Field K] [Finite K] [CommRing R]
    [Finite ι] [Algebra K R] [alg : Algebra.IsAlgebraic K R] (ps : ι → MvPolynomial ι R)
    (S : Set (ι → R))
    (hm : S.MapsTo (fun v i => eval v (ps i)) S)
    (hinj : S.InjOn (fun v i => eval v (ps i))) :
    S.SurjOn (fun v i => eval v (ps i)) S := by
  have is_int : ∀ x : R, IsIntegral K x := fun x => isAlgebraic_iff_isIntegral.1
    (alg.isAlgebraic x)
  classical
  intro v hvS
  cases nonempty_fintype ι
  /- `s` is the set of all coefficients of the polynomial, as well as all of
    the coordinates of `v`, the point I am trying to find the preimage of. -/
  let s : Finset R :=
    (Finset.biUnion (univ : Finset ι) fun i => (ps i).support.image fun x => coeff x (ps i)) ∪
      (univ : Finset ι).image v
  have hv : ∀ i, v i ∈ Algebra.adjoin K (s : Set R) := fun j =>
    Algebra.subset_adjoin (mem_union_right _ (mem_image.2 ⟨j, mem_univ _, rfl⟩))
  have hs₁ : ∀ (i : ι) (k : ι →₀ ℕ),
      k ∈ (ps i).support → coeff k (ps i) ∈ Algebra.adjoin K (s : Set R) :=
    fun i k hk => Algebra.subset_adjoin
      (mem_union_left _ (mem_biUnion.2 ⟨i, mem_univ _, mem_image_of_mem _ hk⟩))
  have := isNoetherian_adjoin_finset s fun x _ => is_int x
  have := Module.IsNoetherian.finite K (Algebra.adjoin K (s : Set R))
  have : Finite (Algebra.adjoin K (s : Set R)) := Module.finite_of_finite K
  -- The restriction of the polynomial map, `ps`, to the subalgebra generated by `s`
  let S' : Set (ι → Algebra.adjoin K (s : Set R)) :=
    (fun v => Subtype.val ∘ v) ⁻¹' S
  let res : S' → S' := fun x => ⟨fun i =>
    ⟨eval (fun j : ι => (x.1 j : R)) (ps i), eval_mem (hs₁ _) fun i => (x.1 i).2⟩,
      hm x.2⟩
  have hres_surj : Function.Surjective res := by
    rw [← Finite.injective_iff_surjective]
    intro x y hxy
    ext i
    simp only [Subtype.ext_iff, funext_iff] at hxy
    exact congr_fun (hinj x.2 y.2 (funext hxy)) i
  rcases hres_surj ⟨fun i => ⟨v i, hv i⟩, hvS⟩ with ⟨⟨w, hwS'⟩, hw⟩
  refine ⟨fun i => w i, hwS', ?_⟩
  simpa [Subtype.ext_iff, funext_iff] using hw


/-- The collection of first order formulas corresponding to the Ax-Grothendieck theorem. -/
noncomputable def genericPolyMapSurjOnOfInjOn [Finite ι]
    (φ : ring.Formula (α ⊕ ι))
    (mons : ι → Finset (ι →₀ ℕ)) : Language.ring.Sentence :=
  let l1 : ι → Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    fun i =>
      (termOfFreeCommRing (genericPolyMap mons i)).relabel
        (Sum.inl ∘ Sum.map id (fun i => (0, i)))
    =' (termOfFreeCommRing (genericPolyMap mons i)).relabel
        (Sum.inl ∘ Sum.map id (fun i => (1, i)))
  -- p(x) = p(y) as a formula
  let f1 : Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    iInf l1
  let l2 : ι → Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    fun i => .var (Sum.inl (Sum.inr (0, i))) =' .var (Sum.inl (Sum.inr (1, i)))
  -- x = y as a formula
  let f2 : Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    iInf l2
  let injOn : Language.ring.Formula (α ⊕ Σ i : ι, mons i) :=
    Formula.iAlls (Fin 2 × ι)
      (φ.relabel (Sum.map Sum.inl (fun i => (0, i))) ⟹
       φ.relabel (Sum.map Sum.inl (fun i => (1, i))) ⟹
        (f1.imp f2).relabel (fun x => (Equiv.sumAssoc _ _ _).symm (Sum.inr x)))
  let l3 : ι → Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    fun i => (termOfFreeCommRing (genericPolyMap mons i)).relabel
        (Sum.inl ∘ Sum.map id (fun i => (0, i))) ='
      .var (Sum.inl (Sum.inr (1, i)))
  let f3 : Language.ring.Formula ((Σ i : ι, mons i) ⊕ (Fin 2 × ι)) :=
    iInf l3
  let surjOn : Language.ring.Formula (α ⊕ Σ i : ι, mons i) :=
    Formula.iAlls ι
      (Formula.imp (φ.relabel (Sum.map Sum.inl id)) <|
        Formula.iExs ι <|
          ((φ.relabel (Sum.map Sum.inl (fun i => (0, i)))) ⊓
            (f3.relabel (fun x => (Equiv.sumAssoc _ _ _).symm (Sum.inr x)))).relabel
        (fun (i : (α ⊕ (Σ i : ι, mons i)) ⊕ (Fin 2 × ι)) =>
          show ((α ⊕ (Σ i : ι, mons i)) ⊕ ι) ⊕ ι
          from Sum.elim (Sum.inl ∘ Sum.inl)
            (fun i => if i.1 = 0 then Sum.inr i.2 else (Sum.inl (Sum.inr i.2))) i))
  let mapsTo : Language.ring.Formula (α ⊕ Σ i : ι, mons i) :=
    Formula.iAlls ι
      (Formula.imp (φ.relabel (Sum.map Sum.inl id))
        (φ.subst <| Sum.elim
          (fun a => .var (Sum.inl (Sum.inl a)))
          (fun i => (termOfFreeCommRing (genericPolyMap mons i)).relabel
            (fun i => (Equiv.sumAssoc _ _ _).symm (Sum.inr i)))))
  Formula.iAlls (α ⊕ Σ i : ι, mons i) ((mapsTo.imp <| injOn.imp <| surjOn).relabel Sum.inr)


theorem realize_genericPolyMapSurjOnOfInjOn
    [Fintype ι] (φ : ring.Formula (α ⊕ ι)) (mons : ι → Finset (ι →₀ ℕ)) :
    (K ⊨ genericPolyMapSurjOnOfInjOn φ mons) ↔
      ∀ (v : α → K) (p : { p : ι → MvPolynomial ι K // (∀ i, (p i).support ⊆ mons i) }),
        let f : (ι → K) → (ι → K) := fun v i => eval v (p.1 i)
        let S : Set (ι → K) := fun x => φ.Realize (Sum.elim v x)
        S.MapsTo f S → S.InjOn f → S.SurjOn f S := by
  classical
  have injOnAlt : ∀ {S : Set (ι → K)} (f : (ι → K) → (ι → K)),
      S.InjOn f ↔ ∀ x y, x ∈ S → y ∈ S → f x = f y → x = y := by
    simp [Set.InjOn]; tauto
  simp only [Sentence.Realize, Formula.Realize, genericPolyMapSurjOnOfInjOn, Formula.relabel,
    Function.comp_def, Sum.map, id_eq, Equiv.sumAssoc, Equiv.coe_fn_symm_mk, Sum.elim_inr,
    realize_iAlls, realize_imp, realize_relabel, Fin.natAdd_zero, realize_subst, realize_iInf,
    Finset.mem_univ, realize_bdEqual, Term.realize_relabel, true_imp_iff,
    Equiv.forall_congr_left (Equiv.curry (Fin 2) ι K), Equiv.curry_symm_apply, Function.uncurry,
    Fin.forall_fin_succ_pi, Fin.forall_fin_zero_pi, realize_iExs, realize_inf, Sum.forall_sum,
    Set.MapsTo, Set.mem_def, injOnAlt, funext_iff, Set.SurjOn, Set.image, setOf,
    Set.subset_def, Equiv.forall_congr_left (mvPolynomialSupportLEEquiv mons)]
  simp +singlePass only [← Sum.elim_comp_inl_inr]
  -- was `simp` and very slow (https://github.com/leanprover-community/mathlib4/issues/19751)
  simp only [Function.comp_def, Sum.elim_inl, Sum.elim_inr, Fin.castAdd_zero, Fin.cast_eq_self,
    Nat.add_zero, Term.realize_var, Term.realize_relabel, realize_termOfFreeCommRing,
    lift_genericPolyMap, Nat.reduceAdd, Fin.isValue, Function.uncurry_apply_pair, Fin.cons_zero,
    Fin.cons_one, ↓reduceIte, one_ne_zero]


theorem ACF_models_genericPolyMapSurjOnOfInjOn_of_prime [Fintype ι]
    {p : ℕ} (hp : p.Prime) (φ : ring.Formula (α ⊕ ι)) (mons : ι → Finset (ι →₀ ℕ)) :
    Theory.ACF p ⊨ᵇ genericPolyMapSurjOnOfInjOn φ mons := by
  classical
  have : Fact p.Prime := ⟨hp⟩
  letI := compatibleRingOfRing (AlgebraicClosure (ZMod p))
  have : CharP (AlgebraicClosure (ZMod p)) p :=
    charP_of_injective_algebraMap
      (RingHom.injective (algebraMap (ZMod p) (AlgebraicClosure (ZMod p)))) p
  rw [← (ACF_isComplete (Or.inl hp)).realize_sentence_iff _
    (AlgebraicClosure (ZMod p)), realize_genericPolyMapSurjOnOfInjOn]
  rintro v ⟨f, _⟩
  exact ax_grothendieck_of_locally_finite (K := ZMod p) (ι := ι) f _


theorem ACF_models_genericPolyMapSurjOnOfInjOn_of_prime_or_zero
    [Fintype ι] {p : ℕ} (hp : p.Prime ∨ p = 0)
    (φ : ring.Formula (α ⊕ ι)) (mons : ι → Finset (ι →₀ ℕ)) :
    Theory.ACF p ⊨ᵇ genericPolyMapSurjOnOfInjOn φ mons := by
  /-
    ι : Type u_1
    α : Type u_2
    inst✝¹ : Finite α
    inst✝ : Fintype ι
    p : Nat
    hp : Or (Nat.Prime p) (Eq p 0)
    φ : FirstOrder.Language.ring.Formula (Sum α ι)
    mons : ι → Finset (Finsupp ι Nat)
    ⊢ (FirstOrder.Language.Theory.ACF p).ModelsBoundedFormula (FirstOrder.genericP …
  -/
  rcases hp with hp | rfl
    /-
      case inl
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      p : Nat
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      hp : Nat.Prime p
      ⊢ (FirstOrder.Language.Theory.ACF p).ModelsBoundedFormula (FirstOrder.genericP …
    -/
  · exact ACF_models_genericPolyMapSurjOnOfInjOn_of_prime hp φ mons
    /-
      🎉 no goals
    -/
    /-
      case inr
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      ⊢ (FirstOrder.Language.Theory.ACF 0).ModelsBoundedFormula (FirstOrder.genericP …
    -/
  · rw [ACF_zero_realize_iff_infinite_ACF_prime_realize]
    /-
      case inr
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      ⊢ (setOf fun p => (FirstOrder.Language.Theory.ACF ↑p).ModelsBoundedFormula (Fi …
    -/
    convert Set.infinite_univ (α := Nat.Primes)
    /-
      case h.e'_2
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      ⊢ Eq (setOf fun p => (FirstOrder.Language.Theory.ACF ↑p).ModelsBoundedFormula  …
    -/
    rw [Set.eq_univ_iff_forall]
    /-
      case h.e'_2
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      ⊢ ∀ (x : Nat.Primes), Membership.mem (setOf fun p => (FirstOrder.Language.Theo …
    -/
    intro ⟨p, hp⟩
    /-
      case h.e'_2
      ι : Type u_1
      α : Type u_2
      inst✝¹ : Finite α
      inst✝ : Fintype ι
      φ : FirstOrder.Language.ring.Formula (Sum α ι)
      mons : ι → Finset (Finsupp ι Nat)
      p : Nat
      hp : Nat.Prime p
      ⊢ Membership.mem (setOf fun p => (FirstOrder.Language.Theory.ACF ↑p).ModelsBou …
    -/
    exact ACF_models_genericPolyMapSurjOnOfInjOn_of_prime hp φ mons
    /-
      🎉 no goals
    -/


/-- A slight generalization of the **Ax-Grothendieck** theorem

If `K` is an algebraically closed field, `ι` is a finite type, and `S` is a definable subset of
`ι → K`, then any injective polynomial map `S → S`  is also surjective on `S`. -/
theorem ax_grothendieck_of_definable [CompatibleRing K] {c : Set K}
    (S : Set (ι → K)) (hS : c.Definable Language.ring S)
    (ps : ι → MvPolynomial ι K) :
    S.MapsTo (fun v i => eval v (ps i)) S →
    S.InjOn (fun v i => eval v (ps i)) →
    S.SurjOn (fun v i => eval v (ps i)) S := by
  /-
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c : Set K
    S : Set (ι → K)
    hS : c.Definable FirstOrder.Language.ring S
    ps : ι → MvPolynomial ι K
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  letI := Fintype.ofFinite ι
  /-
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c : Set K
    S : Set (ι → K)
    hS : c.Definable FirstOrder.Language.ring S
    ps : ι → MvPolynomial ι K
    this : Fintype ι := Fintype.ofFinite ι
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  let p : ℕ := ringChar K
  /-
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c : Set K
    S : Set (ι → K)
    hS : c.Definable FirstOrder.Language.ring S
    ps : ι → MvPolynomial ι K
    this : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  have : CharP K p := ⟨ringChar.spec K⟩
  /-
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c : Set K
    S : Set (ι → K)
    hS : c.Definable FirstOrder.Language.ring S
    ps : ι → MvPolynomial ι K
    this✝ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this : CharP K p
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  rw [Set.definable_iff_finitely_definable] at hS
  /-
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c : Set K
    S : Set (ι → K)
    hS : Exists fun A0 => And (HasSubset.Subset (↑A0) c) ((↑A0).Definable FirstOrd …
    ps : ι → MvPolynomial ι K
    this✝ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this : CharP K p
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  rcases hS with ⟨c, _, hS⟩
  /-
    case intro.intro
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c✝ : Set K
    S : Set (ι → K)
    ps : ι → MvPolynomial ι K
    this✝ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this : CharP K p
    c : Finset K
    left✝ : HasSubset.Subset (↑c) c✝
    hS : (↑c).Definable FirstOrder.Language.ring S
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  rw [Set.definable_iff_exists_formula_sum] at hS
  /-
    case intro.intro
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c✝ : Set K
    S : Set (ι → K)
    ps : ι → MvPolynomial ι K
    this✝ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this : CharP K p
    c : Finset K
    left✝ : HasSubset.Subset (↑c) c✝
    hS : Exists fun φ => Eq S (setOf fun v => φ.Realize (Sum.elim Subtype.val v))
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  rcases hS with ⟨φ, hφ⟩
  /-
    case intro.intro.intro
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c✝ : Set K
    S : Set (ι → K)
    ps : ι → MvPolynomial ι K
    this✝ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this : CharP K p
    c : Finset K
    left✝ : HasSubset.Subset (↑c) c✝
    φ : FirstOrder.Language.ring.Formula (Sum (↑↑c) ι)
    hφ : Eq S (setOf fun v => φ.Realize (Sum.elim Subtype.val v))
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) S S → Set.InjOn (fun v  …
  -/
  rw [hφ]
  have := ACF_models_genericPolyMapSurjOnOfInjOn_of_prime_or_zero
    (CharP.char_is_prime_or_zero K p) φ (fun i => (ps i).support)
  rw [← (ACF_isComplete (CharP.char_is_prime_or_zero K p)).realize_sentence_iff _ K,
    realize_genericPolyMapSurjOnOfInjOn] at this
  /-
    case intro.intro.intro
    K : Type u_1
    ι : Type u_2
    inst✝³ : Field K
    inst✝² : IsAlgClosed K
    inst✝¹ : Finite ι
    inst✝ : FirstOrder.Ring.CompatibleRing K
    c✝ : Set K
    S : Set (ι → K)
    ps : ι → MvPolynomial ι K
    this✝¹ : Fintype ι := Fintype.ofFinite ι
    p : Nat := ringChar K
    this✝ : CharP K p
    c : Finset K
    left✝ : HasSubset.Subset (↑c) c✝
    φ : FirstOrder.Language.ring.Formula (Sum (↑↑c) ι)
    hφ : Eq S (setOf fun v => φ.Realize (Sum.elim Subtype.val v))
    this :
      ∀ (v : ↑↑c → K) (p : Subtype fun p => ∀ (i : ι), HasSubset.Subset (p i).supp …
        let f := fun v i => (MvPolynomial.eval v) (↑p i);
        let S := fun x => φ.Realize (Sum.elim v x);
        Set.MapsTo f S S → Set.InjOn f S → Set.SurjOn f S S
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (ps i)) (setOf fun v => φ.Reali …
  -/
  exact this Subtype.val ⟨ps, fun i => Set.Subset.refl _⟩
  /-
    🎉 no goals
  -/


/-- The **Ax-Grothendieck** theorem

If `K` is an algebraically closed field, and `S : Set (ι → K)` is the `zeroLocus` of an ideal
of the multivariable polynomial ring, then any injective polynomial map `S → S`  is also
surjective on `S`. -/
theorem ax_grothendieck_zeroLocus
    (I : Ideal (MvPolynomial ι K))
    (p : ι → MvPolynomial ι K) :
    let S := zeroLocus I
    S.MapsTo (fun v i => eval v (p i)) S →
    S.InjOn (fun v i => eval v (p i)) →
    S.SurjOn (fun v i => eval v (p i)) S := by
  /-
    K : Type u_1
    ι : Type u_2
    inst✝² : Field K
    inst✝¹ : IsAlgClosed K
    inst✝ : Finite ι
    I : Ideal (MvPolynomial ι K)
    p : ι → MvPolynomial ι K
    ⊢ let S := MvPolynomial.zeroLocus I;
      Set.MapsTo (fun v i => (MvPolynomial.eval v) (p i)) S S → Set.InjOn (fun v i …
  -/
  letI := compatibleRingOfRing K
  /-
    K : Type u_1
    ι : Type u_2
    inst✝² : Field K
    inst✝¹ : IsAlgClosed K
    inst✝ : Finite ι
    I : Ideal (MvPolynomial ι K)
    p : ι → MvPolynomial ι K
    this : FirstOrder.Ring.CompatibleRing K := FirstOrder.Ring.compatibleRingOfRin …
    ⊢ let S := MvPolynomial.zeroLocus I;
      Set.MapsTo (fun v i => (MvPolynomial.eval v) (p i)) S S → Set.InjOn (fun v i …
  -/
  intro S
  /-
    K : Type u_1
    ι : Type u_2
    inst✝² : Field K
    inst✝¹ : IsAlgClosed K
    inst✝ : Finite ι
    I : Ideal (MvPolynomial ι K)
    p : ι → MvPolynomial ι K
    this : FirstOrder.Ring.CompatibleRing K := FirstOrder.Ring.compatibleRingOfRin …
    S : Set (ι → K) := MvPolynomial.zeroLocus I
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (p i)) S S → Set.InjOn (fun v i …
  -/
  obtain ⟨s, rfl⟩ : I.FG := IsNoetherian.noetherian I
  /-
    case intro
    K : Type u_1
    ι : Type u_2
    inst✝² : Field K
    inst✝¹ : IsAlgClosed K
    inst✝ : Finite ι
    p : ι → MvPolynomial ι K
    this : FirstOrder.Ring.CompatibleRing K := FirstOrder.Ring.compatibleRingOfRin …
    s : Finset (MvPolynomial ι K)
    S : Set (ι → K) := MvPolynomial.zeroLocus (Ideal.span ↑s)
    ⊢ Set.MapsTo (fun v i => (MvPolynomial.eval v) (p i)) S S → Set.InjOn (fun v i …
  -/
  exact ax_grothendieck_of_definable S (mvPolynomial_zeroLocus_definable s) p
  /-
    🎉 no goals
  -/


/-- A special case of the **Ax-Grothendieck** theorem

Any injective polynomial map `K^n → K^n` is also surjective if `K` is an
algberaically closed field. -/
theorem ax_grothendieck_univ (p : ι → MvPolynomial ι K) :
    (fun v i => eval v (p i)).Injective →
    (fun v i => eval v (p i)).Surjective := by
  simpa [Set.injective_iff_injOn_univ, Set.surjective_iff_surjOn_univ] using
      ax_grothendieck_zeroLocus 0 p

