instance instTopologicalSemiring (s : NonUnitalStarSubalgebra R A) : TopologicalSemiring s :=
  s.toNonUnitalSubalgebra.instTopologicalSemiring


/-- The (topological) closure of a non-unital star subalgebra of a non-unital topological star
algebra is itself a non-unital star subalgebra. -/
def topologicalClosure (s : NonUnitalStarSubalgebra R A) : NonUnitalStarSubalgebra R A :=
  { s.toNonUnitalSubalgebra.topologicalClosure with
    star_mem' := fun h ↦ map_mem_closure continuous_star h fun _ ↦ star_mem
    carrier := _root_.closure (s : Set A) }


theorem le_topologicalClosure (s : NonUnitalStarSubalgebra R A) : s ≤ s.topologicalClosure :=
  subset_closure


theorem isClosed_topologicalClosure (s : NonUnitalStarSubalgebra R A) :
    IsClosed (s.topologicalClosure : Set A) := isClosed_closure


theorem topologicalClosure_minimal (s : NonUnitalStarSubalgebra R A)
    {t : NonUnitalStarSubalgebra R A} (h : s ≤ t) (ht : IsClosed (t : Set A)) :
    s.topologicalClosure ≤ t :=
  closure_minimal h ht


/-- If a non-unital star subalgebra of a non-unital topological star algebra is commutative, then
so is its topological closure.

See note [reducible non-instances] -/
abbrev nonUnitalCommSemiringTopologicalClosure [T2Space A] (s : NonUnitalStarSubalgebra R A)
    (hs : ∀ x y : s, x * y = y * x) : NonUnitalCommSemiring s.topologicalClosure :=
  s.toNonUnitalSubalgebra.nonUnitalCommSemiringTopologicalClosure hs


instance instTopologicalRing (s : NonUnitalStarSubalgebra R A) : TopologicalRing s :=
  s.toNonUnitalSubring.instTopologicalRing


/-- If a non-unital star subalgebra of a non-unital topological star algebra is commutative, then
so is its topological closure.

See note [reducible non-instances]. -/
abbrev nonUnitalCommRingTopologicalClosure [T2Space A] (s : NonUnitalStarSubalgebra R A)
    (hs : ∀ x y : s, x * y = y * x) : NonUnitalCommRing s.topologicalClosure :=
  { s.topologicalClosure.toNonUnitalRing, s.toSubsemigroup.commSemigroupTopologicalClosure hs with }


/-- The topological closure of the non-unital star subalgebra generated by a single element. -/
def elemental (x : A) : NonUnitalStarSubalgebra R A :=
  adjoin R {x} |>.topologicalClosure


@[aesop safe apply (rule_sets := [SetLike])]
theorem self_mem (x : A) : x ∈ elemental R x :=
  le_topologicalClosure _ <| self_mem_adjoin_singleton R x


@[aesop safe apply (rule_sets := [SetLike])]
theorem star_self_mem (x : A) : star x ∈ elemental R x :=
  le_topologicalClosure _ <| star_self_mem_adjoin_singleton R x


variable {R} in
theorem le_of_mem {x : A} {s : NonUnitalStarSubalgebra R A} (hs : IsClosed (s : Set A))
    (hx : x ∈ s) : elemental R x ≤ s :=
                                                /-
                                                  R : Type u_1
                                                  A : Type u_2
                                                  inst✝¹¹ : CommSemiring R
                                                  inst✝¹⁰ : StarRing R
                                                  inst✝⁹ : NonUnitalSemiring A
                                                  inst✝⁸ : StarRing A
                                                  inst✝⁷ : Module R A
                                                  inst✝⁶ : IsScalarTower R A A
                                                  inst✝⁵ : SMulCommClass R A A
                                                  inst✝⁴ : StarModule R A
                                                  inst✝³ : TopologicalSpace A
                                                  inst✝² : TopologicalSemiring A
                                                  inst✝¹ : ContinuousConstSMul R A
                                                  inst✝ : ContinuousStar A
                                                  x : A
                                                  s : NonUnitalStarSubalgebra R A
                                                  hs : IsClosed ↑s
                                                  hx : Membership.mem s x
                                                  ⊢ HasSubset.Subset (Singleton.singleton x) ↑s
                                                -/
  topologicalClosure_minimal _ (adjoin_le <| by simpa using hx) hs
                                                /-
                                                  🎉 no goals
                                                -/


variable {R} in
theorem le_iff_mem {x : A} {s : NonUnitalStarSubalgebra R A} (hs : IsClosed (s : Set A)) :
    elemental R x ≤ s ↔ x ∈ s :=
  ⟨fun h ↦ h (self_mem R x), fun h ↦ le_of_mem hs h⟩


instance isClosed (x : A) : IsClosed (elemental R x : Set A) :=
  isClosed_topologicalClosure _


instance [T2Space A] {x : A} [IsStarNormal x] : NonUnitalCommSemiring (elemental R x) :=
  nonUnitalCommSemiringTopologicalClosure _ <| by
    letI : NonUnitalCommSemiring (adjoin R {x}) := by
      refine NonUnitalStarAlgebra.adjoinNonUnitalCommSemiringOfComm R ?_ ?_
      all_goals
        intro y hy z hz
        rw [Set.mem_singleton_iff] at hy hz
        rw [hy, hz]
      exact (star_comm_self' x).symm
    /-
      R : Type u_1
      A : Type u_2
      inst✝¹³ : CommSemiring R
      inst✝¹² : StarRing R
      inst✝¹¹ : NonUnitalSemiring A
      inst✝¹⁰ : StarRing A
      inst✝⁹ : Module R A
      inst✝⁸ : IsScalarTower R A A
      inst✝⁷ : SMulCommClass R A A
      inst✝⁶ : StarModule R A
      inst✝⁵ : TopologicalSpace A
      inst✝⁴ : TopologicalSemiring A
      inst✝³ : ContinuousConstSMul R A
      inst✝² : ContinuousStar A
      inst✝¹ : T2Space A
      x : A
      inst✝ : IsStarNormal x
      this : NonUnitalCommSemiring (Subtype fun x_1 => Membership.mem (NonUnitalStar …
      ⊢ ∀ (x_1 y : Subtype fun x_2 => Membership.mem (NonUnitalStarAlgebra.adjoin R  …
    -/
    exact fun _ _ => mul_comm _ _
    /-
      🎉 no goals
    -/


instance {R A : Type*} [CommRing R] [StarRing R] [NonUnitalRing A] [StarRing A]
    [Module R A] [IsScalarTower R A A] [SMulCommClass R A A] [StarModule R A]
    [TopologicalSpace A] [TopologicalRing A] [ContinuousConstSMul R A] [ContinuousStar A]
    [T2Space A] {x : A} [IsStarNormal x] : NonUnitalCommRing (elemental R x) where
  mul_comm := mul_comm


instance {A : Type*} [UniformSpace A] [CompleteSpace A] [NonUnitalSemiring A] [StarRing A]
    [TopologicalSemiring A] [ContinuousStar A] [Module R A] [IsScalarTower R A A]
    [SMulCommClass R A A] [StarModule R A] [ContinuousConstSMul R A] (x : A) :
    CompleteSpace (elemental R x) :=
  isClosed_closure.completeSpace_coe


/-- The coercion from an elemental algebra to the full algebra is a `IsClosedEmbedding`. -/
theorem isClosedEmbedding_coe (x : A) : Topology.IsClosedEmbedding ((↑) : elemental R x → A) where
  eq_induced := rfl
  injective := Subtype.coe_injective
                       /-
                         R : Type u_1
                         A : Type u_2
                         inst✝¹¹ : CommSemiring R
                         inst✝¹⁰ : StarRing R
                         inst✝⁹ : NonUnitalSemiring A
                         inst✝⁸ : StarRing A
                         inst✝⁷ : Module R A
                         inst✝⁶ : IsScalarTower R A A
                         inst✝⁵ : SMulCommClass R A A
                         inst✝⁴ : StarModule R A
                         inst✝³ : TopologicalSpace A
                         inst✝² : TopologicalSemiring A
                         inst✝¹ : ContinuousConstSMul R A
                         inst✝ : ContinuousStar A
                         x : A
                         ⊢ IsClosed (Set.range Subtype.val)
                       -/
  isClosed_range := by simpa using isClosed R x
                       /-
                         🎉 no goals
                       -/


