/-- Transfinite induction construction of the sigma-algebra generated by a set of sets `s`. At each
step, we add all elements of `s`, the empty set, the complements of already constructed sets, and
countable unions of already constructed sets.

We index this construction by an arbitrary ordinal for simplicity, but by `ω₁` we will have
generated all the sets in the sigma-algebra.

This construction is very similar to that of the Borel hierarchy. -/
def generateMeasurableRec (s : Set (Set α)) (i : Ordinal) : Set (Set α) :=
  let S := ⋃ j < i, generateMeasurableRec s j
  s ∪ {∅} ∪ compl '' S ∪ Set.range fun f : ℕ → S => ⋃ n, (f n).1
termination_by i


theorem self_subset_generateMeasurableRec (s : Set (Set α)) (i : Ordinal) :
    s ⊆ generateMeasurableRec s i := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ HasSubset.Subset s (MeasurableSpace.generateMeasurableRec s i)
  -/
  unfold generateMeasurableRec
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ HasSubset.Subset s
        (let S := Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generate …
        Union.union (Union.union (Union.union s (Singleton.singleton EmptyCollecti …
  -/
  apply_rules [subset_union_of_subset_left]
  /-
    case h.h.h
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ HasSubset.Subset s s
  -/
  exact subset_rfl
  /-
    🎉 no goals
  -/


theorem empty_mem_generateMeasurableRec (s : Set (Set α)) (i : Ordinal) :
    ∅ ∈ generateMeasurableRec s i := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s i) EmptyCollection.e …
  -/
  unfold generateMeasurableRec
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ Membership.mem
        (let S := Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generate …
        Union.union (Union.union (Union.union s (Singleton.singleton EmptyCollecti …
        EmptyCollection.emptyCollection
  -/
  exact mem_union_left _ (mem_union_left _ (mem_union_right _ (mem_singleton ∅)))
  /-
    🎉 no goals
  -/


theorem compl_mem_generateMeasurableRec {s : Set (Set α)} {i j : Ordinal} (h : j < i) {t : Set α}
    (ht : t ∈ generateMeasurableRec s j) : tᶜ ∈ generateMeasurableRec s i := by
  /-
    α : Type u
    s : Set (Set α)
    i j : Ordinal.{u_1}
    h : LT.lt j i
    t : Set α
    ht : Membership.mem (MeasurableSpace.generateMeasurableRec s j) t
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s i) (HasCompl.compl t)
  -/
  unfold generateMeasurableRec
  /-
    α : Type u
    s : Set (Set α)
    i j : Ordinal.{u_1}
    h : LT.lt j i
    t : Set α
    ht : Membership.mem (MeasurableSpace.generateMeasurableRec s j) t
    ⊢ Membership.mem
        (let S := Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generate …
        Union.union (Union.union (Union.union s (Singleton.singleton EmptyCollecti …
        (HasCompl.compl t)
  -/
  exact mem_union_left _ (mem_union_right _ ⟨t, mem_iUnion₂.2 ⟨j, h, ht⟩, rfl⟩)
  /-
    🎉 no goals
  -/


theorem iUnion_mem_generateMeasurableRec {s : Set (Set α)} {i : Ordinal} {f : ℕ → Set α}
    (hf : ∀ n, ∃ j < i, f n ∈ generateMeasurableRec s j) :
    ⋃ n, f n ∈ generateMeasurableRec s i := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    f : Nat → Set α
    hf : ∀ (n : Nat), Exists fun j => And (LT.lt j i) (Membership.mem (MeasurableS …
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s i) (Set.iUnion fun n …
  -/
  unfold generateMeasurableRec
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    f : Nat → Set α
    hf : ∀ (n : Nat), Exists fun j => And (LT.lt j i) (Membership.mem (MeasurableS …
    ⊢ Membership.mem
        (let S := Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generate …
        Union.union (Union.union (Union.union s (Singleton.singleton EmptyCollecti …
        (Set.iUnion fun n => f n)
  -/
  exact mem_union_right _ ⟨fun n => ⟨f n, let ⟨j, hj, hf⟩ := hf n; mem_iUnion₂.2 ⟨j, hj, hf⟩⟩, rfl⟩
  /-
    🎉 no goals
  -/


theorem generateMeasurableRec_mono (s : Set (Set α)) : Monotone (generateMeasurableRec s) := by
  /-
    α : Type u
    s : Set (Set α)
    ⊢ Monotone (MeasurableSpace.generateMeasurableRec s)
  -/
  intro i j h x hx
  /-
    α : Type u
    s : Set (Set α)
    i j : Ordinal.{u_1}
    h : LE.le i j
    x : Set α
    hx : Membership.mem (MeasurableSpace.generateMeasurableRec s i) x
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s j) x
  -/
  rcases h.eq_or_lt with (rfl | h)
    /-
      case inl
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      x : Set α
      hx : Membership.mem (MeasurableSpace.generateMeasurableRec s i) x
      h : LE.le i i
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s i) x
    -/
  · exact hx
    /-
      🎉 no goals
    -/
    /-
      case inr
      α : Type u
      s : Set (Set α)
      i j : Ordinal.{u_1}
      h✝ : LE.le i j
      x : Set α
      hx : Membership.mem (MeasurableSpace.generateMeasurableRec s i) x
      h : LT.lt i j
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s j) x
    -/
  · convert iUnion_mem_generateMeasurableRec fun _ => ⟨i, h, hx⟩
    /-
      case h.e'_5
      α : Type u
      s : Set (Set α)
      i j : Ordinal.{u_1}
      h✝ : LE.le i j
      x : Set α
      hx : Membership.mem (MeasurableSpace.generateMeasurableRec s i) x
      h : LT.lt i j
      ⊢ Eq x (Set.iUnion fun n => x)
    -/
    exact (iUnion_const x).symm
    /-
      🎉 no goals
    -/


/-- An inductive principle for the elements of `generateMeasurableRec`. -/
@[elab_as_elim]
theorem generateMeasurableRec_induction {s : Set (Set α)} {i : Ordinal} {t : Set α}
    {p : Set α → Prop} (hs : ∀ t ∈ s, p t) (h0 : p ∅)
    (hc : ∀ u, p u → (∃ j < i, u ∈ generateMeasurableRec s j) → p uᶜ)
    (hn : ∀ f : ℕ → Set α,
      (∀ n, p (f n) ∧ ∃ j < i, f n ∈ generateMeasurableRec s j) → p (⋃ n, f n)) :
    t ∈ generateMeasurableRec s i → p t := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s i) t → p t
  -/
  suffices H : ∀ k ≤ i, ∀ t ∈ generateMeasurableRec s k, p t from H i le_rfl t
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    ⊢ ∀ (k : Ordinal.{u_1}), LE.le k i → ∀ (t : Set α), Membership.mem (Measurable …
  -/
  intro k
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    k : Ordinal.{u_1}
    ⊢ LE.le k i → ∀ (t : Set α), Membership.mem (MeasurableSpace.generateMeasurabl …
  -/
  apply WellFoundedLT.induction k
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    k : Ordinal.{u_1}
    ⊢ ∀ (x : Ordinal.{u_1}), (∀ (y : Ordinal.{u_1}), LT.lt y x → LE.le y i → ∀ (t  …
  -/
  intro k IH hk t
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t✝ : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    k✝ k : Ordinal.{u_1}
    IH : ∀ (y : Ordinal.{u_1}), LT.lt y k → LE.le y i → ∀ (t : Set α), Membership. …
    hk : LE.le k i
    t : Set α
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s k) t → p t
  -/
  replace IH := fun j hj => IH j hj (hj.le.trans hk)
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t✝ : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    k✝ k : Ordinal.{u_1}
    hk : LE.le k i
    t : Set α
    IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s k) t → p t
  -/
  unfold generateMeasurableRec
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    t✝ : Set α
    p : Set α → Prop
    hs : ∀ (t : Set α), Membership.mem s t → p t
    h0 : p EmptyCollection.emptyCollection
    hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
    hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
    k✝ k : Ordinal.{u_1}
    hk : LE.le k i
    t : Set α
    IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
    ⊢ Membership.mem
          (let S := Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.genera …
          Union.union (Union.union (Union.union s (Singleton.singleton EmptyCollec …
          t →
        p t
  -/
  rintro (((ht | rfl) | ht) | ⟨f, rfl⟩)
    /-
      case inl.inl.inl
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t✝ : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      t : Set α
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      ht : Membership.mem s t
      ⊢ p t
    -/
  · exact hs t ht
    /-
      🎉 no goals
    -/
    /-
      case inl.inl.inr
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      ⊢ p EmptyCollection.emptyCollection
    -/
  · exact h0
    /-
      🎉 no goals
    -/
    /-
      case inl.inr
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t✝ : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      t : Set α
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      ht : Membership.mem (Set.image HasCompl.compl (Set.iUnion fun j => Set.iUnion  …
      ⊢ p t
    -/
  · simp_rw [mem_image, mem_iUnion₂] at ht
    /-
      case inl.inr
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t✝ : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      t : Set α
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      ht : Exists fun x => And (Exists fun i => Exists fun j => Membership.mem (Meas …
      ⊢ p t
    -/
    obtain ⟨u, ⟨⟨j, hj, hj'⟩, rfl⟩⟩ := ht
    /-
      case inl.inr.intro.intro.intro.intro
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      u : Set α
      j : Ordinal.{u_1}
      hj : LT.lt j k
      hj' : Membership.mem (MeasurableSpace.generateMeasurableRec s j) u
      ⊢ p (HasCompl.compl u)
    -/
    exact hc u (IH j hj u hj') ⟨j, hj.trans_le hk, hj'⟩
    /-
      🎉 no goals
    -/
    /-
      case inr.intro
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      f : Nat → ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generateMe …
      ⊢ p ((fun f => Set.iUnion fun n => ↑(f n)) f)
    -/
  · apply hn
    /-
      case inr.intro.a
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      f : Nat → ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generateMe …
      ⊢ ∀ (n : Nat), And (p ↑(f n)) (Exists fun j => And (LT.lt j i) (Membership.mem …
    -/
    intro n
    /-
      case inr.intro.a
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      f : Nat → ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generateMe …
      n : Nat
      ⊢ And (p ↑(f n)) (Exists fun j => And (LT.lt j i) (Membership.mem (MeasurableS …
    -/
    obtain ⟨j, hj, hj'⟩ := mem_iUnion₂.1 (f n).2
    /-
      case inr.intro.a.intro.intro
      α : Type u
      s : Set (Set α)
      i : Ordinal.{u_1}
      t : Set α
      p : Set α → Prop
      hs : ∀ (t : Set α), Membership.mem s t → p t
      h0 : p EmptyCollection.emptyCollection
      hc : ∀ (u : Set α), p u → (Exists fun j => And (LT.lt j i) (Membership.mem (Me …
      hn : ∀ (f : Nat → Set α), (∀ (n : Nat), And (p (f n)) (Exists fun j => And (LT …
      k✝ k : Ordinal.{u_1}
      hk : LE.le k i
      IH : ∀ (j : Ordinal.{u_1}), LT.lt j k → ∀ (t : Set α), Membership.mem (Measura …
      f : Nat → ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpace.generateMe …
      n : Nat
      j : Ordinal.{u_1}
      hj : LT.lt j k
      hj' : Membership.mem (MeasurableSpace.generateMeasurableRec s j) ↑(f n)
      ⊢ And (p ↑(f n)) (Exists fun j => And (LT.lt j i) (Membership.mem (MeasurableS …
    -/
    use IH j hj _ hj', j, hj.trans_le hk
    /-
      🎉 no goals
    -/


theorem generateMeasurableRec_omega1 (s : Set (Set α)) :
    generateMeasurableRec s (ω₁ : Ordinal.{v}) =
      ⋃ i < (ω₁ : Ordinal.{v}), generateMeasurableRec s i := by
  /-
    α : Type u
    s : Set (Set α)
    ⊢ Eq (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) (Set.iUnion f …
  -/
  apply (iUnion₂_subset fun i h => generateMeasurableRec_mono s h.le).antisymm'
  /-
    α : Type u
    s : Set (Set α)
    ⊢ HasSubset.Subset (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) …
  -/
  intro t ht
  /-
    α : Type u
    s : Set (Set α)
    t : Set α
    ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
    ⊢ Membership.mem (Set.iUnion fun i => Set.iUnion fun j => MeasurableSpace.gene …
  -/
  rw [mem_iUnion₂]
  /-
    α : Type u
    s : Set (Set α)
    t : Set α
    ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
    ⊢ Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
  -/
  refine generateMeasurableRec_induction ?_ ?_ ?_ ?_ ht
    /-
      case refine_1
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      ⊢ ∀ (t : Set α), Membership.mem s t → Exists fun i => Exists fun j => Membersh …
    -/
  · intro t ht
    /-
      case refine_1
      α : Type u
      s : Set (Set α)
      t✝ : Set α
      ht✝ : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1 …
      t : Set α
      ht : Membership.mem s t
      ⊢ Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
    -/
    exact ⟨0, omega_pos 1, self_subset_generateMeasurableRec s 0 ht⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_2
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      ⊢ Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
    -/
  · exact ⟨0, omega_pos 1, empty_mem_generateMeasurableRec s 0⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_3
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      ⊢ ∀ (u : Set α), (Exists fun i => Exists fun j => Membership.mem (MeasurableSp …
    -/
  · rintro u - ⟨j, hj, hj'⟩
    exact ⟨_, (isLimit_omega 1).succ_lt hj,
      compl_mem_generateMeasurableRec (Order.lt_succ j) hj'⟩
    /-
      case refine_4
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      ⊢ ∀ (f : Nat → Set α), (∀ (n : Nat), And (Exists fun i => Exists fun j => Memb …
    -/
  · intro f H
    /-
      case refine_4
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      f : Nat → Set α
      H : ∀ (n : Nat), And (Exists fun i => Exists fun j => Membership.mem (Measurab …
      ⊢ Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
    -/
    choose I hI using fun n => (H n).1
    /-
      case refine_4
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      f : Nat → Set α
      H : ∀ (n : Nat), And (Exists fun i => Exists fun j => Membership.mem (Measurab …
      I : Nat → Ordinal.{v}
      hI : ∀ (n : Nat), Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
      ⊢ Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateMeas …
    -/
    simp_rw [exists_prop] at hI
    refine ⟨_, Ordinal.lsub_lt_ord_lift ?_ fun n => (hI n).1,
      iUnion_mem_generateMeasurableRec fun n => ⟨_, Ordinal.lt_lsub I n, (hI n).2⟩⟩
    /-
      case refine_4
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      f : Nat → Set α
      H : ∀ (n : Nat), And (Exists fun i => Exists fun j => Membership.mem (Measurab …
      I : Nat → Ordinal.{v}
      hI : ∀ (n : Nat), And (LT.lt (I n) (Ordinal.omega 1)) (Membership.mem (Measura …
      ⊢ LT.lt (Cardinal.lift.{v, 0} (Cardinal.mk Nat)) (Ordinal.omega 1).cof
    -/
    rw [mk_nat, lift_aleph0, isRegular_aleph_one.cof_omega_eq]
    /-
      case refine_4
      α : Type u
      s : Set (Set α)
      t : Set α
      ht : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      f : Nat → Set α
      H : ∀ (n : Nat), And (Exists fun i => Exists fun j => Membership.mem (Measurab …
      I : Nat → Ordinal.{v}
      hI : ∀ (n : Nat), And (LT.lt (I n) (Ordinal.omega 1)) (Membership.mem (Measura …
      ⊢ LT.lt Cardinal.aleph0 (Cardinal.aleph 1)
    -/
    exact aleph0_lt_aleph_one
    /-
      🎉 no goals
    -/


theorem generateMeasurableRec_subset (s : Set (Set α)) (i : Ordinal) :
    generateMeasurableRec s i ⊆ { t | GenerateMeasurable s t } := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{u_1}
    ⊢ HasSubset.Subset (MeasurableSpace.generateMeasurableRec s i) (setOf fun t => …
  -/
  apply WellFoundedLT.induction i
  exact fun i IH t ht => generateMeasurableRec_induction .basic .empty
    (fun u _ ⟨j, hj, hj'⟩ => .compl _ (IH j hj hj')) (fun f H => .iUnion _ fun n => (H n).1) ht


/-- `generateMeasurableRec s ω₁` generates precisely the smallest sigma-algebra containing `s`. -/
theorem generateMeasurable_eq_rec (s : Set (Set α)) :
    { t | GenerateMeasurable s t } = generateMeasurableRec s ω₁ := by
  /-
    α : Type u
    s : Set (Set α)
    ⊢ Eq (setOf fun t => MeasurableSpace.GenerateMeasurable s t) (MeasurableSpace. …
  -/
  apply (generateMeasurableRec_subset s _).antisymm'
  /-
    α : Type u
    s : Set (Set α)
    ⊢ HasSubset.Subset (setOf fun t => MeasurableSpace.GenerateMeasurable s t) (Me …
  -/
  intro t ht
  /-
    α : Type u
    s : Set (Set α)
    t : Set α
    ht : Membership.mem (setOf fun t => MeasurableSpace.GenerateMeasurable s t) t
    ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) t
  -/
  induction' ht with u hu u _ IH f _ IH
    /-
      case basic
      α : Type u
      s : Set (Set α)
      t u : Set α
      hu : Membership.mem s u
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) u
    -/
  · exact self_subset_generateMeasurableRec s _ hu
    /-
      🎉 no goals
    -/
    /-
      case empty
      α : Type u
      s : Set (Set α)
      t : Set α
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) E …
    -/
  · exact empty_mem_generateMeasurableRec s _
    /-
      🎉 no goals
    -/
    /-
      case compl
      α : Type u
      s : Set (Set α)
      t u : Set α
      a✝ : MeasurableSpace.GenerateMeasurable s u
      IH : Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1) …
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) ( …
    -/
  · rw [generateMeasurableRec_omega1, mem_iUnion₂] at IH
    /-
      case compl
      α : Type u
      s : Set (Set α)
      t u : Set α
      a✝ : MeasurableSpace.GenerateMeasurable s u
      IH : Exists fun i => Exists fun j => Membership.mem (MeasurableSpace.generateM …
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) ( …
    -/
    obtain ⟨i, hi, hi'⟩ := IH
    exact generateMeasurableRec_mono _ ((isLimit_omega 1).succ_lt hi).le
      (compl_mem_generateMeasurableRec (Order.lt_succ i) hi')
    /-
      case iUnion
      α : Type u
      s : Set (Set α)
      t : Set α
      f : Nat → Set α
      a✝ : ∀ (n : Nat), MeasurableSpace.GenerateMeasurable s (f n)
      IH : ∀ (n : Nat), Membership.mem (MeasurableSpace.generateMeasurableRec s (Ord …
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) ( …
    -/
  · simp_rw [generateMeasurableRec_omega1, mem_iUnion₂, exists_prop] at IH
    /-
      case iUnion
      α : Type u
      s : Set (Set α)
      t : Set α
      f : Nat → Set α
      a✝ : ∀ (n : Nat), MeasurableSpace.GenerateMeasurable s (f n)
      IH : ∀ (n : Nat), Exists fun i => And (LT.lt i (Ordinal.omega 1)) (Membership. …
      ⊢ Membership.mem (MeasurableSpace.generateMeasurableRec s (Ordinal.omega 1)) ( …
    -/
    exact iUnion_mem_generateMeasurableRec IH
    /-
      🎉 no goals
    -/


/-- `generateMeasurableRec` is constant for ordinals `≥ ω₁`. -/
theorem generateMeasurableRec_of_omega1_le (s : Set (Set α)) {i : Ordinal.{v}} (hi : ω₁ ≤ i) :
    generateMeasurableRec s i = generateMeasurableRec s (ω₁ : Ordinal.{v}) := by
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{v}
    hi : LE.le (Ordinal.omega 1) i
    ⊢ Eq (MeasurableSpace.generateMeasurableRec s i) (MeasurableSpace.generateMeas …
  -/
  apply (generateMeasurableRec_mono s hi).antisymm'
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{v}
    hi : LE.le (Ordinal.omega 1) i
    ⊢ LE.le (MeasurableSpace.generateMeasurableRec s i) (MeasurableSpace.generateM …
  -/
  rw [← generateMeasurable_eq_rec]
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{v}
    hi : LE.le (Ordinal.omega 1) i
    ⊢ LE.le (MeasurableSpace.generateMeasurableRec s i) (setOf fun t => Measurable …
  -/
  exact generateMeasurableRec_subset s i
  /-
    🎉 no goals
  -/


/-- At each step of the inductive construction, the cardinality bound `≤ #s ^ ℵ₀` holds. -/
theorem cardinal_generateMeasurableRec_le (s : Set (Set α)) (i : Ordinal.{v}) :
    #(generateMeasurableRec s i) ≤ max #s 2 ^ ℵ₀ := by
  suffices ∀ i ≤ ω₁, #(generateMeasurableRec s i) ≤ max #s 2 ^ ℵ₀ by
    obtain hi | hi := le_or_lt i ω₁
    · exact this i hi
    · rw [generateMeasurableRec_of_omega1_le s hi.le]
      exact this _ le_rfl
  /-
    α : Type u
    s : Set (Set α)
    i : Ordinal.{v}
    ⊢ ∀ (i : Ordinal.{v}), LE.le i (Ordinal.omega 1) → LE.le (Cardinal.mk ↑(Measur …
  -/
  intro i
  /-
    α : Type u
    s : Set (Set α)
    i✝ i : Ordinal.{v}
    ⊢ LE.le i (Ordinal.omega 1) → LE.le (Cardinal.mk ↑(MeasurableSpace.generateMea …
  -/
  apply WellFoundedLT.induction i
  /-
    α : Type u
    s : Set (Set α)
    i✝ i : Ordinal.{v}
    ⊢ ∀ (x : Ordinal.{v}), (∀ (y : Ordinal.{v}), LT.lt y x → LE.le y (Ordinal.omeg …
  -/
  intro i IH hi
  /-
    α : Type u
    s : Set (Set α)
    i✝¹ i✝ i : Ordinal.{v}
    IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
    hi : LE.le i (Ordinal.omega 1)
    ⊢ LE.le (Cardinal.mk ↑(MeasurableSpace.generateMeasurableRec s i)) (HPow.hPow  …
  -/
  have A : 𝔠 ≤ max #s 2 ^ ℵ₀ := power_le_power_right (le_max_right _ _)
  /-
    α : Type u
    s : Set (Set α)
    i✝¹ i✝ i : Ordinal.{v}
    IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
    hi : LE.le i (Ordinal.omega 1)
    A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
    ⊢ LE.le (Cardinal.mk ↑(MeasurableSpace.generateMeasurableRec s i)) (HPow.hPow  …
  -/
  have B := aleph0_le_continuum.trans A
  have C : #(⋃ j < i, generateMeasurableRec s j) ≤ max #s 2 ^ ℵ₀ := by
    apply mk_iUnion_Ordinal_lift_le_of_le _ B _
    · intro j hj
      exact IH j hj (hj.trans_le hi).le
    · rw [lift_power, lift_aleph0]
      rw [← Ordinal.lift_le.{u}, lift_omega, Ordinal.lift_one, ← ord_aleph] at hi
      have H := card_le_of_le_ord hi
      rw [← Ordinal.lift_card] at H
      apply H.trans <| aleph_one_le_continuum.trans <| power_le_power_right _
      rw [lift_max, Cardinal.lift_ofNat]
      exact le_max_right _ _
  /-
    α : Type u
    s : Set (Set α)
    i✝¹ i✝ i : Ordinal.{v}
    IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
    hi : LE.le i (Ordinal.omega 1)
    A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
    B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
    C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
    ⊢ LE.le (Cardinal.mk ↑(MeasurableSpace.generateMeasurableRec s i)) (HPow.hPow  …
  -/
  rw [generateMeasurableRec]
  apply_rules [(mk_union_le _ _).trans, add_le_of_le (aleph_one_le_continuum.trans A),
    mk_image_le.trans]
    /-
      case h1.h1.h1
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le (Cardinal.mk ↑s) (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.alep …
    -/
  · exact (self_le_power _ one_le_aleph0).trans (power_le_power_right (le_max_left _ _))
    /-
      🎉 no goals
    -/
    /-
      case h1.h1.h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le (Cardinal.mk ↑(Singleton.singleton EmptyCollection.emptyCollection)) ( …
    -/
  · rw [mk_singleton]
    /-
      case h1.h1.h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le 1 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.aleph0)
    -/
    exact one_lt_aleph0.le.trans B
    /-
      🎉 no goals
    -/
    /-
      case h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le (Cardinal.mk ↑(Set.range fun f => Set.iUnion fun n => ↑(f n))) (HPow.h …
    -/
  · apply mk_range_le.trans
    /-
      case h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le (Cardinal.mk (Nat → ↑(Set.iUnion fun j => Set.iUnion fun h => Measurab …
    -/
    simp only [mk_pi, prod_const, Cardinal.lift_uzero, mk_denumerable, lift_aleph0]
    /-
      case h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      ⊢ LE.le (HPow.hPow (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => Meas …
    -/
    have := @power_le_power_right _ _ ℵ₀ C
    /-
      case h2
      α : Type u
      s : Set (Set α)
      i✝¹ i✝ i : Ordinal.{v}
      IH : ∀ (y : Ordinal.{v}), LT.lt y i → LE.le y (Ordinal.omega 1) → LE.le (Cardi …
      hi : LE.le i (Ordinal.omega 1)
      A : LE.le Cardinal.continuum (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal. …
      B : LE.le Cardinal.aleph0 (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.ale …
      C : LE.le (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => MeasurableSpa …
      this : LE.le (HPow.hPow (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => …
      ⊢ LE.le (HPow.hPow (Cardinal.mk ↑(Set.iUnion fun j => Set.iUnion fun h => Meas …
    -/
    rwa [← power_mul, aleph0_mul_aleph0] at this
    /-
      🎉 no goals
    -/


/-- If a sigma-algebra is generated by a set of sets `s`, then the sigma-algebra has cardinality at
most `max #s 2 ^ ℵ₀`. -/
theorem cardinal_generateMeasurable_le (s : Set (Set α)) :
    #{ t | GenerateMeasurable s t } ≤ max #s 2 ^ ℵ₀ := by
  /-
    α : Type u
    s : Set (Set α)
    ⊢ LE.le (Cardinal.mk ↑(setOf fun t => MeasurableSpace.GenerateMeasurable s t)) …
  -/
  rw [generateMeasurable_eq_rec.{u, 0}]
  /-
    α : Type u
    s : Set (Set α)
    ⊢ LE.le (Cardinal.mk ↑(MeasurableSpace.generateMeasurableRec s (Ordinal.omega  …
  -/
  exact cardinal_generateMeasurableRec_le s _
  /-
    🎉 no goals
  -/


/-- If a sigma-algebra is generated by a set of sets `s`, then the sigma
algebra has cardinality at most `max #s 2 ^ ℵ₀`. -/
theorem cardinal_measurableSet_le (s : Set (Set α)) :
    #{ t | @MeasurableSet α (generateFrom s) t } ≤ max #s 2 ^ ℵ₀ :=
  cardinal_generateMeasurable_le s


@[deprecated cardinal_measurableSet_le (since := "2024-08-30")]
alias cardinalMeasurableSet_le := cardinal_measurableSet_le


/-- If a sigma-algebra is generated by a set of sets `s` with cardinality at most the continuum,
then the sigma algebra has the same cardinality bound. -/
theorem cardinal_generateMeasurable_le_continuum {s : Set (Set α)} (hs : #s ≤ 𝔠) :
    #{ t | GenerateMeasurable s t } ≤ 𝔠 := by
  /-
    α : Type u
    s : Set (Set α)
    hs : LE.le (Cardinal.mk ↑s) Cardinal.continuum
    ⊢ LE.le (Cardinal.mk ↑(setOf fun t => MeasurableSpace.GenerateMeasurable s t)) …
  -/
  apply (cardinal_generateMeasurable_le s).trans
  /-
    α : Type u
    s : Set (Set α)
    hs : LE.le (Cardinal.mk ↑s) Cardinal.continuum
    ⊢ LE.le (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.aleph0) Cardinal.cont …
  -/
  rw [← continuum_power_aleph0]
  /-
    α : Type u
    s : Set (Set α)
    hs : LE.le (Cardinal.mk ↑s) Cardinal.continuum
    ⊢ LE.le (HPow.hPow (Max.max (Cardinal.mk ↑s) 2) Cardinal.aleph0) (HPow.hPow Ca …
  -/
  exact_mod_cast power_le_power_right (max_le hs (nat_lt_continuum 2).le)
  /-
    🎉 no goals
  -/


/-- If a sigma-algebra is generated by a set of sets `s` with cardinality at most the continuum,
then the sigma algebra has the same cardinality bound. -/
theorem cardinal_measurableSet_le_continuum {s : Set (Set α)} :
    #s ≤ 𝔠 → #{ t | @MeasurableSet α (generateFrom s) t } ≤ 𝔠 :=
  cardinal_generateMeasurable_le_continuum


