/-- The commutator subgroup of a group G is the normal subgroup
  generated by the commutators [p,q]=`p*q*p⁻¹*q⁻¹`. -/
def commutator : Subgroup G := ⁅(⊤ : Subgroup G), ⊤⁆

-- Porting note: this instance should come from `deriving Subgroup.Normal`

instance : Subgroup.Normal (commutator G) := Subgroup.commutator_normal ⊤ ⊤


theorem commutator_def : commutator G = ⁅(⊤ : Subgroup G), ⊤⁆ :=
  rfl


theorem commutator_eq_closure : commutator G = Subgroup.closure (commutatorSet G) := by
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (commutator G) (Subgroup.closure (commutatorSet G))
  -/
  simp [commutator, Subgroup.commutator_def, commutatorSet]
  /-
    🎉 no goals
  -/


theorem commutator_eq_normalClosure : commutator G = Subgroup.normalClosure (commutatorSet G) := by
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (commutator G) (Subgroup.normalClosure (commutatorSet G))
  -/
  simp [commutator, Subgroup.commutator_def', commutatorSet]
  /-
    🎉 no goals
  -/


variable {G} in
theorem Subgroup.map_subtype_commutator (H : Subgroup G) :
    (_root_.commutator H).map H.subtype = ⁅H, H⁆ := by
  /-
    G : Type u
    inst✝ : Group G
    H : Subgroup G
    ⊢ Eq (Subgroup.map H.subtype (_root_.commutator (Subtype fun x => Membership.m …
  -/
  rw [_root_.commutator_def, map_commutator, ← MonoidHom.range_eq_map, H.range_subtype]
  /-
    🎉 no goals
  -/


instance commutator_characteristic : (commutator G).Characteristic :=
  Subgroup.commutator_characteristic ⊤ ⊤


instance [Finite (commutatorSet G)] : Group.FG (commutator G) := by
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ Group.FG (Subtype fun x => Membership.mem (commutator G) x)
  -/
  rw [commutator_eq_closure]
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ Group.FG (Subtype fun x => Membership.mem (Subgroup.closure (commutatorSet G …
  -/
  apply Group.closure_finite_fg
  /-
    🎉 no goals
  -/


theorem rank_commutator_le_card [Finite (commutatorSet G)] :
    Group.rank (commutator G) ≤ Nat.card (commutatorSet G) := by
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ LE.le (Group.rank (Subtype fun x => Membership.mem (commutator G) x)) (Nat.c …
  -/
  rw [Subgroup.rank_congr (commutator_eq_closure G)]
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ LE.le (Group.rank (Subtype fun x => Membership.mem (Subgroup.closure (commut …
  -/
  apply Subgroup.rank_closure_finite_le_nat_card
  /-
    🎉 no goals
  -/


theorem commutator_centralizer_commutator_le_center :
    ⁅centralizer (commutator G : Set G), centralizer (commutator G)⁆ ≤ Subgroup.center G := by
  rw [← Subgroup.centralizer_univ, ← Subgroup.coe_top, ←
    Subgroup.commutator_eq_bot_iff_le_centralizer]
  suffices ⁅⁅⊤, centralizer (commutator G : Set G)⁆, centralizer (commutator G : Set G)⁆ = ⊥ by
    refine Subgroup.commutator_commutator_eq_bot_of_rotate ?_ this
    rwa [Subgroup.commutator_comm (centralizer (commutator G : Set G))]
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (Bracket.bracket (Bracket.bracket Top.top (Subgroup.centralizer ↑(commuta …
  -/
  rw [Subgroup.commutator_comm, Subgroup.commutator_eq_bot_iff_le_centralizer]
  /-
    G : Type u
    inst✝ : Group G
    ⊢ LE.le (Subgroup.centralizer ↑(commutator G)) (Subgroup.centralizer ↑(Bracket …
  -/
  exact Set.centralizer_subset (Subgroup.commutator_mono le_top le_top)
  /-
    🎉 no goals
  -/


/-- The abelianization of G is the quotient of G by its commutator subgroup. -/
def Abelianization : Type u :=
  G ⧸ commutator G


instance commGroup : CommGroup (Abelianization G) :=
  { QuotientGroup.Quotient.group _ with
    mul_comm := fun x y =>
      Quotient.inductionOn₂' x y fun a b =>
        Quotient.sound' <|
          QuotientGroup.leftRel_apply.mpr <|
            Subgroup.subset_closure
                                                                        /-
                                                                          G : Type u
                                                                          inst✝ : Group G
                                                                          x y : Abelianization G
                                                                          a b : G
                                                                          ⊢ Eq (Bracket.bracket (Inv.inv b) (Inv.inv a)) (HMul.hMul (Inv.inv ((fun x1 x2 …
                                                                        -/
              ⟨b⁻¹, Subgroup.mem_top b⁻¹, a⁻¹, Subgroup.mem_top a⁻¹, by group⟩ }
                                                                        /-
                                                                          🎉 no goals
                                                                        -/


instance : Inhabited (Abelianization G) :=
  ⟨1⟩


instance [Unique G] : Unique (Abelianization G) := Quotient.instUniqueQuotient _


instance [Fintype G] [DecidablePred (· ∈ commutator G)] : Fintype (Abelianization G) :=
  QuotientGroup.fintype (commutator G)


instance [Finite G] : Finite (Abelianization G) :=
  Quotient.finite _


/-- `of` is the canonical projection from G to its abelianization. -/
def of : G →* Abelianization G where
  toFun := QuotientGroup.mk
  map_one' := rfl
  map_mul' _ _ := rfl


@[simp]
theorem mk_eq_of (a : G) : Quot.mk _ a = of a :=
  rfl


variable (G) in
@[simp]
theorem ker_of : of.ker = commutator G :=
  QuotientGroup.ker_mk' (commutator G)


theorem commutator_subset_ker : commutator G ≤ f.ker := by
  /-
    G : Type u
    inst✝¹ : Group G
    A : Type v
    inst✝ : CommGroup A
    f : MonoidHom G A
    ⊢ LE.le (commutator G) f.ker
  -/
  rw [commutator_eq_closure, Subgroup.closure_le]
  /-
    G : Type u
    inst✝¹ : Group G
    A : Type v
    inst✝ : CommGroup A
    f : MonoidHom G A
    ⊢ HasSubset.Subset (commutatorSet G) ↑f.ker
  -/
  rintro x ⟨p, q, rfl⟩
  /-
    case intro.intro
    G : Type u
    inst✝¹ : Group G
    A : Type v
    inst✝ : CommGroup A
    f : MonoidHom G A
    p q : G
    ⊢ Membership.mem (↑f.ker) (Bracket.bracket p q)
  -/
  simp [MonoidHom.mem_ker, mul_right_comm (f p) (f q), commutatorElement_def]
  /-
    🎉 no goals
  -/


/-- If `f : G → A` is a group homomorphism to an abelian group, then `lift f` is the unique map
  from the abelianization of a `G` to `A` that factors through `f`. -/
def lift : (G →* A) ≃ (Abelianization G →* A) where
  toFun f := QuotientGroup.lift _ f fun _ h => MonoidHom.mem_ker.2 <| commutator_subset_ker _ h
  invFun F := F.comp of
  left_inv _ := MonoidHom.ext fun _ => rfl
  right_inv _ := MonoidHom.ext fun x => QuotientGroup.induction_on x fun _ => rfl


@[simp]
theorem lift.of (x : G) : lift f (of x) = f x :=
  rfl


theorem lift.unique (φ : Abelianization G →* A)
    -- hφ : φ agrees with f on the image of G in Gᵃᵇ
    (hφ : ∀ x : G, φ (Abelianization.of x) = f x)
    {x : Abelianization G} : φ x = lift f x :=
  QuotientGroup.induction_on x hφ


@[simp]
theorem lift_of : lift of = MonoidHom.id (Abelianization G) :=
  lift.apply_symm_apply <| MonoidHom.id _


/-- See note [partially-applied ext lemmas]. -/
@[ext]
theorem hom_ext (φ ψ : Abelianization G →* A) (h : φ.comp of = ψ.comp of) : φ = ψ :=
  MonoidHom.ext fun x => QuotientGroup.induction_on x <| DFunLike.congr_fun h


/-- The map operation of the `Abelianization` functor -/
def map : Abelianization G →* Abelianization H :=
  lift (of.comp f)


/-- Use `map` as the preferred simp normal form. -/
@[simp] theorem lift_of_comp :
    Abelianization.lift (Abelianization.of.comp f) = Abelianization.map f := rfl


@[simp]
theorem map_of (x : G) : map f (of x) = of (f x) :=
  rfl


@[simp]
theorem map_id : map (MonoidHom.id G) = MonoidHom.id (Abelianization G) :=
  hom_ext _ _ rfl


@[simp]
theorem map_comp {I : Type w} [Group I] (g : H →* I) : (map g).comp (map f) = map (g.comp f) :=
  hom_ext _ _ rfl


@[simp]
theorem map_map_apply {I : Type w} [Group I] {g : H →* I} {x : Abelianization G} :
    map g (map f x) = map (g.comp f) x :=
  DFunLike.congr_fun (map_comp _ _) x


/-- Equivalent groups have equivalent abelianizations -/
def MulEquiv.abelianizationCongr (e : G ≃* H) : Abelianization G ≃* Abelianization H where
  toFun := Abelianization.map e.toMonoidHom
  invFun := Abelianization.map e.symm.toMonoidHom
  left_inv := by
    /-
      G : Type u
      inst✝¹ : Group G
      H : Type v
      inst✝ : Group H
      e : MulEquiv G H
      ⊢ Function.LeftInverse ⇑(Abelianization.map e.symm.toMonoidHom) ⇑(Abelianizati …
    -/
    rintro ⟨a⟩
    /-
      case mk
      G : Type u
      inst✝¹ : Group G
      H : Type v
      inst✝ : Group H
      e : MulEquiv G H
      x✝ : Abelianization G
      a : G
      ⊢ Eq ((Abelianization.map e.symm.toMonoidHom) ((Abelianization.map e.toMonoidH …
    -/
    simp
    /-
      🎉 no goals
    -/
  right_inv := by
    /-
      G : Type u
      inst✝¹ : Group G
      H : Type v
      inst✝ : Group H
      e : MulEquiv G H
      ⊢ Function.RightInverse ⇑(Abelianization.map e.symm.toMonoidHom) ⇑(Abelianizat …
    -/
    rintro ⟨a⟩
    /-
      case mk
      G : Type u
      inst✝¹ : Group G
      H : Type v
      inst✝ : Group H
      e : MulEquiv G H
      x✝ : Abelianization H
      a : H
      ⊢ Eq ((Abelianization.map e.toMonoidHom) ((Abelianization.map e.symm.toMonoidH …
    -/
    simp
    /-
      🎉 no goals
    -/
  map_mul' := MonoidHom.map_mul _


@[simp]
theorem abelianizationCongr_of (e : G ≃* H) (x : G) :
    e.abelianizationCongr (Abelianization.of x) = Abelianization.of (e x) :=
  rfl


@[simp]
theorem abelianizationCongr_refl :
    (MulEquiv.refl G).abelianizationCongr = MulEquiv.refl (Abelianization G) :=
  MulEquiv.toMonoidHom_injective Abelianization.lift_of


@[simp]
theorem abelianizationCongr_symm (e : G ≃* H) :
    e.abelianizationCongr.symm = e.symm.abelianizationCongr :=
  rfl


@[simp]
theorem abelianizationCongr_trans {I : Type v} [Group I] (e : G ≃* H) (e₂ : H ≃* I) :
    e.abelianizationCongr.trans e₂.abelianizationCongr = (e.trans e₂).abelianizationCongr :=
  MulEquiv.toMonoidHom_injective (Abelianization.hom_ext _ _ rfl)


/-- An Abelian group is equivalent to its own abelianization. -/
@[simps]
def Abelianization.equivOfComm {H : Type*} [CommGroup H] : H ≃* Abelianization H :=
  { Abelianization.of with
    toFun := Abelianization.of
    invFun := Abelianization.lift (MonoidHom.id H)
    left_inv := fun _ => rfl
    right_inv := by
      /-
        G : Type u
        inst✝¹ : Group G
        H : Type u_1
        inst✝ : CommGroup H
        ⊢ Function.RightInverse ⇑(Abelianization.lift (MonoidHom.id H)) ⇑Abelianizatio …
      -/
      rintro ⟨a⟩
      /-
        case mk
        G : Type u
        inst✝¹ : Group G
        H : Type u_1
        inst✝ : CommGroup H
        x✝ : Abelianization H
        a : H
        ⊢ Eq (Abelianization.of ((Abelianization.lift (MonoidHom.id H)) (Quot.mk (⇑(Qu …
      -/
      rfl }
      /-
        🎉 no goals
      -/


/-- Representatives `(g₁, g₂) : G × G` of commutators `⁅g₁, g₂⁆ ∈ G`. -/
def commutatorRepresentatives : Set (G × G) :=
  Set.range fun g : commutatorSet G => (g.2.choose, g.2.choose_spec.choose)


instance [Finite (commutatorSet G)] : Finite (commutatorRepresentatives G) :=
  Set.finite_coe_iff.mpr (Set.finite_range _)


/-- Subgroup generated by representatives `g₁ g₂ : G` of commutators `⁅g₁, g₂⁆ ∈ G`. -/
def closureCommutatorRepresentatives : Subgroup G :=
  closure (Prod.fst '' commutatorRepresentatives G ∪ Prod.snd '' commutatorRepresentatives G)


instance closureCommutatorRepresentatives_fg [Finite (commutatorSet G)] :
    Group.FG (closureCommutatorRepresentatives G) :=
  Group.closure_finite_fg _


theorem rank_closureCommutatorRepresentatives_le [Finite (commutatorSet G)] :
    Group.rank (closureCommutatorRepresentatives G) ≤ 2 * Nat.card (commutatorSet G) := by
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ LE.le (Group.rank (Subtype fun x => Membership.mem (closureCommutatorReprese …
  -/
  rw [two_mul]
  exact
    (Subgroup.rank_closure_finite_le_nat_card _).trans
      ((Set.card_union_le _ _).trans
        (add_le_add ((Finite.card_image_le _).trans (Finite.card_range_le _))
          ((Finite.card_image_le _).trans (Finite.card_range_le _))))


theorem image_commutatorSet_closureCommutatorRepresentatives :
    (closureCommutatorRepresentatives G).subtype ''
        commutatorSet (closureCommutatorRepresentatives G) =
      commutatorSet G := by
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (Set.image (⇑(closureCommutatorRepresentatives G).subtype) (commutatorSet …
  -/
  apply Set.Subset.antisymm
    /-
      case h₁
      G : Type u
      inst✝ : Group G
      ⊢ HasSubset.Subset (Set.image (⇑(closureCommutatorRepresentatives G).subtype)  …
    -/
  · rintro - ⟨-, ⟨g₁, g₂, rfl⟩, rfl⟩
    /-
      case h₁.intro.intro.intro.intro
      G : Type u
      inst✝ : Group G
      g₁ g₂ : Subtype fun x => Membership.mem (closureCommutatorRepresentatives G) x
      ⊢ Membership.mem (commutatorSet G) ((closureCommutatorRepresentatives G).subty …
    -/
    exact ⟨g₁, g₂, rfl⟩
    /-
      🎉 no goals
    -/
  · exact fun g hg =>
      ⟨_,
        ⟨⟨_, subset_closure (Or.inl ⟨_, ⟨⟨g, hg⟩, rfl⟩, rfl⟩)⟩,
          ⟨_, subset_closure (Or.inr ⟨_, ⟨⟨g, hg⟩, rfl⟩, rfl⟩)⟩, rfl⟩,
        hg.choose_spec.choose_spec⟩


theorem card_commutatorSet_closureCommutatorRepresentatives :
    Nat.card (commutatorSet (closureCommutatorRepresentatives G)) = Nat.card (commutatorSet G) := by
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (Nat.card ↑(commutatorSet (Subtype fun x => Membership.mem (closureCommut …
  -/
  rw [← image_commutatorSet_closureCommutatorRepresentatives G]
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (Nat.card ↑(commutatorSet (Subtype fun x => Membership.mem (closureCommut …
  -/
  exact Nat.card_congr (Equiv.Set.image _ _ (subtype_injective _))
  /-
    🎉 no goals
  -/


theorem card_commutator_closureCommutatorRepresentatives :
    Nat.card (commutator (closureCommutatorRepresentatives G)) = Nat.card (commutator G) := by
  rw [commutator_eq_closure G, ← image_commutatorSet_closureCommutatorRepresentatives, ←
    MonoidHom.map_closure, ← commutator_eq_closure]
  /-
    G : Type u
    inst✝ : Group G
    ⊢ Eq (Nat.card (Subtype fun x => Membership.mem (commutator (Subtype fun x =>  …
  -/
  exact Nat.card_congr (Equiv.Set.image _ _ (subtype_injective _))
  /-
    🎉 no goals
  -/


instance [Finite (commutatorSet G)] :
    Finite (commutatorSet (closureCommutatorRepresentatives G)) := by
  /-
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ Finite ↑(commutatorSet (Subtype fun x => Membership.mem (closureCommutatorRe …
  -/
  apply Nat.finite_of_card_ne_zero
  /-
    case h
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ Ne (Nat.card ↑(commutatorSet (Subtype fun x => Membership.mem (closureCommut …
  -/
  rw [card_commutatorSet_closureCommutatorRepresentatives]
  /-
    case h
    G : Type u
    inst✝¹ : Group G
    inst✝ : Finite ↑(commutatorSet G)
    ⊢ Ne (Nat.card ↑(commutatorSet G)) 0
  -/
  exact Finite.card_pos.ne'
  /-
    🎉 no goals
  -/


