/-- The span of a set `s ⊆ M` is the smallest submodule of M that contains `s`. -/
def span (s : Set M) : Submodule R M :=
  sInf { p | s ⊆ p }


/-- An `R`-submodule of `M` is principal if it is generated by one element. -/
@[mk_iff]
class IsPrincipal (S : Submodule R M) : Prop where
  principal' : ∃ a, S = span R {a}


theorem IsPrincipal.principal (S : Submodule R M) [S.IsPrincipal] :
    ∃ a, S = span R {a} :=
  Submodule.IsPrincipal.principal'


theorem mem_span : x ∈ span R s ↔ ∀ p : Submodule R M, s ⊆ p → x ∈ p :=
  mem_iInter₂


@[aesop safe 20 apply (rule_sets := [SetLike])]
theorem subset_span : s ⊆ span R s := fun _ h => mem_span.2 fun _ hp => hp h


theorem span_le {p} : span R s ≤ p ↔ s ⊆ p :=
  ⟨Subset.trans subset_span, fun ss _ h => mem_span.1 h _ ss⟩


@[gcongr] theorem span_mono (h : s ⊆ t) : span R s ≤ span R t :=
  span_le.2 <| Subset.trans h subset_span


theorem span_monotone : Monotone (span R : Set M → Submodule R M) := fun _ _ => span_mono


theorem span_eq_of_le (h₁ : s ⊆ p) (h₂ : p ≤ span R s) : span R s = p :=
  le_antisymm (span_le.2 h₁) h₂


theorem span_eq : span R (p : Set M) = p :=
  span_eq_of_le _ (Subset.refl _) subset_span


theorem span_eq_span (hs : s ⊆ span R t) (ht : t ⊆ span R s) : span R s = span R t :=
  le_antisymm (span_le.2 hs) (span_le.2 ht)


/-- A version of `Submodule.span_eq` for subobjects closed under addition and scalar multiplication
and containing zero. In general, this should not be used directly, but can be used to quickly
generate proofs for specific types of subobjects. -/
lemma coe_span_eq_self [SetLike S M] [AddSubmonoidClass S M] [SMulMemClass S R M] (s : S) :
    (span R (s : Set M) : Set M) = s := by
  /-
    R : Type u_1
    M : Type u_4
    S : Type u_7
    inst✝⁵ : Semiring R
    inst✝⁴ : AddCommMonoid M
    inst✝³ : Module R M
    inst✝² : SetLike S M
    inst✝¹ : AddSubmonoidClass S M
    inst✝ : SMulMemClass S R M
    s : S
    ⊢ Eq ↑(Submodule.span R ↑s) ↑s
  -/
  refine le_antisymm ?_ subset_span
  let s' : Submodule R M :=
    { carrier := s
      add_mem' := add_mem
      zero_mem' := zero_mem _
      smul_mem' := SMulMemClass.smul_mem }
  /-
    R : Type u_1
    M : Type u_4
    S : Type u_7
    inst✝⁵ : Semiring R
    inst✝⁴ : AddCommMonoid M
    inst✝³ : Module R M
    inst✝² : SetLike S M
    inst✝¹ : AddSubmonoidClass S M
    inst✝ : SMulMemClass S R M
    s : S
    s' : Submodule R M := { carrier := ↑s, add_mem' := ⋯, zero_mem' := ⋯, smul_mem …
    ⊢ LE.le ↑(Submodule.span R ↑s) ↑s
  -/
  exact span_le (p := s') |>.mpr le_rfl
  /-
    🎉 no goals
  -/


@[simp]
theorem span_insert_zero : span R (insert (0 : M) s) = span R s := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    ⊢ Eq (Submodule.span R (Insert.insert 0 s)) (Submodule.span R s)
  -/
  refine le_antisymm ?_ (Submodule.span_mono (Set.subset_insert 0 s))
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    ⊢ LE.le (Submodule.span R (Insert.insert 0 s)) (Submodule.span R s)
  -/
  rw [span_le, Set.insert_subset_iff]
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    ⊢ And (Membership.mem (↑(Submodule.span R s)) 0) (HasSubset.Subset s ↑(Submodu …
  -/
  exact ⟨by simp only [SetLike.mem_coe, Submodule.zero_mem], Submodule.subset_span⟩
  /-
    🎉 no goals
  -/


theorem closure_subset_span {s : Set M} : (AddSubmonoid.closure s : Set M) ⊆ span R s :=
  (@AddSubmonoid.closure_le _ _ _ (span R s).toAddSubmonoid).mpr subset_span


theorem closure_le_toAddSubmonoid_span {s : Set M} :
    AddSubmonoid.closure s ≤ (span R s).toAddSubmonoid :=
  closure_subset_span


@[simp]
theorem span_closure {s : Set M} : span R (AddSubmonoid.closure s : Set M) = span R s :=
  le_antisymm (span_le.mpr closure_subset_span) (span_mono AddSubmonoid.subset_closure)


/-- An induction principle for span membership. If `p` holds for 0 and all elements of `s`, and is
preserved under addition and scalar multiplication, then `p` holds for all elements of the span of
`s`. -/
@[elab_as_elim]
theorem span_induction {p : (x : M) → x ∈ span R s → Prop}
    (mem : ∀ (x) (h : x ∈ s), p x (subset_span h))
    (zero : p 0 (Submodule.zero_mem _))
    (add : ∀ x y hx hy, p x hx → p y hy → p (x + y) (Submodule.add_mem _ ‹_› ‹_›))
    (smul : ∀ (a : R) (x hx), p x hx → p (a • x) (Submodule.smul_mem _ _ ‹_›)) {x}
    (hx : x ∈ span R s) : p x hx := by
  let p : Submodule R M :=
    { carrier := { x | ∃ hx, p x hx }
      add_mem' := fun ⟨_, hpx⟩ ⟨_, hpy⟩ ↦ ⟨_, add _ _ _ _ hpx hpy⟩
      zero_mem' := ⟨_, zero⟩
      smul_mem' := fun r ↦ fun ⟨_, hpx⟩ ↦ ⟨_, smul r _ _ hpx⟩ }
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    p✝ : (x : M) → Membership.mem (Submodule.span R s) x → Prop
    mem : ∀ (x : M) (h : Membership.mem s x), p✝ x ⋯
    zero : p✝ 0 ⋯
    add : ∀ (x y : M) (hx : Membership.mem (Submodule.span R s) x) (hy : Membershi …
    smul : ∀ (a : R) (x : M) (hx : Membership.mem (Submodule.span R s) x), p✝ x hx …
    x : M
    hx : Membership.mem (Submodule.span R s) x
    p : Submodule R M := { carrier := setOf fun x => Exists fun hx => p✝ x hx, add …
    ⊢ p✝ x hx
  -/
  exact span_le (p := p) |>.mpr (fun y hy ↦ ⟨subset_span hy, mem y hy⟩) hx |>.elim fun _ ↦ id
  /-
    🎉 no goals
  -/


@[deprecated span_induction (since := "2024-10-10")]
alias span_induction' := span_induction


/-- An induction principle for span membership. This is a version of `Submodule.span_induction`
for binary predicates. -/
theorem span_induction₂ {p : (x y : M) → x ∈ span R s → y ∈ span R s → Prop}
    (mem_mem : ∀ (x) (y) (hx : x ∈ s) (hy : y ∈ s), p x y (subset_span hx) (subset_span hy))
    (zero_left : ∀ y hy, p 0 y (zero_mem _) hy) (zero_right : ∀ x hx, p x 0 hx (zero_mem _))
    (add_left : ∀ x y z hx hy hz, p x z hx hz → p y z hy hz → p (x + y) z (add_mem hx hy) hz)
    (add_right : ∀ x y z hx hy hz, p x y hx hy → p x z hx hz → p x (y + z) hx (add_mem hy hz))
    (smul_left : ∀ (r : R) x y hx hy, p x y hx hy → p (r • x) y (smul_mem _ r hx) hy)
    (smul_right : ∀ (r : R) x y hx hy, p x y hx hy → p x (r • y) hx (smul_mem _ r hy))
    {a b : M} (ha : a ∈ Submodule.span R s)
    (hb : b ∈ Submodule.span R s) : p a b ha hb := by
  induction hb using span_induction with
  | mem z hz => induction ha using span_induction with
    | mem _ h => exact mem_mem _ _ h hz
    | zero => exact zero_left _ _
    | add _ _ _ _ h₁ h₂ => exact add_left _ _ _ _ _ _ h₁ h₂
    | smul _ _ _ h => exact smul_left _ _ _ _ _ h
  | zero => exact zero_right a ha
  | add _ _ _ _ h₁ h₂ => exact add_right _ _ _ _ _ _ h₁ h₂
  | smul _ _ _ h => exact smul_right _ _ _ _ _ h


open AddSubmonoid in
theorem span_eq_closure {s : Set M} : (span R s).toAddSubmonoid = closure (@univ R • s) := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    ⊢ Eq (Submodule.span R s).toAddSubmonoid (AddSubmonoid.closure (HSMul.hSMul Se …
  -/
  refine le_antisymm (fun x (hx : x ∈ span R s) ↦ ?of_mem_span) (fun x hx ↦ ?of_mem_closure)
  case of_mem_span =>
    induction hx using span_induction with
    | mem x hx => exact subset_closure ⟨1, trivial, x, hx, one_smul R x⟩
    | zero => exact zero_mem _
    | add _ _ _ _ h₁ h₂ => exact add_mem h₁ h₂
    | smul r₁ y _h hy =>
      clear _h
      induction hy using AddSubmonoid.closure_induction with
      | mem _ h =>
        obtain ⟨r₂, -, x, hx, rfl⟩ := h
        exact subset_closure ⟨r₁ * r₂, trivial, x, hx, mul_smul ..⟩
      | one => simpa only [smul_zero] using zero_mem _
      | mul _ _ _ _ h₁ h₂ => simpa only [smul_add] using add_mem h₁ h₂
  case of_mem_closure =>
    refine closure_le.2 ?_ hx
    rintro - ⟨r, -, x, hx, rfl⟩
    exact smul_mem _ _ (subset_span hx)


open AddSubmonoid in
/-- A variant of `span_induction` that combines `∀ x ∈ s, p x` and `∀ r x, p x → p (r • x)`
into a single condition `∀ r, ∀ x ∈ s, p (r • x)`, which can be easier to verify. -/
@[elab_as_elim]
theorem closure_induction {p : (x : M) → x ∈ span R s → Prop}
    (zero : p 0 (Submodule.zero_mem _))
    (add : ∀ x y hx hy, p x hx → p y hy → p (x + y) (Submodule.add_mem _ ‹_› ‹_›))
    (smul_mem : ∀ (r x) (h : x ∈ s), p (r • x) (Submodule.smul_mem _ _ <| subset_span h)) {x}
    (hx : x ∈ span R s) : p x hx := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    p : (x : M) → Membership.mem (Submodule.span R s) x → Prop
    zero : p 0 ⋯
    add : ∀ (x y : M) (hx : Membership.mem (Submodule.span R s) x) (hy : Membershi …
    smul_mem : ∀ (r : R) (x : M) (h : Membership.mem s x), p (HSMul.hSMul r x) ⋯
    x : M
    hx : Membership.mem (Submodule.span R s) x
    ⊢ p x hx
  -/
  have key {v} : v ∈ span R s ↔ v ∈ closure (@univ R • s) := by simp [← span_eq_closure]
  refine AddSubmonoid.closure_induction (p := fun x hx ↦ p x (key.mpr hx))
    ?_ zero (by simpa only [key] using add) (key.mp hx)
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    p : (x : M) → Membership.mem (Submodule.span R s) x → Prop
    zero : p 0 ⋯
    add : ∀ (x y : M) (hx : Membership.mem (Submodule.span R s) x) (hy : Membershi …
    smul_mem : ∀ (r : R) (x : M) (h : Membership.mem s x), p (HSMul.hSMul r x) ⋯
    x : M
    hx : Membership.mem (Submodule.span R s) x
    key : ∀ {v : M}, Iff (Membership.mem (Submodule.span R s) v) (Membership.mem ( …
    ⊢ ∀ (x : M) (h : Membership.mem (HSMul.hSMul Set.univ s) x), (fun x hx => p x  …
  -/
  rintro - ⟨r, -, x, hx, rfl⟩
  /-
    case intro.intro.intro.intro
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    p : (x : M) → Membership.mem (Submodule.span R s) x → Prop
    zero : p 0 ⋯
    add : ∀ (x y : M) (hx : Membership.mem (Submodule.span R s) x) (hy : Membershi …
    smul_mem : ∀ (r : R) (x : M) (h : Membership.mem s x), p (HSMul.hSMul r x) ⋯
    x✝ : M
    hx✝ : Membership.mem (Submodule.span R s) x✝
    key : ∀ {v : M}, Iff (Membership.mem (Submodule.span R s) v) (Membership.mem ( …
    r : R
    left✝ : Membership.mem Set.univ r
    x : M
    hx : Membership.mem s x
    ⊢ p ((fun x1 x2 => HSMul.hSMul x1 x2) r x) ⋯
  -/
  exact smul_mem r x hx
  /-
    🎉 no goals
  -/


@[deprecated closure_induction (since := "2024-10-10")]
alias closure_induction' := closure_induction


@[simp]
theorem span_span_coe_preimage : span R (((↑) : span R s → M) ⁻¹' s) = ⊤ :=
  eq_top_iff.2 fun x _ ↦ Subtype.recOn x fun _ hx' ↦
    span_induction (fun _ h ↦ subset_span h) (zero_mem _) (fun _ _ _ _ ↦ add_mem)
      (fun _ _ _ ↦ smul_mem _ _) hx'


@[simp]
lemma span_setOf_mem_eq_top :
    span R {x : span R s | (x : M) ∈ s} = ⊤ :=
  span_span_coe_preimage


theorem span_nat_eq_addSubmonoid_closure (s : Set M) :
    (span ℕ s).toAddSubmonoid = AddSubmonoid.closure s := by
  /-
    M : Type u_4
    inst✝ : AddCommMonoid M
    s : Set M
    ⊢ Eq (Submodule.span Nat s).toAddSubmonoid (AddSubmonoid.closure s)
  -/
  refine Eq.symm (AddSubmonoid.closure_eq_of_le subset_span ?_)
  apply (OrderIso.to_galoisConnection (AddSubmonoid.toNatSubmodule (M := M)).symm).l_le
     (a := span ℕ s) (b := AddSubmonoid.closure s)
  /-
    M : Type u_4
    inst✝ : AddCommMonoid M
    s : Set M
    ⊢ LE.le (Submodule.span Nat s) (AddSubmonoid.toNatSubmodule.symm.symm (AddSubm …
  -/
  rw [span_le]
  /-
    M : Type u_4
    inst✝ : AddCommMonoid M
    s : Set M
    ⊢ HasSubset.Subset s ↑(AddSubmonoid.toNatSubmodule.symm.symm (AddSubmonoid.clo …
  -/
  exact AddSubmonoid.subset_closure
  /-
    🎉 no goals
  -/


@[simp]
theorem span_nat_eq (s : AddSubmonoid M) : (span ℕ (s : Set M)).toAddSubmonoid = s := by
  /-
    M : Type u_4
    inst✝ : AddCommMonoid M
    s : AddSubmonoid M
    ⊢ Eq (Submodule.span Nat ↑s).toAddSubmonoid s
  -/
  rw [span_nat_eq_addSubmonoid_closure, s.closure_eq]
  /-
    🎉 no goals
  -/


theorem span_int_eq_addSubgroup_closure {M : Type*} [AddCommGroup M] (s : Set M) :
    (span ℤ s).toAddSubgroup = AddSubgroup.closure s :=
  Eq.symm <|
    AddSubgroup.closure_eq_of_le _ subset_span fun _ hx =>
      span_induction (fun _ hx => AddSubgroup.subset_closure hx) (AddSubgroup.zero_mem _)
        (fun _ _ _ _ => AddSubgroup.add_mem _) (fun _ _ _ _ => AddSubgroup.zsmul_mem _ ‹_› _) hx


@[simp]
theorem span_int_eq {M : Type*} [AddCommGroup M] (s : AddSubgroup M) :
                                                 /-
                                                   M : Type u_9
                                                   inst✝ : AddCommGroup M
                                                   s : AddSubgroup M
                                                   ⊢ Eq (Submodule.span Int ↑s).toAddSubgroup s
                                                 -/
    (span ℤ (s : Set M)).toAddSubgroup = s := by rw [span_int_eq_addSubgroup_closure, s.closure_eq]
                                                 /-
                                                   🎉 no goals
                                                 -/


/-- `span` forms a Galois insertion with the coercion from submodule to set. -/
protected def gi : GaloisInsertion (@span R M _ _ _) (↑) where
  choice s _ := span R s
  gc _ _ := span_le
  le_l_u _ := subset_span
  choice_eq _ _ := rfl


@[simp]
theorem span_empty : span R (∅ : Set M) = ⊥ :=
  (Submodule.gi R M).gc.l_bot


@[simp]
theorem span_univ : span R (univ : Set M) = ⊤ :=
  eq_top_iff.2 <| SetLike.le_def.2 <| subset_span


theorem span_union (s t : Set M) : span R (s ∪ t) = span R s ⊔ span R t :=
  (Submodule.gi R M).gc.l_sup


theorem span_iUnion {ι} (s : ι → Set M) : span R (⋃ i, s i) = ⨆ i, span R (s i) :=
  (Submodule.gi R M).gc.l_iSup

/- ./././Mathport/Syntax/Translate/Expr.lean:107:6: warning: expanding binder group (i j) -/
/- ./././Mathport/Syntax/Translate/Expr.lean:107:6: warning: expanding binder group (i j) -/

theorem span_iUnion₂ {ι} {κ : ι → Sort*} (s : ∀ i, κ i → Set M) :
    span R (⋃ (i) (j), s i j) = ⨆ (i) (j), span R (s i j) :=
  (Submodule.gi R M).gc.l_iSup₂


theorem span_attach_biUnion [DecidableEq M] {α : Type*} (s : Finset α) (f : s → Finset M) :
                                                                  /-
                                                                    R : Type u_1
                                                                    M : Type u_4
                                                                    inst✝³ : Semiring R
                                                                    inst✝² : AddCommMonoid M
                                                                    inst✝¹ : Module R M
                                                                    inst✝ : DecidableEq M
                                                                    α : Type u_9
                                                                    s : Finset α
                                                                    f : (Subtype fun x => Membership.mem s x) → Finset M
                                                                    ⊢ Eq (Submodule.span R ↑(s.attach.biUnion f)) (iSup fun x => Submodule.span R  …
                                                                  -/
    span R (s.attach.biUnion f : Set M) = ⨆ x, span R (f x) := by simp [span_iUnion]
                                                                  /-
                                                                    🎉 no goals
                                                                  -/


                                                       /-
                                                         R : Type u_1
                                                         M : Type u_4
                                                         inst✝² : Semiring R
                                                         inst✝¹ : AddCommMonoid M
                                                         inst✝ : Module R M
                                                         p : Submodule R M
                                                         s : Set M
                                                         ⊢ Eq (Max.max p (Submodule.span R s)) (Submodule.span R (Union.union (↑p) s))
                                                       -/
theorem sup_span : p ⊔ span R s = span R (p ∪ s) := by rw [Submodule.span_union, p.span_eq]
                                                       /-
                                                         🎉 no goals
                                                       -/


                                                       /-
                                                         R : Type u_1
                                                         M : Type u_4
                                                         inst✝² : Semiring R
                                                         inst✝¹ : AddCommMonoid M
                                                         inst✝ : Module R M
                                                         p : Submodule R M
                                                         s : Set M
                                                         ⊢ Eq (Max.max (Submodule.span R s) p) (Submodule.span R (Union.union s ↑p))
                                                       -/
theorem span_sup : span R s ⊔ p = span R (s ∪ p) := by rw [Submodule.span_union, p.span_eq]
                                                       /-
                                                         🎉 no goals
                                                       -/


notation:1000
  /- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
R " ∙ " x => span R (singleton x)


theorem span_eq_iSup_of_singleton_spans (s : Set M) : span R s = ⨆ x ∈ s, R ∙ x := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    ⊢ Eq (Submodule.span R s) (iSup fun x => iSup fun h => Submodule.span R (Singl …
  -/
  simp only [← span_iUnion, Set.biUnion_of_singleton s]
  /-
    🎉 no goals
  -/


theorem span_range_eq_iSup {ι : Sort*} {v : ι → M} : span R (range v) = ⨆ i, R ∙ v i := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    ι : Sort u_9
    v : ι → M
    ⊢ Eq (Submodule.span R (Set.range v)) (iSup fun i => Submodule.span R (Singlet …
  -/
  rw [span_eq_iSup_of_singleton_spans, iSup_range]
  /-
    🎉 no goals
  -/


theorem span_smul_le (s : Set M) (r : R) : span R (r • s) ≤ span R s := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    r : R
    ⊢ LE.le (Submodule.span R (HSMul.hSMul r s)) (Submodule.span R s)
  -/
  rw [span_le]
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    r : R
    ⊢ HasSubset.Subset (HSMul.hSMul r s) ↑(Submodule.span R s)
  -/
  rintro _ ⟨x, hx, rfl⟩
  /-
    case intro.intro
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set M
    r : R
    x : M
    hx : Membership.mem s x
    ⊢ Membership.mem (↑(Submodule.span R s)) ((fun x => HSMul.hSMul r x) x)
  -/
  exact smul_mem (span R s) r (subset_span hx)
  /-
    🎉 no goals
  -/


theorem subset_span_trans {U V W : Set M} (hUV : U ⊆ Submodule.span R V)
    (hVW : V ⊆ Submodule.span R W) : U ⊆ Submodule.span R W :=
  (Submodule.gi R M).gc.le_u_l_trans hUV hVW


@[simp]
theorem coe_iSup_of_directed {ι} [Nonempty ι] (S : ι → Submodule R M)
    (H : Directed (· ≤ ·) S) : ((iSup S : Submodule R M) : Set M) = ⋃ i, S i :=
  let s : Submodule R M :=
    { __ := AddSubmonoid.copy _ _ (AddSubmonoid.coe_iSup_of_directed H).symm
      smul_mem' := fun r _ hx ↦ have ⟨i, hi⟩ := Set.mem_iUnion.mp hx
        Set.mem_iUnion.mpr ⟨i, (S i).smul_mem' r hi⟩ }
  have : iSup S = s := le_antisymm
    (iSup_le fun i ↦ le_iSup (fun i ↦ (S i : Set M)) i) (Set.iUnion_subset fun _ ↦ le_iSup S _)
  this.symm ▸ rfl


@[simp]
theorem mem_iSup_of_directed {ι} [Nonempty ι] (S : ι → Submodule R M) (H : Directed (· ≤ ·) S) {x} :
    x ∈ iSup S ↔ ∃ i, x ∈ S i := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝³ : Semiring R
    inst✝² : AddCommMonoid M
    inst✝¹ : Module R M
    ι : Sort u_9
    inst✝ : Nonempty ι
    S : ι → Submodule R M
    H : Directed (fun x1 x2 => LE.le x1 x2) S
    x : M
    ⊢ Iff (Membership.mem (iSup S) x) (Exists fun i => Membership.mem (S i) x)
  -/
  rw [← SetLike.mem_coe, coe_iSup_of_directed S H, mem_iUnion]
  /-
    R : Type u_1
    M : Type u_4
    inst✝³ : Semiring R
    inst✝² : AddCommMonoid M
    inst✝¹ : Module R M
    ι : Sort u_9
    inst✝ : Nonempty ι
    S : ι → Submodule R M
    H : Directed (fun x1 x2 => LE.le x1 x2) S
    x : M
    ⊢ Iff (Exists fun i => Membership.mem (↑(S i)) x) (Exists fun i => Membership. …
  -/
  rfl
  /-
    🎉 no goals
  -/


theorem mem_sSup_of_directed {s : Set (Submodule R M)} {z} (hs : s.Nonempty)
    (hdir : DirectedOn (· ≤ ·) s) : z ∈ sSup s ↔ ∃ y ∈ s, z ∈ y := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set (Submodule R M)
    z : M
    hs : s.Nonempty
    hdir : DirectedOn (fun x1 x2 => LE.le x1 x2) s
    ⊢ Iff (Membership.mem (SupSet.sSup s) z) (Exists fun y => And (Membership.mem  …
  -/
  have : Nonempty s := hs.to_subtype
  simp only [sSup_eq_iSup', mem_iSup_of_directed _ hdir.directed_val, SetCoe.exists, Subtype.coe_mk,
    exists_prop]


@[norm_cast, simp]
theorem coe_iSup_of_chain (a : ℕ →o Submodule R M) : (↑(⨆ k, a k) : Set M) = ⋃ k, (a k : Set M) :=
  coe_iSup_of_directed a a.monotone.directed_le


@[simp]
theorem mem_iSup_of_chain (a : ℕ →o Submodule R M) (m : M) : (m ∈ ⨆ k, a k) ↔ ∃ k, m ∈ a k :=
  mem_iSup_of_directed a a.monotone.directed_le


theorem mem_sup : x ∈ p ⊔ p' ↔ ∃ y ∈ p, ∃ z ∈ p', y + z = x :=
  ⟨fun h => by
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      p p' : Submodule R M
      h : Membership.mem (Max.max p p') x
      ⊢ Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membership.me …
    -/
    rw [← span_eq p, ← span_eq p', ← span_union] at h
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      p p' : Submodule R M
      h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
      ⊢ Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membership.me …
    -/
    refine span_induction ?_ ?_ ?_ ?_ h
      /-
        case refine_1
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x : M
        p p' : Submodule R M
        h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
        ⊢ ∀ (x : M), Membership.mem (Union.union ↑p ↑p') x → Exists fun y => And (Memb …
      -/
    · rintro y (h | h)
        /-
          case refine_1.inl
          R : Type u_1
          M : Type u_4
          inst✝² : Semiring R
          inst✝¹ : AddCommMonoid M
          inst✝ : Module R M
          x : M
          p p' : Submodule R M
          h✝ : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
          y : M
          h : Membership.mem (↑p) y
          ⊢ Exists fun y_1 => And (Membership.mem p y_1) (Exists fun z => And (Membershi …
        -/
      · exact ⟨y, h, 0, by simp, by simp⟩
        /-
          🎉 no goals
        -/
        /-
          case refine_1.inr
          R : Type u_1
          M : Type u_4
          inst✝² : Semiring R
          inst✝¹ : AddCommMonoid M
          inst✝ : Module R M
          x : M
          p p' : Submodule R M
          h✝ : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
          y : M
          h : Membership.mem (↑p') y
          ⊢ Exists fun y_1 => And (Membership.mem p y_1) (Exists fun z => And (Membershi …
        -/
      · exact ⟨0, by simp, y, h, by simp⟩
        /-
          🎉 no goals
        -/
      /-
        case refine_2
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x : M
        p p' : Submodule R M
        h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
        ⊢ Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membership.me …
      -/
    · exact ⟨0, by simp, 0, by simp⟩
      /-
        🎉 no goals
      -/
      /-
        case refine_3
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x : M
        p p' : Submodule R M
        h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
        ⊢ ∀ (x y : M), Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x → Memb …
      -/
    · rintro _ _ - - ⟨y₁, hy₁, z₁, hz₁, rfl⟩ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
      exact ⟨_, add_mem hy₁ hy₂, _, add_mem hz₁ hz₂, by
        rw [add_assoc, add_assoc, ← add_assoc y₂, ← add_assoc z₁, add_comm y₂]⟩
      /-
        case refine_4
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x : M
        p p' : Submodule R M
        h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
        ⊢ ∀ (a : R) (x : M), Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x  …
      -/
    · rintro a - _ ⟨y, hy, z, hz, rfl⟩
      /-
        case refine_4.intro.intro.intro.intro
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x : M
        p p' : Submodule R M
        h : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) x
        a : R
        y : M
        hy : Membership.mem p y
        z : M
        hz : Membership.mem p' z
        hx✝ : Membership.mem (Submodule.span R (Union.union ↑p ↑p')) (HAdd.hAdd y z)
        ⊢ Exists fun y_1 => And (Membership.mem p y_1) (Exists fun z_1 => And (Members …
      -/
      exact ⟨_, smul_mem _ a hy, _, smul_mem _ a hz, by simp [smul_add]⟩, by
      /-
        🎉 no goals
      -/
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      p p' : Submodule R M
      ⊢ (Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membership.m …
    -/
    rintro ⟨y, hy, z, hz, rfl⟩
    /-
      case intro.intro.intro.intro
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p p' : Submodule R M
      y : M
      hy : Membership.mem p y
      z : M
      hz : Membership.mem p' z
      ⊢ Membership.mem (Max.max p p') (HAdd.hAdd y z)
    -/
    exact add_mem ((le_sup_left : p ≤ p ⊔ p') hy) ((le_sup_right : p' ≤ p ⊔ p') hz)⟩
    /-
      🎉 no goals
    -/


theorem mem_sup' : x ∈ p ⊔ p' ↔ ∃ (y : p) (z : p'), (y : M) + z = x :=
                      /-
                        R : Type u_1
                        M : Type u_4
                        inst✝² : Semiring R
                        inst✝¹ : AddCommMonoid M
                        inst✝ : Module R M
                        x : M
                        p p' : Submodule R M
                        ⊢ Iff (Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membersh …
                      -/
  mem_sup.trans <| by simp only [Subtype.exists, exists_prop]
                      /-
                        🎉 no goals
                      -/


lemma exists_add_eq_of_codisjoint (h : Codisjoint p p') (x : M) :
    ∃ y ∈ p, ∃ z ∈ p', y + z = x := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    h : Codisjoint p p'
    x : M
    ⊢ Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membership.me …
  -/
  suffices x ∈ p ⊔ p' by exact Submodule.mem_sup.mp this
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    h : Codisjoint p p'
    x : M
    ⊢ Membership.mem (Max.max p p') x
  -/
  simpa only [h.eq_top] using Submodule.mem_top
  /-
    🎉 no goals
  -/


theorem coe_sup : ↑(p ⊔ p') = (p + p' : Set M) := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    ⊢ Eq (↑(Max.max p p')) (HAdd.hAdd ↑p ↑p')
  -/
  ext
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    x✝ : M
    ⊢ Iff (Membership.mem (↑(Max.max p p')) x✝) (Membership.mem (HAdd.hAdd ↑p ↑p') …
  -/
  rw [SetLike.mem_coe, mem_sup, Set.mem_add]
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    x✝ : M
    ⊢ Iff (Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membersh …
  -/
  simp
  /-
    🎉 no goals
  -/


theorem sup_toAddSubmonoid : (p ⊔ p').toAddSubmonoid = p.toAddSubmonoid ⊔ p'.toAddSubmonoid := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    ⊢ Eq (Max.max p p').toAddSubmonoid (Max.max p.toAddSubmonoid p'.toAddSubmonoid)
  -/
  ext x
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    x : M
    ⊢ Iff (Membership.mem (Max.max p p').toAddSubmonoid x) (Membership.mem (Max.ma …
  -/
  rw [mem_toAddSubmonoid, mem_sup, AddSubmonoid.mem_sup]
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p p' : Submodule R M
    x : M
    ⊢ Iff (Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membersh …
  -/
  rfl
  /-
    🎉 no goals
  -/


theorem mem_span_singleton_self (x : M) : x ∈ R ∙ x :=
  subset_span rfl


theorem nontrivial_span_singleton {x : M} (h : x ≠ 0) : Nontrivial (R ∙ x) :=
  ⟨by
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      h : Ne x 0
      ⊢ Exists fun x_1 => Exists fun y => Ne x_1 y
    -/
    use 0, ⟨x, Submodule.mem_span_singleton_self x⟩
    /-
      case h
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      h : Ne x 0
      ⊢ Ne 0 ⟨x, ⋯⟩
    -/
    intro H
    /-
      case h
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      h : Ne x 0
      H : Eq 0 ⟨x, ⋯⟩
      ⊢ False
    -/
    rw [eq_comm, Submodule.mk_eq_zero] at H
    /-
      case h
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x : M
      h : Ne x 0
      H : Eq x 0
      ⊢ False
    -/
    exact h H⟩
    /-
      🎉 no goals
    -/


theorem mem_span_singleton {y : M} : (x ∈ R ∙ y) ↔ ∃ a : R, a • y = x :=
  ⟨fun h => by
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x y : M
      h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
      ⊢ Exists fun a => Eq (HSMul.hSMul a y) x
    -/
    refine span_induction ?_ ?_ ?_ ?_ h
      /-
        case refine_1
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        ⊢ ∀ (x : M), Membership.mem (Singleton.singleton y) x → Exists fun a => Eq (HS …
      -/
    · rintro y (rfl | ⟨⟨_⟩⟩)
      /-
        case refine_1.refl
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        ⊢ Exists fun a => Eq (HSMul.hSMul a y) y
      -/
      exact ⟨1, by simp⟩
      /-
        🎉 no goals
      -/
      /-
        case refine_2
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        ⊢ Exists fun a => Eq (HSMul.hSMul a y) 0
      -/
    · exact ⟨0, by simp⟩
      /-
        🎉 no goals
      -/
      /-
        case refine_3
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        ⊢ ∀ (x y_1 : M), Membership.mem (Submodule.span R (Singleton.singleton y)) x → …
      -/
    · rintro _ _ - - ⟨a, rfl⟩ ⟨b, rfl⟩
      /-
        case refine_3.intro.intro
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        a b : R
        ⊢ Exists fun a_1 => Eq (HSMul.hSMul a_1 y) (HAdd.hAdd (HSMul.hSMul a y) (HSMul …
      -/
      exact ⟨a + b, by simp [add_smul]⟩
      /-
        🎉 no goals
      -/
      /-
        case refine_4
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        ⊢ ∀ (a : R) (x : M), Membership.mem (Submodule.span R (Singleton.singleton y)) …
      -/
    · rintro a _ - ⟨b, rfl⟩
      /-
        case refine_4.intro
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        x y : M
        h : Membership.mem (Submodule.span R (Singleton.singleton y)) x
        a b : R
        ⊢ Exists fun a_1 => Eq (HSMul.hSMul a_1 y) (HSMul.hSMul a (HSMul.hSMul b y))
      -/
      exact ⟨a * b, by simp [smul_smul]⟩, by
      /-
        🎉 no goals
      -/
    /-
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      x y : M
      ⊢ (Exists fun a => Eq (HSMul.hSMul a y) x) → Membership.mem (Submodule.span R  …
    -/
    rintro ⟨a, y, rfl⟩; exact smul_mem _ _ (subset_span <| by simp)⟩
                        /-
                          🎉 no goals
                        -/


theorem le_span_singleton_iff {s : Submodule R M} {v₀ : M} :
                                                      /-
                                                        R : Type u_1
                                                        M : Type u_4
                                                        inst✝² : Semiring R
                                                        inst✝¹ : AddCommMonoid M
                                                        inst✝ : Module R M
                                                        s : Submodule R M
                                                        v₀ : M
                                                        ⊢ Iff (LE.le s (Submodule.span R (Singleton.singleton v₀))) (∀ (v : M), Member …
                                                      -/
    (s ≤ R ∙ v₀) ↔ ∀ v ∈ s, ∃ r : R, r • v₀ = v := by simp_rw [SetLike.le_def, mem_span_singleton]
                                                      /-
                                                        🎉 no goals
                                                      -/


theorem span_singleton_eq_top_iff (x : M) : (R ∙ x) = ⊤ ↔ ∀ v, ∃ r : R, r • x = v := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    ⊢ Iff (Eq (Submodule.span R (Singleton.singleton x)) Top.top) (∀ (v : M), Exis …
  -/
  rw [eq_top_iff, le_span_singleton_iff]
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    ⊢ Iff (∀ (v : M), Membership.mem Top.top v → Exists fun r => Eq (HSMul.hSMul r …
  -/
  tauto
  /-
    🎉 no goals
  -/


@[simp]
theorem span_zero_singleton : (R ∙ (0 : M)) = ⊥ := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    ⊢ Eq (Submodule.span R (Singleton.singleton 0)) Bot.bot
  -/
  ext
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x✝ : M
    ⊢ Iff (Membership.mem (Submodule.span R (Singleton.singleton 0)) x✝) (Membersh …
  -/
  simp [mem_span_singleton, eq_comm]
  /-
    🎉 no goals
  -/


theorem span_singleton_eq_range (y : M) : ↑(R ∙ y) = range ((· • y) : R → M) :=
  Set.ext fun _ => mem_span_singleton


theorem span_singleton_smul_le {S} [Monoid S] [SMul S R] [MulAction S M] [IsScalarTower S R M]
    (r : S) (x : M) : (R ∙ r • x) ≤ R ∙ x := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝⁶ : Semiring R
    inst✝⁵ : AddCommMonoid M
    inst✝⁴ : Module R M
    S : Type u_9
    inst✝³ : Monoid S
    inst✝² : SMul S R
    inst✝¹ : MulAction S M
    inst✝ : IsScalarTower S R M
    r : S
    x : M
    ⊢ LE.le (Submodule.span R (Singleton.singleton (HSMul.hSMul r x))) (Submodule. …
  -/
  rw [span_le, Set.singleton_subset_iff, SetLike.mem_coe]
  /-
    R : Type u_1
    M : Type u_4
    inst✝⁶ : Semiring R
    inst✝⁵ : AddCommMonoid M
    inst✝⁴ : Module R M
    S : Type u_9
    inst✝³ : Monoid S
    inst✝² : SMul S R
    inst✝¹ : MulAction S M
    inst✝ : IsScalarTower S R M
    r : S
    x : M
    ⊢ Membership.mem (Submodule.span R (Singleton.singleton x)) (HSMul.hSMul r x)
  -/
  exact smul_of_tower_mem _ _ (mem_span_singleton_self _)
  /-
    🎉 no goals
  -/


theorem span_singleton_group_smul_eq {G} [Group G] [SMul G R] [MulAction G M] [IsScalarTower G R M]
    (g : G) (x : M) : (R ∙ g • x) = R ∙ x := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝⁶ : Semiring R
    inst✝⁵ : AddCommMonoid M
    inst✝⁴ : Module R M
    G : Type u_9
    inst✝³ : Group G
    inst✝² : SMul G R
    inst✝¹ : MulAction G M
    inst✝ : IsScalarTower G R M
    g : G
    x : M
    ⊢ Eq (Submodule.span R (Singleton.singleton (HSMul.hSMul g x))) (Submodule.spa …
  -/
  refine le_antisymm (span_singleton_smul_le R g x) ?_
  /-
    R : Type u_1
    M : Type u_4
    inst✝⁶ : Semiring R
    inst✝⁵ : AddCommMonoid M
    inst✝⁴ : Module R M
    G : Type u_9
    inst✝³ : Group G
    inst✝² : SMul G R
    inst✝¹ : MulAction G M
    inst✝ : IsScalarTower G R M
    g : G
    x : M
    ⊢ LE.le (Submodule.span R (Singleton.singleton x)) (Submodule.span R (Singleto …
  -/
  convert span_singleton_smul_le R g⁻¹ (g • x)
  /-
    case h.e'_3.h.e'_6.h.e'_4
    R : Type u_1
    M : Type u_4
    inst✝⁶ : Semiring R
    inst✝⁵ : AddCommMonoid M
    inst✝⁴ : Module R M
    G : Type u_9
    inst✝³ : Group G
    inst✝² : SMul G R
    inst✝¹ : MulAction G M
    inst✝ : IsScalarTower G R M
    g : G
    x : M
    ⊢ Eq x (HSMul.hSMul (Inv.inv g) (HSMul.hSMul g x))
  -/
  exact (inv_smul_smul g x).symm
  /-
    🎉 no goals
  -/


theorem span_singleton_smul_eq {r : R} (hr : IsUnit r) (x : M) : (R ∙ r • x) = R ∙ x := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    r : R
    hr : IsUnit r
    x : M
    ⊢ Eq (Submodule.span R (Singleton.singleton (HSMul.hSMul r x))) (Submodule.spa …
  -/
  lift r to Rˣ using hr
  /-
    case intro
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    r : Units R
    ⊢ Eq (Submodule.span R (Singleton.singleton (HSMul.hSMul (↑r) x))) (Submodule. …
  -/
  rw [← Units.smul_def]
  /-
    case intro
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    r : Units R
    ⊢ Eq (Submodule.span R (Singleton.singleton (HSMul.hSMul r x))) (Submodule.spa …
  -/
  exact span_singleton_group_smul_eq R r x
  /-
    🎉 no goals
  -/


theorem mem_span_singleton_trans {x y z : M} (hxy : x ∈ R ∙ y) (hyz : y ∈ R ∙ z) : x ∈ R ∙ z := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x y z : M
    hxy : Membership.mem (Submodule.span R (Singleton.singleton y)) x
    hyz : Membership.mem (Submodule.span R (Singleton.singleton z)) y
    ⊢ Membership.mem (Submodule.span R (Singleton.singleton z)) x
  -/
  rw [← SetLike.mem_coe, ← singleton_subset_iff] at *
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x y z : M
    hxy : HasSubset.Subset (Singleton.singleton x) ↑(Submodule.span R (Singleton.s …
    hyz : HasSubset.Subset (Singleton.singleton y) ↑(Submodule.span R (Singleton.s …
    ⊢ HasSubset.Subset (Singleton.singleton x) ↑(Submodule.span R (Singleton.singl …
  -/
  exact Submodule.subset_span_trans hxy hyz
  /-
    🎉 no goals
  -/


theorem span_insert (x) (s : Set M) : span R (insert x s) = (R ∙ x) ⊔ span R s := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    s : Set M
    ⊢ Eq (Submodule.span R (Insert.insert x s)) (Max.max (Submodule.span R (Single …
  -/
  rw [insert_eq, span_union]
  /-
    🎉 no goals
  -/


theorem span_insert_eq_span (h : x ∈ span R s) : span R (insert x s) = span R s :=
  span_eq_of_le _ (Set.insert_subset_iff.mpr ⟨h, subset_span⟩) (span_mono <| subset_insert _ _)


theorem span_span : span R (span R s : Set M) = span R s :=
  span_eq _


theorem mem_span_insert {y} :
    x ∈ span R (insert y s) ↔ ∃ a : R, ∃ z ∈ span R s, x = a • y + z := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x : M
    s : Set M
    y : M
    ⊢ Iff (Membership.mem (Submodule.span R (Insert.insert y s)) x) (Exists fun a  …
  -/
  simp [span_insert, mem_sup, mem_span_singleton, eq_comm (a := x)]
  /-
    🎉 no goals
  -/


theorem mem_span_pair {x y z : M} :
    z ∈ span R ({x, y} : Set M) ↔ ∃ a b : R, a • x + b • y = z := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    x y z : M
    ⊢ Iff (Membership.mem (Submodule.span R (Insert.insert x (Singleton.singleton  …
  -/
  simp_rw [mem_span_insert, mem_span_singleton, exists_exists_eq_and, eq_comm]
  /-
    🎉 no goals
  -/


theorem span_eq_bot : span R (s : Set M) = ⊥ ↔ ∀ x ∈ s, (x : M) = 0 :=
  eq_bot_iff.trans
    ⟨fun H _ h => (mem_bot R).1 <| H <| subset_span h, fun H =>
      span_le.2 fun x h => (mem_bot R).2 <| H x h⟩


@[simp]
theorem span_singleton_eq_bot : (R ∙ x) = ⊥ ↔ x = 0 :=
                          /-
                            R : Type u_1
                            M : Type u_4
                            inst✝² : Semiring R
                            inst✝¹ : AddCommMonoid M
                            inst✝ : Module R M
                            x : M
                            ⊢ Iff (∀ (x_1 : M), Membership.mem (Singleton.singleton x) x_1 → Eq x_1 0) (Eq …
                          -/
  span_eq_bot.trans <| by simp
                          /-
                            🎉 no goals
                          -/


@[simp]
                                                 /-
                                                   R : Type u_1
                                                   M : Type u_4
                                                   inst✝² : Semiring R
                                                   inst✝¹ : AddCommMonoid M
                                                   inst✝ : Module R M
                                                   ⊢ Eq (Submodule.span R 0) Bot.bot
                                                 -/
theorem span_zero : span R (0 : Set M) = ⊥ := by rw [← singleton_zero, span_singleton_eq_bot]
                                                 /-
                                                   🎉 no goals
                                                 -/


@[simp]
theorem span_singleton_le_iff_mem (m : M) (p : Submodule R M) : (R ∙ m) ≤ p ↔ m ∈ p := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    m : M
    p : Submodule R M
    ⊢ Iff (LE.le (Submodule.span R (Singleton.singleton m)) p) (Membership.mem p m)
  -/
  rw [span_le, singleton_subset_iff, SetLike.mem_coe]
  /-
    🎉 no goals
  -/


theorem iSup_span {ι : Sort*} (p : ι → Set M) : ⨆ i, span R (p i) = span R (⋃ i, p i) :=
  le_antisymm (iSup_le fun i => span_mono <| subset_iUnion _ i) <|
    span_le.mpr <| iUnion_subset fun i _ hm => mem_iSup_of_mem i <| subset_span hm


theorem iSup_eq_span {ι : Sort*} (p : ι → Submodule R M) : ⨆ i, p i = span R (⋃ i, ↑(p i)) := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    ι : Sort u_9
    p : ι → Submodule R M
    ⊢ Eq (iSup fun i => p i) (Submodule.span R (Set.iUnion fun i => ↑(p i)))
  -/
  simp_rw [← iSup_span, span_eq]
  /-
    🎉 no goals
  -/


/-- A submodule is equal to the supremum of the spans of the submodule's nonzero elements. -/
theorem submodule_eq_sSup_le_nonzero_spans (p : Submodule R M) :
    p = sSup { T : Submodule R M | ∃ m ∈ p, m ≠ 0 ∧ T = span R {m} } := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p : Submodule R M
    ⊢ Eq p (SupSet.sSup (setOf fun T => Exists fun m => And (Membership.mem p m) ( …
  -/
  let S := { T : Submodule R M | ∃ m ∈ p, m ≠ 0 ∧ T = span R {m} }
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    p : Submodule R M
    S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
    ⊢ Eq p (SupSet.sSup (setOf fun T => Exists fun m => And (Membership.mem p m) ( …
  -/
  apply le_antisymm
    /-
      case a
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p : Submodule R M
      S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
      ⊢ LE.le p (SupSet.sSup (setOf fun T => Exists fun m => And (Membership.mem p m …
    -/
  · intro m hm
    /-
      case a
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p : Submodule R M
      S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
      m : M
      hm : Membership.mem p m
      ⊢ Membership.mem (SupSet.sSup (setOf fun T => Exists fun m => And (Membership. …
    -/
    by_cases h : m = 0
      /-
        case pos
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        p : Submodule R M
        S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
        m : M
        hm : Membership.mem p m
        h : Eq m 0
        ⊢ Membership.mem (SupSet.sSup (setOf fun T => Exists fun m => And (Membership. …
      -/
    · rw [h]
      /-
        case pos
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        p : Submodule R M
        S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
        m : M
        hm : Membership.mem p m
        h : Eq m 0
        ⊢ Membership.mem (SupSet.sSup (setOf fun T => Exists fun m => And (Membership. …
      -/
      simp
      /-
        🎉 no goals
      -/
      /-
        case neg
        R : Type u_1
        M : Type u_4
        inst✝² : Semiring R
        inst✝¹ : AddCommMonoid M
        inst✝ : Module R M
        p : Submodule R M
        S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
        m : M
        hm : Membership.mem p m
        h : Not (Eq m 0)
        ⊢ Membership.mem (SupSet.sSup (setOf fun T => Exists fun m => And (Membership. …
      -/
    · exact @le_sSup _ _ S _ ⟨m, ⟨hm, ⟨h, rfl⟩⟩⟩ m (mem_span_singleton_self m)
      /-
        🎉 no goals
      -/
    /-
      case a
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p : Submodule R M
      S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
      ⊢ LE.le (SupSet.sSup (setOf fun T => Exists fun m => And (Membership.mem p m)  …
    -/
  · rw [sSup_le_iff]
    /-
      case a
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p : Submodule R M
      S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
      ⊢ ∀ (b : Submodule R M), Membership.mem (setOf fun T => Exists fun m => And (M …
    -/
    rintro S ⟨_, ⟨_, ⟨_, rfl⟩⟩⟩
    /-
      case a.intro.intro.intro
      R : Type u_1
      M : Type u_4
      inst✝² : Semiring R
      inst✝¹ : AddCommMonoid M
      inst✝ : Module R M
      p : Submodule R M
      S : Set (Submodule R M) := setOf fun T => Exists fun m => And (Membership.mem  …
      w✝ : M
      left✝¹ : Membership.mem p w✝
      left✝ : Ne w✝ 0
      ⊢ LE.le (Submodule.span R (Singleton.singleton w✝)) p
    -/
    rwa [span_singleton_le_iff_mem]
    /-
      🎉 no goals
    -/


                                                                                       /-
                                                                                         R : Type u_1
                                                                                         M : Type u_4
                                                                                         inst✝² : Semiring R
                                                                                         inst✝¹ : AddCommMonoid M
                                                                                         inst✝ : Module R M
                                                                                         I : Submodule R M
                                                                                         a : M
                                                                                         ⊢ Iff (LT.lt I (Max.max I (Submodule.span R (Singleton.singleton a)))) (Not (M …
                                                                                       -/
theorem lt_sup_iff_not_mem {I : Submodule R M} {a : M} : (I < I ⊔ R ∙ a) ↔ a ∉ I := by simp
                                                                                       /-
                                                                                         🎉 no goals
                                                                                       -/


theorem mem_iSup {ι : Sort*} (p : ι → Submodule R M) {m : M} :
    (m ∈ ⨆ i, p i) ↔ ∀ N, (∀ i, p i ≤ N) → m ∈ N := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    ι : Sort u_9
    p : ι → Submodule R M
    m : M
    ⊢ Iff (Membership.mem (iSup fun i => p i) m) (∀ (N : Submodule R M), (∀ (i : ι …
  -/
  rw [← span_singleton_le_iff_mem, le_iSup_iff]
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    ι : Sort u_9
    p : ι → Submodule R M
    m : M
    ⊢ Iff (∀ (b : Submodule R M), (∀ (i : ι), LE.le (p i) b) → LE.le (Submodule.sp …
  -/
  simp only [span_singleton_le_iff_mem]
  /-
    🎉 no goals
  -/


theorem mem_sSup {s : Set (Submodule R M)} {m : M} :
    (m ∈ sSup s) ↔ ∀ N, (∀ p ∈ s, p ≤ N) → m ∈ N := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Semiring R
    inst✝¹ : AddCommMonoid M
    inst✝ : Module R M
    s : Set (Submodule R M)
    m : M
    ⊢ Iff (Membership.mem (SupSet.sSup s) m) (∀ (N : Submodule R M), (∀ (p : Submo …
  -/
  simp_rw [sSup_eq_iSup, Submodule.mem_iSup, iSup_le_iff]
  /-
    🎉 no goals
  -/


/-- For every element in the span of a set, there exists a finite subset of the set
such that the element is contained in the span of the subset. -/
theorem mem_span_finite_of_mem_span {S : Set M} {x : M} (hx : x ∈ span R S) :
    ∃ T : Finset M, ↑T ⊆ S ∧ x ∈ span R (T : Set M) := by
  classical
  refine span_induction (fun x hx => ?_) ?_ ?_ ?_ hx
  · refine ⟨{x}, ?_, ?_⟩
    · rwa [Finset.coe_singleton, Set.singleton_subset_iff]
    · rw [Finset.coe_singleton]
      exact Submodule.mem_span_singleton_self x
  · use ∅
    simp
  · rintro x y - - ⟨X, hX, hxX⟩ ⟨Y, hY, hyY⟩
    refine ⟨X ∪ Y, ?_, ?_⟩
    · rw [Finset.coe_union]
      exact Set.union_subset hX hY
    rw [Finset.coe_union, span_union, mem_sup]
    exact ⟨x, hxX, y, hyY, rfl⟩
  · rintro a x - ⟨T, hT, h2⟩
    exact ⟨T, hT, smul_mem _ _ h2⟩


lemma sup_toAddSubgroup (p p' : Submodule R M) :
    (p ⊔ p').toAddSubgroup = p.toAddSubgroup ⊔ p'.toAddSubgroup := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Ring R
    inst✝¹ : AddCommGroup M
    inst✝ : Module R M
    p p' : Submodule R M
    ⊢ Eq (Max.max p p').toAddSubgroup (Max.max p.toAddSubgroup p'.toAddSubgroup)
  -/
  ext x
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Ring R
    inst✝¹ : AddCommGroup M
    inst✝ : Module R M
    p p' : Submodule R M
    x : M
    ⊢ Iff (Membership.mem (Max.max p p').toAddSubgroup x) (Membership.mem (Max.max …
  -/
  rw [mem_toAddSubgroup, mem_sup, AddSubgroup.mem_sup]
  /-
    case h
    R : Type u_1
    M : Type u_4
    inst✝² : Ring R
    inst✝¹ : AddCommGroup M
    inst✝ : Module R M
    p p' : Submodule R M
    x : M
    ⊢ Iff (Exists fun y => And (Membership.mem p y) (Exists fun z => And (Membersh …
  -/
  rfl
  /-
    🎉 no goals
  -/


theorem mem_span_insert' {x y} {s : Set M} :
    x ∈ span R (insert y s) ↔ ∃ a : R, x + a • y ∈ span R s := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝² : Ring R
    inst✝¹ : AddCommGroup M
    inst✝ : Module R M
    x y : M
    s : Set M
    ⊢ Iff (Membership.mem (Submodule.span R (Insert.insert y s)) x) (Exists fun a  …
  -/
  rw [mem_span_insert]; constructor
    /-
      case mp
      R : Type u_1
      M : Type u_4
      inst✝² : Ring R
      inst✝¹ : AddCommGroup M
      inst✝ : Module R M
      x y : M
      s : Set M
      ⊢ (Exists fun a => Exists fun z => And (Membership.mem (Submodule.span R s) z) …
    -/
  · rintro ⟨a, z, hz, rfl⟩
    /-
      case mp.intro.intro.intro
      R : Type u_1
      M : Type u_4
      inst✝² : Ring R
      inst✝¹ : AddCommGroup M
      inst✝ : Module R M
      y : M
      s : Set M
      a : R
      z : M
      hz : Membership.mem (Submodule.span R s) z
      ⊢ Exists fun a_1 => Membership.mem (Submodule.span R s) (HAdd.hAdd (HAdd.hAdd  …
    -/
    exact ⟨-a, by simp [hz, add_assoc]⟩
    /-
      🎉 no goals
    -/
    /-
      case mpr
      R : Type u_1
      M : Type u_4
      inst✝² : Ring R
      inst✝¹ : AddCommGroup M
      inst✝ : Module R M
      x y : M
      s : Set M
      ⊢ (Exists fun a => Membership.mem (Submodule.span R s) (HAdd.hAdd x (HSMul.hSM …
    -/
  · rintro ⟨a, h⟩
    /-
      case mpr.intro
      R : Type u_1
      M : Type u_4
      inst✝² : Ring R
      inst✝¹ : AddCommGroup M
      inst✝ : Module R M
      x y : M
      s : Set M
      a : R
      h : Membership.mem (Submodule.span R s) (HAdd.hAdd x (HSMul.hSMul a y))
      ⊢ Exists fun a => Exists fun z => And (Membership.mem (Submodule.span R s) z)  …
    -/
    exact ⟨-a, _, h, by simp [add_comm, add_left_comm]⟩
    /-
      🎉 no goals
    -/


lemma span_range_update_add_smul (hij : i ≠ j) (v : ι → M) (r : R) :
    span R (Set.range (Function.update v j (v j + r • v i))) = span R (Set.range v) := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝³ : Ring R
    inst✝² : AddCommGroup M
    inst✝¹ : Module R M
    ι : Type u_8
    inst✝ : DecidableEq ι
    i j : ι
    hij : Ne i j
    v : ι → M
    r : R
    ⊢ Eq (Submodule.span R (Set.range (Function.update v j (HAdd.hAdd (v j) (HSMul …
  -/
  refine le_antisymm ?_ ?_ <;> simp only [span_le, Set.range_subset_iff, SetLike.mem_coe] <;>
    /-
      case refine_1
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      ⊢ ∀ (y : ι), Membership.mem (Submodule.span R (Set.range v)) (Function.update  …
    -/
    intro k <;> obtain rfl | hjk := eq_or_ne j k
    /-
      case refine_1.inl
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      ⊢ Membership.mem (Submodule.span R (Set.range v)) (Function.update v j (HAdd.h …
    -/
  · rw [update_self]
    /-
      case refine_1.inl
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      ⊢ Membership.mem (Submodule.span R (Set.range v)) (HAdd.hAdd (v j) (HSMul.hSMu …
    -/
    exact add_mem (subset_span ⟨j, rfl⟩) <| smul_mem _ _ <| subset_span ⟨i, rfl⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_1.inr
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      k : ι
      hjk : Ne j k
      ⊢ Membership.mem (Submodule.span R (Set.range v)) (Function.update v j (HAdd.h …
    -/
  · exact subset_span ⟨k, (update_of_ne hjk.symm ..).symm⟩
    /-
      🎉 no goals
    -/
    /-
      case refine_2.inl
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      ⊢ Membership.mem (Submodule.span R (Set.range (Function.update v j (HAdd.hAdd  …
    -/
  · nth_rw 2 [← add_sub_cancel_right (v j) (r • v i)]
    exact sub_mem (subset_span ⟨j, update_self ..⟩)
      (smul_mem _ _ (subset_span ⟨i, update_of_ne hij ..⟩))
    /-
      case refine_2.inr
      R : Type u_1
      M : Type u_4
      inst✝³ : Ring R
      inst✝² : AddCommGroup M
      inst✝¹ : Module R M
      ι : Type u_8
      inst✝ : DecidableEq ι
      i j : ι
      hij : Ne i j
      v : ι → M
      r : R
      k : ι
      hjk : Ne j k
      ⊢ Membership.mem (Submodule.span R (Set.range (Function.update v j (HAdd.hAdd  …
    -/
  · exact subset_span ⟨k, update_of_ne hjk.symm ..⟩
    /-
      🎉 no goals
    -/


lemma span_range_update_sub_smul (hij : i ≠ j) (v : ι → M) (r : R) :
    span R (Set.range (Function.update v j (v j - r • v i))) = span R (Set.range v) := by
  /-
    R : Type u_1
    M : Type u_4
    inst✝³ : Ring R
    inst✝² : AddCommGroup M
    inst✝¹ : Module R M
    ι : Type u_8
    inst✝ : DecidableEq ι
    i j : ι
    hij : Ne i j
    v : ι → M
    r : R
    ⊢ Eq (Submodule.span R (Set.range (Function.update v j (HSub.hSub (v j) (HSMul …
  -/
  rw [sub_eq_add_neg, ← neg_smul, span_range_update_add_smul hij]
  /-
    🎉 no goals
  -/


